### ISSUE TITLE
[Question] Is it possible to make floating label float when setting input value programmatically?

### ISSUE THREAD

**Issue by deastr** [mdbootstrap/mdb-ui-kit#1000]
Hello. I'm using bootstrap-material-design on our Angular 2 project and we use two-way model binding. When the model bound input floating label doesn't float, stays at the start position (div has "is-empty" class). The same behaviour can be seen when you set value using Javascript. Example: [http://codepen.io/anon/pen/wGNEBm](http://codepen.io/anon/pen/wGNEBm)

Is it possible to make the floating label float when the input value is set?

**Comment by rosskevin** [comment]
Trigger the change event.
