### ISSUE TITLE
V4: promotion/release to master + v3 maintenance branch

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#1004]
We have been discussing a release of v4 because it seems very stable (even more so than the current master), yet the only concern being that we are on the _tip_ of the BS4 `master`.

v3 has been stable but is not being actively developed.  BS v3 has also switched to critical bug fixes only so we should be getting near BS4 stability.

The v4 build is setup to one-step publish, we just need to enable it. We are in a position to release v4 as frequently as necessary, which would allow users to pick their stable version (meaning that the latest version may _not always_ be incrementally better).  Nonetheless, users would have bower tags and npm versions to lock onto if necessary.

@FezVrasta and I are in favor of incremental publishing of v4 and promoting it to `master`.  

With that said, we **really** need some others to step up and pitch in to maintaining.  @FezVrasta and I have other priorities right now and we will need additional maintainers to step up.  I a have to move on to other projects.  If you are interested in becoming a major contributor, please contact @FezVrasta.

Here is the proposed procedure:
- [x] #1045 resolve build issue with bootsrap js (expected in alpha.4)
- [x] #1003 babel-polyfill (expected as resolved but cannot test without #1045)
- [x] add a "past releases link" in the v4 docs that shows the v3 pages
- [x] @FezVrasta update the readme
- [x] @FezVrasta  - give the v4 docs homepage some love
- [x] close _all_ v3 issues with a message that states issue is archived; PR's accepted but maintainers aren't accepting additional issues without PRs, and refer to this issue.
- [ ] merge v4 to master
- [ ] branch `v3-maintenance` - permanant maintenance branch
- [ ] ?? - publish as often as needed
## Tracking issues

Use this link to filter the issues and see only the ones related to our V4 implementation:
https://github.com/FezVrasta/bootstrap-material-design/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20-label%3Av3%20
## What I need from you:
- If you agree with this, just 👍  with the github reactions (not a new message)
- If you agree generally, 👍  with the github reactions and comment with your unique additions/objections
- If you disagree, please 👎  with github reactions, and if not already mentioned, comment with your unique objection.

**Comment by nhomar** [comment]
addition/objection: You should manage this change in something like 2 or 3 months, and release parallely with bootstrap 4 officially. (syncronize the relase I mean).

Following this: http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

**Comment by mgmiles** [comment]
> @FezVrasta and I have other priorities right now and we will need additional maintainers to step up. I am here for this last hurrah, then I'll probably be absent for at least a while.

And I guess if nobody does, and so far it appears that nobody has, then this project slowly withers away.Sad, but these things happen here all the time.

**Comment by rosskevin** [comment]
#1003 is a blocker to this plan.  With babel-polyfill not being rolled-up properly, cross-browser support is broken.

**Comment by cybersharky** [comment]
In my experience with v4, I'd say it's ready, if only tabs were added.

**Comment by rosskevin** [comment]
Tabs are implemented.

http://rosskevin.github.io/bootstrap-material-design/components/navs/#tabs

**Comment by cybersharky** [comment]
Ok, good, I finally got it working.

**Comment by lorvent** [comment]
alpha 3 is close to release

i hope you guys are ready for it :smile:

**Comment by FezVrasta** [comment]
It's taking ages :(

**Comment by lorvent** [comment]
yes :cry: ...but for last 2days they moved all issues into alpha 4 so there is only one issue in alpha 3 and i am guessing they may release it today.

**Comment by lorvent** [comment]
finally released and they overhauled sass variables, so i hope you will do necessary changes

**Comment by rosskevin** [comment]
Blocked by #1045

**Comment by FezVrasta** [comment]
@rosskevin how would you proceed with the following point?

> add a "past releases link" in the v4 docs that shows the v3 pages

Should we include the v3 page inside the jekyll site of the v4 or is there a way to link to an older version of the gh-pages?
Maybe we could fork the v3 repository to `bootstrap-material-design-v3` and pubblish there the old gh-page?

**Comment by FezVrasta** [comment]
I have worked on the gh-page to give it some custom style, this is the result so far:

![image](https://cloud.githubusercontent.com/assets/5382443/17295159/208befce-57fb-11e6-84f4-4d0ebda1e5ed.png)

I'm keeping as base the BS website to avoid to write a lot of custom stuff hard to maintain.

**Comment by FezVrasta** [comment]
About the doc, I can't find anymore the sass files of the documentation inside the `docs/assets` folder... Am I missing something? @rosskevin

**Comment by rosskevin** [comment]
I think you need to fork a permanent v3 branch anyway, so you could just include the html pages in the new release (on gh-pages tip) and have them load the dist from the v3 maintenance branch.

**Comment by FezVrasta** [comment]
Do you mean to load the old page with something like rawgit from the v3 branch?

**Comment by FezVrasta** [comment]
Ok well maybe we could just keep a `gh-pages-v3` branch and link to it in this way:

https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/gh-pages-v3/index.html

Seems like the easiest way.

**Comment by FezVrasta** [comment]
@lorvent may you point me to the variables changes they did or test the latest `v4-dev` and let me know if there's something we should fix? Thanks!

**Comment by FezVrasta** [comment]
The problem with the missing BS source files has been fixed, nothing is blocking our release anymore :tada:.

Now I guess we have just to wait for the official BS release to release our code... Do we want to wait for the final release or it could be good enough wait for the first beta or the first RC?

**Comment by lorvent** [comment]
Since they are releasing new versions slowly, its better you release along with them.

i.e. as they released alpha-3, you also please release alpha 3

notably they changed something in it like labels to tags.

**Comment by iqbalaqaba** [comment]
Maybe restyling the navigation with side-nav system on mobile devices just to make it more _materialized_ ?

**Comment by FezVrasta** [comment]
@iqbalaqaba may you open a dedicated issue with more details? Thanks

**Comment by iqbalaqaba** [comment]
@FezVrasta i can give you some example if you want it to, and  Its not a issue, just suggestion for the next feature style :smile:

**Comment by FezVrasta** [comment]
Yes I'm asking for an "issue/ticket" just to make it easier to track it.

**Comment by iqbalaqaba** [comment]
@FezVrasta Hello, sorry for the very long reply. I already make a issue for the feature that i mentioned before. thanks :smile:

**Comment by tilwinjoy** [comment]
I see version 4.02 under releases... So is v4 officially released?

**Comment by FezVrasta** [comment]
nope, it should be a pre-release actually.

**Comment by FezVrasta** [comment]
I updated the v4 code-base to match with Bootstrap v4 beta.

Any help to improve the current situation is super welcome.
The building process has been dramatically simplified, there are things missing but we'll add them when needed.

**Comment by FezVrasta** [comment]
published 4.0.0-beta.3 and published new docs/website
