### ISSUE TITLE
How to bind DOM element created by JavaScript? 

### ISSUE THREAD

**Issue by isuhendro** [mdbootstrap/mdb-ui-kit#1007]
I am trying to create `input` field via JavaScript (late binding). Initial look and feel is ok, but the "focus" event, is not returning expecting border in the bottom.

How to do this late binding... similar functionality done by `componentHandler.upgradeElement` in MDL?
https://getmdl.io/started/

``` javascript
<div id="container"/>
<script>
  var button = document.createElement('button');
  var textNode = document.createTextNode('Click Me!');
  button.appendChild(textNode);
  button.className = 'mdl-button mdl-js-button mdl-js-ripple-effect';
  componentHandler.upgradeElement(button);
  document.getElementById('container').appendChild(button);
</script>
```

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support
