### ISSUE TITLE
Drawer not working in iPhone 6

### ISSUE THREAD

**Issue by isuhendro** [mdbootstrap/mdb-ui-kit#1009]
Tested drawer fuctionality in below link ...
http://rosskevin.github.io/bootstrap-material-design/material-design/drawers/

It works well in Android phone, but the drawer is not appearing (sliding) in iPhone 6 plus. Pressing hamburger menu button does not respond. Is it known issue?

**Comment by rosskevin** [comment]
This is probably due to #1003.

If rollup doesn't fix it we will have to move to something else for bundling.

**Comment by rosskevin** [comment]
I'm closing this in lieu of #1003

**Comment by isuhendro** [comment]
#1003 is having below test case http://codepen.io/rosskevin/pen/eJMMVB which is for "input" field. But input field is working perfectly in iPhone 6. The issue reported here is for `drawer` not `input` field...
@rosskevin could you please reopen it?

**Comment by rosskevin** [comment]
@isuhendro the test case is irrelevant.  #1003 is for the babel-polyfill being missing, which means that _no javascript_ is running on safari, mozilla, etc.  This means that certainly, the drawer won't work.

Without #1003, no javascript works on iPhone.  Once #1003 is resolved, if the drawer doesn't work then we should reopen or file a new issue.
