### ISSUE TITLE
[v4] Update twbs dependency

### ISSUE THREAD

**Issue by dionysiosarvanitis** [mdbootstrap/mdb-ui-kit#1013]
Current dependency version "twbs/bootstrap#v4-dev" installs Bootstrap 3 instead of 4. It should be used  "bootstrap": "^4.0.0-alpha.2".

**Comment by rosskevin** [comment]
No, it is pointed at the repo branch https://github.com/twbs/bootstrap/tree/v4-dev?files=1

**Comment by dionysiosarvanitis** [comment]
You're right. Mixed up with the master branch. Thank you
