### ISSUE TITLE
Support for centered floating labeled inputs

### ISSUE THREAD

**Issue by gmertk** [mdbootstrap/mdb-ui-kit#1014]
Hi,

I was trying to use the floating labeled inputs with `text-align: center` but the label (in empty state) appears to be shifted to right, not centered properly. Any suggestions to fix this?

![jyju42kwlq](https://cloud.githubusercontent.com/assets/907281/15476719/1e753b9e-2111-11e6-9ad3-a273407298fe.gif)

**Comment by rosskevin** [comment]
This is personal user support, not an issue; per contribution guidelines please ask on StackOverflow.
