### ISSUE TITLE
Hover effect missing for navbar links

### ISSUE THREAD

**Issue by wil93** [mdbootstrap/mdb-ui-kit#1015]
I think this issue could be related to #343 (which was already fixed).

In that issue, neither the hover nor the click effect were present. This time, the click effect is present, but the hover effect is missing.

You can reproduce the issue in the official demo: http://fezvrasta.github.io/bootstrap-material-design/#navbar

At first I thought this might be a design choice, but:
1. Buttons have a hover effect, so why not navabr links?
2. I found the issue linked above, which complained about missing hover effect on the navbar, so I think that the effect was there at some point.
#### Test Case

http://fezvrasta.github.io/bootstrap-material-design/#navbar
#### Summary

The navbar should have a hover effect, but it only has a click effect. It happens on both Chromium and Firefox (latest version) on Archlinux.
#### Expected result

There should be a hover effect.

**Comment by Xayer** [comment]
I think it's just a matter of merging this piece of code into [`_navbar.scss`](https://github.com/FezVrasta/bootstrap-material-design/blob/master/sass/_navbar.scss) at least for Bootstrap v3.

```
.navbar {
  .navbar-nav {
    > .open > a , > li > a {
      &:hover {
        background-color: $mdb-navbar-hover-bg;
      }
      &:focus {
        background-color: $mdb-navbar-active-bg;
      }
    }
  }
}
```

---

Or even just use the code from bootstrap v3's [`_navbar.less`](https://github.com/twbs/bootstrap/blob/v3.3.6/less/navbar.less#L412):

```
// Dark links against a light background
.navbar-light {
  .navbar-brand {
    color: $navbar-light-active-color;

    @include hover-focus {
      color: $navbar-light-active-color;
    }
  }

  .navbar-nav {
    .nav-link {
      color: $navbar-light-color;

      @include hover-focus {
        color: $navbar-light-hover-color;
      }
    }

    .open > .nav-link,
    .active > .nav-link,
    .nav-link.open,
    .nav-link.active {
      @include plain-hover-focus {
        color: $navbar-light-active-color;
      }
    }
  }
```
