### ISSUE TITLE
Provide an input number material design

### ISSUE THREAD

**Issue by HectorLS** [mdbootstrap/mdb-ui-kit#1017]
First, awesome repo !!

Just asking for a new featured element
You already have almost all the forms inputs styled less the **input number**

Would be awesome have one working  #PrayForTheInputTypeNumber 👍

**Comment by FezVrasta** [comment]
What's the problem with the input number? It should be style like all the other inputs.

**Comment by HectorLS** [comment]
Maybe i'm wrong but i didn't see input number here to use it http://fezvrasta.github.io/bootstrap-material-design/

**Comment by SergeyKhval** [comment]
@Tibicenas just add `class="form-control"` to your input and you are good to go

**Comment by HectorLS** [comment]
Awesome ! now works great @SergeyKhval  thank you so much !
