### ISSUE TITLE
Issues with AngularJS, some elements works, others don't

### ISSUE THREAD

**Issue by HectorLS** [mdbootstrap/mdb-ui-kit#1018]
For a normal web works sweet but in AngularJS some components works ( like input type="text")
but others like toggle button or dropdown don't.

``` json
"angular": "^1.5.5",
"bootstrap-material-design": "^0.5.9"
```

``` html
<!-- CSS -->
 <link rel="stylesheet" href="../../bower_components/bootstrap-material-design/dist/css/bootstrap-material-design.min.css" />
 <link rel="stylesheet" href="../../bower_components/bootstrap-material-design/dist/css/ripples.min.css" />

<!-- JS -->
 <script src="../../bower_components/jquery/dist/jquery.min.js"></script>
 <script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
 <script src="../../bower_components/bootstrap-material-design/dist/js/material.min.js"></script>
 <script src="../../bower_components/bootstrap-material-design/dist/js/ripples.min.js"></script>
```

``` html
<!-- input text works -->

<div class="form-group label-static">
    <label for="i2" class="control-label">label-static</label>
    <input type="email" class="form-control" id="i2" placeholder="placeholder attribute">
    <p class="help-block">This is a hint as a <code>p.help-block.hint</code></p>
 </div>

<!-- toggle don't work -->
            <div class="togglebutton">
              <label>
                Bluetooth
                <input type="checkbox">
              </label>
            </div>
```

**Comment by FezVrasta** [comment]
arrive.js

**Comment by HectorLS** [comment]
That file is not in your dist folder and is not installed as dependency, where can  i get it ?

**Comment by rosskevin** [comment]
@Tibicenas you should google "arrive.js".  This issue tracker is for BUGS, not your personal support system.

Please read the following before filing any more issues:
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md

Please follow the issue template and file test cases with any future issues as well, otherwise we will close them.

**Comment by HectorLS** [comment]
Hi @rosskevin you're right, i usually use stackoverflow for personal support, but in this case i thought was a dependency missed somewhere, now i saw the below paragraph, sorry for the inconvenience and thank you so much by the fast reply

> If you need to dynamically add elements to your DOM then you may need to include Arrive.js before Material.js. This will automatically apply material.js to every new element added via JavaScript.

**Comment by li-keli** [comment]
where can download Arrive.js?

**Comment by FezVrasta** [comment]
https://github.com/uzairfarooq/arrive (added link to README)
