### ISSUE TITLE
datetime picker

### ISSUE THREAD

**Issue by joeblew99** [mdbootstrap/mdb-ui-kit#1019]
One thing missing that is really hard to get right is a data tiem picker.

there is one here:
https://github.com/T00rk/bootstrap-material-datetimepicker

It would be nice if it was integrated here, so that its supported as the whole framework changes.
I really need it for al projects i use material design on.

I might be able to do it and PR, but doubt it as frontend is not really my thing.

**Comment by FezVrasta** [comment]
Check out https://github.com/alienfast/picker.js

**Comment by joeblew99** [comment]
thanks !!
