### ISSUE TITLE
Floating Input state after form.reset() 

### ISSUE THREAD

**Issue by x1unix** [mdbootstrap/mdb-ui-kit#1029]
#### Test Case

http://codepen.io/cyberd/pen/PzzrRg
#### Summary

Ubuntu Linux 14, Google Chrome 51
#### Expected result

A state of input with floating label not reset after form.reset();

**Comment by rosskevin** [comment]
You must trigger the `change` event for the label to change positions. Does reset() trigger this for each input?

**Comment by rosskevin** [comment]
You had multiple problems with your test case it wasn't working as-is.  I have corrected it.

Note that [form.reset() restores default values](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset), so your test case needs to start with none.

Here is a working example:
http://codepen.io/rosskevin/pen/wWWVrz?editors=1010
