### ISSUE TITLE
Include `.import.less` files for compatibility with Meteor

### ISSUE THREAD

**Issue by npvn** [mdbootstrap/mdb-ui-kit#103]
This is a problem specific to the Meteor framework: All `.less` files are automatically and independently compiled, so `@import`ing a `.less` file won't work.

Meteor developers often rename the files into `.import.less` and have a `main.less` stylesheet to `@import` them all.

Here is my situation: I'm building a Meteor package, in which `bootstrap-material-design` is a submodule. I want to `@import` all the files in the `/less` directory, but fail because of the reason mentioned above.

I may try to find a workaround, for example: Write a script to automatically rename `.less` files into `.import.less` before the package is added. Unfortunately, the process is very cubersome with the current Meteor package system.

I think a better way should be to include `.import.less` files inside the `bootstrap-material-design` repository. For example, we can put the files here: `/dist/import_less`. The content of this folder would be exactly the same as `/less`, only the file extension is different.

Can we setup a Grunt routine to do this? Meteor developers would be very happy :D

**Comment by FezVrasta** [comment]
Do you mean that the files should looks like these?

```
navbar.import.less
foobar.import.less
main.less
```

If so, I think we can directly use this convention for the /less and /sass folders, would not be a problem at all.

**Comment by npvn** [comment]
That's right. Thank you very much!

**Comment by FezVrasta** [comment]
okay all done, I've fixed the problem in the develop branch
