### ISSUE TITLE
Appending to the html document in the first 10 seconds after page has loaded triggers onchange event

### ISSUE THREAD

**Issue by jorgeandresserrano** [mdbootstrap/mdb-ui-kit#1031]
This happens all over except on checkboxes.

I could not reproduce such behaviour on the code pen for some reason.

Problematic code is from line 261 to 275 on material.js

So, how can I append within this interval? (10s after loaded).

Time is set under this comment:
_// After 10 seconds we are quite sure all the needed inputs are autofilled then we can stop checking them_

**Comment by rosskevin** [comment]
Closed for disregarding contribution guidelines and ignoring the issue template.

Without even a codepen attempt, we have no very little idea what you are doing and have a hard time helping.
