### ISSUE TITLE
React boostrap-material?

### ISSUE THREAD

**Issue by SOSANA** [mdbootstrap/mdb-ui-kit#1032]
Curious if someone has started or if you plan to have support for a React boostrap-material?

**Comment by rosskevin** [comment]
There are several react material design projects, such as material-ui and react-toolbox.  As far as react + bootstrap + material, I am unsure.  This project will not be doing anything with react, but anyone is welcome to wrap it if they so choose.

**Comment by SOSANA** [comment]
@rosskevin none of them are on par with this project but all good, can still use this with my current react components...thank you for replying!

**Comment by Stupidism** [comment]
Use with react-bootstrap!
