### ISSUE TITLE
jquery change event triggering for infinite time

### ISSUE THREAD

**Issue by internshala** [mdbootstrap/mdb-ui-kit#1033]
#### Test Case

$("#input").change(function () {
            console.log($("#input").val());
    });
#### Summary

The moment I changed input field, I am getting message console infinite times.
#### Expected result

I should get message on console only once.

**Comment by rosskevin** [comment]
Submit a test case with the template provided.

**Comment by Klakurka** [comment]
This is happening for me. If I remove Bootstrap Material (4.1.1), it fixes the issue.

      <input type="text" class="form-control" id="myInput" maxlength="12" placeholder="">
      $('#myInput').on('change', function() {
		console.log('hi');
	});

I have the following libs included:

		<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
		<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
		<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>

**Comment by chamnap** [comment]
The same happens to me.

**Comment by chamnap** [comment]
@Klakurka, did you manage to fix this issue?

**Comment by Klakurka** [comment]
No. We're no longer using the Bootstrap Material JS (CSS only) until it's been resolved.
