### ISSUE TITLE
Material Design Icons name with space not working

### ISSUE THREAD

**Issue by changeweb** [mdbootstrap/mdb-ui-kit#1034]
#### Test Case

Here is a **Codepen** example - 
(http://codepen.io/hasib_mahmud/pen/begaMG) 
#### Summary

Material Design Icons name with space not working. The above example shows that icon name **more** is working but icon name with space like **more horiz** or **more vert** is not working. See the following images.

![20dd4a09-d776-4f04-ad23-42488121bbac](https://cloud.githubusercontent.com/assets/9896315/16356606/6500cb10-3b00-11e6-811b-592fa0f91a67.jpg)

![f653271d-991d-42a8-b866-7d40f1c8d2b5](https://cloud.githubusercontent.com/assets/9896315/16356628/064c1966-3b01-11e6-8534-f18e070b5148.jpg)

This problem occurs for all icon names containing space.
#### Expected result

Material Design Icons name with space should work.

**Comment by rosskevin** [comment]
You need to use underscores for spaces. This is Google's font, not owned by this library.

**Comment by jayudhandha** [comment]
@rosskevin Thank you so much!!
