### ISSUE TITLE
Question: Is there a way to disable ripple effect on checkboxes?

### ISSUE THREAD

**Issue by brothell** [mdbootstrap/mdb-ui-kit#1035]
Hi, i love this project, but some animations are annoying for me =/ 
is there a way to disable ripple effect on checkboxes - the pulse on load and check?

Thanks

**Comment by FezVrasta** [comment]
No there's not, but you can easily add a CSS to hide the `.checkbox-material:before` pseudo-element

**Comment by doug-gv** [comment]
answered this here, just in case

https://github.com/FezVrasta/bootstrap-material-design/issues/664#issuecomment-394124911
