### ISSUE TITLE
'onchange' event fires up indefinitely within 10 first seconds 

### ISSUE THREAD

**Issue by jorgeandresserrano** [mdbootstrap/mdb-ui-kit#1036]
#### Test Case

http://codepen.io/jorgeandresserrano/pen/YWNgZp
#### Summary

'onchange' event is fired up indefinitely on inputs type file if they are effectively changed within 10 first seconds after the page loads.

To reproduce the bug on the above codepen url, chose a file within the first 10 seconds after the page has loaded.

Tested on google chrome Version 51.0.2704.106 (64-bit)
#### Expected result

Only one 'onchange' event fire when manually changing the content.

**Comment by FezVrasta** [comment]
Just disable the `autofill` feature from material.js and you are good to go.
