### ISSUE TITLE
Any current issue with this project and Meteor/Atmosphere?

### ISSUE THREAD

**Issue by Orbyt** [mdbootstrap/mdb-ui-kit#1037]
Was wondering why I couldnt find this package in the atmospherejs search results. Google found it here: https://atmospherejs.com/fezvrasta/bootstrap-material-design

Its currently flagged as well.

Are there any current integration issues with Meteor or is it ok to proceed using this package?

**Comment by rosskevin** [comment]
Use the npm package.

**Comment by Orbyt** [comment]
Ah, I just found this: https://github.com/FezVrasta/bootstrap-material-design/issues/930

Anyway, I went and did `meteor npm install boostrap-material-design --save`. The package seemed to download successfully, though I tried using a btn and it is still the default bootstrap styling. Is there a step im missing?

**Comment by romans127** [comment]
any update on this ? 
what's the next step after npm install  ?
