### ISSUE TITLE
SASS compile error

### ISSUE THREAD

**Issue by landsman** [mdbootstrap/mdb-ui-kit#1039]
I have:

@import "../../bower_components/bootstrap-material-design/sass/bootstrap-material-design";

And error:

Running "sass:dist" (sass) task
Error: File to import not found or unreadable: bootstrap/variables.
        on line 1 of bower_components/bootstrap-material-design/sass/_import-bs-sass.scss
        from line 42 of bower_components/bootstrap-material-design/sass/_variables.scss
        from line 3 of bower_components/bootstrap-material-design/sass/bootstrap-material-design.scss
        from line 4 of sass/modules/_bootstrap.scss
        from line 3 of sass/modules/_base.scss
        from line 2 of sass/core.scss
  Use --trace for backtrace.

**Comment by SergeyKhval** [comment]
This is some StackOverflow type question.
Nevertheless I assume you need to add bootstrap-sass into [loadPath (importPath)](https://github.com/gruntjs/grunt-contrib-sass#loadpath)

I use gulp with SASS and Compass and have this config which works perfectly:

`compass: {
      options: {
        importPath: ['./bower_components', './bower_components/bootstrap-sass/assets/stylesheets']
      }
}`
