### ISSUE TITLE
Ripples don't forward click events on browsers that don't understand pointer-events:none CSS attribute

### ISSUE THREAD

**Issue by Chlodny** [mdbootstrap/mdb-ui-kit#1040]
#### Test Case

http://codepen.io/anon/pen/ZOAvYL
#### Summary

Some older browsers on Windows - ex. Opera 12 - don't understand pointer-events CSS attribute and Ripples block click events on buttons/dropdowns. My solution is simple and works in any browser - it is just a few lines of code.
I added it to Test Case's JS window as Ripple.prototype._init function - just change it to init.

I hope someone will find it usefull.
#### Expected result

On Opera button should open link but it doesn't
#### Additional Information

My solution to a problem:

[ripples-init-chlodnys-solution.txt](https://github.com/FezVrasta/bootstrap-material-design/files/370381/ripples-init-chlodnys-solution.txt)

**Comment by FezVrasta** [comment]
Opera 12 is not supported, it's an almost unused browser in its latest version, I wonder how many people use an old version.
