### ISSUE TITLE
Floating Labels Cover Selected Value in Drop Down List

### ISSUE THREAD

**Issue by paranoid-android** [mdbootstrap/mdb-ui-kit#1041]
#### Test Case

[http://codepen.io/anon/pen/RRQYLd](http://codepen.io/anon/pen/RRQYLd)
#### Summary

Basically, I am selecting a drop-down list programmatically. When a drop-down list value is selected programmatically, the floating label covers the selected label text. This is a problem specifically in cascading drop-down scenarios.
#### Expected result

The problem is clearly visible in the CodePen.

**Comment by rosskevin** [comment]
You have to trigger the `change` event.  All floating labels are responding to change, not focus.

**Comment by paranoid-android** [comment]
@rosskevin Thank you so much for letting me know. That makes sense.
