### ISSUE TITLE
How to use bootstrap-material-design with Angular 2?

### ISSUE THREAD

**Issue by andreimladin** [mdbootstrap/mdb-ui-kit#1042]
The design works, but the effects don't. 
My Angular 2 app works as expected with bootstrap-material-design, but the only one problem is that the material effects are lost. Once I extract the Angular initalization, they work.
I like very much this theme and also the Material Kit Pro which I'm going to buy if the integration works well.
I would much appreciate you telling me if there is trick or a workaround to make them work together.

**Comment by FezVrasta** [comment]
Include `arrive.js` before the theme.
https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support

**Comment by andreimladin** [comment]
It works. Much appreciated

**Comment by GoygovRustam** [comment]
I have the same problem with Angular 2 and including arrive.js before material.js did not help me. 
![image](https://cloud.githubusercontent.com/assets/18407297/21068785/065f2d8e-be29-11e6-8e46-2e1b12873f69.png)

Is there anything else I could try to make it work? 

Thank you.
