### ISSUE TITLE
V4: build failing with latest bootstrap#v4-dev

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#1045]
Bootstrap didn't publish umd or src in the latest builds:
https://github.com/twbs/bootstrap/issues/18934

New builds are currently not working. I do see that they intend to publish js modules in alpha 3, just not sure what to do in the interim.

Unfortunately, npm isn't pulling the full repo source like it used to based on `"bootstrap": "twbs/bootstrap#v4-dev"`, otherwise I could just add their `js` source to our transpilation pipeline.

We need to get back to a place where either:
a) bootstrap is publishing modules in the npm package; or
b) npm will pull the `js` source from the repo like I instruct it to! (not sure why this has changed)

**Comment by rosskevin** [comment]
@FezVrasta that's all the time I can give this today.  If you can solve `b)` above, I'm pretty sure I can get the build working again.  As-is, I have no `js` source being pulled from the bs4 repo and I have no idea why.

If alpha 3 is published, that is our best bet and they have promised that this is solved for that release.

**Comment by FezVrasta** [comment]
Sorry what's the point `b`?

Imho there aren't problems in waiting for BS to fix on their side, no rush.

**Comment by rosskevin** [comment]
> b) npm will pull the js source from the repo like I instruct it to! (not sure why this has changed)

**Comment by rosskevin** [comment]
4.0.0-alpha.3 npm package does not contain es6 sources, a cjs or umd bundle.

**Comment by FezVrasta** [comment]
shit :/ will have to wait then..

**Comment by FezVrasta** [comment]
Our blocking issue is being tracked at https://github.com/twbs/bootstrap/pull/20418

**Comment by FezVrasta** [comment]
Updating the status here:

As temporary workaround, https://github.com/FezVrasta/bootstrap-material-design/commit/622fbabe5586213b99d036989ba9fe86e78e98ee is working just fine and allows us to make the build pass.
This means we can proceed with #1004.

Still waiting for Bootstrap to reintroduce the javascript source tho.

**Comment by FezVrasta** [comment]
Latest v4-dev of BS includes the sources, this fixes our problem.

**Comment by FezVrasta** [comment]
Locally it passes, on travis it fails. I'm investigating the issue

**Comment by FezVrasta** [comment]
Ok nice, now even locally I get:

```
    Task: [rollup:umd]
  Plugin: [rollup]
   Error: Error transforming /Users/federicozivolo/Progetti/bootstrap-material-design/js/index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
```

@rosskevin I thought you had fixed it, do you have any clue?

It's freaking weird that even after I reverted the changes the build is still failing locally.. let's see on Travis..

PS. Failing even on Travis... maybe it's some dependency that got updated and broke the build...

**Comment by FezVrasta** [comment]
Ok it's babel-preset-es2015, the newest version breaks something. The 6.9.0 works just fine..

@rosskevin do you know where should we report this problem?

**Comment by FezVrasta** [comment]
Passing both locally and on TravisCI.. for now I'll keep 6.9.0.. I don't have the knowledge to dive into the build system built by Ross

**Comment by FezVrasta** [comment]
Seems like we could fix the problem with this suggestion?

https://github.com/chrisprice/grunt-rollup/issues/18#issuecomment-241024063

**Comment by FezVrasta** [comment]
@rosskevin I can't really understand how the build system you built works... I'm thinking about rewriting it from scratch with Grunt and nothing else, I don't really see the advantages of using all this complex stuff just to run rollup and few commands...

**Comment by rosskevin** [comment]
I have no objections.
