### ISSUE TITLE
v4 compile error:Base-level rules cannot contain the parent-selector-referencing character '&'.

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#1046]
using koala to compile bootstrap-material-design.scss with bootstrap 4.0.0-alpha.3:

Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 106 of scss/mixins/_forms.scss, in `bmd-form-color'
        from line 79 of scss/_forms.scss
        from line 13 of scss/_core.scss
        from line 3 of scss/bootstrap-material-design.scss

**Comment by FezVrasta** [comment]
Dup of #957
