### ISSUE TITLE
V4: Uncaught ReferenceError

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#1047]
general issue => also occurs official website : 
http://rosskevin.github.io/bootstrap-material-design/examples/dashboard/

![2016-07-29_154742](https://cloud.githubusercontent.com/assets/6369772/17250274/dcbf53e8-55a3-11e6-913f-d86ce0d8296d.jpg)
#### Test Case

http://codepen.io/rosskevin/pen/eJMMVB
#### Summary

Execution error :
- bootstrap-material-design.iife.min.js:1 => Uncaught ReferenceError: require is not defined

More specifically (using bootstrap-material-design.iife.js in place of bootstrap-material-design.iife.**min**.js )
`polyfill.js:1Uncaught ReferenceError: require is not defined
e   @   polyfill.js:1
(anonymous function)    @   polyfill.js:1
createCommonjsModule    @   bootstrap-material-design.iife.js:12
(anonymous function)    @   bootstrap-material-design.iife.js:94
(anonymous function)    @   bootstrapMaterialDesign.js:205`
- pen.js:20 => Uncaught TypeError: $(...).bootstrapMaterialDesign is not a function
#### Expected result

Script is not working ... 
#### Additional Information

This problem happens since today.

**Comment by ghost** [comment]
Some extra information : 

The problem is visible on the "Dashboard" example.
http://rosskevin.github.io/bootstrap-material-design/examples/dashboard/

Using the same template for my website, is this any "patch" I can use to resolve this issue ?

**Comment by FezVrasta** [comment]
I think you will have to wait for #1045 and #1003 to be fixed before you can safely use the V4 branch.

Unluckily #1045 is still blocking for us until Bootstrap fixes it or we workaround the problem.

**Comment by ghost** [comment]
Thank you for the quick answer.
I really appreciate your work.
I just wanted to mention that it worked 5 days ago ... no way to use a "older" version of the script ?

**Comment by FezVrasta** [comment]
I have tried to compile the documentation with the latest commit of `v4-dev` and it works without errors. May you give a try?

I'm closing it for now, feel free to open it again if you still reproduce the problem.

**Comment by ghost** [comment]
It works like a charm, thank you !

**Comment by FezVrasta** [comment]
Yea! 👍

**Comment by arun472** [comment]
Right now i stuck from morning in app development I am pointing my application to                         `<script src="https://cdn.rawgit.com/fezvrasta/bootstrap-material-design/dist/dist/bootstrap-material-design.iife.min.js"></script>`

can you share link where js is working  where the above issue is not produced.

**Comment by FezVrasta** [comment]
In not sure the dist file are updated

**Comment by arun472** [comment]
can you help to to build from your source to build material-design.iife.min.js so that our development do not affect

**Comment by FezVrasta** [comment]
Are you using the v3 or the v4 version? The link you provided is for the v3.

Or better, the file name is of the v4, but the URL points to the V3 branch.. Where did you get that URL?

**Comment by arun472** [comment]
we are using v4 . In v4 documentation http://rosskevin.github.io/bootstrap-material-design/getting-started/introduction/ even documentaion pages are also getting same above error.

**Comment by FezVrasta** [comment]
Ok then it's a problem with the build we had before this PR was closed.

I don't know how @rosskevin published the v4 source on the above URL but probably we need to update it somehow.

I think it's better to not rely on the CDN until the V4 release is out and our CDN are properly configured. Download the source with any of the supported package managers and compile it by yourself.

**Comment by ghost** [comment]
Bootstrap Material Design - branch v4-dev - build 2016.08.03 12.07pm (Belgian Time)

https://we.tl/RQhElrl7HS

**Comment by arun472** [comment]
@llhoir  thanks for sharing link

**Comment by rosskevin** [comment]
The latest dist commit is broken based on unresolved Bootstrap sources. @fezvrasta if it builds as is I can publish again.

**Comment by FezVrasta** [comment]
Yes right now the build is working 👍

**Comment by rosskevin** [comment]
I ran `gulp publish`, the latest is up.

**Comment by FezVrasta** [comment]
@rosskevin may you give me write access to the repo so I can update it by myself when needed?

**Comment by rosskevin** [comment]
done, most of my setup docs are here http://rosskevin.github.io/bootstrap-material-design/getting-started/building/

**Comment by FezVrasta** [comment]
I have also fixed the CDN URLs of this page:
http://rosskevin.github.io/bootstrap-material-design/getting-started/introduction/

**Comment by rosskevin** [comment]
The iife doesn't come from gh-pages,  it comes from dist, so that is incorrect.

**Comment by rosskevin** [comment]
All distributables are pushed here:
https://github.com/FezVrasta/bootstrap-material-design/tree/dist

Pointing others to a gh-pages is a bad idea I think.

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/commit/90c0ff2050da7b93fe5bd1153b0d882591c6bf28#commitcomment-18508280
