### ISSUE TITLE
Expose init for injected templates

### ISSUE THREAD

**Issue by rightisleft** [mdbootstrap/mdb-ui-kit#105]
Im using a JS framework that dynamically inserts partial templates. When that occurs i need to bind the new elements to the material.js library. Is there a material object in global scope, or another preferred way to handle this?

**Comment by FezVrasta** [comment]
material.js has support for arrive.js, which take care of running material.js on any new material design element which needs it.

**Comment by rightisleft** [comment]
It would be great to expose an API to allow for this to work w/o a dependency on arrive.js. It would allow materials to work with 3rd party frameworks that already support detecting insertion.

**Comment by FezVrasta** [comment]
I'll do something to fix this problem, expect some kind of `$.material` class with some functions in it...

**Comment by FezVrasta** [comment]
Implemented with c26d5e3ce17eb41aa00628e1d26a178b589a824b
