### ISSUE TITLE
V4: wrong dropdown item padding

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#1051]
@rosskevin may you explain the reasoning behind this line?

```
$bmd-menu-item-padding-top: ($bmd-menu-item-min-height - $font-size-base - $bmd-menu-item-padding-bottom) !default;
```

I think the top and bottom paddings should be the same in the dropdown items.

**Comment by rosskevin** [comment]
I don't recall. What I was last thinking was to kill padding use altogether and switching to flex and min-height. It's just so much easier to maintain and make consistent. Same thoughts on buttons.

**Comment by FezVrasta** [comment]
I see, thanks for the info.
