### ISSUE TITLE
V4: Jumbotron styling

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#1053]
![image](https://cloud.githubusercontent.com/assets/5382443/17400073/3e86ea9a-5a46-11e6-8bb1-e6a52f481e3c.png)

No MD documentation available, it doesn't look so bad our style but I think it's not materialish enough.

**Comment by iqbalaqaba** [comment]
Maybe replace button with `.btn-rasied .btn-info` class and make the background color of the jumbotron more softer ?

**Comment by iqbalaqaba** [comment]
![screenshot_79](https://cloud.githubusercontent.com/assets/20835372/17980044/c6454e4e-6b27-11e6-89d2-7b5437cdc498.jpg)
Color code is : #EEEEEE

**Comment by Firestorm-Graphics** [comment]
you are aware boot 4 deprecated jumbotron Right ?

**Comment by FezVrasta** [comment]
cool thanks
