### ISSUE TITLE
V4: Collapse inline (width) not working properly

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#1054]
http://rosskevin.github.io/bootstrap-material-design/material-design/collapse-inline/

There's not animation, it just switches between the two states.

@rosskevin I tried to look at your script but I can't understand how is it supposed to work. Do you have a little of time to check it out?

Thanks!

**Comment by rosskevin** [comment]
It works for me on chrome and firefox.  It uses bootstrap's default collapse/animation - and is unchanged.   I admit that I don't much like how bootstrap is animating it. 

If you would like a smoother/different/longer animation you'll need to enhance it further by taking over animation from bootstrap.  When I last looked at this, it seemed like we would be better off not reusing bootstrap's collapse as the basis and just writing it ourselves (but I don't have time).

Note: on safari, the icon button is not showing up properly but the collapse functionality works (hover over it and it will change backgrounds)

http://rosskevin.github.io/bootstrap-material-design/material-design/collapse-inline/#example-search-field-triggered-by-an-icon-button

**Comment by FezVrasta** [comment]
![broken](https://cloud.githubusercontent.com/assets/5382443/17408143/58eafa88-5a6a-11e6-9ac1-aa0881c96e7e.gif)

This is what I see. It seems like there's not animation at all.

**Comment by rosskevin** [comment]
This is exactly bootstrap's animation.

**Comment by FezVrasta** [comment]
No really, there's not any kind of animation. It just jumps from 0 to 100%..

**Comment by rosskevin** [comment]
My point is:

This is using bootstrap's collapse, I just adapted it to horizontal. 

Feel free to keep or delete it.  It needs work but I never had time to rewrite it.

**Comment by FezVrasta** [comment]
Ok this is not a problem, but don't tell me that its animation works 😝
