### ISSUE TITLE
Url to js file in V4 get started documentation gives 404

### ISSUE THREAD

**Issue by mrlux** [mdbootstrap/mdb-ui-kit#1056]
Using the v4 documentation:
http://rosskevin.github.io/bootstrap-material-design/getting-started/introduction/

When using the starter template localy the bootstrap-material-design js file is not loaded:

src="https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/dist/dist/bootstrap-material-design.iife.min.js.iife.min.js"

Should be 

src="https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/dist/dist/bootstrap-material-design.iife.min.js"

Quick start is also missing the viewport fix for IE10

 
 src=""

Should be 

 
src="https://maxcdn.bootstrapcdn.com/js/ie10-viewport-bug-workaround.js"

**Comment by FezVrasta** [comment]
I see the problem with the bmd.js file, but the other URL seems to be displayed just fine to me.

![image](https://cloud.githubusercontent.com/assets/5382443/17401263/0936f8e2-5a4d-11e6-905f-3c0a97b17ca3.png)

**Comment by mrlux** [comment]
Is not the code example in the Starter template but above it in the Quick Start 

![image](https://cloud.githubusercontent.com/assets/2972751/17401664/1f9d5d4a-5a4f-11e6-9537-678ecd5aab16.png)

**Comment by FezVrasta** [comment]
I see thanks, fixing it

**Comment by FezVrasta** [comment]
Fixed with https://github.com/FezVrasta/bootstrap-material-design/commit/460688090e9e0b846bf8232f1e69ac453bd280c4

~~publishing it right now~~ published
