### ISSUE TITLE
V3 Input elements are not shown properly in UC mobile browser

### ISSUE THREAD

**Issue by sujanadiga** [mdbootstrap/mdb-ui-kit#1062]
![bootstrap-material-issue](https://cloud.githubusercontent.com/assets/16635045/17583676/c1190ee6-5fcf-11e6-81a3-28a079044a94.jpeg)

The input line is shown above the input text in UC browser 10.10.8.820, Android 5.1
### Steps to reproduce:
- Open UC browser for android
- Open the link http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html
- Observe the line on top of input fields

**Comment by FezVrasta** [comment]
Seems like a bug of the browser, and being an almost unknow and with low share browser I'm not gonna fix it.

If you want you can prepare a PR and propose it.

**Comment by sujanadiga** [comment]
@FezVrasta It may be the bug of the browser, but UC browser is not unknown, It has 100,000,000 - 500,000,000 downloads in Play Store https://play.google.com/store/apps/details?id=com.UCMobile.intl&hl=en

**Comment by FezVrasta** [comment]
The installs is not a reliable information, lot of people install apps to try them and then stop using after few minutes.

Btw as I said, if you want to send a PR to fix it, feel free.
