### ISSUE TITLE
Bottom border on textbox input fields not shown at all in IE9 and certain versions of Safari

### ISSUE THREAD

**Issue by mobbsie** [mdbootstrap/mdb-ui-kit#1065]
#### Test Case

You can test the examples provided.  It is applicable to all inputs.
#### Summary

All textbox input fields don't render a bottom border in IE9 and certain versions of Safari. This makes it difficult for the user to know where they need to enter a response.
#### Expected result

I would expect that even if the animation doesn't work, it should show a bottom border to indicate to the user where they should enter their response.

**Comment by FezVrasta** [comment]
Is it about V3 or V4?

**Comment by mobbsie** [comment]
It seems to do this in both v3 and v4.

I have changed the styles associated with the class (.form-control, .form-group .form-control) and it now seems to be okay but I haven't done extensive testing yet.  My variable names are slightly different, but where you had just the following line, I now have the other fallbacks:

``` scss
background-image: linear-gradient($colour-primary-1, $colour-primary-1), linear-gradient($input-underline-color, $input-underline-color);

background-color: $colour-white; /* Browsers without linear-gradient support */
background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, $colour-primary-1), color-stop(100%, $input-underline-color)); /* Chrome, Safari 4+ */
background-image: -webkit-linear-gradient($colour-primary-1 0%, $input-underline-color 100%); /* Chrome 10+, Safari 5.1+ */    
background-image:    -moz-linear-gradient($colour-primary-1 0%, $input-underline-color 100%); /* Fx 3.6+ */   
background-image: linear-gradient($colour-primary-1, $colour-primary-1), linear-gradient($input-underline-color, $input-underline-color); /* W3C */
-ms-filter: "progid:DXImageTransform.Microsoft.gradient(gradientType=0, startColorstr='#ffffff', endColorstr='#000000')";
```

**Comment by FezVrasta** [comment]
Seems like you have not used autoprefixer (included in our build)
