### ISSUE TITLE
label-floating on input with icon is disoriented

### ISSUE THREAD

**Issue by prafulbagai** [mdbootstrap/mdb-ui-kit#1066]
<img width="581" alt="screen shot 2016-08-15 at 8 07 32 pm" src="https://cloud.githubusercontent.com/assets/4829481/17667850/54dcd624-6324-11e6-8770-ea112f8da578.png">

As you can see, the `icon` is over the `label`.  Following is my HTML markup

```
<form role="form">
    <fieldset>
        <div class="form-group label-floating">
            <label for="sender-email" class="control-label">Email:</label>
            <div class="input-icon"> 
                <i class="icon-user fa"></i>
                <input type="text" class="form-control email">
            </div>
        </div>
    </fieldset>
</form>
```

Also, when I start typing-in, it starts from behind the icon. Ideally it should start after the icon.

**Comment by FezVrasta** [comment]
Are you referring to V3 or V4?

Please provide the requested codepen example. I'll keep it closed until the requirements are satisfied
