### ISSUE TITLE
bootstrap-material-design v4 + angularJs not working sidebar

### ISSUE THREAD

**Issue by igrwijaya** [mdbootstrap/mdb-ui-kit#1067]
I run angularJs with this framework, still work with angular, but when use sidebar ( class="bmd-layout-container bmd-drawer-f-l bmd-drawer-overlay") not working and not show anything when i click the drawer button.
this is my js setup : 
`<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <script src="build/js/arrive.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src="https://cdn.rawgit.com/HubSpot/tether/v1.3.4/dist/js/tether.min.js"></script>
    <script src="https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/dist/dist/bootstrap-material-design.iife.min.js"></script>
    
    <script src="https://maxcdn.bootstrapcdn.com/js/ie10-viewport-bug-workaround.js"></script>
    <script>
      $('body').bootstrapMaterialDesign();
    </script>`

**Comment by FezVrasta** [comment]
ignored issue template === issue closed
