### ISSUE TITLE
bootstrap-material-design.iife.min.js - Failed to instantiate component

### ISSUE THREAD

**Issue by derah04** [mdbootstrap/mdb-ui-kit#1068]
I've problem when implement arrive.js to BMD4, the error like this : 
![1](https://cloud.githubusercontent.com/assets/12068181/17723065/7fb4831a-6469-11e6-92d2-912cfe622f95.PNG)

![2](https://cloud.githubusercontent.com/assets/12068181/17723068/8c73e9ce-6469-11e6-9f21-b630ec413a29.PNG)

here is my js setup on html : 
![3](https://cloud.githubusercontent.com/assets/12068181/17723079/b21eded6-6469-11e6-8799-81b41b9621c4.PNG)

how do i fix this problem ?

**Comment by tilwinjoy** [comment]
Well looks like you haven't included Arrive.js project... It seems there is a hard dependency on it. Try including it before you instantiate this library.

**Comment by derah04** [comment]
@tilwinjoy can you give me an example ? sorry i don't understand what do yo mean..

**Comment by tilwinjoy** [comment]
See [Arrive.js support](https://github.com/FezVrasta/bootstrap-material-design#user-content-arrivejs-support). Basically you just need to add that library before this project using `<script>` tag.
