### ISSUE TITLE
Wrong breadcrumb highlight color 

### ISSUE THREAD

**Issue by tejastank** [mdbootstrap/mdb-ui-kit#1073]
Expecting tiny feature like this, with 3ed and 4th version both upgrade by you official. 

When click. it should be on touch activate and change.

![screenshot from 2016-08-21 00-39-02](https://cloud.githubusercontent.com/assets/311413/17833332/f65c6fca-6737-11e6-830b-410add073267.png)

**Comment by FezVrasta** [comment]
Feel free to re-open once you properly follow the issue template.
