### ISSUE TITLE
How to remove Roboto font link?

### ISSUE THREAD

**Issue by mahendhar9** [mdbootstrap/mdb-ui-kit#1074]
Hello,
I want to remove https://fonts.googleapis.com/css?family=Roboto:300,400,500,700 from my project, but am unable to find the location of this link.
Can someone please guide me.

**Comment by FezVrasta** [comment]
Remove this:

```
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
```

**Comment by mahendhar9** [comment]
@FezVrasta Can u please tell the location of the file that contains this font link. I am unable to find it in bootstrap-material-design.css
