### ISSUE TITLE
[ Feature ] Expecting the new side-navigation system 

### ISSUE THREAD

**Issue by iqbalaqaba** [mdbootstrap/mdb-ui-kit#1075]
First i wouls say thanks and good work on Bootstrap Material Design.
Keep it up @FezVrasta :smile: :+1: 

I very like to work and use your bootstrap material design, but i expecting this new side-nav system. Actually the guys at Google and Materializecss Framework already did it before, but i'm very very expecting this side navigation system is came to Bootstrap Material Design in the next major update :+1: :+1: 

Here's the screenshot i take as a example : 
![screenshot_77](https://cloud.githubusercontent.com/assets/20835372/17979411/a089e4ec-6b24-11e6-842f-f065ef248377.jpg)

Thank you and keep up the good work !

**Comment by FezVrasta** [comment]
In V4 there is support for it.

**Comment by iqbalaqaba** [comment]
Thanks!
