### ISSUE TITLE
V4: Inputs don't work correctly with Angular 2

### ISSUE THREAD

**Issue by dmbaranov** [mdbootstrap/mdb-ui-kit#1076]
I'm using Angular 2 RC5 and the latest version of bootstrap-material-design. The problem is that inputs don't work correctly and i don't know why. As you can see on this image, floated label is raised by default. If i type something in input, then clear and it press somewhere else (to make it lost focus), label will come in it's normal position. And the placeholder-label is not shown at all until i do the same actions as before. I included all the .css and .js files and called $.material.init(). Code for this page was taken from the official documentation. So maybe you know how to fix it? Thanks in advance

[Image](http://imgur.com/a/AJ6rl)

**Comment by kuljaninemir** [comment]
I'm experiencing this as well, although not with Angular. It's probably related to changing the DOM after the page initially loads. Maybe there's some js-function we can call to re-initialize certain form groups?

**Comment by pierrejochem** [comment]
What is the order of your js files in the project?

**Comment by kuljaninemir** [comment]
The order is jQuery, material, ripples, sly. I don't think this is the issue though.

Calling $.material.input() or $.material.init() again after appending html correctly initializes the inputs.

**Comment by dmbaranov** [comment]
My solution is using [MDL](https://getmdl.io) and the special component from this [answer](http://stackoverflow.com/a/35451821). It works almost perfectly.

**Comment by pierrejochem** [comment]
Was just an idea, but from the workflow you are right.

**Comment by pierrejochem** [comment]
Write a directive which can do the job ;-) or bette a complete module ^^

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support
