### ISSUE TITLE
Error when use sass version

### ISSUE THREAD

**Issue by migaber** [mdbootstrap/mdb-ui-kit#1078]
#### Summary

When use the sass version, I got the following error,

`error app/styles/main.scss (Line 1 of bower_components/bootstrap-material-design/sass/_import-bs-sass.scss: File to import not found or
unreadable: bootstrap/variables.`

Is there any thought to resolve this ???
#### Expected result

To check if bootstrap is already imported or not and decide to include or not

**Comment by FezVrasta** [comment]
Our build work, it must be something on your side. sorry.

**Comment by emman-ok** [comment]
Your Build Does not work. Most of the compiler out there gives the same error. Believe me i have tried them for days. _**error app/styles/main.scss (Line 1 of bower_components/bootstrap-material-design/sass/_import-bs-sass.scss: File to import not found or unreadable: bootstrap/variables**_

Beside when you look at the folder structure there is no file like bootstrap/variables which is reference in the _import-bs-sass.scss.

**Comment by FezVrasta** [comment]
if the build would not work, our CI should fail. Instead, it succeeds. No?

**Comment by guzmo** [comment]
I have the exact same error :S

**Comment by emman-ok** [comment]
If you check this thread you will notice that this is the most common error. But the owner thinks because it works on his machine it work on every other. I have try to compile both the less and sass without any success an now frustrated. Every other compiler has the same issue.

**Comment by FezVrasta** [comment]
I'm sorry for the problems you are facing, but if the build works both on local machines and on CI machines, it means that the problem is not this repository but something on your side.

**Comment by SergeyKhval** [comment]
The workaround is mentioned in the very docs of this project
https://github.com/FezVrasta/bootstrap-material-design#bower

I stumbled upon this issue and what helped me is proper configuration for my task runner

**Comment by emman-ok** [comment]
Thanks Very Much for a Great Tool. I have been able to get it running after going through the doc. Just note that no other compiler out there was able to compile it. Except the method provided at the intro doc.

**Comment by FezVrasta** [comment]
that's the idea behind the whole "programming thing" 😉

**Comment by juanibiapina** [comment]
CI is using bower. Sass version doesn't work with NPM.
