### ISSUE TITLE
[Feature request] Chip / Tag elements along with js manipulation

### ISSUE THREAD

**Issue by onclave** [mdbootstrap/mdb-ui-kit#1079]
None of the existing 3rd party chip / tag elements libraries are visually compatible with this library. Can we expect this feature any time soon?

**Comment by FezVrasta** [comment]
Provide more informations please. Any work will be considered only for the V4 tho.

**Comment by brigadier** [comment]
I think he means either select multiple such as https://harvesthq.github.io/chosen/ , which allows picking upt the options from the select multiple and display them inline, or variation of select when users themselves can add options (tags) to it by just typing in a text input and pressing Enter after each tag..

**Comment by FezVrasta** [comment]
Sorry I can't add support to all the libraries out there, if you want to see them supported send a PR.
