### ISSUE TITLE
Material colors not compiled?

### ISSUE THREAD

**Issue by michel3vb** [mdbootstrap/mdb-ui-kit#1080]
#### Summary

For some reason it looks like the variables file from the material-design package is not compiled after running Gulp. All colors are the same as the default Bootstrap package.
#### Expected result

Material design colors
#### Additional Information

I have installed bootstrap-material-design with Bower

App.scss file looks like this:

```
@import "vendor/bower_components/bootstrap-sass/assets/stylesheets/bootstrap";

@import "vendor/bower_components/bootstrap-material-design/sass/bootstrap-material-design";
```

Gulpfile:

```
var elixir = require('laravel-elixir');
var findup = require('findup-sync')

elixir(function(mix) {
    mix.sass('app.scss', null, {includePaths: [findup('vendor/bower_components/bootstrap-sass/assets/stylesheets/')]});

    mix.browserify('app.js')

    mix.copy('node_modules/flag-icon-css/flags', 'public/build/flags');

    mix.version(["public/css/app.css", "public/js/app.js"]);

});
```

Does anyone have a solution to fix this problem?
Thanks in advance

**Comment by FezVrasta** [comment]
What version are you using?

**Comment by michel3vb** [comment]
I installed the master so I assume this is version 3

**Comment by FezVrasta** [comment]
Please provide a screenshot so I can understand.

If you talk about the additional color variations, you have to use the `full-palette`version of the theme

**Comment by michel3vb** [comment]
The navbar has the "navbar-default" class and the panel has "panel-default" class. So I expect the teal color for both elements but for some reason the page shows the Bootstrap color for default

See screenshot below:

![laravel_-_2016-09-02_17 38 14](https://cloud.githubusercontent.com/assets/3601059/18209465/262c6b00-7134-11e6-8632-e8b385ee4391.png)

**Comment by FezVrasta** [comment]
Sorry I can't help you with custom builds, try asking on StackOverflow, I'm sure someone will be able to help.

Keep this place for bug reports. If our build works, and yours not, it's probably not a bug.
