### ISSUE TITLE
A how to integrate within meanjs is required.

### ISSUE THREAD

**Issue by o1lab** [mdbootstrap/mdb-ui-kit#1081]
#### Summary

Please include a **how to** include this in meanjs framework.
Helps a lot for a newbies like me.

**Comment by FezVrasta** [comment]
Sorry I don't even know what meanjs is 😔 Care to elaborate?

**Comment by o1lab** [comment]
[meanjs](http://meanjs.org/)  is a popular js fullstack framework which generates boiler plate code(backend and frontend). 

# Quick start is like below:

#install yo
npm install -g yo

#install generator for meanjs
npm install -g generator-meanjs

#generate meanjs application boiler plate
yo meanjs

npm install

npm start

# npm install --save bootstrap-material-design

I followed current **How to** - but have got stuck with (may be) path and jquery issues. I am new to web-dev (C developer background) - so could not figure our how to include this module. 

But having a **How to include bootstrap-material-design in meanjs** will be helpful since its a popular framework as far as I know. If I figure out - I would be happy to post a blog or make a commit.

**Comment by FezVrasta** [comment]
It doesn't seem so popular... I never heard of it and it has 3k stars on GitHub which is less than both my most popular repositories 😅

Feel free to write an "How To" here or on a Gist, I'll be happy to put it in the wiki

**Comment by o1lab** [comment]
mean.js was branched from [mean.io](https://github.com/linnovate/mean) - which has 9.5k stars. Its written by [same](http://www.amoshaviv.com/) person with minor changes. So this has kind of has 12+k stars in total - will this help to change minds :) 

Irrespective to above - bootstrap-material-design appears to me a seamless integration for frameworks which uses bootstrap - importantly there is no tag name changes. Having a how to integrate with these popular frameworks ([meteor](https://github.com/meteor/meteor), mean, etc) will help it to be used by more dev communities.

**Comment by FezVrasta** [comment]
As I said, feel free to prepare one.
