### ISSUE TITLE
Missing files after bower install

### ISSUE THREAD

**Issue by o1lab** [mdbootstrap/mdb-ui-kit#1082]
#### Summary

`bower install bootstrap-material-design`

material.js is not found under any folder within bower_components/bootstrap-material-design/

whereas npm install gets material.js fine

Am I missing anything while doing bower install or have to do anything after ?

**Comment by o1lab** [comment]
files as seen after bower install bootstrap-material-design

![md](https://cloud.githubusercontent.com/assets/5435402/18226893/915b87e4-720b-11e6-8fe3-a9dbc11f6009.png)

**Comment by Davidiusdadi** [comment]
i have the same issue

**Comment by jandlint** [comment]
I am also lacking the less folder, as reproduced in @o1lab's screenshot.

**Comment by FezVrasta** [comment]
Seems like bower installs the v4, try specifying the version in the install command
