### ISSUE TITLE
!important tag overriding Nav-Tab color and border styles 

### ISSUE THREAD

**Issue by calvin-smith** [mdbootstrap/mdb-ui-kit#1083]
#### Test Case

http://codepen.io/onotadaki/pen/vXOara
#### Summary

The !important tag on nav-tabs border and color makes it impossible to change text color or reorient the tabs.
#### Expected result

The color and border should be high priority, but custom stylesheets specifying those attributes should not be ignored.
#### Additional Information

This was posted earlier and closed during cleanup
https://github.com/FezVrasta/bootstrap-material-design/issues/598

**Comment by FezVrasta** [comment]
Can you reproduce it with v4?

**Comment by calvin-smith** [comment]
This seems to no longer be an issue with v4.

**Comment by FezVrasta** [comment]
Ok then if someone wants to send a PR for the v3 it's fine, but I'm not planning to work on it.
