### ISSUE TITLE
Let the docs breathe XD 

### ISSUE THREAD

**Issue by cquanu** [mdbootstrap/mdb-ui-kit#1085]
#### Summary

I feel that all the contents in the `.card-container` in v4 docs should be "contained/wrapped" with additional `.container`. Currently it looks very tight. 
#### Screenshots

**Before**
<img width="948" alt="nocontainer" src="https://cloud.githubusercontent.com/assets/16508884/18395944/98accfde-76f3-11e6-99ef-d6bb811f1ffc.PNG">
**After**
<img width="948" alt="container" src="https://cloud.githubusercontent.com/assets/16508884/18395945/98ad3e92-76f3-11e6-8fa2-fde88bcfea94.PNG">
#### It's like ...

**Before**

```
<div class="container card-container">
...
</div>
```

**After**

```
<div class="container card-container">
    <div class="container">
    ...
    </div>
</div>
```

What do you think?

**Comment by FezVrasta** [comment]
Doing so the alignment is compromised. Better to add some more padding on the card-container class maybe

**Comment by cquanu** [comment]
Yea what I meant was add more padding. Thanks!
