### ISSUE TITLE
Trigger ripples from js

### ISSUE THREAD

**Issue by Kwaadpepper** [mdbootstrap/mdb-ui-kit#1086]
I could not find a way to do it, but it seems to me that would be possible, I saw in another ticket that we can ad ripple effect to anything using $.material.ripples('.class').

I tried $('#test').ripples('play') without success, any ideas ?

**Comment by FezVrasta** [comment]
It's not supported but it would be really cool!

**Comment by fredgrott** [comment]
something I think most of us would use
