### ISSUE TITLE
Compatabiltity issues between AngularStrap and Bootstrap-Material-Design?

### ISSUE THREAD

**Issue by Rex90** [mdbootstrap/mdb-ui-kit#1088]
I am using [AngularStrap](http://mgcrea.github.io/angular-strap/#) with [Material Design for Bootstrap](http://fezvrasta.github.io/bootstrap-material-design/). For the most part this seems to be working fine but I am finding that the animations provided by AngularStrap are not working, for example for modals and popovers. Is there a known or can someone think of a known compatiabilty issue between these too? I can'think of what else the issue might be. I have included ngAnimate as part of my project.

bower.json

```
"angular-animate": "^1.5.8"
```

index.html

```
<script type="text/javascript" src="bower_components/angular-animate/angular-animate.js"></script>
```

Angular dependencies

```
var app = angular.module('appName', [
    'ng',
    'ui.router',
    'ngCookies',
    'ngAnimate',
    'ngHandsontable',
    'ngStorage',
    'base64',
    'ngWebSocket',
    'angular-loading-bar',
    'wu.masonry',
    'angularSpinner',
    'mgcrea.ngStrap',
    'nvd3',
    'angularMoment',
    'ng.jsoneditor'
]);
```

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support ?
