### ISSUE TITLE
V4: "No Compatible version Found" Error

### ISSUE THREAD

**Issue by tankerkiller125** [mdbootstrap/mdb-ui-kit#1089]
#### Test Case

Running `npm install bootstrap-material-design@4.0.2`
#### Summary

Error: "No compatible version found: bootstrap-material-design@4.0.2"
NodeJS: 6.5.0
NPM: 3.10.3
#### Expected result

Successful installation.

**Comment by FezVrasta** [comment]
Most likely we not yet released it on npm, you can always refer to the branch name tho

**Comment by Danilo-Araujo-Silva** [comment]
When you say `refer to the branch name tho` what you mean?
Is there a package.json or npm or yarn configuration to install it? If yes, how is it?

**Comment by FezVrasta** [comment]
Use this as package URL:

```
git@github.com:FezVrasta/bootstrap-material-design.git#master
```
