### ISSUE TITLE
Ripple effect doesn't work under Safari & Firefox

### ISSUE THREAD

**Issue by Isabellle** [mdbootstrap/mdb-ui-kit#1097]
#### Test Case

http://codepen.io/isabellle/pen/wzqbXz
#### Summary

Firefox 49.0.1 - The ripple effect doesn't work
Safari Version 9.1.2 - Same, the ripple effect doesn't work
#### Expected result

The ripple effect as seen on Google Chrome

**Comment by FezVrasta** [comment]
I could test it with Safari 10, Firefox 48 and Firefox 49. The ripple effect is properly displayed.

May you give me more insights?

**Comment by Isabellle** [comment]
Sorry for the delay of my answer. So what I've just seen is that it works on all browsers with the codepen link provided, but not when browsing this http://fezvrasta.github.io/bootstrap-material-design/#checkbox - Which is the code I've been using. Are there any changes that should be integrated?

Thanks a lot,

**Comment by FezVrasta** [comment]
Ok I can reproduce it. Probably there's some missing script in the docs...

**Comment by edwardpayton** [comment]
Hey, 

I can reproduce the issue

Clicking the radio triggers the ripple, but the effect is different in Firefox than Chrome. The ripple doesn't expand from the click point. 

The Codepen works correctly, the docs do not.

Steps to reproduce
Click near the radio button but not centered on it
The ripple effect will trigger
In Chrome the effect will expand from at the click point
In Firefox (47) the effect will expand from the center of the radio button
