### ISSUE TITLE
Where would I add this extra jquery code

### ISSUE THREAD

**Issue by devouk** [mdbootstrap/mdb-ui-kit#1098]
Hi, sorry I am a bit of a novice and would like to add the following code so I have a fixed footer appear when scrolling down so I can add a back to top on a page.

Is there a particular file which is already called to add the custom code in , or do I alter the page template.

Thanks

```
$(document).scroll(function () 
{
  var position = $(this).scrollTop();
  if (position > 800) 
     {
     $('.footer').fadeIn();
     } 
  else 
     {
     $('.footer').fadeOut();
     }
  });    

```

**Comment by FezVrasta** [comment]
Hi, this bug tracker is meant to track bugs or feature requests of this library. You can ask on www.stackoverflow.com about your problem.
