### ISSUE TITLE
Form on change seems broken (v4)

### ISSUE THREAD

**Issue by Izopi4a** [mdbootstrap/mdb-ui-kit#1102]
#### Test Case

http://codepen.io/anon/pen/rrdxYA?editors=1111
#### Summary

just focus one of the inputs
#### Expected result

no firing change event milion of times
#### Additional Information

if you comment this line $('body').bootstrapMaterialDesign({}); its working fine.

what jQuery does is loop trough all elements and 

``` js
if ($element.val() !== $element.attr('value')) {
    $element.trigger('change');
}
```

and when its broken val is returning "" while attr("value") is undefined. 

I dont think i can fix that

//tested with chrome/windows only

**Comment by FezVrasta** [comment]
have you tried disabling `autofill` option?  Seems the case.

**Comment by Izopi4a** [comment]
can you expalin a bit more what should i disable cuz i am not sure .. please

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/bootstrap-material-design#functions

```
$.material.options.autofill = false;
```

**Comment by Izopi4a** [comment]
ahaaaa, missed that one. Sorry :D
