### ISSUE TITLE
drowndown does not work with angular2 

### ISSUE THREAD

**Issue by davidmontgom** [mdbootstrap/mdb-ui-kit#1103]
copied a pasted your nav bar example.  How do I deal with the href in the dropdown?

This does not work with angular2.  I did do the below:

 ngOnInit(){
     $.material.init();
  }

Page with the nav is at http://localhost:4200/#/dashboard

```

<ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a  href="." data-target="#" class="dropdown-toggle" data-toggle="dropdown">Slugs 
            <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="javascript:void(0)">Action</a></li>
            <li><a href="javascript:void(0)">Another action</a></li>
            <li><a href="javascript:void(0)">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="javascript:void(0)">Separated link</a></li>
          </ul>
        </li>

        <li><a (click)="logout()">Logout</a></li>
      </ul>

```

**Comment by davidmontgom** [comment]
never mind resolved

**Comment by haninaguib** [comment]
What was causing your problem. I am having a similar issue, it was working fine until I upgraded to a new version of angular-cli. I suspect my problem has to do with how jquery is being loaded although all other aspects of bootstrap-material seem to be working (ripples etc...)
