### ISSUE TITLE
Textbox floating label not detecting being filled by non-keypress events

### ISSUE THREAD

**Issue by Bitz** [mdbootstrap/mdb-ui-kit#1104]
#### Test Case

http://codepen.io/bitz/pen/kkAZJx
With typeahead.js: https://gfycat.com/HalfSelfassuredJay
#### Summary

By using typeahead or any other method of auto-filling a textbox (in this case using `$('#i1').val("Test");`), label will still fall back as though the textbox is empty
#### Expected result

On value change '`$('element').change` instead of what seems to be keydown detection.

**Comment by FezVrasta** [comment]
JS can't detect input values change if they are triggered by JS itself. You have to manually call `trigger('change')` on the input after you change its value.
