### ISSUE TITLE
v4: Base-level rules cannot contain the parent-selector-referencing character &

### ISSUE THREAD

**Issue by julkue** [mdbootstrap/mdb-ui-kit#1107]
When compiling bootstrap-material-design I'll get the following error:

```
error styles/main.scss (Line 121 of node_modules/bootstrap-material-design/scss/mixins/_forms.scss: Base-level rules cannot contain the parent-selector-referencing character '&'.)
```
#### Expected result

Should compile silently without errors.
#### Additional information

I'm compiling using `grunt-contrib-compass`: `^1.1.1`.

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/bootstrap-material-design/issues/957
