### ISSUE TITLE
Shadow (z-depth) helpers

### ISSUE THREAD

**Issue by fracz** [mdbootstrap/mdb-ui-kit#1109]
What do you think about z-depth helpers like in [MaterializeCSS](http://materializecss.com/shadow.html)?

[Source](https://github.com/Dogfalo/materialize/blob/d7c8d444260784b4f306d14f0f6462b07991d752/sass/components/_global.scss#L58).

**Comment by FezVrasta** [comment]
I think we already have something like that...

**Comment by fracz** [comment]
How are they called then? I could not find anything similar in [the examples](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html).

**Comment by FezVrasta** [comment]
You should be able to use these classes if I'm not wrong:

https://github.com/FezVrasta/bootstrap-material-design/blob/master/less/_shadows.less

**Comment by fracz** [comment]
These are mixins, i.e. they do not generate classes like `shadow-z1`, `shadow-z2` OOTB. I can use them in less but I can't use them in HTML like `<div class="navbar shadow-z1">`.

**Comment by FezVrasta** [comment]
Feel free to send a PR.

**Comment by FezVrasta** [comment]
closed for inactivity = nobody seems interested in this

**Comment by djsegal** [comment]
I'm interested in this :(

-----

could probably do something a la:

+ https://codepen.io/sdthornton/pen/wBZdXq
