### ISSUE TITLE
The way to choose what elements will be injected ripple effect

### ISSUE THREAD

**Issue by anhtran** [mdbootstrap/mdb-ui-kit#111]
Pleasure to use the plugin like this:

```
 ('a.btn').ripple();
```

This is also useful for mobile cases. I don't have to touch twice on a ripple button.

```
 if(isTouchDevice() === false) {
        ('a.btn').ripple();
 }
```

Thanks!

**Comment by FezVrasta** [comment]
Ok had time to look into this... I can't really see the difference between what is currently implemented, may you make it more clear? Thanks.

**Comment by FezVrasta** [comment]
With c26d5e3ce17eb41aa00628e1d26a178b589a824b I've rewritten the entire Material.js structure, now you have to init it manually and you can configure about everything about it. Should be completely solved here.
