### ISSUE TITLE
Material.js + datetimepicker

### ISSUE THREAD

**Issue by arjuneyy** [mdbootstrap/mdb-ui-kit#1110]
![datetimepicker](https://cloud.githubusercontent.com/assets/12705617/19954728/c2a216ea-a1b5-11e6-914a-18793a348966.gif)

Hello in reference to this issue https://github.com/Eonasdan/bootstrap-datetimepicker/issues/717:

I tried: 
$.material.options.autofill = false;

but still it doesn't solve the issue. I still have to wait for several seconds before I can choose a date. Can you please help me with this one? Thanks :)

**Comment by FezVrasta** [comment]
It could be related to the auto-fill detection, there's an option to disable it. Set `material.options.autofill` to false
