### ISSUE TITLE
Help getting started with v4

### ISSUE THREAD

**Issue by mikegleasonjr** [mdbootstrap/mdb-ui-kit#1114]
I installed v4 using npm: `npm install fezvrasta/bootstrap-material-design#v4-dev`

When I import 'bootstrap-material-design' I get **Error: Cannot find module 'bootstrap-material-design'** even though it's in the 'node_modules' folder..

(Using es6 with babelify and browserify)

**Comment by FezVrasta** [comment]
prepare a repository with all the setup to reproduce your problem please. Closing for now untill you provide the needed setup. thanks.

**Comment by mikegleasonjr** [comment]
Sorry I tried to transpile the package that was in the node_modules folder which babel ignores
