### ISSUE TITLE
Need to Change Primary color

### ISSUE THREAD

**Issue by anandbohra** [mdbootstrap/mdb-ui-kit#1115]
HI,
I have downloaded the project & liked it very much.
I want to change primary color from Teal to Brown
I have no idea bout grunt or npm or bower etc etc.
I am working on Windows machine & using VS2013 as IDE, please tell me how to get full compiled CSS in Brown color instead of TEAL color.

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/bootstrap-material-design#compile-your-customized-distributable

**Comment by anandbohra** [comment]
since last 3 hours I am reading all but I dont know how to use either npm or bower or even install these 2.
pl send me step by step as to what do i need to install on my Windows machine to change css color from teal to brown

**Comment by FezVrasta** [comment]
ask on stackoverflow, this section is ONLY to report BUGS
