### ISSUE TITLE
Less & Sass not working on VS2013

### ISSUE THREAD

**Issue by anandbohra** [mdbootstrap/mdb-ui-kit#1116]
Hi I am using VS 2013 & none of the given less or sass files compiles on VS 2013.
pl help I want to change primary color from teal to brown

less error
Compilation Error occurred (see error list to navigate to the error location):
Error found at line 6, column 40:

pl helpt

**Comment by FezVrasta** [comment]
sorry I don't use VS 2013, try to reproduce the setup of this repository

**Comment by anandbohra** [comment]
![error](https://cloud.githubusercontent.com/assets/6223597/20102221/50637990-a5eb-11e6-8d34-19823ef0c415.png)
pl see above image, I followed instruction from 
http://ericnish.io/blog/compile-less-files-with-grunt/

**Comment by FezVrasta** [comment]
Sorry, really, I would LOVE to help all the people with a problem with their computer on the planet, but I'm only one, with nobody that helps me on this project.

I can't really help you all, if you have a problem with my project, fill the issue template and I will be SUPER HAPPY to help.
For anything else, use StackOverflow.

**Comment by anandbohra** [comment]
I do really appreciate your time & efforts but try to compile on new fresh machine as new user & you will see what the problem a normal user is facing.
since yesterday i have spend my 6 hours & finally with confidence says there is something glitchy in provided zip files
i got simple example where using node we have to just type lessc lessfilename > resultCssname & even that too didnt worked.
see error below.
![less compilation error](https://cloud.githubusercontent.com/assets/6223597/20130631/342881e2-a67e-11e6-942c-aca910f0e227.png)

**Comment by anandbohra** [comment]
Finally I did it.....

scanned over 100 articles on web, fixed 2 lint issues & ultimately it worked & I got my brown theme.

https://github.com/twbs/bootlint/wiki/E046

Again thanks for this awesome product.

**Comment by emman-ok** [comment]
Pls you got to share with me how you did. I have been on this less sass compilation thing for more than 24hrs now. Will appreciate it if you help. Thanks

**Comment by anandbohra** [comment]
from my side, today again i have recreated all steps to make it working again.

wherever in node you get error just google for "error in node" like if it says grunt command not found then google "grunt for node"

[Bootstrap Material Design - New CSS Steps.docx](https://github.com/FezVrasta/bootstrap-material-design/files/594692/Bootstrap.Material.Design.-.New.CSS.Steps.docx)
