### ISSUE TITLE
Selectize not rendering not-allowed for disabled elements

### ISSUE THREAD

**Issue by whelaro** [mdbootstrap/mdb-ui-kit#1119]
#### Test Case 
update to v3 template - http://codepen.io/anon/pen/mOEwdw

#### Summary
If a selectize element is disabled, the cursor still renders as cursor: text

#### Expected result
the element should be cursor: not-allowed like it is with input type=text (including an example in the test case for comparison).

#### Additional Information
http://codepen.io/anon/pen/zoBzGY
I was able to remedy this by adding to the css (derived from selectize's css but replacing with not-allowed):
`.selectize-input.disabled,
.selectize-input.disabled * {
  cursor: not-allowed !important;
}`

**Comment by RobertJGabriel** [comment]
Will do this

**Comment by whelaro** [comment]
I'll see if I can figure out why, but I notice that in IE (at least IE11), the disabled selectize still allows selection. You can render the 2nd codepen in IE to reproduce it. Will look and report back if I find out why. Chrome behaves as one would expect it to.

**Comment by whelaro** [comment]
And I figured it out (at least, this changed the behavior so that it worked like I see it in Chrome). I notice there is a comment in this particular section of material.js (" // this is showing as undefined on chrome but works fine on firefox??") so maybe this will resolve what is being discussed there as well.

I set a breakpoint on line 35 and looked at $element. It is pointing at a parent div. so I essentially updated the block as so:

```
function _addFormGroupFocus(element) {
    var $element = $(element);
    if ($element.is('div')) $element = $element.find('input'); // may want to tune if there's the possibility of more than one input being generated by the library.

    if (!$element.prop('disabled')) {  // this is showing as undefined on chrome but works fine on firefox??
      $element.closest(".form-group").addClass("is-focused");
    }
  }
```
