### ISSUE TITLE
Cannot Compile Less. Have Tried More Than 3 different compilers

### ISSUE THREAD

**Issue by emman-ok** [mdbootstrap/mdb-ui-kit#1120]
C:\Users\Emman\Desktop\bootstrap-material-design-master\less\bootstrap-material-design.less
NameError: variable @line-height-base is undefined in C:\Users\Emman\Desktop\bootstrap-material-design-master\less\_variables.less on line 75, column 37:
74 //** Unit-less `line-height` for use in components like buttons.
75 @mdb-input-line-height-base:        @line-height-base; //1.428571429; // 20/14
76 //** Computed "line-height" (`font-size` * `line-height`) for use with `margin`, `padding`, etc.

**Comment by FezVrasta** [comment]
closing since the issue template has not been respected. feel free to open a new one following the rules.

**Comment by larikitty** [comment]
srsly?! :-1: :disappointed:
