### ISSUE TITLE
Bower BMD Bootstrap v3 only

### ISSUE THREAD

**Issue by varunagrawal** [mdbootstrap/mdb-ui-kit#1125]
When I try to install `bootstrap-material-design` using bower as given in the README, it defaults to using  Bootstrap 4 which is causing errors on my webpage as well giving me a hard time precompiling assets on Rails.

Can you please provide the way in which I might install BMD with only the Bootstrap v3 dependency?

**Comment by FezVrasta** [comment]
you may need to specify the version.

```
bower install bootstrap-material-design@v0.5.10
```

**Comment by varunagrawal** [comment]
Thanks @FezVrasta!
