### ISSUE TITLE
Dropdown not working.

### ISSUE THREAD

**Issue by Lycantant** [mdbootstrap/mdb-ui-kit#1127]
I apologize if there is already a post like this before.
Dropdown I took directly from this link, http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#navbar
and after I use it did not work as it should.
This is a dropdown that I use: https://codepen.io/Lycantant/pen/rWYQXL
I'm sorry for my bad grammar.
Thanks :)

**Comment by ghost** [comment]
Hello, common bootstrap user here and this may be unrelated. But make sure that you have bootstrap.js included in your scripts, as this is a dynamic event.

**Comment by Lycantant** [comment]
i was include this script to my code : https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js

**Comment by FezVrasta** [comment]
you MUST use the codepen templates provided by our issues template. If you used them, you would have noticed that you are not including jQuery.
