### ISSUE TITLE
Floating labels + input-group-addon

### ISSUE THREAD

**Issue by DarthLegiON** [mdbootstrap/mdb-ui-kit#1129]
#### Test Case 
http://codepen.io/anon/pen/Lbegro

#### Summary
I think you should invent behaviour for label-floating fields with prepending addons. It looks ugly now. 

#### Expected result
Default label position should be in a field, not over addon.

#### Additional Information
Maybe there are simple temporary solutions? I found no options by now.

**Comment by whelaro** [comment]
The animation could use some work (probably due to the transition to the end point for label. CSS isn't my strong point but could possibly just force it to move upwards x pixels by default) , but moving the label to before the input seems to fix the initial overlap: http://codepen.io/anon/pen/pNKobe

**Comment by DarthLegiON** [comment]
@whelaro I think this problem has no pure CSS solution because lifting effect works on simple changing position of label near left border of `.form-group` element. JS sounds good, but I should append Bootlint to my project. Interesting...
I think this issue shouldn't be closed for now, let's wait for official solution. Thanks!

**Comment by whelaro** [comment]
Oh, not saying what I sent would be the solution, just that it gets it part of the way (the label aligns with the input and not overlapping the icon). Considering the label is in relation to the textbox itself and not to the input group as a whole, I think realigning the HTML to get proper (initial) alignment doesn't butcher the intent (if anything, it reinforces it).

**Comment by DarthLegiON** [comment]
@FezVrasta this label means this bug will be fixed only in v4?

**Comment by FezVrasta** [comment]
It means the bug targeted only v3 and in v4 is not valid. If it's not the case please open a new ticket
