### ISSUE TITLE
CSS effects is applied on two seperate input Elements in the same form-group

### ISSUE THREAD

**Issue by haddyo** [mdbootstrap/mdb-ui-kit#1132]
CSS transition effect is applied on the 2 different input elements in the same form group.
This issue is not available in bootstrap. When i select one input element, automatically the other element has the transition style applied.
Please look into the image for better understanding.

![image](https://cloud.githubusercontent.com/assets/24606061/21261281/6036f030-c3b0-11e6-9c1d-dd982fc0d7f4.png)

note: I'm not looking for an workaround

**Comment by FezVrasta** [comment]
closing because you have not followed the issues template
