### ISSUE TITLE
CSS effects is applied on two seperate input Elements in the same form-group

### ISSUE THREAD

**Issue by haddyo** [mdbootstrap/mdb-ui-kit#1133]
#### Test Case 
http://codepen.io/haddyo/pen/rWoLJN

#### Summary
CSS transition effect is applied on the 2 different input elements in the same form group.
This issue is not available in bootstrap. When i select one input element, automatically the other element has the transition style applied.

#### Expected result
Only one input field should be selected and highlighted

**Comment by FezVrasta** [comment]
Running your code in http://www.bootlint.com/ a lot of errors pop out. May you fix them and see if the error gets fixed?

Thanks.

**Comment by haddyo** [comment]
I'm not sure why the bootlint throws errors on line:1147 where as my code is only 10 lines. Please view the codepen once and then decide, whether its an bug or my coding mistake.

http://codepen.io/haddyo/pen/zoeGxp

**Comment by FezVrasta** [comment]
Doing so it works, there was some Bootlint errors.

http://codepen.io/FezVrasta/pen/MbLwOr
