### ISSUE TITLE
On including <footer>, webpage stop responding

### ISSUE THREAD

**Issue by sahilbabbar** [mdbootstrap/mdb-ui-kit#1136]
Hi,

On including the `footer` tag in AngularJS(1.x) app, the webpage stops responding and stares at a blank screen. And removing `footer` and using `div` instead, works fine. How is that happening?

**Doesn't Work**
```
<footer class="footer">
      <div class="container">
         <p class="text-muted">Place sticky footer content here.</p>
      </div>
</footer>
```

**Works Fine**
```
<footer class="footer">
      <div class="container">
         <p class="text-muted">Place sticky footer content here.</p>
      </div>
</footer>
```

What's the problem?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
