### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: #     When I use dropdown menu with jquery-3.1.1

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#1137]
#### Test Case 
when I user copy dropdown menu from http://fezvrasta.github.io/bootstrap-material-design/#navbar, I got the problem:
 `jquery.min.js:2 Uncaught Error: Syntax error, unrecognized expression: #
    at Function.ga.error (jquery.min.js:2)
    at ga.tokenize (jquery.min.js:2)
    at ga.select (jquery.min.js:2)
    at Function.ga [as find] (jquery.min.js:2)
    at r.fn.init.find (jquery.min.js:2)
    at r.fn.init (jquery.min.js:2)
    at r (jquery.min.js:2)
    at b (bootstrap.min.js:6)
    at HTMLAnchorElement.g.toggle (bootstrap.min.js:6)
    at HTMLDocument.dispatch (jquery.min.js:3)`

#### Summary
with  jQuery v3.1.1

**Comment by ghost** [comment]
my dropdown menu code:
`<li class="dropdown">
                   <a href="#" data-target="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown
                        <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="javascript:void(0)">Action</a></li>
                        <li><a href="javascript:void(0)">Another action</a></li>
                        <li><a href="javascript:void(0)">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Dropdown header</li>
                        <li><a href="javascript:void(0)">Separated link</a></li>
                        <li><a href="javascript:void(0)">One more separated link</a></li>
                    </ul>
                </li>`

**Comment by lbfreeze** [comment]
when I use jQuery-1.10.2 , I got same error.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by liyi-david** [comment]
@lbfreeze  I've noticed the same issue. It may be caused by using higher version of jQuery. In my case (I was using laravel and it use jquery 3.1 as default option), I switch to jQuery 1.12.4 and it works soon.

Hope it'll help you :)

**Comment by FranciscoSalesCarvalho** [comment]
@liyi-david it worked so well. Thanks!

**Comment by trickly** [comment]
@FezVrasta Are there any plans to fix this without having to downgrade jquery?

**Comment by FezVrasta** [comment]
PRs to fix the incompatibility are more than welcome!

**Comment by janhelly** [comment]
@liyi-david это не решение проблемы. Что вы будете делать когда необходимо будет тот же слайдер со свайпами подключить. Вообще в целом дурной совет, извините

**Comment by bpgusar1** [comment]
**SOLVED**

OPEN bootstrap.min.js

FIND
` n || (n = t.attr("href"), n = n && /#/.test(n) && n.replace(/.*(?=#[^\s]*$)/, "")), r = n && e(n);`

AND REPLACE
`n || (n = t.attr("href"), n = n && /#/.test(n) && n.replace(/.*(?=[^\s]*$)/, "")), r = n && e(n);`

**Comment by FezVrasta** [comment]
yeah... great fix

**Comment by MaungC** [comment]
i think you need your jquery.min.js is top of scripts and than bootstrap.min.js or bootstrap.js that will be work any jquery version is work. So hope this work
