### ISSUE TITLE
Dynamic checkboxes

### ISSUE THREAD

**Issue by Branksy** [mdbootstrap/mdb-ui-kit#1138]
Hi, how can I initialise dynamic checkboxes with bootstrap material design.
Simply doing $.material.init(); is not enough, or rather it replicates existing rendered checkboxes. How can I bind the action just to new ones? Thank you.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
