### ISSUE TITLE
Sass compiling issue....missing bootstrap/variables

### ISSUE THREAD

**Issue by runningrandall** [mdbootstrap/mdb-ui-kit#1142]
When compiling the scss I'm getting the following error:

Module build failed: ModuleBuildError: Module build failed:
@import "bootstrap/variables";

This statement resides in _import-bs-sass.scss.

I installed via npm. I'm going to upload my code base to github.

**Comment by runningrandall** [comment]
https://github.com/runningrandall/myriad-style-guide

**Comment by SergeyKhval** [comment]
look here: https://github.com/FezVrasta/bootstrap-material-design#bower

**Comment by doopz** [comment]
@runningrandall, i had a similar error and I ended up fixing the issue by using the less files instead. They compile without errors. I'm using npm.

**Comment by FezVrasta** [comment]
Sorry guys but without a MINIMAL reproducible example of the problem I can't really help you.

**Comment by juanibiapina** [comment]
Just import the sass version with webpack. There is no way to resolve `@import "bootstrap/variables";`. Where is this file expected to come from?

**Comment by FezVrasta** [comment]
> When using SASS, @import directives cannot be interpolated. Given the variety of configurations, the typical bower_components directory is occasionally in a different location. Given the options, a loadPath was added to the SASS compiler so that bootstrap files could be loaded without specifying the path to the bower_components directory. You may similarly need to add a load path to your compiler. It is still debatable if this is for the greater good, but seems like the only way to accommodate multiple configurations.

https://github.com/FezVrasta/bootstrap-material-design#bower
