### ISSUE TITLE
Checks for document.arrive but later it uses $document.arrive

### ISSUE THREAD

**Issue by mrforsythexeter** [mdbootstrap/mdb-ui-kit#1143]
#### Test Case 
Cannot reproduce on codepen (load order issues)

#### Summary
The init checks for `document.arrive`, if its there, it then tries to attach the events with the `$document` var (jQuery object), this doesn't have the arrive function on it.

#### Expected result
Use the correct function

#### Additional Information
I have updated this in a local copy of mine and its working as expected when using document.arrive instead of $document.arrive.

**Comment by FezVrasta** [comment]
I need more details, I don't understand what's the problem and why you can't reproduce it 🤔

**Comment by mrforsythexeter** [comment]
I Just needed to work a little harder...

#### Codepen URL
http://codepen.io/shaunfpennedin/pen/PWJOxz

#### Error
This is from the console.
`Uncaught TypeError: $document.arrive is not a function (Material.js:323)`

#### Apologies
I would have created a pull request, but I am right up to my eye balls at the second... can do this later if required.

**Comment by FezVrasta** [comment]
Ok I see, thank you for the test case.

The problem is here:
https://github.com/FezVrasta/bootstrap-material-design/blob/master/scripts/material.js#L321-L323

**Comment by Toilal** [comment]
This issue is blocking for anyone using this project in a SPA framework. Could you perform a new release ?

**Comment by FezVrasta** [comment]
I'd like to but I have no idea of how the deploy process works. A different contributor maintained the project for several months but the build/publish process isn't quite clear...

**Comment by Toilal** [comment]
Ho I see :(

Maybe we could ask @rosskevin ? You also need the npm rights for the package published on [npmjs.com](https://www.npmjs.com/).

My current workaround is to copy/paste the javascript source files in my own project and apply the commit from this issue.

**Comment by FezVrasta** [comment]
I *should* already have the rights to publish to npm.

**Comment by Toilal** [comment]
Please tell me if you want to migrate this project to webpack 2, I could help when I have few hours free.

**Comment by FezVrasta** [comment]
v3 isn't maintained anymore, I'm currently rewriting v4 from "scratch" because the current code base is too complex and I really want to end up with a final release in time for the first beta.

**Comment by Toilal** [comment]
Ok ! good luck :) I hope the v4 will be as good as the previous one.

**Comment by FezVrasta** [comment]
Changed my mind actually... lol
https://github.com/FezVrasta/bootstrap-material-design/issues/1166

The code base is messy but good enough for now, we can improve it incrementally.

**Comment by Symbianx** [comment]
So.. Will this be pushed? I'm on Angular + Webpack, and all the solutions to get this theme working is with Arrive.js. Since v3 isn't maintained and has this bug, you are dropping support for Angular + Webpack until v4?

**Comment by Spetnik** [comment]
~~Weird. I had to do the opposite to get it working (using Webpack). I had to change "document" to "$document".~~ Never mind - this seems to be because of an issue using XHTML
