### ISSUE TITLE
Programmatically turn ripples off  

### ISSUE THREAD

**Issue by rzb** [mdbootstrap/mdb-ui-kit#1144]
For instance, I have a .list-group that expands on click and becomes a form. Is there any way to turn ripples on/off programmatically on click so that the effect is not seem when the list item is expanded?

It'd also be useful for buttons that become disabled depending on some action, etc.

**Comment by FezVrasta** [comment]
no there's not a way atm.

**Comment by rzb** [comment]
I'll try toggling .withoutripple class and calling init() again when I get to my pc. Can you think of any collateral damage?

If that doesn't work I might dig deeper in the plugin and make a pull request if you're interested in that feature.

**Comment by FezVrasta** [comment]
I think it should work. a PR would be much better tho

**Comment by rzb** [comment]
Toggling `.withoutripple` and calling `init()` didn't work because the listeners must be removed.

I solved it with:

`$('.element-using-ripples').off().data('plugin_ripples', null);`

To remove ripples from the element. Then:

`$.material.ripples('.element-using-ripples');`

To add them back.

I'll think of a native approach for the PR.
