### ISSUE TITLE
Could it work without jquery for a reactjs application?

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [mdbootstrap/mdb-ui-kit#1148]
Not a bug. Since using jquery defeats the whole purpose of using a library like reactjs, would be interested in a version of this css framework that does not use jquery, just like React-Bootstrap. 

----

#### Test Case 
None.

#### Summary
Looking for a bootstrap material design framework version that could work for reactjs. There is react-bootstrap and there is material-ui reactjs components. Trying to find the best of both the worlds in a single library. Hence the interest.

#### Expected result
None.

#### Additional Information
None.

**Comment by FezVrasta** [comment]
you can easily replace the JavaScript shipped with this library and create custom components that implement the same functionalities

**Comment by Rajiv-Kulkarni** [comment]
Not sure how I could go about doing that. You mean split up the material.js and the ripple.js into components? Could you give an example? Any plans on creating a react-bootstrap like library from the bootstrap-material-design? Thanks.

**Comment by FezVrasta** [comment]
No I have not plans to write React components for this library.

It's fairly easy, for reference, this is the stuff needed by each `input` element:
https://github.com/FezVrasta/bootstrap-material-design/blob/master/scripts/material.js#L127-L182

You just have to convert those scripts to React components making sure the `Input` component implements them.

**Comment by FezVrasta** [comment]
A naive approach would be to simply call the `material.init` on the component in the `componentDidMount` hook,

You would have:

```
class MDInput extends Component {
  componentDidMount() {
    $.material.input(this);
  }

  render() {
    return <input {...this.props} />;
  }
}
```

But I'm not sure if it has side effects.
