### ISSUE TITLE
ctrl + p  not wrking  

### ISSUE THREAD

**Issue by rmnkt** [mdbootstrap/mdb-ui-kit#1149]
![02082017](https://cloud.githubusercontent.com/assets/25636003/22735491/f205a346-ee1f-11e6-87c8-f8dc12188568.png)
 I am new for this framework . 
designed form using materialcss and wanted to print as it is . ( ctrl + p ) if we want to print current page developed in material design its not working . i just want form  as it was designed..

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by rmnkt** [comment]
:(
