### ISSUE TITLE
Well Moving in Grid after setting position fixed / bs affix

### ISSUE THREAD

**Issue by milefork** [mdbootstrap/mdb-ui-kit#1150]
#### Test Case 
http://codepen.io/anon/pen/LxXpav

#### Summary

After creating a affix for the outer columns of my grid the width changes when starting scroll.

#### Expected result
Fixed width

#### Additional Information
As for reference because there is not the same behavior in code pen I took 2 pics to show the error:

1: http://pasteboard.co/wB1ghEOAv.png scrolled to top -> no fixed
2: http://pasteboard.co/wB1WmGj8X.png scrolled a little -> width changes and hit other col.

**Comment by FezVrasta** [comment]
I simply forked your pen removing the theme and leaving just bootstrap, and there is still the problem, so I would exclude is related to my theme.

http://codepen.io/FezVrasta/pen/ggQreB
