### ISSUE TITLE
Sass compiling and changing variables

### ISSUE THREAD

**Issue by sssf90** [mdbootstrap/mdb-ui-kit#1152]
Okay, i am using bootstrap and this library via SASS. I have made file where i imported two files
`@import "bootstrap"; 
  @import "bootstrap-material-design";
`

Unfortunately, i can't change anything in original theme. For example, i am trying to change primary color to pink. For this i change _variables.scss to some color from _color.scss but nothing happens. Is it ok? Chrome shows that it takes color from _mixins file. Help me please

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.

**Comment by g8d3** [comment]
Is there a link showing how to customize colors?

**Comment by FezVrasta** [comment]
Read the README
