### ISSUE TITLE
v4: Input on change event is fired like oninput event

### ISSUE THREAD

**Issue by gargaseem** [mdbootstrap/mdb-ui-kit#1153]
I have added a v4-branch code in my project and when I added a onChange event, it is not fired on tabout rather it fired as onInput (keydown event).
I need to clear the input if it is not selected from drop down. Please help me with the same.

Please refer the following example:
http://codepen.io/aseemgarg/pen/ygWZyV

I debug this further and realize that **form** tag is causing this issue. How can we solve this issue?

I have added **form tag** to your example: (http://codepen.io/aseemgarg/pen/xgNMKY)

**Comment by gargaseem** [comment]
@FezVrasta Any update?

**Comment by FezVrasta** [comment]
I don't understand what are you trying to do, to clean the input state and restore the label position you have to trigger the `change` event manually because there's no any way to let the input know that its content is changed if you changed it with JS.

**Comment by gargaseem** [comment]
Hi,

No, I don't want to clean the input state, rather I need to validate the input and clean it if it is not valid (on focus out only if the input is changed). 
$(input).change() should solve this but if I am using this method inside the form, this method is called like onkeypress.

In my case, I am using it to validate google places, and I want to clear the input if user has not selected the place from dropdown.

Please let me know if I am able to explain the bug or not.

Thanks
Aseem.

**Comment by gargaseem** [comment]
Please refer this link:
http://codepen.io/aseemgarg/pen/ygWZyV

I have 2 input fields and added change event on both fields but the event is working differently on both fields.
On first field, input is getting cleared as soon as I am entering any value where as on second field, input is getting cleared on focus out.

**Comment by gargaseem** [comment]
Hi,

No, I don't want to clean the input state, rather I need to validate the
input and clean it if it is not valid (on focus out only if the input is
changed).
$(input).change() should solve this but if I am using this method inside
the form, this method is called like onkeypress.

In my case, I am using it to validate google places, and I want to clear
the input if user has not selected the place from dropdown.

Please refer this link:
http://codepen.io/ <http://codepen.io/aseemgarg/pen/ygWZyV>aseemgarg
<http://codepen.io/aseemgarg/pen/ygWZyV>/pen/
<http://codepen.io/aseemgarg/pen/ygWZyV>ygWZyV
<http://codepen.io/aseemgarg/pen/ygWZyV>

I have 2 input fields and added change event on both fields but the event
is working differently on both fields.
On first field, input is getting cleared as soon as I am entering any value
where as on second field, input is getting cleared on focus out.

Please let me know if I am able to explain the bug or not.

Thanks
Aseem.

**Comment by FezVrasta** [comment]
Ask on StackOverflow, this place is only for bug reports.

**Comment by gargaseem** [comment]
@FezVrasta I am sorry.
But I am reporting a bug only. Please check the following link where 2 inputs having same onchange event behaving differently:

http://codepen.io/aseemgarg/pen/ygWZyV

**Comment by gargaseem** [comment]
@FezVrasta 
I am reporting a bug only. Please check the following link where 2 inputs having same onchange event behaving differently:

http://codepen.io/aseemgarg/pen/ygWZyV
