### ISSUE TITLE
V4: Bootstrap Modal issue

### ISSUE THREAD

**Issue by gargaseem** [mdbootstrap/mdb-ui-kit#1154]
Adding modal inside 'bmd-layout-content' doesn't open the modal correctly. So I have to place all my modals for different pages above the 'bmd-layout-content' (include all the modals in a single file which results in increasing file size for all pages).

Is it possible to include the modals when required inside the 'bmd-layout-content'?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
