### ISSUE TITLE
Floating label overlap with input value on refresh page

### ISSUE THREAD

**Issue by ZhuQinglei** [mdbootstrap/mdb-ui-kit#1156]
The problem persist here: I am using React in Meteor, and I have already set these in my config.js in client folder:
```
import "../../node_modules/bootstrap-material-design/dist/js/material.js"
import "../../node_modules/bootstrap-material-design/dist/js/ripples.js"
import "../../node_modules/arrive/src/arrive.js"
import "../../node_modules/react-bootstrap-table/dist/react-bootstrap-table.min.js"

$.material.options.autofill = true;
$.material.init();
```
I checked my $.material.options, and it shows that the autofill is enabled successfully:
![screen shot 2017-03-03 at 11 06 18 am](https://cloud.githubusercontent.com/assets/16860302/23536791/530fa7ba-0002-11e7-91e2-e667e6c43f2b.png)

But my floating label is still overlapping with my input value: 
![screen shot 2017-03-03 at 11 07 13 am](https://cloud.githubusercontent.com/assets/16860302/23536748/0aa544bc-0002-11e7-9337-0ca59e47323b.png)

I found that if I set the value before the component is firstly loaded, it is working fine; But when I refresh the page (I was using redux-persist retained the value) then the label is overlapping. 

I checked the css, and I believe it is the is-empty class causing the issue:
![screen shot 2017-03-03 at 11 07 04 am](https://cloud.githubusercontent.com/assets/16860302/23536818/96315494-0002-11e7-8bfa-b55144641702.png)

But I do not know how to solve the problem, isn't it suppose to remove is-empty class once the input value is no longer empty? Any suggestion would be really appreciated! Thanks!

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
