### ISSUE TITLE
Use just ripples on buttons and links. Is it possible?

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#1157]
Can I just use ripples (waves) effect on my Bootstrap 4 project? I don't need all the rest of your amazing project. How can I extract just ripples on buttons and links?

My main goal is to make it clear to the user that he has clicked, especially on mobile devices. This is because sometimes the server response is not immediate.

**Comment by FezVrasta** [comment]
You can include just ripples.js and initialize it

**Comment by ghost** [comment]
Can you please show me how? Please...

**Comment by FezVrasta** [comment]
Everything is explained in the README. If you need assistance ask on StackOverflow
