### ISSUE TITLE
Slow at loading 

### ISSUE THREAD

**Issue by AhmedRamz** [mdbootstrap/mdb-ui-kit#116]
When i use it with my website i become slow 

you cancheck out my website :
https://drive.google.com/file/d/0Bx3O564WoM6IY1lkS0dyVF83MkU/view?usp=sharing

**Comment by FezVrasta** [comment]
We'd need some more specific information...

**Comment by AhmedRamz** [comment]
The boot strap works fine and loads quickly 

and i'm working with another CSS which is flat UI also works fast

but when apply your CSS for the web it loads much slower with the internet connected but if the internet is disconnected it loads faster 

I'm new in web design , so it may be something simple or not :)

**Comment by FezVrasta** [comment]
Try open the dev console, then the network panel and then reload the page, you'll see which script load slow

**Comment by AhmedRamz** [comment]
![aaa](https://cloud.githubusercontent.com/assets/9165820/4613764/2c7728c2-52d9-11e4-843b-ee7358e80227.jpg)

Its in the Roboto Font

**Comment by FezVrasta** [comment]
ok so it's not a problem of our theme, it's something related to the Google fonts service

**Comment by AhmedRamz** [comment]
can you suggest so solution to to solve it :) 

i would be thankful :)
