### ISSUE TITLE
Trying to build the SCSS in V4. In _corebootstrap.scss, line 42 references animation. Where does that come from?

### ISSUE THREAD

**Issue by absolutebica** [mdbootstrap/mdb-ui-kit#1164]
Hi there,

I've been trying to build the SCSS that comes with V4.  I installed the node module, than copied the SCSS files/directories into my src/scss folder.  The _core-bootstrap.scss seems to rely on the bootstrap node module.  I used the NPM method off the getbootstrap.com V4 site, so I did  npm install bootstrap@4.0.0-alpha.6. I then copied the bootstrap folder into my src/scss so it shared the same directory level as 'extensions, mixins, variables, etc." 

So running a SASS build against your bootstrap-material-design.scss works until it hits line 42 in _core-bootstrap.scss looking for @import "bootstrap/scss/animation"; 

It appears @import "bootstrap/scss/tags" doesn't exist next.  And then on line 16 of _input-group.scss, it hits a wall cause of the &.bmd-form-gropu-sm with the node error message 

`message": "Base-level rules cannot contain the parent-selector-referencing character '&'.\n\nBacktrace:\n\tsrc/scss/_input-group.scss:16",`

What am I missing here?

**Comment by FezVrasta** [comment]
I updated the code to work with the latest alpha of Bootstrap.

I can't promise everything will work as expected, if you catch any bug please open an issue reporting them.

**Comment by kleisauke** [comment]
@FezVrasta Is this issue already fixed? Because I've the same error:
```sh
[17:33:23] gulp-notify: [Error running Gulp] Error: bower_components\bootstrap-material-design\scss\_input-group.scss
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.

       Backtrace:
        bower_components/bootstrap-material-design/scss/_input-group.scss:16
        on line 16 of bower_components/bootstrap-material-design/scss/_input-group.scss
>> &.bmd-form-group-sm {
   ^
```

**Comment by FezVrasta** [comment]
What sass compiler are you using?

**Comment by kleisauke** [comment]
I'm using `gulp-sass`. I've commented out `@import "input-group";` in ` _core.scss` as hotfix.

**Comment by eveyrat** [comment]
I had to replace animation by transitions and tags by badge

```
// @import "bootstrap/scss/animation";
@import "bootstrap/scss/transitions";
```
https://github.com/twbs/bootstrap/issues/21986

```
// @import "bootstrap/scss/tags";
@import "bootstrap/scss/badge";
```

I also had to get rid of Normalize :
https://github.com/twbs/bootstrap/pull/22004

**Comment by FezVrasta** [comment]
You may send a PR to updated these things
