### ISSUE TITLE
Promote V4-dev to master

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#1166]
Hi guys,

I know it's been a while since this project has been updated, but I would like to revive it because it's just awesome.

I updated the v4-dev branch to work with the latest alpha of Bootstrap, I didn't notice anything broken but I'm confident that you guys will find out any problems and report them here on the issues tracker.

I wanted to talk with you to propose to drop v3 and move v4-dev to master.

I know Bootstrap 4 isn't yet in beta, but I haven't time to work on both v3 and v4 and I think we could get a lot of new contributors if we switch to v4 now.

What do you think about this idea?

**Comment by Toilal** [comment]
For people relying on semver, you should also increment the major version on the first release of v4 branch. Then rename the old master branch into `0.x`, and update README from both accordingly for people to understand which branch to use.

**Comment by FezVrasta** [comment]
v4-dev has `4.x.x` version while v3 has `0.x.x` version, so I think we are already fine with this.

I'll update the README of v3 to point to `^0`

**Comment by FezVrasta** [comment]
done
