### ISSUE TITLE
bower version (v3) don't work

### ISSUE THREAD

**Issue by D3adKnight** [mdbootstrap/mdb-ui-kit#1168]
#### Summary
I want to use your library in my projects, but I ran into a problem: Version installed from bower don't work correctly.
Steps to reproduce:
- install library from bower: ```bower install --save bootstrap-material-design``` (in my case in '/lib/' folder)
- include installed lib's (jquery, bootstrap, tether and bootstrap-material-design) in my html:
```html
<head>
<!-- Material Design fonts -->
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/icon?family=Material+Icons">

<!-- Bootstrap -->
<link href="lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet">

<!-- Bootstrap Material Design -->
<link rel="stylesheet" href="lib/tether/dist/css/tether.min.css">
<link rel="stylesheet" href="lib/bootstrap-material-design/dist/bootstrap-material-design.css">
</head>
<body>

<!-- simple test checkbox -->
<div>
    <div class="form-group">
        <div class="checkbox">
            <label>
                <input type="checkbox"><span class="checkbox-material"><span class="check"></span></span> Notifications
            </label>
        </div>
        <p class="help-block">Notify me about updates to apps or games that I've downloaded</p>
    </div>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="lib/jquery/dist/jquery.min.js"></script>
<script src="lib/tether/dist/js/tether.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="lib/bootstrap/dist/js/bootstrap.js"></script>
<!-- material design -->
<script src="lib/bootstrap-material-design/dist/bootstrap-material-design.iife.js"></script>
</body>
```

And in this case I don't have ```$.material``` object and most of styles works incorrect:
![wrong](https://cloud.githubusercontent.com/assets/2833696/24408973/aff1c8c6-13d7-11e7-9ed9-44094d21b3c1.PNG)

#### Expected result
When I include downloaded/cdn version from /dist folder, all works fine:
![right](https://cloud.githubusercontent.com/assets/2833696/24409159/0e94fd80-13d8-11e7-8304-1317aad0578f.PNG)

#### Additional Information
Maybe I'm doing something wrong, but in that case it might be worth adding in a section on using your library through npm/bower?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
