### ISSUE TITLE
Examples: the checkboxes and radios only toggle when clicking the text; not when clicking the checkbox/circle.

### ISSUE THREAD

**Issue by klonos** [mdbootstrap/mdb-ui-kit#1171]
#### Test Case (not codepen; happens on the examples page)
https://rosskevin.github.io/bootstrap-material-design/components/buttons/#checkbox-and-radio-buttons

#### Summary
Please see screengrab:

![bootstrap-material-design-checkboxes_and_radio_buttons_not_working](https://cloud.githubusercontent.com/assets/2423362/25066885/77caa24e-2276-11e7-9e61-7e002e6c4aff.gif)

Happens on latest firefox x64 nightly (55.0a1 at the time of writing) and latest Chrome x64 (57.0.2987.133) on Windows 8.1 x64

#### Expected result
The checkboxes/radios should be toggled by pressing the checkbox/circle as well.

#### Additional Information
none

**Comment by FezVrasta** [comment]
Thank you for the report, feel free to send a PR to fix it if someone wants to.

**Comment by FezVrasta** [comment]
Seems fixed now
