### ISSUE TITLE
Flat button conserve it's "Focus" state color until another element is clicked in the DOM

### ISSUE THREAD

**Issue by PierreRoudaut** [mdbootstrap/mdb-ui-kit#1172]
#### Test Case 
http://codepen.io/anon/pen/OmyoOg
1- Hover on the "Cancel" button, note the background color of the button becomes light grey
2- Press the "Cancel button", note the dark grey color
3- The button's background color becomes light grey again

#### Summary
Flat button conserve it's "Focus" state color until another element is clicked in the DOM

#### Expected result
The flat button's background color should become transparent as its initial state after releasing the click without having to click on another element

The "behavior" demo of the flat button highlights what is expected (scroll down a bit)
https://material.io/guidelines/components/buttons.html#buttons-flat-buttons

Thank you for your help

**Comment by FezVrasta** [comment]
That's the default behavior of HTML, you may change it with something like [`what-input`](https://github.com/ten1seven/what-input)

**Comment by PierreRoudaut** [comment]
Forgive me to insist, but every other third party library that implements the material design guidelines for flat button do it this way :)

- [https://material.angular.io/components/component/button](url)
- [http://materializecss.com/buttons.html](url)
- [https://getmdl.io/components/index.html#buttons-section](url)
- [http://www.material-ui.com/#/components/flat-button](url)

**Comment by FezVrasta** [comment]
I know, but that's a achieved with some extra JavaScript and it's not the default browser behavior.

I mean, not that I don't like the result, but it's not a bug the way it currently is.

If you want to add support for `what-input` feel free to send a PR! 🙂

It should look like:


```css
[data-whatinput=mouse] .btn:focus {
  background-color: transparent
}
```
