### ISSUE TITLE
default bootstrap style no being overridden

### ISSUE THREAD

**Issue by Nicks182** [mdbootstrap/mdb-ui-kit#1173]
Simple issue using bootstrap 3, the below style inside the bootstrap.css file is not being overridden by the material theme.

```
.btn-primary:active:hover,
.btn-primary.active:hover,
.open > .dropdown-toggle.btn-primary:hover,
.btn-primary:active:focus,
.btn-primary.active:focus,
.open > .dropdown-toggle.btn-primary:focus,
.btn-primary:active.focus,
.btn-primary.active.focus,
.open > .dropdown-toggle.btn-primary.focus {
  color: #fff;
  background-color: #204d74;
  border-color: #122b40;
}
```

I have button like below and when I click it to open the dropdown menu the background color will change to #204d74 when you move your mouse over the menu items.

```
<button type='button' class='btn btn-primary dropdown-toggle' data-toggle='dropdown' role='button'>
  Some Text
</button>"
```

We changed from blue to a custom green for a new client and spotted the issue, but so far it's only one specific case where we have a button defined like above.

I have a custom .less file and I just added the following to fix the issue in my case:
```

.btn-primary:active:hover,
.btn-primary.active:hover,
.open > .dropdown-toggle.btn-primary:hover,
.btn-primary:active:focus,
.btn-primary.active:focus,
.open > .dropdown-toggle.btn-primary:focus,
.btn-primary:active.focus,
.btn-primary.active.focus,
.open > .dropdown-toggle.btn-primary.focus {
  color: #fff;
  background-color: contrast(@primary, darken(@primary, 4%), lighten(@primary, 4%), 40%);
  background-color: contrast(@primary, darken(@primary, 8%), lighten(@primary, 8%), 40%);
}
```

**Comment by pk-r** [comment]
I'm having the same problem with overriding thing, form components are having the same attributes of default bootstrap.

![a](https://cloud.githubusercontent.com/assets/14369451/25553300/12db4664-2cc5-11e7-9b7f-30f5d53d5471.png)

Looking forward for an answer.
sorry for low quality image.
