### ISSUE TITLE
Checkbox resize (changing mdb-checkbox-size)

### ISSUE THREAD

**Issue by bmla** [mdbootstrap/mdb-ui-kit#1174]
#### Test Case 
http://codepen.io/bmla/pen/VbWZQx

#### Summary
Using sass, set $mdb-checkbox-size to e.g. 14px or 16px. The result I'm seeing is the same as the test case, i.e. the check (✔) is not resized, and consequently cropped.

#### Expected result
The check mark is resized to the checkbox's size

**Comment by sadiq-evinance** [comment]
Hi,
I was wondering how you resolved this issue as I am facing the same problem. I am currently using version 0.5.10 of mdb.

**Comment by bmla** [comment]
Sorry, I didn't solve this issue.

**Comment by FezVrasta** [comment]
v3 isn't maintained anymore, please feel free to open an issue if you reproduce the problem in v4.
