### ISSUE TITLE
V4 - onChange event is fired multiple times

### ISSUE THREAD

**Issue by gargaseem** [mdbootstrap/mdb-ui-kit#1176]
I have added a v4-branch code in my project and when I added a onChange event, it is fired infinite times even when I press any key. Ideally it should fire on blur/Tab-out (Refer - https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onchange2).

Please refer the **Codepen** example:
http://codepen.io/aseemgarg/pen/ygWZyV

For first input box, it is fired infinite times and for second input it is working fine. I have logged the **output in console**.

I debug this further and realize that form tag is causing this issue i.e if input is inside the form tag, then it is fired infinite times but if placed outside, onChange event works fine. How can we solve this issue?

Tested this on Chrome v57.0

**Comment by FezVrasta** [comment]
Dupe https://github.com/FezVrasta/bootstrap-material-design/issues/1036
