### ISSUE TITLE
Modal issue when used with bmd side nav

### ISSUE THREAD

**Issue by gargaseem** [mdbootstrap/mdb-ui-kit#1177]
I have added a v4-branch code in my project and when I added a modal inside the body `(<div class="bmd-layout-content" id="bodyContainerParent" tabindex="-1"> <div id="bodyContainer">)`, the modal backdrop is cover the modal.

Please refer the **Codepen** example:
http://codepen.io/aseemgarg/pen/EmvMob

But when I add this modal just above the footer `(<div id="wrapper" class="bmd-layout-container bmd-drawer-f-l bmd-drawer-overlay-md-down bmd-drawer-in-lg-up">)`, this being it's parent div, it works fine.

Please refer the **Codepen** example:
http://codepen.io/aseemgarg/pen/YVrKxV

Tested this on Chrome v57.0

**Comment by FezVrasta** [comment]
May you simplify the pens? They have quite a bit of stuff going on there.

**Comment by FezVrasta** [comment]
Also, try to replace the Material Design CSS with the basic Bootstrap v4 CSS to see if the error is still there.

https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css

**Comment by gargaseem** [comment]
I have simplified the pens. Please check once.

I tried replacing with CSS this, but it didn't work. Adding this is not showing the modal. Please check once at your side.

Thanks!

**Comment by FezVrasta** [comment]
This happens because `bmd-layout-content` has `z-index: 1` set.

I wonder if it is actually needed?

By the way, it would make sense to position the modal markup as direct child of `body` to avoid this kind of problems at all.

**Comment by gargaseem** [comment]
It would make sense if we have the modals on all pages but I have certain modals that are page specific, so wanted to load these modals on specific pages (based on certain conditions).

If I change the z-index of `bmd-layout-content` to 1041 OR remove the z-index, it started working fine. Is there any other way to fix it so that it would not impact the library?

**Comment by FezVrasta** [comment]
We should make sure that getting rid of the `z-index` will make still everything work properly, if so, we can get rid of it.

**Comment by klonk** [comment]
With z-index removed ( and with 1041) i have issue with modal on iOs devices, any hint how to solve it?

**Comment by bretonio** [comment]
Moving the modall outside `.bmd-layout-container.bmd-drawer` worked for me as well and I thank you all. Will test other suggestions  as well.
