### ISSUE TITLE
.focus-shadow mixin is not compatible with default shadow

### ISSUE THREAD

**Issue by milonas115** [mdbootstrap/mdb-ui-kit#1182]
#### Test Case 
http://codepen.io/anon/pen/KmBXjz

Chrome 58.0.3029.110 (64-bit) Windows 10

#### Summary
The focus box-shadow currently has 2 properties. The normal box-shadows have 3 properties. This causes issues with smoothly transitioning the shadows. Please see codepen.

#### Expected result
See codepen. But the shadow transition is suppose to be smooth.

**Comment by FezVrasta** [comment]
v3 isn't being developed anymore. If you want to send a PR to fix it I'll be happy to merge it.
