### ISSUE TITLE
Ajax .load removes radiobuttons

### ISSUE THREAD

**Issue by lgund** [mdbootstrap/mdb-ui-kit#1183]
Hey,
I got an ajax problem. If I load my page normally all works fine. But if my page over an ajax .load the radio button will not be shown. I´ve tried to add after the load
`$.material.init();`
but it´s still not there. Did have anyone an idea?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
