### ISSUE TITLE
Adding button to form of navbar expands navbar height

### ISSUE THREAD

**Issue by denys-olleik** [mdbootstrap/mdb-ui-kit#1185]
Navbar's height gets expanded when adding a button to the form contained in the navbar.

You can just add a button and see like so...

```
<form class="navbar-form navbar-left">
                  <div class="form-group is-empty">
                    <input type="text" class="form-control col-md-8" placeholder="Search">
                  </div>
  <button type="submit" class="btn btn-default">Submit</button>
                </form>
```

Sorry I don't like rules.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
