### ISSUE TITLE
Checked checkboxes and radios are not checked in print preview and printed output

### ISSUE THREAD

**Issue by EugenVau** [mdbootstrap/mdb-ui-kit#1189]
#### Test Case 
https://codepen.io/anon/pen/EXwRJQ

#### Summary
Check marks in checkboxes and radios are not visible in print previews and printed output.

**Browser:** tested in Chrome 59, Firefox 54, others may be affected, too.

**Steps to reproduce:**
1. go to URL
2. check some checkboxes and radios
3. Show print preview by pressing "ctrl+p" or right-click -> Print

**Result:**
Previosly checked checkboxes and radios don't have check marks, only coloured borders.

#### Expected result
Previosly checked checkboxes and radios have check marks.

**Comment by FezVrasta** [comment]
This is probably because the checkboxes use a box shadow to draw the animated symbol. We may want to replace the box shadow with an SVG image once the animation is complete.

V3 isn't maintained anymore, but the problem is reproducible also on V4 branch so we may want to fix it there.
