### ISSUE TITLE
map-marker icon?

### ISSUE THREAD

**Issue by dandv** [mdbootstrap/mdb-ui-kit#119]
I can't seem to find a map-marker icon, and I've searched for "gps" (it looks like a target), "location" (it looks like a compass needle).

Here's the icon from http://materialdesignicons.com/

![image](https://cloud.githubusercontent.com/assets/33569/4612360/9269c4f4-52c6-11e4-9449-38ff0702ea6c.png)

Should `glyphicon glyphicon-map-marker` be used instead?

**Comment by FezVrasta** [comment]
The current icons are from polymer project, I'd like to find some better implementation, the one you have linked looks good. Will take a look.

**Comment by FezVrasta** [comment]
use `<i class="mdi-maps-place"></i>`
