### ISSUE TITLE
change event fires multiple times with autofill=true

### ISSUE THREAD

**Issue by kkojot** [mdbootstrap/mdb-ui-kit#1193]
#### Test Case 
https://codepen.io/anon/pen/xrNLpY

#### Summary
To reproduce the issue please open the codepen test case and in the very first 10 seconds click the "CHANGE AVATAR" button. Choose the file in the dialog and click open. Now you can see in the browser console that the "avatar file changed" message appeared many times.
10 seconds later after page load everything works fine. If we turn the autofill option to false, it works fine either.

#### Expected result
I expect that the change event should fires only once, with or without the autofill option.

#### Additional Information
I use the autofill=true option when I need to fill inputs value with floating labeles via ajax call. The ugly workaround is to remove "is-empty" class manually.

`$('#input_id').val('new value');
$('#input_id').parent().removeClass('is-empty');`

If anyone has better solution please describe it.

Regards,
Wojtek.

**Comment by FezVrasta** [comment]
It's already been discussed several times. Search the existing issues

**Comment by kkojot** [comment]
Ok thank you, I've searched closed issues and the best solution I found so far is to keep the autofill option disabled and manually trigger change event on inputs.

```
$.material.options.autofill = false;
$.material.init();
$('#input_id').val('new value').trigger('change');
```

**Comment by mxyzzhong** [comment]
now ,api changed, please use `$('body').bootstrapMaterialDesign({ autofill: false });`
