### ISSUE TITLE
Bower version don't works...

### ISSUE THREAD

**Issue by mydiscogr** [mdbootstrap/mdb-ui-kit#1194]
the problem is that bower version (which don't works at all)  is not the same of the one found here: http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html and this one works... thanks

**Comment by trickly** [comment]
Yup the download from the link above has a completely different structure/files than the bower version. Please update the bower link please.

**Comment by howar31** [comment]
And also npm version is outdated.  The latest version on npm is 0.5.10, but the latest should be 4.0.2

**Comment by FezVrasta** [comment]
the v4 branch is not yet released

**Comment by howar31** [comment]
uh.. oops so 0.5.10 should be the master branch? 
sorry for bothering :/

**Comment by FezVrasta** [comment]
yup

**Comment by FezVrasta** [comment]
@mydiscogr and @trickly, have you installed the bower version `0.x` or the `4.x`? You should install `0.x` if you use Bootstrap 3.

**Comment by tobylonge** [comment]
I am using bootstrap 3 and I encountered this issue too. I eventually solved it by using this ` bower install bootstrap-material-design#0.x`. @FezVrasta I will suggest this is added to the readme file to avoid others from making same mistake.

**Comment by FezVrasta** [comment]
Feel free to send a PR to update the README. thanks!

**Comment by FezVrasta** [comment]
published 4.0.0-beta.3
