### ISSUE TITLE
Bootstrap gets disabled once bootstrap-material-design load 

### ISSUE THREAD

**Issue by Zorono** [mdbootstrap/mdb-ui-kit#1197]
Hello sir, so i have just used this nice library today and you was working great on it and my proplem is after including your library (js + css + map..) on my template bootstrap's buttons and others gets hidden or disabled or what ever i don't know why i tried changing the version of my Bootstrap to old version but it didn't work too (iam using latest Bootstrap version) 

Details:-
Bootstrap: v3.3.7
JQuery: v2.1.4
Bootstrap Material Design: Latest one (unknown on ids...)
Website Link URL: https://www.br-gaming.ga/?p=1.0

**Comment by Zorono** [comment]
Why did you close the issue ?? i need help

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
