### ISSUE TITLE
Bootstrap gets disabled once bootstrap-material-design load

### ISSUE THREAD

**Issue by Zorono** [mdbootstrap/mdb-ui-kit#1198]
Test Case: https://codepen.io/anon/pen/brEEqV or https://www.br-gaming.ga/?p=1.0

Summary: so i have just used this nice library today and you was working great on it and my proplem is after including your library (js + css + map..) on my template bootstrap's buttons and others gets hidden or disabled or what ever i don't know why i tried changing the version of my Bootstrap to old version but it didn't work too (iam using latest Bootstrap version).

Browser: tested in Chrome 60.0.3112.78, Internet Explorer 11.

Steps to reproduce: Visit those Test Case Links and check the buttons and the List groups (Bootstrap's Elements) if they are bugged or what ever.. 

Expected result: Bootstrap's elements (Buttons/List groups) doesn't work 100% on testing on my website or any kind of test case and its tested on 2 browsers which are listed below.

**Comment by FezVrasta** [comment]
Bootstrap must be loaded before Bootstrap Material Design

**Comment by Zorono** [comment]
its already loaded before Bootstrap Material Design 
```
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type='text/css'>
<link href="css/bootstrap-material-design.min.css" rel="stylesheet" type='text/css'>
<link href="css/ripples.min.css" rel="stylesheet" type='text/css'>
& 
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="js/ripples.min.js"></script>
<script type="text/javascript" src="js/material.min.js"></script>```

**Comment by FezVrasta** [comment]
nope, this way it works:
https://codepen.io/FezVrasta/pen/BdjjJo

**Comment by Zorono** [comment]
please check https://www.br-gaming.ga/?p=1.0 - it doesn't work even iam stuck

**Comment by FezVrasta** [comment]
Sorry I don't have time to debug your own code, the codepen works, so it's not a problem with the library but something on the way you have coded your page. Ask on StackOverflow for this kind of issues.
