### ISSUE TITLE
jquery select2 is not working with material bootstrap, 

### ISSUE THREAD

**Issue by kvvaradha** [mdbootstrap/mdb-ui-kit#1199]
I was trying to  create select2 inside the bootstrap material design. But its not working.
it has some ui collapsed thing.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
