### ISSUE TITLE
Have a "plain" navbar

### ISSUE THREAD

**Issue by hans-d** [mdbootstrap/mdb-ui-kit#12]
White background, with black texts.
Esp when used as a topbar, a less screaming version is appreciated :-)

**Comment by hans-d** [comment]
And: lightgrey, black

**Comment by FezVrasta** [comment]
Have you tried the navbar-material-lightgrey class?

**Comment by hans-d** [comment]
Just noticed the -material-<color> trick, nice... Leaves black and white..
