### ISSUE TITLE
Modification of div tree causing issues in fetching data from the page.

### ISSUE THREAD

**Issue by mathieutozer** [mdbootstrap/mdb-ui-kit#120]
I am using the yogiben:admin package and bootstrap-material-design, due to the injection of an extra div, caused the autoform code not to find the attributes in the following line

return Meteor.call('adminAddUserToRole', $(e.target).attr('user'), $(e.target).attr('role'));

I'm kind of new to this so not sure what the right fix is here. Calling 'parent' returned the user and role.

**Comment by rougin** [comment]
I think this problem is similar to https://github.com/FezVrasta/bootstrap-material-design/issues/80

**Comment by FezVrasta** [comment]
Unfortunately there are not other solutions to style the inputs in the current way. You should edit your code to make it work with this theme, or disable the style on the input fields.
