### ISSUE TITLE
readMe documentation links are NOT working.

### ISSUE THREAD

**Issue by mfaheemakhtar** [mdbootstrap/mdb-ui-kit#1205]
#### Test Case
The issue is with readMe.md, not with the code.

#### Summary
The links in "documentation" heading in readMe.md are not working and throwing a 404 error.

#### Expected result
links should point to the active and current documentation links.

#### Additional Information
nope

**Comment by kcrossfitter** [comment]
2

**Comment by FezVrasta** [comment]
I'm aware of it, I still need to find some time to publish the beta and update the demo page.
