### ISSUE TITLE
Dropdown does not work with jQuery 3+

### ISSUE THREAD

**Issue by devilstars** [mdbootstrap/mdb-ui-kit#1207]
#### Test Case
https://codepen.io/Simushkin/pen/wqEbBo

#### Summary
Dropdowns does not work with jQuery 3+. Alway get error `Syntax error, unrecognized expression: #`

#### Expected result
Dropdowns have to work with any version of jQuery.

**Comment by FezVrasta** [comment]
dupe of some other issue I can't remember, and v3 is not supported anymore anyway
