### ISSUE TITLE
the package isn't latest from npm(sorry for my Chinese english)

### ISSUE THREAD

**Issue by liuweiGL** [mdbootstrap/mdb-ui-kit#1208]
> [@jasoeight/bootstrap-material-design](https://www.npmjs.com/package/@jasoeight/bootstrap-material-design) can't use by webpack , and I find resources are different with this branch;
# problems

+ ` bootstrap-material-design-4.0.2\scss\_core-bootstrap.scss   @import "bootstrap/scss/custom"; ` is not exist ; and ` @import " bootstrap/**/**  " ` should be ` @import " ~bootstrap/**/** " ` ;

+ `bootstrap-material-design-4.0.2\scss\mixins\_buttons.scss :@include bmd-flat-button-variant($btn-primary-bg); `  the  `$btn-primary-bg` is commented in ` bootstrap-material-design-4.0.2\scss\variables\bootstrap\_buttons.scc`

**Comment by FezVrasta** [comment]
published 4.0.0-beta.3
