### ISSUE TITLE
Reinit Inputs

### ISSUE THREAD

**Issue by jookeing** [mdbootstrap/mdb-ui-kit#121]
I am using jquery datatable, which rendering dynamic content with ajax. In my table, i have checkboxs. Checkbox are not displayed as material design style as i think dynamic content need to reinit.  Can i have a javascript function reinit inputs? Correct me if i am wrong. Thanks you.

**Comment by FezVrasta** [comment]
just include arrive.js before material.js, it will automatically detect new elements and will style them

**Comment by jookeing** [comment]
It is working fine now.Thank you.

**Comment by FezVrasta** [comment]
you're welcome :)
