### ISSUE TITLE
background colors buttons in ie11

### ISSUE THREAD

**Issue by allartk** [mdbootstrap/mdb-ui-kit#1211]
#### Test Case
https://codepen.io/allartk/pen/vJbJwj

#### Summary
In ie11 windows 7 buttons have no transparent background. They keep the background from bootstrap.

#### Expected result
A transparent background on the buttons.

#### Additional Information
![schermafdruk van 2017-09-01 16-28-34](https://user-images.githubusercontent.com/3617965/29974267-a4f13e9e-8f32-11e7-84e1-ab6ca0d80c49.png)

Without .btn { background-color: inherit } it works as expected in ie11 / win7.

**Comment by FezVrasta** [comment]
Thank you, I'd love to see a pull request to fix this if you have some spare time 👍

**Comment by FezVrasta** [comment]
Fixed with #1215
