### ISSUE TITLE
missing _badge.scss and others

### ISSUE THREAD

**Issue by tkuther** [mdbootstrap/mdb-ui-kit#1216]
I'm looking at https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/components/badge/

Though, the _badge.scss is missing in https://github.com/FezVrasta/bootstrap-material-design/tree/master/scss

Also missing: _images.scss, _jumbotron.scss, _media.scss, _carousel.scss
_cards.scss is _card.scss in mainline bootstrap 4-beta

Is this supposed to be that way and one should load the mainline bootstrap css before the material one?

**Comment by FezVrasta** [comment]
Material Design for Bootstrap 4 is based upon the Bootstrap 4 source, it simply imports it and extends/overrides the needed parts.

If a file doesn't need any modification, we don't define any override in our own source code.

**Comment by tkuther** [comment]
OK, thanks for your explanation.

But even on your own page https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/components/badge/ - the CSS for the badges is missing.

**Comment by FezVrasta** [comment]
Good catch, then we definitely have to support them.
