### ISSUE TITLE
File to import not found or unreadable: bootstrap/scss/functions

### ISSUE THREAD

**Issue by JamesVanWaza** [mdbootstrap/mdb-ui-kit#1218]
**Bootstrap-Material-Design:** `4.0.0-beta.3`
**Node:** `8.4.0`
**NPM:** `5.4.0`
**Grunt:** `1.0.1`
**MacOS Sierra** `10.12.6`

<img width="1420" alt="screen shot 2017-09-05 at 5 31 37 pm" src="https://user-images.githubusercontent.com/4000076/30084379-23501c4e-9260-11e7-9243-221f10ee6545.png">

The `bootstrap/scss/functions` file cannot be found.

**Comment by FezVrasta** [comment]
You must define node_modules in the include paths. Read the readme instructions

**Comment by JamesVanWaza** [comment]
@FezVrasta, I had defined the `loadPath`  see screenshot below 

<img width="1354" alt="screen shot 2017-09-05 at 6 16 21 pm" src="https://user-images.githubusercontent.com/4000076/30085841-6c3d822e-9266-11e7-957a-7e7ac00fcb5f.png">

**Comment by jshdolor** [comment]
having this problem also

on my webpack.mix.js
`mix
    .sass('resources/sass/app.scss', 'css', {
        loadPath: ['node_modules/bootstrap-sass/assets/stylesheets']
    })
;`

on my app.scss
`
@import 'node_modules/bootstrap-material-design/scss/bootstrap-material-design',
    'node_modules/bootstrap-material-design/scss/ripples';
`

**Comment by FezVrasta** [comment]
You just have to define `node_modules`, not the whole Bootstrap path
