### ISSUE TITLE
V4 Navbar out of page range

### ISSUE THREAD

**Issue by hawkiq** [mdbootstrap/mdb-ui-kit#1219]
Am facing problem with navbar its show horizontal scrollbar at bottom , but in Bootstrap official css its work fine,
am using CDN
`<link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.0.0-beta.3/dist/css/bootstrap-material-design.min.css" integrity="sha384-k5bjxeyx3S5yJJNRD1eKUMdgxuvfisWKku5dwHQq9Q/Lz6H8CyL89KF52ICpX4cL" crossorigin="anonymous">`

with code
```
<nav` class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
```

![bug](https://user-images.githubusercontent.com/7524502/30243162-84993356-95ac-11e7-9dea-a15122af557b.png)

**Comment by FezVrasta** [comment]
Maybe related to #1210?

**Comment by hawkiq** [comment]
@FezVrasta yup its the same problem I didn't noticed it.
I hope you will fix it soon.

**Comment by Prophet32j** [comment]
I'm curious, has this fix made its way to the CDN? I'm still experiencing this same issue. Code is being pulled directly out of the docs on setting up and creating the navbar.
