### ISSUE TITLE
Checkboxes/radios in forms missing material style

### ISSUE THREAD

**Issue by tkuther** [mdbootstrap/mdb-ui-kit#1222]
The classes for form checkboxes and radios have changed a lot in Bootstrap 4.
Both radios and checkboxes are now covered by .form-check (previously .checkbox and .radio)

Therefore, checkbox styling and ripples don't work anymore. See https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/components/forms/ - they have default bootstrap styling.

**Comment by FezVrasta** [comment]
This is expected, even the original Bootstrap v4 doesn't style the checkbox by default. Refer to this section for the styled components.

https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/forms/

**Comment by tkuther** [comment]
Oops, I really overlooked the forms part in the material design docs menu. Sorry for the noise.
