### ISSUE TITLE
how to make it work with Angular 4 

### ISSUE THREAD

**Issue by nitinht1988** [mdbootstrap/mdb-ui-kit#1225]
Hi,
which files are needed and where to put that files in order to make it work properly in my Angular 4 project. as it seems like something is not correct in my code.

Thanks in advance.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
