### ISSUE TITLE
Can't use bootstrap dependency.

### ISSUE THREAD

**Issue by grapgrap** [mdbootstrap/mdb-ui-kit#1228]
First, I'm not good at english. 

I want to use your scss. 

I installed it and bootstrap.

 I imported it. But It can't reached bootstrap scss. 

So, I fixed bootstrap node module path `bootstrap/scss/~~~` to `../../bootstrap/scss/~~~` in `_core-bootstrap.scss` and `_variables.scss`.

Can i ask pull request for your project? or can you fix this files?

Thanks your attention. Have a good day.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
