### ISSUE TITLE
Dropdowns and jumping divs (v4)

### ISSUE THREAD

**Issue by devilstars** [mdbootstrap/mdb-ui-kit#1229]
#### Test Case
No need to create codepen, it's reproduced in docs.  **Watch the video in "additional info".**

#### Summary
Dropdown click on BSv4, jumps from on top/over the dropdown button to below the dropdown button.

#### Expected result
Everything should be smooth

#### Additional Information
[Video_2017-09-21_134503.zip](https://github.com/FezVrasta/bootstrap-material-design/files/1320870/Video_2017-09-21_134503.zip)

**Comment by ArcanoxDragon** [comment]
Was just about to report this and saw it was already confirmed. When I go to the docs page, the first time I click the dropdown button under the "Menu Alignment" sample, the dropdown opens and then jumps, making it incorrectly aligned.

The second time, it opens offset and smoothly slides into the correct location, which I assume is the correct behavior.

The third time, and any subsequent times, it opens in the correct location, but without any animation.

GIF here: https://i.imgur.com/6dZIvR4.gifv

On my own site, there is no "second time" behavior. The first time it is opened, it opens in the wrong place and jumps to the right place a second later. The second time, and any subsequent times, it opens to the correct location without any animation.

(tested in Chrome 60, on Win10 x64)

**Comment by FezVrasta** [comment]
Fixed in 73887a4
