### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by devalexandre** [mdbootstrap/mdb-ui-kit#123]
I make a dashboard, but don't know how send for you
are in my git

https://github.com/ale-php/bootstrap-material-design/tree/master/css-compiled

**Comment by FezVrasta** [comment]
Hello, thank you for your contribution, I've not understood what have you added, may you try to explain it?  
Is it a sidebar? May you provide some screenshot to show me how it looks and how it works?

Thanks!

**Comment by devalexandre** [comment]
sidebar is a nav-bar fixed in left screem

code for use

  <div class="col-sm-3 col-md-2 sidebar">
             <ul class="nav nav-sidebar">
<li><a href='#'><span class='glyphicon glyphicon-phone'></span> 
Grupos</a><li></li>
<li><a href='#'><span class='glyphicon glyphicon-user'></span> 
Contatos</a><li></li>
<li><a href='#'><span class='glyphicon glyphicon-pencil'></span> 
Campanhas</a><li></li>

```
       </ul>
     </div>
```
