### ISSUE TITLE
Snackbars: not working

### ISSUE THREAD

**Issue by dalisoft** [mdbootstrap/mdb-ui-kit#1231]
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/snackbars/

I'm clicked a lot, but not worked

**Comment by kasturekapil** [comment]
```
Sorry for delayed answer.

You have to just include <script src="https://cdn.rawgit.com/FezVrasta/snackbarjs/1.1.0/dist/snackbar.min.js"></script>
after the bootstrap js to work the snackbar and toast

Below is the code.
<body>
    <button type="button" class="btn btn-secondary" data-toggle="snackbar" data-content="Free fried chicken here! <a href='https://example.org' class='btn btn-info'>Check it out</a>" data-html-allowed="true" data-timeout="0">
  Snackbar
</button>
<script>...</script>
<script>...</script>
<script src="https://cdn.rawgit.com/FezVrasta/snackbarjs/1.1.0/dist/snackbar.min.js"></script>
```
Might be their **Heads up! You don’t need to include SnackbarJS CSS, it’s already bundled in Material Design for Bootstrap.** not working here.

Any one having other solution. Please let me know.

**Comment by dkent600** [comment]
Dang I just spent several hours porting my code to BMD specifically for this feature (snackbars).

**Comment by marknl** [comment]
Snackbars work just fine. Only need to include the js file, css is already in the BMDv4 distribution.

https://codepen.io/marknl/pen/yPpreE

**Comment by dkent600** [comment]
Agreed, they work fine for me.

**Comment by Prophet32j** [comment]
the issue here is that the examples on the docs don't work. Broken in both Chrome and Safari
