### ISSUE TITLE
Radio checkbox: making circles looking better

### ISSUE THREAD

**Issue by dalisoft** [mdbootstrap/mdb-ui-kit#1232]
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/selections/

Link: 
https://fezvrasta.github.io/bootstrap-material-design/dist/css/bootstrap-material-design.css:8301
```css
.radio label input[type=radio]:checked ~ .bmd-radio::before, label.radio-inline input[type=radio]:checked ~ .bmd-radio::before {
    transform: scale3d(0.5, 0.5, 1); // from 0.55 > 0.5
```

**Comment by FezVrasta** [comment]
May you send a PR and attach comparative screenshots?
