### ISSUE TITLE
Navbar Dropdown Item Bug on Mobile View

### ISSUE THREAD

**Issue by Itbankrock** [mdbootstrap/mdb-ui-kit#1235]
There is a bug with the navbar that contains dropdown items. The height of the dropdown menu coming from those dropdown items consumes the navbar space as well even if it's not expanded or collapsed. 

Check the video inside the zip file attached for better visualization.
[Bootstrap Material Design Navbar Dropdown bug.zip](https://github.com/FezVrasta/bootstrap-material-design/files/1337956/Bootstrap.Material.Design.Navbar.Dropdown.bug.zip)

**Comment by FezVrasta** [comment]
Hi may you please use CodePen for the demo?

Thanks.

**Comment by versionzhang** [comment]
Hi, I found Navbar Mobile View has a bug, not only with Dropdown Item. here is CodePen demo.

I just copy` https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/examples/navbar-top-fixed/ ` code and use the latest version of bootstrap-material-design.

CodePen demo: `https://codepen.io/versionzhang/pen/mBKExO`

 @FezVrasta

**Comment by marknl** [comment]
Here's a codepen that presents the issue: https://codepen.io/marknl/pen/ZXwamb
When switching to native bootstrap 4, it works.

**Comment by FezVrasta** [comment]
The example seems to work with the latest beta (4)

https://codepen.io/FezVrasta/pen/QqYrzG
