### ISSUE TITLE
navbar and .hidden-print Still getting printed

### ISSUE THREAD

**Issue by chez14** [mdbootstrap/mdb-ui-kit#1240]
#### Test Case
https://codepen.io/chez14/pen/rGJXqG

#### Summary
Navbar getting printed, even it's contains `hidden-print` class.

#### Expected result
Navbar not getting printed, and everything with `hidden-print` class is not printed.

#### Additional Information
![image](https://user-images.githubusercontent.com/5555026/31312327-258fbb38-abea-11e7-9a37-98930d85b68c.png)

**Comment by FezVrasta** [comment]
Bootstrap v4 renamed those classes, they are now called `.d-*`

https://getbootstrap.com/docs/4.0/migration/#responsive-utilities
