### ISSUE TITLE
Bootstrap collapse not working as expected

### ISSUE THREAD

**Issue by aodendaal** [mdbootstrap/mdb-ui-kit#1242]
#### Test Case

https://codepen.io/aodendaal/pen/NaYopR
#### Summary

I've created a form with a checkbox to show a collapsed input if it is checked. The collapsed input is always shown regardless of checking & unchecking the checkbox.

I've created an example with the same results in the test case.

I'm working in Chrome.

#### Expected result

The div with the ```collapse``` class is hidden until the checkbox is checked.

#### Additional Information
In my project I can see the classes changing when I check the checkbox from ```collapse``` to ```collapsing``` to ```collapse show``` but on the test case I cannot get it to do that. It's like the animation is there but the styling is not being applied.

As a work around I've created my own styling for ```collapse``` and ```collapse show``` to make it work as expected.

**Comment by FezVrasta** [comment]
I think this should be already fixed on master, I just need to fix some more stuff before I can release a new beta.

https://github.com/FezVrasta/bootstrap-material-design/commit/0c90b44d40452d9f33ba6a64129ecb8f65ea4784
