### ISSUE TITLE
Cannot install version v4.0.2 with Bower in VS2017

### ISSUE THREAD

**Issue by rprimora** [mdbootstrap/mdb-ui-kit#1243]
#### Test Case
Create new empty AspNetCore project in VS2017(newest updates) and try to add version v4.0.2 with Bower.

#### Expected result
Scripts and style sheets should be installed in wwwroot

#### Additional Information
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Web\External\Bower.cmd" install bootstrap-material-design#v4.0.2 --force-latest --save
'\\mapaz.com\privat\omdirigerade mappar\robert\my documents\visual studio 2017\Projects\Materialize\Materialize'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
bower bootstrap-material-design#v4.0.2           cached https://github.com/FezVrasta/bootstrap-material-design.git#4.0.2
bower bootstrap-material-design#v4.0.2         validate 4.0.2 against https://github.com/FezVrasta/bootstrap-material-design.git#v4.0.2
bower bootstrap#v4-dev                       not-cached https://github.com/twbs/bootstrap.git#v4-dev
bower bootstrap#v4-dev                          resolve https://github.com/twbs/bootstrap.git#v4-dev
bower tether#^1.2                                cached https://github.com/HubSpot/tether.git#1.4.0
bower tether#^1.2                              validate 1.4.0 against https://github.com/HubSpot/tether.git#^1.2
bower jquery#^2.2                            not-cached https://github.com/jquery/jquery-dist.git#^2.2
bower jquery#^2.2                               resolve https://github.com/jquery/jquery-dist.git#^2.2
bower bootstrap#v4-dev                         checkout v4-dev
bower jquery#^2.2                              checkout 2.2.4
bower jquery#^2.2                              resolved https://github.com/jquery/jquery-dist.git#2.2.4
bower bootstrap#v4-dev                       EMALFORMED Failed to read C:\Users\Robert\AppData\Local\Temp\MAPAZ-Robert\bower\ca4c50b905dc21ea17a10549a6f5944f-5484-4vhyyX\bower.json
Additional error details:
Unexpected token @

**Comment by FezVrasta** [comment]
4.0.2 is an unfortunate release. The right one is 4.0.0-beta.3

**Comment by rprimora** [comment]
The unfortunate release :) It's like a fart in public. Anyway, that one doesn't work too. v4.0.0-beta.3-dist is the one that works if someone bumps into this thread.

Cheers

**Comment by FezVrasta** [comment]
Oh Bower, yes, I really hate Bower...

Glad you found a solution.
