### ISSUE TITLE
Dropdown menu does not work - clicking on menu does not open items

### ISSUE THREAD

**Issue by bestin-it** [mdbootstrap/mdb-ui-kit#1244]
#### Test Case
Check this example page: http://rosskevin.github.io/bootstrap-material-design/components/dropdowns/
You cannot open any of the existed items in dropdowns.
I made test in:
Firefox - version 56.0
Chrome - version 61.0.3163.100

#### Summary
The problem is with most popular web browsers

#### Expected result
Items should be displayed

**Comment by FezVrasta** [comment]
That's an outdated and unsupported demo website, the updated one is at https://fezvrasta.github.io/bootstrap-material-design/
