### ISSUE TITLE
Navbar items are pushed off screen with navbar brand and aligned right

### ISSUE THREAD

**Issue by marknl** [mdbootstrap/mdb-ui-kit#1247]
#### Test Case
Material Design Bootstrap 4: https://codepen.io/marknl/pen/GMPQoj
Bootstrap 4: https://codepen.io/marknl/pen/NaeyNa

#### Summary
When you create a navbar with brand and put navbar items on the right side, they're pushed out of the screen. When you remove the brand, it shows correct. The same code works fine with the regular bootstrap 4 CSS. (Tested on Linux Ubuntu 16.04 on Chrome 62.0.3202.62 (64 bits) and Firefox on 56.0 (64-bit))

#### Expected result
Expected to see the dropdown items nicely to the right, showing inside the navbar.

#### Additional
Not completely sure if I'm doing something wrong, or it's an actual bug. Though I'd check here.

**Comment by FezVrasta** [comment]
This should be already fixed in the master branch, it's not yet released unfortunately.

**Comment by marknl** [comment]
Ah, good to hear it's already been fixed!
