### ISSUE TITLE
Some bg color problem with buttons

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#1248]
![image](https://user-images.githubusercontent.com/5382443/31771954-36a89500-b4de-11e7-9736-ff26c23353fe.png)

**Comment by sabrown84** [comment]
Hi @FezVrasta,

Is there any additional information on this one?

**Comment by FezVrasta** [comment]
I haven't investigated yet. There's that unwanted background when you keep a button pressed and move the mouse outside it.

**Comment by sabrown84** [comment]
Has this already been fixed...I can't seem to reproduce this one.

**Comment by FezVrasta** [comment]
Umh, yeah I can't repro this as well, maybe it has been fixed already in one of the previous releases.
