### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by uebbi** [mdbootstrap/mdb-ui-kit#1249]
I like suggest to update [documentation](https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/getting-started/download/) adjusting links to version 4.0.0-beta.**4**

I just lost some time with a bug in dropdown in version 4.0.0-beta.**3** that doesn't exist on beta.4

Tks!

**Comment by luk3n** [comment]
Same here, I went crazy trying to figure out why the dropdowns examples from the documentation were working fine and mine didn't.
I didn't know there was a 4.0.0-beta.4 until you said it. It's available through bower but not documented anywhere.

**Comment by FezVrasta** [comment]
Updated, thanks for the heads up.
