### ISSUE TITLE
Colorizing cards header and footer

### ISSUE THREAD

**Issue by babbisch** [mdbootstrap/mdb-ui-kit#1252]
When colorizing cards the header and the footer of the card is always white:

https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/components/card/#background-and-color

Because of this definition:

`background-color: #fff`

Changing it in 

`background-color: rgba(0,0,0,.03)`

colorizes the header and footer

**Comment by FezVrasta** [comment]
Thanks for the issue, feel free to send a PR to change this.

**Comment by sabrown84** [comment]
Hi I'd like to try this PR is it still open?

**Comment by FezVrasta** [comment]
sure thing!

**Comment by sabrown84** [comment]
I'm having a little trouble trying to figure out where to put this...any suggestions?

**Comment by FezVrasta** [comment]
There's a `_cards.scss` file in `scss/` folder you can use to change the style of the cards.

You are looking for the `.card-header` selector

**Comment by sabrown84** [comment]
Yes I thought it would be the .card-header selector or would it be [here](https://github.com/FezVrasta/bootstrap-material-design/blob/27c397578b58d2c1da4c4dc57d97b8e42d1286e1/docs/4.0/examples/album/album.css)?

**Comment by FezVrasta** [comment]
Nope that's just some CSS for the examples. It's not part of the shipped product.


Anyway I think the card-header background should just be `transparent` to better follow the Material Design spec.

https://material.io/guidelines/components/cards.html#cards-content-blocks

**Comment by sabrown84** [comment]
Ok I understand. Thank you! 👍
