### ISSUE TITLE
JS should not require textarea to be class=form-control

### ISSUE THREAD

**Issue by steren** [mdbootstrap/mdb-ui-kit#1254]
The https://github.com/handsontable/handsontable library creates textarea under the hood.
As a user of this library, I have no control over its class.

When initializing `bootstrapMaterialDesign`, I get:
`````
Uncaught Error: Textarea element: <textarea id="HandsontableCopyPaste" class="copyPaste" tabindex="-1" wrap="hard"> requires class: form-control
``````

I would suggest that if the `form-control` is not present, then `bootstrapMaterialDesign` just ignores it instead of raising an error.

**Comment by HectorLS** [comment]
_"bootstrap-material-design": "4.0.0-beta.4"_

Hello, this bug its still happening with input text & input email.

Should just ignores it but i got the error and everything crash 😢

**Comment by FezVrasta** [comment]
the fix has not yet been released

**Comment by HectorLS** [comment]
Thanks by the fast replay 👍 
is there an approximate release date ?

**Comment by FezVrasta** [comment]
I'm probably going to release a new beta once Bootstrap releases a new one as well.

**Comment by HectorLS** [comment]
Perfect thank you so much !

**Comment by chamnap** [comment]
@FezVrasta, does this one get fixed and released already? I agree it should just ignore it. Selectize.js automatically create textbox under the hood, and it broke everything.

**Comment by FezVrasta** [comment]
This should be already released AFAIK

**Comment by maximeCote819** [comment]
Hey guys, I still got the same problem as you do/did. If I'm reading this forum rightfully, the problem should've been fixed but yet, still a ton of errors in my console log. Honestly, I'm not even sure it's about the bootstrap material design or my own project, but if you can help, please do so ! 😃  

Here's my errors : 
 
<img width="841" alt="console log errors" src="https://user-images.githubusercontent.com/26975834/38617587-6559fd84-3d65-11e8-890f-1d5dd4bd5506.png">

**Comment by FezVrasta** [comment]
I think you are using an outdated version
