### ISSUE TITLE
Add SASS import tilde "~" info to the documentation

### ISSUE THREAD

**Issue by blisst** [mdbootstrap/mdb-ui-kit#1258]
When compiling SASS I got the following error:
"File to import not found or unreadable: ~bootstrap/scss/functions"

It seems like most people not using Webpack will have this error, so would it be possible to add something about solving this to the documentation?

I solved it with 'node-sass-tilde-importer':

For example:
```
npm install 'node-sass-tilde-importer'
```

In Gulpfile:
```
var tildeImporter = require('node-sass-tilde-importer');
var sass = require('gulp-sass');

// In your SASS compile function
sass({
            includePaths: ['node_modules'],
            importer: tildeImporter
        })
```

**Comment by FezVrasta** [comment]
`node-sass-tilde-importer` is already what this package uses to build the page. Feel free to add a note in the documentation to make it easier to setup custom environments.

Thanks.

**Comment by dkent600** [comment]
I use webpack and I just hit this tonight.  The fix for webpack, in webpack.config.js:

```
    resolve: {
      alias: {
        "bootstrap": path.resolve(nodeModulesDir,"bootstrap/"),  <== THIS LINE
        "BMD": path.resolve(nodeModulesDir,"bootstrap-material-design/scss/"),
      }
    },
```

**Comment by pnghai** [comment]
To who still use grunt-sass, just include the below package
https://www.npmjs.com/package/grunt-sass-tilde-importer
