### ISSUE TITLE
extends vs ovverride 

### ISSUE THREAD

**Issue by rightisleft** [mdbootstrap/mdb-ui-kit#126]
Since you're using sass, im curious about the decision to override bootstrap 3 instead of extending it. 

With the bootstrap-sass-official, you can modify the core bootstrap 3 theme to incorporate your own implementation and brand guidelines. 

What i've seen most folks do is mimic the import structure of in their own sass target
https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap.scss

Becomes:
//mybrand/_sassTarget.css.scss

// Core variables and mixins
@import "bootstrap/variables";
@import "bootstrap/mixins";

@import "mybrand/mixins";
@import "mybrand/variables";

// Core CSS
@import "bootstrap/scaffolding";
@import "bootstrap/type";
@import "bootstrap/code";
@import "bootstrap/grid";
@import "bootstrap/tables";
@import "bootstrap/forms";
@import "bootstrap/buttons";
@...

This leaves the core bootstrap elements in place so you can isolate dependancies and allow for boostrap to be upgraded. 

The benefit of this is that you're not creating a massive inheritance chain. 

Right now, to use this project with any modifications you end up with - SomeBrand on top of BootStrap Material Design on top of Bootstrap 3 Default.

**Comment by FezVrasta** [comment]
I'm following a kind of "bootswatch" style approach, I'm doing this to don't depend on a specific version of Bootstrap and because I find easier develop in this way.
