### ISSUE TITLE
`bmd-help` is not supported on `form-inline`

### ISSUE THREAD

**Issue by dkent600** [mdbootstrap/mdb-ui-kit#1260]
#### Test Case
https://codepen.io/dkent600/pen/NwgqXv

#### Summary
STEPS:

1) browser view width is > 576px
2) you have a `bmd-label-floating` label on a text input
3) the input has a value
4) the form class is `form-inline`
5) you click on the input

RESULT: 
The label is positioned on top of the value in the input.

#### Expected result
The label to not be visible unless the input is empty.

**Comment by FezVrasta** [comment]
Isn't this what you expect?
![image](https://user-images.githubusercontent.com/5382443/33725320-19a64af0-db72-11e7-935c-aa63a39b1d69.png)


What's your browser?

**Comment by dkent600** [comment]
By "on top" I mean overlapping within the input area.  I  believe I saw this in Edge and Chrome.  Did you try the test case?

**Comment by dkent600** [comment]
@FezVrasta  You said "needs test case" but I did provide one.

**Comment by FezVrasta** [comment]
May you attach a screenshot of the problem?

**Comment by dkent600** [comment]
![image](https://user-images.githubusercontent.com/1821666/33743650-be7fb72e-db7b-11e7-9fd5-376f45492c08.png)

**Comment by FezVrasta** [comment]
The problem seems to be that `bmd-help` blocks are not supported  by `form-inline`.

**Comment by PromanSEW** [comment]
Any updates? This bug is very ugly
