### ISSUE TITLE
v4 docs example links are broken

### ISSUE THREAD

**Issue by 185driver** [mdbootstrap/mdb-ui-kit#1270]
#### Test Case
N/A - Docs issue

#### Summary
The two drawer example links in the docs return 404 File Not Found:
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/drawers/#overview

#### Expected result
Working examples

#### Additional Information
Wow, three submitted issues on the same theme. I must be working on something related, ha. I'm quite enjoying using bmd, however! Thanks for the great tool.

Doug

**Comment by KODerFunk** [comment]
Please, publish! :+1:

**Comment by douglasmiranda** [comment]
This page: https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/layout/utilities-for-layout/

Has a link for: https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/components/alerts/

It should be: https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/bootstrap-components/alerts/

**Comment by shayneoneill** [comment]
Yeah I'm kind of struggling on the BMD drawers thing, and the link with example code seems to be dead. Also, while I'm at it, the examples in the docs kind of just look like the vanilla bootstrap ones. We sure we've actually got the right samples in there?

**Comment by FezVrasta** [comment]
I didn't have to time create ad-hoc examples so I'm just using the ones of Bootstrap, which, in any case, is a good way to show how an existing Bootstrap app can get a new look by just switching to this project.

For the links, PRs are welcome.
