### ISSUE TITLE
Floating label acting as if input is not readonly when it is

### ISSUE THREAD

**Issue by vleput** [mdbootstrap/mdb-ui-kit#1271]
#### Test Case
https://codepen.io/vleput/pen/qpjYdL
Simply added a `readonly` on the input of the sample codepen

#### Summary
On click on a `readonly` input with a floating label, the label moves up and the help is displayed under the input, as if the input was focusable

Reproduced on Chrome 63, Firefox 57, Edge 15

#### Expected result
If the input is set to readonly, the label probably should not move and the help should not be displayed?

**Comment by amitgandole** [comment]
hi,

i added 'disabled' instead of readonly. it works as expected.

hope this will work..!!
here is the test case : :

https://codepen.io/amitgandole/pen/opeoje
thanks..!!!

**Comment by vleput** [comment]
@amitgandole Right! I ended up getting the behavior I needed by using `disabled` as well.

I actually didn't find a `readonly` state example in the [Material spec](https://material.io/guidelines/components/text-fields.html#text-fields-states), only `disabled`: so `readonly` may not be in the scope of this repo? Would be great to have it though, as it would allow to submit the value of the input with the form

@FezVrasta Should it look like the current disabled input (and the one from the material spec)?
