### ISSUE TITLE
No ripple effect on JS-created tab elements

### ISSUE THREAD

**Issue by 185driver** [mdbootstrap/mdb-ui-kit#1274]
#### Test Case
https://codepen.io/185driver/pen/ZvZQNY

#### Summary
Windows 10 & Chrome. Tab elements created in HTML markup get a ripple-effect when clicked. Tab elements created in JS and appended to the DOM do not.

#### Expected result
Tab elements created both ways should have the same ripple effect.

**Comment by FezVrasta** [comment]
You can include the [Arrive.js](https://github.com/uzairfarooq/arrive) library before Bootstrap Material Design to fix this.

**Comment by 185driver** [comment]
Thank you.
