### ISSUE TITLE
Several components fails after upgrading to 4.1.0

### ISSUE THREAD

**Issue by evjand** [mdbootstrap/mdb-ui-kit#1275]
This includes at least Dropdown, Modal and Tabs. Not even the docs are working for me right now.

#### Test Case
Example with dropdown from docs.
https://codepen.io/evjand/pen/jYRaqy

#### Summary
I get the following error when I click on elements.
> Cannot read property 'getSelectorFromElement' of undefined

Might be missing something from Util?

**Comment by FezVrasta** [comment]
You are using outdated urls
https://codepen.io/FezVrasta/pen/jYRabV

**Comment by evjand** [comment]
Sorry, i linked the wrong codepen. Here is the correct one: https://codepen.io/evjand/pen/jYRaqy

**Comment by FezVrasta** [comment]
Ok I messed this up, Rollup is trying to import `bootstrap/js/src/util` as external dependency and I have no idea on how to make it embed it as internal :(

**Comment by FezVrasta** [comment]
Fixed with 4.1.1, sorry for the problem :-(

Please do let me know if it works for you

**Comment by evjand** [comment]
Seems to have solved all the problems I experienced. Thanks!

**Comment by FezVrasta** [comment]
You're welcome and thanks for the report!
