### ISSUE TITLE
Drawers component broken in v.4.1.1

### ISSUE THREAD

**Issue by 185driver** [mdbootstrap/mdb-ui-kit#1277]
#### Test Case
https://codepen.io/185driver/pen/rpELoJ

#### Summary
Two things appear to be broken in the drawers component with the change from 4.0.0-beta.4 to 4.1.1:
1. The entire browser window now scrolls vertically instead of just scrolling the `.bmd-layout-content` container. Both `.bmd-layout-header` and `.nav-drawer` divs now scroll out of view and they shouldn't.
2. The offcanvas nav (`.nav-drawer`) is no longer full window height if the page content is less than that. To see the effect, delete my codepen `<li>`s.

#### Expected result
The nav drawer should always be full window height and only the page main content should scroll, as it is in 4.0.0-beta.4.

**Comment by Legotckoi** [comment]
Hello,

I solved this problem, when I set position: absolute for bmd-layout-container.

**Comment by unceasingwaves** [comment]
@Legotckoi 
Thanks it solved my problem.
