### ISSUE TITLE
The letters are cut at the bottom in input

### ISSUE THREAD

**Issue by PromanSEW** [mdbootstrap/mdb-ui-kit#1278]
#### Test Case
https://codepen.io/PromanSEW/pen/LeKzqj

#### Summary
Firefox 58.0 / macOS 10.13.2

When I input letters "qypgj" to `<input>` they are cut at the bottom by default.
If I select text and move mouse down letters become normal

#### Expected result
Letters must be fully viewed by default

#### Additional Information
Screenshot that demonstrates the bug:

<img width="50" alt="2018-01-25 09 00 40 pm" src="https://user-images.githubusercontent.com/5219866/35389495-e58830ea-0212-11e8-8779-dd902962553d.png">

**Comment by billyjov** [comment]
@FezVrasta does it make sence do change here the line-height to `1.5` like the default value?.

**Comment by FezVrasta** [comment]
I don't think that would match the Material Design spec, since the bug is on a single browser I'd say there's something else going on.

**Comment by PromanSEW** [comment]
This issue was fixed by #1291?

**Comment by FezVrasta** [comment]
Yup
