### ISSUE TITLE
Errors during compiling of bootstrap-material-design with ruby gem sass v3.5.5

### ISSUE THREAD

**Issue by Legotckoi** [mdbootstrap/mdb-ui-kit#1279]
Hello,

I tried to build bootstap-material-design in my project using PyCharm IDE.
PyCharm use File Watcher for automatically compiling scss files.

This File Watcher use Ruby gem sass v 3.5.5.

I have got error 
error ../../node_modules/bootstrap-material-design/scss/mixins/_forms.scss (Line 153: Base-level rules cannot contain the parent-selector-referencing character '&'.)

May be I made something wrong or is it bug? Because I haven`t problems with build of actual Bootstrap 4.

**Comment by FezVrasta** [comment]
It seems it is using the Ruby version of the SASS compiler, which isn't supported by this project.
