### ISSUE TITLE
Advertised Bootstrap Dashboard Pro does not use Bootstrap 4

### ISSUE THREAD

**Issue by tturnerdev** [mdbootstrap/mdb-ui-kit#1282]
This issue relates to misinformation on the documentation website:
https://fezvrasta.github.io/bootstrap-material-design/

All affiliate links for "official" _Material Dashboard Pro_ point to a product that does not use Bootstrap 4.

Also, there is verbiage such as:
>Official Pro Kits
>Take Material Design for Bootstrap 4 to the next level with official Material Kit Pro and Material Dashboard Pro.

However, _Material Dashboard Pro_ does not use Bootstrap 4.
I highly recommend removing this incorrect advertisement as it's leading to disputes with the seller.

**Comment by FezVrasta** [comment]
Thanks for the heads up, I didn't notice the ambiguous wording. I'll change it ASAP.

Anyway, the V4 compatible version should come soon AFAIK.

**Comment by tturnerdev** [comment]
@FezVrasta Thanks for the quick response. No problem at all.

Biggest issue for me was the confusion in not immediately realizing it was bootstrap 3.
I wasted some time trying to use the Material Kit and Dashboard together before realizing what was wrong.

I'm looking forward to the V4 compatible version!

**Comment by tturnerdev** [comment]
Material Dashboard PRO (v2.0.x, with BS4 support) came out a few days ago.

Closing this, thanks for the help.
