### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource

### ISSUE THREAD

**Issue by ArGaspar** [mdbootstrap/mdb-ui-kit#1283]
Im getting this error with the JS file, I see another guy had the problem with the css too, so I copied the old link for css that he posted. Does someone have the old JS link?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
