### ISSUE TITLE
Could not get the checked state of a input switch

### ISSUE THREAD

**Issue by lgund** [mdbootstrap/mdb-ui-kit#1286]
#### Test Case
https://codepen.io/anon/pen/eVRmyp

#### Summary
It´s not possible to change the checked status of every switch in this framework. Even if you try it with javascript it´s not possible to change it. Strange that if a click change the state of the switch.
I also need a method to change the state of a switch. How does I make it? Normaly I would remove the checked attribute. But this doens´t work even if I remove the attribute via DOM.

**Comment by FezVrasta** [comment]
you have to trigger a change event on it

**Comment by lgund** [comment]
A change event will also no help cause the checked state can´t be changed. The change event will be called unlimited times. It will just flood the console.

**Comment by FezVrasta** [comment]
Sorry I don't really know what are you talking about.

**Comment by lgund** [comment]
You have a example in the issue. If you open the issue you can see the switches. What I need to do to switch them off via JavaScript. Remove the checked attribute won’t work.

**Comment by FezVrasta** [comment]
As said, it works just fine.

https://codepen.io/FezVrasta/pen/PQjqWr
