### ISSUE TITLE
Minified versions.

### ISSUE THREAD

**Issue by brxkensmile** [mdbootstrap/mdb-ui-kit#1288]
Hi, @FezVrasta !
Please, could you be so kind to add minified versions of JS and CSS, because now, the only option to get newer version of material design is to build up the github project :/

**Comment by FezVrasta** [comment]
Why you say so?

https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.min.js

https://github.com/FezVrasta/bootstrap-material-design/tree/dist/js

**Comment by brxkensmile** [comment]
@FezVrasta all the links (include those, where was said that it is minified version) was only source code :/

**Comment by FezVrasta** [comment]
Where? Can you point me to the page where the links are wrong?

**Comment by brxkensmile** [comment]
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/getting-started/download/

**Comment by FezVrasta** [comment]
ok fixed the URL, thanks
