### ISSUE TITLE
v4 Docs - NPM install

### ISSUE THREAD

**Issue by emilgodsk** [mdbootstrap/mdb-ui-kit#1289]
#### Test Case
N/A Docs

#### Summary

I'm I right that the docs has not been updated currectly? 

https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/getting-started/download/
If we look at that link under npm, it says you should just install bootstrap - should this not be bootstrap-material-design@4.1.1?

Or am i missing something?

**Comment by FezVrasta** [comment]
Right, that should be fixed, thanks.

**Comment by emilgodsk** [comment]
#1290

**Comment by PromanSEW** [comment]
Fixed by #1290?
