### ISSUE TITLE
Unexpected added classes to a switch element on deploy

### ISSUE THREAD

**Issue by 185driver** [mdbootstrap/mdb-ui-kit#1292]
#### Test Case
https://codepen.io/185driver/pen/QQVZWR

#### Summary
According to the docs, the code for adding a Switch is:
```
<div class="switch">
  <label>
    <input type="checkbox" checked>
    Wi-Fi
  </label>
</div>
```
On deploy, a parent span element is programmatically added by bootstrap-material-design to the `.switch` class div, which is not unexpected. Oddly though, two classes are added to the div that seem better suited for input elements that can receive alphanumeric characters rather than to a checkbox input. The two added classes are `.bmd-form-group` and `.is-filled`. Should this be the case?
```
<span class="bmd-form-group is-filled">
  <div class="switch">
    <label>
      <input type="checkbox" checked=""><span class="bmd-switch-track"><div class="ripple-container"></div></span>
      Wi-Fi
    </label>
  </div>
</span>
```
Tested on Windows 10 Chrome only.

#### Expected result
No addition of `.bmd-form-group` or `.is-filled` classes to the parent span element. When I look at the switch examples in the [docs](https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/selections/#switches) with Chrome Dev Tools open, those two classes do **not** get added, but I'm not sure why.

**Comment by FezVrasta** [comment]
Why you say "alphanumeric" characters? `bmd-form-group` is generic to any input element of Bootstrap, the same for `is-filled`.

**Comment by 185driver** [comment]
I'm only sharing my observation of what seems an unexpected behavior that `bmd-form-group` and `is-filled` classes are added to switch elements when they appear to have no effect. Given there are no alphanumeric characters to 'act' upon (like floating a label or changing input text color), it seems an unexpected addition.

And then there's the demo code in the docs that doesn't seem to get these classes added at run time; I'm not sure why that is.

From the [docs](https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/forms/#form-groups):

> the only purpose of the .bmd-form-group is to demarcate Material Design behaviors for a combination of label/input. Focus/hover styling for the label/input is determined based on the .bmd-form-group.

If that's the case, are there label/input focus/hover stylings being demarcated for a switch element? I'm not seeing them, hence the post. Apologies.
