### ISSUE TITLE
onchange event triggered several times

### ISSUE THREAD

**Issue by jdub18** [mdbootstrap/mdb-ui-kit#1293]
#### Test Case
https://codepen.io/marcosmoski/pen/xYQQvy

#### Summary
the issue ocurred on Google Chrome we dont test on other browsers.

#### Expected result
We need a new aditional verification on bootstrap-material-design.js on line 6249 on event attachEventHandlers.
If you have a form and an entry with the onchange event, this event will be activated several times even if you have not changed the field.

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/bootstrap-material-design/issues/1193

**Comment by jdub18** [comment]
Thank you, we solved the problem with the line below: 

```js
$('body').bootstrapMaterialDesign({autofill:false});
```
