### ISSUE TITLE
Dynamically added checkboxes not styled 

### ISSUE THREAD

**Issue by thesmithee** [mdbootstrap/mdb-ui-kit#1294]
#### Test Case
https://codepen.io/anon/pen/MQxodK

#### Summary
I'm trying to generate UI on the fly from data returned from the server in a similar way as within the codepen example (just a larger number of them). However, the checkboxes are not shown as is the case in the codepen when the button is clicked. 

As a workaround, for now, I'm generating the checkboxes within a container `<div>` that is then being used in the jQuery selector to fire off the `bootstrapMaterialDesign()` function. This works, as in, the checkboxes are shown. However, there has to be a better way than this, which seems very hacky. 

#### Expected result

The checkboxes are rendered in material style.

**Comment by FezVrasta** [comment]
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/getting-started/javascript/#dynamically-generated-elements

**Comment by thesmithee** [comment]
@FezVrasta so what you're saying basically is that what I'm doing, to some point, is the only way to do it? Is there a per-input element type init function or something like that?

**Comment by FezVrasta** [comment]
Each newly generated element needs to be initialized to work, the alternative is to write the JS logic by yourself using the view library/framework you prefer.

**Comment by thesmithee** [comment]
@FezVrasta got it. Is the `boostrapMaterialDesign()` the only way to initialize?

**Comment by FezVrasta** [comment]
I guess that's the safest way.

**Comment by thesmithee** [comment]
OK, thanks. I've noticed some weirdness where repeatedly calling that function on each `div` container as described in my issue above generates two `<span>` elements per checkbox, instead of one. It works, but styles and other things are messed up. Oh well, will figure it out.

**Comment by FezVrasta** [comment]
There should be a check that avoids to call the init function multiple times on the same element... 🤔

**Comment by thesmithee** [comment]
@FezVrasta hm, will test some more and create a new issue if I keep seeing this. Maybe I should move the function call to the actual checkbox being generated rather than the div the checkboxes are in?

**Comment by FezVrasta** [comment]
Sorry it's been a while since I directly used this project so I'm going by memory, I think you should call it on the checkbox, the generated `div` is just an "implementation detail" and you shouldn't consider it

**Comment by thesmithee** [comment]
@FezVrasta ah, I see, so if I'm dynamically adding a checkbox, I should add the following HTML blob:

```html
<div class="checkbox">
    <label>
        <input type="checkbox"/> Label here 
    </label>
</div>
```
Then call `bootstrapMaterialDesign();` on just the added input element above?

**Comment by FezVrasta** [comment]
Yes it should be so

**Comment by mathiasleroy** [comment]
I'm having issues here too.  
When the checkbox is added and then initialized with `bootstrapMaterialDesign()` it works.  
But after that when that checkbox is removed from the dom (_e.g._ `v-if` in vuejs ) and then restored, it's broken and you can't reapply the function `bootstrapMaterialDesign()` a second time.

and arrive.js doesn't solve that either
