### ISSUE TITLE
Problem with Jhipster 4.14.1 and bootstrap material design Generator

### ISSUE THREAD

**Issue by DaMair** [mdbootstrap/mdb-ui-kit#1298]
When i try to use the generator on a fresh JHipster installation i get several Errors. 
First one is that "navbar.html" is not found. After that i get the error "Unable to find src/main/webapp/scss/main.scss or missing required jhipster-needle. Style not added to JHipster app." At this point i am not able to fix the problems. Am i missing some installation which is not included/required in Jhipster itself?

Greetings

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
