### ISSUE TITLE
radio buttons not displayed

### ISSUE THREAD

**Issue by hans-d** [mdbootstrap/mdb-ui-kit#13]
I have a working angular app using bootstrap. I'm currently applying the bootstrap-material-design.
Now for the following fragment the radio buttons (circles) are not shown, only the indented text.

```
<div class="modal-body">
    <div class="radio">
        <label>
            <input type="radio" ng-model="custom.format" value="A">
            Choose A
        </label>
    </div>
    <div class="radio">
        <label>
            <input type="radio" ng-model="custom.format" value="B">
            Or B
        </label>
    </div>
</div>
```

I could not find (yet) something in the examples or code to give a me a hint what needs fixing.
The example on http://fezvrasta.github.io/bootstrap-material-design/ is working ok.

Css (via less):

```
@import 'bootstrap';
@import 'material';
@import (inline) 'icons-material-design.css';

```

**Comment by FezVrasta** [comment]
are you using the material.js script? Without it the radios (at the moment) has not a pure css fallback.

**Comment by hans-d** [comment]
yup, that was the issue. Thnx
