### ISSUE TITLE
Dropdown with Material Design

### ISSUE THREAD

**Issue by BrunIF** [mdbootstrap/mdb-ui-kit#130]
Can you make dropdown menu like [this](http://getleaf.com/component/type/dropdowns)?

**Comment by FezVrasta** [comment]
At the moment I'm using Selectize.js to provide dropdown menus, but I don't feel comfortable with it so I've in mind to write my own plugin. I'll need some day, I'll try to add to it the future you require.

**Comment by roeku** [comment]
http://material-ui.com/#/components/dropdown-menu

They've implemented the dropdown pretty good it seems.

**Comment by FezVrasta** [comment]
Check out my project. Dropdownjs
