### ISSUE TITLE
Build error with node-sass v4.8.2

### ISSUE THREAD

**Issue by razorness** [mdbootstrap/mdb-ui-kit#1300]
#### Test Case
- clone repository
- execute `yarn upgrade`
- run `npm run build`

#### Summary
```
{
  "status": 1,
  "file": "/tmp/bootstrap-material-design/scss/mixins/_forms.scss",
  "line": 155,
  "column": 3,
  "message": "Base-level rules cannot contain the parent-selector-referencing character '&'.\n\nBacktrace:\n\tscss/mixins/_forms.scss:155, in mixin `bmd-form-color`\n\tscss/_forms.scss:75",
  "formatted": "Error: Base-level rules cannot contain the parent-selector-referencing character '&'.\n\n       Backtrace:\n       \tscss/mixins/_forms.scss:155, in mixin `bmd-form-color`\n       \tscss/_forms.scss:75\n        on line 155 of scss/mixins/_forms.scss\n>>   &.is-focused {\n\n   --^\n"
}
```

```
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.

       Backtrace:  
           scss/mixins/_forms.scss:155, in mixin `bmd-form-color`  
           scss/_forms.scss:75
        on line 155 of scss/mixins/_forms.scss
>>   &.is-focused {

   --^
```

The reason is found in:

- [scss/mixins/_forms.scss#L155](https://github.com/FezVrasta/bootstrap-material-design/blob/master/scss/mixins/_forms.scss#L155)
- [scss/_forms.scss#L75](https://github.com/FezVrasta/bootstrap-material-design/blob/master/scss/_forms.scss#L75)

#### Expected result
Successful build.

**Comment by FezVrasta** [comment]
Our build uses node-sass, what version are you using? Try 4.5.3 please

**Comment by razorness** [comment]
yarn.lock is currently using v4.7.2 of node-sass, which builds sucessfully. Current version of node-sass is v4.8.2 which is legid due [package.json](https://github.com/FezVrasta/bootstrap-material-design/blob/74bbccf97f600e0ff586413f55f0085c1b293668/package.json#L58).
But build fails with node-sass v4.8.2.

If you include `bootstrap-material-design` scss code in other project and run `yarn upgrade`/`npm update`, you are getting this error.

**Comment by FezVrasta** [comment]
Thanks, they introduced a breaking change in a minor version then... I'd open an issue on their repository to see if this is expected. If so, I guess we'll have to find some way to workaround the problem.

**Comment by FezVrasta** [comment]
Ok looks like that code was never supposed to work.

https://github.com/sass/libsass/issues/2581

I can't find any way to rewrite that mixin to work with the new version requirements... Help is more than welcome.

**Comment by xzyfer** [comment]
I can confirm this error is correct. 

The code is invalid and should never have worked. It worked due a bug that has since been fixed.

Please see [this blog post](https://medium.com/@xzyfer/why-node-sass-broke-your-code-and-semver-1b3e409c57b9) for why this isn't a breaking a change.

You cannot use `&` outside of a selector. In this case 
- `@include bmd-form-color` is called outside of a selector
- inside that mixin `&.is-focus` is called outside of a selector

This is a error because `&` is essentially undefined.

**Comment by FezVrasta** [comment]
How can I tell Sass to consider `&` the `:root` scope of the DOM?

**Comment by xzyfer** [comment]
That's not how `&` works. `&` is always the parent selector.

To get to the root you can use `@at-root`. The following 

```
@at-root (without: all) {
  .is-focused { ... }
}
```

is pretty much the same as 

```
:root { 
  is-focused { .. } 
}
```

**Comment by jpaulomotta** [comment]
@FezVrasta 

I've fixed this issue compiling bmd on a Ruby project that uses Sass 3.5.2. 

I've replaced the buggy `&` for this:
`#{if(&, "&", "*")}`

`scss/mixins/_drawer.scss`
![screen shot 2018-09-04 at 11 47 43 am](https://user-images.githubusercontent.com/1813007/45038853-802ead80-b038-11e8-94ef-01a7abb33880.png)

`scss/mixins/_form.scss`
![screen shot 2018-09-04 at 11 46 53 am](https://user-images.githubusercontent.com/1813007/45038738-3fcf2f80-b038-11e8-9103-a45fade0a90a.png)

sass/sass#1873 helped me out.

Do you want a pull request with these changes? The focus styles looks ok on my end.
![screen shot 2018-09-04 at 11 52 26 am](https://user-images.githubusercontent.com/1813007/45039074-31354800-b039-11e8-92eb-e45fed8db854.png)

**Comment by vishal423** [comment]
I don't see this issue with latest node-sass v4.9.4. Per my understanding from above discussions / blog, it's not complaint with sass specifications. @xzyfer, can you please cross check?
For reference, [dart-sass](https://github.com/sass/dart-sass) v1.14.3, shows this as non compliant.

**Comment by master-vulpus** [comment]
I've run into the same error while updating my dependencies.
The solution of @jpaulomotta works also in my environment :)

Is there a planed version where the fix will be released?
@FezVrasta if you need help, I can try to make the fix and send you an pull-request?

**Comment by AngelinCalu** [comment]
Any updates on this issue?

**Comment by FezVrasta** [comment]
Yea, sorry, a pull request to fix it would be great.

**Comment by klonwar** [comment]
So will you fix this bug?

**Comment by AngelinCalu** [comment]
> Similar bug in `node_modules\bootstrap-material-design\scss\mixins\_forms.scss 153:3`, can you fix this too?
> 
> ```
>       Top-level selectors may not contain the parent selector "&".
>     ╷
> 153 │ ┌   .is-focused,
> 154 │ │   // may or may not be a form-group or bmd-form-group
> 155 │ │   &.is-focused {
>     │ └─────────-^
> ```

This should be ok in the fix but it wasn't yet merged. 

@FezVrasta any idea when you could check an merge?

**Comment by klonwar** [comment]
> This should be ok in the fix but it wasn't yet merged.

Yea, I'm sorry I was a little inattentive

**Comment by Trojaner** [comment]
Would be great if you could push this to npm, currently I can not build because of this:
![grafik](https://user-images.githubusercontent.com/1809172/62000462-4a773500-b0e0-11e9-8ccc-58dd0f03a57a.png)

**Comment by ptejada** [comment]
@FezVrasta  Can't install this hotfix. Please push a new version tag.

---

The only workaround at the moment is to install the package referencing the GitHub repository

```
npm i --save-dev bootstrap-material-design@master

**Comment by MasterBroki** [comment]
Hey guys, I've encountered this issue, but it doesn't seems to be deployed in production. Last version is 4.1.2 and I still encounter this issue @FezVrasta

**Comment by tjmosia** [comment]
I just encountered the same problem with Material Design Components...
`ERROR in ./wwwroot/src/shared/default.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--6-2!./wwwroot/src/shared/default.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 199 of node_modules/@material/button/_mixins.scss, in mixin `mdc-button-container-fill-color`
        from line 181 of node_modules/@material/button/_mixins.scss, in mixin `mdc-button-filled-accessible`
        from line 19 of D:\MOSIA GROUP\Mosia Group\Subsidiaries\Propatti.com\Propatti\Propatti\wwwroot\src\shared\default.scss
>>   &:not(:disabled) {
`

**Comment by ViRuSTriNiTy** [comment]
**Push** because as i encounter this issue also with sass 1.26.0 in `_forms.scss` as @Trojaner posted already.

**Comment by MoAqsam** [comment]
Hi please push to npm as the fix is really needed.
