### ISSUE TITLE
Wrong link to BMD 3 github page

### ISSUE THREAD

**Issue by behradkhodayar** [mdbootstrap/mdb-ui-kit#1302]
When someone clicks **Bootstrap Elements** menu item on [This page](https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/gh-pages-v3/index.html#getting-started), gets redirected to [BMD 3 elements](https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/gh-pages-v3/bootstrap-elements.html) page which is talking about BMD **3**. But the download link there, is linking to version 4 (current version). It should instead link to https://github.com/FezVrasta/bootstrap-material-design/tree/v3 .

**Comment by NickolasBenakis** [comment]
Hello, I would like to fix it

**Comment by INNOVATIVEGAMER** [comment]
I am not understanding why this issue is still open. Can someone help me ?
