### ISSUE TITLE
Not working with dangrossman/bootstrap-daterangepicker plugin

### ISSUE THREAD

**Issue by russellhoff** [mdbootstrap/mdb-ui-kit#1304]
#### Test Case
https://codepen.io/russellhoff/pen/Kozbxw

#### Summary
I've created a web page containing several libraries: Zendesk's SDK, jQuery, MomentJS, Underscore,  DataTables, [Datarangepicker](https://github.com/dangrossman/bootstrap-daterangepicker) and Bootstrap 4.

#### Expected result
When you click on the text input, a little window should appear, so that you can select a data range. However, that window isn't shown.

This is what it should be shown:
![image](http://www.daterangepicker.com/drp.png)

#### Additional Information
It seems that it's a visual issue, as there isn't any console error logged out. Additionally, if you remove bootstrap material design's css and put bootstrap's default, the element works as expected.

I've opened an [issue](https://github.com/dangrossman/bootstrap-daterangepicker/issues/1693) to tha author of Daterangepicker, but he's reluctant to solve the problem.

Could you take a look, please? 

Thank you!

**Comment by FezVrasta** [comment]
I'm sorry, I don't provide support to 3rd party plugins, it wouldn't be feasible.

Consider to ask help to the plugin creator to see if she/he can change the plugin to properly work with different CSS.
