### ISSUE TITLE
not that easy to combine navbar and drawer

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [mdbootstrap/mdb-ui-kit#1307]
**Test Case**
https://codepen.io/anon/pen/pLxQdx

**Summary**
I wanted a simple "dashboard" look with overlay drawer (so not always visible)
As you can see from the TestCase, I just merged the jumbotron and drawer overlay examples together.
But I'm not happy with the result.

**Expected result**
Have a nice styled "navbar-toggler" button for the drawer always visible and stay in the navbar header with all other items (brand, links, search field, menus, ...)

**Additional Information**
I had to change the button class from "navbar-toggler" to "nav-item" to make it visible.
Because if it is (like in the example) "navbar-toggler" it will disappear on large browser windows.

**Comment by veteran29** [comment]
Alternatively you can add `d-block` class to `navbar-toggler`. This an easy fix for the issue.

[Example](https://codepen.io/anon/pen/YaBebR)

**Comment by Jorgen-VikingGod** [comment]
@veteran29 thx for the hint.
Based on your idea, I updated my example to only show the button on "collapsed" state of drawer:
https://codepen.io/anon/pen/XEOBEY

I think I can live with this solution.
