### ISSUE TITLE
Feature request: Use two drawer at the same time

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [mdbootstrap/mdb-ui-kit#1308]
**Test Case** (just one drawer)
https://codepen.io/anon/pen/XEOBEY

**Summary**
Feature request to have two drawer (one left and one right)

**Expected result**
Would be great to have two drawer instead of just one at a time (left or right).
So it is possible to create much cleaner designs with f.e. one "sidebar" drawer (like in the codepen example above) and in addition a second drawer on the right (which is only overlay when needed, to show some info)

**Comment by MasterBroki** [comment]
@Jorgen-VikingGod I made a hack that allows for two drawers on the same side. You can check it on my fork

**Comment by Jorgen-VikingGod** [comment]
thx @MasterBroki .Works for me 👍
