### ISSUE TITLE
Dropdown is broken after of clicking once

### ISSUE THREAD

**Issue by joannesalfa** [mdbootstrap/mdb-ui-kit#1309]
http://rosskevin.github.io/bootstrap-material-design/components/dropdowns/

Just look at first example at **Single button dropdowns**, after of clicking once, it won't open anymore.

**Comment by FezVrasta** [comment]
That's not even the right documentation website of this project 🤷‍♂️

**Comment by joannesalfa** [comment]
According this notice:

**Designed and built by Federico Zivolo (@FezVrasta) (You) and Kevin Ross (@rosskevin). Maintained by our core team with the help of our contributors.

Code licensed MIT, docs CC BY 3.0.

Bootstrap Material Design v4.0.2 is a customization of Bootstrap vv4-dev documentation and source.**

What happened this site? isn't your project?

**Comment by FezVrasta** [comment]
That's not linked anywhere in this repository as far I know

**Comment by rosskevin** [comment]
I'll pull down that old site so it isn't found on google anymore.

**Comment by rosskevin** [comment]
Branch deleted, it should fall out of the cache after a few days.

**Comment by joannesalfa** [comment]
Thanks for clear.
