### ISSUE TITLE
dist/ css contains SASS theme-color(primary)

### ISSUE THREAD

**Issue by 01e9** [mdbootstrap/mdb-ui-kit#1310]
https://github.com/FezVrasta/bootstrap-material-design/blob/1cbc3b61cec55aed78cb201c28eeab69f9fa494a/css/bootstrap-material-design.css#L10483-L10485

https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/bootstrap-components/navs/#javascript-behavior

![screenshot from 2018-04-16 12-12-37](https://user-images.githubusercontent.com/28860670/38800267-8860b648-416f-11e8-9be7-bf07004b021c.png)

**Comment by FezVrasta** [comment]
That should be compiled away 🤔
