### ISSUE TITLE
Bootstrap 3 navbar

### ISSUE THREAD

**Issue by lpil** [mdbootstrap/mdb-ui-kit#1313]
Hello!

I'm having some trouble getting a navbar to render correctly with bootstrap 3, the examples in the bootstrap 3 docs don't work.

If bootstrap 3 still supported (as stated in the repo description)? 

If so, would it be possible for you to share an example of such a navbar with bootstrap 3?

Thanks,
Louis

**Comment by lpil** [comment]
Oops! Ignore me. I thought there was bs 3 support but it seems there is not. Not sure where I got that idea!

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
