### ISSUE TITLE
Checkbox background not right a certain browser zoom levels

### ISSUE THREAD

**Issue by dkent600** [mdbootstrap/mdb-ui-kit#1318]
#### Test Case
https://codepen.io/dkent600/pen/BxeBYX

#### Summary
The checkbox background is not always the right size at various the browser window scales.

STEPS:
1. make sure the checkbox is checked
2. zoom in and out in the browser.  You will observe empty space on different checkbox interior edges at different zoom levels.  The checkbox edge is not flush with the interior background.

#### Expected result
Clean background at all zoom levels, flush with the interior edges of the checkbox.

#### Additional Information
I've tried on Edge and Chrome, same results. 

It's ugly, I hope we can find a fix or recommend a work-around until then.

**Comment by himanshuwt** [comment]
Yes, I'm also facing the same issue.

**Comment by manishmp7** [comment]
Yes, I'm also facing the same issue.

**Comment by FezVrasta** [comment]
Bootstrap doesn't support browser zoom.

**Comment by himanshuwt** [comment]
>> Bootstrap doesn't support browser zoom.

How you can say that? User can zoom the website using ctrl + '+'. And the issue will simply replicate.

**Comment by FezVrasta** [comment]
https://getbootstrap.com/docs/4.3/getting-started/browsers-devices/#browser-zooming
