### ISSUE TITLE
Can Checkbox HTML be the same as Bootstrap HTML?

### ISSUE THREAD

**Issue by dkent600** [mdbootstrap/mdb-ui-kit#1319]
#### Summary
This is a feature request.  I note that the HTML one uses for MBD checkboxes is different from what one uses for Bootstrap 4.

MBD:

```
<div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
```

Bootstrap 4:

```
<div class="form-check">
  <input class="form-check-input" type="checkbox" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1">
    Check me out
  </label>
</div>
```

#### Expected result
MBD HTML to be the same as Bootstrap 4.

#### Additional Information

I really like how generally MBD follows very closely Bootstrap patterns.   That is the whole idea.  In this case it doesn't, however.  Would be great if it did.  (Same for radio buttons if they are also different).

**Comment by brandon14** [comment]
It also can affect form validation as using the default bootstrap setup for form validation will not show validation errors on MBD checkbox.

**Comment by FezVrasta** [comment]
Our custom checkbox implementation is older than the Bootstrap one, that's why they differ, I guess we could easily switch to their new syntax, but I'm not sure how should we handle the breaking change.

Maybe allow both the syntaxes? In that case a PR would be lovely.
