### ISSUE TITLE
Githooks problem?

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#132]
Githooks runs our tasks before the commit but... does it adds the compiled files to the files interested by the commit? For what I seen, no... this should be fixed.

**Comment by TransitoryBliss** [comment]
@FezVrasta could you elaborate and I will look into this

**Comment by FezVrasta** [comment]
I mean, our grunt tasks updates the .min.css files but when I commit something I do:

```
git add something.css
```

and not

```
git add something.min.css
```

so the commit contains only the new something.css and the minified version is just generated but not committed.
