### ISSUE TITLE
Navbar-Drawer: How to put javascript into html code?

### ISSUE THREAD

**Issue by tauchvogel** [mdbootstrap/mdb-ui-kit#1322]
Hi,

I am new to javascript and material design. In your navbar-drawers section you say, that I have to put only one single line of code of javascript to the template.

But I do not know where to put it in? 

Could you please give me an example code?

**Comment by FezVrasta** [comment]
In the documentation there's plenty of info and example templates that explain how to include this project, please read carefully the get started page

https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/getting-started/introduction/
