### ISSUE TITLE
Modal scrolling issue on Android installation of Firefox

### ISSUE THREAD

**Issue by VuNe** [mdbootstrap/mdb-ui-kit#1324]
#### Test Case
https://codepen.io/anon/pen/mKrQYN

#### Summary
There appears to be some strange behavior where Modal elements scroll all over the place, when scrolling a modal overlay that overflows the screen on an Android installation of Firefox.

#### Expected result
To be able to scroll a modal with it's child elements staying in place.

#### Additional Information

This issue was found on a Android 5.0.1 phone with Firefox 60.0.2.
Everything works fine on Windows 10 with Firefox 60.0.1 (64-bit).

**Comment by FezVrasta** [comment]
May you make sure this is a bug of this library and not of Bootstrap itself please?

**Comment by VuNe** [comment]
The modal example works fine at:
https://getbootstrap.com/docs/4.1/components/modal/
But doesn't at:
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/bootstrap-components/modal/

**Comment by FezVrasta** [comment]
May you try with this one?
https://codepen.io/FezVrasta/pen/xzEMZG

**Comment by VuNe** [comment]
The thing is that a modal doesn't seem to behave similarly in a CodePen window as it does on a regular site. As in my original CodePen actually works, but the modal on my environment or the example at GitHub docs doesn't.

I already tested out just using regular Bootstrap .js and .css in my environment and the modals worked fine. The issue actually seems to crop up only when using the .css from this library.
