### ISSUE TITLE
SASS

### ISSUE THREAD

**Issue by amirulasyraf88** [mdbootstrap/mdb-ui-kit#1328]
@import "~bootstrap/scss/functions"; // from bootstrap node_module
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  node_modules\bootstrap-material-design\scss\_variables.scss 56:9                @import
  node_modules\bootstrap-material-design\scss\_core.scss 2:9                      @import
  node_modules\bootstrap-material-design\scss\bootstrap-material-design.scss 3:9  @import
  custom.scss 4:9

Hi I have an issue with SASS which I try to do is > sass custom.scss custom.css

inside custom.scss I put this one @import "node_modules/bootstrap/scss/bootstrap"; 

do I need to install bootstrap or rename bootstrap-material-design ?

**Comment by amirulasyraf88** [comment]
https://snag.gy/RyZanw.jpg here the screenshot

**Comment by FezVrasta** [comment]
You have to install Bootstrap as dependency, also, make sure you have the needed loader as specified in the docs.

**Comment by amirulasyraf88** [comment]
ok thank you very much ^_^
