### ISSUE TITLE
Navs dropdown menu no feedback for selection

### ISSUE THREAD

**Issue by destan** [mdbootstrap/mdb-ui-kit#133]
There is no click/touch feedback on dropdown menu items (`Action`, `Another action` items in this case) of nav component. 

![screenshot from 2014-10-20 12 03 24](https://cloud.githubusercontent.com/assets/442813/4698732/0ca56d60-5838-11e4-99a3-f0e3a423a841.png)

PS: It's the same with Button groups

**Comment by lipis** [comment]
+1

**Comment by FezVrasta** [comment]
fixed with 7585f95
