### ISSUE TITLE
Switches not showing properly

### ISSUE THREAD

**Issue by mathiasleroy** [mdbootstrap/mdb-ui-kit#1330]
Hello,
The switches components do not seem to work for me.

Did I do something wrong?  
Does it need to be activated/initialized somewhere?

Here is a codepen : https://codepen.io/anon/pen/NBpEON?editors=1000

![image](https://user-images.githubusercontent.com/2870437/43078059-94512aac-8e89-11e8-81f8-87d13b32d607.png)

Having same issue with all selections :   
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/selections/#switches

**Comment by FezVrasta** [comment]
Please follow the documentation, it's explained there that you must initialize them with a javascript command. Thanks.

**Comment by mathiasleroy** [comment]
@FezVrasta Can you point me to where in the docs ?
It's not on this page https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/selections/#switches

**Comment by FezVrasta** [comment]
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/getting-started/introduction/#js

**Comment by Bronwin** [comment]
Hi. Could you please clarify what javascript command it needs to be initialized? 

Edited: If it helps anyone,
I changed the following HTML:
```
         <div class="switch">
            <label>
              <input type="checkbox">
            </label>
          </div>
```
To:

```
          <div class="switch">
             <label>
               <input type="checkbox">
               <span class="bmd-switch-track"></span>
             </label>
           </div>
```

And it works now

**Comment by mathiasleroy** [comment]
@Bronwin Thanks! Where did you get that ? I still have issues with the checkboxes (in vuejs when changing routes) so I might find a similar move to solve my problem.

**Comment by Bronwin** [comment]
Hi @mathiasleroy . I checked the source css of the demo page

**Comment by mathiasleroy** [comment]
I didn't find any bmd-checkbox something.
I found that this was added after the `<input>`

```
<span class="checkbox-decorator">
  <span class="check"></span>
</span>
```

But adding it manually break the checkboxes

If only `$('body').bootstrapMaterialDesign();` could be run a second time ? @FezVrasta ?

**Comment by FezVrasta** [comment]
Guys, everything is explained in the documentation. That's why I spent my time writing it.

You have to use Arrive.js

**Comment by mathiasleroy** [comment]
@FezVrasta I do, using arrive.js doesn't help.
Whenever switches or checkboxes are created by vuejs, they bug / don't display.
