### ISSUE TITLE
How to close or toggle drawer by javascript?

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [mdbootstrap/mdb-ui-kit#1331]
I want to trigger a close or toggle of the drawer by javascript (jquery), how can I do this?

**Comment by Jorgen-VikingGod** [comment]
I have now a dirty workaround:
just force the click() event on the toggle button with the data-toggle attribute.

f.e. if my button is like this:

```
<button id="drawerToggleButton" class="navbar-toggler d-block" type="button" data-toggle="drawer" data-target="#dw-s2">
```

I will call:
```
$('drawerToggleButton').click();
```

But it would be great to have a official API to access - to toggle, close or open the drawer by javascript.

**Comment by shayneoneill** [comment]
Yeah its kind of puzzling that the documentation doesnt make any mention of the fact that theres a JS compent to it that isn't supplied.

**Comment by calebfoster** [comment]
Hey @Jorgen-VikingGod I was needing the same thing, looked at the source and the Drawer instance is saved to a data attribute. So you can do something like the following:

`$('#dw-s2').data('bmd.drawer').toggle()`
`$('#dw-s2').data('bmd.drawer').open()`
`$('#dw-s2').data('bmd.drawer').close()`

Hope that helps!

**Comment by Jorgen-VikingGod** [comment]
thanks @calebfoster for this nice solution!

**Comment by mathiasleroy** [comment]
> `$('#dw-s2').data('bmd.drawer').toggle()`
> `$('#dw-s2').data('bmd.drawer').open()`
> `$('#dw-s2').data('bmd.drawer').close()`
> 
> Hope that helps!

It doesn't work for me (using v4.1.1):

> Uncaught TypeError: $(...).data(...).open is not a function

`.toggle()` works ok, but that's not what I'm looking for :/


**EDIT**  
`.show()` and `.hide()` work \o/
