### ISSUE TITLE
The Sticky navbar is invisible on iOS (iPhone - all browsers)

### ISSUE THREAD

**Issue by y471n** [mdbootstrap/mdb-ui-kit#1332]
#### Test Case
https://www.gadget20.com - I've a live version running on this site

#### Summary
On iOS, If I add the bootstrap 4 library it's working normally

#### Expected result
The sticky navbar to be visible on iOS too.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
