### ISSUE TITLE
Form Input's change event is calling automatcally on onFocus event

### ISSUE THREAD

**Issue by koushikbasu** [mdbootstrap/mdb-ui-kit#1334]
https://codepen.io/koushikbasu/pen/rrrgzR
Input element inside form is calling 'change' events on foucus, which is not a usual behavior and so onchange function of input is not working properly. The above pen has a similar example, please solve the issue. thanks.

**Comment by FezVrasta** [comment]
That's the `autofill` behavior, you can disable it.

https://codepen.io/FezVrasta/pen/NBBZbo?editors=1111
