### ISSUE TITLE
Diseapearing switches / checkboxes / radios with routes in vuejs 

### ISSUE THREAD

**Issue by mathiasleroy** [mdbootstrap/mdb-ui-kit#1338]
Hi,

I think there is a bug with vue-router, when you navigate to other route and then come back , the switches / checkboxes / radios disappear.

Here is codepen :  https://codepen.io/anon/pen/bxLpYr?editors=1010
(click on navigation link "bar" and then on "foo" )

I tried to re-run $('body').bootstrapMaterialDesign();
but that's not working.

Can we reactivate them with a javascript command ?

**Comment by FezVrasta** [comment]
You should use arrive.js, it's explained in the documentation.
