### ISSUE TITLE
With Angular where is $('body').bootstrapMaterialDesign(); add ?

### ISSUE THREAD

**Issue by khanghyxda** [mdbootstrap/mdb-ui-kit#1339]
I try using bootstrap-material-design with angular 6. If haven't line $('body').bootstrapMaterialDesign(); bootstrap-material-design not working. Where is $('body').bootstrapMaterialDesign(); add ?

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
