### ISSUE TITLE
Increase the effect visibility

### ISSUE THREAD

**Issue by ruwanthalk** [mdbootstrap/mdb-ui-kit#134]
When I am going through the material designing, I found that google itself, angular and polymer project use much visible effect on their projects. 
Ex: Button click effect. I have already implemented, but not visible as much as in the above projects
https://material.angularjs.org/#/demo/material.components.button
https://www.polymer-project.org/components/paper-elements/demo.html#paper-button

**Comment by FezVrasta** [comment]
Il take a look when I find some time
