### ISSUE TITLE
.form-row > form labels and select alignments are off

### ISSUE THREAD

**Issue by jmalatia** [mdbootstrap/mdb-ui-kit#1343]
#### Test Case
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/bootstrap-components/forms/#form-row
or
https://codepen.io/jmalatia/pen/pxQNwg

#### Summary
1. In a `.form-row`, labels are not horizontally aligned with the input (labels are too far to left).
2. A `select` in a `.form-row` is not vertically aligned with an adjacent `input` (select is below visual baseline of inputs).

Both are visible in chrome, edge and firefox from the main BMD website example.

#### Expected result

Every thing to be aligned  :)

#### Additional Information
![example png](https://user-images.githubusercontent.com/5606334/47442068-42681e80-d777-11e8-9c47-f1d8681c2a78.png)

**Comment by kwatmi** [comment]
![screenshot_2018-11-05 bmd bug form-row alignment is off labels too far to left and select is below baseline](https://user-images.githubusercontent.com/23109232/48025773-9fcf7880-e144-11e8-83ef-a21f2c32ac6f.png)

## follow the steps below to achieve  perfect vertical alignment 

- Add a class to the **select**  `<select id="inputState" class="form-control Kwatmi_tyron">`

- give it a style of height 30px and make it important : see below 

.kwatmi_tyron{
  height:30px !important;
}

**Comment by Deepaksuri76** [comment]
height:30px !important;
The above fix is working in firefox but not in chrome70 and IE11

**Comment by Deepaksuri76** [comment]
Temporarily we can fix this by browser specific below CSS

@media screen and (-webkit-min-device-pixel-ratio:0) { 
    .selector {
        height: 36px !important;
        line-height: 36px !important;
        padding-bottom: 0;
        padding-top: 0;
    } 
}
@-moz-document url-prefix() {
    .selector {
        height: 30px !important;
        padding-bottom: 0px;
        padding-top: 0;
    }
}
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) { 
    .selector {
        height: 36px !important;
        line-height: 36px !important;
    }
}

**Comment by FezVrasta** [comment]
May you please send a PR to fix this?

**Comment by johanfleury** [comment]
@FezVrasta I have a similar issue with a form that looks like that (it is not an inline form, it has other fields):

```
<form>
  <fieldset class="row">
    <div class="col form-group">
      <label for="field1" class="bmd-label-floating">field</label>
      <input id="field1"class="form-control" type="text">
    </div>

    <div class="col form-group">
      <label for="field2" class="bmd-label-floating">Field 2</label>
      <input id="field2" class="form-control" type="text">
    </div>
  </fieldset>
</form>
```

When the field are focused, the labels are slightly moved to the left. This is due to `.row` having a `margin-left: -15px` and `.col` having `padding-left: 15px`.

Would you accept a PR that does something like:

```
.row .bmd-form-group.col .bmd-label-floating {
  left: 15px;
}
```
