### ISSUE TITLE
How to adding material-icon inside input text?

### ISSUE THREAD

**Issue by hid0** [mdbootstrap/mdb-ui-kit#1344]
how to add Icon Prefixes in inputs text like in materializecss
[https://materializecss.com/text-inputs.html](this)

**Comment by willianbello** [comment]
Uma das maneiras é colocando um input-group.
Não irá ficar exatamente igual ao mostrado, mas terá um efeito muito semelhante.


<div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" style="background: white;" id="basic-addon1">
                        <i class=" fas fa-search"></i>
                    </span>
                </div>
                <input type="text" class="form-control" style="border-left: 0px solid white;" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
            </div>

**Comment by willianbello** [comment]
Utilizando Bootstrap
script para Font Awesome

< script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js" integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0" crossorigin="anonymous"></script>


Uma das maneiras é criando uma div com a classe input-group-prepend.
Dentro dela você cria um span com a classe input-group-text
Dentro da span pode utilizar a Font Awesome pra colocar um ícone
< div class="input-group mb-3" >
                < div class="input-group-prepend" >
                    < span class="input-group-text" style="background: white;" id="basic-addon1" >
                        < i class=" fas fa-search" >< /i >
                    < /span>
                < /div>
                < input type="text" class="form-control" style="border-left: 0px solid white;" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
            < /div>

**Comment by willianbello** [comment]
Utilizando Bootstrap
script para Font Awesome

< script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js" integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0" crossorigin="anonymous"></script>

Uma das maneiras é criando uma div com a classe input-group-prepend.
Dentro dela você cria um span com a classe input-group-text
Dentro da span pode utilizar a Font Awesome pra colocar um ícone
< div class="input-group mb-3" >
< div class="input-group-prepend" >
< span class="input-group-text" style="background: white;" id="basic-addon1" >
< i class=" fas fa-search" >< /i >
< /span>
< /div>
< input type="text" class="form-control" style="border-left: 0px solid white;" placeholder="Pesquisa" aria-label="Username" aria-describedby="basic-addon1">
< /div>

**Comment by willianbello** [comment]
Utilizando Bootstrap
script para Font Awesome

< script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js" integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0" crossorigin="anonymous"></script>

Uma das maneiras é criando uma div com a classe input-group-prepend.
Dentro dela você cria um span com a classe input-group-text
Dentro da span pode utilizar a Font Awesome pra colocar um ícone
< div class="input-group mb-3" >
< div class="input-group-prepend" >
< span class="input-group-text" style="background: white;" id="basic-addon1" >
< i class=" fas fa-search" >< /i >
< /span>
< /div>
< input type="text" class="form-control" style="border-left: 0px solid white;" placeholder="Pesquisa..." aria-label="pesquisa" aria-describedby="basic-addon1">
< /div>
