### ISSUE TITLE
Replace `~` with nothing

### ISSUE THREAD

**Issue by moonglum** [mdbootstrap/mdb-ui-kit#1349]
#### Summary
This package uses `~bootstrap/scss/functions` to import things from bootstrap. This works via the [node-sass-tilde-importer](https://github.com/matthewdavidson/node-sass-tilde-importer) extension. I propose removing the tilde and instead extend the include path.

#### Expected result
This will result in an easier build that is more portable to different task runners etc.

#### Additional Information

sass allows to extend the include path. In the `sass` NPM package, the CLI accepts a parameter `-I` to add a folder to the include path. I regularly use this to add the `node_modules` folder to the include path. Doing that would allow to import parts from bootstrap without using any extension or `~`.

```
sass -I node_modules index.scss
```

with index.scss being:
```scss
@import "bootstrap-material-design/scss/bootstrap-material-design";
```
would work.

The include path option is also available [via the API](https://github.com/sass/node-sass#includepaths), which can usually be set by any task runner.

**Comment by FezVrasta** [comment]
That was the approach I used before the adoption of the tilde importer, people couldn't figure out how to configure their sass compiled to include the node_modules path, so we moved to the tidle importer that makes the operation easier.

https://github.com/FezVrasta/bootstrap-material-design/pull/1214#issuecomment-327230956

To add to this, webpack makes use of the tilde as a standard convention to import from `node_modules` so it makes sense to use it to help webpack users.
