### ISSUE TITLE
button-groups don't release selection

### ISSUE THREAD

**Issue by rightisleft** [mdbootstrap/mdb-ui-kit#135]
OS: OS X 10.9
Browser: Chrome 
Issue:
When i click between different elements in a button-group, the active state seems to get stuck. 

Location:
http://fezvrasta.github.io/bootstrap-material-design/

Repro:
In the 1,2,3,4 button group - click between different buttons 

Impacts all button-groups

**Comment by rightisleft** [comment]
Actually - it seems to occur with more frequency on the vertical groups... 

<div class="btn-group-vertical">
    <a href="javascript:void(0)" class="btn btn-default">Button</a>
    <a href="javascript:void(0)" class="btn btn-default">Button</a>
    <a href="javascript:void(0)" class="btn btn-default">Button</a>
    <a href="javascript:void(0)" class="btn btn-default">Button</a>
</div>

Result:
http://imgur.com/sNa0OGD

**Comment by FezVrasta** [comment]
it happens when you click the button, move the mouse and then release the click. It's a problem already known, stil in the tofix list

**Comment by FezVrasta** [comment]
should be fixed
