### ISSUE TITLE
File to import not found or unreadable

### ISSUE THREAD

**Issue by dreamysx** [mdbootstrap/mdb-ui-kit#1354]
Hi, I got this error after updating Node version.
```
Error: node_modules\clear-platform-common\lib\common\clearBootstrap\_clearBootstrap.scss
Error: File to import not found or unreadable: ../../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap/glyphicons.
       Parent style sheet: H:/node_modules/clear-platform-common/lib/common/clearBootstrap/_clearBootstrap.scss
        on line 14 of node_modules/clear-platform-common/lib/common/clearBootstrap/_clearBootstrap.scss
@import  "../../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap/gl
at options.error (H:\node_modules\js-build-engine\node_modules\node-sass\lib\index.js
```

I am not able to modify any sass file. I cannot fix it by "npm update" nor "npm install".

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
