### ISSUE TITLE
Laravel 5.8 Webpack mix Can't resolve 'popper' 

### ISSUE THREAD

**Issue by Max75010** [mdbootstrap/mdb-ui-kit#1356]
Hi, 

#### Test Case
Sorry  but it is difficult to give a codepen for this.

#### Summary
I'm using Laravel 5.8, and trying to get bootstrap 4.2.1 and bootstrap-material-design 4.1.1 working.
I've already fixed the mixing / functions / variables problems (found the solution [here](https://github.com/FezVrasta/bootstrap-material-design/issues/1300))
but now I'm facing an issue building the javascript.
I keep getting the error:

```
_ERROR in ./node_modules/bootstrap-material-design/dist/js/bootstrap-material-design.js
Module not found: Error: Can't resolve 'popper'_
```

event after trying many solutions.

#### Additional Information
Here is my `webpack.mix.js`:

```
const mix = require('laravel-mix');
mix.autoload({
        jquery: ['$', 'window.jQuery', 'jQuery'],
        'popper.js/dist/umd/popper.js': ['Popper']
    })
    .js( 'resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .styles(['public/css/override.css',],'public/css/all.css')
    .version()
```

My bootstrap.js:

```
window._ = require('lodash');
import Popper from 'popper.js/dist/umd/popper.js';

try {
    window.$ = window.jQuery = require('jquery');
    window.Popper = Popper;
    require('bootstrap');
} catch (e) {}
```

And my app.js:

```
require('./bootstrap');

// Register $ global var for jQuery
import $ from 'jquery';
window.$ = window.jQuery = $;

import 'bootstrap-material-design/dist/js/bootstrap-material-design.js';
```

Anyone has an idea of what I m doing wrong ?

**Comment by poldelgado** [comment]
I 've the same issue in laravel 7, someone could resolve it?
