### ISSUE TITLE
Switch change event issue

### ISSUE THREAD

**Issue by AndrewLawendy** [mdbootstrap/mdb-ui-kit#1359]
#### Test Case
The issue doesn't appear of codepen but it appears on your documentation [page](https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/selections/#switches)

#### Summary
Any change event on the switch keeps repeating

#### Expected result
Change event to be executed once.

#### Additional Information
![image](https://user-images.githubusercontent.com/22712035/56092321-08bcd880-5ebb-11e9-8063-26e967aa673a.png)

**Comment by ltrtuan** [comment]
Same problem with checkbox in my project
