### ISSUE TITLE
Docs show unstyled checkboxes

### ISSUE THREAD

**Issue by lordi** [mdbootstrap/mdb-ui-kit#1361]
Am I missing something, or are the checkboxes and radio buttons in currently broken/unstyled in the documentation at https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/bootstrap-components/forms/#checkboxes-and-radios ?

![image](https://user-images.githubusercontent.com/232086/56787282-5101c200-67fc-11e9-833d-125c0ced9620.png)

**Comment by FezVrasta** [comment]
Material forms are in their own section 
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/forms/
