### ISSUE TITLE
Which version supports the Boostrap 3?

### ISSUE THREAD

**Issue by NickolasBenakis** [mdbootstrap/mdb-ui-kit#1364]
Hello,
Does anyone knows which build version supports the Bootstrap 3 ?
this page : https://cdn.rawgit.com/FezVrasta/bootstrap-material-design/gh-pages-v3/index.html
does not provide the actual version number when npm install.

Thanks a lot :)

**Comment by FezVrasta** [comment]
Any version prior to 4.0 is made for Bootstrap 3.0

0.5.10 is the most recent Bootstrap v3 compatible

**Comment by NickolasBenakis** [comment]
Thanks a lot @FezVrasta  :)

**Comment by NickolasBenakis** [comment]
sorry to bother again but, 
is there any existing CDN  link & script url for this version [0.5.10] that works?

**Comment by FezVrasta** [comment]
https://unpkg.com/bootstrap-material-design@0.5.10/dist/
