### ISSUE TITLE
Init JavaScript

### ISSUE THREAD

**Issue by CKGrafico** [mdbootstrap/mdb-ui-kit#1366]
In the docs I can read that is mandatory to execure
`$('body').bootstrapMaterialDesign();` to init the library (for example ripple effects)

I'm in a SPA with Vuejs if I change the page have I to execute again `$('body').bootstrapMaterialDesign();`? Seems not the most performant idea :(

**Comment by CKGrafico** [comment]
I've created a plugin inside my project to solve this situation.
If you're using Vue, this probably will work for you:

```
export const Material = {
  install(Vue) {
    Vue.mixin({
      mounted() {
        $(this.$el).bootstrapMaterialDesign();
      }
    });
  }
};

```
 Not sure if is the best option, but is working. Is probably time to upgrade your library and make it compatible with this kind of frameworks creating and maintaining plugins like this :)

**Comment by FezVrasta** [comment]
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/getting-started/javascript/#dynamically-generated-elements
