### ISSUE TITLE
Ripple doesn't fade away in some circumstances

### ISSUE THREAD

**Issue by MarshallOfSound** [mdbootstrap/mdb-ui-kit#137]
In some cases the ripple effect doesn't fade out leaving the buttons or <li> elements darker than they were previously and if repeated they darken to the point of unread-ability.

The only way I can replicate this issue 100% of the time is to click and drag off a button.  Method is as follows.
1. Click and hold on a button
2. While still holding move the mouse rapidly off the button
3. Watch as the ripple effect doesn't disappear.

**Comment by rightisleft** [comment]
I think this is the same issue:

https://github.com/FezVrasta/bootstrap-material-design/issues/135

**Comment by MarshallOfSound** [comment]
Ahh yes, so it is.  Didn't see that issue
