### ISSUE TITLE
SASS ERROR RESULTS AN INCOMPATIBILITY WITH ANGULAR 8

### ISSUE THREAD

**Issue by imalhasaranga** [mdbootstrap/mdb-ui-kit#1372]
#### Test Case
Sorry I don't have a test case

#### Summary
Your code `bootstrap-material-design/scss/mixins/_forms.scss` line `153` is not compatible with `sass` please kindly fix it as top-level selectors may not contain the parent selector "&", this create a compatibility issue when i'm upgrading angular 7. * app to 8.*  

#### Read More

https://github.com/angular/angular-cli/issues/14497

**Comment by vishal423** [comment]
Isn't that resolved by #1370 ?

**Comment by imalhasaranga** [comment]
yes it has.. this is not in prod right ?

**Comment by FezVrasta** [comment]
Sorry I'm traveling and didn't have time to cut a new release yet.

**Comment by juliapacula** [comment]
When will it be available on prod?
