### ISSUE TITLE
Need Drag Drop Menu

### ISSUE THREAD

**Issue by rootflood** [mdbootstrap/mdb-ui-kit#1374]
hi and thanks for awesome and simple tool

i need a menu which i able to drag that for close the menu
like mobile devices menus
something like : https://materializecss.com/mobile.html

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
