### ISSUE TITLE
Broken validation UI for text fields

### ISSUE THREAD

**Issue by ptejada** [mdbootstrap/mdb-ui-kit#1379]
#### Test Case
https://codepen.io/ptejada/pen/OJLOdQN

#### Summary
In the latest build or 4.1.2 the validation UI for text fields is broken. I might be affecting other elements like selects. When a field is valid the underline is gone instead a green checkmark is shown. When a field is not valid a the underline is also gone and red X is shown. When the invalid is in focus the X floats to the center of the field.
![image](https://user-images.githubusercontent.com/253405/64309195-c8452080-cf69-11e9-939f-01053d0d35c2.png)

#### Expected result
![image](https://user-images.githubusercontent.com/253405/64309190-c4b19980-cf69-11e9-86f6-150641c3b3ea.png)
Same test case with version 4.1.1
https://codepen.io/ptejada/pen/PoYOVaN

#### Additional Information
This issue can be related to PR https://github.com/FezVrasta/bootstrap-material-design/pull/1370

**Comment by tschortsch22** [comment]
Hi,
are there any news regarding this issue?

Kind regards,
Tschortsch
