### ISSUE TITLE
Missing ripple.js compatibility with default browser of Android

### ISSUE THREAD

**Issue by jjalonso** [mdbootstrap/mdb-ui-kit#138]
From mobile (Nexus 5 kitkat) the demo page work fine. The ripple effect work properly.

But when is used in Phonegap/AngularJS Ripple effect show only a little circle where i touch.

Im using all dependencies:

```
      <script src="vendors/jquery-2.1.1.min.js"></script>
      <script src="vendors/bootstrap-material/js/material.min.js"></script>
      <script src="vendors/bootstrap-material/js/ripples.min.js"></script>
      <link rel="stylesheet" href="vendors/bootstrap.min.css">
      <link rel="stylesheet" href="vendors/bootstrap-material/css/material-wfont.min.css">
      <link rel="stylesheet" href="vendors/bootstrap-material/css/ripples.min.css">
      <link rel="stylesheet" href="vendors/bootstrap-material/css/material.min.css">
```

Using in this way:

```
      <button type="button" class="btn btn-flat btn-material-indigo">
        <i class="mdi-navigation-menu"></i>
      </button>
```

OR

```
        <a class="btn btn-material-indigo btn-fab btn-raised mdi-content-add"></a>
```

Look screenshot. (SEE FAB BUTTON)
![screenshot 10-49pm oct 21 2014](https://cloud.githubusercontent.com/assets/389467/4729399/cc28ac58-5985-11e4-8971-0e86bc940740.png)

**Comment by jjalonso** [comment]
Im trying of find a reason.. Angular cannot do nothing con that :-s

**Comment by FezVrasta** [comment]
not sure what the problem could be, you should use the dev tools and look what happens to the ripple.

**Comment by jjalonso** [comment]
Mmmm. I think that angular is not the guilty, because when i run my angular
project in desktop, is working. But not in Mobile running over PhoneGap, i
tried to use Ripple phonegap emulator in my desktop, but is working fine,
then is not a valid testing environment. (http://emulate.phonegap.com/)

2014-10-23 10:49 GMT+01:00 Fez Vrasta notifications@github.com:

> not sure what the problem could be, you should use the dev tools and look
> what happens to the ripple.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FezVrasta/bootstrap-material-design/issues/138#issuecomment-60216057
> .

## 

```
         Descargala en Google Play
```

https://play.google.com/store/apps/details?id=com.rocktaps.climatip&hl=es
                   Twitter @Climatip https://twitter.com/Climatip
                       - Rocktaps -

**Comment by jjalonso** [comment]
The reason is that, phonegap use native android webview for render the
page, and the project is working fine under chrome, but not under native
android browser.

Is not compatible with native (builtin)  android browser

2014-10-28 9:17 GMT+00:00 Fez Vrasta notifications@github.com:

> Closed #138
> https://github.com/FezVrasta/bootstrap-material-design/issues/138.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FezVrasta/bootstrap-material-design/issues/138#event-184558313
> .

## 

```
         Descargala en Google Play
```

https://play.google.com/store/apps/details?id=com.rocktaps.climatip&hl=es
                   Twitter @Climatip https://twitter.com/Climatip
                       - Rocktaps -

**Comment by FezVrasta** [comment]
android L should allow use of chrome as renderer of the webviews. it should fix the problem I guess.

**Comment by jjalonso** [comment]
Yeah but, its not possible launch a production app with a user rate of
0.N...% of users.

I will look more forward about a solution.

2014-10-28 11:32 GMT+00:00 Fez Vrasta notifications@github.com:

> android L should allow use of chrome as renderer of the webviews. it
> should fix the problem I guess.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FezVrasta/bootstrap-material-design/issues/138#issuecomment-60742156
> .

## 

```
         Descargala en Google Play
```

https://play.google.com/store/apps/details?id=com.rocktaps.climatip&hl=es
                   Twitter @Climatip https://twitter.com/Climatip
                       - Rocktaps -

**Comment by destan** [comment]
:+1: 

came here to open the exact same bug and find this one 

any solution yet?

Besides, in [this link](https://developer.chrome.com/multidevice/webview/overview) it's stated that WebView uses chrome for rendering engine for 4.4+ however the bug exists on Nexus 4 and Nexus 7 (tablet) whereas both have Android 4.4.4

**Comment by FezVrasta** [comment]
I had no time yet to fix this problem. Any PR is very welcome as usual :)

**Comment by jjalonso** [comment]
Also in my Nexus 5 4.4.4... 

Android 4.4.4 in theory use chromium webview... then im starting to think that is not the problem.
Is true ?

**Comment by FezVrasta** [comment]
Probably... Maybe it uses an old version of chrome

**Comment by FezVrasta** [comment]
This bug should be fixed with fc0fed6eabec91e4535d78d06478a25c1fff67ce (:develop branch)

May you try it out and give me feedbacks?

**Comment by jjalonso** [comment]
I will try to use it this week.

Another tip:  In android 5 is working without problem.

**Comment by FezVrasta** [comment]
I've checked the compatibility with the stock browser (HTC One M8 4.4.4) and everything works fine. I'm closing this issue. Feel free to open a new one in case the problem happens again.

**Comment by kamaldlk** [comment]
Angularjs Material design Not working in Phone-Gap android4.2 and 4.4 , but working 5.0 please help me anyone if know the answer

<md-toolbar style="height: 64px;">
        <h2 class="md-toolbar-tools">
            <span>Sign In</span>
        </h2>
    </md-toolbar>

**Comment by FezVrasta** [comment]
Please open a new issue with more details
