### ISSUE TITLE
Documentation Request - How to setup in react app for theme overwrite

### ISSUE THREAD

**Issue by ChristopherHButler** [mdbootstrap/mdb-ui-kit#1380]
I was looking to use this package in a create-react-app and wanted to overwrite the theme. I can get it to work from the cdn just fine but then I am stuck with the default theme. I was wondering if there was any documentation on the steps required to get this working with a react project. I have installed the package with npm and created a custom.scss file as suggested in the installation docs, importing bootstrap but I get an error: `File to import not found or unreadable: ../../node_modules/bootstrap/scss/bootstrap.`. I would greatly appreciate a few steps on what is needed to bootstrap(-material-design) a react app with this package.

**Comment by gringolalia** [comment]
My experience is similar. It seems perhaps the docs have been cloned over from Bootstrap plain-vanilla and should account for the @import of the corresponding bootstrap-material-design file in the @import statement? In my case I am using a Vue project.

**Comment by tombohub** [comment]
I think you should use 'bootstrap-material-design' instead of 'bootstrap'.  
Because there is no bootstrap folder in node_modules

**Comment by ViRuSTriNiTy** [comment]
The docs are directly taken from bootstrap hence the paths are wrong. Here is an example `custom.scss` file:

```
$theme-colors: (
    primary: red,
    secondary: green,
    light: gray,
    dark: black
);

@import "node_modules/bootstrap-material-design/scss/bootstrap-material-design";
```
