### ISSUE TITLE
Opened modals has too much space above

### ISSUE THREAD

**Issue by rougin** [mdbootstrap/mdb-ui-kit#139]
Is it me or the opened modals has too much space above within the browser?

![hehehehe](https://cloud.githubusercontent.com/assets/6078637/4732073/4d91b5c0-59b6-11e4-907d-e222542a4b5a.jpg)

**Comment by FezVrasta** [comment]
I don't think I've edited this aspect of the modal dialogs... I'll check out this problem when I'll have some free time
