### ISSUE TITLE
UI not updating when new html content on jQuery - AJAX load() 

### ISSUE THREAD

**Issue by jason-cemanes** [mdbootstrap/mdb-ui-kit#1392]
UI not updating when new html content on jQuery load function (Ex ripple effects, floating label), I tried to reinitialize the ui by using this code $('body').bootstrapMaterialDesign(); & it works but the problem now is when I use this code after load function in jquery & display "multiple input fields" in my form makes input lag.

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
