### ISSUE TITLE
Release patched version.

### ISSUE THREAD

**Issue by halfnibble** [mdbootstrap/mdb-ui-kit#1393]
You have some very important fixes (like this one: https://github.com/FezVrasta/bootstrap-material-design/issues/1300) that must be released in order for Sass to transpile on the latest build tools. 

Can we please get a patch release? Current master is working ok for me. Thanks.

**Comment by james090500** [comment]
I'm just going to follow on this, really needing this version adding to NPM. Would be amazing if this could be done.

**Comment by FezVrasta** [comment]
I just released a new version yesterday.

**Comment by james090500** [comment]
I can't believe it. I've been looking at this github for the past week trying to get a working version. The one day I don't look you update it!

Thank you very much and sorry for bothering you! 🥳
