### ISSUE TITLE
Upgrade to newest Bootstrap version

### ISSUE THREAD

**Issue by rh78** [mdbootstrap/mdb-ui-kit#1394]
Hello,

I'd like to suggest an upgrade of Bootstrap to the newest version. Bootstrap 4.0.0 has known security issues: https://snyk.io/test/npm/bootstrap/4.0.0

We discovered this during a penetration test.

Please advise.

Best wishes!

**Comment by FezVrasta** [comment]
Thanks, I need to dedicate some time to update the project, but I'm currently focused on the next release of Popper.js so it may take some time.

**Comment by rh78** [comment]
Hello can you please give an update about the status? Thank you!

**Comment by xperseguers** [comment]
Hello. Any news here?

**Comment by FezVrasta** [comment]
Sorry, no news, but PRs are welcome.

**Comment by MrCordeiro** [comment]
I would update this request to bump bootstrap up to v4.5, as v4.1 and v4.2 also have vulnerabilities.
https://snyk.io/vuln/npm:bootstrap

**Comment by hgnelson83** [comment]
Man, I would love this mixture of Material Design to have the latest version of Bootstrap 4.5.x

**Comment by rh78** [comment]
Look at the acticity on this project. It seems to be dead. We ripped it out of our solution some time ago and switched to Vue/Vuetify.

**Comment by hgnelson83** [comment]
> Look at the acticity on this project. It seems to be dead. We ripped it out of our solution some time ago and switched to Vue/Vuetify.

Thanks for your input. 

I am going to implement Vue/Vuetify into my Laravel project then.
