### ISSUE TITLE
suggestions for input type=file

### ISSUE THREAD

**Issue by hans-d** [mdbootstrap/mdb-ui-kit#14]
Would love to see some example(s?) on how to style the file selection to best fit this theme. May involve JS.

**Comment by FezVrasta** [comment]
I'll need it for my own project in few days so I'll do it when I'll be back from vacation.

**Comment by FezVrasta** [comment]
Implemented with a3a371757ccf066b85146a30a602a9e14dfcfc0e.

This is just a first draft because I can't find any example of file input in material design style, if someone has some better idea just let me know.
