### ISSUE TITLE
Button dropdown are not working on Microsoft Browsers IE/Edge

### ISSUE THREAD

**Issue by Nishant-Choudhary** [mdbootstrap/mdb-ui-kit#1403]
#### Test Case

Button Dropdown on Microsoft Browsers(IE/ Edge)
#### Summary

I have tested below link on IE version: 11.13 and Edge Version: 42.17134.1098.0. Dropdown are not working.

https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/bootstrap-components/button-group/

**Comment by ViRuSTriNiTy** [comment]
This is most likely caused by broken java-script initialization calls in Edge. You can verify that by looking at the developer console, there should be a javascript error right?
