### ISSUE TITLE
material is not defined

### ISSUE THREAD

**Issue by FardinSaboori** [mdbootstrap/mdb-ui-kit#1407]
hello guys,
i wrote a program for web development and it seems that everrything is ok except for this error **material is not defined**
i used this code to initialize material:
$.material.init();

**Comment by FezVrasta** [comment]
Thank you for your issue.

Unfortunately I can't answer to all the reported issues without a little help from you.
Please, make sure to follow the **issues template** when you submit a new issue, in this way I will already have all the informations needed to understand the problem and help you with it.

I'm closing this issue for now, but feel free to open a new one making sure to follow all the instructions!

Thank you for your understanding.
