### ISSUE TITLE
Django: CompileError with django-libsass on @import statements

### ISSUE THREAD

**Issue by christiankyle-ching** [mdbootstrap/mdb-ui-kit#1413]
#### Test Case
N/A

#### Summary
Trying to theme using Sass source files. Using django-libsass (v0.8), libsass cannot proceed to compile bootstrap-material-design.scss due to import errors.

#### Expected result
CompileError (Additional information below)

#### Additional Information

Django Version: 3.0.7
Exception Type: CompileError
Exception Value:
Error: File to import not found or unreadable: ~bootstrap/scss/functions.
         on line 56:1 of rooms/static/bootstrapmd/scss/_variables.scss
         from line 2:1 of rooms/static/bootstrapmd/scss/_core.scss
         from line 3:1 of rooms/static/bootstrapmd/scss/bootstrap-material-design.scss
         from line 2:1 of rooms/static/css/style.scss >> @import "~bootstrap/scss/functions"; // from bootstrap node_module

Note: I tried to compile the original Bootstrap 4.0.0 with no issues (proceeds to compile).

**Comment by FezVrasta** [comment]
bmd 4.1.3 should work, may you tell me which version are you using?

**Comment by christiankyle-ching** [comment]
> bmd 4.1.3 should work, may you tell me which version are you using?

I'm using 4.1.3.
