### ISSUE TITLE
Snackbar not working - container has wrong ID

### ISSUE THREAD

**Issue by drozdik-m** [mdbootstrap/mdb-ui-kit#1415]
I use Chrome and for some reason, the container appends with id `"snackbar-container/"` instead of `"snackbar-container"` (notice the '/' character at the end). I believe it is because inside the snackbarjs source code, the container appends string `<div id=snackbar-container/>`, which should be `<div id="snackbar-container"></div>` so any browser won't get confused. 

Unfortunately, this does not happen when I open for example the demo http://fezvrasta.github.io/snackbarjs/ page. I do not know why it sometimes happens and sometimes does not. Would 100 % recommend to specify the appended container element to `<div id="snackbar-container"></div>`.

Sorry that I created this issue here, but SnackbarJS does not have the "Issues" tab.

**Comment by FezVrasta** [comment]
SnackbarJS is not maintained anymore, sorry ☹️
