### ISSUE TITLE
When combined with `.button('loading')` of bootstrap the loading state is not rendered correctly.

### ISSUE THREAD

**Issue by lipis** [mdbootstrap/mdb-ui-kit#142]
This is how it looks now:

![screen shot 2014-10-22 at 20 04 08](https://cloud.githubusercontent.com/assets/125676/4741411/fad8a5f4-5a15-11e4-9c2d-8a635887c52a.png)

But I would expect to see it like this:

![screen shot 2014-10-22 at 20 04 56](https://cloud.githubusercontent.com/assets/125676/4741416/002e30dc-5a16-11e4-86a4-aa1b31a229ae.png)

Not sure about the shadow.. :)

**Comment by FezVrasta** [comment]
may you provide a pen? you can use the MD playground 

http://codepen.io/FezVrasta/pen/ihmea

Thanks

**Comment by shak18** [comment]
He is talking about this bootstrap feature that for reason im not able to replicate in your playground

http://jsfiddle.net/YCst4/1/

**Comment by lipis** [comment]
Here you are: http://codepen.io/anon/pen/gJbzo

**Comment by FezVrasta** [comment]
fixed with fe27e7e

**Comment by lipis** [comment]
+1
