### ISSUE TITLE
Checkbox checked not working on Safari 14 and iOS 14

### ISSUE THREAD

**Issue by Elisa1202** [mdbootstrap/mdb-ui-kit#1421]
Hi,
on Safari 14 and also on iOS 14 when I select a checkbox the animation doesn't working well and it seems not be checked.

**Test Case**
https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/material-design/selections/#checkboxes

**Summary**
Checkbox does not work correctly.

**Expected result**
Checkbox has to be selected on click.

Thanks

**Comment by laucel** [comment]
@FezVrasta I'm having the same issue, any news about that?
thank for your support

**Comment by aeroxr1** [comment]
@FezVrasta any update ?

**Comment by Max75010** [comment]
Same problem here, any update ?

**Comment by Toommi** [comment]
Same here.

Issue seems to be, that the .checkbox label .checkbox-decorator .check::before is not rendering with 0 width and height. I put it on 1px and seems to work.

**Comment by Max75010** [comment]
Ok if I add : 
```


.checkbox .checkbox-material .check:before, label.checkbox-inline .checkbox-material .check:before {
	width: 1px !important;
	height: 1px !important;
}
```

it works.
