### ISSUE TITLE
bower install failing

### ISSUE THREAD

**Issue by pragathivasireddy** [mdbootstrap/mdb-ui-kit#1423]
#### Test Case
Bower install failing with error ENORESTARGET No version found that was able to satisfy 0.5.10

#### Summary
bower install failing from yesterday after the repository has been moved
Here is the error
bower bootstrap-material-design#0.5.10             ENORESTARGET No version found that was able to satisfy 0.5.10

#### Expected result
Successful installation

#### Additional Information

**Comment by FezVrasta** [comment]
Bower is dead, please move to a modern package manager
