### ISSUE TITLE
bower install bootstrap-material-design not working any more

### ISSUE THREAD

**Issue by motabass** [mdbootstrap/mdb-ui-kit#1424]
We use version 0.5.10 of this lib in an legacy client project where we can't update. Lately our build startet to fail when bower is trying to install 
`"bootstrap-material-design": "0.5.10"`

I get the following error:

`bower bootstrap-material-design#0.5.10     ENORESTARGET No tag found that was able to satisfy 0.5.10`

it seems like bower looks in the old repository where it can't find the 0.5.10 tag anymore.

I also tried install from the new repository but get another error:

`"bootstrap-material-design": "https://github.com/bootstrap-material-design/bootstrap-material-design.git#0.5.10"`

```
bower bootstrap-material-design#0.5.10          extract archive.tar.gz
bower bootstrap-material-design#0.5.10     invalid-meta for:/tmp/976ce187bf289c0680a14d01b62444da/bower/68c601ff276fe4551a8809b3805d1983-2446895-Dv2q8Z/bower.json
bower bootstrap-material-design#0.5.10     invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .css files: ["dist/css/bootstrap-material-design.css","dist/css/ripples.css"]
bower bootstrap-material-design#0.5.10     invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["dist/js/material.js","dist/js/ripples.js"]
bower bootstrap-material-design#v0.5.9           cached https://github.com/FezVrasta/bootstrap-material-design.git#0.5.9
bower bootstrap-material-design#v0.5.9         validate 0.5.9 against https://github.com/FezVrasta/bootstrap-material-design.git#v0.5.9
bower bootstrap-material-design#0.5.10         resolved https://github.com/bootstrap-material-design/bootstrap-material-design.git#0.5.10
bower bootstrap-material-design#v0.5.9     ENORESTARGET No tag found that was able to satisfy v0.5.9
```

also when searching for the package on bower.io it still shows the old repository:

![image](https://user-images.githubusercontent.com/4824274/94919999-bb209b00-04b5-11eb-9e1f-d79dc88531d4.png)

**Comment by FezVrasta** [comment]
It's been so long since I used Bower that I can't even find my credentials, and I can't find a password reset form...

**Comment by motabass** [comment]
I know i'm also not happy with using it;) But still it would be great if it could still find even the old version in the old repository. Where the tags removed from the old repo?

**Comment by motabass** [comment]
I really don't understand why you could not just leave the old release as is, so poor people installing your lib for years with bower can continue to do so. That's really bad

**Comment by motabass** [comment]
Thanks a lot! It seems to work again

**Comment by nowakjestem** [comment]
I'm stiil having this problem :(
Trying to install `0.3.0` version and it could not find any versions in an old repository 
```
bower bootstrap-material-design#~0.3.0               ENORESTARGET No tag found that was able to satisfy ~0.3.0

Additional error details:
No versions found in https://github.com/FezVrasta/bootstrap-material-design.git
```

@FezVrasta any chance on adding version tags to previous repo?
