### ISSUE TITLE
Publishing releases

### ISSUE THREAD

**Issue by aureq** [mdbootstrap/mdb-ui-kit#1425]
Hi,

Could it be possible to publish the project releases on github as well please?

For example, if I visit https://github.com/matomo-org/matomo/releases, I'm able to see and download assets for specific versions.
In addition, this allows project subscribers/watchers to be automatically get notified when a new release is available and (optionally) be informed of the recent changes.

I guess this could be somehow automated using github actions.

Thank you for considering this improvement.

**Comment by smolenski-mikolaj** [comment]
This is our standard procedure. When we finish migrating the repositories, the release list will be restored.

**Comment by filipkappa** [comment]
@aureq please check the repo now - the tags & npm install via tags should work properly

**Comment by aureq** [comment]
Hi @filipkappa 

Thanks for the update. I did check the repository but I'm not sure this is actually working as expected.

In short, I'm watching this repository for new releases. This way, I get an email when a new version is published. However, upon the publication of 3.0.0 I haven't received that notification email.

A possible explanation could be the release is actually missing other information (like a release description maybe). There's the official doc here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository

I'm assuming this is something that could be automated using some tools like https://github.com/remixz/publish-release

If this issue could be reopened, that would be great.

Thank you.

**Comment by aureq** [comment]
Hi @filipkappa 

Thank you. I think you changed something as I just received a received a notification email for version 3.0.0.
The release link and the latest version are also showing up on the repository main page as well which is awesome.

Thank you so much for looking into this.

Happy New Year to you and the MDB team.
