### ISSUE TITLE
Collapse object expading when declaring it in JS

### ISSUE THREAD

**Issue by Miguel-Dorta** [mdbootstrap/mdb-ui-kit#1426]
## Expected behaviour

Collapse object should not expand nor collapse when you declare it in the JS

## Displayed behaviour

Collapse object is expanded when declared in JS

## Tested in

OS: Windows
Browsers: Chrome and Firefox

## How to replicate it

1. Download the standard project from https://mdbootstrap.com/docs/standard/getting-started/installation/

2. Replace the context of the index.html for the following code:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
    <link rel="stylesheet" href="css/mdb.min.css" />
  </head>

  <body>
    <nav class="navbar navbar-expand-md">
      <div class="container-fluid">

        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Open menu">
          <i class="fas fa-bars"></i>
        </button>

        <div id="navbarSupportedContent" class="collapse navbar-collapse justify-content-end">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a id="item1" class="nav-link active" href="#!">Item 1</a>
            </li>
            <li class="nav-item">
              <a id="item2" class="nav-link" href="#!">Item 2</a>
            </li>
            <li class="nav-item">
              <a id="item3" class="nav-link" href="#!">Item 3</a>
            </li>
            <li class="nav-item">
              <a id="item4" class="nav-link" href="#!">Item 4</a>
            </li>
            <li class="nav-item">
              <a id="item5" class="nav-link" href="#!">Item 5</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <script src="js/mdb.min.js"></script>
    <script>
        const navCollapse = new mdb.Collapse(document.getElementById('navbarSupportedContent'));
    </script>
  </body>
</html>
```

3. Shrink the browser window until the md breakpoint

## What should I see?

The collapse object in the navbar expanding when the page loads with 766px width or less. You can shrink the window until it collapses and refresh the page to see it clearly.

**Comment by smolenski-mikolaj** [comment]
Collapse is an auto initiated component, which means that you do not need to run it manually with javascript. 
Here's an example code: https://mdbootstrap.com/snippets/standard/mikolaj-smolenski/2830517#html-tab-view

**Comment by Miguel-Dorta** [comment]
Sorry for opening this again. I will post the solution in case someone google it and arrives to this issue.

That thing I posted above is intended behaviour. It didn't work like that, which made me confuse.

What do I mean by "is intended behaviour"? If you go to the [Collapse API documentation](https://mdbootstrap.com/docs/standard/components/collapse/#docsTabsAPI), you'll see that there's a section called "Options" that mentions a "toggle" option with the default value in "true". This is what expands the collapse on its creation.

How to change it when you create the collapse from JS? In the documentation simply says "Options can be passed via data attributes or JavaScript", and I found out that this means that you can pass the options as a field of an object in the second parameter of its initialization, like so:

```javascript
new Collapse(document.getElementById('collapseID'), {
  toggle: false,
});
```

I think this should be better documented, but I have to admit that it's my fault for not reading it deeply.

Also, as a side note, if you're trying to do what I did, and initialize the Collapse object from JS, you can entirely omit the "data-mdb-toggle" and "data-mdb-target" from the HTML, since you're initializing them from the JS.

**Comment by smolenski-mikolaj** [comment]
Thanks for sharing Your solution. We fixed the documentation.
