### ISSUE TITLE
String.startsWith exception when integrate into SharePoint

### ISSUE THREAD

**Issue by sebasky** [mdbootstrap/mdb-ui-kit#1428]
I am trying to integrate MDB 5 into SharePoint but there is an exception relative startWith function implemented inside MDB 5. The problem occurs because a function with the same name is defined by SharePoint but with a different number of parameters.
I am aware that this is a problem relative to specific product, but migth be useful to have a solution for this case too...

Conflict code, with this error: 'Parameter count mismatch.':

String.prototype.startsWith = function String$startsWith(prefix) {
    /// <summary locid="M:J#String.startsWith" />
    /// <param name="prefix" type="String"></param>
    /// <returns type="Boolean"></returns>
    var e = Function._validateParams(arguments, [
        {name: "prefix", type: String}
    ]);
    if (e) throw e;
    return (this.substr(0, prefix.length) === prefix);
}

**Comment by smolenski-mikolaj** [comment]
Thank you for reporting, but unfortunately we cannot take responsibility for conflicts with other tools.
