### ISSUE TITLE
ASP core 5 intergration

### ISSUE THREAD

**Issue by weedkiller** [mdbootstrap/mdb-ui-kit#1430]
Hello do you have ASP Core 5 bundle with Tag-Helpers & Identity. We are looking for MDB in ASP Core with the tag helpers/View COmponent the BS 5 version how long would it be supported 

WIll you have a demo and pro version how much would it be

**Comment by smolenski-mikolaj** [comment]
We have the **Admin Dashboard + .NET Core + ASP.NET Core** with integrated Authentication. Please check out the documentation: https://mdbootstrap.com/docs/standard/integrations/admin-dashboard-net-aspnet/.

Backend integrations are part of the MDB5 Advanced license.

**Comment by weedkiller** [comment]
Ok that will give me a chance to test it, but its the old core 3.1, can you please update target to ASP Core 5 / 6.
