### ISSUE TITLE
Can't use your FAQ contact form

### ISSUE THREAD

**Issue by PubliAlex** [mdbootstrap/mdb-ui-kit#1431]
Hello, 

I have a question about your services, but when I try to send a message using your contact form on the right side of your FAQ, I get the following error :

![image](https://user-images.githubusercontent.com/55833027/108830483-b75af580-75c9-11eb-81b8-670bef4d1ec9.png)

Best regards,

**Comment by ezechiaskumbu77** [comment]
Hello,  i a m a web developper, presentley i'm about to learn about Mobile development.
so i can buil for you an entire web app witha actual technology and more.
Hope that i answered to you question

**Comment by bwsky-a** [comment]
Hello, 

The problem should no longer occur, but if you still have any problems with accessing the site, contact us at contact@mdbootstrap.com

Best regards, 
Adam From MDB
