### ISSUE TITLE
Ripple not fully implemented

### ISSUE THREAD

**Issue by jasonabullard** [mdbootstrap/mdb-ui-kit#1433]
Reviewing the examples provided on [https://mdbootstrap.com/docs/standard/forms/checkbox/](MDB Bootstrap), the ripples do not fully complete.  Currently using Chrome 89 and when I click on an unchecked checkbox, the ripple starts and creates the full circle but then stops.  It never fades out.  This happens whether it is checked or unchecked.

Also, in Safari, 14.0.3, the ripple effect doesn't work.

Seems to be isolated to Checkboxes as normal buttons work just fine.

**Comment by smolenski-mikolaj** [comment]
The effect your writing about is not a ripple. It's just a focus circle of a selected element. It's part of the checkbox accessibility utilities.
