### ISSUE TITLE
Where are the releases?

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [mdbootstrap/mdb-ui-kit#1434]
Hi there,

the repo release cycle seems broken as this repo does not have a [release](https://github.com/mdbootstrap/mdb-ui-kit/releases) for 3.2.0, 3.3.0 and 3.4.0. There are [tags](https://github.com/mdbootstrap/mdb-ui-kit/tags) for these versions but GitHub does not send notification e-mails for newly created tags.

I think a related issue is #1425 which is already closed indicating that the repo should have a release for each version in the [changelog](https://mdbootstrap.com/docs/standard/getting-started/changelog/). 

Can you look into it?

It would be nice to have proper releases as I also rely on GitHub e-mails to get informed about new releases. 

So lonG

Daniel

**Comment by smolenski-mikolaj** [comment]
Thanks for posting the issue. We've just published missing releases.
