### ISSUE TITLE
MDB event listeners not working

### ISSUE THREAD

**Issue by AgentSmith0** [mdbootstrap/mdb-ui-kit#1435]
The following code is not working:
```
const myModalEl = document.getElementById('myModal')
myModalEl.addEventListener('hidden.mdb.modal', (event) => {
  // do something...
})
```

But this works:
```
const myModalEl = document.getElementById('myModal')
myModalEl.addEventListener('hidden.bs.modal', (event) => {
  // do something...
})
```

And the css variables are named --bs-primary and not --mdb-primary.

**Comment by smolenski-mikolaj** [comment]
@AgentSmith0 I just checked the issue with event listeners in console and both examples work fine. 
![image](https://user-images.githubusercontent.com/31181850/113824947-aaacee00-9780-11eb-9fe7-da6aaf7e7b5b.png)

Can you prepare a snippet showing the issue? https://mdbootstrap.com/snippets/

**Comment by AgentSmith0** [comment]
Oh, sorry, it looks like I've made a mistake, both examples are working.

Thank you very much.
