### ISSUE TITLE
Bootstraps default select borders are wrong styled

### ISSUE THREAD

**Issue by AgentSmith0** [mdbootstrap/mdb-ui-kit#1436]
The mdbootstrap theme is not applied to the default form-select class of bootstraps select (see screenshot below):

![Screenshot_Select](https://user-images.githubusercontent.com/67276662/114276766-680d3f00-9a28-11eb-977d-fee1a23bd294.png)

**Comment by Martussky** [comment]
Hi, our select is integrated into the essential pro pack.

Keep coding,
Marta

**Comment by AgentSmith0** [comment]
Yes, I know that feature, but it is not the same as the default form-select. Isn't it possible for the free users to use a mdb styled default select?

**Comment by Martussky** [comment]
Hi,

yes, it's possible to add the mdb styles to the form-select for free users. We have this case in our roadmap.

Keep coding,
Marta

**Comment by AgentSmith0** [comment]
Thank you very much for the excellent service.
