### ISSUE TITLE
Color Picker onChange event and colorPickerDisabledAlpha option not working

### ISSUE THREAD

**Issue by AgentSmith0** [mdbootstrap/mdb-ui-kit#1438]
Here is my code:

HTML:
`<div id="colorpicker1" class="color-picker"></div>`

JS:
```
const picker = document.getElementById('colorpicker1');
const pickerInstance = new ColorPicker(picker, { colorPickerDropdown: true, colorPickerDisabledAlpha: true });

picker.addEventListener('onChange.mdb.colorPicker', () => {
		console.log('on change');
});

picker.addEventListener('onOpen.mdb.colorPicker', () => {
		console.log('on open');
});
```

The onChange event does not work, but onOpen works. And the color picker still shows the alpha option.

**Comment by michal-duszak** [comment]
We are currently working on a fix. By the time you can use workarounds:

**Disable Alpha:**
JS:
```
const pickerAlpha = picker.querySelector('#alphaRange');
pickerAlpha.setAttribute('disabled', 'disabled');
```
https://mdbootstrap.com/snippets/standard/m-duszak/3015669#js-tab-view

**Hide Alpha:**
CSS: 
```
#colorpicker1 .color-picker-range-alpha {
  display: none;
}
```
https://mdbootstrap.com/snippets/standard/m-duszak/3015749#css-tab-view

**Fire onChange:**
You can listen to canvas
JS: 
```
pickerCanvas.addEventListener('mouseup', () => {
	const actualColor = pickerDot.style.backgroundColor;	
  console.log('on change');
  console.log(actualColor);
});
```
You can also listen to alpha range input
JS:
```
pickerAlpha.addEventListener('change', () => {
	const actualColor = pickerDot.style.backgroundColor;	
  console.log('on change');
  console.log(actualColor);
});
```
And hue range input
JS:
```
pickerHue.addEventListener('change', () => {
	const actualColor = pickerDot.style.backgroundColor;	
  console.log('on change');
  console.log(actualColor);
});
```
https://mdbootstrap.com/snippets/standard/m-duszak/3015819#js-tab-view

**Comment by AgentSmith0** [comment]
Thank you, I will wait for the new update. Please also add the new version to the mdb snippets page when it comes out.

**Comment by smolenski-mikolaj** [comment]
We've just released a new version with a fix.
