### ISSUE TITLE
label effect

### ISSUE THREAD

**Issue by MaxyBlack** [mdbootstrap/mdb-ui-kit#144]
Can you add this label effect

http://scotch.io/tutorials/css/google-material-design-input-boxes-in-css3

that's what is missing in your material style.

**Comment by FezVrasta** [comment]
It's already implemented... it's a floating label. Check out the demo

**Comment by MaxyBlack** [comment]
I saw demo, but without label effect.

**Comment by MaxyBlack** [comment]
Oh, now i see. 
That foating only if you write something
