### ISSUE TITLE
mdbootstrap tabs error Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by fredericpetitdev** [mdbootstrap/mdb-ui-kit#1444]
Hello, when i want to use mdbootstrap tabs here https://mdbootstrap.com/docs/standard/navigation/tabs/#section-buttons , i have in the console.log

`input.js:341 Uncaught TypeError: Cannot read property 'split' of undefined`

Error is present into mdbootstrap website himself.

**Comment by smolenski-mikolaj** [comment]
Thanks for your remarks. We're going to make an update for this soon.

Keep coding, 
Mikołaj from MDB
