### ISSUE TITLE
Can I build form dinamically using OpenAPI schema?

### ISSUE THREAD

**Issue by KES777** [mdbootstrap/mdb-ui-kit#1446]
Hi.

Does your kit support to build form dynamically by providing link to OpenAPI schema?

Or probably by supplying a hash with options like this: 
https://www.jqueryscript.net/form/form-builder-bootstrap-formy.html
or this https://www.jqueryscript.net/form/clever-form-generator.html
or this https://www.jqueryscript.net/form/Form-JSON-Schema.html

**Comment by smolenski-mikolaj** [comment]
Unfortunately, we do not support dynamic form creation.

Keep coding, 
Mikołaj from MDB
