### ISSUE TITLE
MDBSideNavLink :to property wrong type

### ISSUE THREAD

**Issue by aronsuarez** [mdbootstrap/mdb-ui-kit#1448]
The property 'to' of the MDBSideNavLink component has the type String, but router link will support also en object, the property needs to have a two types.

runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Invalid prop: type check failed for prop "to". Expected String with value "[object Object]", got Object 

This is only a warning, the code will work.

**Comment by smolenski-mikolaj** [comment]
I'm closing because the thread concerns a different repository.
