### ISSUE TITLE
Btn-flat doesn't work with btn-material

### ISSUE THREAD

**Issue by wopian** [mdbootstrap/mdb-ui-kit#145]
When using `btn-material`, adding `btn-flat` does not work as intended. Instead of the text becoming the material colour the text becomes the default white.

Example: (left: `btn-flat btn-material-deeporange`, right: `btn-flat btn-success`)
![](http://i.imgur.com/N9n1rUR.png)

**Comment by FezVrasta** [comment]
Have you tried adding the btn class as first one?

**Comment by wopian** [comment]
I didn't include `btn` as it's the basic bootstrap css for a button.

`<a class="btn btn-material-red btn-flat">` is the full snippet.
