### ISSUE TITLE
MDBModalDialog container should be placed in same container as modal's backdrop

### ISSUE THREAD

**Issue by swayok** [mdbootstrap/mdb-ui-kit#1450]
Currently MDBModalDialog placed inside container where component used while backdrop placed in <body>
This sometimes causes modal content be shown behind backdrop and be inaccessible. 

Backdrop and modal contents should be placed inside same container to avoid this. Bootstrap places everything in <body> (at least in v3 and v4). I think MDB should work the same way to avoid described issue. 
Or at least place backdrop alongside modal contents.

Note: z-indexes are correct but in some case the does not work as intended. I failed to find out the reason why some of the modals bugged while others are ok. Maybe it is related to situation when modal placed inside 'scrollable' container.

**Comment by smolenski-mikolaj** [comment]
Please post this issue on our [support channel](https://mdbootstrap.com/support/) to be guaranteed a reply.

keep coding,
Mikołaj from MDB

**Comment by swayok** [comment]
Tried to post issue to support channel but it went offline with 502 error =(
I'l repost it to `mdbootstrap/mdb-react-ui-kit` repo where I actually intended to post it.
