### ISSUE TITLE
MDBCarousel behavior is weird + bug in documentation

### ISSUE THREAD

**Issue by swayok** [mdbootstrap/mdb-ui-kit#1451]
1. Carousel with 1 slide magically slides to 2nd non-existing slide and then never slides again showing black screen
2. Carousel should have an option to disable autosliding at all - there are lots of stuations when autosliding is not needed (for example simple image gallery for shop item)
3. Carosuel prev and next buttons should not use font awesome - not everyone uses font awesome and in result icons are not shown. And you can just use borders to imitate these icons
4. In documentation `interval` is placed on `<MDBCarousel showControls interval={10000}>` while in reality `interval` prop should be placed on each `<MDBCarouselItem interval={10000}>`. 
5. `MDBCarouselItem` should use `MDBCarousel`'s `interval` unless it has its own `interval`. 

Example SCSS for prev and next buttons:
```
$carousel-controls-size: 20px;
.carousel-control-next-icon,
.carousel-control-prev-icon {
    position: relative;
    display: block;
    width: $carousel-controls-size * 1.42;
    height: $carousel-controls-size * 1.42;

    &:after {
        position: absolute;
        top: -2px;
        display: block;
        content: '';
        width: $carousel-controls-size;
        height: $carousel-controls-size;
        border-top: 3px solid #FFF;
    }
}

.carousel-control-next-icon {
    &:after {
        right: $carousel-controls-size * 0.4;
        border-right: 3px solid #FFF;
        transform: rotate(45deg);
        transform-origin: left center;
    }
}

.carousel-control-prev-icon {
    &:after {
        left: $carousel-controls-size * 0.4;
        border-left: 3px solid #FFF;
        transform: rotate(-45deg);
        transform-origin: right center;
    }
}
```

**Comment by smolenski-mikolaj** [comment]
1. There is no logical explanation for a carousel with one item.
2. To disable autoslide just set `data-mdb-interval` to `false`
3. Font Awesome was integrated with many MDB components and for this moment is required.
4. There are two variants for interval. If placed on `<MDBCarousel>` sets the global value. If placed on `<MDBCarouselItem>` sets individual interval value for each item.
5. It's exactly how it works.

Please post your other issues on our [ support channel ](https://mdbootstrap.com/support/) to be guaranteed a reply.

keep coding,
Mikołaj from MDB

**Comment by swayok** [comment]
It seems I misplaced the issue. It should be in react's repo. Also support channel currently offline with 502 error.
I'l explain a bit more;
1. Imagine that you provide an admin panel for your client to manage slides and he places there as many slides as he want. You can't say your client to place at least 2 slides, don't you? Some will just fire you and hire "better" developer. Also it is a waste of time to write code for this specific stuation so supporting 1 slide is prefered. Also in react version it works very unexpectedly with 1 slide.
2. There are no such option in react components =(. I ended up setting interval to 24 hours.
4. In react components there are `interval` prop only for item, not for container. I've reviewed code - no `interval` prop or its usage there.
