### ISSUE TITLE
Material Input & All colors

### ISSUE THREAD

**Issue by devtrix** [mdbootstrap/mdb-ui-kit#1463]
Is there a way to get the form (Material Input) & colors back like your v4?  I know enough SASS to be dangerous.  I do have both v4 & v5 pro. 
I want to be able to sell your packages.  Currently I just make my clients purchase it from you directly, but I am glad I checked mine out.  I wasnt expecting this changes as they seem to break while I tried to upgrade from v4 on my own personal project.
Please advise.

**Comment by dwaju** [comment]
Hi,

What do you mean by "get the form (Material Input) & colors back like your v4"? This https://mdbootstrap.com/docs/b4/jquery/forms/inputs/ material input with only bottom border? 

MDB5 has been rewritten from scratch and is not compatible with MDB4. Changing design on your own to match previous one probably won't solve your compatibility issues. But as I'm not fully aware of what your are trying to accomplish, I might be wrong. Please provide more information.

And what do you mean by "I want to be able to sell your packages"?

Keep coding,
Dawid

**Comment by devtrix** [comment]
> What do you mean by "get the form (Material Input) & colors back like your v4"? This https://mdbootstrap.com/docs/b4/jquery/forms/inputs/ material input with only bottom border?
**Me:  Yes.  The inputs with bottom border & the colors ex: pink lighten-5**

> _MDB5 has been rewritten from scratch and is not compatible with MDB4. Changing design on your own to match previous one probably won't solve your compatibility issues._ 
**Me:  Yes, I am fully aware of the rewrite and the incompatibility and that is exactly why I asked your help.**

> _But as I'm not fully aware of what your are trying to accomplish, I might be wrong. Please provide more information._
**Me: I am trying to style the inputs like v4 with a bottom border.  Whether that portion of styling could be exported from your v4 was part of my question.  As to why I need this is explained below in the next question.**

> _And what do you mean by "I want to be able to sell your packages"?_
**Me: I have a software development company based out of Florida, USA and an upcoming Collaborative development, Code Gen & Project manager website called Appiphany.ai.  Its a AI driven simple Q&A for multiple platforms addressing  various market verticals.  During the UI design part of the questions, I demo available CSS packages like Bootstrap 5, Foundation, Materialize css, MDBootstrap etc.  There will be samples as they choose. If they decide  to select your Pro version, we redirect them to your site.  They do the purchase and then, once verified, our site allows them to use your pro CSS.  I really like your versatility as it allows those of less experience to do their own.  I wanted them to see both the styles, outline & material input.  So to answer your question, I am trying to be a reseller.  I wasnt ready to approach you guys yet, but due to this issue we are discussing this now.**

I understand that it was a total re-write, believe me in my 40+ years as a programmer I have seen my share.  But in situations like these, we always provide previously available options where possible.  Especially the UI stuff as that is customer facing. I hope I this was clear and hope to resolve this positively.

Code mindfuly,
Cheers!
Raj

**Comment by dwaju** [comment]
Hi,

You can change CSS on your own and compile your own version of MDB UI KIT - here is the instruction https://mdbootstrap.com/docs/standard/getting-started/webpack-starter/#section-custom-version-of-mdb-ui-kit, But I would suggest just adding your custom CSS, to your CSS file, which will overwrite our default CSS. Here are the snippets showing possible solutions: default one -  https://mdbootstrap.com/snippets/standard/d-wajszczuk/3247671#css-tab-view and one with color (you can make it in whichever color you want) - https://mdbootstrap.com/snippets/standard/d-wajszczuk/3247690#css-tab-view.

For any information related to buying, selling etc. our packages, please contact us on contact@mdbootstrap.com. We will try to give you all wanted details.

Keep coding,
Dawid

**Comment by devtrix** [comment]
Since its this simple for you guys, why not create Form components called form-material or something like that and add it to the package?  SMH.  I do appreciate your guidance, I was trying to save my time hoping this could be done by you guys.  Nevertheless,  I will add these to my backlogs.  I just hope your future featuresets are not subtractive but additive.  Thats what we call mindful coding.  Have a great day, stay safe.
Cheers!
Code mindfully,
Raj

**Comment by dwaju** [comment]
Hi,

You can try this two solutions: 1. in source directory find js folder and then input.js. Then make new constants for your "form-material" and duplicate every peace of code which contains "form-outline" (places where you have `CLASSNAME_WRAPPER,` `SELECTOR_OUTLINE_INPUT`,  `SELECTOR_OUTLINE_TEXTAREA`) and put there your variables.
Or 2. duplicate input.js, rename it, change `const CLASSNAME_WRAPPER = 'form-outline'` to `const CLASSNAME_WRAPPER = 'form-material'`. Import your new component to mdb.free.js or mdb.pro.js.
Don't forget to also make new CSS for your `form-material`. And finally, compile newly created package.

Keep coding,
Dawid

**Comment by devtrix** [comment]
You are awesome! I am going to attempt that.  I'll close this. 
 
 Dziękuję bardzo!
 Code mindfully,
 Raj

**Comment by devtrix** [comment]
I am so sorry, I went the variable route. Where can I dind any doc for compiling? I know I closed it and didnt want to open an issue.
