### ISSUE TITLE
Can't use mdb-ui-kit modules

### ISSUE THREAD

**Issue by pommepommee** [mdbootstrap/mdb-ui-kit#1465]
npm version: 6.14.13
nodejs version: 14.17.3
mdb-ui-kit version: 3.9.0

Hi there,

I installed mdb-ui-kit as written [here](https://mdbootstrap.com/docs/standard/getting-started/installation/) with NPM terminal command `npm i mdb-ui-kit` and I managed to use the package's CSS. But when I try to import a mdb module like so :

```TS
import { Input } from 'mdb-ui-kit'; 
```
I have this error : 
```
Could not find a declaration file for module 'mdb-ui-kit'. 'c:/Users/my/project/path/node_modules/mdb-ui-kit/js/mdb.min.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mdb-ui-kit` if it exists or add a new declaration (.d.ts) file containing `declare module 'mdb-ui-kit';`ts(7016)
```

I tried the `npm i --save-dev @types/mdb-ui-kit` command, no success and I don't think that the second command will work.

In my node_modules folder, I see mdb-ui-kit but this is its tree: 
```
mdb-ui-kit
   | css
   | img
   | js
   | src

```

Is there a solution ? 
Thanks

**Comment by gbujanski** [comment]
I need more information to reproduce this problem. How is your project structured? Are you using any framework? Can you provide a minimal repository for this issue?

**Comment by pommepommee** [comment]
Hi @gbujanski 
Here is my tree folder
![](https://i.ibb.co/Q9dxsDB/gitissue.png)

I'm only using Angular and MDBootstrap (via npm i mdb-ui-kit)

**Comment by gbujanski** [comment]
Unfortunately, MDB Standard was not designed to be used with frameworks. For Angular we have a dedicated MDB version: https://github.com/mdbootstrap/mdb-angular-ui-kit

**Comment by pommepommee** [comment]
Thanks for the answer
