### ISSUE TITLE
Border colors doesn't work properly

### ISSUE THREAD

**Issue by Szczurowsky** [mdbootstrap/mdb-ui-kit#1466]
### Issue
When adding `border-warning` (or any other color) border of card doesn't have set color. (dark version)
### Photo
![image](https://user-images.githubusercontent.com/70973416/133298961-dc877673-e19b-4685-9090-86f75f6d5933.png)
### Code to reproduce
```
<div class="card bg-dark rounded-6 border border-4 border-warning">
    <div class="card-title pt-4">
        <h2 class="font-weight-bold">Example</h2>
    </div>
</div>
```

**Comment by gbujanski** [comment]
I checked it and everything works fine: https://mdbootstrap.com/snippets/standard/grzegorz-bujanski/3314612 
Can you create your snippet with this error?

**Comment by Szczurowsky** [comment]
Actually an issue happened when using mdb.dark.css not light one (default).
I will try to reproduce an error on codepen using dark version of MDB.

**Comment by Szczurowsky** [comment]
Reproduced bug on latest version of MDB:. https://jsfiddle.net/v2du7pbw

**Comment by gbujanski** [comment]
Thanks for reporting. We will check it, test your solution and fix it

**Comment by Szczurowsky** [comment]
I wasn't able to find the issue in scss, but i found it in generated dark css file. After deleting that all is fine. `.border,.border-bottom,.border-left,.border-right,.border-top{border-color:hsla(0,0%,100%,.12)!important} `
