### ISSUE TITLE
Buttons enforce min-width when interacted with them, and don't remove it

### ISSUE THREAD

**Issue by Miguel-Dorta** [mdbootstrap/mdb-ui-kit#1468]
### What I expected:
Buttons to resize responsively always

### What happens:
When you interact with a button in any way, it sets its own style with "min-width: <current_width>". This prevents the button to resize down when resizing the window / rotating the device.

### Which version was introduced it?
Version 3.8.0, in [this commit](https://github.com/mdbootstrap/mdb-ui-kit/commit/d80a54c79aef6e51abcd1f4908bb5c720676e5e7#diff-4041c2e633959ac0bdfe3c1dc33d4b63bfba3d80871615abcbd6d354b22067db) with no explanation of why.

### What I suppose it happens:
That property was defined to avoid some animation re-scale, and it was not set to remove itself after the animation. I could be wrong, this is pure speculation.

### How to recreate it?
1. Create a stretched button. For example, the "Sign in" button in the [official login page demo](https://mdbootstrap.com/freebies/login-page/).
2. Interact with it (not only clicking it, but also right-click and click-and-drag on it).
3. Resize the window. You'll see that it expands beyond the parent div because now it has a "min-width" property defined.

#### Before interacting with it
![Screenshot of the botton acting regularly](https://i.imgur.com/nHbrzWG.png)
#### After interacting with it, and resizing the window
![Screenshot that shows the button extending beyond its parent component, and with a min-width defined in the devtools](https://i.imgur.com/GyLC0iv.png)

UPDATE: I found out the version and commit. I updated it above. It has no comment of why it was introduced.

**Comment by gbujanski** [comment]
You're right. This was introduced due to the animation that appears when clicked. We already have a task on our to-do list to fix this.

**Comment by dk-raw** [comment]
I am having the exact same issue with version 3.10.1. Any updates on the fix?

**Comment by gbujanski** [comment]
@dk-raw  Are you sure you are using version 3.10.1, not earlier? This has been fixed in 3.10.1. 
I following the steps in the list of How to recreate it and everything will work fine
