### ISSUE TITLE
Material.js hidden checkbox

### ISSUE THREAD

**Issue by Eonasdan** [mdbootstrap/mdb-ui-kit#147]
Razor view pages in ASP.Net MVC applications use a hidden checkbox to allow checkbox values to be posted (as false) in the event that the user didn't check the box.

With the current material.js setup this cause a duplicate fake checkbox to be created. To fix this issue [Line 15](https://github.com/FezVrasta/bootstrap-material-design/blob/master/scripts/material.js#L15) and [Line 18](https://github.com/FezVrasta/bootstrap-material-design/blob/master/scripts/material.js#L18)  should be changed as follows

[See my codepen fork](http://codepen.io/anon/pen/vgGiK)

```
// Add fake-checkbox to material checkboxes
$(".checkbox > label > input").not(":hidden, .bs-material").addClass("bs-material").after("<span class=check></span>");

// Add fake-radio to material radios
$(".radio > label > input").not(":hidden, .bs-material").addClass("bs-material").after("<span class=circle></span><span class=check></span>");
```

**Comment by FezVrasta** [comment]
I can't do what you've written because the checkboxes are already hidden when the page loads (by css) and mostly because your case is quite specific.

**Comment by Eonasdan** [comment]
What I've written works just fine and doesn't affect people who aren't using it that way.

Also, this isn't going to be a fringe case, anybody who uses .net MVC or the hidden checkbox method will have this problem.

Suite yourself

**Comment by FezVrasta** [comment]
I'll not express my opinion about .net :)

About your problem, I've completely re-structured material.js, may you try it and let me know if the problem still exists?
