### ISSUE TITLE
Mdb.min.css overwrites .navbar-light .navbar-toggler-icon

### ISSUE THREAD

**Issue by 99Arrzel** [mdbootstrap/mdb-ui-kit#1477]
![image](https://user-images.githubusercontent.com/64380067/150167600-dfd4e05b-a864-4f43-8a69-9a76f96246da.png)

As the title says, it overwrites default navbar from Bootstrap 5.
A quickfix is just remove that line from mdb.min.css

**Comment by smolenski-mikolaj** [comment]
We use FontAwesome icon for navbar toggler that's why it's overwritten.
