### ISSUE TITLE
Hamburger animation doc not available for angular in mdb bootstrap 4

### ISSUE THREAD

**Issue by tushar33** [mdbootstrap/mdb-ui-kit#1481]
Using "\<mdb-navbar\>\</mdb-navbar\>" for navigation but didn't found angular document to do open close animation for hamburger menu.

I need to apply below animations
https://mdbootstrap.com/snippets/jquery/mdbootstrap/911054

**Comment by smolenski-mikolaj** [comment]
Please open an issue in the angular repository.

**Comment by tushar33** [comment]
Done
