### ISSUE TITLE
Material Design 3

### ISSUE THREAD

**Issue by unsalkorkmaz** [mdbootstrap/mdb-ui-kit#1486]
Hi,
Is there a roadmap for Material Design 3?

https://m3.material.io/

**Comment by holema** [comment]
Hello team,

I´m  very interested in this question too, if there is any roadmap to material design 3,

**Comment by MrinmoyHaloi** [comment]
They never respond to anything. They just care about the premium users

**Comment by ascensus-mdb** [comment]
Hi. Sorry for such a late response. In our daily work, we use our own forum to communicate with the users. I strongly recommend using it if you need a quick answer:

https://mdbootstrap.com/support/

Regarding Material Design 3 - we have a broader plan to provide different design systems as options in our theming. 

That means, we want you can easily change what design system you want to use in your MDB project. We are considering supporting the following options:
1. Material Design 2
2. Material Design 3
3. [Material Minimal ](https://mdbootstrap.com/docs/standard/getting-started/material-minimal/)
4. Default Bootstrap styling
5. Unstyled components

However, this is a really huge task and it requires a lot of changes in Bootstrap itself. Right now Bootstrap team work hard on improving their theming options. We are looking forward to these changes and as soon as they are released we will start to work on the implementations I have described above.

**Comment by MrinmoyHaloi** [comment]
Ok thanks for the response
