### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by omararturo** [mdbootstrap/mdb-ui-kit#1487]
The autocomplete function conflicts with other libraries such as jquery UI, Kendo UI for example calls this function, kendoautocomplete to avoid these conflicts. You could ask me, why not use MDBootstrap's autocompletion, well, because if we try to add autocompletion to an input that is different from the format `<div class="form-outline">` it gives an error:
  

```
jquery.min.js:2 Uncaught TypeError: Cannot read properties of null (reading 'offsetWidth')
at E0._initDropdown (index.js:149:26)
     at E0._init (index.js:135:10)
     at new E0 (index.js:93:10)
```

 
The initDropdown function fails, because the input does not have the necessary elements. I think that changing the name of the autocomplete function solves the problem

**Comment by gbujanski** [comment]
Thanks for reporting. We will discuss in the team the possibility of introducing changes to prevent such conflicts in the future.
