### ISSUE TITLE
Color of Input Field

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#149]
I think that the colors of the input fields (as well as the flash inside the field) should be much lighter. Maybe around 500 or 400 on the color pallette (http://www.google.com/design/spec/style/color.html#color-ui-color-palette).

Thanks.

**Comment by FezVrasta** [comment]
I have used the one used in the polymer paper project, is it changed recently? if you want to change it you could just override it.

**Comment by ghost** [comment]
@FezVrasta I dont think it has changed, but in my opinion its too dark.

Anyways, ill just change it myself.

Thanks.

**Comment by FezVrasta** [comment]
I understand that some part of this project can look not nice to everyone, but my goal is to provide just the standard template of material design. People are invited to override the style to make their interface unique.

**Comment by ghost** [comment]
Ok, thanks.

**Comment by ghost** [comment]
Ok, thanks.
