### ISSUE TITLE
Input-group misalignment

### ISSUE THREAD

**Issue by dk-raw** [mdbootstrap/mdb-ui-kit#1490]
The input is actually shorter in height than the button and the input-group-text
OS: Windows 11
Browser: Firefox 100+ (also tested on Edge and it's still broken)
![image](https://user-images.githubusercontent.com/68110106/170660481-420653f1-1fcf-440f-a01d-6199debc3a76.png)

**Comment by gbujanski** [comment]
Fixed in 4.1.0
