### ISSUE TITLE
Datepicker - click Feb directs to March

### ISSUE THREAD

**Issue by Sarah-Hao** [mdbootstrap/mdb-ui-kit#1491]
Issue exists on the [demo page](https://mdbootstrap.com/docs/standard/forms/datepicker/) too.

![GACEUQu8ZAp1ryh-gxD-TRCiqYM29hD3NU1r89HP6dw](https://user-images.githubusercontent.com/81778996/170899041-7a7b4106-8e32-4976-b0a2-139dfdbbb6a6.png)
![StV_VJtIiV6HpNwiySgsSb57HKlyqhVB_NqJXm3QYeA](https://user-images.githubusercontent.com/81778996/170899047-5c2e026c-93bd-4d31-a29e-80138294fd6c.png)

**Comment by simonanewton** [comment]
Just tested this bug, but I wasn't able to reproduce it. I tried switching to every month, especially on February, but no errors. Is this issue still reproduceable on your device?

**Comment by Sarah-Hao** [comment]
@simonanewton  thanks for replying, look like it's been fixed.
