### ISSUE TITLE
Rename `color-adjust` to `print-color-adjust` to fix Autoprefixer deprecation warning

### ISSUE THREAD

**Issue by Vheissu** [mdbootstrap/mdb-ui-kit#1496]
The W3 spec has deprecated the `color-adjust` property, but in its place added `print-color-adjust` which accepts the same values. As a result, in version of Autoprefixer 10.4.6 onwards, using MDB UI Kit will result in a deprecation warning and break builds with the warning. The fix is simple and I have done so in a pull request [here](https://github.com/mdbootstrap/mdb-ui-kit/pull/1495).

**Comment by gbujanski** [comment]
Thanks for reporting. We'll check it.
