### ISSUE TITLE
MDB video slider issue

### ISSUE THREAD

**Issue by Surinder05** [mdbootstrap/mdb-ui-kit#1497]
Hi , I'm using MDB video slider .

Video slide start its self again on slide show . 

Is there any solutions for it ?? 

Thanks

**Comment by Surinder05** [comment]
https://curryanddosapalace.com.au/video/

**Comment by gbujanski** [comment]
I understand you mean this example: https://mdbootstrap.com/docs/standard/extended/video-carousel/#section-basic-example

note that the `autoplay` attribute is added to the video. It is enough to remove it so that the video does not start automatically.
