### ISSUE TITLE
Multiselect Dropdown on Screenreaders

### ISSUE THREAD

**Issue by bbertucc** [mdbootstrap/mdb-ui-kit#1498]
Adding a `multiselect` drown down injects new code above the original multiselect. This makes it hard for my screenreader users to use (they essentially see two forms). 

You probably can just resolve this by adding `aria-hidden` to the HTML that's injectected. That said, `aria-hidden`  would exclude screen reader users from the search functionality of your awesome `multiselect`.

**Comment by gbujanski** [comment]
Thanks for reporting. We will check it and fix it.
