### ISSUE TITLE
v.5 ignores $secondary value for some styles

### ISSUE THREAD

**Issue by mwittmann** [mdbootstrap/mdb-ui-kit#1499]
In your latest release (or a recent release), the `src/scss/free/_variables.scss` does not respect the `$secondary` theme color for various UI elements. 

While `primary`, `success` and other theme colors use their respective color variables, `secondary` has some hard-coded values. For example, the `_variables.scss` file contains:
```scss
// scss-docs-start ripple-colors-map
$ripple: (
  'primary': $primary,
  'secondary': #e3ebf7,
  'success': $success,
  'danger': $danger,
  'warning': $warning,
  'info': $info,
  'light': $light,
  'dark': $dark,
) !default;
// scss-docs-end ripple-colors-map
...
$buttons: map-merge(
  (
    'primary': (
      'background-color': $primary,
      'text-color': $white,
      'shadow-color': $primary,
    ),
    'secondary': (
      'background-color': #e3ebf7,
      'text-color': #285192,
      'shadow-color': #e3ebf7,
    ),
    'success': (
      'background-color': $success,
      'text-color': $white,
      'shadow-color': $success,
    ),
    ...
  ),
  $buttons
);
...
$buttons-outline: map-merge(
  (
    'primary': (
      'text-color': $primary,
      'border-color': $primary,
      'background-color': $primary,
    ),
    'secondary': (
      'text-color': #285192,
      'border-color': #e3ebf7,
      'background-color': #e3ebf7,
    ),
    'success': (
      'text-color': $success,
      'border-color': $success,
      'background-color': $success,
    ),
   ...
  ),
  $buttons-outline
);
````

Because I am working with a theme with a high contrast `$secondary: #f14e54` color, I had to override `$buttons`, `$buttons-outline`, and additional variables such as `$btn-secondary-hover-focus-bgc` and `$btn-secondary-active-bgc` to get the secondary UI elements to fit my theme.

It would be best for all of the secondary UI element colors to be derived from `$secondary`, in the same way that `$primary`, `$success` and others are. Or alternatively, you might document why some of the secondary UI elements are **not** derived from `$secondary`, and provide some guidance about why and what might need to be changed.

It would also be great if future releases included release notes that could warn about potential upgrade compatibility issues.

**Comment by gbujanski** [comment]
Thanks for reporting. Perhaps, as you may have noticed, we have made a lot of changes to the variables due to the bootstrap changes. Bootstrap plans to add more changes, which will also cause an update on our side.
