### ISSUE TITLE
Problems with upgrade

### ISSUE THREAD

**Issue by mendykrauss** [mdbootstrap/mdb-ui-kit#1502]
Shows me an empty page.

On the other hand, when I try buying an upgraded version, I get an error: "the credit card is used already by a different user" (myself).

Please help ASAP. I want to upgrade

**Comment by bwsky-a** [comment]
Hi, 
Please contact us by email  (at contact@mdbootstrap.com) with a detailed description of the problem 
(please attach your order number)

Keep coding,
Adam From MDB
