### ISSUE TITLE
Better Material Tabs

### ISSUE THREAD

**Issue by holema** [mdbootstrap/mdb-ui-kit#1503]
Hello team,
I use the framework since some years and I´m very happy with it.
But the Tabs are not realy material conform.
For this I created a npm mudule with real material tab design. It also stores the last selected tab.

Propably it can be usefullfull for the project.
https://www.npmjs.com/package/h2-invent-material-tabs

Best regards

**Comment by gbujanski** [comment]
Thanks! We will check it and try to adapt our tabs to Material Tabs
