### ISSUE TITLE
XS sizing not functioning

### ISSUE THREAD

**Issue by jakkut** [mdbootstrap/mdb-ui-kit#1506]
For code like the following, the `xs` property doesn't function.
`        <MDBCol xs="6" sm="4" lg="2" className="col-6 kanji-tile-col d-flex justify-content-center">`
`            <MDBCard className="kanji-tile-card">`
`                <MDBCardBody>`
`                    <MDBCardTitle className="kanji-character">{ props.character }</MDBCardTitle>`
`                    <MDBCardText className="kanji-voting">`
`                        <button className="upvote"><MDBIcon fas icon="angle-up" /></button>`
`                        <span className="vote-count">104</span>`
`                        <button className="downvote"><MDBIcon fas icon="angle-down" /></button>`
`                    </MDBCardText>`
`                </MDBCardBody>`
`            </MDBCard>`
`        </MDBCol>`

I can override it by adding stylings to other breakpoints and adding the `col-6` class, but the `xs` functionality is not there.

**Comment by gbujanski** [comment]
It looks like you are using a different version of the MDB, this is the MDB Standard repository. Please create issue on the repo you are using ([MDB Angular](https://github.com/mdbootstrap/mdb-angular-ui-kit), [MDB React](https://github.com/mdbootstrap/mdb-react-ui-kit/issues) or [MDB Vue](https://github.com/mdbootstrap/mdb-vue-ui-kit))
