### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by robertdelanghe** [mdbootstrap/mdb-ui-kit#1510]
I've come across a few bugs within `MDB Pro`. I have patches I'd love to create PRs for. Of course not here within the public repo. I suggest added to this readme a contribution section or a seperate contribution doc.

In the meantime could you direct me to the appropriate place?

**Comment by gbujanski** [comment]
If you are using a single use license you will not have a place to add PR. But if you bought a license with access to Git lab there you can add MR. 

Remember that you can always create a ticket on our support and send us information about what is not working and how to fix it. There you can add the code that you would use in the component to make it work properly. Of course, if they are about 2-3 lines of code, not 50% of the component code :D If a large amount of code needs to be changed, you can send us a solution at contact@mdbootstrap.com
