### ISSUE TITLE
Carousel - API - disable interval not working

### ISSUE THREAD

**Issue by pw-appstruction** [mdbootstrap/mdb-ui-kit#1514]
As in the documentation described, data-mdb-interval sets the time for auto slide. With data-mdb-interval="false" it is possible to disable the interval - but this is not working - when I set it to "false" it slides only much faster.

**Comment by gbujanski** [comment]
Thanks for reporting. This is incorrect information in the documentation. We'll fix it. 
To disable autoplay set data-mdb-ride="false"
