### ISSUE TITLE
Improve dropdown behavior

### ISSUE THREAD

**Issue by jmcbee** [mdbootstrap/mdb-ui-kit#152]
http://www.google.com/design/spec/components/buttons.html#buttons-other-buttons

![](http://material-design.storage.googleapis.com/images/components-buttons-desktop-dropdowns_large_mdpi.png)

**Comment by FezVrasta** [comment]
How would you apply these guidelines on, for example, this navbar menu?

![image](https://cloud.githubusercontent.com/assets/5382443/4810131/f6568150-5eb0-11e4-8884-86cdd357284a.png)

I think we should make the button large as the dropdown, but I think it would not looks quite good.

**Comment by TransitoryBliss** [comment]
My suggestion is that we animate the Dropdown anchor, putting it above other items, expand to the size of the actual dropdown content and then animate the dropdown to slide down. Seeing as it would be impossible to have the exact same behaviour in a navbar.

**Comment by FezVrasta** [comment]
this would make the other elements shift and could cause problems, for example:

```
[foo] [bar] [is] [awesome]
```

Would becomes:

```
[foo] [bar       ] [is]
[awesome]
```

I mean, it would shift elements and make some of them go to a new line... I hope I'm clear ^_^

**Comment by TransitoryBliss** [comment]
Yeah but what I'm talking about is that it positions itself above the other elements on click, I'm on ghat btw =)

**Comment by FezVrasta** [comment]
ah ok I see, it would overlap the other elements so, umh not sure if this is what material design says but I think would look okay :) I'm on ghat as well

**Comment by jmcbee** [comment]
I think the first step would be changing the caret to point upwards when the dropdown is expanded.

**Comment by FezVrasta** [comment]
well this is the last of our problems :P

**Comment by FezVrasta** [comment]
Check out Dropdown.js to get a behavior similar to the one specified by Material Design.
