### ISSUE TITLE
root variables not used?

### ISSUE THREAD

**Issue by MichalNemec** [mdbootstrap/mdb-ui-kit#1520]
Hello, 
i see that in free kit there are :root variables i.e. --md-blue. Whenever i change it, nothing happens.
Is there a way to completely switch to these so that the dark mode and changes themselves are easily done?

**Comment by gbujanski** [comment]
I guess you meant to change `--mdb-primary`. This variable is used to define the button color (`.btn-primary`). We currently use css variables where possible and we intend to develop the ability to customize MDB UI Kit with css variables

**Comment by BaileymcCarthy** [comment]
Thanks for the information. [ Mybkexperience](https://www.mybkexperience.one/)
