### ISSUE TITLE
Button randomly resizes on click

### ISSUE THREAD

**Issue by Robin-OwO** [mdbootstrap/mdb-ui-kit#1521]
I am a bit confused by the behavior as it is a new Vue project.
When clicking on the button, it randomly resizes like shown and then shrinks back down.
<img src="https://github.com/mdbootstrap/mdb-ui-kit/assets/68992023/dd7ae042-9c38-4d65-9167-488ce8e0f2c5" alt="drawing" width="80%"/>

**Comment by gbujanski** [comment]
We have created a dedicated version for Vue. You should use https://github.com/mdbootstrap/mdb-vue-ui-kit

**Comment by AdamMiltonBarker** [comment]
This also happens with us. We are not using Vue and cannot get it to stop.
