### ISSUE TITLE
Transforming Icons

### ISSUE THREAD

**Issue by davidpiesse** [mdbootstrap/mdb-ui-kit#153]
This guy seems to have some useful code
http://sarasoueidan.com/demos/navicon-transformicons/
https://github.com/sarasoueidan/navicon-transformicons

D

**Comment by FezVrasta** [comment]
They are already planned, honestly the ones you have linked looks ugly

**Comment by davidpiesse** [comment]
I agree that they are not pretty (or use material design icons) just a FYI of something that is 'complete' - even if a bit crud
