### ISSUE TITLE
Wrong colour for pills, breadcrumbs, pagination, pager, and badges

### ISSUE THREAD

**Issue by kerunaru** [mdbootstrap/mdb-ui-kit#154]
It seems that blue colour is not #4285f4 but #428bca (bootstrap default one)

In fact, I think styles for these components are not even overwritten with material design colours and shapes (note the pills have rounder borders than a button, for example).

**Comment by FezVrasta** [comment]
these components are not yet ready, I had no time to work on them. any PR is welcome.

**Comment by kerunaru** [comment]
Okay, I'll take a look this evening :)
