### ISSUE TITLE
Rendering issue inside ng-view

### ISSUE THREAD

**Issue by redbeardmickey** [mdbootstrap/mdb-ui-kit#157]
I was trying to mark up a form in a template inside Angular ng-view. The button works fine with ripples but the input field is not rendered properly: no animation on-click and can't add classes (has warning, etc.). However, everything works fine if I just move them to the index.html. I looked for solutions everywhere but couldn't figure out why. Any idea?

Thanks,
Mickey

**Comment by FezVrasta** [comment]
try including arrive.js before material.js

**Comment by redbeardmickey** [comment]
Thanks! It works!

**Comment by redbeardmickey** [comment]
Hi,

The problem came up again. I did an bower update on all the packages and suddenly it fails to render the animations.

This is how I include the js files right now:
  `<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>`
  `<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>`
  `<script src="bower_components/bootstrap-material-design/dist/js/ripples.min.js"></script>`
  `<script src="arrive-2.0.0.min.js"></script>`
  `<script src="bower_components/bootstrap-material-design/dist/js/material.min.js"></script>`

**Comment by FezVrasta** [comment]
Recently the material.js API is changed, now you have to init it manually running $.material.init(), maybe this is the problem?

**Comment by redbeardmickey** [comment]
Solves the problem again. Thanks!
