### ISSUE TITLE
Ripple starts on mouseover on some particular combination of Windows+PC

### ISSUE THREAD

**Issue by miczza** [mdbootstrap/mdb-ui-kit#161]
It also happens on your demo page, I don't know if is because I'm using the 64bit of Chrome, but when I go with my pointer hover a button or a link for the first time, the ripple effect starts automatically.

**Comment by FezVrasta** [comment]
Please provide the version of your browser

**Comment by miczza** [comment]
Google Chrome
Version 38.0.2125.111 m (64-bit)

**Comment by FezVrasta** [comment]
I use the dev version 64bit (39.x.x.x) and everything works correctly... I'd wait some time to see if this problem get fixed by an update or what.

**Comment by rbozan** [comment]
Got the same issue.

**Comment by Jonathlee** [comment]
Same issue with Firefox 32, win 7 (64bit). But not on my Chrome Version 38.0.2125.111 m or Chrome Canary.

Firefox 32.

Scenario:
After clicked on any one button element; 
upon mouse hover on any other button, ripple will trigger.

**Comment by ukits** [comment]
In my case,
Chrome on Windows 8.1 got same. (Chrome 38.0.2125.111 m, Windows 8.1)
Same version of Chrome on Windows 7 is OK.(Chrome 38.0.2125.111 m, Windows 7)

I have a couple of Windows 8.1 Virtual Machines, All Chromes on Win 8.1 get same.

**Comment by FezVrasta** [comment]
I can't really reproduce this issue so please any PR is very welcome.

**Comment by TransitoryBliss** [comment]
Tried reproducing this as well - no luck.

**Comment by mikedepo** [comment]
Same here. On chrome. MouseOver cause ripple effect.

**Comment by mikedepo** [comment]
But it actually does it since the beginning,  not only the last version.

**Comment by rbozan** [comment]
Maybe something with this -> ripples.js, line 150 -> bind(["mouseover", "touchstart"], withRipple, rippleInit);

i dont know what else could produce this issue..

**Comment by FezVrasta** [comment]
it's absolutely this the problem but it should not cause this problem because rippleInit just prepares the element for the click event... by the way I'll try to improve the way this is handled so maybe the problem will be fixed.

**Comment by ukits** [comment]
I found something difference between OSes,

on ripple.js line 137,
if (window.ontouchstart === null) {

When mouseover event rises on Chrome 38.0.2125.111 m with Windows 7, 'window.ontouchstart' returns 'undefind'. and never ripple when mouseover
When mouseover event rises on Chrome 38.0.2125.111 m with Windows 8.1, 'window.ontouchstart' returns 'null'. and ripple when mouseover

Chrome has just updated and same on Chrome 38.0.2125.122 m

**Comment by FezVrasta** [comment]
thanks I'll try to fix it.

**Comment by FezVrasta** [comment]
may someone try the 604360b69528cea8cb06dc649178e725f7e6e953 patch and let me know if now it is fixed?

**Comment by ukits** [comment]
Thank you for fixing it.

on Chrome 38.0.2125122 m with Windows 7, [ "ontouchstart" in window ] returns false.
on Chrome 38.0.2125122 m with Windows 8.1, [ "ontouchstart" in window ] returns true.

So they still have the ripple effect when mouseover on Windows 8.1.

**Comment by FezVrasta** [comment]
ok so the question is, why chrome thinks that it support touch screens? It shouldn't, or better, on my 3 PC with Windows 8 and 8.1 the ontouchstart returns false...

I've tried with another approach, may you test?

**Comment by ukits** [comment]
The fixed code works fine on my Surface 3 pro (Windows 8.1). It didn't works only Windows 8.1 vmware machines. Sorry about my carelessness.

But I have no idea why the VMs return true [ "ontouchstart" in window ].
I'll try futher.

Thank you again.
