### ISSUE TITLE
The ripple doesn't clear when you click on another button

### ISSUE THREAD

**Issue by sophlee** [mdbootstrap/mdb-ui-kit#164]
![buttons](https://cloud.githubusercontent.com/assets/2179222/4835514/3986713a-5fb8-11e4-85f7-8b0e323f4b63.gif)

You can fix it by changing line 119 in the ripples.js from
 $ripple.remove();
to 
$( ".ripple-on" ).remove();

**Comment by FezVrasta** [comment]
duplicate of #135
