### ISSUE TITLE
main element is wrong in bower.json

### ISSUE THREAD

**Issue by destan** [mdbootstrap/mdb-ui-kit#169]
in bower.js the main element is as follows:

```
"main": [
    "dist/css/material.css",
    "dist/js/material.js",
    "dist/css/ripples.css",
    "dist/js/ripples.js"
  ]
```

however in the repo, files under `dist` [directory](https://github.com/FezVrasta/bootstrap-material-design/tree/master/dist/css) are  ending with `.min.css` or `.min.js`

**Comment by apexskier** [comment]
This commit needs to be patched to 0.1.4 - 18be97eb948f4c035ec12329a52ef13ea18c2aa1

**Comment by FezVrasta** [comment]
I've not idea on how to patch an already existing git tag... currently I'm working on the 0.1.5 which should fix it and other problems.

**Comment by FezVrasta** [comment]
I close it because the problem is fixed in the develop branch

**Comment by apexskier** [comment]
You can [change a git tag](http://stackoverflow.com/questions/8044583/how-can-i-move-a-tag-on-a-git-branch-to-a-different-commit), but it's probably not the best thing to do.

You could also create a patch level release, which would allow bower users to use ~0.1.4 and get it.

I think you'd tag a release with something like 0.1.5 or maybe 0.1.4-patch.1. I'm not really sure though. I got my info from https://github.com/npm/node-semver#tilde-ranges-123-12-1.

In any case, if someone really needs this working right now, they can specify the commit in their bower.json.

``` json
"bootstrap-material-design": "FezVrasta/bootstrap-material-design#7cab18db8c1db769b83e8f92de0fc4877476043b",
```
