### ISSUE TITLE
ripples.js not working properly in Firefox

### ISSUE THREAD

**Issue by waylaidwanderer** [mdbootstrap/mdb-ui-kit#17]
For example, clicking a link in the navbar will show the ripple effect properly, except that it stops it from actually acting as a link - i.e. clicking a link does not make the page go anywhere.

It works fine in Chrome, however. No javascript errors in Firefox's console that I can see. I also removed the `javascript:void(0)` from the `href` but that made no difference.

I'd also like to note that this stops the dropdowns in the navbar from showing up. I haven't tested what happens if I try using a button.

**Comment by FezVrasta** [comment]
Will try to fix it tomorrow morning.. probably it's some css problem.

**Comment by waylaidwanderer** [comment]
I fixed this with a simple `target.click();` added to the end of `rippleStart`.

I'll leave this issue open if you want to implement another solution, though.

**Comment by waylaidwanderer** [comment]
Actually, this breaks button functionality (causing buttons to be clicked twice), so I added a check that makes sure it's an `a` tag first.

```
if (target.tagName == 'A' || target.parentNode.tagName == 'A') {
    if (e.buttons == 1) {
        target.click();
    }
}
```

**Comment by FezVrasta** [comment]
fixed with 42494e245b2ce0ab464fcedfa36ed12b0ebe9403

not sure if the click event would be better on rippleStart or rippleEnd, atm I've put it on rippleEnd so the ripple effect is visible even when you click a link which should change the page content.

**Comment by waylaidwanderer** [comment]
Putting it on rippleEnd only navigates to the link when the animation is over, which is unintuitive and goes against how links should work. Putting it on rippleStart will still play the rippleEnd animation if the page takes long enough to load.

**Comment by FezVrasta** [comment]
I've already fixed it

**Comment by waylaidwanderer** [comment]
Great to hear, I didn't notice
