### ISSUE TITLE
Inbox vs this project?

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#174]
Has someone tried Google Inbox? I've just got the invitation and it looks very nice, but it lack of animations and the ones it has are very laggy. Looks like this project has a better implementation of Material Design than the Inbox project by Google.

What do you think?

**Comment by cgeorgakopoulos** [comment]
Material design is not yet mature. If you actually try to implement it on real environments, you' ll notice that there aren't ready solutions for many issues (although it's way more mature than MS metro style). So I think it's normal that different Google products are not yet consistent, or taking slightly different approaches. It certainly feels like material design is moving to the right direction and solutions are waiting to be discovered...

**Comment by FezVrasta** [comment]
Yea I'm using it on my company project and I find every day problems without solutions :/
