### ISSUE TITLE
Tagged version 0.1.5 has conflicts in readme

### ISSUE THREAD

**Issue by jbueza** [mdbootstrap/mdb-ui-kit#175]
![screen shot 2014-11-01 at 7 19 54 pm](https://cloud.githubusercontent.com/assets/25766/4874039/ce508c76-6236-11e4-874a-d384561b679a.png)

Currently on `develop` this doesn't show up -- are you guys going to publish 0.1.6 to bower, which addresses this?

Cheers,
Jaime

**Comment by FezVrasta** [comment]
I've noticed this problem after I've published 0.1.5, it will be fixed in 0.1.6 but I think it's not really a big problem... It affects just the readme

**Comment by jbueza** [comment]
Thanks!!
