### ISSUE TITLE
Use Material Design icon web font

### ISSUE THREAD

**Issue by soygul** [mdbootstrap/mdb-ui-kit#178]
Material Design icons are now open sourced and published on Bower so you can use them to get automatic updates rather then burying them in the project sources: https://github.com/google/material-design-icons

**Comment by FezVrasta** [comment]
I can't find an iconic font version of them in that repo

**Comment by soygul** [comment]
Yep, I automatically assumed this feature request (https://github.com/google/material-design-icons/issues/1#issuecomment-60055131) to have been done by now. Obviously still in works though.

**Comment by FezVrasta** [comment]
I'll implement the official one when they'll release the iconic font so.

**Comment by soygul** [comment]
:+1:

**Comment by MikeElghali** [comment]
+1

**Comment by bsr203** [comment]
https://github.com/google/material-design-icons/tree/master/iconfont

**Comment by rosskevin** [comment]
Font seems to be available now - http://google.github.io/material-design-icons/#icon-font-for-the-web

**Comment by ivantcholakov** [comment]
I did in my place a local installation. Might be helpful somehow. https://github.com/ivantcholakov/starter-public-edition-3/commit/8315eb9a106a76e292194f85fbff14372afec9f0

**Comment by rosskevin** [comment]
Fixed in 0.5.0-dev
