### ISSUE TITLE
Checkboxes don't word in chrome on android

### ISSUE THREAD

**Issue by sgldev** [mdbootstrap/mdb-ui-kit#179]
The checkboxes dont seem to work correctly when viewed in chrome on android, this is also a issue when viewed in the android default browser.

The issue is visible in the docs when viewed on android.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
