### ISSUE TITLE
Graphical glitch when repeatedly clicking on a rippled element.

### ISSUE THREAD

**Issue by waylaidwanderer** [mdbootstrap/mdb-ui-kit#18]
I found this on the navbar but I assume it'd be the same for other ripply elements too. If you spam-click a link, the ripple overlay sometimes doesn't get removed so the element gets darker and darker. If you're not sure what I'm talking about, try it on one of the navbars on your demo page: http://fezvrasta.github.io/bootstrap-material-design/

**Comment by FezVrasta** [comment]
I'm aware of this problem but I can't find what is the error...

**Comment by waylaidwanderer** [comment]
I found the source of the problem. `document.dispatchEvent` seems to be unreliable. I've tested a fix that seems to work and I'll make a pull request once you've looked at #21.

**Comment by FezVrasta** [comment]
Still open to PRs for this bug.

**Comment by roeku** [comment]
Well i too noticed this when i first came in contact with this git. I didn't make an issue of it because when you click on a button it's supposed to perform an action which would negate a user spamclicking a button. Don't get me wrong it would be better if it didn't bug out but looking at it from a UI perspective i don't consider it an issue.

**Comment by FezVrasta** [comment]
It can cause problems if you apply the ripple effect to something that is not a link (an image, a dropdown toggle etc)

I'd very like to fix this problem :/

**Comment by shak18** [comment]
this could help you fix the issue there are 4 great approaches to ripple and doesnt seem to have that bug

http://codepen.io/madshaakansson/pen/ykode

http://codepen.io/KrisOlszewski/pen/Dnktj

http://codepen.io/Craigtut/pen/dIfzv

http://codepen.io/idiotWu/pen/nefhC

hope it can help cause youre making a great job with this :)

**Comment by FezVrasta** [comment]
All of them have a trouble, when you hold the mouse down the ripple does not stay active. And this is the difficult part of my script which makes it different and(possibly) better than others

**Comment by aarohmankad** [comment]
Has this since been fixed? I can't seem to replicate the issue.

**Comment by ezpuzz** [comment]
Definitely gets darker after repeated clicks for me in FF33, I like that last example shak18 posted.

**Comment by waylaidwanderer** [comment]
I've submitted a pull request that should fix this problem.

**Comment by waylaidwanderer** [comment]
I've updated the pull request to allow multiple ripples to animate while still removing old ripples correctly.
