### ISSUE TITLE
In Safari Version 8.0 (10600.1.25), the ripple effect is not working.

### ISSUE THREAD

**Issue by aniarya82** [mdbootstrap/mdb-ui-kit#181]

**Comment by FezVrasta** [comment]
I've not a mac to test Safari, PR are welcome.

**Comment by irwing-reza** [comment]
Hi,
I could check this out :hand:

**Comment by FezVrasta** [comment]
thanks, it would be useful :)

**Comment by pmtarantino** [comment]
I can confirm this is not working on Safari on mobile (iOS). It shows a dot where you clicked but it doesn't expand (the same happnes on Chrome on iOS)

**Comment by FezVrasta** [comment]
thanks but I've not a mac or an iphone to test.

**Comment by irwing-reza** [comment]
Sorry for the delay, found the issue

**Comment by irwing-reza** [comment]
Pull request for fix here https://github.com/FezVrasta/bootstrap-material-design/pull/223
