### ISSUE TITLE
Prevent duplicated event handlers

### ISSUE THREAD

**Issue by npvn** [mdbootstrap/mdb-ui-kit#184]
On dynamic frameworks like Meteor, `$.material.init` will be called several times. This leads to an issue: multiple ripples are generated at the same time, making the ripple color look very bold + high overhead.

This issue can be reproduced by going to http://fezvrasta.github.io/bootstrap-material-design and execute `$.material.init` several times from the console.

At first I thought this can be solved by changing the bind helper from

``` javascript
var bind = function(events, selector, callback) {
    if (typeof events === "string") {
        events = [events];
    }
    events.forEach(function(event) {
        document.addEventListener(event, function(e) {
            var target = (typeof e.detail !== "number") ? e.detail : e.target;

            if (matchesSelector(target, selector)) {
                callback(e, target);
            }
        });
    });
};
```

to

``` javascript
var bind = function(events, selector, callback) {
    if (typeof events === "string") {
        events = [events];
    }

    executeCallback = function(e) {
        var target = (typeof e.detail !== "number") ? e.detail : e.target;

        if (matchesSelector(target, selector)) {
            callback(e, target);
        }
    };

    events.forEach(function(event) {
        document.removeEventListener(event, executeCallback);
        document.addEventListener(event, executeCallback);
    });
};
```

where `executeCallback` is a global variable (just a placeholder to store the function's name).

But this doesn't work.

Any explanation or suggestion is very welcomed.

**Comment by FezVrasta** [comment]
ripples.js binds events even on dinamically generated elements, so you may just add a check to know if ripples.js was already inited

```
// add the "done" boolean inside ripples.js
window.ripples = { 
    init: function(withRipple) { /*bla bla*/ },
    done: false
}

// Then, where you run ripples.init... (aka, material.js, or maybe directly inside the init function of ripples.js)
if (!window.ripples.done) { 
  ripples.init();
  ripples.done = true;
}
```

**Comment by npvn** [comment]
Thank you. This works perfectly.

Do you think we should add this to the project so other developers won't encounter this issue?

**Comment by FezVrasta** [comment]
I think it can be only a good addition, I can't see any downsides.
