### ISSUE TITLE
Buttons active state issue

### ISSUE THREAD

**Issue by nospoon** [mdbootstrap/mdb-ui-kit#186]
I've noticed an issue with buttons, where after clicking they sometimes retain the active state visually, even though it has no representation in class. It can be seen on the example page. I haven't been able to find any specific replication condition.

**Comment by wopian** [comment]
Clicking on buttons then moving your cursor off the button before releasing will nicely replicate this issue on Chrome.

**Comment by FezVrasta** [comment]
duplicate of another issue
