### ISSUE TITLE
Bug in "Navs" Section.

### ISSUE THREAD

**Issue by BCleverly** [mdbootstrap/mdb-ui-kit#19]
If you click on the Dropdown in the very left nav and move your mouse out of the Dropdown anchor it will go transparent and you won't be able to read the text.

Firefox V32.

**Comment by FezVrasta** [comment]
sorry I can't reproduce the problem... may you be more specific or register a short video with something like  https://addons.mozilla.org/en-US/firefox/addon/makegif-video-capture/

?

thanks!

**Comment by BCleverly** [comment]
Currently not able to reproduce it now. Most probably something playing up on my machine. If i can reproduce it again I'll update the issue. Thanks for the handy add-on as well, will come in handy.
