### ISSUE TITLE
The sass version is different from the css in dist folder

### ISSUE THREAD

**Issue by JakeLin** [mdbootstrap/mdb-ui-kit#193]
The sass version is different from the css in dist folder, how can I get the latest sass for the css which the demo site (http://fezvrasta.github.io/bootstrap-material-design/) is using?

Thanks
Jake

**Comment by FezVrasta** [comment]
unfortunately I'm not the maintainer of the SASS version, he's @shockwork. Looks like he's quite busy in these weeks so I'm not even sure if I should still support the SASS version...

**Comment by JakeLin** [comment]
Why don't you use sass to develop the code and compile it to css? how can I help with this?

**Comment by FezVrasta** [comment]
I use LESS to develop the code, if you want to translate LESS to CSS feel free to send a pull request.

**Comment by TransitoryBliss** [comment]
@JakeLin Hello Jake, feel free to read the README :) https://github.com/FezVrasta/bootstrap-material-design#less--sass . I'm the maintainer of the SASS version, it's being updated. But do not expect the SASS version to reflect the LESS version until a stable version is released.

**Comment by JakeLin** [comment]
Hi @shockwork , Could you please advice branch did you update the sass to match the less version? I can't find it in the repo? 

Thanks
Jake
