### ISSUE TITLE
Angular.js textarea binding doesn't trigger floating-label

### ISSUE THREAD

**Issue by destan** [mdbootstrap/mdb-ui-kit#194]
In a textarea with `floating-label`, when data-binding happens automatically via `ng-model`, label doesn't push-up and overlaps with the text value.

**Comment by FezVrasta** [comment]
does angular fires some event when it pushes the new content to the element?

OT: I'm planning to use Angular for my next projects so the support for it will improve.

**Comment by destan** [comment]
I don't know the nuts'n'bolts of angular to that degree.

currently (and temporarily) I had to use `$('textarea').trgigger('change')` :(

**Comment by FezVrasta** [comment]
I've done some research and looks like you should trigger the change event inside the angula binding... 

```
$(element).trigger("change");
```

Can't find any other way to fix this problem, the current implementation of the material inputs is tricky because it needs to add lot of elements and unfortunately there's not a fu**ing CSS selector for empty inputs... If someone finds a way to select with pure CSS an empty input please post it and all this pain will end ^_^"

**Comment by destan** [comment]
I have problems with calling `$(element).trigger("change");` properly because I couldn't find a callback which is triggered after Angular's `ng-model` bindings are done on the DOM. Do you get what I mean?

So currently I trigger the `change` event after a 200ms timeout which is soo lame :-1: 

PS: Waiting for document ready event doesn't resolve the issue since Angular's  bindings wouldn't be completed at that time.

**Comment by FezVrasta** [comment]
I'm trying to find some better way...

**Comment by FezVrasta** [comment]
have you tried "ng-change"? It should do the trick (but I'm still looking for a support-everything solution)

**Comment by destan** [comment]
`ng-change` is not triggered for `ng-model` bindings.

By the way [I've asked SO](http://stackoverflow.com/questions/26884566/is-there-a-callback-in-angular-js-triggered-after-a-ng-model-binding-is-done) about this issue, hope something pops out.

**Comment by FezVrasta** [comment]
related to #473, continue there
