### ISSUE TITLE
When using with Angular, inputs have 'ng-dirty' class from the page load

### ISSUE THREAD

**Issue by d668** [mdbootstrap/mdb-ui-kit#198]
Please have a look 
http://plnkr.co/edit/aO8OvXMmRq7N3R3o9kfC
the textbox has ng-dirty class from the beginning 

here is ripples.js and material.js commented out
http://plnkr.co/edit/JYKBuENvkQFg8o3KWMKb?p=preview
and it works as expected - i.e. the text box gets the class ng-dirty only after starting to type

this issue is critical for forms in Angular that rely on ng-dirty for styling

**Comment by FezVrasta** [comment]
This is the problem:

https://github.com/FezVrasta/bootstrap-material-design/blob/master/scripts/material.js#L124-L156

Honestly I can't find a way to keep that fix and prevent this problem... Any idea?

For now, if you wanna disable this, you can init manually the material scripts:

```
$.material.input();
$.material.checkbox();
$.material.radio();
$.material.ripples();
```

Instead of:

```
$.material.init();
```

**Comment by d668** [comment]
Thanks this is perfect for the moment!

**Comment by FezVrasta** [comment]
Now autoinit is disabled by default
