### ISSUE TITLE
Dropdown in navbar

### ISSUE THREAD

**Issue by Bound3R** [mdbootstrap/mdb-ui-kit#20]
The dropdown is disabled for no reason, as if run with hover, click check status to verify that the drop remains active.
review: class = [ .dropdown-toggle .withripple ] && data-toggle = [ dropdown ]

**Comment by FezVrasta** [comment]
Sorry I don't understand what are you talking about... May you try to be more clear?

**Comment by Bound3R** [comment]
ok, no problem look : http://i.imgur.com/mXmsh1j.gif
do not know if you noticed, but takes action to click, and then hides alone, without making or click on another item in the same.

**Comment by waylaidwanderer** [comment]
I think @Bound3R is saying that when he clicks the Dropdown it hides itself immediately without him doing anything else.

**Comment by waylaidwanderer** [comment]
By the way, the problem is caused by 42494e245b2ce0ab464fcedfa36ed12b0ebe9403. I would suggest implementing my fix instead, which I have tested and it works in both Firefox and Chrome with no issues. I'll make a pull request momentarily for you.

**Comment by FezVrasta** [comment]
I've forgot to add a preventDefault to the script... Will fix it asap

**Comment by FezVrasta** [comment]
fixed with 68d3fd3be597452c127eb15e96bcb2176648c426
