### ISSUE TITLE
Graph Icons

### ISSUE THREAD

**Issue by sureshprasanna70** [mdbootstrap/mdb-ui-kit#203]
If there are icons for graph then I feel the icon set will be complete

**Comment by FezVrasta** [comment]
I'm using the icons from the official google library, if you know some better material design iconic font please let me know.

**Comment by sureshprasanna70** [comment]
Why not use this @FezVrasta 
http://saeedalipoor.github.io/icono/

**Comment by FezVrasta** [comment]
awesome :) But they are not material design so not a good idea implement them here

**Comment by sureshprasanna70** [comment]
Will keep looking...
