### ISSUE TITLE
extra 1px on btn-group on click

### ISSUE THREAD

**Issue by MRezaSafari** [mdbootstrap/mdb-ui-kit#204]
i have this button group which is the second one have negative margin and no border radius on top and the first one have no border radius on the bottom.
here is the markup 

 `<div class="btn-group first-set btn-group-flat" role="group" aria-label="...">
            <button type="button" class="btn btn-info"><i style="color:rgb(253, 229, 55)" class="fa fa-star"></i></button>
            <button type="button" class="btn btn-info"><i style="color:#7ffa3a" class="fa fa-indent"></i></button>
            <button type="button" class="btn btn-info"><i style="color:#fd2f2f" class="fa fa-heart"></i></button>
        </div>
        <div class="btn-group second-set btn-group-flat" role="group" aria-label="...">
            <button type="button" class="btn btn-info"><i style="color:#ff8b8b" class="fa fa-warning"></i></button>
            <button type="button" class="btn btn-info"><i style="color:white" class="fa fa-send"></i></button>
            <button type="button" class="btn btn-info"><i style="color:#60b9ff" class="fa fa-share-alt"></i></button>
        </div>
        <div class="btn-group third-set btn-group-flat" role="group" aria-label="...">
            <button id="GoPrevQ" type="button" style="border-right: 2px solid #2a2a3a" class="btn btn-info">prev<i style="margin-right: 5px;vertical-align: middle" class="fa fa-arrow-circle-o-left"></i> </button>
            <button id="GoNextQ" type="button" class="btn btn-info"><i style="margin-left: 5px;vertical-align: middle" class="fa fa-arrow-circle-o-right"></i> next</button>
        </div>`

and the output is :
![noclick](https://cloud.githubusercontent.com/assets/1060150/5043381/d7fbe6ea-6bf9-11e4-902b-7c149ff4aa17.jpg)

but there is a problem . when i click on one of button its create an extra pixel at the left which is not pretty at all . i have btn-group-flat class to not having a shadow but still no luck on this one .

![onclick](https://cloud.githubusercontent.com/assets/1060150/5043382/d81dfd02-6bf9-11e4-8adc-9c765acbdb5a.jpg)

**Comment by FezVrasta** [comment]
this bug should be fixed in the next days.

**Comment by FezVrasta** [comment]
should be fixed @rSafari

**Comment by MRezaSafari** [comment]
totally fixed the problem .
thank you .
