### ISSUE TITLE
Input onChange event

### ISSUE THREAD

**Issue by jdutriaux** [mdbootstrap/mdb-ui-kit#205]
Hello, in all navigators : the checkbox onChange event is unexpectedly triggered, here is a little codepen to show you the problem : http://codepen.io/anon/pen/NPWwRE.

The onChange event is also triggered at the page's start which is not a good behavior (in my opinion).

**Comment by jdutriaux** [comment]
Update : problem is on all inputs elements

**Comment by FezVrasta** [comment]
this is caused by some javascript that should fix the autofill feature of the browsers.
