### ISSUE TITLE
Flickering When Used With Token Tag

### ISSUE THREAD

**Issue by bentinata** [mdbootstrap/mdb-ui-kit#210]
I tried using this with some other token tag (Bootstrap-tokenfield, Bootstrap-tagsinput, taggingJS, etc). The result is flickering tag inside the input box.
Any ideas?

**Comment by FezVrasta** [comment]
may you provide a demo? (codepen.io)

**Comment by bentinata** [comment]
http://codepen.io/anon/pen/vEYPge
Well, the flicking isn't as rapid as in my site. Maybe my site is the one that wrong.

**Comment by FezVrasta** [comment]
are you talking about the focus effect that starts on each click?

**Comment by bentinata** [comment]
No. Look at this input. http://cloud.jepret.me/flicker
Anyway, how do I give that input animation to an usual div?

**Comment by FezVrasta** [comment]
it does not happen in the pen so is not a problem of this theme I think.

**Comment by FezVrasta** [comment]
Not tested:

```
<div class="form-control-wrapper" tabindex=0>
something
</div>
```

**Comment by bentinata** [comment]
Well, it does happen in pen, but not as extensive as in my site. Anyway thanks. :)
