### ISSUE TITLE
Issue Internet Explorer 11

### ISSUE THREAD

**Issue by HeB-zz** [mdbootstrap/mdb-ui-kit#214]
Hi,
when I try the test page in the "dist" folder, It works in Chrome and Firefox but not IE 11.

Error on thi file :
Fichier : ripples.min.js, ligne : 1, colonne : 633

Thanks

**Comment by FezVrasta** [comment]
please provide more details and a pen (codepen.io) thanks.

**Comment by FezVrasta** [comment]
This bug should be fixed with fc0fed6eabec91e4535d78d06478a25c1fff67ce (:develop branch)

May you try it out and give me feedbacks?

**Comment by HeB-zz** [comment]
Sorry I was on an another project.
I'll try as I can .
Thank you

**Comment by FezVrasta** [comment]
any update? thanks
