### ISSUE TITLE
.ripple-wrapper border-radius should be inherit

### ISSUE THREAD

**Issue by garrettlancaster** [mdbootstrap/mdb-ui-kit#216]
.ripple-wrapper should have a border-radius of inherit so that more rounded ripple containers do not ripple across a square extending beyond their borders.

**Comment by FezVrasta** [comment]
Agree

**Comment by FezVrasta** [comment]
should be enough use `border-radius: inherit`?

**Comment by garrettlancaster** [comment]
Seems to work in my testing http://codepen.io/anon/pen/myyXPy

**Comment by dirtybirthdaycake** [comment]
`border-radius: inherit;` fixed this issue for me
