### ISSUE TITLE
support navbar-raised class

### ISSUE THREAD

**Issue by gasolin** [mdbootstrap/mdb-ui-kit#217]
It's a common effect that standing out the header from content

```
.navbar-raised {
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
}
```

**Comment by gasolin** [comment]
It will be better if we could change shadow level from 1 to 5 https://medium.com/@Florian/freebie-google-material-design-shadow-helper-2a0501295a2d

**Comment by FezVrasta** [comment]
there are specific classes to add shadows to every kind of element. Check out /less/_shadows.less

**Comment by gasolin** [comment]
I just realized I can use `shadow-z-n` to add shadow effect for any element, nice!
