### ISSUE TITLE
Can't minify material.js

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#22]
When I try to minify it (both with uglifyjs or with google closures compiler) the script does not work anymore... Need to investigate about this problem.

**Comment by hhsnopek** [comment]
@FezVrasta I just pulled the repo down, and used [uglify-js](https://github.com/mishoo/UglifyJS2) and it compiled over.
cmd: `uglifyjs --screw-ie8 material.js -o material.min.js`

I then updated the demo to use `material.min.js` and everything is still working. What exactly wasn't working?

**Comment by vishalsh-spec** [comment]
for Google Closure compiler : i tried to compile ripples js , it will compile and minifiy correctly 

Compilation was a success!
Original Size:  1.68KB gzipped (5.34KB uncompressed)
Compiled Size:  763 bytes gzipped (1.61KB uncompressed)
Saved 55.61% off the gzipped size (69.78% without gzip)
