### ISSUE TITLE
Scrollable tabs

### ISSUE THREAD

**Issue by zhulduz** [mdbootstrap/mdb-ui-kit#220]
Hi,

Is it possible to make scrollable tabs?

Thanks.

**Comment by FezVrasta** [comment]
what do you mean?

**Comment by zhulduz** [comment]
Scrollable tabs display a subset of tabs at any given moment, and can contain longer tab labels and a larger number of tabs...

To navigate between scrollable tabs, touch the tab, swipe the tabs left or right, or swipe the content area left or right.

http://www.google.com/design/spec/components/tabs.html#tabs-usage

**Comment by FezVrasta** [comment]
This feature is not implemented at the moment.

**Comment by zhulduz** [comment]
ok, thanks.

**Comment by FezVrasta** [comment]
First prototype of tabs:

http://codepen.io/FezVrasta/pen/eBAvx

I'm not sure if would be better write a specific plugin or hack the Bootstrap one... probably is better a different plugin.

**Comment by M2A** [comment]
Hi,
Me and my friend are passionate to implement this feature,
so i have a question, is _tabs.less file related to the this feature?

**Comment by FezVrasta** [comment]
It should
