### ISSUE TITLE
Bootstrap modal, doesn't shade out the background.

### ISSUE THREAD

**Issue by ianpurton** [mdbootstrap/mdb-ui-kit#222]
Hi, you can see what I mean here. 

![screen shot 2014-11-20 at 18 11 34](https://cloud.githubusercontent.com/assets/36966/5129187/b72bf40a-70e0-11e4-97c5-c9bc9f819043.png)

When clicking on the modal the background used to be faded away. Now since moving over to material design it doesn't do that anymore.

Feature or bug ?

Demo is available after registration. https://bitsinodice.com/

Thanks.

**Comment by wopian** [comment]
I'd say it's a bug since the Material design specs uses this:

![](https://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B08MbvYZK1iNZ3ZWYkxacmJBZ1E/layout-structure-whiteframe_calendar_large_xhdpi.png)
