### ISSUE TITLE
Ripple effect leak

### ISSUE THREAD

**Issue by s-a** [mdbootstrap/mdb-ui-kit#224]
While fast clicks on different buttons the ripple effect leaks and some style will not remove totally. The behavior can be reproduced at http://fezvrasta.github.io/bootstrap-material-design/

I' ve tested this with Google Chrome Version 39.0.2171.65 m 

This is the result after a click attack. Only the Info button survived.
It seems that some css style accumulates.

![image](https://cloud.githubusercontent.com/assets/1270662/5140776/80456b36-716e-11e4-9ebf-33218a690852.png)

**Comment by justb81** [comment]
same behavior on Chrome 38.0.2125.122 (64-bit) , Firefox 33.0  (both Linux)

it is reproducable that way:
- start a "click storm" on one button
- move the mouse to another button, but continue to do fast clicks
- move back to the first button

i seems to have something to do with showing the ripple fadeout on different buttons at the same time.

**Comment by s-a** [comment]
Only a small addendum. I noticed this behavior first on Google Nexus 7 Tablet. And it is good reproducable with large buttons.

**Comment by FezVrasta** [comment]
yup this is a bug I'm aware of... by the way I'll rewrite from scratch ripples.js (probably with jquery) to respect the effect visible on Android Lollipop (the Nexus 5 of my gf have just got the upate so I can play with the buttons).

**Comment by FezVrasta** [comment]
This bug should be fixed with fc0fed6eabec91e4535d78d06478a25c1fff67ce (:develop branch)

May you try it out and give me feedbacks?

**Comment by s-a** [comment]
Seems to work there, but the effect is very dark now. It becomes black on double click.

**Comment by FezVrasta** [comment]
it can be tweaked, I've completely rewritten it, if you can suggest a good opacity value I can commit it

**Comment by s-a** [comment]
Sorry I am in minified mode :)
I think previous behavior was perfect. It was much more decent.

**Comment by FezVrasta** [comment]
if I remember right it was 0.2.... I'll try

**Comment by FezVrasta** [comment]
fixed with 0.1 opacity
