### ISSUE TITLE
mdi icon 

### ISSUE THREAD

**Issue by ovaar** [mdbootstrap/mdb-ui-kit#225]
I wanted to be able to Write some text with a Icon before or after the text within a link. Such as this : <a href="javascript:void(0)" class="btn btn-default btn-raised background-white withripple"><div class="ripple-wrapper"></div><figure class="mdi mdi-navigation-arrow-forward"></figure> Learn More</a>

In this case the icon comes above the text, unfortunally this is not what I want. By using "display:inline-block" on ".mdi, icon", line 5064, this is fixed. See also the font awesome implementation:
.fa {
  display: inline-block;
  font: normal normal normal 14px/1 FontAwesome;
  font-size: inherit;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

**Comment by FezVrasta** [comment]
please may you provide a codepen.io example?

**Comment by ovaar** [comment]
Example
http://codepen.io/anon/pen/emmbqe

**Comment by FezVrasta** [comment]
icons should be used with the tag `<i>`, not with `<figure>`.
