### ISSUE TITLE
Ripple from mobile

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#226]
I'm having trouble to run the ripple effect from mobile. Sometimes it works, sometimes it only works if I click twice (it seems it need the property: active to work).

Tested on Chrome Mobile

**Comment by FezVrasta** [comment]
I'll rewrite the script soon, these problems should be fixed then.

**Comment by ghost** [comment]
Ok, thank you for your awesome Material theme
