### ISSUE TITLE
Icon with ugly border: mdi-action-work

### ISSUE THREAD

**Issue by brunolemos** [mdbootstrap/mdb-ui-kit#227]
Just a detail, but it's keeping me from using this icon that would be perfect:

![screen shot 2014-11-23 at 1 34 15 pm](https://cloud.githubusercontent.com/assets/619186/5158020/85649c2e-7315-11e4-84b1-087217a152a3.png)

**Comment by FezVrasta** [comment]
Yup, have to fix it

**Comment by brunolemos** [comment]
Thanks :)

**Comment by FezVrasta** [comment]
finally fixed with #452!
