### ISSUE TITLE
ripple fires multiple times on mobile

### ISSUE THREAD

**Issue by Navgeet** [mdbootstrap/mdb-ui-kit#228]
each tap on a button leads to multiple ripples being fired

**Comment by FezVrasta** [comment]
ripples.js will be rewritten when I'll find some time, all these problems will be then fixed.

**Comment by Navgeet** [comment]
@FezVrasta any way I can help? I'm using bootstrap-material in a website and looking to fix this bug and a few others.

**Comment by FezVrasta** [comment]
I'm rewriting it, it should take another hour I think.

PRs for any of the issues opened here (except the ones related to ripples.js) are welcome.

**Comment by FezVrasta** [comment]
This bug should be fixed with fc0fed6eabec91e4535d78d06478a25c1fff67ce (:develop branch)

May you try it out and give me feedbacks?

**Comment by Navgeet** [comment]
will give it a go tonight.

**Comment by FezVrasta** [comment]
any update?

**Comment by FezVrasta** [comment]
I consider it fixed because the OP has not replied...

**Comment by eweseong** [comment]
tested, it works for me

**Comment by FezVrasta** [comment]
thanks

**Comment by Navgeet** [comment]
Sorry have been swamped with work over the last week. Just tested master on mobile, works perfectly. Also degrades gracefully in Cordova. Will be deploying ripples in production. Thanks!

**Comment by FezVrasta** [comment]
Great ;)
