### ISSUE TITLE
Colours on panels now showing

### ISSUE THREAD

**Issue by jones6951** [mdbootstrap/mdb-ui-kit#229]
In a previous version, the following HTML worked - the text in the h4 tag had a blue background. In current version, the panel background is grey.

```
    <div class="row well">
        <div class="panel">
            <div class="panel-heading well-material-lightblue">
                <h4>Text on blue background</h4>
            </div>
            Normal text
        </div>
    </div>
```

I think the 'styled panels, improved shadows' fix broke the colour.

**Comment by FezVrasta** [comment]
I've implemented panel stylings.. your markup is not correct, you can't use a well- class on a panel...

you should use a panel and add the well class to it prbably. check out the demo for some panel example

**Comment by jones6951** [comment]
Thanks. Will do as advised
