### ISSUE TITLE
In IE 11 "Object doesn't support this action" on m=new CustomEvent("rippleEnd",{detail:h}) line

### ISSUE THREAD

**Issue by d668** [mdbootstrap/mdb-ui-kit#231]
How to reproduce:
1. Download and extract bootstrap-material-design-master
2. Open Visual Studio 2013 and select File - Open - Web Site
3. Run in IE 11, click F12 and click on Primary button in Buttons section
   The debugger pause on the error 
   "Object doesn't support this action" 
   at the code 
   m=new CustomEvent("rippleEnd",{detail:h})

![image](https://cloud.githubusercontent.com/assets/2155554/5169746/13d1f97c-7445-11e4-899f-dfff2debc01a.png)

**Comment by FezVrasta** [comment]
does it happens even with the online demo?

**Comment by d668** [comment]
yes

![image](https://cloud.githubusercontent.com/assets/2155554/5198817/c236ad0e-7590-11e4-9bc3-d4d58a233995.png)

**Comment by d668** [comment]
,m=new CustomEvent("rippleEnd",{detail:h})

**Comment by FezVrasta** [comment]
okay confirmed, it will be fixed with the new version of ripples.js

**Comment by FezVrasta** [comment]
This bug should be fixed with fc0fed6eabec91e4535d78d06478a25c1fff67ce (:develop branch)

May you try it out and give me feedbacks?

**Comment by d668** [comment]
how to try out?

**Comment by FezVrasta** [comment]
Clone the develop branch....
