### ISSUE TITLE
Bug in btn-group

### ISSUE THREAD

**Issue by brodrigues1990** [mdbootstrap/mdb-ui-kit#233]
The Button Group has a bug, when I select the button it don't change the color !

**Comment by FezVrasta** [comment]
may you be more specific?

**Comment by brodrigues1990** [comment]
When I click on a button on btn-group, the specific button doesn't change
is active.

Obs.: Sorry my english, is not my mother tongue

2014-11-26 7:19 GMT-02:00 Fez Vrasta notifications@github.com:

> may you be more specific?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FezVrasta/bootstrap-material-design/issues/233#issuecomment-64535022
> .

## 

Bruno Rodrigues de Figueiredo

---

Tel.: (21)98136-2393

**Comment by FezVrasta** [comment]
Does it happens on the official demo?

May you please provide a demo of your problem using http://codepen.io/FezVrasta/pen/ihmea?

Thanks!

**Comment by brodrigues1990** [comment]
Yep

2014-11-26 9:55 GMT-02:00 Fez Vrasta notifications@github.com:

> Does it happens on the official demo?
> 
> May you please provide a demo of your problem using
> http://codepen.io/FezVrasta/pen/ihmea?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FezVrasta/bootstrap-material-design/issues/233#issuecomment-64594034
> .

## 

Bruno Rodrigues de Figueiredo

---

Tel.: (21)98136-2393

**Comment by brodrigues1990** [comment]
How do I get the input text value, if it is inside a SHADOW DOM ?

**Comment by ChihChengLiang** [comment]
Dear @FezVrasta , please see http://codepen.io/anon/pen/ogdBZB . The selected button should stand out in the button group, you can see this plain bootstrap example in comparison. http://jsfiddle.net/KyleMit/0nevkwyn/
