### ISSUE TITLE
At the begining ripple.js is activate on mouse hover

### ISSUE THREAD

**Issue by xavadu** [mdbootstrap/mdb-ui-kit#236]
Hello,

In an angular application i have the problem that the ripples occurs on mouse over (hover) the element but only for the first time, if i back with the mouse again over the element its doesn't activate the ripple. Later on click the ripple works good.

Some idea about this issue?
Some additional information that i can post?

Thanks

**Comment by FezVrasta** [comment]
Please check out the develop branch, this problem is fixed there.

**Comment by xavadu** [comment]
Thanks!
