### ISSUE TITLE
Dropdown not working correctly without focus (tested on firefox - ubuntu)

### ISSUE THREAD

**Issue by singold** [mdbootstrap/mdb-ui-kit#239]
If there isn't any focused element, the dropdowns don't work, you need to make 2 clicks, one to focus on the link, and the second to open the dropdown.

Also if you have focus on another element (for example a form input), the dropdowns work as expected.

Maybe this is an issue in dropdown.js, but I really don't know.

**Comment by FezVrasta** [comment]
I can't reproduce the problem...

**Comment by jaddison** [comment]
I'm seeing this as well on http://fezvrasta.github.io/bootstrap-material-design/ - Safari 8.0 (10600.1.25.1), OSX Yosemite 10.10.1. Appears to work fine in latest stable Chrome, same OSX system.

I click on it the first time and the ripple effect happens - the second time, the dropdown appears. Clicking on buttons in general requires two clicks. (ie. coming here to the github issues from the button in the top right required two clicks).

**Comment by FezVrasta** [comment]
should be fixed with d1c75c7 (:develop), please reopen this issue if is still bugged.

**Comment by jaddison** [comment]
@FezVrasta, what's the ETA for the next stable release?

**Comment by FezVrasta** [comment]
I've released today the 0.2.0

**Comment by chenop** [comment]
I encounter this problem on 0.2.0.
Couldnt identify d1c75c7 in 0.2.0 so i guess this fix was not included.

**Comment by FezVrasta** [comment]
The problem now affects only the first click, before it was ok every click. I'm fixing it

**Comment by tusharvikky** [comment]
I dont know if this is what you guys are discussion, but if you click any link in topbar the ripple is off focus. But as soon as you click any button on the document -or- search box (topbar) the ripple fixes and works fine.
