### ISSUE TITLE
Check in checkbox is tilted in iPhone

### ISSUE THREAD

**Issue by rougin** [mdbootstrap/mdb-ui-kit#24]
Hello! I'm trying this on iPhone 4s but then I saw that the check on the checkbox is tilted by some degrees. Also I found out that I cannot show a modal or cannot redirect from another page once I click a link or a button. I tried using it in Chrome and Safari.

**Comment by rougin** [comment]
Here is the screenshot.

![image](https://cloud.githubusercontent.com/assets/6078637/4331602/b8d0a552-3fc7-11e4-9cc6-739a327392c7.png)

**Comment by FezVrasta** [comment]
I've not already tested it on mobile devices, probably adding some vendor prefix would fix it.

**Comment by rougin** [comment]
What do you mean vendor prefix? Sorry for asking about that.

**Comment by FezVrasta** [comment]
for example a class like this:

```
.check {
    transform: rotate(90deg);
}
```

should become:

```
.check {
  -webkit-transform: rotate(90deg);
  -moz-transform: rotate(90deg);
  transform: rotate(90deg);
}
```

**Comment by FezVrasta** [comment]
This problem should be fixed with 8583cad3ec4422d1e449e12473e2a4c256d248dd, may you let me know?

**Comment by rougin** [comment]
The result is this.
![image](https://cloud.githubusercontent.com/assets/6078637/4331957/1c02c61e-3fcd-11e4-88c1-b0f99f7b3f60.png)

**Comment by FezVrasta** [comment]
at least something now rotates ;)

may you try to test this page on iphone?

http://codepen.io/FezVrasta/full/zpGve

does it looks okay?

**Comment by rougin** [comment]
It is now align with that link you provided. :+1:

**Comment by FezVrasta** [comment]
so is it fixed? Or just my link works?

The problem with iPhone specific troubles is that I can't really test them by myself, I've not an iPhone. Even for safari specific problems I had problems but I've installed a virtual machine to solve this..

**Comment by rougin** [comment]
Here is the screenshot. It is fixed for me i think :smile: 
![image](https://cloud.githubusercontent.com/assets/6078637/4332416/994073a0-3fd3-11e4-9536-a20ffc8c206b.png)

**Comment by FezVrasta** [comment]
I was just testing if the -webkit-transform: rotate() was working properly, seems so..

No idea why the rotation is not correct on iPhone, I should have an iPhone to test it with some debugging tool... unfortunately I've not one. Feel free anyone to try to fix it, I'm open to PRs.
