### ISSUE TITLE
Radiobutton & bootstrapValidator 

### ISSUE THREAD

**Issue by faebuk** [mdbootstrap/mdb-ui-kit#240]
Hey there

I'm currently using your material design theme. I'm doing a registration form and validating it with "bootstrapValidator". 

Now, if I dont use your material-design (without css etc), the validation of the radiobutton works.

Now if I'm using your material design with bootstrapValidator, and trying to validate radiobuttons, it doesn't work. The other fields (text, email etc) works fine, but the radiobutton doesn't validate.
Here is the fiddle: 
http://jsfiddle.net/ckL3zqaz/2/

if you need the whole code, just write. :)

Greeting
faebuk

**Comment by FezVrasta** [comment]
I don't know how the BootstrapValidator works... you should ask to the developer of this tool how ti handles radios and then understand why it fails with my radios...

**Comment by FezVrasta** [comment]
Reading the issues list seems like Bootstrap Validator is quite bugged... Probably it's just another bug of it, closing this issue until someone proof that is a fault of this theme.

**Comment by nghuuphuoc** [comment]
@faebuk 
It's not issue of Bootstrap Material Design. I gave the working example here http://jsfiddle.net/ckL3zqaz/4/
