### ISSUE TITLE
Left Nav

### ISSUE THREAD

**Issue by soygul** [mdbootstrap/mdb-ui-kit#241]
React material ui's left nav looks really cool and is mobile friendly (http://material-ui.com/#/components/left-nav). It could be a nice idea to backport it. Reporting this as a future idea.

**Comment by FezVrasta** [comment]
actually this theme is just "a theme"... so is not in its goals to provide these kind of components.

a jquery script could be written to add this feature, and then this theme could support it with a specific style to it.

**Comment by soygul** [comment]
True actually. I would say this should be more like a Bootstrap feature but it doesn't specifically try and implement Material Design specs so might be invalid for it too.
