### ISSUE TITLE
Win 8.1, Safari 5.1.7 Buttons don't click first time

### ISSUE THREAD

**Issue by d668** [mdbootstrap/mdb-ui-kit#242]
Both stable version demo https://fezvrasta.github.io/bootstrap-material-design/ and dev branch the same - on  Safari 5.1.7 dropdown doesn't open on the first click and l think urls don't work on the first click. URLs not confirmed

**Comment by FezVrasta** [comment]
Safari 5 is very old... you may want to update it to the most recent version.

**Comment by d668** [comment]
it is latest http://support.apple.com/downloads/#safari Safari 5.1.7 for
Windows

**Comment by FezVrasta** [comment]
Safari on Windows was discontinued, this means that nobody should use it anymore because it doesn't get security updates and new features.
