### ISSUE TITLE
Including styles in less (ext)

### ISSUE THREAD

**Issue by Rodeveer** [mdbootstrap/mdb-ui-kit#243]
Is there an option to include the styles in your own less files and it still keeps working?
I tried once to include it but because I don't got the 'fonts' folder in '../' the fonts didn't work properly.

This way you can add button styles to non-accessible elements. (This happens a lot in Wordpress widgets/themes, or even other CMS's)

**Comment by FezVrasta** [comment]
the fonts folder is configurabile editing the _variables.less file, could it solve the problem?

**Comment by Rodeveer** [comment]
That can fix the issue. But have to change it every time there 's update.
Maybe possible to define that variable in your own less files?

**Comment by FezVrasta** [comment]
I'm not so skilled in LESS... if you have some idea to let people overwrite the variables it would be nice.

**Comment by FezVrasta** [comment]
You can override variables with the example provided in the README.md
