### ISSUE TITLE
Android 4.4.2 + PhoneGap requires two separate clicks on links

### ISSUE THREAD

**Issue by d668** [mdbootstrap/mdb-ui-kit#244]
if I comment the line 
$.material.ripples();
and redeploy, all works OK

**Comment by FezVrasta** [comment]
Try out the develop branch

**Comment by d668** [comment]
i was using dev branch that you gave me

**Comment by FezVrasta** [comment]
does it happens even on the stock android browser?

**Comment by FezVrasta** [comment]
should be fixed with d1c75c7 (:develop), please reopen this issue if is still bugged.
