### ISSUE TITLE
new demo page

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#245]
Here a link (it's not yet finished) of the new demo page of this project:

https://rawgit.com/FezVrasta/bootstrap-material-design/develop/index.html

it's a clone of the [Polymer Project demo](http://www.polymer-project.org/components/paper-elements/demo.html), if you find bugs or have any suggestion please post it here.

_note that my demo has the scrolling with mousewheel working and the Google's one not, duh!_

**Comment by legart** [comment]
Very sexy! I am missing the button to quickly view the HTML for the given demo.

**Comment by FezVrasta** [comment]
I'll add it, I've just not implemented it yet

**Comment by alessiodionisi** [comment]
On Mozilla Firefox (Ubuntu) i need to double click the items on left menu :(

**Comment by FezVrasta** [comment]
It's a bug with the new ripples.js, I've to fix it

**Comment by xavadu** [comment]
also in Opera, one, two or more click isn't working

**Comment by FezVrasta** [comment]
should be fixed with d1c75c7321b1f4b7428ddc45599a7f1240229014

**Comment by xavadu** [comment]
tested in the latest version of Chrome, Chromium, Opera and Firefox for Linux and it is working.

Thanks.

**Comment by FezVrasta** [comment]
yuppi :D

**Comment by FezVrasta** [comment]
landed in the latest stable release.

**Comment by wopian** [comment]
You're missing the icon font list, unless that's the `Icon Button (To do)`?

Colour [variations](https://github.com/FezVrasta/bootstrap-material-design#variations) should probably have a tab with (a few/list of) examples too.

**Comment by FezVrasta** [comment]
We are reworking the variations engine. I'll add them to the demo after it's ready.

About the icons, I'll add them soon.

**Comment by wopian** [comment]
:+1:
