### ISSUE TITLE
Using arrive and template based modal causing performance leak

### ISSUE THREAD

**Issue by Xeevis** [mdbootstrap/mdb-ui-kit#246]
I'm trying to apply ripple to inputs in a modal window that gets created from a JS template using http://angular-ui.github.io/bootstrap/#/modal

I've included arrive as instructed and styling works ... but if I open and close the modal couple times without refreshing the page, it gets slower and slower and on 5th modal open browser freezes and starts warning about unresponsive script. If I exclude this line from **material.js** performance hog is gone but modal doesn't get the styling.

```
if (document.arrive) {
    document.arrive("input, textarea, select", function() {
        $.material.init();
    });
}
```

I don't have much experience with JS so hopefully someone understands what can be possibly causing this performance leak problem?

**Comment by FezVrasta** [comment]
You may insert already the markup needed by this theme instead of ask the script to generate it for you

**Comment by FezVrasta** [comment]
Or you may manually init the elements when the modal pops in
