### ISSUE TITLE
Toggle button

### ISSUE THREAD

**Issue by mschipperheyn** [mdbootstrap/mdb-ui-kit#248]
You have the slider but you don't have the slide / checkbox yet.

**Comment by FezVrasta** [comment]
do you mean the toggle button?

**Comment by mschipperheyn** [comment]
yeah, that one. This one is a pretty good template
https://github.com/twbs/ratchet/blob/master/js/toggles.js

**Comment by FezVrasta** [comment]
implemented with 84ff024

**Comment by FezVrasta** [comment]
Prototype here:

http://codepen.io/FezVrasta/full/raOWVw/

**Comment by yoonjechoi** [comment]
Hi @FezVrasta .
In the latest commit of the master branch, the color of the toggle button is not changed.
The codepen link above works well but the code from the github doesn't.
The toggle button on the https://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html 
doesn't alter color, too.

Would you check it please?

**Comment by rosskevin** [comment]
Please open a new issue with a new codepen test case and link to this issue,  this issue has been closed for one year and is untracked with the exception of the email notification I received
