### ISSUE TITLE
Checkbox not working

### ISSUE THREAD

**Issue by nospoon** [mdbootstrap/mdb-ui-kit#249]
I'm not entirely sure this is an actual issue or am I just doing something wrong.

I have the following standard code:

```
<div class="checkbox">
    <label for="remember">
       <input name="remember" type="checkbox"> Remember
    </label>
</div>
```

The checkbox square is showing, but it's not reacting to click.
I have the javascript included and initialized.
I'm using the development branch.

**Comment by FezVrasta** [comment]
May you provide a demo codependent?

**Comment by nospoon** [comment]
http://codepen.io/anon/pen/VYvYMy

Please note I'm also using the same resources from CDN as provided in this example.

**Comment by nospoon** [comment]
I've also noticed just now that dropdowns and navbar toggle also doesn't seem to work, even using code blocks copied from examples. 

EDIT:
Please ignore this one, it was an issue with bootstrap js i was using.

**Comment by wopian** [comment]
The `for` attribute looks up the `id`, not the `name` attribute.

http://codepen.io/Wopian/pen/WbQGEW
