### ISSUE TITLE
Whats the point of the gem?

### ISSUE THREAD

**Issue by noctivityinc** [mdbootstrap/mdb-ui-kit#250]
Maybe I'm missing something here but I don't see the point of the gem if I need to download and install all of the css, fonts, js and images anyway.

I installed the gem but no references to the stylesheets are found.  Perhaps the README is out of date.

Can someone explain to me how to go about getting this up and running on a Rails 4 project running the latest version of BS?

**Comment by FezVrasta** [comment]
The gem Is not maintained by me, probably is out dated

**Comment by FezVrasta** [comment]
removed the gem from the readme
