### ISSUE TITLE
Input field text disappears on focus

### ISSUE THREAD

**Issue by wethecode** [mdbootstrap/mdb-ui-kit#253]
Since 2.0 when I focus on an input field (text, email, password, etc) the text disappears (also while I'm typing). When the field is out of focus the text reappears. It's interesting because in this demo it seems ok: http://fezvrasta.github.io/bootstrap-material-design/#input, but in this demo the issue is existing: http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

(OSX Yosemite, Chrome, Safari, Firefox)

**Comment by FezVrasta** [comment]
I can't reproduce this problem.

May you try to create a fiddle using codepen.io (http://codepen.io/FezVrasta/pen/ihmea)?

Also, try to open the dev tools (F12) when you are in the page with the problem and paste here any javascript error log.

Thanks!

**Comment by donnyv** [comment]
Yup, its happening to me too. During the focus event color is set to transparent. The css is in the material-wfont.min.css file.

Using bootstrap-material-design: v0.2.0
Chrome v39.0.2171.62 beta-m

**Comment by Koslun** [comment]
Same here. Reproduced this bug on latest Chrome, Firefox, Safari and Opera on OS X Yosemite as well as latest Firefox on Ubuntu v14.0.4.

**Comment by FezVrasta** [comment]
I'll try to fix this problem tomorrow.

**Comment by donnyv** [comment]
Windows 7

**Comment by wethecode** [comment]
@FezVrasta There is no error in the console. 

Btw the pen you linked won't work as expected because the external CSS and JS files are not exists (for example: https://rawgit.com/FezVrasta/bootstrap-material-design/master/dist/css/material-wfont.min.css) or rawgit.com is down.

Thank you.

**Comment by guymguym** [comment]
I see it comes from a rule on material.less:

```
// Prevent highlight on mobile
* {
  -webkit-tap-highlight-color: rgba(255, 255, 255, 0);
  -webkit-tap-highlight-color: transparent;
  &:focus {
        outline: 0;
        border:none;
        color: rgba(0, 0, 0, 0);
  }
}
```

as a workaround I used an overriding rule which makes it visible:

```
*:focus {
  color: initial;
}
```

great project!

**Comment by FezVrasta** [comment]
okay I was probably drunk when I've written that line ^_^"

**Comment by davideschiera** [comment]
@FezVrasta Have you already scheduled a new release to include this fix? Do you know when it could happen? Thanks a lot!

**Comment by FezVrasta** [comment]
Should be the 0.2.1, I'll release it in some days, maybe tomorrow

**Comment by davideschiera** [comment]
Great, thanks!

**Comment by FezVrasta** [comment]
@davideschiera we are working to implement a new mixin to make available every material color to any element of this theme.  
After we'll have finished this I'll release the 0.2.1.

It should take just one day or two.

**Comment by davideschiera** [comment]
Cool, thanks! FWIW I'm currently using master at commit 908c0ec80b2882be0646a7f5d2f78e5269a9f591 and everything seems to work perfectly.
