### ISSUE TITLE
Have to click buttons twice to register click in Firefox v34.0

### ISSUE THREAD

**Issue by donnyv** [mdbootstrap/mdb-ui-kit#257]
If you go to http://fezvrasta.github.io/bootstrap-material-design using Firefox v34.0. You will have to click any of the buttons on the left hand side twice before they work. I'm running across the same issue with my project.

**Comment by FezVrasta** [comment]
The problem was almost fixed with a previous commit, now looks like it happens only on the first click on any element.

Am I right?

**Comment by donnyv** [comment]
yes

**Comment by FezVrasta** [comment]
high priority to this bug, will fix it asap.

**Comment by donnyv** [comment]
Thanks!

**Comment by FezVrasta** [comment]
Not sure why, but now everything works... I've just recompiled the CSS.

Can you confirm?

**Comment by donnyv** [comment]
Yup, works now! Thanks!

**Comment by donnyv** [comment]
It was the ripples.css file.
On line 13 you had "pointer-events : none"

**Comment by FezVrasta** [comment]
but pointer-events none is still there :\

https://github.com/FezVrasta/bootstrap-material-design/blob/master/dist/css/ripples.css#L13

**Comment by donnyv** [comment]
Sorry I mean to say you "didn't" have "pointer-events : none"

**Comment by FezVrasta** [comment]
ah oke :)
