### ISSUE TITLE
Panel primary color little mistake

### ISSUE THREAD

**Issue by roxteddy** [mdbootstrap/mdb-ui-kit#258]
Hi !

Since primary color changed, the panel kept a thin line of the previous color on the bottom of the header.

Cheers
RoxTeddy

**Comment by FezVrasta** [comment]
Sorry I can't find the problem... may you provide a screenshot?

**Comment by roxteddy** [comment]
Sorry for the delay. Here's the problem and the html code. Maybe its my bad but I cant figure out..

![screen shot 2014-12-08 at 10 55 36](https://cloud.githubusercontent.com/assets/6069870/5337459/179051a6-7ec9-11e4-8586-80527d10d965.png)
![screen shot 2014-12-08 at 10 57 30](https://cloud.githubusercontent.com/assets/6069870/5337461/1a1b0132-7ec9-11e4-988b-838985c2962d.png)

**Comment by roxteddy** [comment]
I'm also posting a screenshot from your own example. I'm using Chrome 39.0.2171.71 (64-bit) on MacOS X 10.9.3 (but it is the same on Firefox and Safari).

can you see the blue line below the primary color header ? It is very thin.

![screen shot 2014-12-08 at 13 04 19](https://cloud.githubusercontent.com/assets/6069870/5338991/ecb282bc-7eda-11e4-93cc-bccb0f9c73aa.png)

**Comment by FezVrasta** [comment]
ah yea I see
