### ISSUE TITLE
Ripple effect not working on IE11 and the buttons have a weird divider.

### ISSUE THREAD

**Issue by TheGreenGentleman** [mdbootstrap/mdb-ui-kit#261]
Hi,

First of all,what you're doing here is amazing. I'm using it on my site and more likely my whole team will be on board as well. Again, good job.

Regarding the issue I encountered, here is a screen grab of what I'm getting when I hover on every buttons:

![button](https://cloud.githubusercontent.com/assets/10061484/5280992/4ac03d7c-7ac6-11e4-8328-badcb10a710e.PNG)

I encounter this on all my browsers.

Also, the ripple effect is not working on IE11. But on Google Chrome and Mozilla it's working well.

Note: 
All I got from your CDN is the CSS and JS of Material and Ripple. Should I include the fonts for this to work?

**Comment by FezVrasta** [comment]
Fonts are provided by Google Fonts.

Please provide a complete example of your code so I can find the problem (codepen.io)

**Comment by ianfreemonkey** [comment]
Fez your framework rocks, kudos
IE 9 fails on rendering the page
CodePen: http://codepen.io/Ianfreemonkey/pen/bNVzrd
Live: http://www.ctslanguagelink.com/material/index.html

What would you suggest to fix the rendering issue? 
Overall, do you have any suggestions looking at the code for IE or to optimize the code?

**Comment by FezVrasta** [comment]
I've tested it with IE9-10-11 and everything looks good. What's the problem? May you provide a screenshot?

By the way, please, open a different **issue**. Thanks.

**Comment by FezVrasta** [comment]
@TheGreenGentleman: the ripple effect is working on IE10 and IE11.

On IE9 it does not work because I use CSS transitions to animate the ripple and IE9 does not support CSS transitions. I think I can add a fallback mode.

**Comment by FezVrasta** [comment]
The ripple now should work even on IE9.

About the problem with your button, I'm still waiting a demo to check the problem.

**Comment by FezVrasta** [comment]
your problems may be caused by the compat mode of IE that turns on and make your IE11 act like an IE8. Please be sure to have it disabled.
