### ISSUE TITLE
form issue with uiRouter 

### ISSUE THREAD

**Issue by workspacerg** [mdbootstrap/mdb-ui-kit#263]
Hi, Thanks for your work.

I have some trouble with the formulaire, i want to use it in view using ui router.
Unfortunately, this one don't work normally. there is no effect, in addition some elements don't appear as the checkbox.

![capture d ecran 2014-12-03 a 23 04 27](https://cloud.githubusercontent.com/assets/4296421/5289873/40c3deba-7b42-11e4-8bf5-e255ea40e3ea.png)

By sample this code works fine out of the view but don't in the view: 

![capture d ecran 2014-12-03 a 23 19 56](https://cloud.githubusercontent.com/assets/4296421/5289953/f432a238-7b42-11e4-9f3b-4ce2b7821cda.png)

Thank's for your work

**Comment by FezVrasta** [comment]
you have probably to init the elements, should be enough run `$.material.init()` after you load the view.
