### ISSUE TITLE
Optionally disable Detect autofill in $.material.init()

### ISSUE THREAD

**Issue by macrozone** [mdbootstrap/mdb-ui-kit#264]
Hi,
I noticed that $.material.init() breaks a drag&drop file-field, that I used in a project (https://github.com/aldeed/meteor-cfs-autoform). 

The reason is, that $.material.init() sends change events to every input when a focus event occures on any input. The package above that i used will listen to this events and break, because it is not a drag&drop event and therefore has no .originalEvent property. (This is of course a problem of the package above)

Calling each of $.material.ripples(), $.material.input(), $.material.checkbox(), $.material.togglebutton(), $.material.radio()
fixes the issue, because the "Detect autofill" part is only done in $.material.init()

so two questions:
- Maybe, the "detect autofill"-Function could be disabled per option?
- add another function $.material.autofill()

Thank you for the good work, the design is great :-)

**Comment by FezVrasta** [comment]
Thank you, I've added some options to choose what enabled with .init() and what not.

You should be able to run:

```
$.material.options.autofill = false;
$.material.init();
```
