### ISSUE TITLE
Checkbox element unavailable under android 4.4.3 webview

### ISSUE THREAD

**Issue by beata** [mdbootstrap/mdb-ui-kit#265]
The hint circle keeps flashing and when clicked on the checkbox input, the status won't change.

**Comment by FezVrasta** [comment]
Currently mobile is not very supported, I'm open to PR to fix bugs related to mobile issues.

**Comment by pedramN** [comment]
Let me know if I can help anyway with the mobile version. Be specific as possible because I’m mainly a backend guy whose willing to get his hands dirty out on friend out of necessity. By the way excellent work, hats off to you!!

**Comment by FezVrasta** [comment]
Hey, thanks.

This is the file about checkboxes:
https://github.com/FezVrasta/bootstrap-material-design/blob/master/less/_checkboxes.less

There is a little Javascript to make the checkboxes working:
https://github.com/FezVrasta/bootstrap-material-design/blob/master/scripts/material.js#L46-L52
https://github.com/FezVrasta/bootstrap-material-design/blob/master/scripts/material.js#L102

Probably the L102 is the one that causes the flashing (it's really an horrible trick and I would like to remove it).

**Comment by tuxedo1** [comment]
Is there a solution yet for this bug? Works great on Desktop, just unfortunate that this is happening for me on Android (4.2.2).

**Comment by FezVrasta** [comment]
not yet... I've still to look into this. By the way the problem is at 99% [this row](https://github.com/FezVrasta/bootstrap-material-design/blob/master/scripts/material.js#L106)

**Comment by joshuadiezmo** [comment]
the bug is in android web browser lower version

**Comment by rosskevin** [comment]
Please check the latest version http://fezvrasta.github.io/bootstrap-material-design/#checkbox

If this is still present, please reopen stating the Android OS versions with which it can be reproduced.  Thank you.
