### ISSUE TITLE
Performance and possible memory leak when dom node is removed and added back in.

### ISSUE THREAD

**Issue by donnyv** [mdbootstrap/mdb-ui-kit#267]
I'm using RactiveJS to do all the templating and binding in my project. I have a simple template to hide and show 2 panels. I use tabs with click event to show or hide them. The more times I go back and fourth the slower the div's render. Eventually the browser crashes. I'v used Bootstrap before with RactiveJS with no problems. So there's something definitely going on with material design.

This code sits inside of a modal-dialog.

```
         <ul class="nav nav-pills">
                <li class="{{#tab == 1}}active{{/}}"><a on-click="user-profile" href="javascript:void(0)">Profile</a></li>
                <li class="{{#tab == 2}}active{{/}}"><a on-click="user-account" href="javascript:void(0)">Account</a></li>
            </ul>
           {{#tab == 1}}
            <div class="user-profile" >
                <div class="form-group">
                    <label for="name">Full name</label>
                    <input id="user-fullname" name="name" type="text" value="{{formData.FullName}}"
                           required
                           data-parsley-errors-messages-disabled
                           data-toggle="popover"
                           data-placement="top"
                           class="form-control"
                           placeholder="e.g. Don Smith"
                           autocomplete="off">
                </div>
                <div class="form-group">
                    <label for="email">Email</label><br />
                    <input id="email" type="email" value="{{formData.Email}}"
                           required data-parsley-errors-messages-disabled
                           class="form-control"
                           placeholder="e.g. dsmit@email.com"
                           autocomplete="off">
                </div>
            </div>
            {{/}}
            {{#tab == 2}}
            <div class="user-account" >
                <div class="form-group">
                    <label for="username">Username</label>
                    <input id="username" name="username" type="text" value="{{formData.username}}"
                           required
                           data-parsley-errors-messages-disabled
                           data-toggle="popover"
                           data-placement="top"
                           class="form-control"
                           placeholder="e.g. dsmit"
                           autocomplete="off">
                </div>
                <div class="form-group">
                    <label for="new-password">New Password</label>
                    <input id="new-password" name="new-password" type="text" value="{{formData.new_password}}"
                           required
                           data-parsley-errors-messages-disabled
                           data-toggle="popover"
                           data-placement="top"
                           class="form-control"
                           placeholder="e.g. ********"
                           autocomplete="off">
                </div>
            </div>
            {{/}}
```

**Comment by FezVrasta** [comment]
Please may you provide a codepen so that I can investigate?

**Comment by guymguym** [comment]
the same also happened to me, though with angular.js in my case.
after several times of opening & closing a custom modal with a form inside (with floating labels), in my case the modal is created and disposes its DOM elements on each display, which made me suspect this is related to arrive.js...
but I don't have a simple code to reproduce yet.

**Comment by FezVrasta** [comment]
Have you tried the latest version? I've improved the performances

**Comment by guymguym** [comment]
@FezVrasta yes latest version (0.2.0) is still the same.

here is the simplest reproduction I could write with angular's ng-if:
http://codepen.io/anon/pen/EaPLXj?editors=101

press the button 1,2,3 times and you'll immediately notice (at least on chrome) how ripples are becoming whiter, response is slower and then gets completely stuck with 100% cpu.

**Comment by guymguym** [comment]
btw it seems that the problem becomes much worse the more fields there are in the form.
I updated the form to have just 1 field so it's easier to see the progression, but if you duplicate that input field 10 times you will see it happening after just 1-2 toggles.

also replaced the arrive.js script to the non minified version, so it will be possible to debug.

**Comment by FezVrasta** [comment]
Thanks, I'll try to fix the problem

**Comment by FezVrasta** [comment]
Looks like a problem of Arrive.js, continue in the referenced issue please.

**Comment by FezVrasta** [comment]
Looks like you were using an old version in the demo.

http://codepen.io/FezVrasta/pen/ogzBOm

with the latest one everything works great.
