### ISSUE TITLE
input file on change event 

### ISSUE THREAD

**Issue by tinquang** [mdbootstrap/mdb-ui-kit#270]
I have an input type file with change event to show the image when user select it from computer, somehow my custom change event for that input trigger dozen of times after user selected their image. I think because of your trigger and setinterval, is there anyway to avoid this loop ?

Thanks

**Comment by FezVrasta** [comment]
With the latest version you can disable it with

```
$.material.options.autofill = false
```

**Comment by tinquang** [comment]
thanks for your quick response, but I tried with your lastest version (0.2.0) and my problem still the same,when I exclude material.min.js it back to normal. Do you have any idea ?

Thanks.

**Comment by tinquang** [comment]
Sorry, when I upgrade using bower install, bower file content shows version 0.2.0 but I check source code of material.js, the source does not have option autofill, so I try again by download directly from github and it works now. Thanks.
