### ISSUE TITLE
form validation rendering

### ISSUE THREAD

**Issue by mschipperheyn** [mdbootstrap/mdb-ui-kit#273]
I noticed that when you render a form validation has-error, has-warning etc, the label is coloured and the underline of the form element isn't. The material design guidelines seem to point to the reverse approach. Changing the colour of the underline and having a validation error message in the same colour and leaving the label in the original colour.

**Comment by FezVrasta** [comment]
Thanks, I'm going to rewrite the color variations soon, then I'll fix this

**Comment by FezVrasta** [comment]
it should be fixed in the latest releases
