### ISSUE TITLE
Input with float label doesn't work in IE9

### ISSUE THREAD

**Issue by DuskoV** [mdbootstrap/mdb-ui-kit#276]
On the demo:
http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

it's impossible to enter text in text box with float label (in Forms section, first box on the right). Input doesn't get even focus when clicked on it).

This is in IE9. All other elements in IE9 sems to work great!

**Comment by kylerberry** [comment]
@FezVrasta has it been decided to have default input/label functionality in IE9? I'm testing and see that the inputs work as they should just without floating labels.

**Comment by FezVrasta** [comment]
Sorry had no time yet to look into this

**Comment by rosskevin** [comment]
0.4.1 changed floating labels a bit.  Please check and reopen if needed.

> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
