### ISSUE TITLE
Back button unresponsive on demo page

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#277]

**Comment by GradyD** [comment]
Can you provide some details on this one? I tried to duplicate but could not figure out what you are referring to.

Thanks!

**Comment by FezVrasta** [comment]
if you click the "back button" of your browser, the page doesn't change. It should move you to the previous visited page instead.

**Comment by rosskevin** [comment]
Will be solved in #728
