### ISSUE TITLE
Wells should be... wells

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#279]
> A well is a container <div> that causes the content to appear sunken or an inset effect on the page. To create a well, simply wrap the content that you would like to appear in the well with a <div> containing the class of .well.

Probably well should be replaced by just a simple panel...

**Comment by caseahr** [comment]
I completely agree.  Material design seems to dictate no sunken objects.

**Comment by FezVrasta** [comment]
Right :/

**Comment by rosskevin** [comment]
Note: Wells and panels were dropped in v4

http://v4-alpha.getbootstrap.com/migration/#panels-thumbnails-and-wells
