### ISSUE TITLE
Number validation label overlays input value

### ISSUE THREAD

**Issue by jamime** [mdbootstrap/mdb-ui-kit#281]
When using the number input the label overlays the input value on the [demo](http://fezvrasta.github.io/bootstrap-material-design/#input) when you enter a text value.

**Steps to reproduce:**
- Visit the [demo](http://fezvrasta.github.io/bootstrap-material-design/#input).
- Enter a text value into the 'Validation' number field

**Result:**
- On key up the label will overlay the input
- On key down the label will be in the correct position above the input

**Expected:**
- On key up the label should be in the correct position above the input

**Browser:** Google Chrome Version 39.0.2171.71 (64-bit) (OSX)

![2014-12-10 170739 00001](https://cloud.githubusercontent.com/assets/2328042/5380324/1ac3acc0-808f-11e4-99e0-9bc060d34adf.png)

**Comment by kylerberry** [comment]
@jamime @FezVrasta I'm working on this now. It's not possible to get the value of a number-input in Chrome if it isn't numeric, which is how the 'empty' class is being added/removed in other inputs.

I suggest we either limit input to numbers only OR swap type="number" for type="tel"

**Comment by FezVrasta** [comment]
I think :invalid could be a solution

**Comment by kylerberry** [comment]
@FezVrasta the validation works correctly. It's the floating label logic that won't work with type="number"

**Comment by FezVrasta** [comment]
yes I was talking about it, if the label goes down when the validation fails (letters instead of numbers), then :invalid can help probably.

**Comment by kylerberry** [comment]
@FezVrasta Ah I gotcha. Lemme give that some looksee

**Comment by kylerberry** [comment]
https://github.com/FezVrasta/bootstrap-material-design/pull/285

**Comment by kylerberry** [comment]
@FezVrasta @jamime please close this issue.
