### ISSUE TITLE
$.material.init() is somehow interfering with input on change

### ISSUE THREAD

**Issue by ArdianPerlaska** [mdbootstrap/mdb-ui-kit#284]
Hello guys,

I'm using your framework for a site. But somehow $.material.init() is interfering with input on change (.change() jquery). And is affecting to return the same file n times (it takes up to 80 times), and this is causing a File Uploader to break, because of multiple times loading one file.

Congrats on the elements, you did an awesome work.

Looking forward for help.

Regards,
Ardian.

**Comment by FezVrasta** [comment]
```
$.material.options.autofill = false
$.material.init();
```

**Comment by ArdianPerlaska** [comment]
Thanks a lot.
