### ISSUE TITLE
Possible ASP.NET support sometime?

### ISSUE THREAD

**Issue by Bodokh** [mdbootstrap/mdb-ui-kit#286]
Buttons for example do work with the material theme, but not the ripple. I assume the style is targeted to specific button element. Would love an option to enable ripple effects for button controls which are not standard:
<Telerik:RadButton
<asp:Button
and so on...

Edit:
I have detected the source of the issue, ripples only work on button elements. ASP.NET buttons are rendered as an input type=button, not buttone elements. It would be nice for ripple support for the Input type=button element.

**Comment by FezVrasta** [comment]
oh well...
actually ASP.NET is something really bad... I would suggest you to switch to something else, even Pascal is better.

Talking about your problem. Ripples.js works adding some elements inside the button tag.
`<input type=button>` is a self closing element and cannot contain anything, so... you should wrap the button inside a `<div>` and apply to it ripples.js

**Comment by Bodokh** [comment]
Thank you FerVrasta. By the way, you are a smart peron, and as a smart person you should know that calling a framework like asp.net bad is pretty stupid. Each framework/language has its benefits and its downfalls. I could bet you anything you want that what you code in 6 hours with php i do with 2 hours of asp.net. 

Either way, Thanks again.

**Comment by FezVrasta** [comment]
omg.. PHP vs ASP.NET, not sure which is worse :stuck_out_tongue: 
Unfortunately I've worked years on Microsoft_based companies and I've always seen horrible code with ASP.NET, VB, etc... 

By the way this issue looks like a good example. Can't you just tell ASP.NET to use `<button>` instead of `<input>`? If it is so awesome I think it will not be a problem ;)

**Comment by Bodokh** [comment]
I'm afraid its not currently possible :( , Hopefully in the future. And i don't know what you have against php and asp.net? ASP.NET is great, and if you use it with MVC then is supreme. it's easy and fast coding! Either way I absolutely love your Material Design, You did a very good job, but there are still a lot of issues with rtl websites, Checkboxes, textboxes and other stuff don't behave well, even when i use Bootstrap RTL.

**Comment by FezVrasta** [comment]
I've never used an RTL website (I'm Italian) and for me is something obscure, please feel free to open issues about these problems. I'd like to fix them. Just be sure to attach a codepen so I can see it live.

PHP leads to spaghetti code a gogo, ASP.NET has some horrible things, for example you have to compile it.. it has not so good performances, it needs Microsoft sh*t and so on... By the way it's just my opinion.

There are thousands of websites built with ASP.NET that work well (I've never seen one but I'm sure there are some) and I'm sure there are PHP websites written with good patterns (except for Laravel based I think there aren't though).

**Comment by Bodokh** [comment]
Well, everyone is entitled to their own opinion. And what do you use for server side?

**Comment by caseahr** [comment]
@Bodokh - Perhaps you could use the old UseSubmitBehavior="false" trick, which renders an asp:Button as a button.

**Comment by FezVrasta** [comment]
@Bodokh I usually use JavaScript for server side.

@caseahr thanks :)

**Comment by Bodokh** [comment]
Javascript is not a server side language. You can perform ajax requests but as far as i know it is not a server side language.

@caseahr  Thank you i will give it a try

**Comment by FezVrasta** [comment]
@Bodokh I think you are not updated :stuck_out_tongue_closed_eyes: 

http://nodejs.org/

**Comment by Bodokh** [comment]
@FezVrasta Well why didn't you say so! This makes more sense.

**Comment by FezVrasta** [comment]
Umh? It's JavaScript, I've said it.

**Comment by Bodokh** [comment]
@FezVrasta Yes it is, but i did not think of node.js, i just thought as javascript plainly

**Comment by FezVrasta** [comment]
okay, remember to open issues for the RTL bugs. Thanks!

**Comment by caseahr** [comment]
@Bodokh - Please also consider making plain html buttons and calling server-side code via a .NET Web API Controller.  There's really not a good reason to create server-side click-events anymore, in my opinion.  Simply wire the button to an API call.  I program ASP.NET websites with zero server-side controls and AngularJS bindings.  The server-side code is for data calls and saves only.   Just my advice.  If your web app is modern enough to be using Material Design, you should rely more heavily on Javascript MVC for your user interactions -- especially button clicks.  Also, for Telerik, look into their KendoUI.

**Comment by FezVrasta** [comment]
I've not closed this issue because asp.net sucks.

**Comment by caseahr** [comment]
I don't think you should have to cater to ASP, but all you'd have to do is copy the styles for buttons and make them available to input[type=submit] and you'd be done with it.  :)  That's not really "supporting" sucky development, it's just allowing submit inputs to be styles with ripples and such.  Easy peasy.  (I promise I'll get up to speed next month and start contributing).

**Comment by FezVrasta** [comment]
The ripple effect can't be applied to self closing elements

**Comment by caseahr** [comment]
Oh, well, then... Like I said earlier... Just because you're programming in ASP does not mean you have to use ASP buttons. Get over it... 😊 

-----Original Message-----
