### ISSUE TITLE
variations error

### ISSUE THREAD

**Issue by mrroot5** [mdbootstrap/mdb-ui-kit#287]
Hello,

At variations I see a documentation issue.
In the example change this:

```
<button class="btn btn-material-deeppurple">Deep purple button</button>
```

for this:

```
<button class="btn btn-material-deep-purple">Deep purple button</button>
```

Regards.

**Comment by FezVrasta** [comment]
actually this is a change introduced recently and not yet released (it's still in master). Keep it as a memo for when I'll release the whole thing.

**Comment by mrroot5** [comment]
Ok, thanks :).

**Comment by FezVrasta** [comment]
fixed
