### ISSUE TITLE
There are any way to choose the default theme color?

### ISSUE THREAD

**Issue by luanfonceca** [mdbootstrap/mdb-ui-kit#288]
Hi folks, i just downloaded the code and put the css and js stuff on my master template, but all link texts, checkboxes and other elements are Green, there are any simple way to choose another color as default? An way which doesn't need that I put an class in each element.

Thanks and congrats for this project. o/

**Comment by FezVrasta** [comment]
Hi, you could create a less file in your less/ folder with:

```
@import "../bower_components/bootstrap-material-design/less/material-wfont.less";
@primary: @deep-purple;
```

This should override the primary color.

**Comment by luanfonceca** [comment]
Thanks for the quick answer. 

o/
