### ISSUE TITLE
Markup for dropdown menu

### ISSUE THREAD

**Issue by wezley98** [mdbootstrap/mdb-ui-kit#289]
I am trying to replicate this dropdown menu:

http://fezvrasta.github.io/bootstrap-material-design/#dropdown-menu

But the dropdown effect is not working with 0.2.1 is there a special class/data tag I need to apply?

```
<select class="form-control" name="task" style="width:200px;">
<option value="">Select Task</option>
<option value="1">test</option>
<option value="2">New task</option>
</select>
```

**Comment by FezVrasta** [comment]
You have to use dropdown.js, I thought it was mentioned, sorry

**Comment by wezley98** [comment]
Thanks that worked perfectly.
