### ISSUE TITLE
How does this theme work with Bootstrap's glyphicons?

### ISSUE THREAD

**Issue by dandv** [mdbootstrap/mdb-ui-kit#292]
Does it override them? Or does it work side-by-side?

If Bootstrap's glyphicons are not necessary when using the Material Design, then I can exclude them from the Bootstrap Meteor package on which the Meteor integration depends.

**Comment by FezVrasta** [comment]
It should work with it without problems... 

Actually those icons are really horrible and I've never tried them, but if they act like **FontAwesome** then everything should work just fine.

**Comment by dandv** [comment]
OK, so the recommendation is to exclude the Bootstrap icons (I agree they're kinda ugly) and use the Google ones, correct?

**Comment by FezVrasta** [comment]
actually there's not a reccomandation.

I'm waiting the official iconic font from Google https://github.com/google/material-design-icons/issues/1
My implementation has not lot of icons and some are bugged.
FontAwesome is not material.
Glyphicons are ugly...
