### ISSUE TITLE
.btn-default is white on white

### ISSUE THREAD

**Issue by ruiramos** [mdbootstrap/mdb-ui-kit#294]
.btn-default currently displays as white on white, on white backgrounds.

I'm guessing that's due to the changes in 0c12c1fc85653885f067a131414dd5318cb18845 on buttons.less, line 23, as you end up using the `contrast()` function in the background-variations mixin with transparent as a color (the default for `@btn-default`), thus getting white all the time - LESS' contrast with transparent always picks the lightest color not sure why.

Changing `@btn-default` to white solves this problem.

**Comment by FezVrasta** [comment]
Umh, will look into this bug, thanks!

**Comment by spapas** [comment]
I confirm this bug. Here's the output of `dist/test.html`:

![material-bug](https://cloud.githubusercontent.com/assets/3911074/5454162/f64cb29a-8536-11e4-80f9-18af7c75a2ff.png)

I'm not very familier with less but when I copied over `less/_buttons.less` from an older commit the white color of `btn-default` was changed again into black.

**Comment by FezVrasta** [comment]
we have added support for thousands of colors for each element, there's just a small bug with the transparent one. Will fix it soon.

**Comment by spapas** [comment]
@FezVrasta no problem, if people want to avoid this bug they can just use an older version. 

Thanks a lot for the really great work on bootstrap-material-design !

**Comment by FezVrasta** [comment]
The problems should be fixed now
