### ISSUE TITLE
Documentation for row-action

### ISSUE THREAD

**Issue by dandv** [mdbootstrap/mdb-ui-kit#296]
Is there some other documentation besides the README or reading through the large CSS files? I was looking for possible `row-action-` classes, and classes that mix with them, e.g. `checkbox`.

What I want to achieve is like [the "Tile with a label" example](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html), but with a square container/background for the primary action instead of a circle.

**Comment by FezVrasta** [comment]
Umh... actually there aren't "square" elements inside lists in Material Design specs, so I've not added them.

I see it could be useful but it's not really something related to material design (aka, the purpose of this framework) so probably would be better if you define your own class to achieve this.

I'm open to discussion.

**Comment by dandv** [comment]
OK, that was an example for my particular app, so I'll style it. But where can one find the documentation for classes like `row-action-`?

**Comment by FezVrasta** [comment]
I think it's not documented... Maybe there's some comment somewhere in the code but I'm not sure about it.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
