### ISSUE TITLE
Floating label does not work on auto filled input elements

### ISSUE THREAD

**Issue by mrijken** [mdbootstrap/mdb-ui-kit#297]
When a form is filled by ie a password manager, only the first floating label will be floated. The labels of the other input elements will be floated if I click somewhere on the page.

**Comment by FezVrasta** [comment]
probably is something related to my horrible trick to make autofills work...

**Comment by mrijken** [comment]
When I reload a page with F5, everything works OK. When I go to a page by clicking on a link, the floating labels will not work as expected. May be this will help you to find the cause.

**Comment by kmmbvnr** [comment]
That looks like common problem. Even fixes didn't works for me - http://tbosch.github.io/autofill-event/test/manual/login-form.html

this looks like nice description of the problem - https://github.com/tbosch/autofill-event/issues/12

And it sounds like browser issue.

**Comment by FezVrasta** [comment]
duplicate of #473
