### ISSUE TITLE
file component is not displaying correctly

### ISSUE THREAD

**Issue by sadhasivam** [mdbootstrap/mdb-ui-kit#299]
File Component is not displaying correctly.
e.g) 
<input id="id_settlement_file" name="settlement_file" type="file">
display blank by default. some CSS mismatch.

looks like position abs causing this.

.form-control-wrapper input[type=file] {
    opacity: 0;
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 100
}

**Comment by FezVrasta** [comment]
may you provide a pen to let me see the error?

**Comment by FezVrasta** [comment]
ping @sadhasivam

**Comment by FezVrasta** [comment]
sorry I need a live code, please use:

http://codepen.io/FezVrasta/pen/ihmea

**Comment by sadhasivam** [comment]
http://codepen.io/sadhasivam/pen/PwzKaK

Please let me know if this helps for you. for some reason i am not able to use ur LInk. so created mine and shared.

**Comment by FezVrasta** [comment]
the pen I've provided includes already all the CSS and JS needed by this theme. Please put in there only the HTML and the JS needed to reproduce the problem

Thanks.

**Comment by sadhasivam** [comment]
same thing happens in your pen as well.  when i refresh or share my contents (simple HTML) lost for you to view.  may be i am missing something.    

i again forked ur pen and just changed the HTML snippet to mine. http://codepen.io/sadhasivam/pen/ZYOREd

**Comment by FezVrasta** [comment]
You are using the wrong markup. Please read the documentation and show the code examples to use it correctly.
