### ISSUE TITLE
Floating action button

### ISSUE THREAD

**Issue by roeku** [mdbootstrap/mdb-ui-kit#3]
I've managed to make my own [Floating action button](http://www.google.com/design/spec/components/buttons.html#buttons-main-buttons) with some fiddling might be nice to have it ready for use in the theme?
![screenshot from 2014-09-05 00 37 49](https://cloud.githubusercontent.com/assets/7256461/4157940/dc00fc5a-3484-11e4-8fe7-946387d157b9.png)

custom Floating action css: 

```
  .share-wrapper {
        position: fixed;
        bottom: 15px;
        margin-left: -15px;
    }

    .share-dropdown-wrapper:hover {
        background: none;
    }

    .icon-material-share {
        border-radius: 100px;
        width: 62px;
        padding-left: 10px;
    }

    .share-ripple {
        border-radius: 100px;
    }
```

HTML: 

```
<div class="share-wrapper col-xs-1 col-xs-push-10">
   <a href="javascript:void(0)" style="background: none">
     <i class="icon icon-material-share btn btn-info btn-raised withripple" style="color: #03a9f4; background: rgba(255, 255, 255, 0.90); font-size: 30px; padding-left: 16px; padding-top: 14px; height: 60px;">
       <div class="share-ripple ripple-wrapper"></div>
       </i>
    </a>  
</div> 
```

It's not the most elegant way though.

**Comment by FezVrasta** [comment]
thank you, it was in my to do list 😁

**Comment by FezVrasta** [comment]
I've added FABs into the theme core, you can create a FAB with:

```
<a href="javascript:void(0)" class="btn btn-default btn-fab btn-raised icon-material-share"></a>
```

Checkout the demo for some examples. 
http://fezvrasta.github.io/bootstrap-material-design/#buttons

**Comment by divinaet** [comment]
Thanks a lot for this positionning solution, it makes my day !

**Comment by athmangude** [comment]
Thanks a lot for this one
