### ISSUE TITLE
dropdown mouseover do not highlight item

### ISSUE THREAD

**Issue by nvcken** [mdbootstrap/mdb-ui-kit#30]

**Comment by FezVrasta** [comment]
Why should it be highlighted?

**Comment by nvcken** [comment]
like this, why it should not?
![untitled](https://cloud.githubusercontent.com/assets/3489866/4436721/d908e838-477f-11e4-99ee-124826c19f0a.png)

**Comment by FezVrasta** [comment]
The polymer paper project has not hover effect (http://www.polymer-project.org/components/paper-elements/demo.html#paper-dropdown-menu).

But in the Google Material Design documentation it has an hover effect (http://www.google.com/design/spec/components/menus.html#menus-usage).

Probably it should have one so... Thanks for the report.
