### ISSUE TITLE
Panel background color is not white

### ISSUE THREAD

**Issue by jrood** [mdbootstrap/mdb-ui-kit#300]
The panel background color (for panel-default or any of the other) is grey rather than white.

**Comment by FezVrasta** [comment]
The panel background color is #FFFFFF so, white...

**Comment by gggauravgandhi** [comment]
I am facing same problem, here is jsFiddle : https://jsfiddle.net/ps3ohmL1/4/

Please help, thank you.

**Comment by SergeyKhval** [comment]
@gggauravgandhi, you need to include bootstrap.css along with bootstrap-material-design.css

**Comment by gggauravgandhi** [comment]
@SergeyKhval  Thanks for quick response, it worked.
I have one more problem : look here https://jsfiddle.net/t7L8qo5a/
Why button looks that weird ?

**Comment by gggauravgandhi** [comment]
@SergeyKhval Leave it, it was file order issues. Sometime you excited and lose basic senses.
Thanks for help.
