### ISSUE TITLE
Popover title, active color different from main, some icons are mapped bad

### ISSUE THREAD

**Issue by tasonface** [mdbootstrap/mdb-ui-kit#302]
1) Popover's title has a white background on its black layout when using `data-title="Title..."`.
This should be fixed. For now I'd suggest this workaround:

```
<a href="#" 
     data-toggle="popover" 
     data-html="true"
     data-content="<h3>Title...</h3>Vivamus sagittis lacus vel augue laoreet rutrum faucibus."
 ><a>
```

2) `<ul class="nav nav-pills nav-stacked">` with an active `<li>` inside has a default bootstrap's blue background. Other `<li>`s have green color on links. Probably different elements that support `active` class on them will have default bootstrap blue color.

3) I see many icons that have the same output while the code differs:

```
mdi-device-signal-wifi-0-bar
mdi-device-signal-wifi-1-bar
mdi-device-signal-wifi-{N}-bar
```

or

```
mdi-device-battery-20
mdi-device-battery-40
mdi-device-battery-60
```

**Comment by FezVrasta** [comment]
About the icons, it's a bug in the current iconic font. I'm waiting the official one from Google to fix these problems. 

About the popover... If you may provide a [pen](http://codepen.io) to reproduce the problem I can try to work to fix it.

**Comment by tasonface** [comment]
Sorry, this was my first post on github, didn't know that posts supported HTML format. I fixed my first post right now, it was already reproducing popover's issue.

Also..

4) `bg-primary` class and similar (`bg-warning`, `bg-info`, `bg-success`...) should have same background color of `btn-primary` and corresponding

**Comment by kuttiecc** [comment]
okay you can edit it

On 17 December 2014 at 08:48, tasonface notifications@github.com wrote:

> Sorry, this was my first post on github, didn't know that posts supported
> HTML format. I fixed my first post right now, it was already reproducing
> popover's issue.
> 
> Also..
> 
> 4) "bg-primary" class and similar (bg-warning, bg-info, bg-success...)
> should have same background color of "btn-primary" and corresponding
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FezVrasta/bootstrap-material-design/issues/302#issuecomment-67352375
> .

## 

Char

**Comment by kuttiecc** [comment]
hey, is there anyway I can call you and maybe together we can figure this
thing out...What do you say?

On 17 December 2014 at 10:21, char carradine kuttiecc@gmail.com wrote:

> okay you can edit it
> 
> On 17 December 2014 at 08:48, tasonface notifications@github.com wrote:
> 
> > Sorry, this was my first post on github, didn't know that posts supported
> > HTML format. I fixed my first post right now, it was already reproducing
> > popover's issue.
> > 
> > Also..
> > 
> > 4) "bg-primary" class and similar (bg-warning, bg-info, bg-success...)
> > should have same background color of "btn-primary" and corresponding
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/FezVrasta/bootstrap-material-design/issues/302#issuecomment-67352375
> > .
> 
> ## 
> 
> Char

## 

Char

**Comment by kuttiecc** [comment]
Let me give you a better e-mail addy to contact me Carradine20@aol.com

On 17 December 2014 at 15:49, char carradine kuttiecc@gmail.com wrote:

> hey, is there anyway I can call you and maybe together we can figure this
> thing out...What do you say?
> 
> On 17 December 2014 at 10:21, char carradine kuttiecc@gmail.com wrote:
> 
> > okay you can edit it
> > 
> > On 17 December 2014 at 08:48, tasonface notifications@github.com wrote:
> > 
> > > Sorry, this was my first post on github, didn't know that posts
> > > supported HTML format. I fixed my first post right now, it was already
> > > reproducing popover's issue.
> > > 
> > > Also..
> > > 
> > > 4) "bg-primary" class and similar (bg-warning, bg-info, bg-success...)
> > > should have same background color of "btn-primary" and corresponding
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/FezVrasta/bootstrap-material-design/issues/302#issuecomment-67352375
> > > .
> > 
> > ## 
> > 
> > Char
> 
> ## 
> 
> Char

## 

Char

**Comment by tasonface** [comment]
@kuttiecc are you project cooperator or something? I ask, because I see FezVrasta with "OWNER" flag

**Comment by FezVrasta** [comment]
I don't really know him :/

**Comment by tasonface** [comment]
@FezVrasta Thank you, or whoever edited my first post. It's great that with simple indentation it creates blocks of code! I appreciate very much this bootstrap theme release, you're doing a great job and I'm developing almost every day, using it! I'll update this post with more bugs/suggestions I'll find. It might be easier to organize it from your side.

For now the last thing I've noticed is that:
5)  "onchange" event attached to the "select" element, which uses Dropdown.js, doesn't fire it. I created a form with method GET and tried to force a submit on change event of the select. So I wrote:

```
<form method="GET">
    <select name="date" onchange="this.form.submit()" class="form-control">
        <option value="18-12-2014">18-12-2014</li>
        <option value="17-12-2014">17-12-2014</li>
    </select>
</form>
```

It just ignores my event and creates a super-cute dropdown. For now I keep a submit button inside the form. I'm not sure it's a part of your material core code but maybe you could extend it inside your project so It could inherit all the events from the original selector (in my case, all the "select" elements)

Thanks man, keep doing this great job :)

**Comment by FezVrasta** [comment]
I've edited your first post.

About bugs, please open a different issue for each one, this make easier to organize them.

Thanks.

**Comment by FezVrasta** [comment]
1) I can't see any problem:
http://codepen.io/FezVrasta/pen/LEZdXq

2) pills are not yet supported by this theme #316

3) there are several duplicates of this problem in the issues list, it will be fixed once Google releases an official iconic font.
