### ISSUE TITLE
Input "Focus" Block Slide Animation Color Won't Change

### ISSUE THREAD

**Issue by CowDotDev** [mdbootstrap/mdb-ui-kit#303]
This may be an error on my part not understanding what to change with CSS, but I want that little "block slide" animation when you focus on an input to be a different color than that default (primary) green. 

The `.material-input` span has the `:before` and `:after:` and the before has the `background-color` that you can change, but when I change that color it only makes the border on the bottom the new color, the slide animation doesn't change.

If I am just not changing the right area, please just let me know!
Cheers!

**Comment by FezVrasta** [comment]
You should change `.material-input:before`  if I remember it correctly.

**Comment by CowDotDev** [comment]
That is what I have been changing, and that only changes the `border-bottom` color of the input on focus. It looks like the color is part of the animation, and not the `:before` or `:after`. I'm giving the code a look to see if I can't find it.

**Comment by CowDotDev** [comment]
Found it! Don't know why I couldn't see it in Chrome's Inspector, but it is the `background` for `input.form-control:focus ~ .material-input:after`.

**Comment by FezVrasta** [comment]
chrome inspector is not the best with :focus and pseudo element things.

I'm glad you have found it :)
