### ISSUE TITLE
Ripple Color

### ISSUE THREAD

**Issue by koenhendriks** [mdbootstrap/mdb-ui-kit#304]
Is their anyway to set a custom ripple color on a button ?

**Comment by FezVrasta** [comment]
You can force the color setting:

```
.ripple-wrapper .ripple { background: #000 !important;   }
```

**Comment by koenhendriks** [comment]
ok thanx! 
But if i want multiple buttons with different ripple colors? their is not an attribute i can set? 
E.x:

``` html
<button class="btn btn-info" ripple-color="#FF0000">Custom Ripple Color</button>
```

**Comment by FezVrasta** [comment]
Not currently, I'm open to PR to implement it.

**Comment by FezVrasta** [comment]
You may use a class, like

```
.ripple-red .ripple { background: red }
```
