### ISSUE TITLE
Your license uses the term "free software" incorrectly.

### ISSUE THREAD

**Issue by MarkTraceur** [mdbootstrap/mdb-ui-kit#307]
> This program is free software

Then, later...

> You cannot sell this software

This is decidedly not free software, and I would ask that you kindly stop claiming that it is. The definition of free software by the Free Software Foundation explicitly grants users the freedom to distribute copies of the software, modified or not, without any further restrictions. Please do not dilute the meaning of the term "free software" any further by continuing to include this false statement in your license file.

Alternatively, you could remove the non-commercial clause, or even better, just use the GNU GPLv3 in its full form, instead of trying to imitate parts of it, which would better protect you (and everyone else) legally.

Thanks.

**Comment by MarkTraceur** [comment]
For reference, the license is available here:

https://github.com/FezVrasta/bootstrap-material-design/blob/master/LICENSE.md

**Comment by FezVrasta** [comment]
Actually this software is free for every purpose that doesn't implies commercial activities, so I've all the rights to call it in this way.

**Comment by MarkTraceur** [comment]
You have every right to make whatever inaccurate claim you'd like, but that doesn't make it any more true. You have restricted your users from exercising specific freedoms, and that makes this a non-free license. Please consider changing the text of that clause.

**Comment by MaxSem** [comment]
Replace it with "This program is free-as-in-beer software"?

**Comment by FezVrasta** [comment]
I've wanted to use the gpl because I want to allow all the rights regarding this license, but I want to limit this rights to only non commercial activities.

If you don't agree with this license then you can use another library or write your own.

**Comment by MarkTraceur** [comment]
@FezVrasta sorry, can you clarify: Are you currently distributing this software under the entire text of the GNU General Public License, Version 3?

**Comment by Krenair** [comment]
I suspect you should check with a lawyer before trying to do such things with licenses.

**Comment by FezVrasta** [comment]
You can fork, edit, redistribute and use it but only for not commercial projects and the part added by me overrides everything that is written inside the gpl

**Comment by MarkTraceur** [comment]
@FezVrasta That doesn't answer my question. Are you currently distributing the software under the GPLv3, with the added text in your LICENSE.md file?

**Comment by FezVrasta** [comment]
By the way I'll try to improve the format of the license to make it clearer

**Comment by FezVrasta** [comment]
Improved.

I was mentioning the gpl to make it clear that for free purpose you may edit the software, always following the license.

**Comment by MarkTraceur** [comment]
That makes very little sense.

The new license terms seem totally fabricated, and I doubt you ran them past a lawyer. Have you considered doing so? Because I'm not sure you understand what any of this means.

**Comment by FezVrasta** [comment]
I think it is very very clear. What is unclear?

**Comment by MarkTraceur** [comment]
Your desires are almost clear (if not particularly well-written), but I'm talking about the various complex ramifications of the license terms, and possible interpretations. There's a reason lawyers go through so much education and get paid so much: They know their shit. Please consider either using an existing license or talking with a legal professional about the one you've made up yourself.

**Comment by FezVrasta** [comment]
I can't find licenses that fit my needs and I don't think I need to pay a lawyer for a so simple license.

Again, if you don't find it clear please you are invited to do not use this software. Thanks.

**Comment by camalot** [comment]
FYI, even if you change the licence right now, it does not retroactively change the license. The code that was under the previous license still is bound to that license. If you first licensed under some sub-set of the GPL, that is what the code at that time is licensed under. even if you say "i can change the license at any time". 

Also, "no-profit" and commercial are not opposites. Commercial products can be "no-profit". 

You really should consider an existing license. You contradict other parts of your license with the line:

This software may be sold if used inside a software which uses it as dependency, in any case, this license must be included in the software. 

I see what you are trying to accomplish, which is preventing someone from forking it and selling it as a theme. But you probably wouldn't be able to enforce that. I could argue that I could create a theme, that is derived from this and since it would be a dependency, I can sell it. 

You should probably read this: http://programmers.stackexchange.com/questions/179383/open-source-license-that-prevents-re-selling

**Comment by FezVrasta** [comment]
Please stop, I've never said a change can be retroactive, if you don't like what I do just ignore me. Bye

**Comment by camalot** [comment]
You are missing my point, you think I am attacking you here. I am not, it's the opposite actually. But that shows that there is a lot of ambiguity with your license. The way it is worded, it makes it sound like you can change the license at anytime and it applies to all. 

Also, there are a lot of GPL'd projects that sell commercially. 

That is all I will say about this, I was just trying to offer some insight, not trying to attack.

**Comment by floatingatoll** [comment]
On the off chance that your research did not reveal it, CC BY-NC-SA is a prebuilt license that provides approximately GPLv2 + non-commercial. I can't speak to whether it addresses any/all of your needs, but FYI in case you aren't already aware.

https://creativecommons.org/licenses/by-nc-sa/3.0/us/

**Comment by sethwoodworth** [comment]
https://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F

> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed as “open source” by the Open Source Initiative.

The GPL restricts one's ability to add additional restrictions on top of the GPL.  But I don't see the GPL referenced in `LICENSE.md`.

**Comment by pramod1988** [comment]
Hello @FezVrasta ,
I am using your material design to make wordpress theme for free.But my theme is not getting approved because your theme license of the used Bootstrap theme is not GPL compatible.
Can you help me in this?

**Comment by sethwoodworth** [comment]
@pramod1988 This project is not and will not be GPL compatible with the further non-commercial restrictions.
