### ISSUE TITLE
Compile with LESS 1.x

### ISSUE THREAD

**Issue by fredfortier** [mdbootstrap/mdb-ui-kit#308]
I do not have the option of running a LESS 2.x compiler at the moment.

com.asual.lesscss.LessException: Parse Error: Unrecognised input (line 6, column 19) near
    &@{extra}, &-default@{extra} {
        @{property}: @default;
    }

I get past the error by hacking _mixins.less and to essentially comment everything out. Since the issue seems isolated to a single file, would be possible to use a LESS 1.x syntax throughout?

**Comment by FezVrasta** [comment]
We use some complex mixin there, I don't think I could make it work with an older version.

I can't see why can't you install the right version specified in the package.
