### ISSUE TITLE
Including a note that explains the licensing terms in your contributions file

### ISSUE THREAD

**Issue by Ironholds** [mdbootstrap/mdb-ui-kit#309]
Your comment [here](https://github.com/FezVrasta/bootstrap-material-design/issues/201) suggests that your intent is, for for-profit projects, to charge them money for reusing your content, which you'll then pocket. That's...you know, fine, but you should probably include a note explaining the terms in your [contributing](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md) file. At the moment, you are soliciting a vast array of contributions from a [vast array](https://github.com/FezVrasta/bootstrap-material-design/graphs/contributors) of contributors, for a project that does not make clear that they are transferring the intellectual property rights to you, and that you intend to make money off it. This is, at the very least, certainly ethically problematic.

**Comment by FezVrasta** [comment]
Actually this is very clear in the license. I can add a note to the contrib file to remember users to read the license.

**Comment by Ironholds** [comment]
I don't find it clear at all. What are the conditions? You don't specify them. And, re "may be modified at any time"; you do understand you cannot modify licensing _post-hoc_, yes?

**Comment by FezVrasta** [comment]
Actually I can change the license at any time and it will be valid for any future bit of code.

The conditions may vary by each situation.

I've edited contrib.md
