### ISSUE TITLE
Embedded RobotoDraft

### ISSUE THREAD

**Issue by julianpaulozzi** [mdbootstrap/mdb-ui-kit#314]
In the last update I noticed improvements in fonts using RobotoDraft however this comes from Google Fonts. 
Some way to make them available to in the project fonts referenced by font-face?
The standard materials design fonts are available here:
http://www.google.com.br/design/spec/resources/roboto-noto-fonts.html

**Comment by FezVrasta** [comment]
Currently I'm using Google Web Fonts service, I think we could move to the official Roboto font from Google Web Fonts once they release there the new version.

**Comment by julianpaulozzi** [comment]
Is easy to get supplies to work offline. Just put the urls in the browser and got the fonts locally. 
After only rename the fonts and change the url of their respective font-face.
Placing the fonts with the project would be more for convenience in use.

**Comment by FezVrasta** [comment]
implemented
