### ISSUE TITLE
Should the drop-down examples use the data-target attribute?

### ISSUE THREAD

**Issue by dandv** [mdbootstrap/mdb-ui-kit#315]
There are a few drop-down examples at http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html, e.g. in the navbars. The code for them uses `a href="javascript:void(0)`.

The [Bootstrap docs on dropdowns](http://getbootstrap.com/javascript/#dropdowns) say

> To keep URLs intact with link buttons, use the data-target attribute instead of href="#".
> 
> ``` html
> <div class="dropdown">
>   <a id="dLabel" data-target="#" href="http://example.com" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false">
> ```

Should the example code be updated to reflect that?

**Comment by FezVrasta** [comment]
thanks
