### ISSUE TITLE
Breaks Select2 (due to infinite loop?)

### ISSUE THREAD

**Issue by JP-Ellis** [mdbootstrap/mdb-ui-kit#320]
I am using Bootstrap, this Bootstrap theme and I'm using Select2 to handle selection boxes which have potentially a lot of options.

I have noticed that `$.material.autofill()` breaks Select2.  Specifically, the first Select2 field that is clicked on will work exactly as expected, but any subsequent Select2 field is then broken;  the drop-down box is closed as soon as it is opened.

I am no JavaScript / jQuery expert, but it think it might be an infinite loop with a `$(element).on('change', ...)` ultimately causing a `$(element).trigger('change')`.

You can see a JSFiddle demonstration of this bug over at http://jsfiddle.net/JPEllis/jras2vee/.

I am not completely sure whether this is a bug with this theme's `$.material.autofill()` or whether it could be a bug with Select2; so I have actually also submitted this bug with Select2 over at ivaynberg/select2#2883.

**Comment by FezVrasta** [comment]
probably autofill should be disabled by default..

you can disable it with:

```
$.material.options.autofill = false;
$.material.init();
```

**Comment by JP-Ellis** [comment]
I have disabled `autofill()` for the time being, but I wanted to let you know of this issue in case it might cause other issues with other plugins and/or if there could or should be a different implementation of `autofill()`.

**Comment by FezVrasta** [comment]
the current implementation is the best thing I've found... unfortunately the autofill feature of browsers is almost impossible to handle :(

PR are very welcome with any kind of improvement.

**Comment by JP-Ellis** [comment]
The particular issue with Select2 will be fixed when Select2 4.0 comes out (which is a complete re-write of Select2), so as far as I am concerned, this issue can be closed.  I don't know whether you still want to find an alternative implementation for `autofill()` in case it might break any other JS libraries/plugins.
