### ISSUE TITLE
focus style is not removed from inputs when columns are arranged horizontally

### ISSUE THREAD

**Issue by chiragjn** [mdbootstrap/mdb-ui-kit#322]
The Focus styling is not removed from text inputs when columns are arranged side by side,
![issue](https://cloud.githubusercontent.com/assets/10295418/5553567/02351e06-8c4b-11e4-88c8-08aa26a8dd86.png)

when columns are arranged one below another, focus styling works as expected.

**Comment by FezVrasta** [comment]
Please may you provide a codepen demo?

**Comment by chiragjn** [comment]
Here : http://codepen.io/chiragjn/pen/OPRgrP

**Comment by FezVrasta** [comment]
I can't reproduce this problem... which browser are you using? which version?

**Comment by chiragjn** [comment]
I was using Firefox 34.0 on Ubuntu while reporting the issue,
I installed Chromium and found out the issue occurs only in FireFox.

**Comment by rosskevin** [comment]
Works for me on 0.4.1

> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
