### ISSUE TITLE
Bootstrap compatibility and ease of implementation

### ISSUE THREAD

**Issue by mschipperheyn** [mdbootstrap/mdb-ui-kit#323]
I'm eagerly waiting for this library to be finished. At the same time, when I examine the source, I'm noticing that you seem to be drifting from some of the bootstrap html structure or adding to them in ways that make it harder to drop this in as a replacement.

Take for instance the floating label.

The default HTML structure for a form element in most websites and bootstrap is

```
<div class="form-group">
    <label>Some label</label>
    <input type="email" name="email" placeholder="E-mail" required>
</div>
```

In your material design implementation it is

```
<div class="form-group">
    <div class="form-control-wrapper">
        <input class="form-control" id="focusedInput" type="text">
        <div class="floating-label">Write something to make the label float</div>
        <span class="material-input"></span>
    </div>
</div>
```

In my humble opinion, this structure unnecessarily breaks compatibility with bootstrap in a number of ways.

First of all, I think that class qualifiers should be put at the highest possible level. 
So 'floating-label' should be at the level of the form-group, and 

```
 <div class="floating-label"> 
```

should be 

```
 <label>
```

This will allow us to more easily extend the appropriate classes at a central level without having to manipulate HTML to achieve this effect.

I know that Bootstrap often uses these low level selectors as opposed to higher level selector but I believe this is a wrong approach and it will certainly significantly reduce adoption of your mod.
Imagine having to change all the forms in a website or app to get the material design effect.

I haven't delved into this all too deeply at the HTML level, but it also seems a shame to have the form-control-wrapper and the material-input span.
I am wondering if the material-input effect that it creates cannot be achieved by adding a before class to the input field? I know some of the older browser don't support animated pseudo classes, but modern browsers do and it would be a shame to depend on html to achieve an animation effect.

Also, I noticed on the horizontal field example of a form, that you use the the col class to achieve the desired horizontal effect, which is strange since Bootstrap has simple "form-native" classes to achieve this effect, again making the implementation harder to implement.

**Comment by FezVrasta** [comment]
It was already in my to do list to restructure the floating label, thanks for this issue.

**Comment by FezVrasta** [comment]
I've tried to work on this issues...

pseudo elements are not supported on self-closing tags, so I can't get rid of material-input and so I can't neither get rid of the wrapper.

If you find some solution feel free to let me know.

**Comment by mschipperheyn** [comment]
One thing you might consider is dropping that animation (and corresponding span) that happens when you click the form input. There's this quick bar like animation. It's inelegant and I'm not sure it's supposed to happen. What I think should happen is that the underline for the input item is animated inside to out. I think is how it's supposed to work: http://material-ui.com/#/components/inputs

**Comment by FezVrasta** [comment]
Material ui project barely follows material design specs. And, even removing it, I would need the wrapper element.
