### ISSUE TITLE
Ripple Effect not working after update

### ISSUE THREAD

**Issue by danielesalvatore** [mdbootstrap/mdb-ui-kit#325]
First of all I would like to thank for your project and your code!

I recently updated the version of bootstrap-material-design and since that moment the ripple effect is not working no more. Before the update everything was working perfectly. 
I have a single-page application based on RequireJS.

As required I added arrive.js (v2.0.0) to the project.
I use jQuery v2.1.3
Bootstrap v3.2.0
dist/css/ripple.min.css and dist/css/material-wfont.min.css (in this order)
dist/js/ripples.min.js and dist/js/material.min.js

Here you can find part of the RequireJS configuration to set the load sequence of libraries

```
shim: {
    "bootstrap": {
        deps: ["jquery"]
    },
    "ripples" : {
        deps: ["jquery", 'arrive']
    },
    "material": {
        deps: ["bootstrap", 'ripples']
    },
```

... 

In my initialisation module I import only 'material' dependency. This mean it will load
jQuery, then Bootstrap, Arrive, Ripples and Material

Do you know what can cause the problem?

Thank you very much for your support

PS: there is a not resolved conflict in https://github.com/FezVrasta/bootstrap-material-design/blob/master/dist/css/ripples.min.css.map

**Comment by FezVrasta** [comment]
please may you provide a codepen sample? Also, if you have upgraded from a old version you may need to add `$.material.init()` to your JS

**Comment by danielesalvatore** [comment]
Dear @FezVrasta thank you for you support. The $.material.init() solved the problem.

Thank you very much for your prompt reply and have a happy 2015.

**Comment by matewilk** [comment]
Actually, I have the same problem,

I'm requiring arrive **before** material, and 1 out of 10 times I'm getting the same error:

```javascript
Uncaught TypeError: $(...).arrive is not a function material.js:197
```
This is how my main.js file looks like, the arrive is attached before material

```javascript
/*global require*/
'use strict';

require.config({
    shim: {
        bootstrap: {
            deps: ["jquery"]
        },
        ripples : {
            deps: ["jquery", 'arrive']
        },
        material: {
            deps: ["bootstrap", 'ripples']
        },
        velocity: {
            deps: ["jquery"]
        }
    },
    paths: {
        scripts: '../scripts',
        globals: './globals',
        jquery: '../bower_components/jquery/dist/jquery',
        backbone: '../bower_components/backbone/backbone',
        underscore: '../bower_components/lodash/dist/lodash',
        bootstrap: '../bower_components/bootstrap/dist/js/bootstrap',
        arrive: '../bower_components/arrive/src/arrive',
        material: '../bower_components/bootstrap-material-design/dist/js/material',
        ripples: '../bower_components/bootstrap-material-design/dist/js/ripples',
        handlebars: '../bower_components/handlebars/handlebars',
        templates: '../scripts/templates',
        "jquery-cookie": '../bower_components/jquery-cookie/jquery.cookie',
        epubjs: "../bower_components/epubjs/build/epub",
        jszip: "../bower_components/jszip/dist/jszip.min",
        dropzone: "../bower_components/dropzone/dist/dropzone-amd-module",
        velocity: "../bower_components/velocity/velocity",
        react: "../bower_components/react/react",
        "backbone-react": "../bower_components/backbone-react-component/lib/component"
    }
});

require([
    'backbone',
    'app',
    'globals/session',
    'material',
    'velocity'
], function (Backbone, Application, SessionModel) {

    $(document).ready( function() {
        $.material.init();
    });

    window.App = {
        session: SessionModel
    };
    new Application();

    Backbone.history.start({
        pushState: true,
        hasChange: false
    });
});
```
