### ISSUE TITLE
Problem when using ripples.js alone

### ISSUE THREAD

**Issue by grvcoelho** [mdbootstrap/mdb-ui-kit#327]
Hello there folks!

I'm trying to use the ripple effect alone! I've included the stylesheets and the scripts, and I'm trying to call it like this: 

``` javascript
  $('#my-button').ripples();
```

But I'm getting this error, when I click it:`Uncaught TypeError: Cannot read property 'createDocumentFragment' of null`

What could I probably be missing? How can I use the ripples.js like this?

Thanks in advance :smile: 

_Ps: I tried including the material.js as well, but I got the same error!_

**Comment by FezVrasta** [comment]
please provide a codepen.io example

**Comment by grvcoelho** [comment]
Here you go: http://codepen.io/grvcoelho/pen/NPRMmX

In this pen, I've used the CDN versions, but that doesn't seem to make any difference. The error is the same, if you inpect the console.

**Comment by FezVrasta** [comment]
Looks like you have to use:

```
$.ripples("selector");
```

Don't ask me why... will fix it when I've some free time.

**Comment by grvcoelho** [comment]
Hey @FezVrasta! I've created a pull request fixing it!

I also took the liberty to change the structure of the plugin to something like the awesome [jQuery Boilerplate](https://github.com/jquery-boilerplate/jquery-boilerplate) project.

And, as mentioned in the PR, I also removed the default target elements off the plugin.

I think this should be in an initialization file (or even in the same file but on the bottom of it). Something like: 

``` javascript
var defaultTargets = '.btn .card .test #ripple #anotherSelector';
$(defaultTargets).ripples();
```

This way, the plugin can be used completely independent from whatever the developer is using as UI toolkit.

Oh, and I commented everything as well :smile:

**Comment by benstr** [comment]
FYI: Got this error when I accidently had `material.js` called twice in the head.

**Comment by agnel** [comment]
That's pretty good then if its independent of the UI a developer uses. Nice work @grvcoelho. Thanks

**Comment by grvcoelho** [comment]
Thanks @agnel, the new code is still a little buggy, but I'm trying to fix the problems :smiley:
