### ISSUE TITLE
buttons and button classed links don't look the same

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#328]
```
  <a class="btn btn-default">button 1</a>
  <button class="btn btn-default">button 1</button>
```

links have diferent margins, paddings and sizes

**Comment by FezVrasta** [comment]
I can't see any difference...

http://codepen.io/FezVrasta/pen/EagrPY

**Comment by ghost** [comment]
Maybe it is my bootstrap version.
I'm using bootstrap-sass 3.3.1 and bootstrap-material 0.2.0

I close, and try to find out.

sorry.

**Comment by FezVrasta** [comment]
I use 3.2.0, I'll try with the new one soon
