### ISSUE TITLE
$.material.init() with Meteor Template

### ISSUE THREAD

**Issue by sivailango** [mdbootstrap/mdb-ui-kit#329]
Hi,

I am using Material design with Meteor. I am using init ($.material.init()) for every template to get material design work for all templates. Is there any way to place $.material.init() in one place which can be commonly used by all templates in meteor. Also i have been creating some dom elements on the fly (jQuery clone, data from mongo which prepend by checkbox). But it did not add material style for newly created elements on the fly.

**Comment by FezVrasta** [comment]
you may want to include `arrive.js` before `material.js`

**Comment by txs** [comment]
How do I use the arrive.js?
