### ISSUE TITLE
No range sliders

### ISSUE THREAD

**Issue by wengqi** [mdbootstrap/mdb-ui-kit#33]
I noticed that you use noUiSlider plugin to Implement your material slider component. 
When I set "connect: true" of the slider's options, the range slider does not work.

I you have time, please try and have a look at it.
Thanks.

**Comment by FezVrasta** [comment]
Thanks, my graphic card at the moment is died, I've ordered a new one, I'll be able to fix it in few days.

**Comment by FezVrasta** [comment]
Okay had found time to fix it, now everything should work correctly.

**Comment by wengqi** [comment]
Thanks, the range slider is okay now, but there are some other bugs. 
1) set ---- connect: "lower",  the connect background color is not shown.
2) if you have time, can you also support vertical style by setting [orientation: "vertical"]
Here is my test code below:

<div class="bs-component">
        <div class="slider" id="slider-upper"></div>
        <div class="slider slider-success" id="slider-lower"></div>
        <div class="slider slider-material-pink" id="slider-range"></div>
</div>

<script>
            $(function() {
                $("#slider-upper").noUiSlider({
                    start: 40,
                    connect: "upper",
                    range: {
                        min: 0,
                        max: 100
                    }
                });
                $("#slider-lower").noUiSlider({
                    start: 60,
                    connect: "lower",
                    range: {
                        min: 0,
                        max: 100
                    }
                });
                $("#slider-range").noUiSlider({
                    start: [40,80],
                    connect: true,
                    /*orientation: "vertical",*/
                    range: {
                        min: 0,
                        max: 100
                    }
                });
            });
 </script>

Here is the result of the code
![qq 20140929170557](https://cloud.githubusercontent.com/assets/6908877/4439406/dbc0f5a6-47b7-11e4-9eb8-04bfc202e376.png)

Thanks.

**Comment by FezVrasta** [comment]
The "lower" connect option is used in the demo...

![image](https://cloud.githubusercontent.com/assets/5382443/4439454/54312bdc-47b8-11e4-86e2-cf60042afa0c.png)

it works there, are you sure you are even with the master branch? I've sent two commits to fix the sliders.

About the vertical support, at the moment I've not time but when I'll have my home pc again I'll add support for them.

A PR to add vertical support is very welcome :)

**Comment by wengqi** [comment]
Thanks, the range slider is okay now, but there are some other bugs. 
1) set ---- connect: "lower",  the connect background color is not shown.
2) if you have time, can you also support vertical style by setting [orientation: "vertical"]
Here is my test code below:

<div class="bs-component">
        <div class="slider" id="slider-upper"></div>
        <div class="slider slider-success" id="slider-lower"></div>
        <div class="slider slider-material-pink" id="slider-range"></div>
</div>

<script>
            $(function() {
                $("#slider-upper").noUiSlider({
                    start: 40,
                    connect: "upper",
                    range: {
                        min: 0,
                        max: 100
                    }
                });
                $("#slider-lower").noUiSlider({
                    start: 60,
                    connect: "lower",
                    range: {
                        min: 0,
                        max: 100
                    }
                });
                $("#slider-range").noUiSlider({
                    start: [40,80],
                    connect: true,
                    /*orientation: "vertical",*/
                    range: {
                        min: 0,
                        max: 100
                    }
                });
            });
 </script>

Here is the result of the code

Thanks.

2014-09-29 

wengqi 

发件人：Fez Vrasta notifications@github.com
发送时间：2014-09-29 16:16
主题：Re: [bootstrap-material-design] No range sliders (#33)
收件人："FezVrasta/bootstrap-material-design"bootstrap-material-design@noreply.github.com
抄送："wengqi"wq_forever@126.com

Okay had found time to fix it, now everything should work correctly.

**Comment by wengqi** [comment]
I checked out the latest code and  It's okay now. Thanks.
