### ISSUE TITLE
Material.js + datetimepicker = craziness

### ISSUE THREAD

**Issue by benstr** [mdbootstrap/mdb-ui-kit#333]
Demo of issue: http://codepen.io/benstr/pen/dPOPxY

I have a project using @Eonasdan 's [Bootstrap datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker)

When only picking a "day" on hover the DOM goes into an endless loop re-rendering the table elements. This happens about 80% of the time. Sometimes you need to click a date first to trigger the endless loop. It only happens when hovering over a **day** `<td>` element. 

Removing **Material.js** stops the bug. 

Reference issue on datetime repo: https://github.com/Eonasdan/bootstrap-datetimepicker/issues/717

**Comment by FezVrasta** [comment]
Sorry I can't notice any problem with your demo... which browser are you using?

**Comment by benstr** [comment]
I am on a Mac. The issue happens in Safari, Chrome and Firefox.
- Chrome: day background hover color flickers, cursor is fine, selecting day is spotty.
- Safari: day background hover color is fine, cursor is fine, selecting day is spotty.
- Firefox: day background hover color is fine, cursor flickers, selecting day is spotty.

If you are on the static CodePen page for longer than ~30 seconds the issue seems to reconcile itself. But with dynamic systems like Meteor the issue is consistent and never reconciles on its own.

**Comment by benstr** [comment]
@FezVrasta It is Autofill causing the issue. I increased the timeout function in the pen so you can see it now. You have the timeout at 10sec. so that may be why you did not notice it. Try now.

**Comment by FezVrasta** [comment]
Try disabling it so

```
$.material.options.autofill = false
$.material.init()
```

**Comment by benstr** [comment]
Yeah that is what I did for now. My project is in Meteor so autofill probably is not needed anyways.
