### ISSUE TITLE
Ideas for new features

### ISSUE THREAD

**Issue by digitalcraftsman** [mdbootstrap/mdb-ui-kit#335]
After I took a look at your awesome project I thought some elements could be added. I don't know with which grade of detail you started your bootstrap material theme, so some features are either an enhancement for the project or not campatible with the idea of a lightweight framework like bootstrap.

The list:
1. Advanced global color options for styling. If I use `navbar-inverse``for example, the color scheme of the other components don't match the color of the other elements (e.g. a purple navbar is not coherent with green fonts on a buttons by default). You may could add a simple interface in form of classes to implement the [colors of material design](https://www.google.com/design/spec/style/color.html#color-ui-color-application) with global classes, that changes the theme of all elements.
2. Adding the auto growing behavior to textareas like [here](https://www.polymer-project.org/components/paper-input/demo.html) (see decorators -> 3rd input field)
3. Adding a floating label to input fields. [Here is a demo](https://www.polymer-project.org/components/paper-input/demo.html) (2nd input).
4. Implementing a simple off-canvas menu in material design.
5. Adding [animations for elements](http://www.polymer-project.org/components/core-animated-pages/demo.html).
6. More options for dialogs, like a backdrop or different animations of how the dialog appears. Look [here](https://www.polymer-project.org/components/paper-dialog/demo.html)
7. Adding pages like them on the [start page](https://fezvrasta.github.io/bootstrap-material-design/#navbar) of your demos, which fly in, if you select an element on the left to look at. 

I hope you find some of the ideas are useful.

**Comment by abodacs** [comment]
+1

**Comment by FezVrasta** [comment]
I'm from mobile, I'll reply to some of the points:

2: you should use jQuery Autosize for this.
3: already implemented

**Comment by FezVrasta** [comment]
1. duplicate of #73
2. I think this is something that you should achieve with 3rd party solutions, this is just a theme :)
3. good idea
4. @gitdvcs may you explain it a bit better? I'm not sure I get what you mean

**Comment by digitalcraftsman** [comment]
2: Your mentioned autosize function of jQuery looks pretty similar.

4:  Resize the window of [this demo page](https://www.polymer-project.org/components/paper-elements/demo.html#paper-progress) at Project Polymer and click the menu bottom in the top left corner. It would be a nice alternative for responsive layout. Furthermore I found [this image](https://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7djQtdzFQN291akU/components_dividers_type2.png) in the design explenations of material design itself. It has a slightly different structure.

**Comment by FezVrasta** [comment]
yea the demo page has no mobile support for now, I've to implement it.
