### ISSUE TITLE
How can change toggle button left when checked?

### ISSUE THREAD

**Issue by lmquang** [mdbootstrap/mdb-ui-kit#336]
Dear fez,
I wanna change 'left' of togglebutton after check to balance position of button before and after check.
Can you show me how ?

**Comment by FezVrasta** [comment]
sorry I don't get what you mean

**Comment by lmquang** [comment]
i wanna change this attribute in material-wfont.min.css:
.togglebutton label input[type=checkbox]:first-child:checked + .toggle:after
from left:15px(default) to left:5px
Can you show me how to change this ?

**Comment by FezVrasta** [comment]
You should just override it using you custom stylesheet
