### ISSUE TITLE
Circle fill in click

### ISSUE THREAD

**Issue by danimasa** [mdbootstrap/mdb-ui-kit#337]
Hello,

I’ve had a problem with the circle fill when I click in some button. I tried to copy the script of the index.html in the disp folder of the project but it didn’t work. I also tried to copy the scripts of the website of the project http://fezvrasta.github.io/bootstrap-material-design/#about but it didn’t work too, the animation of the circle fill didn’t work. What I have done wrong?

Thanks

**Comment by FezVrasta** [comment]
Please may you use this pen to provide an example of your code? Thanks.

http://codepen.io/FezVrasta/pen/ihmea

**Comment by danimasa** [comment]
Sorry for my late. I was traveling and without net.

I saw your pen and the button on that pen (I don't change anything) the fill doesn't work too. In your website about the project, when you click on the buttons a circle fill animation is activated and I want to provide the same effect in my website. I copied all the js files but the effect doesn't work. Thanks.

**Comment by FezVrasta** [comment]
the pen is on the branch master, the ripple effect is bugged right now, you have to use the latest stable

**Comment by danimasa** [comment]
Ow, Ok. I used the tag 0.2.1 and all worked fine! Thanks.
