### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by sivailango** [mdbootstrap/mdb-ui-kit#339]
Hi,

Is there any CSS for materialize datepicker (with bootstrap) like from here http://materializecss.com/components.html ?

**Comment by FezVrasta** [comment]
no there's not such feature at the moment but I'd like to implement it.

**Comment by T00rk** [comment]
I've made one according to Google material specs and using your bootstrap plugin.
https://github.com/T00rk/bootstrap-material-datepicker

**Comment by FezVrasta** [comment]
Hey nice! Looks awesome

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
