### ISSUE TITLE
Selectize Styling

### ISSUE THREAD

**Issue by mfrancis107** [mdbootstrap/mdb-ui-kit#340]
I feel the selectize plugin just doesn't work well. The styling isn't very good for multiselect setup.

It would be nice if this was included in a separate css file. So we could choose to include it or not.

**Comment by FezVrasta** [comment]
What's the problem with this style?

**Comment by chervand** [comment]
Agree. Completely useless for me. I'll try to provide more info later, but anyways it would be nice to have 3rd party plugins styles separated.

**Comment by ztzven** [comment]
I think I'm having this issue too.
I'm using Material BS + selectize + angular + angular-selectize. See image below for an example of the styling issue.
![selectize_material_error](https://cloud.githubusercontent.com/assets/860865/9433310/c84cfd8c-4a84-11e5-80c6-cb752713a26c.png)

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
