### ISSUE TITLE
Floating label doesn't stay floated with invalid inputs

### ISSUE THREAD

**Issue by wopian** [mdbootstrap/mdb-ui-kit#341]
On the [demo](https://fezvrasta.github.io/bootstrap-material-design/#input) page under _Validation_, typing in (a number then) an invalid character turns the floating text red but also returns it back to it's initial location.

Typing in a number behaves like normal and the second input under _Hints_ also works fine, so it's possibly an issue with the `number type`.

![](http://zippy.gfycat.com/ThatPerfectGalah.gif)
![](http://zippy.gfycat.com/MiserlyHomelyBobwhite.gif)

**Comment by FezVrasta** [comment]
I thought this bug was fixed some week ago with #285 ... Need to investigate.

**Comment by FezVrasta** [comment]
yup it was already fixed
