### ISSUE TITLE
GitHub page is not updated...

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#345]
Maybe someone can help me.

I've updated the gh-pages branch with the new content and the index.html should have some new feature, the code is okay but if you open http://fezvrasta.github.io/bootstrap-material-design/ you see the old version.

Why?

**Comment by sekanderb** [comment]
Can you guide me a bit about what to do and how to do?
I am eager to contribute here :)

**Comment by FezVrasta** [comment]
I've no other informations :(

**Comment by FezVrasta** [comment]
Looks like there was a symlink broken inside the meteor packages folder... I've just removed the meteor folder from gh-pages but I don't think is a real solution.

**Comment by GradyD** [comment]
@FezVrasta Is this still an issue?

**Comment by FezVrasta** [comment]
Yes looks so
