### ISSUE TITLE
body background is set without using bootstrap's @body-bg

### ISSUE THREAD

**Issue by guymguym** [mdbootstrap/mdb-ui-kit#347]
in the beginning of material.less there's the rule 
`body { background-color: #EEEEEE; ... }`

instead I expected it to use @body-bg so that I can override the color in a consistent manner like in other bootstrap themes.

any reason not to convert that to: 
`@body-bg: #EEEEEE;`

thanks!

**Comment by guymguym** [comment]
btw in a similar way also these bootstrap variables are not set and I have to set them to be able to use the real colors. maybe add to colors.less?

```
@brand-primary: @primary;
@brand-success: @success;
@brand-danger: @danger;
@brand-warning: @warning;
@brand-info: @info;
```

**Comment by FezVrasta** [comment]
fixed
