### ISSUE TITLE
body.inverse causes modals and panels to have white text on white bg

### ISSUE THREAD

**Issue by guymguym** [mdbootstrap/mdb-ui-kit#348]
when setting `inverse` class on body it sets text color to white.
for modals which I assume they should remain light, it should reset the text to dark.
for panels I assume it should set the background to dark (though not when inside a modal).

**Comment by FezVrasta** [comment]
the inverse class is not really supported, I should add it to my todolist.

**Comment by guymguym** [comment]
@FezVrasta maybe in the meanwhile this workaround will do which at least makes the text readable:

```
body {
  background-color: #EEEEEE;
  &.inverse {
    background: #333333;
    &, .form-control {
      color: @darkbg-text;
    }

    /* elements which are left un-inverted */
    .modal,
    .panel-default,
    .card {
        &,
        .form-control {
            background-color: initial;
            color: initial;
        }
    }

  }
}
```
