### ISSUE TITLE
Enlarging the tick in the checkbox?`

### ISSUE THREAD

**Issue by Paladinoras** [mdbootstrap/mdb-ui-kit#349]
Love your design, but I have one minor issue which I'd like to ask:

I am currently trying to enlarge the native checkbox included, and while enlarging the element itself was simple, I honestly have no idea how to enlarge the tick inside. I've tried playing around with the :after and :before pseudo-elements but nothing significant changed. 

Any ideas on how to do it?

**Comment by FezVrasta** [comment]
The checkbox is a complex mix of inner box shadows, I think the easiest even if not elegant way would be to use transform: scale(x) 

Probably could be possible change the variables used in the checkbox to be relative to a single number but right now I've not time for it

**Comment by Paladinoras** [comment]
Thanks for the reply. 

Yeah I tried using transform: scale. It's not pretty but it gets the job done. Thanks for the help!
