### ISSUE TITLE
Checkboxes display:none; line 850 not displaying

### ISSUE THREAD

**Issue by phil-hudson** [mdbootstrap/mdb-ui-kit#35]
Hi guys,

Why are checkboxes on line 850 in the compiled CSS set to display none?

It's causing my checkboxes to not display - unless I'm using the class in some way wrong?

compiled/material.css - line 850:

Thanks again,
Phil

**Comment by FezVrasta** [comment]
Follow the instructions on the read me please

**Comment by phil-hudson** [comment]
`<div class="checkbox checkbox-primary form-group">    
                <label>
                  <input type="checkbox" name="rememberMe" ng-model="rememberMe" unchecked>Remember me
                </label>
              </div>`

I did :) anything wrong?

**Comment by FezVrasta** [comment]
Looks ok.. Will make some test tomorrow at office.

**Comment by phil-hudson** [comment]
awesome man, if you need any more details about my project feel free to drop me a line.

cheers

**Comment by FezVrasta** [comment]
Have you included the JS?

**Comment by FezVrasta** [comment]
Okay did some test, everything works fine, just remember to include material.js (with the latest version of material.js everything should works even without ripples.js).

**Comment by phil-hudson** [comment]
thanks, will look again
