### ISSUE TITLE
navbar uses media queries with hard coded width instead of bootstrap's variables @screen-*

### ISSUE THREAD

**Issue by guymguym** [mdbootstrap/mdb-ui-kit#352]
for example in _navbar.less it uses `@media (max-width: 767px)` and `@media (max-width: 1199px)` which can easily be replaced with `@screen-sm` and `@screen-lg` respectively...

this will allow changing to custom app values.

thanks!

**Comment by FezVrasta** [comment]
the problem is that this theme doesn't compile along with the bootstrap source. it overrides the theme, so it has no access to the bootstrap variables.

**Comment by guymguym** [comment]
I see. maybe best way to co-exist is to provide these @screen-\* variables with default values and if bootstrap is imported or other less file of the application overrides it will take the latest value?
as suggested here https://github.com/less/less.js/issues/1706 it can be done like this:

```
.my-library-defaults() {
    @a: 1;
    @b: 2;
    // etc.
} .my-library-defaults();
```

**Comment by rosskevin** [comment]
closing in lieu of #727, which aims at reuse/import of basic bootstrap variables
