### ISSUE TITLE
ripple effect is not working 

### ISSUE THREAD

**Issue by gjgit** [mdbootstrap/mdb-ui-kit#353]
ripple effect is not working  how to enable ripple effect

**Comment by timhovius** [comment]
Yes I have the same problem. I added the javascripts and the following code:

```
$(function() {
    $.material.init();
});
```

I have no console errors.

**Comment by FezVrasta** [comment]
are you using the latest master or the 0.2.1 pre release?

this is based on the latest master and works perfectly:
http://codepen.io/FezVrasta/pen/ihmea

**Comment by timhovius** [comment]
I inspected your code and found that I was forgot to include the ripple css

**Comment by FezVrasta** [comment]
okay nice :)

**Comment by krazyeom** [comment]
How do i add ripple css on Meteor? 
Checkbox and Radio button are disappear.

**Comment by gjgit** [comment]
i"m developing in asp.net and still i can"t able to figure out why ripple effect is not availble ... i did all the things 

![1](https://cloud.githubusercontent.com/assets/2841150/5690670/0f1c0d92-98c0-11e4-845f-7243684d9b44.png)
![2](https://cloud.githubusercontent.com/assets/2841150/5690671/0f2156d0-98c0-11e4-81e9-415bd67296d7.png)
![untitled](https://cloud.githubusercontent.com/assets/2841150/5690672/0f274b76-98c0-11e4-93ad-1bc9ecc7698f.jpg)

**Comment by gjgit** [comment]
i "m using visual studio still i cant able to add the ripple effect 

![1](https://cloud.githubusercontent.com/assets/2841150/5690676/601593d0-98c0-11e4-8c57-a05c8a0cc224.png)
![2](https://cloud.githubusercontent.com/assets/2841150/5690677/6031c62c-98c0-11e4-980f-b6dfc70838e0.png)
![untitled](https://cloud.githubusercontent.com/assets/2841150/5690675/5fe77d1a-98c0-11e4-86c4-6fa2e18c2e90.jpg)

**Comment by FezVrasta** [comment]
Are you using input=button? Ripple can't work on self closing elements

**Comment by timhovius** [comment]
You also need to execute the following script for the ripple effect:

```
$(function() {
    $.material.init();
});
```

**Comment by krazyeom** [comment]
I am using Meteor platform. so _Bootstrap Material Design_ was installed by **meteor add fezvrasta:bootstrap-material-design**. 

Button's ripple effect works correctly. but Check box, radio button and some effect is not working now. 

![screen shot 2015-01-11 at 8 17 14 am](https://cloud.githubusercontent.com/assets/442477/5693656/4e48efe4-996a-11e4-81b3-4b2ba0a8db84.png)

I just install material design, not added anything using by blow scripts.

``` html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
<link href="css/ripples.min.css" rel="stylesheet">
<link href="css/material-wfont.min.css" rel="stylesheet">

....
<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<script src="js/ripples.min.js"></script>
<script src="js/material.min.js"></script>
```

How do I use _Checkout, CheckBox_? I have no idea to implement it. 

![screen shot 2015-01-11 at 8 16 32 am](https://cloud.githubusercontent.com/assets/442477/5693657/4e5186e0-996a-11e4-91e6-5585b8cf892c.png)

**Comment by krazyeom** [comment]
Sorry about that. It works correctly on **main.html**. there are some mistake in the **<template> tag**

**Comment by siddhsuper** [comment]
Hi I am new to bootstrap angular material, 
I am not getting ripple effect on a anchor.
![screenshot from 2015-01-17 00 41 38](https://cloud.githubusercontent.com/assets/7190266/5782514/b3abdab0-9de1-11e4-9b91-9f5a9e2170f3.png)
![screenshot from 2015-01-17 00 42 53](https://cloud.githubusercontent.com/assets/7190266/5782519/d392e634-9de1-11e4-9021-267844417f3b.png)

Please help; I have given a screen shot of the css and js file I referred and the anchor example shown in bootstrap material design.

Regards,
Sid

**Comment by soniar4i** [comment]
I'm having problems to get the ripple to work on Safari 7.1.3 . It doesn't show any problem and it works on Chrome but in Safari the ripple begins but the transition doesn't continue. Just like the image below.

Thanks in advance :)

![captura de pantalla 2015-02-03 a la s 15 44 57](https://cloud.githubusercontent.com/assets/2337181/6022228/ac7e650e-abbb-11e4-9fd3-19623dcbf31b.png)

**Comment by FezVrasta** [comment]
This theme was not tested on safari mobile yet. Sorry.

**Comment by soniar4i** [comment]
Hi! I know how to solve the issue, as @irwing-reza pointed a while ago on #223 it has missing ":" on -moz-transform and -webkit-transform on the ripple javascript. But you forgot to include those changes on your compressed ripples.min.js too :)

Thanks anyways

**Comment by markadward** [comment]
ripple ink effect is not working on desktop safari and also on mobiles. One more this i am entegerating dropdown exctly but it is not working Please help me to sort out this. 

Thanks

**Comment by soniar4i** [comment]
@markadward make sure that you have ":" on -moz-transform and -webkit-transform ripples.min.js

**Comment by FezVrasta** [comment]
I use this now:

``` javascript
$ripple
      .css({
        "-ms-transform": "scale(" + size + ")",
        "-moz-transform": "scale(" + size + ")",
        "-webkit-transform": "scale(" + size + ")",
        "transform": "scale(" + size + ")"
      })
```

So it should not be the problem @soniar4i

**Comment by soniar4i** [comment]
Yes, it's true. I was thinking on the previous version @FezVrasta.

@markadward how it behaves when you click on a button with ripple effect. I've been working with safari on imac and I don't have any trouble with ripple or dropdown buttons.

**Comment by phtn** [comment]
###### with Meteor

``` javascript
Template.homepage.rendered = () => {
$.material.init()
}
```

_material has to initialize on render_

**Comment by ibgithub** [comment]
I also meet the same problem, the ripple effect is not working, I already  add ripples.cs and ripples.js:

```
    <link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="bower_components/bootstrap-material-design/dist/css/material.css" />
    <link rel="stylesheet" href="bower_components/bootstrap-material-design/dist/css/ripples.css" />

    <script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script src="bower_components/bootstrap-material-design/dist/js/material.js"></script>
    <script src="bower_components/bootstrap-material-design/dist/js/ripples.js"></script>
```

What should I need to add? please someone help this situation.

**Comment by ibgithub** [comment]
I create simple html index using bootstrap-material-design and the ripple effect is exist, and then I compare with my application (I am using jhipster), the different is: there is no div class="ripple-contaner" on jhipster component.
<img width="960" alt="18ripplenotok" src="https://cloud.githubusercontent.com/assets/364083/12168121/35f38fca-b4e5-11e5-813d-213ec4cc1474.png">

while on my simple index.html using bootstrap-material-design there is div class="ripple-contaner"
<img width="960" alt="16rippleok" src="https://cloud.githubusercontent.com/assets/364083/12168140/44a0b246-b4e5-11e5-8a7c-39e3c6964b77.png">

Why on my application the div class="ripple-container" is not exist? I already register the ripples.js and ripples.cs

**Comment by ibgithub** [comment]
I want to report to you guys that I already solved my problem with adding two files (css and js) from this link http://codepen.io/anon/pen/gPmJZR or http://codepen.io/zavoloklom/pen/Gubja (both are the same), I save it as ripples-alt.css and ripples.alt.js and I add class ripple-effect into my button or my menu, and now it's work (I still don't know why it not working by default, may be it conflict with other component).

```
    <link rel="stylesheet" href="bower_components/bootstrap-material-design/dist/css/material.css" />
    <link rel="stylesheet" href="bower_components/bootstrap-material-design/dist/css/ripples.css" />
    <link rel="stylesheet" href="bower_components/bootstrap-material-design/dist/css/ripples-alt.css" />


    <script src="bower_components/bootstrap-material-design/dist/js/material.js"></script>
    <script src="bower_components/bootstrap-material-design/dist/js/ripples.js"></script>
    <script src="bower_components/bootstrap-material-design/dist/js/ripples-alt.js"></script>
```

and in my button I add:
class="btn btn-raised btn-primary ripple-effect"

**Comment by watsonkelvin** [comment]
I also do not see the ripple effect. I installed using meteor add fezvrasta:bootstrap-material-design. 
Here are the tags inside my <head></head> tags

```
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.5.7/css/bootstrap-material-design.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.5.7/css/ripples.min.css" rel="stylesheet">  
<link href="https://cdn.rawgit.com/FezVrasta/dropdown.js/master/jquery.dropdown.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.5.7/js/material.min.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-design/0.5.7/js/ripples.min.js"></script>
```

**Comment by rosskevin** [comment]
@watsokel, @ibgithub, this issue has been closed since May of 2015.  Please file new issues, and for personal support please use stackoverflow.  Regarding meteor, the package has not been updated for a long time, please see Meteor package update #769.  We need help from the community if you want meteor support.
