### ISSUE TITLE
ripple effect on input type="button" not working

### ISSUE THREAD

**Issue by Blink515** [mdbootstrap/mdb-ui-kit#355]
I can't seem to get the ripple effect to work on an input with type="button". Is this as intended or just something that isn't implemented? I also tried using the withripple class on the input with no results.

**Comment by FezVrasta** [comment]
Is not possible as ripples to self closing elements, use a button tag or wrap your input inside a div

**Comment by SemihAkar** [comment]
yes it is not working for me too.
