### ISSUE TITLE
Can we Floating text (placeholder) on focus of input element?

### ISSUE THREAD

**Issue by sivailango** [mdbootstrap/mdb-ui-kit#356]
Hi,

Placeholder text moves top left after input fieds gets some value. Can we move placeholder text on focus of element?

Here they done http://materializecss.com/forms.html

**Comment by FezVrasta** [comment]
Ok actually this would be the correct behavior so I'm going to implement it soon.

**Comment by FezVrasta** [comment]
fixed with c5eb110d781487e715bcdd5828495271fabb5694
