### ISSUE TITLE
'on change' event for <select> element (dropdown menu) is not working

### ISSUE THREAD

**Issue by NoelChew** [mdbootstrap/mdb-ui-kit#362]
I have problem triggering the 'on change' event using jquery and javascript when I add 'form-control' class on my dropdown menu. I noticed that the actual <'select'> element is hidden by in-line CSS 'style= display: hidden;', and another few elements such as <'input'> and <'ul'> are generated to give a better looking UI.

The event works when I remove the 'form-control' class, but it looks ugly.

Can you show me how to trigger the onChange event with 'form-control' class?

**Comment by Antronin** [comment]
This is standard for bootstrap. There is a solution on StackOverflow:
http://stackoverflow.com/questions/25720986/bootstrap-select-how-to-fire-event-on-change

**Comment by NoelChew** [comment]
According to the solution in http://stackoverflow.com/questions/25720986/bootstrap-select-how-to-fire-event-on-change, it asks to have the event function inside $(document).ready(function() { ... }); .
My code is already in the 'onReady' function, but it is not working.

To clarify, my code works without 'form-control' class. The question is to have the 'onChange' event fired while having the 'form-control' class.

**Comment by FezVrasta** [comment]
Are you using Dropdown.js to style selects? In this case you should open an issue on the repo of that project

**Comment by NoelChew** [comment]
Yup, will do that. Thank you!

**Comment by nuno101** [comment]
I found the same issue. As a workaround I used the onclick event instead:
`jQuery('div.selector').on("click", function(e) {`

The hidden select and the other elements are all placed within `div.selector`.
