### ISSUE TITLE
Readonly Checkbox

### ISSUE THREAD

**Issue by JP-Ellis** [mdbootstrap/mdb-ui-kit#363]
It appears that the checkboxes do not obey the `readonly` attribute.  A simple codepen exame is provided [here](http://codepen.io/anon/pen/JoWpbx).

I have not yet checked if other input types are the same, nor have I checked if it obeys other attributes (e.g. disabled).

**Comment by FezVrasta** [comment]
Actually checkbox element doesn't support readonly according to W3C specs, you have to use `disabled`

**Comment by JP-Ellis** [comment]
Oh, my bad then.  I should've checked that first.  Thanks anyway :)
