### ISSUE TITLE
Linked items broken with this css

### ISSUE THREAD

**Issue by muhammadcahya** [mdbootstrap/mdb-ui-kit#364]
Thanks for great bootstrap with material design
I hope this will be better and still continous for update / enhancement feature :+1: 

For [Linked Items](http://getbootstrap.com/components/#list-group-linked) 
The result :

``` html
<div class="list-group">
  <a href="#" class="list-group-item active">
    Cras justo odio
  </a>
  <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
  <a href="#" class="list-group-item">Morbi leo risus</a>
  <a href="#" class="list-group-item">Porta ac consectetur ac</a>
  <a href="#" class="list-group-item">Vestibulum at eros</a>
</div>
```

is broken after add material css

**Comment by FezVrasta** [comment]
Hello, I'm aware of it. Not had time yet to style them.

**Comment by MarshallOfSound** [comment]
I styled these for one of my projects because I wanted them, I'll find the stuff I added and put it into a PR or something

**Comment by FezVrasta** [comment]
Great, thanks

**Comment by MarshallOfSound** [comment]
@FezVrasta The CSS I have made the components, should I be modifying it to follow the spec

http://www.google.com/design/spec/components/lists.html

As much as possible?

**Comment by FezVrasta** [comment]
actually lists are already supported, if the style is the same we could recycle the CSS

**Comment by MarshallOfSound** [comment]
Lists are technically supported through the _list.less stylesheet, but they are missing several things from the spec.  For instance, using a checkbox has the secondary item has a strange positioning glitch.  The using an avatar as the the primary action does not vertically center it when you have two lines of text in the list content.

I am going through and fixing these things so that it strictly follows the spec.  Is this OK?

**Comment by FezVrasta** [comment]
Would be great, thanks

**Comment by jerone** [comment]
:+1:

**Comment by rosskevin** [comment]
dup of #578 ?

> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
