### ISSUE TITLE
How to use bootstrap-material-design theme with Angular.js ?

### ISSUE THREAD

**Issue by prady00** [mdbootstrap/mdb-ui-kit#366]
How can I use this theme with angular js?

Solution 1-
A quick solution is to include arrive.js before material.js
What yo will achieve -
CSS will work fine but ripple effect will not. Angular's data binding will work

Solution 2-
Extend solution 1 by calling $.material.init(); when your controller is loaded
What yo will achieve -
CSS will work fine, ripple effect will work. Angular's data binding will be lost

Can you suggest a solution in which there is no loss of angular's data binding?

**Comment by FezVrasta** [comment]
Ripples.js has been rewritten and it lost the ability to apply to dynamically added elements. There is a PR to add the feature again.
https://github.com/FezVrasta/bootstrap-material-design/pull/365

You may want to try it and let me know if it fixes the problem.

**Comment by prady00** [comment]
Thanks @FezVrasta ! 
Ripples.js has been rewritten for applying rippling effect to dynamic added elements. I have achieved this earlier in solution 2 above.

When we change DOM outside of angular, the bindings are lost. firing $.material.init(); does the same! Is there any work around on this?

**Comment by FezVrasta** [comment]
Just use solution 1 using the PR I've linked.

By the way the most angular way would be to assign directives to each element and init manually each element that requires material.

**Comment by prady00** [comment]
I was wondering if we can implement ripples effect using CSS 
coz this library is too awesome to avoid, but as it manipulates DOM on init.. 
angulars's data binding is set to fire.

I am closing it for now..

**Comment by FezVrasta** [comment]
with the current CSS specifications is not possible to implement Ripples in the right way. You can create a ripple effect but will not be nice as the one with JS

**Comment by prady00** [comment]
Yes, agreed, but can we do some downgraded version. 
As I can see in issues list, most of ng-devs have stumbled around this.
To simplify: We need to achieve ripple effect without manipulating DOM.

Your work is ingenious and we angular devs are dying to use it.

**Comment by FezVrasta** [comment]
Ripples on my framework can be achieved only manipulating DOM.

**Comment by f2net** [comment]
I think it would be great to have an Angularized version of the framework with the ready-made AngularJs Directives. What do you think?

**Comment by FezVrasta** [comment]
It's something I'd like to do, I'm in touch with a guy which should help me

**Comment by mmattax** [comment]
I've started a set of directives for a rewrite we have started on our SaaS product. The directives are pretty basic for now, but  should be under pretty active development by our team over the next few days/weeks:

https://github.com/heyflock/angular-bootstrap-material

I'll also get bower support and documentation soon.

**Comment by FezVrasta** [comment]
Ah great! Once they are done please let me know and I'll add them to the readme.

**Comment by tilwinjoy** [comment]
I have created a project http://tilwinjoy.github.io/angular-bootstrap-material.  It is more like a JS rewrite for AngularJS and does not depend on jQuery and Bootstrap's JS unlike the one mentioned above.

**Comment by WilldelaVega777** [comment]
Any hope to have this great framework working on Angular 2?

**Comment by WilldelaVega777** [comment]
Is there any hope to have soon this great framework working on Angular 2?

**Comment by FezVrasta** [comment]
You have just to replace the built-in JS with custom Angular directives, the CSS works.

It's not that hard.

**Comment by zeshan098** [comment]
bootstrap metrial not load in angularjs 1. any one have solution please guide me.

**Comment by tilwinjoy** [comment]
@zeshan098  take a look at few projects mentioned above for using it with angular 1

**Comment by rspalok** [comment]
may i use it as in jsp and Spring
