### ISSUE TITLE
Dropdown menu hover and active colors

### ISSUE THREAD

**Issue by timhovius** [mdbootstrap/mdb-ui-kit#368]
Hello,

The background colors for dropdown menus are incorrect. They are bootstrap-blue.

![image](https://cloud.githubusercontent.com/assets/7972792/5801173/79fc1286-9fe8-11e4-9df4-5de78c98737f.png)

I changed the `less` by meself, something like this:

```
.dropdown-menu {
  .active {
    a {
      background-color: transparent;
      color: #333333;
    }

    a:hover {
      background-color: transparent;
      color: #009587;
    }
  }
}
```

**Comment by FezVrasta** [comment]
Where are you trying?

Here everything works:
http://fezvrasta.github.io/bootstrap-material-design/#navbar

**Comment by psenechal** [comment]
Try adding the class "active" to one of the <li> tags in the dropdown menu and you'll see what Tim is referring to. It's a common class addition for CMS apps. I'm working in Orchard CMS and it does it as well.

**Comment by timhovius** [comment]
Yes @psenechal you are right. I use this bundle with KnpMenuBundle. KnpMenuBundle added the class active when the current page matches the route of the dropdown item.
