### ISSUE TITLE
Proper way to disable a component

### ISSUE THREAD

**Issue by urecio** [mdbootstrap/mdb-ui-kit#372]
For example: 

If I don't want to affect inputs with bootstrap-material, I will set to false options.input and in addition I can add a mandatory selector to inputElements like `input.form-control.material` 

The problem is that the inputs will inherit some style from this library anyway.
Am I missing something?

**Comment by kmmbvnr** [comment]
That's common problem for any bootstrap based style. To get raw styling don't use form-control class at all.

**Comment by urecio** [comment]
I don't mean exactly raw. Just the plain bootstrap style, without bootstrap material.

**Comment by kmmbvnr** [comment]
That's impossible, untill you've build custom bootstrapp css with some another class prefix for default styles. Or just do some manual copy-paste.

**Comment by FezVrasta** [comment]
The @kmmbvnr answers are correct
