### ISSUE TITLE
Nested lists

### ISSUE THREAD

**Issue by isflavior** [mdbootstrap/mdb-ui-kit#374]
Greetings,

Is there a way to prevent the ripple effect to propagate in the `li` that contains the nested dropdown menu when you click on the second level `li`?

Example

```
<ul class="dropdown1">
    <li>AB
        <ul class="dropdown2">
            <li>a</li>
            <li>b</li>
        </ul>
    </li>
    <li>C</li>
    <li>D</li>
</ul>
```

When you click on the `li` inside the `ul` with class `dropdown2`, the ripple effect propagates to the `li` AB, which contains the second `li`.

Best Regards

**Comment by FezVrasta** [comment]
You may want to apply `ripples.js` to a wrapper element.

``` html
<ul class="dropdown1">
    <li><span class="ripple">AB</span>
        <ul class="dropdown2">
            <li><span class="ripple">a</span></li>
            <li><span class="ripple">b</span></li>
        </ul>
    </li>
    <li><span class="ripple">C</span></li>
    <li><span class="ripple">D</span></li>
</ul>
```

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
