### ISSUE TITLE
The project's wiki seems to be full of spam

### ISSUE THREAD

**Issue by ignisf** [mdbootstrap/mdb-ui-kit#376]
Hello

It seems that there is a spam issue in the wiki... 179 pages of it... :tired_face: 
Please consider restricting edit access to it.

**Comment by FezVrasta** [comment]
I didn't noticed the access was open to all... I can't find a way to delete those pages.

Clicking on them opens a white page and if I clone the wiki repository locally I can't checkout the branch because "the file name is too long"...

**Comment by ignisf** [comment]
Hmm... It clones correctly but fails to checkout on my side. However, whenever I `cd` in the cloned repo directory and do a git status, it shows all the files as staged for deletion. So theoretically this should work on your side:

```
git clone https://github.com/FezVrasta/bootstrap-material-design.wiki.git
cd bootstrap-material-design.wiki
git commit -m 'Remove spam'
git push origin master
```

**Comment by FezVrasta** [comment]
Thanks, it worked :)
