### ISSUE TITLE
bootstrap material design breaks angular typeahead

### ISSUE THREAD

**Issue by andrewljohnson** [mdbootstrap/mdb-ui-kit#377]
If you add the form-control class to an input, that input won't fire the typeahead directive.

I think this is because BMD inserts a span after the input. Is there any workaround, so I can get the input styled nicely, and also use typeahead?

**Comment by FezVrasta** [comment]
What is typehead?

**Comment by andrewljohnson** [comment]
It is an auto-complete widget, for searching while the user types.

Search for typeahead here: http://angular-ui.github.io/bootstrap/

**Comment by FezVrasta** [comment]
no idea sorry, I need these elements to style them properly...

**Comment by jerone** [comment]
Apparently the AngularJS team made a [port of Bootstrap](https://github.com/angular-ui/bootstrap) combining with AngularJS [(demo)](http://angular-ui.github.io/bootstrap/), which include an extra feature called [typeahead.js](https://twitter.github.io/typeahead.js/) (which originally was included in Bootstrap, but [later removed](http://blog.getbootstrap.com/2013/08/19/bootstrap-3-released/)).

**Comment by FezVrasta** [comment]
I'm working on a new version that will get rid of the additional span (and even the wrapper) on inputs that have not floating labels or hints

**Comment by andrewljohnson** [comment]
Sweet, thanks! I appreciate your work, and BMD is a really great template.
Work-in-progress here: http://scriber.io/demo/

Andrew Johnson
Founder
_gaiagps.com http://gaiagps.com_

**Comment by FezVrasta** [comment]
@andrewljohnson check out the license about commercial projects please.

**Comment by andrewljohnson** [comment]
Oh I see. Could we get permission to use this for a commercial project?
Could you email me details at andrew@scriber.io?

Andrew Johnson
Founder
_gaiagps.com http://gaiagps.com_

**Comment by FezVrasta** [comment]
May you checkout my last commit and test typehead with simple inputs (without floating labels) and let me know what happens?

**Comment by andrewljohnson** [comment]
Well, the search field (top right) now works with a form-control class added. But, it's not styled with the blue underline, and I don't see the animation flash (in Chrome/Mac) when the input is selected.

See: http://scriber.io/demo/

**Comment by FezVrasta** [comment]
I can't see the new CSS in your website, are you sure you are using the latest commit?

**Comment by andrewljohnson** [comment]
Pretty sure I deployed the new code.. autocomplete doesn't work if I use
the bower version, but does if I use your new version, just no styling.

Andrew Johnson
Founder
_gaiagps.com http://gaiagps.com_

**Comment by FezVrasta** [comment]
Bower installs the last stable

**Comment by andrewljohnson** [comment]
When I pull from Bower, typeahead is broken.

When I install from GitHub, typeahead works, but the textfield isn't styled
colorfully, and I don't see the flash on select.

**Comment by akhilrs** [comment]
@FezVrasta - Last commit works good, thanks.

@andrewljohnson - you are right, bower install not fetching the latest commit from the repository. But you can add the latest commit sha in bower.json to fetch the latest using bower.

"bootstrap-material-design": "https://github.com/FezVrasta/bootstrap-material-design.git#5e6f593ccb7eb47dfd6b42a7115d2c97e8517704"

**Comment by dholcombe** [comment]
Use md-autocomplete instead of typeahead if you are already using material design. No need to mix material design with ui-bootstrap.
