### ISSUE TITLE
".navbar .navbar-text" hight not reduced when navbar hight changed from 60px to 50px

### ISSUE THREAD

**Issue by rajeev1982** [mdbootstrap/mdb-ui-kit#379]
This is the css loaded when screen size is reduced.

.navbar .navbar-text {
color: inherit;
margin-top: 20px;
margin-bottom: 20px;
}

Attached is screenshot showing navbar does not work properly.
![screen shot 2015-01-26 at 5 16 56 pm](https://cloud.githubusercontent.com/assets/2239359/5899601/988ae308-a583-11e4-8c95-25fd5a85f1b5.png)

**Comment by FezVrasta** [comment]
Sorry may you outline better the problem? Are you talking about the size of the header when it changes with media queries?

**Comment by rajeev1982** [comment]
Here is the problem.
- On fullscreen browsing, the navbar is 60px high with all components (links and text) are correctly centre aligned vertically.
- When I reduce the browser size and move to medium width (col-md) the navbar hight is reduced to 50px and padding for links are reduced to 15 px (total height to 50px) but navbar-text still have height of 60px. This caused the other navbar elements to move up and not centre aligned vertically. 
- I override the css in my application css and it works fine. Here is my css. If I remove the material-design-theme and revert back to bootstrap default theme, the navbar work correctly without my custom css.

/\* Extra small devices (phones, less than 768px) */
@media (max-width: @screen-xs-max) {
  .navbar .navbar-text {
    margin-top: 15px;
    margin-bottom: 15px;
  }
}

/\* Small devices (tablets, 768px and up) */
@media (min-width: @screen-sm-min) and (max-width: @screen-sm-max) {
  .navbar .navbar-text {
    margin-top: 15px;
    margin-bottom: 15px;
  }
}

/\* Medium devices (desktops, 992px and up) */
@media (min-width: @screen-md-min) and (max-width: @screen-md-max) {
  .navbar .navbar-text {
    margin-top: 15px;
    margin-bottom: 15px;
  }
}

/\* Large devices (large desktops, 1200px and up) */
@media (min-width: @screen-lg-min) {

}

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
