### ISSUE TITLE
Broken list group item with checkbox and template on Meteor

### ISSUE THREAD

**Issue by comigor** [mdbootstrap/mdb-ui-kit#381]
When setting a checkbox as row-primary-action of a list group item by a collection loop, it won't appear.

``` html
<body>
    <div class="container">
        <div class="list-group">
            {{#each tasks}}
                {{> task}}
            {{/each}}
        </div>
    </div>
    <script>
        $(document).ready(function() {
            $.material.init();
        });
    </script>
</body>

<template name="task">
    <div class="list-group-item">
        <div class="row-action-primary checkbox">
            <label><input type="checkbox"></label>
        </div>
    <div class="row-content">content</div>
    </div>
    <div class="list-group-separator"></div>
</template>
```

**Comment by aloaiza** [comment]
Same thing here using AngularJS, checkbox inside ng-repeat won't show up after push to the items collection...it does show on initial render, but adding items later shows no checkbox...

``` javascript
<tr ng-repeat="item in todo.items">
    <td class="vert-align">
         {{item.action}}
    </td>
    <td>
        <div class="checkbox checkbox-primary">
        <label>
            <input type="checkbox" ng-model="item.done"><span class="ripple"></span>
        </label>
        </div>
    </td>
</tr>
```

**Comment by FezVrasta** [comment]
you have to include Arrive.js before Material.js, or initialize every new checkbox manually.

**Comment by comigor** [comment]
Well, I believe it should be fixed on Meteor's package then.

**Comment by aloaiza** [comment]
I can confirm that using arrive.js fixed the problem with AngularJS, thanks @FezVrasta !

**Comment by FezVrasta** [comment]
@Igor1201 most of the people prefer initialize elements manually, so I let them choose if use Arrive.js or not.

**Comment by comigor** [comment]
I see. It worked by reinitializing `$.material.checkbox()` on every addition.
It's not the most beautiful approach in my point of view, but I understood the matter.
Thank you @FezVrasta!
