### ISSUE TITLE
Move color variations to separate css in dist

### ISSUE THREAD

**Issue by SDKiller** [mdbootstrap/mdb-ui-kit#383]
As of now even minimized `material.min.css` takes 1 Mb
There are >36k strings in `material.css`.

Even IDE hangs when starts to index project after installation.
Of course you can say that one can compile with `less` what he wants, etc.

But IMO - those who is willing to compile anything will not use `material.css` from `dist`.
And who is not going to do it - deals with overbloated css file even if he does not need _pink_ or _lime_.

I suggest moving non-standard color variations to separate css file and thus make main css file **usable**.

If someone needs color variations - he will include the file.

If someone is into playing around with compilation tools - he won't even notice any drawbacks of that change.

**Comment by FezVrasta** [comment]
yes this is a great idea. 

probably have 1 file for each color + shades? (red, red-100, red-200 etc in red.css etc)

**Comment by SDKiller** [comment]
> probably have 1 file for each color + shades? (red, red-100, red-200 etc in red.css etc)

Maybe

**Comment by FezVrasta** [comment]
fixed with a4c09ab76ed95c8fe299530acf83b9a130576592
