### ISSUE TITLE
Change color text input

### ISSUE THREAD

**Issue by CorentinLeGal** [mdbootstrap/mdb-ui-kit#384]
Hello,

I can not seem to change the color of "input text" at the focus of it.

If anyone has an answer, I'm interested.
Thank you in advance

Sorry for my English.

**Comment by salem-chinsu** [comment]
By default, the input text will have "Teal" color when focus, if you want to change to other color, see the example code :

&lt;div class="form-group-material-xxx-yyy"&gt;
    &lt;input class="form-control" /&gt;
&lt;/div&gt;

where "xxx" is the color name, "yyy" is the number (hex color)

Please see the color palette : http://www.google.com/design/spec/style/color.html#color-color-palette

Example, we will change the input text to red with hex color is #f44336 (number 500)

&lt;div class="form-group-material-red-500"&gt;
    &lt;input class="form-control" /&gt;
&lt;/div&gt;

**Comment by siddhsuper** [comment]
Hi,

I tried this but it is not working for me:-

> ```
>  <div class="form-group-material-red-500">
>    <label for="inputName" class="col-lg-2 control-label">Name</label>
>     <div class="col-lg-10">
>       <div class="form-control-wrapper">
>         <input type="text" id="inputName" placeholder="Name" class="form-control">
>           <span class="material-input"></span>
>       </div>
>     </div>        
>   </div>
> ```
> 
> ![issue1](https://cloud.githubusercontent.com/assets/7190266/5954158/92d7343e-a78b-11e4-9994-7d8864ff886b.png)

**Comment by linuxson27** [comment]
Don't know why this was closed, as this is still an issue. Your custom class does not style the input

**Comment by FezVrasta** [comment]
With version 4 you have to change the color in the SCSS variables.
