### ISSUE TITLE
Dropdown menu display not correctly in ios

### ISSUE THREAD

**Issue by salem-chinsu** [mdbootstrap/mdb-ui-kit#385]
i tested this problem in ios7 and 8, the dropdown menu always display all the item (please see the attached file).
Hope you can fix this asap. Thanks.

![dropdown-error-ios](https://cloud.githubusercontent.com/assets/5398485/5951576/dae6c1e4-a79b-11e4-8e74-a84a512f5994.PNG)

**Comment by Angularjschile** [comment]
+1

**Comment by FezVrasta** [comment]
I've not an iPhone to debug the problem, I'm open to PR from you guys :)

**Comment by davidMGS** [comment]
It happens on Safari (Version 7.1.3 (9537.85.12.18)) on Mac OSX Mavericks also.

Problem lies with dropdownjs.  Needs to use long-form CSS3 transform scale definition in the CSS file (and possibly for transition and transform-origin).  Will add issue on dropdownjs repo.  Sample fix below:
(https://github.com/FezVrasta/dropdown.js/issues/11)

.dropdownjs > input.focus ~ ul {
  -webkit-transform: scale(1);
  -moz-transform:    scale(1);
  -ms-transform:     scale(1);
  -o-transform:      scale(1);
}
.dropdownjs > ul {
  position: absolute;
  padding: 0;
  margin: 0;
  min-width: 200px;
-webkit-transform: scale(0);
  -moz-transform:    scale(0);
  -ms-transform:     scale(0);
  -o-transform:      scale(0);
  z-index: 10000;
}

**Comment by FezVrasta** [comment]
continue here
https://github.com/FezVrasta/dropdown.js/issues/11
