### ISSUE TITLE
[Proposals] Change the behavior of float label

### ISSUE THREAD

**Issue by RomainLanz** [mdbootstrap/mdb-ui-kit#386]
Hi,

What do you think about change the behavior of the float label to correspond with the behavior on Polymer? (http://www.google.com/design/spec/components/text-fields.html#text-fields-floating-labels)

You can have a demo here: http://jsfiddle.net/gh2jh582/2/

**Comment by jerone** [comment]
:+1: I saw it in one of Google's apps and really like it.

I don't understand what you mean with [Polymer](https://www.polymer-project.org/)...

**Comment by RomainLanz** [comment]
It was the wrong link, I edited.

The style is the same on Polymer (If my brain don't suck), just to have a reference.

**Comment by FezVrasta** [comment]
Yes probably is better

**Comment by RomainLanz** [comment]
@FezVrasta Do you make the change or I create a PR?

**Comment by FezVrasta** [comment]
If you'd like to send a pr is more then welcome

**Comment by RomainLanz** [comment]
I don't have the time right know to write a PR. So if anybody what that behavior quickly you can just look at the fiddle and write your own PR.

Also it seems to have a bug when the input (with floating label) is already populate with the latest release.

**EDIT:** The bug appear when we put a float element.

**Comment by RomainLanz** [comment]
@FezVrasta The PR will create a BC break for the floating label.

According to the current version:

``` html
<input type="text" class="form-control floating-label" placeholder="floating label">
```

In my version:

``` html
<div class="form-group">
    <label class="floating-label">Label text</label>
    <input type="text" class="form-control">
</div>
```

**Comment by FezVrasta** [comment]
Looks good

**Comment by RomainLanz** [comment]
But all person using `floating-label` need to rewrite all the code to handle the new version. Maybe better to keep that and to use http://materializecss.com/forms.html if you want special things.

**Comment by FezVrasta** [comment]
I've not problems in losing compatibility with old versions. This theme is still in development and I warn users about this possible problem.

**Comment by FezVrasta** [comment]
done
