### ISSUE TITLE
Ripples not working as expected in table element

### ISSUE THREAD

**Issue by eweseong** [mdbootstrap/mdb-ui-kit#388]
Hi I'm trying to incorporate the ripples effect with each table row (tr) click, but unfortunately table related element doesn't wrap absolute div and hence the ripples effect is not working as expected. I was wondering anyone have any alternative to solve that issue? http://jsfiddle.net/4ds8exc0/1/ this is a sample fiddle of what i ask talking about

**Comment by FezVrasta** [comment]
Please use StackOverflow, maybe someone can help you.
