### ISSUE TITLE
Checkbox does not appear

### ISSUE THREAD

**Issue by Obiwarn** [mdbootstrap/mdb-ui-kit#389]
I use Meteor. Everything works great including ripples, etc.

But checkboxes do not appear, just the text when I use:

<div class="sample1">
  <div class="checkbox">
    <label>
      <input type="checkbox"> Notifications
    </label>
  </div>
  <p class="hint">Notify me about updates to apps or games that I've downloaded</p>
</div>

**Comment by FezVrasta** [comment]
can you provide a demo to see the problem? I really don't know meteor so much so without see it I can't understand.

**Comment by Obiwarn** [comment]
hm....it seems that some of the JS is not working.

I also cannot get the dropdown.js to work.

Any ideas?

**Comment by RomainLanz** [comment]
@obiwarn Did you write `$.material.init();` or `$.material.checkbox();` on your body?

**Comment by 255kb** [comment]
@obiwarn i had the same problem, this is due to the fact that material elements are initialized before the template is rendered by Meteor. 
As @RomainLanz said you must use `$.material.checkbox();` or `$.material.init();`.
Put this after the _template_ has been rendered, by using Meteor `rendered` function; like this:

``` javascript
Template.myTemplate.rendered = function(){
    $.material.init();
};
```

I think that this issue can be closed as it is not directly related to Bootstrap material design.

**Comment by Obiwarn** [comment]
Thank you! 

Checkbox & radio work great now. 

However, dropdowns still not :-(

**Comment by FezVrasta** [comment]
dropdowns are provided by dropdown.js (https://github.com/FezVrasta/dropdown.js)

**Comment by Obiwarn** [comment]
I know. But this did not work for me in Meteor:

$(".select").dropdown({ "autoinit" : ".select" });

**Comment by FezVrasta** [comment]
sorry without an example (codepen or similar) I can't say why it's not working.

**Comment by MrDanMacDonald** [comment]
Great work!  I am having the same issues with the checkbox (and all of the form animations) in my rails app - the checkbox doesn't appear, nor do any of the animations.  

Any suggestions?

**Comment by FezVrasta** [comment]
Did you init them?

**Comment by jeromin** [comment]
Hello, I think i got the same problem but only in specific browser (up-to-date).
Works perfect on firefox (the ripple effect and css display)
But the css tag "animation" isn't found on chrome and safari (and mobiles .) so no ripple effect
You take a look at the different browser display... it doesn't work where your bootstrap elements page perfectly works.
As it works perfectly on firefox, i'm wondering if the "webkit-transform" exists somewhere, I didn't fine it in less files.

I also have trouble overriding the color using a custom less file with primary and my color but nothing after less recompiling, the colors is stil green ..

I'm using the symfony bundle. Css is rewritten using less in assetic
http://browsershots.org/http://dev.jeromin.fr/

Thanks for your help and sorry if i disturb.

**Comment by MrDanMacDonald** [comment]
@FezVrasta Hi Fez, I haven't tried that yet but definitely will.

**Comment by phtn** [comment]
Template.homepage.rendered = () => {
    $.material.init()
}

_material has to initialize on render_
