### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#39]
Hey!

I love your new theme for bootstrap. I would love if the colors were much lighter. Right now they are too bright compared to some other material themes (http://bootswatch.com/paper/).

Thanks!

**Comment by wb14123** [comment]
It's true. +1 for this.

**Comment by ghost** [comment]
Personally I think the Paper theme colors.

**Comment by FezVrasta** [comment]
I'm using the official Google Material Design color palette.

**Comment by ghost** [comment]
The color palette has a lot of colors. The ones you chose are too bright. Just sayin'.

**Comment by FezVrasta** [comment]
Are the same used by the official polymer paper project and the angularjs paper project...
