### ISSUE TITLE
Black text on buttons with LESS

### ISSUE THREAD

**Issue by f2net** [mdbootstrap/mdb-ui-kit#394]
I included the material.less into my main less file, but I see the button text as black instead of white:
`<a class="btn btn-primary">Ciao</a>`

From Chrome Inspector:
.btn-primary:not(.btn-link):not(.btn-flat) {
background-color: #009587;
color: #333333;
}

While on your demo page I see:
.btn-primary:not(.btn-link):not(.btn-flat) {
background-color: #009587;
color: rgba(255,255,255,.84);
}

What could that be?

Thank you,
Matteo

**Comment by jerone** [comment]
In Chrome Developer Tool you can define the [color format](https://developer.chrome.com/devtools/docs/settings#color-format)...

**Comment by f2net** [comment]
The color on the buttons is white if I use the compiled CSS file, while it is black if I import the less file.

**Comment by adtennant** [comment]
This also affects the text on the navbar.

**Comment by johannchen** [comment]
When I use the Meteor package, it's the other way around. btn-default has white text instead of black text.

**Comment by johannchen** [comment]
btw, is v0.2.2 pushed to meteor atmosphere? thanks for all the good work!

**Comment by houston88** [comment]
ditto, had to write some less to override

**Comment by FezVrasta** [comment]
can someone confirm if the bug is still around with the new commits?

**Comment by houston88** [comment]
I still seem to have the problem after updating to 0.3.0. Also the ripples don't appear to work anymore, but have not had a chance to look into yet.

**Comment by capi-trulii** [comment]
I set the @btn-success-text variable to white but the text for a btn-success looks still in black :( why?

**Comment by FezVrasta** [comment]
When I compile from source the text is white... I wonder where is the problem

**Comment by gabadi** [comment]
I'm having the same problem, this appears in v0.2.2

**Comment by Invis1ble** [comment]
``` less
@path_bootstrap_material: '@{path_bower}bootstrap-material-design/less/';

@import '@{path_bootstrap_material}material-fullpalette.less';
@import '@{path_bootstrap_material}roboto.less';
@import '@{path_bootstrap_material}ripples.less';
```

black color in `0.3.0`

in Chrome inspector

``` css
.btn-warning:not(.btn-link):not(.btn-flat) {
  background-color: #ff5722;
  color: #333333;
}
```

@ _mixins_fullpalette.less:88

**Comment by Denoder** [comment]
yea im getting this too. Trying to fix it for myself.

for me the affected code is:
_mixins_fullpalette.less

```
.background-variations(@extra, @default) {
  .generic-variations(@extra, @default, {
      background-color: @material-color;
      color: @text-color;
      & when (@material-color = @btn-default) {
        color: @lightbg-text;
      }
    });
}
```

**Comment by FezVrasta** [comment]
A PR to fix it would be very welcome :(

**Comment by Denoder** [comment]
i think i fixed it :D
changed:

```
.background-variations(@extra, @default) {
  .generic-variations(@extra, @default, {
      background-color: @material-color;
      color: @text-color;
      & when (@material-color = @btn-default) {
        color: @lightbg-text;
      }
    });
}
```

to

```
.background-variations(@extra, @default) {
  .generic-variations(@extra, @default, {
      background-color: @material-color;
      color: contrast(@material-color, @lightbg-text, @darkbg-text, @contrast-factor);
      & when (@material-color = @btn-default) {
        color: @lightbg-text;
      }
    });
}
```

and all the dark text to light text variations worked for me.

**Comment by gabadi** [comment]
I've to do the same in the navbar and i don't know if this must be done i the alerts too

**Comment by tylervick** [comment]
This is also an issue for me. @Teranode 's solution worked great for all btn classes. However, the navbar still remains with a black background for me.

I'm using bower packages of bootstrap/bs-material-design. Using Laravel's Elixir package to compile the less with the following:

```
@import '../bower/bootstrap/less/bootstrap';
@import '../bower/font-awesome/less/font-awesome';
@import '../bower/bootstrap-material-design/less/material';


// Material Design
@primary: @blue-grey;
// White bg color on text
.background-variations(@extra, @default) {
  .generic-variations(@extra, @default, {
    background-color: @material-color;
    color: contrast(@material-color, @lightbg-text, @darkbg-text, @contrast-factor);
  & when (@material-color = @btn-default) {
    color: @lightbg-text;
  }
  });
}
```

Anyone else find a way to make the navbar text white? At least until a fix comes...

**Comment by Invis1ble** [comment]
@FezVrasta, check out my PR. It should fix this issue.
