### ISSUE TITLE
Wrong border-radius on list-group-item inside panel

### ISSUE THREAD

**Issue by f2net** [mdbootstrap/mdb-ui-kit#395]
While panel has 2px border-radius, the first (last) list-group-items have top (bottom) border radius of 3px. You don't see it unless you set a color to an item.

**Comment by FezVrasta** [comment]
I can't reproduce, can someone provide me an example or a screenshot?

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
