### ISSUE TITLE
Ripple effect with angular

### ISSUE THREAD

**Issue by stlouisweb** [mdbootstrap/mdb-ui-kit#398]
I've read through the past issues with ripple and angular, and I have included the arrive.js script (I think, there are a couple projects called arriveJS so I'm not sure which one).
Still I can't get the ripple effect working and angular data-binding working simultaneously.
Can somebody put up a codepen or fiddle of this working??
I just installed BMD and arrive tonight via bower.

**Comment by FezVrasta** [comment]
better ask on stackoverflow.
