### ISSUE TITLE
Weird input texts style using form-control

### ISSUE THREAD

**Issue by rougin** [mdbootstrap/mdb-ui-kit#399]
Hello! After I downloaded the latest version from the [Bootstrap Elements](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html) page, try it out, and it seems that the `.form-control` is very weird. Even on the navbar. I cant see the text that I typed on the `.navbar-form`. I also copied the navbar and the form from the same page.

![screenshot from 2015-01-31 15 13 25](https://cloud.githubusercontent.com/assets/6078637/5987238/e28af8ae-a95b-11e4-93b1-2d458528daaa.png)

**Comment by FezVrasta** [comment]
Are you on master or on latest stable?

**Comment by rougin** [comment]
Oh. I did not carefully check the link. According to the Bootstrap Elements page, it is in [master](https://github.com/FezVrasta/bootstrap-material-design/archive/master.zip).
