### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by roeku** [mdbootstrap/mdb-ui-kit#4]
[Lists](http://www.google.com/design/spec/components/lists.html#lists-usage) are probably going to be used a lot in material design. Might be handy to have an example ready that fits material design specification.

I'm still working on mine: 
![image](https://cloud.githubusercontent.com/assets/7256461/4163847/4478c508-34ec-11e4-872f-ae9732918731.png)

Trying to create something like this:
![material design lists](http://material-design.storage.googleapis.com/images/components-recommendedtwolinelists-8_large_mdpi.png)

**Comment by FezVrasta** [comment]
yes it could be a nice addition but I'll have to put it in a secondary stylesheet, I don't want to fill the core stylesheet with too much stuff which some people could not use at all.

**Comment by roeku** [comment]
Sure thing, it would be nice to choose the element you want to use, though having too many different stylesheets might give performance issues?

**Comment by FezVrasta** [comment]
I had in mind just the core stylesheet and the additional one with all the stuff which is not "core".

By the way the entire project is written with LESS and every part of the theme is in a specific less file, you could just download the source and compile the theme with just what you really need.

**Comment by FezVrasta** [comment]
Added them inside the core of the theme, them are the Bootstrap "list groups".

**Comment by roeku** [comment]
The font size of .list-group .list-group-item .list-group-item-heading seems a bit big compared to the examples, i believe font-size: 16px; suits it better and would do make margin-bottom: 0;

**Comment by FezVrasta** [comment]
agree with the margin bottom but not with the font size, the screenshot you have provided is resized, so everything looks smaller than how it should be.

**Comment by roeku** [comment]
You might be right. According to the material design website in the [lists section](http://www.google.com/design/spec/components/lists.html#lists-keylines) it says 16sp but that has multiple px variations according to the screen density.

**Comment by FezVrasta** [comment]
I'll try to fix the sizes according to the documentation.
