### ISSUE TITLE
Add SASS support

### ISSUE THREAD

**Issue by pengux** [mdbootstrap/mdb-ui-kit#40]
There is currently official support for SASS in Twitter Bootstrap here https://github.com/twbs/bootstrap-sass. Would be nice if material design could support SASS too.

**Comment by FezVrasta** [comment]
At the moment I'm focusing on add features to the project, once I'll have most of the needed features ready I'll add support for SASS.

There is an (outdated) fork of this project with SASS support, if someone wanna mantain it feel free to proceed.

https://github.com/patw0929/bootstrap-material-design

**Comment by scottromack** [comment]
+1

**Comment by TransitoryBliss** [comment]
I'm working on a SASS port that I will try and maintain to the best of my abilities. It should be up later today.

**Comment by pengux** [comment]
I will try to help you maintain it...

**Comment by FezVrasta** [comment]
thanks guys :)

**Comment by TransitoryBliss** [comment]
pengux, if I push up my fork changes - mind helping me with the conversion?

**Comment by pengux** [comment]
No problem, :shipit:

**Comment by TransitoryBliss** [comment]
https://github.com/shockwork/bootstrap-material-design-sass

**Comment by pengux** [comment]
@shockwork can you add issues so I can share the work with you?

**Comment by TransitoryBliss** [comment]
Done :)

**Comment by TransitoryBliss** [comment]
So the fork is now working. There is some mixins left (for slider) but that's basically the only missing feature currently.

**Comment by pengux** [comment]
:+1:

**Comment by FezVrasta** [comment]
What about include the SASS files inside the main branch?  Maybe as a subrepository or something like this. I think would be better for users, instead of have different repositories, bower packages, npm packages etc...

**Comment by TransitoryBliss** [comment]
FezVrasta do you have any chat client we could talk on? So these guys don't get spammed

**Comment by FezVrasta** [comment]
http://mywebexpression.com:3001/

ahahah this project was awesome, by the way we can talk there, I'll shut down it in few days.

**Comment by TransitoryBliss** [comment]
We decided to merge my sass fork into the main project 84e18436d09733b9720b7d620ead3d8f2b44349c. Closing.

**Comment by FezVrasta** [comment]
yea thanks :D
