### ISSUE TITLE
small button size variations

### ISSUE THREAD

**Issue by jssevestre** [mdbootstrap/mdb-ui-kit#403]
Button sizes are not very distinct: 

![screenshot - 02022015 - 14 37 59](https://cloud.githubusercontent.com/assets/1177459/6001362/42fbc4f0-aae9-11e4-84d5-94125e9c54c6.png)

`.btn` has a padding (8px 30px)  which is not overwrite by `.btn-sm`, `.bt-lg` and `.btn-xs`.

**Comment by FezVrasta** [comment]
Will look into this, thanks

**Comment by wopian** [comment]
:+1: `xs` is pretty much the same size as `sm`
