### ISSUE TITLE
Dropdowns don't work

### ISSUE THREAD

**Issue by BrianKrohn** [mdbootstrap/mdb-ui-kit#405]
I have been able to get all other controls to work, but all examples of dropdowns fail.  Is there some missing code somewhere?  I can get the nav to render, but when you click the dropdown, nothing happens.

`<ul class="nav nav-tabs" style="margin-bottom: 15px;">`
`<li class="active"><a href="#home" data-toggle="tab">Home</a></li>`
`<li><a href="#profile" data-toggle="tab">Profile</a></li>`
`<li class="disabled"><a>Disabled</a></li>`
`<li class="dropdown">`
`<a class="dropdown-toggle" data-toggle="dropdown" href="bootstrap-elements.html" data-target="#">`
`Dropdown <span class="caret"></span>`
`</a>`
`<ul class="dropdown-menu">`
`<li><a href="#dropdown1" data-toggle="tab">Action</a></li>`
`<li class="divider"></li>`
`<li><a href="#dropdown2" data-toggle="tab">Another action</a></li>`
`</ul>`
`</li>`
`</ul>`

**Comment by BrianKrohn** [comment]
Let's try that code post again:

`<ul class="nav nav-tabs" style="margin-bottom: 15px;">`
`    <li class="active"><a href="#home" data-toggle="tab">Home</a></li>`
`    <li><a href="#profile" data-toggle="tab">Profile</a></li>`
`    <li class="disabled"><a>Disabled</a></li>`
`    <li class="dropdown">`
`        <a class="dropdown-toggle" data-toggle="dropdown" href="bootstrap-elements.html" data-target="#">`
`            Dropdown <span class="caret"></span>`
`        </a>`
`        <ul class="dropdown-menu">`
`            <li><a href="#dropdown1" data-toggle="tab">Action</a></li>`
`            <li class="divider"></li>`
`            <li><a href="#dropdown2" data-toggle="tab">Another action</a></li>`
`        </ul>`
`    </li>`
`</ul>`

**Comment by FezVrasta** [comment]
You must use dropdown.js

**Comment by BrianKrohn** [comment]
Thank you.
