### ISSUE TITLE
Error: can't find config file: .jshintrc right after cloning and NPM install

### ISSUE THREAD

**Issue by versedi** [mdbootstrap/mdb-ui-kit#406]
Hello guys,

I've just cloned fresh bootstrap-material-design, went with npm install and now when I try to grunt build I got an error:

```
Running "jshint:all" (jshint) task
ERROR: Can't find config file: .jshintrc
```

Gruntfile.js is perfectly identical as here. If I copy original  jshintrc from Bootstrap and run grunt build I get an error:

```
Gruntfile.js
line 22 col 56 Extra comma <it breaks older versions of IE>
line 35
line 48
line 1
line 4
line 169
....
scripts/material.js
line 5 col 3 Missing "use strict" statement.
Aborted due to warnings.
```

Any clues? When running only grunt less it works...

**Comment by FezVrasta** [comment]
I could be wrong but `grunt build` could be outdated... need to check it

**Comment by tylervick** [comment]
Also experiencing this issue on a new clone/npm install too.

**Comment by FezVrasta** [comment]
changed the grunt task. it should be ok now

**Comment by tylervick** [comment]
I installed the package to a new directory with v0.3.0 and I was still receiving the error.
Instead of removing the jshint option in the Gruntfile, I had to manually download the .jshintrc from the repo.

It seems that the bower.json file manually ignores the .jshintrc file. Not sure if you had intended to ignore this file but that was the cause of my experience.

**Comment by FezVrasta** [comment]
I see... I'll try to fix it soon

**Comment by gdvallance** [comment]
This is an issue for me too. 

I can confirm that copying .jshintrc from repo into the `bootstrap-material-design` folder and running `grunt build` works as per `tylerjvick` above.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
