### ISSUE TITLE
ripple an element with a javascript command

### ISSUE THREAD

**Issue by andrewljohnson** [mdbootstrap/mdb-ui-kit#407]
I'd like to be able to trigger a ripple on an element at the end of a different transition.

See this movie: https://www.dropbox.com/s/zraakiq1azo8imn/bounce.mov?dl=0

I'd be cool to easily be able to ripple the bullets, instead of bouncing them.

**Comment by FezVrasta** [comment]
yes in fact it would be really cool. but it would need very huge edits of ripples.js I think...

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
