### ISSUE TITLE
Disabled Textarea does not display correctly

### ISSUE THREAD

**Issue by GradyD** [mdbootstrap/mdb-ui-kit#408]
I am using material.min.css and when I tack on the disabled tag for a textarea it does not include the proper background color.

I checked on the example page and it is using the wfont version and it is rendering correctly.

![image](https://cloud.githubusercontent.com/assets/994964/6030338/d6c1fa84-abc4-11e4-8b94-2d0324af099d.png)

It also does not display the dashed line correctly. It has this CSS

![image](https://cloud.githubusercontent.com/assets/994964/6030375/105c20b2-abc5-11e4-9ea9-192cf6099302.png)

I had to remove the solid in order to get the dashed to display correctly. Again, this looks correct on the example page.

**Comment by FezVrasta** [comment]
Which version are you using?

**Comment by GradyD** [comment]
When I cracked open the package.json it has a version of   "0.2.0".

**Comment by FezVrasta** [comment]
may you provide me an example? codepen

**Comment by GradyD** [comment]
Issue was with order CSS files were loaded in.
