### ISSUE TITLE
Add support for vertical sliders

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#41]
noUiSlider vertical support

**Comment by nelsonomuto** [comment]
i can look into this, assign to me.

**Comment by FezVrasta** [comment]
thank you :)

**Comment by celestejoyce25** [comment]
Im new and jest dont understand all of the information help please and thank you?!

**Comment by celestejoyce25** [comment]
New at this and I don't quite understand the information please help please and thank you?!

**Comment by FoxxMD** [comment]
@celestejoyce25 what are you trying to do? if you need some help you are welcome to ask me at matt.duncan13@gmail.com

**Comment by npvn** [comment]
@FoxxMD Upvoted :D

@celestejoyce25 You are welcome to contact me too: hi@nguyenphuc.info. I'm also a non-native English speaker (I don't live in an English-speaking country and I learnt English as a second language), so maybe you will find it easier to talk to me.

**Comment by FezVrasta** [comment]
@nelsonomuto any news about this issue?

**Comment by nelsonomuto** [comment]
Sorry, a bit busy with office work, I will try and squeeze some hours
tomorrow to focus on this issue.

On Sat, Oct 18, 2014 at 10:19 AM, Fez Vrasta notifications@github.com
wrote:

> @nelsonomuto https://github.com/nelsonomuto any news about this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FezVrasta/bootstrap-material-design/issues/41#issuecomment-59615280
> .

## 

Thanks,
Nelson Omuto
cell: 678-301-8297

**Comment by blckdragon** [comment]
hello! does this have a navbar with a navigation drawer? thanks!

**Comment by blckdragon** [comment]
Oh sorry, when i viewed it on mobile it does have a hamburger button for its navigation drawer. Can you tell me how to make it in a default view where the hamburger is always present and i have to click or hover to it to see the navs? Im working on my website ans i really like this work. Thumbs up!

**Comment by nelsonomuto** [comment]
@FezVrasta I have begun working on the issue and narrowed down the problem to be lack of css styling for .noUi-vertical class. I have my work in my fork on this branch https://github.com/nelsonomuto/bootstrap-material-design/tree/feature/verticaluislider.

Once you run grunt serve, navigate to sliders page, http://localhost:8040/sliders.html to view vertical sliders work in progress.

**Comment by FezVrasta** [comment]
I needed them for one of my personal projects so I've implemented them by myelf. I've not tested them very well so maybe you could improve my implementation if it has some missing feature.

**Comment by nelsonomuto** [comment]
That's fine, I like what you did so far. I have no need for them personally
so I won't focus too much energy on that for now.

I would advise employing unit testing on any new functionality moving
forward though.

On Wed, Nov 12, 2014 at 6:25 AM, Fez Vrasta notifications@github.com
wrote:

> I needed them for one of my personal projects so I've implemented them by
> myelf. I've not tested them very well so maybe you could improve my
> implementation if it has some missing feature.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FezVrasta/bootstrap-material-design/issues/41#issuecomment-62704674
> .

## 

Thanks,
Nelson Omuto
cell: 678-301-8297

**Comment by FezVrasta** [comment]
@nelsonomuto please stop flooding here...

**Comment by FezVrasta** [comment]
@nelsonomuto please stop...

**Comment by nelsonomuto** [comment]
Sorry not sure why you are getting these, I think something hacked my email. :(
