### ISSUE TITLE
Move colors to separate css files

### ISSUE THREAD

**Issue by eccentrikit** [mdbootstrap/mdb-ui-kit#414]
Is there a way to color text using material colors like this:

``` html
<span class="text-material-blue">Some text</span>
<a href="#" class="link-material-blue">Some link </a>
```

**Comment by DiMaNacho** [comment]
I **vote +1** for this feature!

**Comment by gasolin** [comment]
why not change the text color in CSS, maybe with css variable?

**Comment by DiMaNacho** [comment]
@gasolin why not change everything with CSS? :-1:

**Comment by gasolin** [comment]
currently there are 17 colors in bootstrap-material-design, each color has 9 level varient (red-100, red-200). 

In #383 people already indicate material.min.css takes over 1 Mb and >36k strings in material.css.
Introduce these 2 new syntax looks simple but might contribute a visible volume on base library. 
And size does matter for the load performance.

I'm not sure why bootstrap does not include these syntax but I believe they might got some similar consideration as well.

**Comment by eccentrikit** [comment]
Why not release them as optional files?

**Comment by DiMaNacho** [comment]
@gasolin: Excellent answer.

**Comment by DiMaNacho** [comment]
@eccentrikit it's a possibility, but, I think, is not friendly for work with CDN. (Sorry for my bad english).

**Comment by FezVrasta** [comment]
I was considering moving each color to a separated css and let users load the one they need.

**Comment by DiMaNacho** [comment]
It's an excellent idea! :+1:

**Comment by rosskevin** [comment]
Colors are now exclusively configured via variables in 0.5.0.  

Please [check the release notes before jumping in](https://github.com/FezVrasta/bootstrap-material-design/releases/tag/0.5.0).
