### ISSUE TITLE
Ripple behaving oddly in FireFox when clicking on Nav links

### ISSUE THREAD

**Issue by etmarch** [mdbootstrap/mdb-ui-kit#415]
On Chrome and Safari the ripple animation is smooth no matter what input is pressed. In FireFox however, the ripple animation is very "blocky" and choppy, instead of a continous smooth animation. This only happens when clicking a link that takes you to a different route, and the loading of the new route is very choppy as well. When I click on the 'active' link, AKA the the link for the route I am already on, the ripple animation is smooth like the other two browsers. Also, in Firefox the more I click around to different routes, the slower my app gets until FireFox pretty much becomes unresponsive. Could this be a memory leak?

**Comment by etmarch** [comment]
Also forgot to mention: Modals (using with Yogiben:autoform-modals package) appear very briefly then disappear, on all browsers.

**Comment by teknologist** [comment]
I confirm modals briefly appear and disappear in flash, even without using autoform.
I am using a standard form.

**Comment by FezVrasta** [comment]
I don't think I can support every single plugin out there... If you give me a workaround to fix this problem I can implement it (aka, send me a PR).

**Comment by etmarch** [comment]
I think this may be related to the dependency on twbs: bootstrap, as I am using a custom bootstrap implementation. Is it possible to remove the hard dependency on twbs:bootstrap?

**Comment by GradyD** [comment]
I think that removing the bootstrap dependency would mean more work to maintain the project and also take away from the purpose of this theme. I would say this is out of scope being that this is bootstrap theme.

**Comment by FezVrasta** [comment]
closing as related to some unknow plugin, PR are welcome..
