### ISSUE TITLE
Why jquery ~2.1.1 is needed, when bootstrap ask for >=1.9.1 ?

### ISSUE THREAD

**Issue by hokkos** [mdbootstrap/mdb-ui-kit#416]
Hi,
Why jquery ~2.1.1 is needed, when bootstrap ask for >=1.9.1 ?
Does this project need thing only found in jquery >1.9.1, would it be possible to add more lenient dependencies ?

Thanks.

**Comment by FezVrasta** [comment]
really no reason, it was just the version installed by default when I've installed jquery... it may be changed to something less restrictive.
