### ISSUE TITLE
Input with DatePicker

### ISSUE THREAD

**Issue by joaopedronardari** [mdbootstrap/mdb-ui-kit#418]
I tried to use Input with DatePicker - Like in bootstrap and doesn't work.

**Comment by FezVrasta** [comment]
please may you provide an example? (use this as base: http://codepen.io/FezVrasta/pen/ihmea)

**Comment by joaopedronardari** [comment]
Hi @FezVrasta 

I tried to use with http://tarruda.github.io/bootstrap-datetimepicker/, but doesn't work. I will paste it in codepen later, ok?

**Comment by GradyD** [comment]
I just confirmed that http://eonasdan.github.io/bootstrap-datetimepicker/ works without any issues, tested in one of our internal apps. Just to point out also, if you are updating/creating a new project I would avoid anything that is already out of dated an unsupported. 

I also threw together a quick pen for tarruda version (specific one in question), http://codepen.io/anon/pen/vEWozX

Styling is not great but it does show that it works.

**Comment by rcevs** [comment]
Are the "Today Button" and "Clear Button" showing up correctly in Eonasdan's datetimepicker? I'm getting the Time Picker Button instead. Thanks.

**Comment by GradyD** [comment]
I will have to get into one of our dev environments and try that, currently we do not use either of those options. But if you are invoking them correctly in the javascript options it should work, especially since it is not related or overridden using this framework.

**Comment by joaopedronardari** [comment]
Thanks @GradyD, I will try to use bootstrap-datepicker with material-bootstrap.

**Comment by rcevs** [comment]
Thanks @GradyD. It is working correctly, I had an error within my code. Regards.

**Comment by japita-se** [comment]
Also here doesn't work. If I do not import the md  .css, the bootstrap-datepicker works.
The problem is with d
```
.dropdown-menu {
  display: none;
  padding: .25rem 0;
  border: 0;
   opacity: 0; 
 transform: scale(0); 
  transform-origin: 0 0;
  will-change: transform, opacity;
  transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1), opacity 0.2s cubic-bezier(0.4, 0, 0.2, 1); }

```
in particular opacity and transform
