### ISSUE TITLE
input effect does not work in IE

### ISSUE THREAD

**Issue by GradyD** [mdbootstrap/mdb-ui-kit#420]
I can confirm (from multiple users) that the effect on inputs do not work in IE11 and IE10. This effects <input> and <textarea> tags.

Looking into the error I am not getting any javascript errors so I am assuming this is 100% css that is breaking. 

I took a quick look at the input.less file but I did not see any CSS errors.

**Comment by GradyD** [comment]
Looking into this I have narrowed it down to one mixin, .form-group in _inputs.less (starts on line 96).

It looks like `linear-gradient` needs more parameters, https://msdn.microsoft.com/en-us/library/ie/hh673532(v=vs.85).aspx unless it should be "to bottom",

> Not including any keywords or angle is equivalent to "to bottom".

**Comment by GradyD** [comment]
Just trying to provide as much information as possible. So the input effect works in chrome and firefox, I am using the same internal page on all three browsers. 

What is weird is when I go to http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html using IE the input effect works. 

What could be causing this?

**Comment by FezVrasta** [comment]
I've changed the css of the inputs lately, the demo uses the old version.

**Comment by GradyD** [comment]
Dang, I assume you are referring to comment, https://github.com/FezVrasta/bootstrap-material-design/commit/dbe4705ef8c10e6f5b3eb31ea169d5c8e0ceafd9

This is a pretty big commit, could you be more specific as to the changes you have made? Or provide some example markup with the new CSS applied?

**Comment by FezVrasta** [comment]
This is the relevant part:
https://github.com/FezVrasta/bootstrap-material-design/commit/dbe4705ef8c10e6f5b3eb31ea169d5c8e0ceafd9#diff-e3a8a0ce5365e76612f427d96b4d764eR36

With the new CSS I use two linear-gradient as input background, using the CSS multi background support I animate the one on top and expand it to be 100% width.

**Comment by GradyD** [comment]
Just an update on this. Starting in v.0.3 the inputs look much better and are only missing the underline effect.

**Comment by FezVrasta** [comment]
The problem should not be the multi-background support according to caniuse...
http://caniuse.com/#search=background%20multi

I've not a windows machine to test the inputs on IE... may you try this example and see if in IE it's animated?
http://davidwalsh.name/demo/multiple-background-css-animations.php

**Comment by GradyD** [comment]
That example works. I also tested the demo page, http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html, and it does not work either. 

Very weird bug.

**Comment by FezVrasta** [comment]
can you hover it?

http://codepen.io/FezVrasta/pen/MYZegy

**Comment by GradyD** [comment]
When I hover it does not transition, it switches to the green instantly

**Comment by jerone** [comment]
@FezVrasta commented on [19 mrt. 2015 14:47 CET](https://github.com/FezVrasta/bootstrap-material-design/issues/420#issuecomment-83587834):

> can you hover it?
> 
> [http://codepen.io/FezVrasta/pen/MYZegy](http://codepen.io/FezVrasta/pen/MYZegy)

The transition **doesn't work on IE11 and IE10** (Codepen doesn't support lower versions). No errors. The green is shown instantly on hover. Transition does work on Firefox.

**Comment by FezVrasta** [comment]
yes sorry, forgot the autoprefixer, now it should animate.

By the way looks like the problem is not in the animation itself...

**Comment by FezVrasta** [comment]
@GradyD may you try my last commit? I've removed some useless CSS... maybe it fixed the problem

**Comment by GradyD** [comment]
Just testing this on the demo page, http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html, and nothing appears to be different. Did your changes get built and pushed?

**Comment by FezVrasta** [comment]
I don't think so. The commit is
56a6d8d8ee5326a3e1f1ab067011411b8c6acf66

**Comment by rosskevin** [comment]
@GradyD is this still a problem?  A lot has changed since April.

**Comment by seerjun** [comment]
I found issue regarding the input field which is 
background-image: linear-gradient(#009688, #009688), linear-gradient(#d2d2d2, #d2d2d2);
background-position: center bottom, center calc(100% - 1px);

web browser engines -moz-linear-gradient, -webkit-linear-gradient, -o-linear-gradient, -ms-linear-gradient are not added for the linear-gradient

calc is not supported by some older version browser, not sure if it is appropriate to add background-position: center bottom, center 99%; as a fallback

**Comment by FezVrasta** [comment]
calc is supported by all the recent (and not) browsers: http://caniuse.com/#search=calc
IE8 is not supported by this theme anyway.

the prefixed versions of `linear-gradient` are automatically added by autoprefixer

**Comment by rosskevin** [comment]
I'm going to close this issue as stale.  Let's open something new if needed.
