### ISSUE TITLE
ripples effects for some elements does not fire on mobile

### ISSUE THREAD

**Issue by Proxy305** [mdbootstrap/mdb-ui-kit#424]
Hi,
I recently noticed that the ripple effects for some elements don't fire on (probably some) mobile phones. 

I tested the two demo pages:
- http://fezvrasta.github.io/bootstrap-material-design/
- http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

on my phones:
- Android 4.4.4
  - Default Android Browser
  - Chrome Browser
- Android 4.1.2
  - Default Android Browser

I found the ripples effects for buttons`<a></a>` and list-items `<li></li>` missing. 

Are those effects turned down deliberately for performance reasons? If so, how can I turn it on? Thank you.

**Comment by FezVrasta** [comment]
No I don't turn off anything. Probably there is some compatibility issue.

Does the bug happens only on `<a>` and `<li>`?

**Comment by Proxy305** [comment]
I am not sure whether there are more...  
But so far,according to my observation:
- Not missing:
  - Checkboxes
  - Toggle Buttons 
  - Input (But the animation is laggy) `<input class="form-control floating-label" id="focusedInput"type="text" placeholder=" ">`
- Missing:
  - Buttons `<a href="javascript:void(0)" class="btn btn-default">Default</a>`
  - FABs `<a href="javascript:void(0)" class="btn btn-default btn-fab btn-raised mdi-action-grade"></a>`
  - List Items `<li class="withripple" data-target="#material-colors">Material Colors</li>`

PS: It seems that someone reorganized my original post in the form of markdown... whoever you are, thanks bro... I am new to github and I just find out how to use markdown in comment a minute ago

**Comment by FezVrasta** [comment]
I've fixed your post :)

I'll check out this problem and will try to find a solution.

**Comment by JosephGF** [comment]
Hello, I think that the problem is in ripples.js, replace if(event.touches.length !== 1)  for if(event.touches.length === 1) in Ripples.prototype.getRelX and Ripples.prototype.getRelY functions,I try it and works

**Comment by JosephGF** [comment]
you can test it in chrome for desktop if active in debug options "Emulation" -> "User Agent" -> Spoof user agent, and select Chrome - Android Mobile, and "Emulation" -> "Sensors" and check "Emulate touch screen"

**Comment by Proxy305** [comment]
@JosephGF 
Thank you but unfortunately, it seems that it didn't work for me... I tried it out on both desktop chrome(Device Mode Mobile Emulation) and my mobile phone.
But I also think that the issue have something to do with touch event.

**Comment by jensz12** [comment]
Can confirm this, it does not work on phones, tested it with Chrome and HTC Browser on Android 5.0.1

**Comment by JosephGF** [comment]
Hello, it works in my phone (Android 4.4.2) test in chrome and works in my tablet (Android 4.1.1) test in opera, firefox and chrome but does not work in Android 4.1.1 default brower

We can try it in http://materialdemo.esy.es

**Comment by Sanchit23** [comment]
How do I turn off the ripple effect on certain elements?

Thanks in Advance.

**Comment by FezVrasta** [comment]
You can customize the css selector that is used to apply the ripple effect

```
$.material.options.ripples = ".withripple"
```

Imay have written it wrongly,I'm not at home to check it. Read the readme pls

**Comment by evgenious** [comment]
ripples doesnt work on my ipad air 2 at all :(
on the nexus 5 lollipop neither...
UPDATE:
just found out how to fix, i am using the minified version:
- replace the `!` by `=` after 1 in: `....(b = b.originalEvent, 1 === b.touches.length...`
- add: `"-webkit-transition": "-webkit-transform 0.8s"`, under `"-webkit-transform": "scale(" + c + ") "`,
- add: `"-webkit-transition": "-webkit-transform 0.8s"`, `"-webkit-transform": "scale(1)"` to the `ripple.css`

nut sure how clean this is, but it worked for me now on android & ios...

**Comment by FezVrasta** [comment]
@evgenious please may you explain me what parts have you changed in the unminified version?

**Comment by whegar** [comment]
i use, 'grunt-autoprefixer' for correct prefixes, and works for me. You can use it for comparison, and correct the original material less file.

**Comment by dylanmensaert** [comment]
This problem might be related to following thread: http://stackoverflow.com/questions/2987706/touchend-event-doesnt-work-on-android

**Comment by rosskevin** [comment]
We are using the autoprefixer now, and there have been various build-time changes to make sure we are more cross compatible.  I'm going to close this as an old issue, if it is not working with the latest version, please let me know and we can reopen it.

**Comment by tsega** [comment]
@rosskevin I'm still having this problem on an Android 4.1.2 device I'm using. Can you please instruct me on how to fix this. I'm building a Meteor app and I'm using the latest [fezvrasta:bootstrap-material-design](https://atmospherejs.com/fezvrasta/bootstrap-material-design) package.

**Comment by rosskevin** [comment]
See #769 the meteor package is far out of date and is going to be removed because we do not have a meteor package maintainer.
