### ISSUE TITLE
Material Design fonts missing

### ISSUE THREAD

**Issue by wdiechmann** [mdbootstrap/mdb-ui-kit#432]
b-m-d is super!

I only have one tiny itch - and that is pertaining to the fonts addressed in the material.css

I'm on Ruby 2.1.2, Rails 4.1.5, Node 0.10.35 and Bower 1.3.7

I added a `.bowerrc` with

```
{
  "directory" : "vendor/assets/bower_components"
}
```

then I put `gem "bower-rails", "~> 0.9.2"` in my Gemfile

and then I listed the bower packages in Bowerfile

```
# A sample Bowerfile
# Check out https://github.com/42dev/bower-rails#ruby-dsl-configuration for more options
# asset 'bootstrap'

asset "jquery", "2.1.1"
asset "jquery-ujs", "1.0.1"
asset "sweetalert", "0.2.0"
asset "bootstrap-material-design", "0.2.2"
```

Then I did my `bower install` – and everything was perfect!

But after `cap production deploy` I have to go and do on my app servers this:

```
cd public && ln -s /var/www/clock/current/vendor/assets/bower_components/bootstrap-material-design/fonts fonts
```

Or else my browser barfs with 

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://irrelevant.domain/fonts/Material-Design-Icons.woff?-g7cqhn
```

Is there a way around this?

**Comment by GradyD** [comment]
I am not familiar with rails but I would say this is an issue with your build bot/server config and not really this project. Only because this project is a UI "theme" and the issue you are having is more of server side/config issue.

I would try posting this on stack exchange to see if they are able to help out.

**Comment by FezVrasta** [comment]
Yes I think the same. Feel free to report here the solution if you find one.

**Comment by wdiechmann** [comment]
well - my [SO](http://stackoverflow.com/questions/28577504/where-are-my-font-files-in-my-rails-project-i-use-bower-and-material-design/28588716#28588716) tells the plot :)

**Comment by heavysixer** [comment]
For those interested, this will work out of the box with just a small change to the asset pipeline. You can see a related example in the font-awesome project: https://github.com/platanus/guides/blob/master/setup/fontawesome-bower-rails.md
