### ISSUE TITLE
Demo page, bootstrap-elements.html, has broken inputs

### ISSUE THREAD

**Issue by GradyD** [mdbootstrap/mdb-ui-kit#435]
The demo page is not overriding the .form-control background color. So inputs show as white,

![image](https://cloud.githubusercontent.com/assets/994964/6219819/792f2b34-b5fc-11e4-9738-f61b87e66fb3.png)

This can been seen on http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

It looks like this was last changed with #426

**Comment by FezVrasta** [comment]
Hi, thanks for the report. Looks like I was drunk when I've set the background color of the input. I'm fixing it.
