### ISSUE TITLE
V4: pagination

### ISSUE THREAD

**Issue by BrianMitchL** [mdbootstrap/mdb-ui-kit#437]
Pagination isn't (yet?) properly themed. I have an attached image of what it looks like for me currently. Pagination is a part of Bootstrap as well as Angular Bootstrap (which uses the 'pagination' tag).

![screen shot 2015-02-17 at 1 16 37 am](https://cloud.githubusercontent.com/assets/3683168/6224513/a6ef75f6-b642-11e4-8e31-2f880afc3f9c.png)

**Comment by GradyD** [comment]
If you scroll down about 3/4's of the page it shows pagination and it looks similar to what you are using. http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

I do agree that the styling of this does not match the material design theme. I also checked the LESS files and there currently is not one for pagination/pager. 

Are you able to find a material design spec on pagination? I looked through, http://www.google.com/design/spec/components/bottom-sheets.html, but was not able to find anything that resembled pagination...

**Comment by jerone** [comment]
The only paging I could find was for tabs, http://www.google.com/design/spec/components/tabs.html 
It includes next and previous buttons for tabs overflow, aldo no much styling is going on there.

**Comment by BrianMitchL** [comment]
Yeah, that's a good point, I can't find any specifications for pagination at all. I guess it's up to the framework or a designer to decide.

It is themed differently than stock bootstrap, so that's something, it just looks at a weird not quite there point. Feature request?

**Comment by GradyD** [comment]
I took a look to see if that icon already existed and sure enough it did! You will want to use `.mdi-navigation-chevron-left` and `.mdi-navigation-chevron-right`. They can be found under the navigation section.

![image](https://cloud.githubusercontent.com/assets/994964/6241677/60a577dc-b6ef-11e4-98f9-62a6adb55156.png)

I threw together this quick pen of what I would recommend until something more permanent is figured out. http://codepen.io/anon/pen/xbWOOR

**Comment by FezVrasta** [comment]
This is a prototype I've prepared some week ago.

http://codepen.io/FezVrasta/pen/LExQYo

I had not yet time to implement it in this theme.

**Comment by zachguo** [comment]
@FezVrasta :+1: The prototype looks great!

**Comment by elincognito** [comment]
The prototype looks fine, one thing is that the ripple effect transition should complete when clicked
It doesn't finish its effect completely if you click on an anchor

**Comment by CoalaJoe** [comment]
I updated it with new svg resource and some javascript. 
http://codepen.io/Ashura/pen/XXNeod?editors=011

**Comment by FezVrasta** [comment]
Promoting to V4, this means that it will be implemented in V4 and not in V3. Any PR to implement this in V3 is welcome.
