### ISSUE TITLE
New component: card

### ISSUE THREAD

**Issue by RohovDmytro** [mdbootstrap/mdb-ui-kit#438]
http://www.google.com/design/spec/components/cards.html
http://materializecss.com/cards.html

I'd love to see this component. It's pretty simple to do and quite basic in usage.

P.S. Thanks for your work, it's awesome.

**Comment by FezVrasta** [comment]
Cards are already implemented

**Comment by RohovDmytro** [comment]
Found it. Neat!

**Comment by RohovDmytro** [comment]
It would be great to see some docs or examples, but it's okay.

Thanks for your work again.

**Comment by FezVrasta** [comment]
Yes probably should be documented :P

**Comment by kantorcodes** [comment]
Any more detailed examples of usage?

**Comment by FezVrasta** [comment]
It's documented in the readme
