### ISSUE TITLE
Floating Label won't work.

### ISSUE THREAD

**Issue by rafaeltscs** [mdbootstrap/mdb-ui-kit#439]
Hello,

I am testing bootstrap-material-design out in an app with angularjs and angular-ui-router.

Everything is working fine except for the floating label that is not floating at all.

This is the code I am using: 

```
<div id="add-role-dialog" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">{{roleCtrl.action}} Perfil de Acesso</h4>
            </div>
            <form name="newRoleForm" ng-submit="roleCtrl.addR ole()">
                <div class="modal-body">
                    <input type="text" class="form-control floating-label" id="roleNameInput" placeholder="Nome do Perfil" 
                        data-hint="Nome que deseja atribuir ao novo perfil de acesso"
                        ng-model="roleCtrl.role.name" required
                        ng-disabled="roleCtrl.isViewAction()">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{{roleCtrl.isViewAction() ? "Fechar" : "Cancelar"}}</button>
                    <button type="submit" class="btn btn-primary" ng-disabled="newRoleForm.$invalid" ng-show="!roleCtrl.isViewAction()">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>
```

One thing I could notice taking a look at the demo code is that when I inspect the element at the demo, it is translated to this:

```
<div class="form-control-wrapper">
    <input type="text" class="form-control empty">
    <div class="floating-label">floating label</div>
    <span class="material-input"></span>
</div>
```

And at may app it doesn't happen. It keeps just like it was written. 
I get no errors at the console. 

What could be the reason of that behavior?

**Comment by rafaeltscs** [comment]
It happened that I needed to include `$.material.init();` into the state file too. It is added to the DOM lately so It was not initialized yet.

**Comment by FezVrasta** [comment]
You may want to use arrive.js instead

**Comment by rafaeltscs** [comment]
Thanks, FezVrasta!! really nice tip!

**Comment by dannygoncalves** [comment]
@rafaeltscs Sorry for the necro, I have the same issue on a project with angularJS and ui-router, my empty inputs only have the transition behavior after they change, I've added the $.material.init(); on my state file too but it still happens, how did you managed to fix it?

**Comment by FezVrasta** [comment]
Read the readme, the section about Arrive.js

**Comment by dannygoncalves** [comment]
Thanks @FezVrasta and sorry for the late answer, it worked to me now.
