### ISSUE TITLE
Text input in navbar is unreadable

### ISSUE THREAD

**Issue by projectgheist** [mdbootstrap/mdb-ui-kit#441]
The text input box background color is white instead of transparent. See [Sample](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#navbar).

**Comment by FezVrasta** [comment]
I've fixed it yesterday with 129d0997493ef3b14a78b3217edd07b5d47c8883

**Comment by jerone** [comment]
It would be nice if you could update the files with a version. I have no idea what version both documentation pages ([1] & [2]) use.

1) http://fezvrasta.github.io/bootstrap-material-design/
2) http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

**Comment by FezVrasta** [comment]
I've not yet released a new version, it's not a priority right now. I'm working on different features.

**Comment by rogovdm** [comment]
Is there an estimate release date of new version?

**Comment by RohovDmytro** [comment]
@FezVrasta Is there an estimate release date of new version?

**Comment by FezVrasta** [comment]
I think you'll have to wait few weeks. I'm moving home and I've not lot of free time lately. Sorry
