### ISSUE TITLE
Icon font is off by half a pixel

### ISSUE THREAD

**Issue by jmillspaysbills** [mdbootstrap/mdb-ui-kit#445]
When trying to set the icon font to 24px(the size of the standard Google Icons), the icons are blurry.

It looks like the svgs are off by half a pixel. If you look at the svgs that you download from Google via the Material specs, the SVGs are all off by a half pixel. This looks fine when you use a .svg file, but when you are converting those SVG files to an icon font, you get this half pixel nastiness.

 The set of icons is great, and I love that you guys are using the material icons. But we need to do something about this half pixel. It doesn't look very good at all.

Thanks for all your hard work. It's much appreciated.

**Comment by GradyD** [comment]
Thanks for this! That's impressive your eye was able to spot half a pixel.

Would you mind posting this a bug to the Google guys though? I am not good with graphics but someone else that contributes to this project might be. But either way this is a bug on googles end and if they every fix anything or add anything we will have to keep adjusting by .5px.

Thanks!

**Comment by jmillspaysbills** [comment]
Well, I don't think this is necessarily a bug on googles part. Their svf icons work fine on the web. But if you open their svg icons in a vector editor like illustrator, you can see how it is set on the half pixel.

There probably isn't an issue on high density displays, like retna or most smart phones. But it's definitely noticable on a standard desktop display at 72 DPI.

The problem is probably with how the font icon is created. What did you use to create the font icon? I don't mind helping you out with this. It should be easy to fix, and I think it would be very helpful to everyone using it. 

It would definitely help me.

**Comment by FezVrasta** [comment]
I've created it using iconmoon.

I'm waiting the official Google font to replace the current one

**Comment by jmillspaysbills** [comment]
Fez, can you send me the .json file from icomoon? That's the same service I usually use to create my icon fonts.

I'd love to help fix this issue for the project as it would also greatly help me with a project we're currently working on.

**Comment by FezVrasta** [comment]
Sorry I've not the json anymore

**Comment by jmillspaysbills** [comment]
Ok. If I correct the blurry icon issue would you use the icon font I create?

**Comment by FezVrasta** [comment]
Yes sure just be sure to keep compatibility with current classes

**Comment by jmillspaysbills** [comment]
Will do. Looking forward to contributing.

**Comment by jmillspaysbills** [comment]
I've got this complete and I'll be checking it in in the morning.

**Comment by jmillspaysbills** [comment]
@FezVrasta , I've got the updated fonts and stylesheets ready to commit. However, I have to confess that I'm not 100% familiar with forking and merging within Git. What's the best way to get this to you?

I noticed that the dist directory contains the compiled CSS for the project, including the icon fonts. I have the css from icomoon, and I've added some additional functionality that mimics what Font Awesome does. I did this, because I figured if people are using BootStrap, they're likely familiar with Font Awesome. We can remove this if you see that being necessary.

Anyway, what's the best way to go about doing this if you're using less/sass, but I have just compiled CSS from icomoon.

Thanks.

**Comment by FezVrasta** [comment]
Just push the new font, I'll take care of the rest. Thanks !

**Comment by jmillspaysbills** [comment]
@FezVrasta can you verify my check in is correct? I haven't submitted something like this via git hub before, and I want to make sure that I've done it correctly.

I still need to check in my css file as the content declarations are different from the original. I'm just not sure where that should go. So you'll need the new CSS. 

I also added some of the stuff that Font Awesome does with their css file. My thinking is that since people using Bootstrap are probably familiar with Font Awesome, it would be good to allow them to do some of the similar things, like the 2x, 3x, spin classes, etc.

**Comment by FezVrasta** [comment]
I've not internet at home atm, I'm moving home.. I should be online again in some days

**Comment by jmillspaysbills** [comment]
No problem. I'll be around. Just let me know how you'd like me to proceed.

**Comment by overclokk** [comment]
Hi, Bootstrap glyphicon glyphicon-plus has the same problem (maybe other glyphicon as well), I have fixed like this:

``` css
.btn-fab .glyphicon {
    left: 1.5px;
    top: -0.5px;
}
```

I have opened an issue for this https://github.com/FezVrasta/bootstrap-material-design/issues/498

**Comment by FezVrasta** [comment]
fixed by the OP
