### ISSUE TITLE
Checkbox, radio and toggle weird css

### ISSUE THREAD

**Issue by jeromin** [mdbootstrap/mdb-ui-kit#448]
Hello, they works perfect on firefox (the ripple effect and css display)
But the css tag "animation" isn't found on chrome and safari (and mobiles)(up-to-date) so no ripple effect
You may take a look at the different browser display... it doesn't work where your bootstrap elements page perfectly works.
As it works perfectly on firefox, i'm wondering if the "webkit-transform" exists somewhere, I didn't fine it in less files.

I also have trouble overriding the color using a custom less file with primary and my color but nothing after less recompiling, the colors is stil green ..

I'm using the symfony bundle. Css is rewritten using less in assetic
http://browsershots.org/http://dev.jeromin.fr/

Thanks for your help and sorry if i disturb.

**Comment by FezVrasta** [comment]
We use autoprefixer to add vendor specific prefixes like `-webkit-animation`. Please be sure to use it if you compile the theme yourself.

**Comment by jeromin** [comment]
Well, I thank you very much, I didn't know what an autoprefixer was but thanks to you within 5min, problem solved :)
Just another easy one, I do i use the primary color for the toggle button (or what is the css class "toggle-material-color" doesn't work.

**Comment by FezVrasta** [comment]
Please open a new issue with more details. Thanks.
