### ISSUE TITLE
loads of css bloat due to colors (generic-variations) . 

### ISSUE THREAD

**Issue by geertbrit** [mdbootstrap/mdb-ui-kit#451]
I'm wondering if it might be a performance issue to have thousands of (often unneeded) styles which get generated based on the `.generic-variations` mixin. 

Are these 10's of thousands of styles a real performance concern on mobile or am I too dense looking into this with some skepticism?

**Comment by wopian** [comment]
#383?

**Comment by FezVrasta** [comment]
I'm already on it

**Comment by geertbrit** [comment]
cheers
