### ISSUE TITLE
Navbar form floating label placeholder color

### ISSUE THREAD

**Issue by irontiga** [mdbootstrap/mdb-ui-kit#455]
On primary navbar with a floating label from, the placeholder is grey, and the floated label goes the same color as the navbar....oh, actually...that was on 0.2.1....

**Comment by FezVrasta** [comment]
is it still valid? @irontiga

**Comment by irontiga** [comment]
Not sure, i didn't update, so don't worry.

**Comment by irontiga** [comment]
It is still broken, and so i made a class, 'has-white'(just copied 'has-error' etc.)

```
.form-group.has-white .form-control{box-shadow:none}.form-group.has-white .material-input:focus,.form-group.has-white .form-control:focus,.form-group.has-white .form-control.focus{background-image:linear-gradient(white,white),linear-gradient(#d2d2d2,#d2d2d2);box-shadow:none}.form-group.has-white .control-label,.form-group.has-white input.form-control:focus~.floating-label{color:white}

```

This works fine, but now i am adding a contact from on a blue-grey background(a footer, not the navbar in this case), and it looks terrible with any color but white for the floating label. Here the text area remains a green float. Any idea why? Can't find any reason in you material.css

Here's an example: http://screencast.com/t/6tg3qyuK

It's actually broken on your has-error class as well.... http://screencast.com/t/djqxqAlbm

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
