### ISSUE TITLE
WOFF2 font please

### ISSUE THREAD

**Issue by tomByrer** [mdbootstrap/mdb-ui-kit#456]
42% browser share can use WOFF2 now, & should grow fast.  http://caniuse.com/#feat=woff2
Not sure if this compresses the best: https://everythingfonts.com/ttf-to-woff2  (Google has very aggressive compression before they host on their font CDN,...)

Let me know if you want a PR.

**Comment by FezVrasta** [comment]
Are you talking about the iconic font or the embedded Google Fonts?

**Comment by tomByrer** [comment]
Yes to both?

**Comment by FezVrasta** [comment]
Both already use woff

**Comment by tomByrer** [comment]
WOFF**2** is better than 'WOFF'(v1)
https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a
http://sth.name/2014/09/03/Speed-up-webfonts/
http://demosthenes.info/blog/976/Serving-Up-WOFF2-Fonts-For-Faster-Pages

**Comment by FezVrasta** [comment]
Both uses woff2

**Comment by tomByrer** [comment]
AFAIK, WOFF2 uses `.woff2` extension.  Is there another folder other than here I should look for `Material-Design-Icons.woff2`?
https://github.com/FezVrasta/bootstrap-material-design/tree/master/dist/fonts

**Comment by FezVrasta** [comment]
You're right, the roboto font uses woff2, the iconic font uses woff. The iconic font will be replaced soon with official Google Fonts

**Comment by tomByrer** [comment]
hehe yea, "[soon](https://github.com/google/material-design-icons/issues/1#issuecomment-74499435)"

**Comment by tomByrer** [comment]
"Soon" is unknown: https://github.com/google/material-design-icons/issues/1#issuecomment-92078153
