### ISSUE TITLE
Double underline on select

### ISSUE THREAD

**Issue by jones6951** [mdbootstrap/mdb-ui-kit#458]
Select dropdown has a double-underline prior to focus on the field. Running chrome on OSX

https://www.evernote.com/shard/s4/sh/48b87d46-9344-42e9-b99e-d2e058306acb/71e89d472adc8f01b7ba80acd45e8a9c/res/f8db03f1-2ae9-4362-a635-e49cafd15a39/skitch.png

```
<select id="user-date_format" class="form-control" name="User[date_format]">
    <option value=""></option>
    <option value="dd/mm/yyyy" selected>dd/mm/yyyy</option>
    <option value="mm/dd/yyyy">mm/dd/yyyy</option>
</select>
```

**Comment by cvrebert** [comment]
Your image link just leads to a "Access denied." error page

**Comment by jones6951** [comment]
I still see the issue. 

https://www.evernote.com/shard/s4/sh/48b87d46-9344-42e9-b99e-d2e058306acb/71e89d472adc8f01b7ba80acd45e8a9c

**Comment by FezVrasta** [comment]
I've not updated the demo
