### ISSUE TITLE
Popovers in Firefox need to be double clicked to stay open

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#46]
When clicking on the popovers in chrome they stay open instantly. However when clicking in Firefox I have to click the second time for them to stay open.

Awesome repo, I have just found it today via a weekly enews I get.

**Comment by FezVrasta** [comment]
Thanks I'll investigate.

**Comment by FezVrasta** [comment]
again the fault is of ripples.js

it's kinda bugged in lot of browsers except chrome (and honestly I think the problem are the browsers and not my script, by the way I'm working to fix all these problems...)

**Comment by FezVrasta** [comment]
should be fixed with 242b3ea
