### ISSUE TITLE
popover-title background-color different from popover

### ISSUE THREAD

**Issue by GradyD** [mdbootstrap/mdb-ui-kit#462]
Looking through the CSS popover-title is not modified by material CSS but popover is. Material CSS has this CSS,

```
.popover, .tooltip-inner {
  background: #323232;
  color: #FFF;
  border-radius: 2px;
}
```

The problem is that `.popover-title` has `background-color: #f7f7f7;` applied to it so the coloring is not correct and unreadable. 

I was able to fix this by adding, 

```
.popover-title {
  background-color: #323232;
}
```

to _popups.less.

**Comment by FezVrasta** [comment]
fixed by you, lol
