### ISSUE TITLE
css file size too huge!

### ISSUE THREAD

**Issue by bdotq** [mdbootstrap/mdb-ui-kit#469]
The file size of the material.css (even the materia.min.css) is HUGE!
The file size is over a megabyte! for a stylesheet!

An alternative smaller version should be available, or the ability to customize should be available

**Comment by FezVrasta** [comment]
yup we are working on it...

**Comment by bdotq** [comment]
It's 80% all the color variations

**Comment by lukasMega** [comment]
+1

**Comment by FezVrasta** [comment]
fixed with a4c09ab76ed95c8fe299530acf83b9a130576592
