### ISSUE TITLE
Slider grab not having raised effect in Firefox

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#47]
I have looked at the slider in Chrome, and the beautiful raised effect I saw does not happen in Firefox. No big issue, but thought I would report my findings. 
Again, stunning work on this project.

Are you using it commercially on any project that you would like to share?

**Comment by FezVrasta** [comment]
I'm using it on a commercial project but nothing is online at the moment.

I'll fix this problem, thanks.

**Comment by ghost** [comment]
Cool, looking forward to seeing it used in the wild.
