### ISSUE TITLE
Grunt watch recurses endlessly

### ISSUE THREAD

**Issue by tyleriguchi** [mdbootstrap/mdb-ui-kit#471]
In the grunt watch task
 `files: [
          "index.html",
          "dist/css/**/*.css",
          "**/*.{png,jpg,jpeg,gif,webp,svg}"
        ]`
the splat recurses and throws a warning: ENAMETOOLONG

**Comment by GradyD** [comment]
Can you provide steps to duplicate this? I ran `grunt watch` without any issues.

**Comment by GradyD** [comment]
It looks like this was fixed with PR #472. @FezVrasta can you confirm and close?

**Comment by FezVrasta** [comment]
Never had this problem but I think it's being fixed by that commit.
