### ISSUE TITLE
Make use of an autofill events polyfill

### ISSUE THREAD

**Issue by barbatus** [mdbootstrap/mdb-ui-kit#473]
Since there is already one dependency on an external library i.e. Active.js, I was thinking why not 
to make use of e.g. tbosch/autofill-event (based on script made at Google) to support autofill events instead of that brittle code we have in material.js file. I could send a pull request. What do you think?

**Comment by FezVrasta** [comment]
I wasn't aware of it, yes please I'd love to see this pr

**Comment by FezVrasta** [comment]
Hey @barbatus ? Are you still available to send a PR about this or should I implement it by myself?

Thanks!

**Comment by barbatus** [comment]
Hi,

I think I'll send PR tomorrow or day after tomorrow.
Times goes fast and I was busy a bit, apologies.

Alex

**Comment by barbatus** [comment]
Hi,

I studied this autofill script deeper and found that it uses setTimeout as well but instead of firing change event for 10 seconds it fires it only once when 200ms past. Second, it doesn't work for Safari's keychain autofill whereas current solution works.
Given that, I wouldn't touch current solution except only change that 10sec to 200ms because it seems enough time for browser to autofill fields.

Here are examples
http://autofill-test.meteor.com - with that autofill script added
http://autofill-test-old.meteor.com - untouched

Alex

**Comment by FezVrasta** [comment]
ah lol, ok thanks

**Comment by FezVrasta** [comment]
maybe something with Arrive.js could be done... Will investigate

**Comment by barbatus** [comment]
@FezVrasta Arrive.js seems to me has nothing to do with autofill events. It just observes new elements appearance in DOM.

**Comment by barbatus** [comment]
Why not to change current code to

``` js
setTimeout(function() {
  $("input[type!=checkbox]").each(function() {
     if ($(this).val() && $(this).val() !== $(this).attr("value")) {
         $(this).trigger("change");
      }
  });
}, 200);
```

It should just work.

**Comment by FezVrasta** [comment]
My version is better optimized. It loops on page load for few seconds and then stops. Then it starts looping only on the focused inputs when necessary

**Comment by barbatus** [comment]
@FezVrasta I don't think generating a bunch of bogus events is good. It actually gave me some pain when it was on by default. I used Angular and each change event there causes some binding code to execute by design, so when it's 100 events generated one after another it's not right.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
