### ISSUE TITLE
Usage Instructions for beginner

### ISSUE THREAD

**Issue by akshayagarwal** [mdbootstrap/mdb-ui-kit#476]
It should be highlighted as 'Usage Instructions' that one needs to call $.material.init() to apply all the cool effects. Its currently not intuitive right out of the box and I spent a few hours figuring that out.

**Comment by FezVrasta** [comment]
Or better, try to read the README :P 

> Navigate to the dist/ folder in this repository, and you will see the test.html file, which has the CSS include statements, in the head section and the JS includes just before body section closes.

**Comment by akshayagarwal** [comment]
I do see you now made a change to dist/test.html https://github.com/FezVrasta/bootstrap-material-design/commit/a4c09ab76ed95c8fe299530acf83b9a130576592#diff-7cdb8d81570ea7c1cb914abeb463dbdd to highlight this. Still, even if you READ your README, you will find you have phrased your instruction as 'JS includes'. Do you think after reading this, people would immediately understand its not just the includes they have to care about but also some additional code which is needed for initialisation?

**Comment by akshayagarwal** [comment]
Also, I don't understand why should the initialisation code be left outside the material.js library code? I find this is needed in other libraries only when you have to run it on an element specific to the HTML of that page. However, if your init is just on the global jQuery object and always needed whenever the material.js library is to be utilised why bother the user at all?

**Comment by FezVrasta** [comment]
Lot of people use frameworks like Angular or Ember where it's better initialize elements manually and not globally.

**Comment by akshayagarwal** [comment]
Does your library depend on any of them? Don't you think this would be counter intuitive to the greater majority who don't use Angular or Ember?

**Comment by akshayagarwal** [comment]
In fact, from what I can see, your library depends on jQuery instead where majority plugins are auto initialised for global stuff with the option to override when anything specific to HTML needs to be brought in the perspective.

**Comment by FezVrasta** [comment]
This theme aims to be more pure CSS as possible, so if I can let users choose if use JS or not I do it.

It's not a big problem include one extra row of JS where you need :)
