### ISSUE TITLE
Light Grey doesn't work?

### ISSUE THREAD

**Issue by tobiascornille** [mdbootstrap/mdb-ui-kit#478]
You report that you can use `-material-light-grey` as it's a color from the palette, but it doesn't work when I apply this to my navbar. It just displays the default green color.

`<nav class="navbar navbar-default navbar-static-top navbar-material-light-grey">`
Doesn't work

`<nav class="navbar navbar-default navbar-static-top navbar-material-lightgrey">`
Also doesn't work

`<nav class="navbar navbar-default navbar-static-top navbar-material-deep-purple">`
Does work

**Comment by tobiascornille** [comment]
Also: black and white don't seem to work either.

**Comment by FezVrasta** [comment]
please may you provide a codepen demo?

**Comment by tobiascornille** [comment]
How do I include Bootstrap Material Design into a Codepen?

**Comment by FezVrasta** [comment]
http://codepen.io/FezVrasta/pen/ihmea

**Comment by tobiascornille** [comment]
Nothing with colors works on Codepen so I'll just share some screencaps and some code:

Grey works:
![Grey works](http://i.imgur.com/QQPWdr4.png)

Light grey doesn't:
![Light-grey doesn't](http://i.imgur.com/3EbC708.png)

Code:

``` html
  <nav class="navbar navbar-default navbar-static-top navbar-material-light-grey">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <div class="navbar-brand" href="#">
                    <img src="img/static.svg">
                </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="index.html">Home</a></li>
                    <li><a href="services.html">Services</a></li>
                    <li><a href="about.html">About</a></li>
                    <li><a href="contact.html">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
```

**Comment by FezVrasta** [comment]
Sorry but light-grey is not a standalone color. The schema in the readme is outdated.

You have to use a light shade of grey, the complete list is here:

http://www.google.com/design/spec/style/color.html#color-color-palette

**Comment by tobiascornille** [comment]
Thanks!
