### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by jbethuel** [mdbootstrap/mdb-ui-kit#482]
Hello, im new to Github and also beginner web developing. I have already designed a Mock up website using bootstrap. I have tried yours and it didnt work out well. am i missing something? i have following your bootstrap theme codes well. doesnt seem it works out well.

**Comment by FezVrasta** [comment]
It's not very specific, I need more informations and some code to look at.

**Comment by jbethuel** [comment]
Im sorry i got it working now.Thank you
