### ISSUE TITLE
Ripple Effect, Check Box, Toggle Button

### ISSUE THREAD

**Issue by jbethuel** [mdbootstrap/mdb-ui-kit#484]
Hello. Im having trouble with the Ripple Effect, Check Box, Toggle Button. what could possibly go wrong? here is my source code:
http://pastebin.com/JyWVykg9

**Comment by FezVrasta** [comment]
Looks like you have missed `$.material.init()`

**Comment by jbethuel** [comment]
i have wrtten it below.

**Comment by jbethuel** [comment]
should this be written be like this? 
< script >
    $(function() {
    $.material.init();
      });
    < / scrip t>    

i have inserted some spaces because git doesn't allow html tags

**Comment by FezVrasta** [comment]
sorry, you have written it before the dependencies.

You are executing material.js before you include it, it should go below.

**Comment by jbethuel** [comment]
Works now! Thank you sir! Im just a beginner..  Will include you in the credits when my school project will be done! cheers

**Comment by FezVrasta** [comment]
I'd love to see it when done :)

Email me at  `fez [@] tekhy [.] net`   please
