### ISSUE TITLE
Accordion styled incorrerctly

### ISSUE THREAD

**Issue by GradyD** [mdbootstrap/mdb-ui-kit#485]
Due to the accordion using panels the styling looks very bad. Bootstrap markup http://getbootstrap.com/javascript/#collapse-example-accordion and it looks like,

![image](https://cloud.githubusercontent.com/assets/994964/6561260/258701e4-c666-11e4-873f-a254c32f07c8.png)

Background is white on this page. I will say that I have modified the accordion markup to make the entire heading clickable. 

```
<div class="panel panel-default">
  <a class="panel-heading visible-xs-block visible-sm-block visible-md-block visible-lg-block collapsed" data-parent="#test" data-toggle="collapse" href="#collapseOne">
    <h4 class="text-danger">Urgent</h4>
  </a>
  <div class="panel-collapse collapse" id="collapseOne" style="height: 0px;">
    <div class="panel-body">
      ...
    </div>
  </div>
```

**Comment by FezVrasta** [comment]
I wouldn't change the markup.

We may apply `display: block` to the `.panel-title > a` element so that it takes the entire header of the panel.

About the styling, we can use the `.panel-group` class to target it?

**Comment by GradyD** [comment]
I hate changing the markup but from a UI prospective users were very confused when they would click on the container and it would not do anything. All I did was move line 4 from the modal and combine it with line 2. Since the `<a>` is not actually styling anything and is only being used to trigger the click event I was able to add the needed classes `panel-heading`.

```
<div class="panel panel-default">
  <div class="panel-heading" role="tab" id="headingOne">
    <h4 class="panel-title">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Collapsible Group Item #1
      </a>
    </h4>
  </div>
  <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
    <div class="panel-body">
    </div>
  </div>
</div>
```

I agree that targeting `.panel-group` is the right move. Looking at bootstrap source I was able to find the styling in https://github.com/twbs/bootstrap/blob/master/less/panels.less on line 211. Should be easy to adjust this to match by editing the handful of lines there.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
