### ISSUE TITLE
Toggle button css class for coloring

### ISSUE THREAD

**Issue by jeromin** [mdbootstrap/mdb-ui-kit#486]
Hello,
How I do i use the primary color for the toggle button (or what is the css class "toggle-material-color" doesn't work ? It stays green whereas my primary color is deep-orange.
For a button i had "btn-material-deep-orange" but i didn't find anything working for the toggle-button, i can't find the css class for its color.
Hope you'll understand.
Thank you

**Comment by FezVrasta** [comment]
Looks like variations for toggles are not implemented, I'm adding them right now.

**Comment by jeromin** [comment]
Ok, thanks, let us know.

**Comment by FezVrasta** [comment]
3cf4a656bfdf9bc331a586d753b47d250b1b7c2a implemented
