### ISSUE TITLE
ripple effect not working with less.js

### ISSUE THREAD

**Issue by srocerer** [mdbootstrap/mdb-ui-kit#491]
Hello,

I decited to try FezVrasta bootstrap theme. Realy great job.

Imported in my theme.less, everything work great, but ripple effect gone from checkbox and radio buttons in chrome browser but in firefox browser works great.
I think  -webkit- prefix missing in .less files?

How to fix this?

less.js 2.4 version

**Comment by FezVrasta** [comment]
You must use autoprefixer to add the vendor prefixes

**Comment by srocerer** [comment]
Can i use autoprefixer with less.js or less.php?

**Comment by FezVrasta** [comment]
I'm not sure. It's not a good idea compile LESS on the fly.
