### ISSUE TITLE
Form elements display not correctly in safari 5.1.7 (window)

### ISSUE THREAD

**Issue by salem-chinsu** [mdbootstrap/mdb-ui-kit#492]
Please see the attached file :

input - textarea missing border, checkbox display not correctly.

Best regards.
salem.

**Comment by FezVrasta** [comment]
I can't see any attached file...

**Comment by salem-chinsu** [comment]
Sorry for this, bellow is the image :)

No border and effect for these elements.

![safari-error](https://cloud.githubusercontent.com/assets/5398485/6650579/c4b9c938-ca4c-11e4-8f75-cc1c0b5f0dc2.PNG)

**Comment by FezVrasta** [comment]
ah sorry I didn't read the title...

Safari for Windows is deprecated and unsupported, you should never use it. It's a very old version of that browser. I don't support it so.
