### ISSUE TITLE
Roboto fonts missing in dist/fonts

### ISSUE THREAD

**Issue by mist-webit** [mdbootstrap/mdb-ui-kit#493]
![image](https://cloud.githubusercontent.com/assets/7987637/6638292/3e9eaa36-c98d-11e4-8950-2905efe04446.png)

**Comment by FezVrasta** [comment]
fixed, thanks.

**Comment by tural-ali** [comment]
Maybe you just remove the font from theme?

**Comment by FezVrasta** [comment]
I had forgot to run the `grunt copy` task to copy the new fonts to the dist folder.
