### ISSUE TITLE
CSS Wring warning

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#495]
```
$ npm i
npm WARN deprecated grunt-csswring@1.1.1: Use task shipped with node-csswring instead
```

It happens when you install npm dependencies. This is just a reminder.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
