### ISSUE TITLE
.dropdown-menu overrides .shadow-z-*

### ISSUE THREAD

**Issue by GradyD** [mdbootstrap/mdb-ui-kit#497]
When using a .dropdown-menu the `box-shadow` overrides any `shadow-z-*` value. Couple of possible fixes to this. @FezVrasta how would you like for this to be fixed? Just add `!important` tags?

![image](https://cloud.githubusercontent.com/assets/994964/6645083/dec62974-c98f-11e4-966e-da20998794e0.png)

**Comment by jerone** [comment]
Maybe switch classes `.dropdown-menu` and `.shadow-z-4`. What's your HTML?

**Comment by GradyD** [comment]
I tried switching and it did not make a difference, my HTML (without switching) is:

```
<ul class="dropdown-menu shadow-z-3">
  <li><a href="javascript:void(0)">Edit</a></li>
  <li><a href="javascript:void(0)">Delete</a></li>
</ul>
```

**Comment by jerone** [comment]
Changing CSS priority mite be a little hard here, because of the minimal selector matching, but one could probably use (untested):

``` css
    .shadow-z-4, .dropdown-menu.shadow-z-4 { ... }
```

Or reorder classes `.dropdown-menu` and `.shadow-z-4` in the stylesheet.

Using `!important` is never a good solution.

**Comment by GradyD** [comment]
If I move `.shadow-z-*` to the bottom of the CSS file, so it is under `dropdown-menu` would that solve the issue?

**Comment by FezVrasta** [comment]
Not sure, it depends by the specificity of the selector you want to override... Probably moving shadows to the bottom will do the trick.
