### ISSUE TITLE
Bug input Checkbox (Toggle Button) + CakePHP

### ISSUE THREAD

**Issue by Kwaadpepper** [mdbootstrap/mdb-ui-kit#499]
Hi,

There is a bug with cakePHP which print an extra hidden input to give a 0 value in case checkbox is not selected.

So this works:

```
echo $this->Form->input('title_visible', array(
    'div' => 'togglebutton',
    'label' => false,
    'hiddenField' => false,
    'before' => '<label>Afficher le titre de l\'article',
    'after' => '<span class="toggle"></span></label>'
));

<div class="togglebutton">
  <label>Afficher le titre de l'article
    <input name="data[Article][title_visible]" value="1" id="ArticleTitleVisible" type="checkbox">
    <span class="toggle"></span>
  </label>
</div>
```

![cakematerial_ok](https://cloud.githubusercontent.com/assets/6019313/6666763/d3e6923c-cbe7-11e4-8b09-a9f6336ac76c.png)

while cake will print:

```
echo $this->Form->input('title_visible', array(
    'div' => 'togglebutton',
    'label' => false,
    'before' => '<label>Afficher le titre de l\'article',
    'after' => '<span class="toggle"></span></label>'
));

<div class="togglebutton">
  <label>Afficher le titre de l'article
    <input name="data[Article][title_visible]" id="ArticleTitleVisible_" value="0" type="hidden">
    <input name="data[Article][title_visible]" value="1" id="ArticleTitleVisible" type="checkbox">
    <span class="toggle"></span>
  </label>
</div>
```

![cakematerial_nok](https://cloud.githubusercontent.com/assets/6019313/6666767/d6556750-cbe7-11e4-9828-32067d20a868.png)

I think this is a css problem there might be a easy work around.

EDIT:
found that `input[type="checkbox][disabled"]:first-of-type` the first of type might be conflicting

**Comment by FezVrasta** [comment]
may you let me know if my last commit fixed it?

I've tested it here and everything works fine http://codepen.io/FezVrasta/pen/gbQmNo

**Comment by Kwaadpepper** [comment]
Yes your fix makes the trick :P
