### ISSUE TITLE
Future features

### ISSUE THREAD

**Issue by roeku** [mdbootstrap/mdb-ui-kit#5]
Don't really know what you are working on atm maybe a summary of what's to come in the [readme.md](https://github.com/FezVrasta/bootstrap-material-design/blob/master/README.md) would stop people from posting 'issues' you are already doing.

**Comment by FezVrasta** [comment]
atm I'm not working directly on this project, I'm using it to develop an application of the company I work for and when I find some bug or something I'd need I then add it to the core of this project.

**Comment by roeku** [comment]
Oh, very well. It does have a lot of potential though, from all the thing I found regarding to material design  like polymer & angulars material design, this was the easiest one to dive into.

**Comment by FezVrasta** [comment]
yup this is one of the goals... the other goal is to avoid the use of the new "Web Components" which remember me "iframes"...

**Comment by roeku** [comment]
Dunno, think what the guys at polymer are trying to do (expanding the DOM) is cool, just the they implement it isn't very intuitive.

**Comment by FezVrasta** [comment]
I've added a to-do list, feel free to suggest elements which should stay there.

**Comment by npvn** [comment]
Hi @FezVrasta,

Thank you for sharing this project. This is the most comprehensive base for implementing Material Design I've found so far.

I'm planning to create a Meteor package for this and publish it on atmospherejs.com. Hope that is ok :)

Cheers!

**Comment by FezVrasta** [comment]
Hello, yes there are no problems, just be sure to attach the license beside the rest of the package. Thanks!
