### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#506]
`mdi-av-queue-music` and `mdi-social-public` don't show in the demo page.

@jmillspaysbills @GradyD you have worked on the new icons so... any idea? :-)

**Comment by GradyD** [comment]
I looked at https://github.com/FezVrasta/bootstrap-material-design/blob/master/less/_icons-material-design.less and it looks like both of those are just missing tags.

**Comment by jmillspaysbills** [comment]
i'm looking into it now.

**Comment by jmillspaysbills** [comment]
weird. it looks like both classes are missing the "ic" at the end. 

I'm fixing this now.

**Comment by jmillspaysbills** [comment]
Ok, I just committed this. Let me know if you have any trouble with it.

**Comment by jmillspaysbills** [comment]
I had to change the file names of the SVG files from the Google repository in order to upload to icomoon. It looks like I somehow removed the "ic" from the end of these two classes.

**Comment by FezVrasta** [comment]
thanks :)
