### ISSUE TITLE
woff2 files missing from cdnjs

### ISSUE THREAD

**Issue by azam** [mdbootstrap/mdb-ui-kit#511]
This is a cdn issue, but I assume the project owner
should be informed.

roboto(.min).css tries to import woff2 files before woff,
but there is no woff2 files on the cdn, so it will 404.

Problem exist on 0.3.0 .
Previous versions are not affected if we use material-wfont.css

Ref: https://cdnjs.com/libraries/bootstrap-material-design

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
