### ISSUE TITLE
Change sea green on example page to something less ugly

### ISSUE THREAD

**Issue by dbkaplun** [mdbootstrap/mdb-ui-kit#513]
Pretty much any color would be better than that baby food-looking color.

**Comment by FezVrasta** [comment]
It's the primary color of the Lollipop UI. I like it and I think it's good.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
