### ISSUE TITLE
form-control styles not working in Chrome with angular.js

### ISSUE THREAD

**Issue by andrewljohnson** [mdbootstrap/mdb-ui-kit#517]
1) I have added arrive.js to my project.

2) In Safari & FF, I don't get the blue underline animation on my inputs: http://scriber.io/#/?signup

3) I do see the effect on Firefox.

4) Has anyone else had this issue? I suspect it relates to how angular.js generates DOM, and then also appends classes to the CSS. Angular adds several CSS classes to the end of the input, and I wonder if the BMD gets tripped up by the appended classes?

**Comment by FezVrasta** [comment]
What version of the theme are you using?

**Comment by andrewljohnson** [comment]
I updated to the latest version via bower, and deployed to scriber.io just
now. Still the same issue.

**Comment by GradyD** [comment]
I looked into this and if I had to guess it is because the modal is being dynamically added to the page. This means that you will need to call the JS functions to apply the effect onClick.

**Comment by andrewljohnson** [comment]
I noticed if I call  $.material.init() after the popover is instantiated,
then the ripple effect gets applied to popover buttons.

But it doesn't activate the style on the inputs no matter what. Even on
other pages, I can't get the input effect to work for me in Chrome or
Safari, only FF. Must be some of my other JS.

**Comment by FezVrasta** [comment]
Try including arrive.js

**Comment by andrewljohnson** [comment]
Yep, already doing that too.

**Comment by FezVrasta** [comment]
Are you talking about the floating label effect or the underline effect?

**Comment by andrewljohnson** [comment]
The underline effect.

**Comment by FezVrasta** [comment]
ok so you are using an old version (not 0.3.0). On 0.3.0 the underline effect is applied without any Javascript.

**Comment by andrewljohnson** [comment]
I'm definitely on the latest version.

**Comment by andrewljohnson** [comment]
Please note that this affects Chrome and Safari, but not FireFox.

Here is a video showing it work on FireFox, but not the other 2:
https://www.dropbox.com/s/6uzdohsv60c156r/bmd-bug.mov?dl=0

Could my custom CSS interfere somehow, in Chrome only?

**Comment by FezVrasta** [comment]
Give me a demo to inspect

**Comment by FezVrasta** [comment]
are you compiling the LESS by yourself?

**Comment by FezVrasta** [comment]
Yes, you are compiling it. You must use autoprefixer to add vendor prefixes and make it work on every browser.

**Comment by andrewljohnson** [comment]
Thanks for the suggestion.

**Comment by andrewljohnson** [comment]
Sweet thanks, turning on CodeKit's auto-pre-fixer did it.

**Comment by FezVrasta** [comment]
Ok great and sorry, just checked the emails :)

**Comment by leqwasd** [comment]
Your included files in /dist folder does not have this effect. I replaced them with files from your live demo site, and it worked.

**Comment by FezVrasta** [comment]
The master branch is used as development branch, if you look for a stable version use the releases tab
