### ISSUE TITLE
installing issue with bower

### ISSUE THREAD

**Issue by spyshiv** [mdbootstrap/mdb-ui-kit#518]
when i tried to install bootstrap material design using terminal it was not working.

command given by me:  bower install bootstrap-material-design
issue:                /usr/bin/env: node: No such file or directory

Help me out.

**Comment by jerone** [comment]
First result from [Google](https://www.google.nl/search?q=issue:+/usr/bin/env:+node:+No+such+file+or+directory&gws_rd=cr,ssl&ei=lTkNVfHXOpPqaKWVggg): https://github.com/joyent/node/issues/3911
