### ISSUE TITLE
Use waves instead of ripples.js?

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#52]
ripples.js was the first with "click and hold" support, now I see that Waves has added this feature as well, and seems to work better than ripples.js.

Maybe would be better drop ripples.js and start using [waves](http://fian.my.id/Waves/)?

What do you think?

**Comment by yannski** [comment]
Waves seems to work really nicely. And it works really well on my Android phone too.

BTW, the Google WSK's team (Web Starter Kit) is currently developping a version of the kit with material design in sight. You can see what they plan to use here https://github.com/google/web-starter-kit/issues/296 to fullfill all the "material functionnalities".

**Comment by FezVrasta** [comment]
not so promising... thanks

**Comment by yannski** [comment]
Waves would also resolve the "Button icon" item in the todo ;-)

**Comment by FezVrasta** [comment]
no, the button icons of waves does not follow the material design guidelines.

**Comment by waylaidwanderer** [comment]
Wave seems a bit buggy to me. Lags on Firefox when I click it too much/too quickly.

**Comment by FezVrasta** [comment]
Just updated ripples.js, now the problem with multiple ripples seems fixed, maybe we could stay with our plugin now :)

**Comment by FezVrasta** [comment]
Ok we'll stay with our plugin because now it works very well.
