### ISSUE TITLE
0.3.0 breaks Material.js

### ISSUE THREAD

**Issue by Obiwarn** [mdbootstrap/mdb-ui-kit#521]
When I update to 0.3.0. The hover effects and ripples are gone.

After a downgrade, everything worked fine again:

meteor add fezvrasta:bootstrap-material-design@=0.2.1

**Comment by FezVrasta** [comment]
I need more details.. Errors in console and so on

**Comment by allanlundhansen** [comment]
+1 (no console errors)

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
