### ISSUE TITLE
Should Input Height be hard-coded to 28px?

### ISSUE THREAD

**Issue by simonv3** [mdbootstrap/mdb-ui-kit#524]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/sass/_inputs.scss#L4

I could be missing that it is a requirement for something though? 

Should that just be `height: auto` - reacting to the font height?

I'm happy to supply a PR that fixes this if it should be `auto`

**Comment by FezVrasta** [comment]
I can't remember but probably it was required to prevent some problem. If you can provide a PR with height auto that actually works then feel free to

**Comment by rosskevin** [comment]
Input heights are addressed in 0.4.1.
