### ISSUE TITLE
Checkboxes should not animate on page load

### ISSUE THREAD

**Issue by GradyD** [mdbootstrap/mdb-ui-kit#525]
They should only animate when clicked.

**Comment by geoguide** [comment]
Agreed. Once someone teaches me how to commit submodules I will work on this.

**Comment by FezVrasta** [comment]
Not sure if it is possible commit on submodules... umh.. probably you have to `cd` in the submodule directory. I'm not sure.

By the way yes, it should be fixed somehow... 

here a CSS challenge, looking at the forks of it you should find lot of solutions (included one written by me)

http://codepen.io/HugoGiraudel/pen/gbgBem/

maybe there's something useful.

**Comment by rosskevin** [comment]
Is this required in the material design spec or just nice to have?
