### ISSUE TITLE
Sidemenu / icon idea

### ISSUE THREAD

**Issue by bboerendans** [mdbootstrap/mdb-ui-kit#526]
Hi,

I have no idea where to start to make it compatible with this theme, but maybe it will be a nice idea to implement a sidemenu + hamburger-to-arrow icon for mobiles like i did with my testwebsite http://netwaves.nl/poollicht/ .

I have used these 2 things:
sidemenu http://zombiehippie.github.io/Side-drawer/
material hamburger menu https://github.com/swirlycheetah/material-design-hamburger

I've added swipe gestures as well in my test website too open and close the menu (http://hammerjs.github.io/)

Sidenote: the ripple effect i'm using at the moment is https://github.com/fians/Waves.

**Comment by FezVrasta** [comment]
I'm not sure it's  a good idea add all this stuff to this framework... Let's see what other guys say

**Comment by GradyD** [comment]
I feel that the project is starting to reach a point where it is in a pretty stable state. I think that starting to add new features would be a step in the right direction. 

As for merging all of this in like it stands... I think might be a bad idea. I believe that some of the code can be cleaned up and reformatted to better align with the coding style of this project. 

Personally I would like to see this added but in a more generic way that allows for navigation similar to what Google Inbox does.

**Comment by Danielku15** [comment]
I'd also love to see a sidebar/-menu functionality in this library. But the library should aim for a solution that reflects the [Material Design Guidelines](http://www.google.com/design/spec/layout/structure.html#structure-side-nav): 

In your sample the top navigation becomes the contents of the sidebar, but in most of the newer mobile apps have separate "app bar" and "navigation drawer" contents. According to the Material Design Guidelines, the "app bar" should have:
- a "nav icon" which opens the side navigation 
- a title, like now
- action icons  
- a menu icon. 

(See [App Bar](http://www.google.com/design/spec/layout/structure.html#structure-app-bar))

The navigation drawer has the actual app menu in it. While on mobile systems the side menu is shown as a temporary overlay, on desktop system you have a pinning/toggle mechanism. 

http://www.google.com/design/spec/patterns/navigation-drawer.html

Demo Web Sites using this behavior: 
http://www.google.com/design/spec/
http://inbox.google.com
http://materializecss.com/
https://material.angularjs.org
http://codepen.io/zavoloklom/pen/dIgco

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
