### ISSUE TITLE
Checkbox validation over the checkbox

### ISSUE THREAD

**Issue by geoguide** [mdbootstrap/mdb-ui-kit#527]
The actual checkbox element that is "hidden" should be below the generated checkbox so the user can click the checkbox.

http://grab.by/FQR8

**Comment by FezVrasta** [comment]
What's that tooltip?

**Comment by geoguide** [comment]
@FezVrasta It's native HTML5 form validation

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
