### ISSUE TITLE
What is difference between 'card', 'well', and 'panel'?

### ISSUE THREAD

**Issue by chongkong** [mdbootstrap/mdb-ui-kit#528]
Well, they seemingly provides same result (at least on my eye?), so I'd wanted to ask question of it.
- Is there a difference in rendered results?
- So it is just difference of usage? Could you provide some simple example of comparison?

p.s. What does bs-component mean, which comes quiet often with `<div class="well">`.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
