### ISSUE TITLE
Icons are crazy

### ISSUE THREAD

**Issue by caiowilson** [mdbootstrap/mdb-ui-kit#529]
the mdi-action-search for example points to mdi-action-room. every icon is behaving weirdly.

**Comment by FezVrasta** [comment]
probably some cache problem?

the demo works correctly...

**Comment by caiowilson** [comment]
nops, just tested. with the current eot svg woff and ttf it's broken, with the old one (not sure the version, i'm sorry) it works, changed my files back to what i had in my repo.

**Comment by FezVrasta** [comment]
It's most likely a problem on your side, the demo works correctly

http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

**Comment by caiowilson** [comment]
any guess on why would the new fonts mess it up on my side?

**Comment by FezVrasta** [comment]
we have updated them and then you are probably having some cache problem (you load the old CSS or the old font) and the two files mismatch

**Comment by caiowilson** [comment]
its local and non cached, but i'll try to verify that later and get back here.

**Comment by jerone** [comment]
If it's local it's probably a folder linking issue. Have you tried running it from a server and watching your web developer tool for missing files?

**Comment by FezVrasta** [comment]
even local files are chached by browser. fyi

**Comment by caiowilson** [comment]
I know local files are cached, I meant mine weren't. I'll dig into it. maybe it's missing files as @jerone suggested. I spend too much time looking at my js source and console I may have missed it. I'll get back here asap.

**Comment by caiowilson** [comment]
it just fucks up with the new fonts. no idea. no missing nothing.

**Comment by caiowilson** [comment]
Today i'm deploying the first RC, i'll then test locally the font issues more thoroughly, guess i'll be back soon.
in the meantime: is there a class for defining specific height shadows? like shadow 1, 2 and 3 z 'axiswise'

**Comment by GradyD** [comment]
Yes there is, http://fezvrasta.github.io/bootstrap-material-design/#shadow

`shadow-z-#` where `#` is a number 1-5.

**Comment by caiowilson** [comment]
Thank you @GradyD , although I found it pretty soon after asking... haha, my bad. But I love this project and It's community. Thank you all.

**Comment by caiowilson** [comment]
@FezVrasta I'm sorry I didn't have the time to proprly check the icons issue, as soon as I can I promise I'll do it.

**Comment by FezVrasta** [comment]
There's also a dedicated repository right now.
https://github.com/FezVrasta/material-design-iconfont

**Comment by caiowilson** [comment]
I know they're supposed to be cached. I was only stating that mine wasn't.
Yet,  the missing files may be a good starting point. I spend most of my
time looking at my js and console I may have let it slip past me. Thanks.
I'll update you tomorrow.
