### ISSUE TITLE
new checkboxes

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#53]
the specs for checkboxes was updated, this is a good CSS only implementation of them. 

http://jsfiddle.net/cavico/a7u9jwhn/1/

we should update our implementation.

**Comment by cncolder** [comment]
not css only
we need add `<span class="check"></span>` after :checkbox also.
so just a new style.

**Comment by FezVrasta** [comment]
yes exactly ^_^

**Comment by cncolder** [comment]
I have finished(maybe) copy them style. pr later.

**Comment by cncolder** [comment]
http://jsfiddle.net/colder/e2z8j7mh/

have some position issue in `input-group-addon`

**Comment by FezVrasta** [comment]
thanks, seems there's not the ripple effect, is it a problem of my browser?

**Comment by cncolder** [comment]
their(google) implementation without ripple.
i am not expert at css.
i will take ripple back.

**Comment by FezVrasta** [comment]
you can use this pen to develop new features:

http://codepen.io/FezVrasta/pen/ihmea

I've included every needed dependency.

**Comment by cncolder** [comment]
cavico/Web-Starter-Kit-Checkbox use `.check` as background, `:after` as marker(✓), `:before` as accessibility check.

so...
i don't know where can i put our ripple.

**Comment by FezVrasta** [comment]
I see that ":before" is used as ripple. Am I missing something?

**Comment by cncolder** [comment]
oh yes. ripple at focus. and do not support safari. so i have not saw that before.

**Comment by FezVrasta** [comment]
probably would be better use my css animations instead of the implementation of cavico

**Comment by cncolder** [comment]
you have use `:before` to make check marker. `:after` to make ripple.
if we want to a white marker in a green box.
the only way is let `.check` become that green box background.

but this will raise new layout issue. old animation need change to fit new layout.

**Comment by FezVrasta** [comment]
I assign this issue to me, I'll see what can I do tomorrow.

**Comment by cncolder** [comment]
http://jsfiddle.net/colder/e2z8j7mh/1/

here is the final effect.

**Comment by chenxinru** [comment]
good work

**Comment by cncolder** [comment]
@FezVrasta do you need my pr? i have resolve the focus issue. with animation end event handler.

**Comment by FezVrasta** [comment]
yea a PR would be helpful

**Comment by cncolder** [comment]
http://codepen.io/colder/pen/xznbC

**Comment by FezVrasta** [comment]
ok thanks I'm waiting the pull request to be able to merge your branch with the develop branch

**Comment by cncolder** [comment]
this pr fork from newest master.

**Comment by TransitoryBliss** [comment]
OK, in the future develop on the develop branch, makes it easier to keep a clean master. Especially now when it's a lot of development going on.

**Comment by cncolder** [comment]
agree.
i will checkout develop now.

**Comment by FezVrasta** [comment]
I'm writing from scratch the checkboxes, the ones created by cavico use too much elements, I'm writing one which uses just a :before pseudo-element to create the entire "check" animation.

**Comment by FezVrasta** [comment]
new checkbox style are ready.

Not sure if lot of people use the box shadows in this way but it works!

**Comment by cncolder** [comment]
looks great :+1:

**Comment by FezVrasta** [comment]
problem

I'm using overflow: hidden to hide the overflow shadows... but this prevent the ripples for being shown.

![image](https://cloud.githubusercontent.com/assets/5382443/4519505/e95ff494-4cbe-11e4-9eca-2c76a00d683b.png)

![image](https://cloud.githubusercontent.com/assets/5382443/4519503/d160983a-4cbe-11e4-9819-01c28b8d469b.png)

has someone a solution? The only idea I have is to create the check with more shadows to make sure them do not overflow.

**Comment by cncolder** [comment]
performance?
i have try 100+ checkboxes in a page. cavico version a bit faster than us.

**Comment by FezVrasta** [comment]
Who uses 100+ checkboxes in the same page?

**Comment by TransitoryBliss** [comment]
I will just leave this here http://c2.com/cgi/wiki?PrematureOptimization

**Comment by cncolder** [comment]
aha, only 42 checkboxes. but it's a real example. choose shoes sizing.
but that's ok. i agree @shockwork . let's make it works first.

![2014-10-06 4 30 50](https://cloud.githubusercontent.com/assets/127009/4519877/ace3fd7a-4cce-11e4-859c-99429d902493.png)

**Comment by FezVrasta** [comment]
What about a select box to choose the shoes size? :P
