### ISSUE TITLE
Input Floating Labels Not Working with Multiple Inputs In a Div

### ISSUE THREAD

**Issue by SpencerLynn** [mdbootstrap/mdb-ui-kit#530]
I'm having some issues with floating labels working on the same page.

If I have only one of them, it works great. But if I add subsequent inputs to the same div, the floating labels break on all inputs.

```
<div class="form-group medium-width">
    <label class="control-label">Label</label>
    <div class="inputs">
      <input type="text" class="form-control floating-label" ng-model="ctrl.value1" placeholder="Place 1">
      <input type="number" class="form-control floating-label" ng-model="ctrl.value2" placeholder="Place 2">
      <input type="number" class="form-control floating-label" ng-model="ctrl.value3" placeholder="Place 3">
    </div>
    <button class="btn btn-primary" ng-click="ctrl.save()">Add</button>
  </div>
```

**Comment by FezVrasta** [comment]
are you adding them dynamically? If so you need to initialize them manually or include arrive.js and let it do it for you

**Comment by SpencerLynn** [comment]
No. They are not being added dynamically. They are in the HTML.

arrive.js is loaded in the page.

**Comment by FezVrasta** [comment]
may I have some kind of demo to stare at? I can't find the problem with not enough info.,.

**Comment by SpencerLynn** [comment]
Sure. Here is a page with three inputs.

http://discores.azurewebsites.net/#/courses

**Comment by SpencerLynn** [comment]
Here is the code for those inputs.

```
<input class="form-control floating-label" type="text" ng-model="courseCtrl.newName" placeholder="Where ya playin'?" />
<input class="form-control floating-label" type="number" ng-model="courseCtrl.newPar" placeholder="What's par?" />
<input class="form-control floating-label" type="number" ng-model="courseCtrl.newNumberOfHoles" placeholder="How many holes?" />
```

**Comment by rosskevin** [comment]
Please try again with 0.4.1

> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
