### ISSUE TITLE
Select animation causes mouse to glitch

### ISSUE THREAD

**Issue by GradyD** [mdbootstrap/mdb-ui-kit#531]
If you are using a `<select>` and try to select an option while the animation is running the hover item keeps jumping around. Once loaded it works as expected without any issues.

**Comment by FezVrasta** [comment]
May you record it with some software (eg: Licecap) so I can see the problem? I don't think I get what you mean...

**Comment by GradyD** [comment]
![selectissue](https://cloud.githubusercontent.com/assets/994964/7080869/2358f404-df07-11e4-9590-c48939231373.gif)

Notice when I try and quickly select an item it freaks out.

**Comment by FezVrasta** [comment]
ahhh... oh well I don't think it's an important problem, it's just the demo page and the stupid script that shows the source code...

**Comment by GradyD** [comment]
I can replicate this on my own projects, I just used the demo page to capture it.

**Comment by FezVrasta** [comment]
ahh sorry I was looking at the wrong part of the screen lol.. yes that's a problem

**Comment by rosskevin** [comment]
Can it be reproduced as a test case with the latest code?

> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
