### ISSUE TITLE
Checkbox doesn't work without the material-fullpalette.css

### ISSUE THREAD

**Issue by fbatiga** [mdbootstrap/mdb-ui-kit#533]
Hello,

The checkbox doesn't work if the page is not associated with  the material fullpalette. I have pinpointed the issue to this block of animations : ( line 21500 to 21700 ). 

```
    example of missing animation : animation: checkbox-on .3s forwards;
```

They should probably be moved to the material.css file (i'm not completely familiar with less so i can't do a merge request).

**Comment by ddmng** [comment]
Hi,
  it happens to me too.
Is there any workaround for this?

Thanks!

**Comment by FezVrasta** [comment]
I'll try to fix it tomorrow

**Comment by ddmng** [comment]
False alarm here. I had a bug elsewhere and now it's showing without the fullpalette.
I've only an issue with the ripple that's appearing below the checkbox but I should solve that too.

Thanks.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
