### ISSUE TITLE
Add version numbers to material and ripple js

### ISSUE THREAD

**Issue by noctivityinc** [mdbootstrap/mdb-ui-kit#534]
Please add some kind of header with a version number to the js files.  Im updating those directly from the repo and its hard to know if I have the latest version or not.

Thanks.

**Comment by jerone** [comment]
[Agreed](https://github.com/FezVrasta/bootstrap-material-design/issues/441#issuecomment-75041673).

**Comment by rosskevin** [comment]
The version number exists in the downloaded `.bower.json` or `package.json`, otherwise a PR is welcome.

> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
