### ISSUE TITLE
Button is not Flat

### ISSUE THREAD

**Issue by abhinaykumar** [mdbootstrap/mdb-ui-kit#535]
Every thing is working as expected except button.
I am using this code 

```
<%= link_to "Click Here to Login", new_user_registration_path, class: "btn btn-primary btn-lg" %>
```

below is the image where you can see button is not flat:

![screenshot from 2015-03-30 00 01 26](https://cloud.githubusercontent.com/assets/4496810/6887107/41961fb6-d672-11e4-8eb1-dbfc2496d95c.png)

**Comment by FezVrasta** [comment]
you are not using the `btn-flat` class...

**Comment by abhinaykumar** [comment]
but on this page http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html
when i inspect element, i dont see any class named "btn-flat"

**Comment by FezVrasta** [comment]
Ok probably you are using the wrong nomenclature... Your screenshot is weird, looks like the Material Design style is not applied. Open the console and check if there are some errors, you are probably not including correctly the library.

**Comment by abhinaykumar** [comment]
I think Material design is working but only to the limited classes like well, jumbotron etc. in my case ofcourse. Also, there are no errors in the console.

adding class: "btn-flat" results in
![screenshot from 2015-03-30 00 32 16](https://cloud.githubusercontent.com/assets/4496810/6887154/42a4f8ee-d674-11e4-8880-dac08d837fd2.png)

**Comment by FezVrasta** [comment]
Ok really no idea, it's 100% a problem with your specific project, but I don't have any clue if you don't give me some working demo or a link to it.

**Comment by abhinaykumar** [comment]
Well thats OK, right now the code is on my system.
github repo will do or you need working demo only ?

**Comment by FezVrasta** [comment]
a github repo would be fine I think. Consider that not being a problem with my project I'm doing it just because I've some free time. I can't promise anything.

**Comment by abhinaykumar** [comment]
OK then let me quickly push it to github.
and thanks for everything, I dont want to waste your time but if you can just help me on this
then that would be really great.

**Comment by FezVrasta** [comment]
no rush, I'll do it as soon when I find a minute :)

**Comment by abhinaykumar** [comment]
thank you. :+1: 
Its here https://github.com/abhinaykumar/bootstrap-material
Sure whenever you find sometime just have a look at it and I am open to any suggestions as well 
if you want to give any. 
Its my pleasure to talk to you. thanks for such wonderful work.

**Comment by FezVrasta** [comment]
Seems like you are using the SASS version, it's outdated and not maintained anymore (no one wanna take care of it). I don't know if you can move to LESS, but it would be a great idea.

**Comment by abhinaykumar** [comment]
Ohh thats a bummer!!, well thanks then. 
I will give a try to LESS. will let you know if that works.
thanks for everything, have a nice day!!

**Comment by abhinaykumar** [comment]
Sorry If I am bothering you too much but I couldn't find any Gem or help on integrating LESS version of bootstrap-material-design, although this gem https://github.com/metaskills/less-rails says that it "provides integration for Rails projects using the Less stylesheet language in the asset pipeline." but I dont know how to use the LESS version of your bootstrap into my Rails-project. 
Will you help me on this ?

**Comment by FezVrasta** [comment]
I'm sorry but I've not knowledge with ruby

**Comment by abhinaykumar** [comment]
thats completely fine :+1:  thanks :)
