### ISSUE TITLE
IE10 Cannot click to focus input with floating label

### ISSUE THREAD

**Issue by higgins777** [mdbootstrap/mdb-ui-kit#537]
Greetings,

I'm not sure what sort of browser compatibility is really being targeted, but I found that if you try to click on the floating label (prior to it floating), then it will just act like static text and not allow input.

This issue seems unique to IE10 and potentially early versions, seems resolved in IE11. Any idea where to start for a work around before I just go with standard labels? 

If you have IE10 available it can be reproduced on the demo by clicking directly on the "floating label" text: http://fezvrasta.github.io/bootstrap-material-design/#input

Thanks!

**Comment by higgins777** [comment]
Just added some Jquery to focus labels for the time being.

**Comment by GradyD** [comment]
Just wanted to let @FezVrasta know that I have confirmed this. It is only an issue with IE10 and lower, IE11 works. 

![ie10floatlabel](https://cloud.githubusercontent.com/assets/994964/7080943/42ede378-df08-11e4-9cbc-0c01d6e9f003.gif)

**Comment by rosskevin** [comment]
Please try again (actually, this test case link is a floating label) and reopen if still an issue.  Thank you)

> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).

**Comment by dannygoncalves** [comment]
Hi, I know this is closed but @GradyD or @higgins777  did you find a solution for this?

**Comment by higgins777** [comment]
I took a quick look and I think my workaround was to use the JS below, and add that '.focus-my-children' class to the input wrapper.

JS
```
    $('.focus-my-children').click(function(){
      $(this).find('input:first').focus();
    });
```

Added focus-my-children class to an input wrapper div
```
<div class="form-control-wrapper tiny-top-buffer focus-my-children">
<div class="form-control-wrapper"><input class="form-control empty" data-hint="These comments will be visible on the detailed report" id="focusedInput" name="beforebegin[rc4]" value="" type="text"><div class="hint">These comments will be visible on the detailed report</div><div class="floating-label">Comments</div><span class="material-input"></span></div>
</div>
```
