### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by woozyking** [mdbootstrap/mdb-ui-kit#54]
Hi,

Can we get this amazing theme on some sort of CDN such as cdnjs or jsdelivr?

Thank you!

**Comment by FezVrasta** [comment]
Will see what can I do :)

**Comment by dandv** [comment]
I've had a good experience with https://github.com/cdnjs/cdnjs

**Comment by FezVrasta** [comment]
I was looking into it as well, I'll try to release something this evening

**Comment by sentenza** [comment]
Consider also this GitHub based CDN service: https://rawgit.com/

**Comment by TransitoryBliss** [comment]
Anyone with good experience of a good flow for releasing to CDNs? Considering we have barely tagged the repository yet as it's quite unstable.

**Comment by FezVrasta** [comment]
Looks like some good guy did the work for us:

https://cdnjs.com/libraries/bootstrap-material-design

@PeterDaveHello  s the guy!
https://github.com/cdnjs/cdnjs/commit/cbce383cdd6a1851ed7cac48ba6e2f37947dc30d

**Comment by jimaek** [comment]
@FezVrasta We added your project to [jsDelivr](https://hacks.mozilla.org/2014/03/jsdelivr-the-advanced-open-source-public-cdn/) too http://www.jsdelivr.com/#!bootstrap.material-design

**Comment by PeterDaveHello** [comment]
I added 8 days ago :) 
https://github.com/cdnjs/cdnjs/commit/dc271403f4839109c2f05ec8b839d514ae3a7d0f

**Comment by TransitoryBliss** [comment]
@jimaek @PeterDaveHello thanks :)!

**Comment by FezVrasta** [comment]
@jimaek I can't find anything on the link you've provided

**Comment by jimaek** [comment]
@FezVrasta It was a temp issue with search of the website, the DB had some problems. It should be fine now. Sorry about that

Here is our auto-update bot in action too https://github.com/jsdelivr/jsdelivr/pull/2176

**Comment by FezVrasta** [comment]
thanks, added to the readme at develop branch
