### ISSUE TITLE
navbar-light-grey color is missing from the fullpalette

### ISSUE THREAD

**Issue by romdim** [mdbootstrap/mdb-ui-kit#541]

**Comment by FezVrasta** [comment]
You must use a light shade of grey, the image on homepage is outdated

**Comment by othermachines** [comment]
Related? I'm getting the error below during less compile. @lightgrey isn't defined anywhere.

```
SyntaxError: variable @lightgrey is undefined in dist\less\_navbar.less on line 169, column 3
```

**Comment by eric-wieser** [comment]
Same issue. `@light-?gr[ae]y` has no matches within `/less`. Where is this variable supposed to come from?
