### ISSUE TITLE
Reference to deprecated file in README

### ISSUE THREAD

**Issue by othermachines** [mdbootstrap/mdb-ui-kit#542]
I'm really loving this theme. Thanks!

In README.md _Getting Started_ we are instructed to change the primary color of the theme by creating a less file that contains (as an example) the following:

```
@import "../bower_components/bootstrap-material-design/less/material-wfont.less";

// Override @primary color with one took from _colors.less
@primary: @deep-purple;
```

However according to the CHANGELOG material-wfont.css is deprecated as of v 0.3.0.

**Comment by FezVrasta** [comment]
Thanks, I'll update the readme
