### ISSUE TITLE
update source code view at section 'List groups' on preview page

### ISSUE THREAD

**Issue by d-koppenhagen** [mdbootstrap/mdb-ui-kit#544]
Please update the source code on `https://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html`
in the section 'List groups'  you forgot to add the following lines in Source Code View of this section (related to a list group with checkbox):

```
<span class="checkbox-material">
   <span class="check"></span>
</span>
```

**Comment by FezVrasta** [comment]
you have to initialize such elements to add that markup (`$.material.init()`), the source code view, in fact, shows the real source code of the page.
