### ISSUE TITLE
Ripple don't work on mobile devices

### ISSUE THREAD

**Issue by Rom4eg** [mdbootstrap/mdb-ui-kit#545]
RippleJs has a bug in ripples.js on line 200 in function Ripples.prototype.getRelY.

this not work.

```
if(event.touches.length !== 1) {
        return event.touches[0].pageY - wrapperOffset.top;
}
```

need to remove '!' symbol and it's work fine

```
if(event.touches.length == 1) {
        return event.touches[0].pageY - wrapperOffset.top;
}
```

if was 1 touch then start ripple effect, else do nothing(return False)

**Comment by Rom4eg** [comment]
I'm sorry. on line 200

this not work.
```
if(event.touches.length !== 1) {
        return event.touches[0].pageY - wrapperOffset.top;
}
```
need to remove '!' symbol and it's work fine
```
if(event.touches.length == 1) {
        return event.touches[0].pageY - wrapperOffset.top;
}
```

**Comment by Rom4eg** [comment]
@FezVrasta You tested? I'm right?

p.s. Sorry for my english.

**Comment by FezVrasta** [comment]
I had still no time to test it :(

**Comment by kdex** [comment]
I'd love to see some progress here. Great work so far, @FezVrasta!

**Comment by Rom4eg** [comment]
@FezVrasta Thank's. I'll close this issue.
