### ISSUE TITLE
floating label missing 

### ISSUE THREAD

**Issue by claudiosantina** [mdbootstrap/mdb-ui-kit#550]
I think this css rule is missing

.form-control-wrapper .form-control:focus ~ .floating-label,
.form-control-wrapper .form-control:not(.empty) ~ .floating-label {
  opacity: 1;
}

**Comment by X3Technology** [comment]
Confirmed.  I'm seeing the same issue.  The floating label disappears as soon as you type anything in the input. 

Oddly, the demo here still works: 
https://fezvrasta.github.io/bootstrap-material-design/#input

**Comment by rosskevin** [comment]
Please check the latest 0.4.1, floating labels reworked, but could still be an issue.

> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
