### ISSUE TITLE
icon class issue

### ISSUE THREAD

**Issue by sivailango** [mdbootstrap/mdb-ui-kit#551]
Did you miss to add dot (.) in front of icon-\* ? 

i.e 
.mdi-info,
icon-info {
  color: #03a9f4;
}

Also if i want display text in material color, i think there is no way to do that? Can you add .text-material-{{color}}-{{size}}? Its my suggestion.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
