### ISSUE TITLE
alert-default as white background and text

### ISSUE THREAD

**Issue by Eonasdan** [mdbootstrap/mdb-ui-kit#553]
`alert-default` as the same `rgba` setting for both `color` and `background-color`

https://github.com/FezVrasta/bootstrap-material-design/blob/master/dist/css/material.css#L6717

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
