### ISSUE TITLE
Floating label

### ISSUE THREAD

**Issue by sigorilla** [mdbootstrap/mdb-ui-kit#554]
Hi!

When I added `floating-label` class to input without placeholder, so instead of empty string I saw floating label with `undefined` string.

**Comment by Zyst** [comment]
RTFM

**Comment by FezVrasta** [comment]
What would you expect? The input to act like a not-floating-label input or what?

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
