### ISSUE TITLE
CSS is different from the live demo

### ISSUE THREAD

**Issue by tank22119** [mdbootstrap/mdb-ui-kit#556]
my browser is Firefox37.0.1

I found that everything at live demo works well

but at local i encountered the problem just like #549 

and then i download material-fullpalette.min.css from live demo

finally everything works fine

so, could you Sync the code?

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
