### ISSUE TITLE
Resizing checkbox hides check

### ISSUE THREAD

**Issue by noctivityinc** [mdbootstrap/mdb-ui-kit#557]
If you try to change @checkbox-size to something smaller, such as 14px, the check wont appear in the box.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
