### ISSUE TITLE
autofocus doesn't work

### ISSUE THREAD

**Issue by FBoquet-exp** [mdbootstrap/mdb-ui-kit#56]
trying to use an input like this : 
<input ... autofocus>

=> I don't get the focus when the page is loaded (using safari and chrome)

**Comment by FezVrasta** [comment]
Can't see the example I think..

**Comment by FBoquet-exp** [comment]
Don't know why but I can't display HTML code
Anyway the problem is that an input don't get the focus even if I add the "autofocus" attribute.

**Comment by martin-g** [comment]
Wrap the code in backticks:
`
<demo>code</demo>
`

**Comment by FezVrasta** [comment]
http://codepen.io/FezVrasta/pen/yfwrj

confirmed

**Comment by martin-g** [comment]
Seems to work fine in full screen: http://codepen.io/FezVrasta/full/yfwrj/

**Comment by FezVrasta** [comment]
oh right, didn't tried it, :stupid:
