### ISSUE TITLE
links in panel-heading incorrect color

### ISSUE THREAD

**Issue by liesislukas** [mdbootstrap/mdb-ui-kit#560]
div.panel-primary > div.panel-heading > a

this gets 

a, a:hover, a:focus {
  color: #009688;
}

from line 2592 in material.css

![ss](https://cloud.githubusercontent.com/assets/2733862/7217101/d0bddbe4-e620-11e4-9bda-384c51069212.jpg)

fix:

.panel-primary .panel-heading a, .panel-primary .panel-heading a:visited, .panel-primary .panel-heading a:hover, .panel-primary .panel-heading a:active {
  color: rgba(255, 255, 255, 0.84);
}

**Comment by rosskevin** [comment]
Please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.
