### ISSUE TITLE
Checkboxes not displaying properly in Safari

### ISSUE THREAD

**Issue by noctivityinc** [mdbootstrap/mdb-ui-kit#561]
Im having odd issues with the checkboxes in Safari.  Im sure its my other code somehow since the demos work, but not sure what would cause this.  Anyone else experience anything like the attached?

![screen shot 2015-04-18 at 9 13 42 pm](https://cloud.githubusercontent.com/assets/78850/7217769/ff73e398-e611-11e4-9316-47167f851ce9.png)

**Comment by noctivityinc** [comment]
Forget it.  It had to do with not autoprefixing the LESS files and compiling on the fly.

TBH - you REALLY should update the README that LESS needs to be compiled and then autoprefixed and how to do that.  Those of us coming from SASS have no idea what to do.

**Comment by FezVrasta** [comment]
I'll add it, thanks
