### ISSUE TITLE
Npm package

### ISSUE THREAD

**Issue by tenbits** [mdbootstrap/mdb-ui-kit#562]
Hi @FezVrasta , could you please also upload the package to the npm. There is already [one](https://www.npmjs.com/package/bootstrap-material), but it has other mainteiner and is also awfully outdated. 

Thanks, Alex

**Comment by trevorbernard** [comment]
I second that request. :shipit: :+1: 
Best,
Trevor

**Comment by creynders** [comment]
:+1:

**Comment by tachuris** [comment]
+1

**Comment by tachuris** [comment]
@tenbits @trevorbernard @creynders I've published the latest tagged version (0.3.0): https://www.npmjs.com/package/bootstrap-material-design

@FezVrasta Please, give me your npm username to add you as "collaborator".

**Comment by FezVrasta** [comment]
@rstuven I've took ownership of the bootstrap-material NPM package. Not sure if we should have two npm modules...

**Comment by FezVrasta** [comment]
```
"You cannot publish over the previously published version 0.1.5." : bootstrap-material
```

:/ why.. why...

**Comment by FezVrasta** [comment]
Ok looks like the right name of the NPM package is bootstrap-material-design so we should use the one from @rstuven, my npm name is fezvrasta, please add me :)

**Comment by rosskevin** [comment]
@FezVrasta I didn't upload to NMP the 0.4.1.  Perhaps I need to be added so I can do that as part of any release?

**Comment by sankho** [comment]
bumping this @FezVrasta ...the theme's awesome but I would love to drop bower as a dependency and just use NPM!

**Comment by FezVrasta** [comment]
Added rosskevin as collaborator of bootstrap-material-design on NPM
