### ISSUE TITLE
All but Tooltips not working

### ISSUE THREAD

**Issue by suntong** [mdbootstrap/mdb-ui-kit#564]
UPDATE (was title as "All but Tooltips not working")
- I got a copy from https://github.com/FezVrasta/bootstrap-material-design/archive/0.3.0.tar.gz
- Everything is working except when duplicating the Tooltips demo 
- Here is how I did:
  
  cd /var/www/bmd
  view bootstrap-elements.html 
  visit http://my.site/bmd/bootstrap-elements.html
  
  cp dist/test.html . 
  visit http://my.site/bmd/test.html
  edit test.html 

The content of my final edited test.html is posted in http://pastie.org/10105740. Everything is working except the duplicated Tooltips demo. I.e., no any tooltips showing. Why is that? They show well in http://my.site/bmd/bootstrap-elements.html. What I'm missing? 

**UPDATE 1**
Well, found that the ripple effect is not working, even in the http://my.site/bmd/dist/test.html file. Looking at the the CSS inclusion, I think that file should be placed above the dist folder, hence I copied it up. the ripple effect is working fine in http://my.site/bmd/bootstrap-elements.html. So there must be something missing from the distributed `dist/test.html`. 

**UPDATE 2**
Thanks to GradyD's help, I found two js errors. Having correct them both, the ripple effect is working. Now no errors in the developer console, but tooltips are still not working. 

Please help.

Thanks

**Comment by FezVrasta** [comment]
are you compiling from source or using the provided precompiled css?

**Comment by suntong** [comment]
I just download the https://github.com/FezVrasta/bootstrap-material-design/archive/0.3.0.tar.gz and expand it as `/var/www/bmd`, and all the rest of steps are listed above. I don't quite understand your question, but hope you can understand mine. Thanks.

**Comment by suntong** [comment]
I make the `bootstrap-elements.html` file working with CDN (http://my.site/bootstrap-elements.html, ref #570), then substitute its content with the content of my above test file. However, neither the ripple effect nor tooltips are working. So something is wrong with... no, can't understand. 

The `bootstrap-elements.html` file using CDN: ... too big to paste anywhere, see the diff in #570.
The `test.html` file using CDN: http://pastie.org/10110066

**Comment by GradyD** [comment]
I know you have to run a grunt command of you want to view the demo page locally. i don't remember the exact command through...

**Comment by FezVrasta** [comment]
It's `grunt serve` but he's already using a web server so it should not be the problem. He's not running it from the file system

**Comment by suntong** [comment]
FezVrasta, have I answered your questions? Is it still "more info required"? 

After all, the Material-design theme is not working out of the box with the given example. I'm still waiting for an answer. 

Hope someone can spare some time to make the given example work out of the box. Thanks.

**Comment by GradyD** [comment]
When you open up the developer console do you see any errors?

**Comment by suntong** [comment]
Oh, thanks, found two js errors. Having correct them both, the ripple effect is working. Now no errors in the developer console, but tooltips are still not working.

**Comment by GradyD** [comment]
Glad that is fixed.

Looking at your example page you are not initializing the tooltips, http://getbootstrap.com/javascript/#opt-in-functionality

**Comment by suntong** [comment]
Ah, that's the problem, Thanks. 

I fixed the tooltips problem. I'll try to describe what I did as clear as possible.

To fix it, I tired
1. Duplicate my final edited test.html (posted in http://pastie.org/10105740) to https://gist.github.com/suntong001/9b9276bedbb6cd0b8443/177d7bd7cc7ec6cee9fe5d295a665e898affb8da
2. Make the change locally and to gist, https://gist.github.com/suntong001/9b9276bedbb6cd0b8443/revisions
3. New final edited posted at https://gist.github.com/suntong001/9b9276bedbb6cd0b8443/

This is why I made my change, based on http://getbootstrap.com/javascript/#opt-in-functionality, and:

```
$ grep 'tooltip()' bootstrap-elements.html
            $('.bs-component [data-toggle="tooltip"]').tooltip();
```

**Comment by suntong** [comment]
Thanks again GradyD!
