### ISSUE TITLE
Keep navbar color constant when switching to narrow width

### ISSUE THREAD

**Issue by dandv** [mdbootstrap/mdb-ui-kit#565]
The problem is illustrated in this screencast:

![bootstrap material design navbar color changes when resizing](https://cloud.githubusercontent.com/assets/33569/7264686/3cefb3b8-e843-11e4-9045-14fc9f51d09a.gif)

The color of the drop-down is white on wide displays and transparent on narrow ones. This causes a problem with [this library that displays the login buttons dropdown](https://github.com/ianmartorell/meteor-accounts-ui-bootstrap-3/issues/104). I've asked its author about providing compatibility with Bootstrap Material Design, and he said:

> With the default Bootstrap colors this is not noticeable because it goes from white to light gray, and the colors of the dropdown still work fine. In this case though the color scheme should be reversed to work on a dark background. It's not only the links on the bottom having the same color as the background, it's also affecting the inputs' highlights (the selected input should be highlighted but you can't see it because it has the same color as the background) and the readability of their contents. The button shouldn't have the same color either even if its text is readable. I'm not sure how I would go about fixing this though... I would say it's a bug on fezvrasta's package as this will happen to all dropdowns in a navbar.

The markup is below:

``` handlebars
<div class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <a class="navbar-brand" href="#">Meteor issue 4246</a>
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      {{> loginButtons}}
    </ul>
  </div>
</div>
```

Would it be possible for you gentlemen to work together towards solving this issue? CC @ianmartorell.

**Comment by FezVrasta** [comment]
So this plugin doesn't work neither on navbar-inverse because the background of the dropdown changes from white to black?

http://codepen.io/FezVrasta/pen/xGxdWr

I think the plugin should not set the colors and just use the Bootstrap CSS...

**Comment by ianmartorell** [comment]
Hey @FezVrasta, I completely agree with you, the package should use the colours provided by the Bootstrap CSS, and that's exactly what it's doing. If you compare the screenshots below you can see that your theme (or any other theme) controls the colors of the anchor links and other text in the dropdown:

Original:
![screen shot 2015-04-28 at 00 32 55](https://cloud.githubusercontent.com/assets/318800/7359469/e3e400ac-ed3e-11e4-948b-2da5dde99a45.png)
Material theme:
![screen shot 2015-04-28 at 00 31 55](https://cloud.githubusercontent.com/assets/318800/7359468/e3b4701c-ed3e-11e4-89b9-6186e55829f5.png)

So if the theme controls the colours of the links and buttons, it should also set them accordingly when the background turns to dark, don't you think?

This is what the dropdown looks like on navbar-inverse:
![screen shot 2015-04-28 at 00 29 02](https://cloud.githubusercontent.com/assets/318800/7359537/bc488c38-ed3f-11e4-8efd-f85e61ba7d92.png)
I think the links should be changed to white, but like you said, we're just using Bootstrap CSS, maybe we should submit an issue to them, too. At least we can read it all and it doesn't look too bad.

This is what it looks like on your theme:
![screen shot 2015-04-28 at 00 40 17](https://cloud.githubusercontent.com/assets/318800/7359541/c2e50152-ed3f-11e4-8144-eabfd335e65d.png)
You can't even read the text.

**Comment by dandv** [comment]
The theme needs to ensure that the link looks good on the navbar background. I've filed a [similar issue for some Bootswatch themes](https://github.com/thomaspark/bootswatch/issues/447#event-293627254), and the author has just fixed it.

**Comment by FezVrasta** [comment]
I'll fix it, thanks

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
