### ISSUE TITLE
JSF Project: Input underline not working on latest chrome, ie. Works in Firefox

### ISSUE THREAD

**Issue by Zyst** [mdbootstrap/mdb-ui-kit#566]
Found out that different browsers have some errors while running this.

Firefox v37: Everything works as intended.
Chrome v42: Underscore does not appear.
IE 11: Line underscore animation outright does not occur.

This was tested using JSF, so they are running inside xhtml files. 

**Firefox**:
![image](http://a.pomf.se/cgdsgk.gif)

**Chrome**:
![image](http://a.pomf.se/rlgwih.gif)

**IE**:
![image](http://a.pomf.se/hfpbqi.gif)

**Comment by Zyst** [comment]
HTML Code:

```
<div class="container jumbotron">
    <h:form styleClass="form-group-material-blue form-horizontal">
        <legend>Legend Test</legend>
        <div class="form-group">
            <p:outputLabel for="Test" class="col-lg-2 control-label primary-text-color">Float: </p:outputLabel>
            <div class="col-lg-10">
                <p:inputText id="Test" styleClass="form-control floating-label" type="text" pt:placeholder="It floats" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label" for="largeText">Larger input</label>
            <p:inputText id="largeText" styleClass="form-control" type="text" pt:placeholder="The largest of inputs" />
        </div>

        <p:commandButton value="Awesome Button" id="buttonTest" styleClass="btn btn-primary btn-material-blue btn-lg pull-right"  />
    </h:form>
</div>
```

**Comment by Zyst** [comment]
Header can be seen in this link: http://pastebin.com/99PxKxvN

Couldn't get the markdown to work without butchering the entire thing.

**Comment by Zyst** [comment]
After further analysis I believe the root cause of the issue might be that Primefaces is importing jQuery JavaScript Library v1.11.0

This version of jQuery is incompatible with the project, although a lot of stuff works regardless.

Still, I understand this is completely out of the scope of the development team, thus, I'll leave it at that, disregard the input fields and keep using the cool Jumbotron, buttons, and a few other goodies.

Sorry for the incorrect Issue raised.

**Comment by FezVrasta** [comment]
it's weird, the inputs underline animation is pure css powered.

**Comment by Zyst** [comment]
Yeah, I started using Materialize for the input fields and that does work
across browsers with JSF 2/Primefaces. Not sure why the inputs failed at
all on different browsers.

it's weird, the inputs underline animation is pure css powered.

##
