### ISSUE TITLE
Demo has incorrect class for material public icon

### ISSUE THREAD

**Issue by aljachimiak** [mdbootstrap/mdb-ui-kit#567]
When viewing the (demo for this repo)[http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html] the icon for mdi-social-public does not appear.

The issue seems to be that the css uses a different class than is specified in the markup.

![screen shot 2015-04-23 at 7 42 25 am](https://cloud.githubusercontent.com/assets/1467678/7296336/8fae491c-e98c-11e4-9528-b2eedb3046b2.png)

**Comment by aljachimiak** [comment]
Ahh... This is actually fixed in the master branch.

See this commit: https://github.com/FezVrasta/bootstrap-material-design/commit/b89afd8de56a57b1edc1c6e28d64f97b4e1fab1b

The solution looks like: get the latest changes into the gh-pages branch.

Is there a way I can help?

-Al

**Comment by FezVrasta** [comment]
I'll update the page soon
