### ISSUE TITLE
Browser frozen when debugger opened

### ISSUE THREAD

**Issue by jdutriaux** [mdbootstrap/mdb-ui-kit#569]
Hi, I don't know why but every time I refresh a page with Bootstrap Material Design included and the firefox developer tools opened my whole browser is frozen for about 15-20 seconds.

It makes the debugging tasks really painfull, the only solution I found is to close the dev tools then refresh then reopen dev tools.

I really don't know if it's Firefox's fault but I post here because I only had this issue with pages which includes Bootstrap Material Design.

Thanks for your work.
Halfman.

Edit : Tested on firefox 38, 39, 40. Same issue.
Edit 2 : Tested on Chrome, no issue.

**Comment by FezVrasta** [comment]
Nothing happens on Firefox 35, I'm updating and I'll let you know on the latest version.

(OS X)

ps: on 37 no problems

**Comment by jdutriaux** [comment]
Thanks for the answer. For more precisions it happens on Windows and Ubuntu 14.10. (Don't have OSX to try it)

My page don't have so much elements : this issue is weird :(.

**Comment by FezVrasta** [comment]
Does it happen even on the demo page at fezvrasta.github.com/bootstrap-material-design ?

I've not other OS to try this problem..

**Comment by jdutriaux** [comment]
Yes it happens on the demo page :(. 

I can take a little video if it helps you.

**Comment by FezVrasta** [comment]
I don't think it would be useful. I'll setup a vm with ubuntu to see the problem by myself.

**Comment by jdutriaux** [comment]
Tested on a colleague's OS X with firefox 37 : no issue.

**Comment by ThreeSevenths** [comment]
I also have this problem with IE11 when using the debugger or debugging through VS. It does not seem to happen unless I reference the fullpalette version of the CSS file.

**Comment by GradyD** [comment]
When you have dev tools open it probably is parsing and prettifing the code. I know that VS does this.

Due to the file size of the complete option this blows up the memory and also is a huge process for a browser to preform. I would look into see if this is the issue or if it can be disabled.

Side note, chrome has no issues.

**Comment by FezVrasta** [comment]
@GradyD neither Firefox and other browsers on OSX have issues. Looks like it happens only on Linux e Windows. I'm still trying to setup some VM to test it.

**Comment by FezVrasta** [comment]
I've just tried Firefox on Ubuntu and everything works perfectly...

**Comment by jdutriaux** [comment]
Thanks for these investigations. I'll make a video to show you exactly what happens.

**Comment by jdutriaux** [comment]
Here is a little video where you can see that the browser is frozen for approximately 5 sec when refreshing. (Time is longer with more tabs)

https://www.youtube.com/watch?v=_W-YVZXWiqY

Thanks :smile:

**Comment by francisbrito** [comment]
This also happens on my Ubuntu 14.04 PC using FireFox 37. As mentioned in the first comment, it only happens if you refresh the page **while** having FireFox dev. tools open.

**Comment by GradyD** [comment]
Ok, I spent some time on my windows 8.1 desktop 16gb of rams so it didn't freeze to long but I did notice it freezing when using Firefox and IE11. It only lasted 1-3 seconds, I am guessing this is related to my CPU/RAM being higher then the average computer. No matter how many tabs/things I opened it wouldn't freeze longer then 3 seconds.

As to the reason for this, I did some digging and the only difference between Chrome and FF is that FF was taking the minified CSS and JS and unminifing it. Being that there are multiple CSS and JS files and it is trying to process all of these into readable files. 

I have no idea what causes IE to load slowly and I was not able to get it to be consistent. Sometimes it would be slow but not like FF. When I bumped IE down from edge to 10 it did get slower. My guess is that it is something with IE just sucking in general.

**Comment by jdutriaux** [comment]
What CPU do you have @GradyD? I also have 16gb of RAM.

Maybe it's possible to prevent Firefox from pretiffy theses files.

**Comment by GradyD** [comment]
I have duel i5s lol. I don't use FF so I'm not what hidden settings they have.

**Comment by jdutriaux** [comment]
Bug seems to be solved on Firefox 40 alpha 2 :smile: with multi-process enabled. (Seems logic)

**Comment by FezVrasta** [comment]
Ah ok :)

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
