### ISSUE TITLE
Add git tags to support rails-assets.org

### ISSUE THREAD

**Issue by caarlos0** [mdbootstrap/mdb-ui-kit#57]
Please, push the tags so we can add it to rails-assets.org :dancer: 

Cheers

**Comment by FezVrasta** [comment]
Sorry I've not experience with rails... what are you talking about? :)

**Comment by caarlos0** [comment]
https://rails-assets.org/ maps bower dependencies as gems, so we can use them in rails with ease.

But, it depends on the tags... and you didn't pushed any :cry:

**Comment by FezVrasta** [comment]
I have "keywords"...

should I copy them in the "tags" attribute?

```
"tags": [
    "material",
    "design",
    "bootstrap",
    "theme",
    "google",
    "android"
]
```

**Comment by martin-g** [comment]
I think @caarlos0 means Git tags.
Push a tag with a release.

**Comment by FezVrasta** [comment]
oh I see

I've not experience with git tags... should I do something like:

```
git tag 0.0.1
git push --tags
```

? Do I need to update the tag on every commit I do?

**Comment by caarlos0** [comment]
I believe you should tag the same version that is in `bower.json`, and, with the same commit of that release...

So, probably it is [this commit](https://github.com/FezVrasta/bootstrap-material-design/commit/67e8e4fbbf507ec16763aa298bde3dd51571d1bc)...

``` sh
git tag "0.0.8" 67e8e4fbbf507ec16763aa298bde3dd51571d1bc
git push origin --tags
```

I'm not sure how bower works, but maybe it created the tags itself, and you just didn't pushed them. If so, `git tag` will show them, and you can use `git push origin --tags`.

**Comment by FezVrasta** [comment]
well the problem is that I'm not giving version numbers to my project at the moment... there are lot of commits everyday and most are critical bug fixes, so I'd need to change the version on every commit.

**Comment by FezVrasta** [comment]
added the 0.1.0 tag, we'll try to release a new tag for every feature version

**Comment by caarlos0** [comment]
Thanks!

**Comment by FezVrasta** [comment]
you're welcome
