### ISSUE TITLE
Text input css is not properly working when using required

### ISSUE THREAD

**Issue by siddhsuper** [mdbootstrap/mdb-ui-kit#571]
Hi,

I have put the required in the text input with the ng-message but it is showing not properly.

```
input.form-control(type='text' required ng-minlength = 5 ng-maxlength = 20 name='roleName' ng-model="roleName")
        div(ng-messages='rolesForm.roleName.$error')
          div(ng-message='required') Role name is required
          div(ng-message='minlength') Role min length is 5
          div(ng-message='maxlength') Role max length is 20    
```

Added the screen shot for the help.

I am trying this for a long time but couldn't get over it.

Thanks Much,
Siddharth Singh

![newimage](https://cloud.githubusercontent.com/assets/7190266/7303046/65157980-ea0b-11e4-9c98-28e3345dd62c.png)

**Comment by francisbrito** [comment]
Hello @siddhsuper. 

I think there's a syntax error on your Jade snippet. Did you mean this instead?

``` jade
input.form-control(type='text' required ng-minlength = 5 ng-maxlength = 20 name='roleName' ng-model="roleName")
div(ng-messages='rolesForm.roleName.$error')
  div(ng-message='required') Role name is required
  div(ng-message='minlength') Role min length is 5
  div(ng-message='maxlength') Role max length is 20
```

Also, could you please provide the rendered HTML?

**Comment by rosskevin** [comment]
This is likely affected by 0.4.1 release.

> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
