### ISSUE TITLE
Super slow

### ISSUE THREAD

**Issue by nkint** [mdbootstrap/mdb-ui-kit#572]
Hi. 
For sure a known issue but I have a very slow experience full of "freezy" seconds.
Is there any list of all things I can deactivate to try to make as light as possible?

Anyway, very good job a part that.

**Comment by FezVrasta** [comment]
I never read about these kind of problems. Please provide more informations and a demo of the problem.

Thanks.

**Comment by nkint** [comment]
I have removed ripples and things a much more better

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
