### ISSUE TITLE
Overlapping Floating labels with input value

### ISSUE THREAD

**Issue by PratibhaP** [mdbootstrap/mdb-ui-kit#573]
![overlappingfloatinglabels](https://cloud.githubusercontent.com/assets/5593075/7315185/aa666e72-ea88-11e4-9a6f-bb68b5206212.png)
 <script type="text/javascript">
    $(document).ready(function(){
        $.material.init();
    });
</script>  
I have initilized bootstrap-material-design using above code.
But if I set values to inputs using $("#roleName").val('Manager'); then the floating labels and value overlapping. 
Not getting where is the problem?

**Comment by FezVrasta** [comment]
you should trigger the `change` event when you set a value with JS.

**Comment by PratibhaP** [comment]
like $.material.change(); ?

**Comment by FezVrasta** [comment]
`$("#roleName").val('Manager').trigger('change');`

**Comment by PratibhaP** [comment]
Not working. :(

**Comment by FezVrasta** [comment]
It works here:

http://codepen.io/FezVrasta/pen/LVYaKv

**Comment by PratibhaP** [comment]
I am  using bootstrap-material-design with angularjs. In angularjs controller, binding the value to input after getting values from api success.

**Comment by PratibhaP** [comment]
Is there any way to handle this issue?

**Comment by PratibhaP** [comment]
$.material.options.autofill = true;
$.material.init();
using this floating label overlap problem sloves.

**Comment by FezVrasta** [comment]
great

**Comment by PratibhaP** [comment]
Thank you :+1:

**Comment by prasanna-ghose** [comment]
$.material.options.autofill = true;
is not working for textarea

**Comment by 6624465** [comment]
above codepen link broken.

**Comment by gmerabishvili** [comment]
Hello guys, Did you find any solution on textarea autofill fields? because "$.material.options.autofill = true"
is not working for textarea... :(
