### ISSUE TITLE
Question on inigration Ripple effects

### ISSUE THREAD

**Issue by Gregory-Phillips** [mdbootstrap/mdb-ui-kit#576]
I have a question regarding the Ripple Effect. I have been trying to integrate the bootstrap-material-design with a current bootstrapped site that I have created using the core .less and building my own. Right now I have most of the material design elements working.

However, I cannot create the ripple effect and I'm kinda at a point where I need some feedback. 
Do I need to integrate all the bootstrap-material-design .less files?

I have the core `ripples.min.css` and the `ripples.min.js` with `material.min.js`.

.less files i have imported:
`@import "../../bower_components/bootstrap-material-design/less/material.less";`
`@import "../../bower_components/bootstrap-material-design/less/ripples.less";`
`@import "../../bower_components/bootstrap-material-design/less/_buttons.less";`
`@import "../../bower_components/bootstrap-material-design/less/_navbar.less";`

I don't know what I am missing or have indirectly not associated with my code. If there is any help for me yet I hope someone can shed some light on this matter

**Comment by Gregory-Phillips** [comment]
I just loaded a live site that I still need to work out a few kinks. www.themobilemusicstudio.com. It is running most of the material code. However, I still cannot figure out why the ripple effects are not coming through.

**Comment by AdamHudsonNall** [comment]
I started using the LESS version and noticed the same thing. The compiled .css in the dist folder does work for me. It appears that the LESS version is not using the vendor specific tags for "animation", "transition", "@keyframe". 

Changed this to include the vendor specific versions for "-webkit","-o","-moz" and it works.

@FezVrasta are you using a LESS compiler that automatically adds the vendor specific tags? I need to research this because that would be a great feature. If not I can probably clean up my changes and resolve this issue for a few people. Apparently the current LESS version is working in some browsers that are not sensitive to the vendor specific versions of the aforementioned tags.

**Comment by FezVrasta** [comment]
The grunt task has autoprefixer built-in, to automatically add the prefixes

**Comment by AdamHudsonNall** [comment]
@FezVrasta , I assumed there was some option in the LESS compiler to accommodate this. I am using this with a Visual Studio project, so I need to check if the less compiler I am using has the autoprefixer. That would make my life so much easier.

Hopefully, this at least sheds some light on the issue for others.

**Comment by FezVrasta** [comment]
Less has not an autoprefixer built in, you should use grunt to be sure that the entire project compiles correctly.

**Comment by Gregory-Phillips** [comment]
I was just thinking about this and took a look into this. I'm not running Grunt on this project but might implement Grunt soon. I found this less auto-prefix plug-in https://github.com/less/less-plugin-autoprefix.

@AdamHudsonNall, I read that you had used the dist/css as where able to get the ripple to work. I just applied the `class="withripple"` and also loaded all the min.css on a project I'm working on using the full package unedited code. I was unsuccessful and the ripple was still not working. I'll try and approach this the same way you have by adding the vendor prefix before I try to use a auto-prefix solution.

**Comment by meetbryce** [comment]
@Gregory-Phillips a little late to the party, but it may be worth using Codekit which is a Graphical Interface for grunt/gulp/bower which will allow you to setup autoprefixer easily.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
