### ISSUE TITLE
Arrive.js with Meteor

### ISSUE THREAD

**Issue by nwalters512** [mdbootstrap/mdb-ui-kit#577]
Using Iron.Router with Meteor and this library, I've found that I'll have to recall `$.material.init()` each time a new template is rendered. You suggested `arrive.js` for this functionality; however, there's no clear way to add it to a Meteor project and ensure that it loads prior to `material.js`. I'm a total Meteor noob, so I'll defer to your expertise. What's the best way to go about this?

**Comment by FezVrasta** [comment]
Hello, unfortunately I've not experience with meteor :(

**Comment by Alveoli** [comment]
Hi @nwalters512, I'm about to try Meteor + this library. Still got this issue? Would you recommend going ahead?

**Comment by eskan** [comment]
Try to put arrive.js from https://github.com/uzairfarooq/arrive in client/lib/

**Comment by uzairfarooq** [comment]
I'm not experienced in meteor but have noticed that someone has put it on atmospherejs https://atmospherejs.com/modweb/arrive. Maybe that would help?

**Comment by ShockiTV** [comment]
just add weak dependency to som arrivejs package like this and it all starts to work ok
note for now: this arrive package have debugOnly set, so I am not sure if it will work for deploy.
I just cloned it to my package folder and removed that option.

```
api.use(['ryne:arrive-debug'],'client' , {weak: true, unordered: false});
```

Same with any package optional package.
Btw, with weak: true you need to add that ryne:arrive-debug with 

```
meteor add ryne:arrive-debug
```

It will not be added automatically
But for me, all works as a charm now :D

**Comment by ShockiTV** [comment]
I can mantain Meteor part if you need help.
BTW https://medium.com/@ShockiTV/how-i-tried-bootstrap-with-material-design-and-autoform-on-meteorjs-32333baad85f

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
