### ISSUE TITLE
list-group not styled properly

### ISSUE THREAD

**Issue by nwalters512** [mdbootstrap/mdb-ui-kit#578]
I installed this via the Meteor package manager, and by and large it worked great. However, I'm trying to create a `list-group`, but the styling isn't appearing as it should. My HTML is as follows:

``` html
<div class="col-md-2 list-group">
    <a href="#" class="list-group-item">Students</a>
    <a href="#" class="list-group-item">Teachers</a>
    <a href="#" class="list-group-item">Administrators</a>
    <a href="#" class="list-group-item">Places</a>
</div>
```

However, the items only render as stacked links, not the richly styled list that is visible [on the Bootstrap site](http://getbootstrap.com/components/#list-group-basic). Can the styles be updated to provide better support for `list-group` and `list-group-item`?

**Comment by rosskevin** [comment]
[Test case](http://codepen.io/rosskevin/pen/XmGGVL)

**Comment by rosskevin** [comment]
[0.5.1 Updated test case with some icons vs no icons](http://codepen.io/rosskevin/pen/zrORMq).

**Comment by rosskevin** [comment]
Is there a comparable component in the spec that we feel a list-group should emulate?  https://www.google.com/design/spec/material-design/introduction.html

**Comment by nwalters512** [comment]
I think the closest comparable component is just a standard list. Frankly, the default Bootstrap styling wouldn't look half-bad in a Material setting.

**Comment by rosskevin** [comment]
I know this isn't a solution for v3, but I've implemented the material design spec list on the v4-dev branch.  Example here: http://rosskevin.github.io/bootstrap-material-design/material-design/list-group/

If someone wants to try to port that back to v3, I'm happy to accept the PR.

**Comment by robophil** [comment]
i fixed this issue. check out fix on this  [codepen](http://codepen.io/RoboPhil/pen/zrMEqK).
Send a **PR**?

**Comment by rosskevin** [comment]
Yes
