### ISSUE TITLE
Floating-labels on inputs that are converted to hidden should disappear

### ISSUE THREAD

**Issue by lamoni** [mdbootstrap/mdb-ui-kit#579]
When an input text has a floating label, and is then later turned into a hidden input, the floating label is still visible.

Javascript used to convert a text input to hidden:

```
    $('input[name=imageUrl]').val(data.result.filePath).attr('type', 'hidden');
```

HTML for input text:

```
   <input type="text" required class="form-control floating-label" name="imageUrl" placeholder="Image URL">

```

**Comment by rosskevin** [comment]
Open to a PR, but this is custom behavior.  It should be just as easily to hide the parent `form-group`
