### ISSUE TITLE
Touch effect on checkboxes happening on mouseup instead of mousedown

### ISSUE THREAD

**Issue by StewartAtkins** [mdbootstrap/mdb-ui-kit#58]
With elements like nav bar items and buttons the ripple effect occurs on mousedown. This appears to be consistent with official material design examples. 

Checkboxes and radio buttons have no ripple effect on mousedown, with a brief ripple instead triggering on mouseup. This doesn't line up with expected ripple behaviour, or with the material demos available here https://www.polymer-project.org/components/paper-elements/demo.html#paper-radio-button

**Comment by FezVrasta** [comment]
There's not a way to run the effect on mouse down without javascript...

**Comment by npirotte** [comment]
Note that the google implementation is buggy : if ou mousedown on the checkbox then move the mouse out without mouse up the ripple will stay forever (until a mouseup occurs ...)

**Comment by StewartAtkins** [comment]
It seems somewhat strange to exclude a possible behaviour because it would be javascript dependent, when the component itself, as well as all the other ripple effects are also JS dependent.

**Comment by FezVrasta** [comment]
I'm trying to keep the theme less js powered. the current effect is very good I think, maybe we could add a js plugin which improves the effect when js is active...
