### ISSUE TITLE
Slider/Vertical Sliders not implemented or..?

### ISSUE THREAD

**Issue by Orbyt** [mdbootstrap/mdb-ui-kit#580]
Hey ive been trying to get the sliders to work but it seems like the feature isnt implemented? The source on the sliders page (http://fezvrasta.github.io/bootstrap-material-design/#slider) doesnt seem to work and doing a search for "svert" in the repository brings up nothing but the html for the above^. Is this feature not ready? The sliders on the example page seem to be working fine.

Im using the Meteor package btw.

**Comment by sovanna** [comment]
it works, I've pulled the repo and it works.
make sure to include http://refreshless.com/nouislider/

you have also to call for example

``` javascript
$(".shor").noUiSlider({
    start: 40,
    connect: "lower",
    range: {
        min: 0,
        max: 100
    }
});
```

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
