### ISSUE TITLE
runat server textarea

### ISSUE THREAD

**Issue by HeB-zz** [mdbootstrap/mdb-ui-kit#582]
Hi,

I use bootstrap material design in an asp.net project.
I've an issue on the textarea when I add the attribute runat="server", it doesn't display it in the form, if I delete this attribute, it works.

Have you heard about this problem ?
Thanks

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
