### ISSUE TITLE
about angular

### ISSUE THREAD

**Issue by muei** [mdbootstrap/mdb-ui-kit#583]
will it to be dependence on angular without jquery?

**Comment by dunmaksim** [comment]
@ohohco, you can try [Angular Material](http://material.angularjs.org).

**Comment by FezVrasta** [comment]
jquery is needed just for very simple tasks, most of them can be replaced by native angular directives. Someone is working on them https://github.com/FezVrasta/bootstrap-material-design/issues/366#issuecomment-108058226

**Comment by tilwinjoy** [comment]
@ohohco try http://tilwinjoy.github.io/angular-bootstrap-material/
