### ISSUE TITLE
List Groups using divs

### ISSUE THREAD

**Issue by cactushead** [mdbootstrap/mdb-ui-kit#584]
Is there a particular reason why the list groups are created using a succession of divs instead of ul and li like bootstrap does and your own navbars use?

Seems a bit strange.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
