### ISSUE TITLE
Improve icon documentation

### ISSUE THREAD

**Issue by udiedrichsen** [mdbootstrap/mdb-ui-kit#586]
Hi,

I like your package, but I have one suggestion for the icon overview here
http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

Instead of showing the name of an icon using tooltip (mouseover), please place
the name direct under the icon. Two advantages:
- User can use find to search for a icon
- Easier to copy and paste the icon name

**Comment by stachrom** [comment]
You are talking about: http://google.github.io/material-design-icons/ ?

Link has changed:  https://www.google.com/design/icons/

2015-05-10 10:37 GMT+02:00 Ulrich Diedrichsen notifications@github.com:

**Comment by jmillspaysbills** [comment]
I believe @udiedrichsen is saying that he would like to see the icons section more similar to what they do on the Font Awesome cheat sheet. http://fortawesome.github.io/Font-Awesome/cheatsheet/

**Comment by udiedrichsen** [comment]
@jmillspaysbills is right.

**Comment by paultopia** [comment]
In general, I think the documentation and provision of the icons is a bit confusing.  The readme.md says there are 490 icons; the overview page noted in the first comment for this issue says there are 700-some.  Also, why include them at all as a separate font; why not just have users serve them directly from google's versions?

**Comment by rosskevin** [comment]
#728 solves this
