### ISSUE TITLE
Problems when using uncss

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#587]
Things go haywire when uncss is used (https://github.com/addyosmani/grunt-uncss) 

Are there elements that need to be put in the ignore options for the same

This may not be a problem in this project but help appreciated anyways

**Comment by ghost** [comment]
i found these to be helpful in getting things to work

```
ignore: [
        '#added_at_runtime',
        '.created_by_jQuery'
        ".fade",
        ".fade.in",
        ".collapse",
        ".collapse.in",
        ".collapsing",
        /\.dropdown-+/,
        /\.open(>\.+)?/,
        /(\.)*ripple(-+)?/
      ]
```

i think putting this in the readme will be helpful to others planning to use uncss

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
