### ISSUE TITLE
Docs and examples should respond to mobile

### ISSUE THREAD

**Issue by zdwolfe** [mdbootstrap/mdb-ui-kit#590]
See below screenshot.

Chrome for Android latest
Samsung S6

[screenshot_2015-05-11-08-04-12](https://cloud.githubusercontent.com/assets/719730/7567920/bbccc8d0-f7b4-11e4-9359-6d4eea4c1aca.png)

**Comment by FezVrasta** [comment]
Yes I know, it's not mobile optimized

**Comment by zdwolfe** [comment]
Ok

**Comment by rosskevin** [comment]
Closed in lieu of #728
