### ISSUE TITLE
Icons not working in mobile browsers

### ISSUE THREAD

**Issue by al2six** [mdbootstrap/mdb-ui-kit#591]
I'm trying to use one of the icons on my website. Looks great in IE11 and Chrome desktop. But on my Android Chrome and iOS Safari, i just get a white rectangle instead of the icon.  Is there a work around for this?

Thanks!

**Comment by popohum** [comment]
Its works on  iOS-8.3 Safari.

**Comment by jmillspaysbills** [comment]
@al2six is the main example page working for you? The icons on this page? http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

Or is it not working in your project?
