### ISSUE TITLE
Some mistakes in home page

### ISSUE THREAD

**Issue by popohum** [mdbootstrap/mdb-ui-kit#592]
The select option of DONOTE WITH PAYPAL  do not dispaly  on Windows7 Chrome 42.0.2311.90 (64-bit)
Its font color is inherit of white,but the background-color is white too.
![20150512111425](https://cloud.githubusercontent.com/assets/6667477/7579567/60b05798-f898-11e4-8c37-97864d9da5ff.png)

**Comment by FezVrasta** [comment]
Oh thanks! I see you have the commit ready,feel free to pr

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
