### ISSUE TITLE
When using 'material-fullpalette.min.css' IE9 or less, forms, gracefully degrade

### ISSUE THREAD

**Issue by cesterline** [mdbootstrap/mdb-ui-kit#594]
As far as I'm concerned this is a great thing.  NON-modern browsers, in the case of IE9 or less, seem to ignore any css direction where forms are concerned and present ala native Bootstrap.  Whereas, when I apply 'material.min.css' forms, in ie9 or less, fail to present and/or function properly.

Regardless, as I previously stated, this is a good thing.  Those still using legacy browsers aren't accustom to seeing the modern web and thus forcing the issue would lessen their overall UX.

I read through your docs and have not found anything regarding this 'feature'.  Did I miss something?  Is this behavior intended?

Thanks for your time in advance and keep up the good work!

**Comment by FezVrasta** [comment]
No this is not intended... I've not a Windows machine to test it :(

**Comment by cesterline** [comment]
In either event, I would consider performing a diff against material.css to understand what, apparent, lack of specificity is causing material.fullpalette.css to enable the fallback to bootstrap.css.  And push those changes to material.css for the sake graceful degradation.  Pushing Material Design upon non-modern browser users would likely be seen as an inconsistent user experience.

**Comment by cesterline** [comment]
As it turns out, it looks as if material-fullpalette.css crosses one or more limits (https://support.microsoft.com/en-us/kb/262161) built into IE 9 or less.  There is, also, an undocumented but much reported, max file size (278kb).  Any of which will cause IE9 or less to dismiss the CSS doc entirely.

**Comment by GradyD** [comment]
This would require some changes to the way we currently build but if we made two css files this could be fixed. File 1 would be the material.css file we have today. File 2 would only include what material.css doesn't. So all projects would include material.css and if you wanted all color options you would include the additional CSS file. 

This would shrink the file size and prevent any issues like this from happening.

This will also help the windows machines from freezing when opening the developer console, because the files won't be as big.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
