### ISSUE TITLE
LESS: Black font color on success buttons

### ISSUE THREAD

**Issue by davidkudera** [mdbootstrap/mdb-ui-kit#597]
I'm using less version which is probably outdated. This is how success button looks like:

![vyber_001](https://cloud.githubusercontent.com/assets/1174072/7671803/8dbda3f0-fcdd-11e4-8a6f-2a52cfcd2474.png)

Thank you

**Comment by Denoder** [comment]
this is actually happening to all button for me

**Comment by FezVrasta** [comment]
known bug: #394
