### ISSUE TITLE
!important Tag Overwriting Necessary CSS

### ISSUE THREAD

**Issue by samuelbeard** [mdbootstrap/mdb-ui-kit#598]
```
.nav-tabs>li>a, .nav-tabs>li>a:hover, .nav-tabs>li>a:focus {
  background-color: transparent!important;
  border: 0!important;
  color: #fff!important;
  font-weight: 500;
```

The color: #fff!important is causing disables links in the nav to not look any different from normal links. The css for this is being overwritten: 

```
.nav-tabs>li.disabled>a, .nav-tabs>li.disabled>a:hover {
  color: rgba(255,255,255,.5);
```

**Comment by leo60228** [comment]
Maybe try changing the second one to this?

``` css
.nav-tabs>li.disabled.disabled.disabled.disabled>a, .nav-tabs>li.disabled.disabled.disabled.disabled>a:hover {
  color: rgba(255,255,255,.5) !important;
```

A little bit of a hack, but if we really need `!important`...

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
