### ISSUE TITLE
form-control background-position issue

### ISSUE THREAD

**Issue by alex-webb** [mdbootstrap/mdb-ui-kit#599]
Hi all, 

I had issues with the form-control class, specifically the background-position rule that affects the form control underline.  If I bundled the CSS:

``` c#
bundles.Add(new ScriptBundle("~/bundles/material").Include(
                        "~/Scripts/material/ripples.js",
                        "~/Scripts/material/material.js"));
```

Firefox rendered a rule centre centre, centre centre causing the line to be vertically centred instead of appear at the bottom.  Chrome didn't recognize the rule at all because some spaces where removed - causing the line to appear at the top.  IE was fine.

It should be: 

``` css
background-position: center bottom, center calc(100% - 1px);
```

I found linking to the css resources directly in markup stopped the issue, does anyone know why this could be happening?  I'd prefer to use MVC bundling if possible.  The issue only happened when running the published site on my 1 and 1 windows hosting account.

Thanks

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
