### ISSUE TITLE
Delightful details

### ISSUE THREAD

**Issue by roeku** [mdbootstrap/mdb-ui-kit#6]
Any plans to start with the [details](http://www.google.com/design/spec/animation/delightful-details.html#delightful-details-delightful-details)? Some animations like this [action button](http://codepen.io/andreasstorm/pen/DkLqA) perhaps?

**Comment by FezVrasta** [comment]
would be awesome but it would require a lot of work and very specific code... probably I'll implement them after the basic features will be ready.

**Comment by roeku** [comment]
I'm aware of the complexity but I believe the element that makes material design so appealing are those small details. Though I do get your point of view. Maybe i'll try my hand at it.

**Comment by roeku** [comment]
Made the [menu/arrow](http://codepen.io/anon/pen/xqoks) button to the best of my ability.

**Comment by FezVrasta** [comment]
Well we could use this codepen for it, http://codepen.io/albebonv/pen/gIlrw/

**Comment by roeku** [comment]
Looks good

**Comment by FezVrasta** [comment]
talking about animations, I've re-written the animation of the checkboxes and now it looks almost identical to the original one.

**Comment by roeku** [comment]
Real nice, how about adding ripples to the icons like the [icon toggles](http://www.google.com/design/spec/components/buttons.html#buttons-other-buttons)?

**Comment by FezVrasta** [comment]
at the moment I'm working on lists, by the way you can get a similar effect to what you need using a FAB button with transparent background.

**Comment by roeku** [comment]
Problem with that is, the ripple doesn't start from the center of the icons so it wouldn't be fitting. I believe the ripple like the checkbox is better suited for this.

**Comment by FezVrasta** [comment]
yes I see, I need this component for my project as well, I'll add it monday I think.

**Comment by rtcoms** [comment]
we can use marka library for those effects. check the link

http://fian.my.id/marka/

**Comment by FezVrasta** [comment]
Nice!

**Comment by connor4312** [comment]
Marka is great, I was coming here to suggest that!

**Comment by ryanmcdonough** [comment]
Also the option of using: https://github.com/alexk111/SVG-Morpheus

**Comment by FezVrasta** [comment]
What prevent you from using these libraries with this project?

**Comment by ryanmcdonough** [comment]
None, I'm currently adding it to my copy of the project, i'll send a pull request when done.

**Comment by connor4312** [comment]
While SVG-Morpheus is a neat project, I feel that Marka's transitions are much smoother and more true to the material design spec.

**Comment by ryanmcdonough** [comment]
I'll be doing two branches - one with each, see how they fare performance wise together, I'm happy with either :)

**Comment by FezVrasta** [comment]
I was asking why should you put that stuff inside this framework? Isn't enough use them as dependencies of your projects?

**Comment by FezVrasta** [comment]
Closing as I think it's better to keep this stuff into a separated library
