### ISSUE TITLE
CSS layout do not work properly

### ISSUE THREAD

**Issue by archy-rock3t-cloud** [mdbootstrap/mdb-ui-kit#600]
I've created django project and added files 'material.min.css' and 'material.min.js'. Also I've installed jquery as said in requirements and created main script with `$.material.init()`
While small styling, e.g. for button is applied, navigation bar styling definitely do not work, I mean it is not rendered like on demo page.
I've checked that everything is loaded properly.
In that time styles from bootswatch are displayed as should.
Can you please advice how your theme should be included in project.
Also how ripples could be enabled? Seems like simply adding this script to <head> do not help.
Here is my index.html file
http://pastebin.com/jS2CWLsp

**Comment by irontiga** [comment]
First include bootstrap(before the material stuff). http://getbootstrap.com/
