### ISSUE TITLE
radiobutton

### ISSUE THREAD

**Issue by HeB-zz** [mdbootstrap/mdb-ui-kit#603]
Hi,

I use your material design with asp.net form but the asp radio button doesn't works in readonly and disabled mode.

Thanks

**Comment by FezVrasta** [comment]
please provide the markup generated by ASP.net, they usually make a mess with it..

**Comment by HeB-zz** [comment]
Hey,

Here is the result when its disabled with c# code 

![sans titre](https://cloud.githubusercontent.com/assets/3049986/7809733/a79c0de6-039c-11e5-9362-2d4e9e255e58.png)

and the html 

```
<div class="radio radio-primary">
                                        <label>
                                            <span disabled="disabled"><input type="radio" disabled="disabled" checked="checked" value="ApproveSuperior" name="APPROVAL_SUPERIOR_DECISION" id="ApproveSuperior"></span>
                                            Approve
                                        </label>
                                    </div>
```

**Comment by HeB-zz** [comment]
I tryed the other web control asp : radiobuttonlist but it just doesn't works. the design doesn't change.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
