### ISSUE TITLE
using with asp.net

### ISSUE THREAD

**Issue by omarmallat** [mdbootstrap/mdb-ui-kit#605]
is there any documentation on how to use this in Visual Studio and asp.net?

**Comment by FezVrasta** [comment]
No, I'm not an expert of it, I don't know why there should be some specific walkthrough just for asp.net

**Comment by elmcherqui** [comment]
Hey omar, i'am using this this great design for my asp mvc projects with kendo ui , and it fits very very well. I can help you if you work with kendo ui too.

**Comment by B3nCr** [comment]
Just add the CSS and JS files to a bundle like any other CSS+JS

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
