### ISSUE TITLE
Add dependencies to bower.json ?

### ISSUE THREAD

**Issue by pwnjack** [mdbootstrap/mdb-ui-kit#606]
Since this package is a Bootstrap theme and requires Bootstrap to work, shouldn't it have Bootstrap as a bower.json dependency?

Im asking this because right now I'm trying to integrate this package in my workflow and when it comes to dependencies injection it's getting the wrong order. I think this is happening because of the undeclared Bootstrap dependency in bower.json, and the injection order is messed up:

```
script(src="/bower_components/jquery/dist/jquery.js")
script(src="/bower_components/bootstrap-material-design/dist/js/material.js")
script(src="/bower_components/bootstrap-material-design/dist/js/ripples.js")
script(src="/bower_components/bootstrap/dist/js/bootstrap.js")
```

Bootstrap should be right after jquery, right? (Don't mind the jade syntax)

Thanks in advance.

**Comment by jdutriaux** [comment]
:+1: I just had the same idea.

Bootstrap should be required by Bs Material Design. 
In addition, it will make us sure that the installed bootstrap version will always be compatible with Bootstrap Material Design.

**Comment by tbprojects** [comment]
This introduces a problem when we want to use 'bootstrap-sass' instead of 'bootstrap'
