### ISSUE TITLE
disable ripple effect on radiobutton 

### ISSUE THREAD

**Issue by HeB-zz** [mdbootstrap/mdb-ui-kit#608]
Hi,

I have a form in asp.net and the ripple effect appears for each post back I do on the form.
Is it possible to disable this effect just for the radiobutton load ?

Many thanks

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
