### ISSUE TITLE
floating label disappears when i write inside input

### ISSUE THREAD

**Issue by giovanniciriello** [mdbootstrap/mdb-ui-kit#609]
that's my simple code 

`<input type="text" class="form-control floating-label" placeholder="Name" id="name" />`

When I insert a character and the label/placeholder slide up, it disappears.

Help me please

**Comment by kiemthu123** [comment]
Same here. Here is my form and inputs:

```
<form class="" method="post">
				    			    
    <input name="username" type="text" class="form-control floating-label" placeholder="Username" data-hint="Enter your username here" required>
    				    
    <input name="pass" type="password" class="form-control floating-label" placeholder="Password" data-hint="Enter your passowrd here" required>
	
	<button class="btn btn-primary btn-lg btn-block">Send</button>
	
</form>
```

Removing either **data-hint** or **required** attribute does not work.

**Comment by louis-l** [comment]
Same here. I did call the **$.material.init()** but still does not work.

When I tried to copy the demo HTML from **fezvrasta.github.io/bootstrap-material-design/#input** after my form inputs, those inputs work fine but not from my form.

**Comment by FezVrasta** [comment]
On this pen everything works...  
http://codepen.io/FezVrasta/pen/MwmWdv

Are you sure the label is not covered by some other element of your page? Or your input has `overflow: hidden`

**Comment by louis-l** [comment]
The pen your provided is also having the same problem. The label disappear when inputing.

However, the label turns up again when I clear the input. But mine keeps hiding

There is no **overflow hidden** in my inputs, here is my HTML inside the body tag:

```

<div class="container" style="margin-top: 10%;">

    <div class="row">

        <div class="well col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4">

            <h1 class="header text-center">Title</h1>

            <form class="middle-form" method="post">

                <input name="iden" type="text" class="form-control floating-label" placeholder="something" required>

                <input name="pass" type="password" class="form-control floating-label" placeholder="something" required>

                <div class="togglebutton">
                    <label>
                        <span class="right-margin">something </span>
                        <input type="checkbox" checked>
                    </label>
                </div>

                <button class="btn btn-primary pull-right">something</button>

                <div class="clearfix"></div>

            </form>

        </div>

    </div>

</div>
```

**Comment by FezVrasta** [comment]
Ah sorry, that..

You may want to try the latest stable.
https://github.com/FezVrasta/bootstrap-material-design/releases/tag/0.3.0
