### ISSUE TITLE
Bad behavior with global div style

### ISSUE THREAD

**Issue by praveenpenumaka** [mdbootstrap/mdb-ui-kit#610]
Button color changing 

http://codepen.io/anon/pen/doWpML

**Comment by praveenpenumaka** [comment]
Probably because of ripple-wrapper div class is being appended in scripts/ripples.js: 63

**Comment by ShashankaNataraj** [comment]
+1! Recently ran into this issue as well!

**Comment by FezVrasta** [comment]
Ok but you should never target a so generic tag in your stylesheet...

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
