### ISSUE TITLE
Checkboxes don't style correctly in modals

### ISSUE THREAD

**Issue by cascer1** [mdbootstrap/mdb-ui-kit#613]
I have a form in a modal with a checkbox in it, the checkbox itself doesn't show.

``` html
<form>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group col-lg-4">
                <input class="form-control floating-label" id="numNummer" type="number" placeholder="Zaalnummer" data-hint="Het zaalnummer, dient uniek te zijn" required/>
                <br/>
            </div>
            <div class="form-group col-lg-4 col-lg-offset-2">
                <input class="form-control floating-label" id="numChairs" type="number" placeholder="Aantal stoelen" data-hint="Hoeveel stoelen zijn er in deze zaal?" required/>
                <br/>
            </div>
            <div class="form-group col-lg-4">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="chkImax" /> IMAX
                    </label>
                </div>
            </div>
        </div>
    </div>
</form>
```

Example:

![Example](http://i.imgur.com/fTsLvl6.png)

**Comment by B3nCr** [comment]
They don't style properly in a panel. I've not tried anywhere else yet.

**Comment by B3nCr** [comment]
It seems like the issue for me is that because the content is being added dynamically the initialisation is missing them out.

It looks like if I want to use this in a single page app I'm going to have some work to do to get it running. Is there a companion project which does this already?

**Comment by B3nCr** [comment]
If you include this library https://github.com/uzairfarooq/arrive then bootstrap-material-design will listen for new controls being added to the DOM and initialise them at runtime.

**Comment by cascer1** [comment]
I'll try that out tonight, see if it fixes the issue for me. @B3nCr

**Comment by sean-stanley** [comment]
Adding arrive.js fixed this issue for me. Thanks so much for that tip @B3nCr
