### ISSUE TITLE
How can i change the <Input></input> tag focus effect & <a></a> tag text color (other than green to match the navbar color)

### ISSUE THREAD

**Issue by corientdev** [mdbootstrap/mdb-ui-kit#614]
First of all thanks for the wonderful project.

How can i change the <Input></input> tag focus effect & <a></a> tag text color (other than green to match the navbar color)

**Comment by FezVrasta** [comment]
You can edit the less variables

**Comment by corientdev** [comment]
and how about button hover color change?

I changed the default color from green to blue but when hovering on to the button it still shows green. Any fix??

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
