### ISSUE TITLE
Sliders don't work in Android Chrome

### ISSUE THREAD

**Issue by al2six** [mdbootstrap/mdb-ui-kit#615]
When using noUIslider, the sliders load in android chrome, and you can drag them once, but then they stop responding. Clicking on the path of the slider works, but grabbing the handle does not.  You can see it here: http://fastfoodnutrition.org/materialsandbox/

**Comment by al2six** [comment]
I've tried both v6 and v7 of noUIslider. they both work perfectly w/o material design bootstrap, but don't work with it

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
