### ISSUE TITLE
<input> focus underline animation - consider alternatives?

### ISSUE THREAD

**Issue by estaub** [mdbootstrap/mdb-ui-kit#616]
Version 0.3.

This is totally a matter of taste, but given the quality of the rest of b-m-d, I thought I should note how turned off I am by the form-control underline animation.  

At least in left-to-right languages, the animation should go from left to right, not from the center outward.  I suspect the center-outward motion was a compromise for bi-di and right-to-left languages; if so, consider something else altogether, like a fade-in and/or a slide-in with an upward motion of just a couple of pixels.  The main point is that the end where typing will start should be visible first or simultaneously with the rest of the line.

Moving from input to input is a very frequent user activity, and so a slow animation is not appropriate.  It should be trimmed down to about .3s - perceived subconsciously, not waited for.

No need for a response - just close it if I'm in left field relative to everyone else.  Best of luck, and thanks for a great project.

**Comment by FezVrasta** [comment]
Yes probably it should be a bit shorter, at least

**Comment by rosskevin** [comment]
It looks like MDL center out as well.  I don't see specific guidance in the [spec](http://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-material-response), do you?  I think at best it is point of interaction, which is above my head regarding css animation techniques.

The animation on master is 0.3s, so I think this can be closed there is nothing more to do.
