### ISSUE TITLE
Should not show focus effect on disabled text inputs

### ISSUE THREAD

**Issue by xingrz** [mdbootstrap/mdb-ui-kit#617]

**Comment by gpgekko** [comment]
If I try this on the [demo page](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#forms), I can't reproduce your problem. How did you disable the text input?

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
