### ISSUE TITLE
Floating Label on Input Box Dynamically feeding value

### ISSUE THREAD

**Issue by corientdev** [mdbootstrap/mdb-ui-kit#619]
How can i feed dynamic value like by fetching from database in input box with floating label and make the label float just like we focus on text box

**Comment by rosskevin** [comment]
This is a general javascript question that is probably best answered on StackOverflow.

**Comment by corientdev** [comment]
it doesn't work with floating label. the label doesn't show up.

**Comment by rosskevin** [comment]
Please see [the contributing section](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#using-the-issue-tracker) about filing issues that we can help with, including reducing test cases to the codepen template.
