### ISSUE TITLE
Button onClick is triggered two times

### ISSUE THREAD

**Issue by jdutriaux** [mdbootstrap/mdb-ui-kit#62]
On Firefox : the onClick event of buttons is fired two times. (First one from rippleJs and second one from the navigator)

This behavior can be annoying.

**Comment by FezVrasta** [comment]
are you using the latest version of ripples.js? This problem should be already fixed.

**Comment by jdutriaux** [comment]
I'm using the version commited yesterday on this repo. (Commit 242b3eaf35dbb51f2e13fa307ae9ff7a06716997 )

**Comment by FezVrasta** [comment]
weird... may you put online a little demo with jsfiddle or codepen?

**Comment by jdutriaux** [comment]
Here is a Codepen showing the bug : http://codepen.io/anon/pen/EhIdz

It happens on Firefox at the first click on the button. Seems to be a problem with mouse Down/Up.

**Comment by FezVrasta** [comment]
can't see why there is this bug... I don't even call the click event in ripples.js...

**Comment by jdutriaux** [comment]
When I place a debugger : my callstack is showing that RippleJS is firing the event.

**Comment by icyflame** [comment]
But in the codepen example that you pointed us to, when the button is clicked once, the text `bar` is added once to the div. But I have checked this on chrome only. is the issue in firefox?

**Comment by jdutriaux** [comment]
Yes, I said that the issue is only in Firefox.

**Comment by jdutriaux** [comment]
Here is the stack trace for the click events : 

First call : 

```
<anonymous> index.html:23
n.event.dispatch() jquery-2.1.1.min.js:3
n.event.add/r.handle() jquery-2.1.1.min.js:3
ripples.init/rippleStart() ripples.js:61
ripples.init/rippleInit() ripples.js:102
ripples.init/bind/<() ripples.js:23
```

Second call :

```
<anonymous> index.html:23
n.event.dispatch() jquery-2.1.1.min.js:3
n.event.add/r.handle() jquery-2.1.1.min.js:3
```

Second call seems to be the legit one.

**Comment by FezVrasta** [comment]
I can't see where is the problem, I don't call clicks with ripples.js :s 

Any help is welcome.

**Comment by jdutriaux** [comment]
Maybe there is a conflict with mouseDown/Up events and click?

**Comment by FezVrasta** [comment]
can't see any reason of why I should not be able to trigger an even on mousedown/mouseup... I mean, this is the way javascript is thought to work.

**Comment by jdutriaux** [comment]
I agree with you, that's weird but the call stack clearly shows that the event is fired by ripple.

**Comment by FezVrasta** [comment]
This is the only event dispatched by ripples.js

https://github.com/FezVrasta/bootstrap-material-design/blob/master/scripts/ripples.js#L67

but it has nothing to do with "click" or "mousedown/up"

**Comment by jdutriaux** [comment]
The line that trigger the event is not in the file you linked : 

``` javascript
// Dirty fix for Firefox... seems like absolute elements inside <A> tags do not trigger the "click" event
if (/firefox|crios|(^(?!.*chrome).*safari)|ip(ad|hone|od)/i.test(navigator.userAgent)) {
   $el.click();
}
```

Maybe there is a version problem and the bug is already fixed as you said before.

**Comment by FezVrasta** [comment]
yes you are using the demo files, they are not updated.

**Comment by jdutriaux** [comment]
Ok, thx for the help.

**Comment by FezVrasta** [comment]
you're welcome
