### ISSUE TITLE
Dropdown only trigger once. 

### ISSUE THREAD

**Issue by Koxzi95** [mdbootstrap/mdb-ui-kit#620]
So I'm using this with Rails. I have all of the JavaScripts and CSS files linked correctly as mostly everything works fine except the dropdown menus. They only trigger once. 

I have the dropdown.js plugin but I'm not sure how to use it correctly.

When I click a link in a dropdown it does work but the tab changes to 'undefined'

**Comment by rosskevin** [comment]
Please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
