### ISSUE TITLE
Tooltip not working?

### ISSUE THREAD

**Issue by aaronfranco** [mdbootstrap/mdb-ui-kit#622]
I'm trying to get tooltips to work, but I cannot seem to do it properly...

Here is the HTML i'm using in [Codepen](http://codepen.io/anon/pen/KpXzBQ):

```
<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Tooltip on right">Right</button>
```

Am I missing something? 

Tested with:
Google Chrome: Version 43.0.2357.125 (64-bit)
Firefox 38

on 
Ubuntu 14.04

**Comment by aidanlloydtucker** [comment]
Add this to the botton of your body:

```
<script>
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip();
        $.material.init();
    });
</script>
```

**Comment by aaronfranco** [comment]
Thank you! That worked. I couldn't find that in the documentation.
