### ISSUE TITLE
Selectize - how?

### ISSUE THREAD

**Issue by slnowak** [mdbootstrap/mdb-ui-kit#623]
Sorry for stupid question, but should my 
'select' and 'select multiple' inputs be styled automatically? 
If not, then what should I do to turn it on? I'm using your project with angularjs and I want to avoid jquery or anything as much as I can. 

I thought that your library will style select inputs out of the box, just like the other types, but it doesn't.

There's selectize.js mentioned as a plugin in readme, but I have no idea how to turn it on.

Thanks,

**Comment by raulgd** [comment]
+1 on this newbie question, would be nice to have a selectize.js example, and also for the other mentioned plugins as well

**Comment by FezVrasta** [comment]
you can follow the official doc of the plugin
