### ISSUE TITLE
License GPL-compatible for WordPress Theme

### ISSUE THREAD

**Issue by braginteractive** [mdbootstrap/mdb-ui-kit#625]
I have created and submitted a WordPress theme that is getting pretty popular to the WordPress theme repo. I am on the final steps of getting it approved, but I have one problem. Your current license is not GPL-compatible. 

I was hoping you would give me permission or consider changing your license so others can enjoy your project. 

You can see the ticket here: https://themes.trac.wordpress.org/ticket/23342

Hope you will consider.

**Comment by gpgekko** [comment]
Linking all license related issues to issue #630, which discusses a license change.
