### ISSUE TITLE
Overriding some default question

### ISSUE THREAD

**Issue by Nicks182** [mdbootstrap/mdb-ui-kit#628]
Hi

I hope this is the right place to ask, apologies if not.

We are currently busy with an overhaul of our web application. It's quite complex, but we love the material style and what you've done is quite easy for us to implement as we already use bootstrap.

However, after getting the css and js files added and working I quickly found that I cannot override some stuff with css like the animated bars under input fields or the color of buttons.

I looked at the site again and found that I need to change some of the variables in the .less files and recompile. I found that can use !important, but that has some unwanted side effects.

I've not used .less before and just want to confirm that changing the variables and recompiling is the only way to change the color of something like the animated bars... or am I just being a noob and doing it wrong?

**Comment by FezVrasta** [comment]
You may even override the entire selector but I wouldn't advice it. Better compile less

You may want to integrate grunt in your workflow to atomize such things

**Comment by Nicks182** [comment]
Thank you for the reply. :)
