### ISSUE TITLE
Minified css is corrupted

### ISSUE THREAD

**Issue by gpgekko** [mdbootstrap/mdb-ui-kit#629]
The generated minified CSS is corrupted. It seems that any place where there are two selectors back to back selectors, for example `[type=something][disabled]`, the minifier messes up with quotes, resulting in things like `.togglebutton label input[type="checkbox][disabled"]+.toggle`.

**Comment by FezVrasta** [comment]
does it happen with the minified css provided by this repo or only if you compile it?

**Comment by gpgekko** [comment]
To the minified CSS in the repo (and thus also in the releases). I can't
link you to the line in the file, since its minified to one line, but a
ctrl+f for `[disabled"]` should yield results (11 to be exact).

**Comment by gpgekko** [comment]
Looks like [issue 48](https://github.com/hail2u/node-csswring/issues/48) in csswring?

**Comment by sean-stanley** [comment]
+1

I think this is why my checkboxes and toggles don't render when using the meteor package.

**Comment by tothand** [comment]
@sean-stanley 

I was thinking the same until I've figured it out that I didn't include Arrive.js so the initialization of new elements (e.g. autoform checkbox) are not done automatically.

Clearly I don't know if this causes the problem for you but worths a try.

If so, you can include Arrive.js or you can use

```
Template.your_template.rendered = function() {
    $.material.togglebutton($('selector'));
}
```

to manually init togglebutton checkboxes.
If every checkbox in the current template needs to be a toggle then you can use `"input[type=checkbox]"` as your selector.

Hope it helps you or someone (like me :) ) who finds this issue,
thinking that there is a problem with the css.

Happy coding!

**Comment by rosskevin** [comment]
Switching to cssmin with #728, likely to affect this.

**Comment by rosskevin** [comment]
cssmin is now used instead of csswring.  I'll see if anything comes up while I'm working on #738.

**Comment by rosskevin** [comment]
With cssmin now used, and csslint hitting all our deliverables, I'm going to close this since there are no linting errors.  [0.5.0 has been released, though check the release notes before jumping in](https://github.com/FezVrasta/bootstrap-material-design/releases/tag/0.5.0).
