### ISSUE TITLE
.btn class crazy big???

### ISSUE THREAD

**Issue by Kepro** [mdbootstrap/mdb-ui-kit#63]
WHY that crazy big buttons??? padding: 8px 30px; please remove this from btn... is very big and crash design :/ margin: 10px 1px; and margin too....

**Comment by FezVrasta** [comment]
this is the style of the buttons in material design paper, you may change it if you prefer a smaller padding but in this theme this will be the padding until Google decides differently.

**Comment by Kepro** [comment]
and what about change .btn to .btn-material to don't must to change your great theme?

**Comment by FezVrasta** [comment]
you may use the btn small class if you want smaller buttons
