### ISSUE TITLE
Seeking for suggestions about the license switch

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#630]
So, I think I'll move this project to some open source license.

I'd like to make it the more "open" possible to make everybody happy.
My first idea was MIT license, then I have thought about a dual MIT/GPL license.

What do you think?

**Comment by jmls** [comment]
+1 for MIT

**Comment by abaldwin99** [comment]
Adopting the MIT license would make this my library of the year.

**Comment by Calinou** [comment]
Dual MIT/GPL is pointless, because the GPL is a license that is _compatible_ with MIT (and that applies for all of its versions).

So, go with plain MIT.

**Comment by rougin** [comment]
+1 for MIT

**Comment by meetbryce** [comment]
+1 for MIT

**Comment by lukebranch** [comment]
+1 MIT, or LGPLv3

**Comment by rmhrisk** [comment]
MIT

**Comment by unsafecode** [comment]
+1 MIT

**Comment by nirkaufman** [comment]
+1 MIT

**Comment by FezVrasta** [comment]
Maybe release it as beerware... Who know lol

**Comment by Calinou** [comment]
> Maybe release it as beerware... Who know lol

Please use a commonly used and accepted license, Beerware should be avoided due to that.

**Comment by FezVrasta** [comment]
look at the license

**Comment by rougin** [comment]
:+1:

**Comment by nirkaufman** [comment]
:) awesome!!

**Comment by meetbryce** [comment]
Great news!

**Comment by lukebranch** [comment]
@FezVrasta ,

Thank you. I plan to use this in an open-source 'boilerplate' theme module for the Odoo platform. I'll email you with a link once the first version is ready so you can take a look if you like.

**Comment by MikeyBeLike** [comment]
Awesome!
