### ISSUE TITLE
Floating labels disappear on required inputs, if user deletes input

### ISSUE THREAD

**Issue by tzafrir** [mdbootstrap/mdb-ui-kit#631]
Some investigation shows that this is due to a validation check which prevents adding "empty" class when input is invalid, added at https://github.com/FezVrasta/bootstrap-material-design/commit/8a2322530dca010c2b62b68e8ca7100a016cefc9 which says this is for number inputs.

I suggest that the validity check should only be performed if input type is number.

**Comment by rosskevin** [comment]
Please try the latest and reopen if still present.
