### ISSUE TITLE
Gratipay policy change

### ISSUE THREAD

**Issue by gpgekko** [mdbootstrap/mdb-ui-kit#632]
Just a heads up. Seems a recent policy change means people can no longer tip individuals, only teams. So the Gratipay links lead to a page on which you can't actually tip any more.

**Comment by FezVrasta** [comment]
Yup I think I should create a team composed by myself but the page to do so is not working :/

**Comment by mattbk** [comment]
You should be able to apply for a team now at http://gratipay.com/new if you're still interested.

**Comment by FezVrasta** [comment]
I didn't find any way to do it :D thanks

**Comment by chadwhitacre** [comment]
All set, @FezVrasta? :-)

https://gratipay.com/md-for-bootstrap/

**Comment by FezVrasta** [comment]
yup thx
