### ISSUE TITLE
Having to Click Twice for Dropdown Select Values

### ISSUE THREAD

**Issue by mcfarlanedev** [mdbootstrap/mdb-ui-kit#633]
On mobile/desktop, it seems that you have to click/tap twice for select menus to reveal options. The first click provides the animation on the dropdown menu, the second click reveals the options in the menu.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
