### ISSUE TITLE
novalidate for forms

### ISSUE THREAD

**Issue by leqwasd** [mdbootstrap/mdb-ui-kit#634]
Hi,
I am making a form, I am using also angularJS. I want to use `required` or `ng-required="true"` attribute on input. But I dont want it to validate the form for me. I have also added `novalidate` attribute to form tag. But still, it adds `.form-control:invalid` class to label and colors it red. Question is - how do I make, that it does'nt add this class automatically, when input loses focus? I am not really sure, what adds it, is it html5, angular, jquery?

**Comment by rosskevin** [comment]
I'm guessing this is no longer an issue with 0.4.1, but if it is, please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.
