### ISSUE TITLE
Dropdown selection reseted until combobox animation finishes

### ISSUE THREAD

**Issue by emujagic-devlogic** [mdbootstrap/mdb-ui-kit#635]
I have combobox (select/option) which when clicked has animation of bottom line going from center to both ends.

However when I fast click combobox and hover over non-first item in combobox, it keeps returning selection to first element in comboboxbox. This behavior isn't exhibited when animation finishes. Only when I fast click combobox, and hover over second or third or non-first item in combobox.

Functionally even if I click on second (non selected) item while selection background being given to first item, selected item is correct, it's just visually confusing.

Is this an issue or expected behavior, and can I change speed of animation?

**Comment by rosskevin** [comment]
You may change the speed of the animation by overriding the css.   If you think you have a problem, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.
