### ISSUE TITLE
Toggles/Radios/Checkboxes don't seem to update underlying elements.

### ISSUE THREAD

**Issue by alevental** [mdbootstrap/mdb-ui-kit#638]
Perhaps I'm missing something but I can't quite figure out how to hook any data binding into the toggles, radio buttons, checkboxes, etc. They appear to not update the hidden inputs they're replacing and I can't find any event listeners or similar to hook into.

Moreover ...I also can't find by what magic the states actually change, I can't seem to find any on "change", "click" "touch" or similar events.

**Comment by alevental** [comment]
Just realized I might be duplicating #636 although strictly speaking they are speaking about consistency in the opposite direction I was mentioning.

**Comment by alevental** [comment]
I have since figured out that the `:checked` selector is updated / handled separately from the `checked` attribute on the element, and therefore it is easy to bind to the behavior of the toggle.

Thanks for your help!

**Comment by flip111** [comment]
@alevental how do you set the toggle of not through adding the html checked attribute?

edit: found it -- `document.querySelector('[type="checkbox"]').checked` for getting
