### ISSUE TITLE
Color not working

### ISSUE THREAD

**Issue by alegaballo** [mdbootstrap/mdb-ui-kit#639]
I'm trying to change color of my elements, if I just use element-material-color and for the color I only specify the name, everything is fine but if i type element-material-color-code it doesn't work, any idea?
(e.g)
class = navbar navbar-material-blue works fine
class = navbar navbar-material-blue-900 doesn't work

**Comment by gpgekko** [comment]
Did you include material-fullpalette.min.css or material.css? The second one only has the primary colours and not the shades.

**Comment by alegaballo** [comment]
I've included both material-fullpalette.css and material.min.css, is there a conflict? Or it is wrong to include material-fullpalette.css rather than material-fullpalette.min.css?

**Comment by gpgekko** [comment]
You only need to include one (either material-fullpalette or material). Minified or not shouldn't matter (just inconsistent typing by me). On the other hand, including both shouldn't lead to a conflict, so something else must be wrong... :/

**Comment by alegaballo** [comment]
Apparently they're in conflict, I solved deleting material.min.css
