### ISSUE TITLE
Dropdown Tab with transparent background

### ISSUE THREAD

**Issue by ianchanning** [mdbootstrap/mdb-ui-kit#64]
Its possible to end up with a transparent background on the tab with a dropdown.

I'm using FF 32.0.3 on Windows 8.
1. Click the dropdown tab
2. Click again to close the dropdown
3. Move the mouse out

This leaves a transparent background for the tab:

![2014-10-02 09_43_08-bootstrap material](https://cloud.githubusercontent.com/assets/233318/4488266/0efc1c16-4a0b-11e4-9753-54ec39e6a4ec.png)

**Comment by FezVrasta** [comment]
thanks for the bug report, will fix it asap

**Comment by FezVrasta** [comment]
should be fixed now
