### ISSUE TITLE
MDL

### ISSUE THREAD

**Issue by RohovDmytro** [mdbootstrap/mdb-ui-kit#641]
https://github.com/google/material-design-lite

If there will be any integration with MDL?

Maybe it makes sense to use some CSS from there? Or export some components.

What are the plans about MLD, if there is some?

**Comment by FezVrasta** [comment]
No plans right now. I'm not sure how they could work together.. This theme is for bootstrap, MDL not.

**Comment by sahilbabbar** [comment]
But we can certainly first replicate and then improve some of the features from MDL.

**Comment by ekerazha** [comment]
There are definitely some differences between bootstrap-material-design UI and MDL UI. E.g. the radio button effect is on onMouseUp in bootstrap-material-design, while there's a onMouseDown effect in MDL. There are also styling differences. Maybe bootstrap-material-design should "sync" to the MDL UI.

**Comment by rosskevin** [comment]
In my latest pull request #725 I referenced MDL quite a bit, albeit using the [spec](http://www.google.com/design/spec/material-design/introduction.html) as the authority.  I think my PR gets us closer in some ways to the methodology MDL uses i.e. my PR uses the bootstrap `.form-group` for all signaling of focus, label styles, and sizing.

In general, after my review of MDL, the bootstrap markup is a pseudo standard of it's own...and I think it's one work staying with.  Given that, I don't think there is an 'integration' to be done between these two projects.

I think `bootstrap-material-design` can by default style the bootstrap standard markup, without the need to add a bunch of classes.  As-is, MDL requires quite a bit of class annotation to make it work, and I don't think we must have that given bootstrap's standard.

With that said, there are definitely techniques to be reused.

I think this issue can be closed and we can open separate issues when  we want to take action on a specific item.
