### ISSUE TITLE
form reset/clear

### ISSUE THREAD

**Issue by cesterline** [mdbootstrap/mdb-ui-kit#642]
When using floating labels, is there a method, already in place, to reset labels to their default state?

**Comment by rafaelrenanpacheco** [comment]
#631 ?

**Comment by rosskevin** [comment]
Resolved by #725 and released as [0.4.0](https://github.com/FezVrasta/bootstrap-material-design/releases/tag/0.4.0).

Note that [any programmatic change of value using `$('#id').val('')` requires triggering change event. e.g. `$('#id').val('').trigger('change')`](http://stackoverflow.com/questions/4672505/why-does-the-jquery-change-event-not-trigger-when-i-set-the-value-of-a-select-us)
