### ISSUE TITLE
Text input Underline color

### ISSUE THREAD

**Issue by adithyaharun** [mdbootstrap/mdb-ui-kit#643]
Can I use another underline color for the text input (without editing the CSS)? When I use it on the green navbar (.navbar-success), the default underline color seems having not enough contrast.

**Comment by FezVrasta** [comment]
checkout the styling example here:
http://fezvrasta.github.io/bootstrap-material-design/#input

**Comment by francoisNova** [comment]
Hi there,

I have tried your suggestion for styling the inputs, but it seems to only respond to the "form- group **has success**" class entry for the parent div. How could the individual input's styling be changed to lets say _material-orange_?

E.g.

```
<div class="form-group">
        <input type="email" class="form-control form-control-material-orange floating-label" placeholder="eg. user@domain.com" name="email" autofocus id="inputEmail" value="${fn:escapeXml(param.email)}" >
</div>
```

**Comment by irontiga** [comment]
i'm afraid you'll have to try either has-error, has-success, has-warning, or has-info. The rest is up to you to write your own css classes...Although has warning should do fine.

**Comment by francoisNova** [comment]
Cool thanks for the recommendation @irontiga
