### ISSUE TITLE
Easier LESS control for navbar background

### ISSUE THREAD

**Issue by MikeyBeLike** [mdbootstrap/mdb-ui-kit#644]
I'm slyly new to github contribution, but i'd love to help properly if someone can point me in the right direction.

But my real issue is with the navbar background.

Currently in _navbar.less we have .navbar's background-color set to @primary, why not use the bootstrap variable @navbar-default-bg? It's easier to overwrite in case we want a different background colour navbar than our primary colour

**Comment by rosskevin** [comment]
Please see [Contributing](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md)
