### ISSUE TITLE
Styling not present with Bootstrap Social

### ISSUE THREAD

**Issue by Purus** [mdbootstrap/mdb-ui-kit#646]
When using the Bootstrap Social buttons, the colors are not shown as required. It shows a transparent color.

Effects are shown fine, but the colors and borders are missing.

https://github.com/lipis/bootstrap-social

**Comment by Purus** [comment]
This does not work for any other such library. Other such example is http://adamneumann.co/bootstrap-social-buttons/3/

Is there any way to overcome this?

**Comment by rosskevin** [comment]
Please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.
