### ISSUE TITLE
Checking a tick box in a form causes iOS to crash

### ISSUE THREAD

**Issue by WilliamWCYoung** [mdbootstrap/mdb-ui-kit#647]
Been getting this for a while, works on every other device other than iPhone?

**Comment by WilliamWCYoung** [comment]
By iOS I mean the safari app.

**Comment by rosskevin** [comment]
Please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.

**Comment by rosskevin** [comment]
Works for me both on OSX safari and IOS safari.

**Comment by WilliamWCYoung** [comment]
Which version of IOS,? It works on newer versions but fails on iPhone 4. I will make a boiled down test case when I get a moment

**Comment by rosskevin** [comment]
I'm guessing that iPhone 4 is [ios 7.1.2 at the most](http://www.everyi.com/by-capability/maximum-supported-ios-version-for-ipod-iphone-ipad.html) with [less than 5% of the current market](https://mixpanel.com/trends/#report/ios_8/from_date:-29,report_unit:day,to_date:0).   

This a market share too low for me to spend time given all the other issues, though I would welcome a fix from you!  If the OS version is different with a large market share, then we can reopen and spend more time.  

Make sense?  Again,  if it's important to you I need a fix from you.

**Comment by WilliamWCYoung** [comment]
Sounds like a fair and succinct point. If I come across the cause I'll be sure to open a pull request. Thank you for your time

**Comment by FezVrasta** [comment]
You may try with the new [input components](https://github.com/FezVrasta/bootstrap-material-design/issues/743) , I think they will work well
