### ISSUE TITLE
ng-repeat generated radio button doesn't show

### ISSUE THREAD

**Issue by kiga01** [mdbootstrap/mdb-ui-kit#648]
hello everyone, i have this bug, im trying the library, and doesn't work right, i have a couple of radio buttons dinamically generates with angular, when i try to see it, i just can see the label, but notthing else.

any help or guide so i can try to fix this?

thank u,

```
        <di v class="radio" ng-repeat="(key, structure) in structures">
            <label >
                <inpu t type="radio" value="{{key}}" ng-model="model.structure" ng-change="changeStructure(key, structure)"> {{key}}
            </labe l>
```

**Comment by BrennanMcDonald** [comment]
Make sure that the bottom of your file you are calling

``` javascript
    <script>
        $(document).ready(function() {
            $.material.init();
        });
    </script>
```

As this is required if you want to initialize material design on to dynamically generated elements.

**Comment by majorvin** [comment]
Same happens to me but I think it was design as expected.
You have to include `arrive.js` before `bootstrap-material-design.js`
