### ISSUE TITLE
Multiple clicks on buttons breaks color

### ISSUE THREAD

**Issue by ebertmi** [mdbootstrap/mdb-ui-kit#65]
See the appended image. If you click 10-20 times on a button pretty fast they get darker.

![image](https://cloud.githubusercontent.com/assets/1634468/4488691/4021394c-4a11-11e4-8b4b-bd48151580d4.png)

on Google Chrome Version 37.0.2062.124 m

**Comment by FezVrasta** [comment]
duplicate of #18
