### ISSUE TITLE
Request independent repository for ripples.js

### ISSUE THREAD

**Issue by xiaoyuze88** [mdbootstrap/mdb-ui-kit#650]
I like your job very much, Especially your Ripples.js, it's awesome!

I'd like to fork your Ripples.js and make some improve for it but you don't have an independent repository for it, could you open one?

Now I open a repository on my github [here](https://github.com/xiaoyuze88/Ripples.js-from-bootstrap-material-design). 

If you don't like it or you could kindly open the independent one for Ripples, I'll remove it from my github ASAP.

Best regard!
Xiao Yuze

**Comment by rosskevin** [comment]
In working on `v4-dev`, I've decided to integrate ripples as an es6 class and default stylesheet.  That's not to say we couldn't extract it later, but I'm not focused on that at the moment.
