### ISSUE TITLE
List group not working properly

### ISSUE THREAD

**Issue by sahilbabbar** [mdbootstrap/mdb-ui-kit#651]
Bootstrap defines the following syntax for a list group:

```
<ul class="list-group">
      <li class="list-group-item">Cras justo odio</li>
      <li class="list-group-item">Dapibus ac facilisis in</li>
      <li class="list-group-item">Morbi leo risus</li>
      <li class="list-group-item">Porta ac consectetur ac</li>
      <li class="list-group-item">Vestibulum at eros</li>
</ul>
```

But when the above definition is used using Bootstrap Material, the proper functionality is not observed.
The same thing will work when the above is used without `<ul>` tags.

Why is this happening?

**Comment by rosskevin** [comment]
[Test case](http://codepen.io/rosskevin/pen/XmGGVL)

**Comment by rosskevin** [comment]
dup of #578

**Comment by sahilbabbar** [comment]
The test case mentioned above doesn't rectify the bug. See below screenshot.
![image 1](https://cloud.githubusercontent.com/assets/6317330/13912656/82dcc36e-ef65-11e5-95ec-cf78e637ca1f.png)

Code for the same:

```
<ul class="list-group">
     <li class="list-group-item">Cras justo odio</li>
     <li class="list-group-item">Dapibus ac facilisis in</li>
     <li class="list-group-item">Morbi leo risus</li>
     <li class="list-group-item">Porta ac consectetur ac</li>
     <li class="list-group-item">Vestibulum at eros</li>
</ul>
```
