### ISSUE TITLE
Input data-hint change doesn't show

### ISSUE THREAD

**Issue by Frekimoto** [mdbootstrap/mdb-ui-kit#652]
Hi!

I want to change an input's data-hint content, when I type into it with jQuery, but the hint doesn't render.
In default the input's is empty: data-hint="".

$('#myInput').on('input', function() { $('#myInput').data('hint', 'somethingelse'); });

**Comment by FezVrasta** [comment]
You should init the input again I think

**Comment by Frekimoto** [comment]
Okay, I think it's working. Thank you!
