### ISSUE TITLE
How to let the top navbar has been suspended in

### ISSUE THREAD

**Issue by guoyoujin** [mdbootstrap/mdb-ui-kit#654]
How to let the top navbar has been suspended in

**Comment by irontiga** [comment]
These are questions are off topic. This is about a theme, not the framework. But add the class navbar-fixed-top to suspend it.

**Comment by guoyoujin** [comment]
@irontiga Ok, how can let navbar drilling in effect

**Comment by guoyoujin** [comment]
![image](https://cloud.githubusercontent.com/assets/8827550/8951464/98af8e02-3600-11e5-8157-35e09d90bd7a.png)

**Comment by guoyoujin** [comment]
@irontiga Ok, I have found, thank you
