### ISSUE TITLE
Checkbox does not work in meteor

### ISSUE THREAD

**Issue by dalwadani** [mdbootstrap/mdb-ui-kit#655]
Hi all,

I am trying to use the material template in meteor.
However, the checkbox does not show properly. I have made a small replication of the issue at http://meteorpad.com/pad/63uRdCXZuaSAGtRN2/material%20checkbox%20and%20radio

What am I missing?
Thanks

**Comment by petr24** [comment]
Hey @dalwadani,

I had the same problem, add the package "modweb:arrive" and it will take care of the init required for checkboxes and radios in meteor.
