### ISSUE TITLE
Use nemo64's Bootstrap package for a customizable version of the meteor package

### ISSUE THREAD

**Issue by cmaddalozzo** [mdbootstrap/mdb-ui-kit#656]
@dandv In the TODO section of the meteor readme, adding fined-grained control is mentioned as a feature that needs to be implemented. I assume this means fine-grained control over material, not bootstrap itself. In the meantime would it make sense to create a package that depends on [nemo64's bootstrap package](https://github.com/Nemo64/meteor-bootstrap) instead of [twbs:bootstrap](https://atmospherejs.com/twbs/bootstrap) so we at least get the benefit of fine grained control over bootstrap?

Let me know if this sounds acceptable and I can create a PR.

**Comment by artshostak** [comment]
Second this request.

**Comment by FezVrasta** [comment]
It's okay to me.

**Comment by miri-am** [comment]
+1

**Comment by olizilla** [comment]
:+1:

**Comment by miri-am** [comment]
maybe this will be easier with Meteor 1.2, which allows 

```
@import "{twbs:bootstrap}/_variables.scss";
```

**Comment by PolGuixe** [comment]
Has this been implemented?

**Comment by FezVrasta** [comment]
no

**Comment by rosskevin** [comment]
See #769.  We need someone to step up and help with meteor, as the two maintainers don't use it.
