### ISSUE TITLE
Can't get compiled zip

### ISSUE THREAD

**Issue by ElGatoSaez** [mdbootstrap/mdb-ui-kit#657]
Can't get the compiled zip i don't have bower or that stuff, where can I get that zip with css, js and fonts please help

**Comment by ferran294** [comment]
You can download the Zip from the Github repository clicking this button:
![githubissue](https://cloud.githubusercontent.com/assets/6933023/9056715/4337a358-3a95-11e5-8d70-167c16caa551.png)

You will found the compiled files in the folder _dist_

**Comment by ElGatoSaez** [comment]
Thank you very much.
