### ISSUE TITLE
Checkboxes and Radio buttons not working

### ISSUE THREAD

**Issue by Shtokes** [mdbootstrap/mdb-ui-kit#660]
I'm trying to put checkboxes and radioboxes on my page. Strange thing is, they don't show up as I navigate from page to page, but only when I refresh the page on THAT path. I am using Angular ui-router to navigate around the pages. When I transition to a new page, the checkboxes and radios don't show up at all.

```
<label class="col-lg-2 control-label">
     <input type="checkbox"> Checkbox
 </label>
```

**Comment by FezVrasta** [comment]
Add arrive.js to your project

**Comment by FezVrasta** [comment]
Add arrive.js to your project

**Comment by Shtokes** [comment]
I tried, but it doesn't fix anything and I get errors in the Chrome console

```
Uncaught TypeError: $(...).arrive is not a function$.material.init @ material.js:197(anonymous     function) @ index.html:29(anonymous function) @ index.html:30 
material.js:197 

Uncaught TypeError: $(...).arrive is not a function
```

**Comment by FezVrasta** [comment]
this one https://github.com/uzairfarooq/arrive

if it gives you this error it means that you are including it after material.js, it must be loaded before it

**Comment by Shtokes** [comment]
This actually works... cool. 

How did you figure it out? And also, why isn't arrive.js mentioned in your docs?

**Comment by FezVrasta** [comment]
Actually it's mentioned

**Comment by Eonasdan** [comment]
Where is that documented?

I see it menteioned in the [readme](https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support), but the keep word is **if**

It's not mentioned [here](http://fezvrasta.github.io/bootstrap-material-design/#checkbox) or [here](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html)

**Comment by FezVrasta** [comment]
It's enough to have it on the readme, it's the file every developer read when start work with any project

**Comment by visesh-p** [comment]
@FezVrasta Thanks for this library. Its amazing really. 
So, this issue really screwed up my day. I googled non-stop only to stumble here and find out that arrive.js was required. 
I did not see it in any of the documentation, so it would really really help others if you added it.
This is still relevant now in the latest version: 4.1.1
Thanks!
