### ISSUE TITLE
datetimepicker color change?

### ISSUE THREAD

**Issue by Nicks182** [mdbootstrap/mdb-ui-kit#662]
Hi

I hope this is the right place to ask. I do I change the default color of the DateTimePicker from the default green to match that of the color of the main theme?

Do I just create new css for it or is there some build in support to make the color scheme match that of the main setup? I just want make sure I'm not missing some build in support option before I go and edit stuff.

Regards

**Comment by StZuu** [comment]
Hi guys how can I exit your conversation 😐

Nicholas Marais <notifications@github.com>于2015年8月4日星期二写道：

**Comment by cjjuice** [comment]
I just overided the css in my project
