### ISSUE TITLE
Large css file. I believe there should be sub-versions that take up much less space.. Some sort of customization..

### ISSUE THREAD

**Issue by nekkon** [mdbootstrap/mdb-ui-kit#663]
200 KB for a css file that also needs bootstrap and jquery is way too much..

**Comment by FezVrasta** [comment]
Yup it's a known issue... I may make the CSS much more lightweight if I wouldn't have to override every single class with very long and specific selectors... But this is bootstrap, and this theme changes everything about it and probably have never to do with Bootstrap.

A separated CSS framework not based on Bootstrap would work much better.

**Comment by nekkon** [comment]
From what I've noticed there are selectors that can be grouped in:
1. material-colors
2. material-icons
3. selectize

The css of the above could be in separate css files.. They take a lot of space and are not used in every project..

**Comment by rosskevin** [comment]
The option to use the less/sass files directly is possible too.
