### ISSUE TITLE
Disable Ripples?

### ISSUE THREAD

**Issue by nekkon** [mdbootstrap/mdb-ui-kit#664]
Is there a way to disable Ripples on an element? (currently it runs on all my a:links)

**Comment by sekarasiewicz** [comment]
add class .withoutripple to anchor tag

**Comment by sekarasiewicz** [comment]
add class .withoutripple to anchor tag

**Comment by doug-gv** [comment]
I'm writing this in case some poor souls happen upon this problem.

There are two methods I'll describe here, assume you want to disable ripples on links inside your `.site-header`

1. the javascript way:
`$('.site-header a').off().data('plugin_ripples', null);`
above call should be made after material-kit.js
2. the css way
`.site-header .ripple-container {display: none;}`

**Comment by ricardofreeman** [comment]
3. another javascript way
When you initialize bootstrapMaterialDesign you pass an object with ripples set to false:
```$('body').bootstrapMaterialDesign({ ripples: false });```

**Comment by chase439** [comment]
@doug-gv 
`$('.site-header a').off().data('plugin_ripples', null); ` doesn't work for me but the css works perfectly!

I also tried targeting it different ways.
