### ISSUE TITLE
Tips on using only the input section styles?

### ISSUE THREAD

**Issue by diosney** [mdbootstrap/mdb-ui-kit#665]
Hi,

I'm facing some issues while integrating only some of the styles defined here, namely the inputs on an existing theme with custom bootstrap styling applied.

In a less file I'm importing the input less file like this and the required variables and mixins for it to work properly:

``` less
@import '@{bower-path}/bootstrap-material-design/less/_colors.less';
@import '@{bower-path}/bootstrap-material-design/less/_mixins.less';
@import '@{bower-path}/bootstrap-material-design/less/_inputs.less';
```

and in a js file I'm initializing the inputs:

``` js
$.material.input();
```

but it doesn't display correctly, fi: it doesn't display the colored border-bottom on focus.

Any ideas to make this work properly?

Thanks in advance.

**Comment by FezVrasta** [comment]
are you using autoprefixer?

**Comment by diosney** [comment]
@FezVrasta No sorry, what is that?

pd. Thanks for your very quick answer.

**Comment by diosney** [comment]
@FezVrasta I just included directly the less files in my own theme files, I didn't used grunt-autoprefixer for building the css files. I hope this answer your question.

**Comment by FezVrasta** [comment]
You should use autoprefixer to add the correct vendor specific prefixes, otherwise it could cause the problem you are reporting

**Comment by diosney** [comment]
@FezVrasta OK, I will try to customize the less file by the inline addition of the required vendor mixins, since using grunt-autoprefixer doesn't integrate with my current workflow (I would prefer to only include the less file and use vendor mixins for the job).

Once I test that I will let you know if it worked.

Thanks for your help.

**Comment by diosney** [comment]
@FezVrasta :smile: I confirmed that the issue is related to the vendor prefixes.

Thanks.
