### ISSUE TITLE
navbar-material-white has no effect

### ISSUE THREAD

**Issue by sean-stanley** [mdbootstrap/mdb-ui-kit#666]
Hi,

I was trying out the color scheme classes on a design and found that `.navbar-material-white`  had no effect on my navbar's colour.

Are these supposed to be included without material-fullpalette.css. ?

**Comment by mjt60** [comment]
I have also experienced this. Would also like to know the answer.

**Comment by irontiga** [comment]
I believe that navbar-white is the fix. I think black and white don't need the -material part.

**Comment by rosskevin** [comment]
Please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.

**Comment by rosskevin** [comment]
Color variations have been removed in the upcoming 0.5.0.  It will support customization via variables.
