### ISSUE TITLE
toggle button not working 

### ISSUE THREAD

**Issue by cookie-ag** [mdbootstrap/mdb-ui-kit#667]
index.jade

```
                div.row
                  div.form-group
                    div.togglebutton
                      input#check.form-control(type='checkbox',checked)
```

Javascript : 

```
$(document).ready(function(){
  $.material.init();
  });

```

Added all deps, console also has no error!

**Comment by AlexECP** [comment]
Also not working for me

**Comment by FezVrasta** [comment]
yes you both are missing part of the markup

```
<div class="togglebutton">
  <label>
    Bluetooth
    <input type="checkbox">
  </label>
</div>
```

**Comment by AlexECP** [comment]
Nope, thats the markup I have.

**Comment by FezVrasta** [comment]
ok then you have a different problem then @serganus

**Comment by Streemo** [comment]
Actually, I'm also having this problem -- but only on cordova ios (meteor). it works fine on android.... strange....

**Comment by AlexECP** [comment]
I was able to resolve it by calling $.material.init(); on document ready
