### ISSUE TITLE
New idea: a very cool Responsive Modal for Material Design with source code

### ISSUE THREAD

**Issue by obezzad** [mdbootstrap/mdb-ui-kit#669]
Hello, Firstly thank you for the cool Theme and i'm waiting for your updates. i have a very cool modal design with his source code, 
1. please add a FAB list (when you click on a Floating Action Button a list of FAB will be displayed like the dropdown in normal bootstrap but will be more useful and interactive).
2. HERE THE EXAMPLE + SOURCE CODE : http://codepen.io/ettrics/pen/Jdjdzp

**Comment by irontiga** [comment]
Not so easy, it's not built on boostrap!

**Comment by obezzad** [comment]
i know, but it's not a bad thing to add custom CSS and do a simple docs about the Special API, so the Material Design for Bootstrap will not be just a simple theme like others. it will be like plugin built on Bootstrap and Bootstrap users know the base of this plugin and they need to learn just the additional features if they want , if not it's just optional to learn them

**Comment by rosskevin** [comment]
We are very much open to enhancements that meet the google design specification, please feel free to take a shot and submit a pull request.
