### ISSUE TITLE
Navbar & mobile devices

### ISSUE THREAD

**Issue by vbauer** [mdbootstrap/mdb-ui-kit#67]
Maybe, it will be useful to add extra media queries for navbar to make it a little bit smaller in some cases.

Google did it on the site with official guidelines (just try to resize window): http://www.google.com/design/spec/style/typography.html

It will help to use bootstrap-material-design project on mobile devices.

**Comment by xvik** [comment]
+1

**Comment by mahnunchik** [comment]
+1
