### ISSUE TITLE
Chebox: transform: translateZ(0) causes tooltip positioning issues

### ISSUE THREAD

**Issue by davideberlein** [mdbootstrap/mdb-ui-kit#670]
Applying transform: translateZ(0) to the .checkbox class causes any modal element like the tooltip in the .checkbox container to have an invalid z-index on Chrome Version 44.0.2403.130 m. (See screenshots).
This is very unfortunante since the "checkbox" class must be set to the container of the actual input and therein using tooltips is rather common. (at least in my case)
Additionally according to this statement: http://stackoverflow.com/questions/10814178/css-performance-relative-to-translatez0
using transaltez(0) to force 3d rendering isn't really helpful in general.

I would suggest to either set the translateZ(0) to ".checkbox .checkbox-material" or just removing it alltogether.

What do you think?

Z-Index Problem:
![image](https://cloud.githubusercontent.com/assets/3438183/9324799/d8b73026-458d-11e5-88fa-2a2a0d2326cf.png)
Z-Index Problem resolved:
![image](https://cloud.githubusercontent.com/assets/3438183/9324801/dde4d468-458d-11e5-8f13-580823b3f472.png)

**Comment by FezVrasta** [comment]
Sorry I don't see any difference... I'm aware about the implications of 3d accelerated rendering but never had problems with it in this case.

**Comment by davideberlein** [comment]
On the top picture the tooltip is displayed behind the label text and behind the next panel with the title "AS enhancment features" (it is cut off at the bottom). 

On the bottom picture this problem is resolved.

**Comment by rosskevin** [comment]
This line was removed and should be fixed in 0.4.1
