### ISSUE TITLE
Integration With AngularJS Does not Work

### ISSUE THREAD

**Issue by siddmegadeth** [mdbootstrap/mdb-ui-kit#673]
Currently integrating bootstrap-material-design with Angularjs. However there are no erros but most of the element does not work using angularjs 1.3 +

Please suggest

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1">
<title>Material Design</title>
<link rel="stylesheet" href="plugins/bootstrap-3.3.4/css/bootstrap.min.css" />
<link rel="stylesheet" href="plugins/bootstrap-material-design-master/dist/css/material-fullpalette.min.css" /> 
<link rel="stylesheet" href="plugins/bootstrap-material-design-master/dist/css/ripples.min.css" /> 
<link rel="stylesheet" href="plugins/bootstrap-material-design-master/dist/css/roboto.min.css" /> 

<link rel="stylesheet" href="plugins/font-awesome-4.3.0/css/font-awesome.min.css" /> 
<link rel="stylesheet" href="style/init.css" />
</head>
<body ng-app="myApp" ng-controller="globalCtrl">

<div ng-view></div>

</body>

<script src="plugins/angular/angular.min.js" ></script>

<script src="plugins/angular/angular-animate.min.js" ></script>

<script src="plugins/angular/angular-route.min.js" ></script>

<script src="plugins/angular/angular-aria.js" ></script>

<script src="plugins/jquery-1.11.3.min.js" ></script>

<script src="init.js" ></script>

<script src="controllers/landingCtrl.js"></script>

<script src="controllers/globalCtrl.js"></script>

</html>

**Comment by RohovDmytro** [comment]
Can I suggest you https://material.angularjs.org/latest/#/ ?

**Comment by rosskevin** [comment]
Please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.
