### ISSUE TITLE
Support of bootstrap 4

### ISSUE THREAD

**Issue by RohovDmytro** [mdbootstrap/mdb-ui-kit#674]
Any plans?

https://github.com/twbs/bootstrap/milestones

**Comment by obezzad** [comment]
Bootstrap 4 is a major update for Bootstrap 3 and support the Bootstrap 3 elements, so FerVrasta can add a Beta version for BS4 users that just will be compatible with the built-in new card element and some features that make the Material Design theme more powerful for developers and beautiful for visitors

**Comment by FezVrasta** [comment]
Right now I've not time, I think I'll start from scratch with bs4 to keep stuff clean

**Comment by RohovDmytro** [comment]
@FezVrasta can you please provide ane ETA according to your current plans? Thanks in advance.

**Comment by Ricky-G** [comment]
yes please BS4 support will be awesome!!

**Comment by FezVrasta** [comment]
Ok just took a look and it shouldn't be that hard... I'd wait for the official release first, so I don't have to re-do some work if they change something during the development.

**Comment by RohovDmytro** [comment]
Sounds promising! Thanks, @FezVrasta
