### ISSUE TITLE
Bundled RobotoDraft font rendering glitch

### ISSUE THREAD

**Issue by 8aginski** [mdbootstrap/mdb-ui-kit#680]
RobotoDraft font bundled with bootstrap-material-design doesn't render correctly.

It looks like this (on FF):
![orig](https://cloud.githubusercontent.com/assets/1757440/9427920/7bc12528-4995-11e5-88cd-0f7bdaf70269.png)

It should look like this:
![correct](https://cloud.githubusercontent.com/assets/1757440/9427922/827911aa-4995-11e5-9338-98cd1da30409.png)

(For the second screenshot I replaced `<link href="dist/css/roboto.min.css" rel="stylesheet">` with `<link href="http://fonts.googleapis.com/css?family=RobotoDraft:400,500,700,400italic&subset=latin,latin-ext" rel="stylesheet" type="text/css">` in the relevant HTML file.)

**Comment by rosskevin** [comment]
Can you reproduce this with a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case?

**Comment by rosskevin** [comment]
I don't see what is incorrect in the screenshots you have posted.  If you could give more information and point to the error, please reopen.
