### ISSUE TITLE
placeholders, hits etc. and angular-translate

### ISSUE THREAD

**Issue by valera33** [mdbootstrap/mdb-ui-kit#686]
Hello,

I am trying to build a multilingual angular application using your theme and I have a problem with angular-translate support, obviously translate is changing texts dynamically when user is switching the language but all placeholders, hints etc. in text inputs stay the same, any ideas how to fix the problem?

angular-translate uses its own directives for translation, so my placeholder looks like this: placeholder="{{'USER_REGISTRATION.email_input_label'| translate}}

..and I already use arrive.js

**Comment by FezVrasta** [comment]
the current script doesn't support update of the placeholders :(

**Comment by valera33** [comment]
btw, I found a workaround to my problem,

I do not use placeholder attribute in input element, instead I put div with class="floating-label"  and span with class="material-input" manually after input element

everything is working now..

**Comment by FezVrasta** [comment]
yes on my company we did the same with ember, actually it's much better to not rely on the automatic scripts when you use such frameworks.

**Comment by cfrezier** [comment]
Hi,
I do have the same problem, and i'm looking at your workaround, but actually i'm not able to have a working solution. Can you provide an example ?

**Comment by valera33** [comment]
This is how I did it on my registration form:

```

<div class="form-group form-control-wrapper" ng-class="{'has-error' : signupForm.email.$invalid && !signupForm.email.$pristine, 'has-success': signupForm.email.$valid}">
    <input name="email" type="email" class="form-control empty" autocomplete="off" ng-model="registration.email" ng-minlength="3" ng-maxlength="30" ng-trim required>
    <div class="floating-label control-label">{{'USER_REGISTRATION.email_input_label'| translate}}</div>
    <span class="material-input"></span>
    <div class="hint">{{'USER_REGISTRATION.hint_email'|translate}}</div>
</div>

```

**Comment by rosskevin** [comment]
In 0.4 and above, the preferred method is the `label` element, so there shouldn't be any problem translating content.  Please reopen if there is.
