### ISSUE TITLE
Material with arrive - require.js

### ISSUE THREAD

**Issue by matewilk** [mdbootstrap/mdb-ui-kit#688]
Hello,

It seems very similar to the issue [here](https://github.com/FezVrasta/bootstrap-material-design/issues/325)
But as it's closed already, I've decided to create a new one and the solution for the above is not the one I'm looking for.

So please kindly take a look :smile: 

I'm requiring arrive **before** material, and 1 out of 10 times I'm getting the same error:

``` javascript
Uncaught TypeError: $(...).arrive is not a function material.js:197
```

This is how my main.js file looks like, the arrive is attached before material

``` javascript
/*global require*/
'use strict';

require.config({
    shim: {
        bootstrap: {
            deps: ["jquery"]
        },
        ripples : {
            deps: ["jquery", 'arrive']
        },
        material: {
            deps: ["bootstrap", 'ripples']
        },
        velocity: {
            deps: ["jquery"]
        }
    },
    paths: {
        scripts: '../scripts',
        globals: './globals',
        jquery: '../bower_components/jquery/dist/jquery',
        backbone: '../bower_components/backbone/backbone',
        underscore: '../bower_components/lodash/dist/lodash',
        bootstrap: '../bower_components/bootstrap/dist/js/bootstrap',
        arrive: '../bower_components/arrive/src/arrive',
        material: '../bower_components/bootstrap-material-design/dist/js/material',
        ripples: '../bower_components/bootstrap-material-design/dist/js/ripples',
        handlebars: '../bower_components/handlebars/handlebars',
        templates: '../scripts/templates',
        "jquery-cookie": '../bower_components/jquery-cookie/jquery.cookie',
        epubjs: "../bower_components/epubjs/build/epub",
        jszip: "../bower_components/jszip/dist/jszip.min",
        dropzone: "../bower_components/dropzone/dist/dropzone-amd-module",
        velocity: "../bower_components/velocity/velocity",
        react: "../bower_components/react/react",
        "backbone-react": "../bower_components/backbone-react-component/lib/component"
    }
});

require([
    'backbone',
    'app',
    'globals/session',
    'material',
    'velocity'
], function (Backbone, Application, SessionModel) {

    $(document).ready( function() {
        $.material.init();
    });

    window.App = {
        session: SessionModel
    };
    new Application();

    Backbone.history.start({
        pushState: true,
        hasChange: false
    });
});
```

I'm also including init() function as you can see just after document is ready.

And what is most annoying, it doesn't work for the first time I launch the app, no matter if it's a localhost, or vps.

Any suggestions much appreciated 

Thanks

**Comment by FezVrasta** [comment]
you should set arrive as dep of material probably

**Comment by matewilk** [comment]
unfortunately, although my app is not stopping on arrive error, now it occurs every time I refresh the page, so in some sense it makes it worst.

**Comment by FezVrasta** [comment]
actually ripples.js doesn't need arrive.js, maybe you could try to remove it from ripples and put it just on material

**Comment by matewilk** [comment]
yes, this is exactly how I did it:

``` javascript
shim: {
        bootstrap: {
            deps: ["jquery"],
            exports: 'jquery'
        },
        ripples : {
            deps: ["jquery"]
        },
        material: {
            deps: ["bootstrap", 'ripples', 'arrive']
        },
        velocity: {
            deps: ["jquery"]
        }
    }
```

But it behaves as I've mentioned in the previous comment.

**Comment by matewilk** [comment]
I think the problem is that material.js still assumes that arrive.js has jQuery dependency (but it doesn't anymore), in line 197:

``` javascript
$(document).arrive ....
```

It should simply be document.arrive instead

I have solved my problem by adding another shim (to the ones presented in the first post):

``` javascript
arrive: {
            deps: ['jquery']
        },
```

But I think that now it's a bug in material.js

Thanks

**Comment by matewilk** [comment]
I've created this [pull request](https://github.com/FezVrasta/bootstrap-material-design/pull/689) if you don't mind :smiley:

**Comment by rosskevin** [comment]
Please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.
