### ISSUE TITLE
btn-group class styling and behavior

### ISSUE THREAD

**Issue by nlourenco** [mdbootstrap/mdb-ui-kit#690]
The bootstrap-material-design "btn-group" class differs wildly from the styling and behavior found on the official bootstrap code base. Why is that? 

Bootstrap, see http://getbootstrap.com/components/#btn-groups-single 

```
<div class="btn-group" role="group" aria-label="...">
  <button type="button" class="btn btn-default">Left</button>
  <button type="button" class="btn btn-default">Middle</button>
  <button type="button" class="btn btn-default">Right</button>
</div>
```

**Comment by rosskevin** [comment]
Please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case and describe the behavior you are looking for.
