### ISSUE TITLE
onblur event doesn't work with Material Design theme in Firefox

### ISSUE THREAD

**Issue by mot4** [mdbootstrap/mdb-ui-kit#692]
I try to handle a onblur event on a input type number with Material Design. It works fine in Chrome and IE but not in Firefox.

Example and temporal solution here: https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/553

**Comment by rosskevin** [comment]
Please submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.

**Comment by rosskevin** [comment]
onblur seems to work for me, but I found other label issues.  I'm tracking in #731
