### ISSUE TITLE
Radio input must either not wrap the option name or wrap in div not span

### ISSUE THREAD

**Issue by tachang** [mdbootstrap/mdb-ui-kit#693]
Just a comment on the radio css:

```
            <div className="radio radio-primary" key={option.id}>
              <label>
                <input type="radio"
                       name="example"}
                       value={option.id}  />
                <span className="circle"></span>
                <span className="check"></span>
                <div>{option.name}</div>
              </label>
```

I noticed that there is absolute positioning applied to all span elements. Ran into it when wrapping my option.name in a span tag. Switched to div and it worked. Should this be the default?

**Comment by FezVrasta** [comment]
I'll try to address all these problems with the new version based on BS4

**Comment by rosskevin** [comment]
@tachang can you provide a  [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case so I can see if I can make a fix for bs3?
