### ISSUE TITLE
input focus not shown on radio/checkbox when using keyboard

### ISSUE THREAD

**Issue by salvadoresc** [mdbootstrap/mdb-ui-kit#695]
when u fill a form, and use tab to jump from the inputs, there is no focus state for the button so u dont know if the button is already selected.

**Comment by salvadoresc** [comment]
by the way u find same problem, with checkbox and radiobuttons

**Comment by rosskevin** [comment]
Is there any reference in the specification? https://www.google.com/design/spec/material-design/introduction.html
