### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by dadmor** [mdbootstrap/mdb-ui-kit#696]
I install theme from dist and my console sed:

GET http://wpbca.com/less/_icons-material-design.less 404 (Not Found) _icons-material-design.less:1
GET http://wpbca.com/less/_buttons.less 404 (Not Found) _buttons.less:1
GET http://wpbca.com/less/_checkboxes.less 404 (Not Found) _checkboxes.less:1
GET http://wpbca.com/less/_togglebutton.less 404 (Not Found) _togglebutton.less:1
GET http://wpbca.com/less/_radios.less 404 (Not Found) _radios.less:1
GET http://wpbca.com/less/_inputs.less 404 (Not Found) _inputs.less:1
GET http://wpbca.com/less/_navbar.less 404 (Not Found) _navbar.less:1
GET http://wpbca.com/less/_lists.less 404 (Not Found) _lists.less:1
GET http://wpbca.com/less/_alerts.less 404 (Not Found) _alerts.less:1
GET http://wpbca.com/less/_progress.less 404 (Not Found) _progress.less:1
GET http://wpbca.com/less/_tabs.less 404 (Not Found) _tabs.less:1
GET http://wpbca.com/less/_popups.less 404 (Not Found) _popups.less:1
GET http://wpbca.com/less/_icons.less 404 (Not Found) _icons.less:1
GET http://wpbca.com/less/_cards.less 404 (Not Found) _cards.less:1
GET http://wpbca.com/less/_dialogs.less 404 (Not Found) _dialogs.less:1
GET http://wpbca.com/less/_labels.less 404 (Not Found) _labels.less:1
GET http://wpbca.com/less/_dividers.less 404 (Not Found) _dividers.less:1
GET http://wpbca.com/less/_panels.less 404 (Not Found) _panels.less:1
GET http://wpbca.com/less/_plugin-snackbarjs.less 404 (Not Found) _plugin-snackbarjs.less:1
GET http://wpbca.com/less/_plugin-nouislider.less 404 (Not Found) _plugin-nouislider.less:1
GET http://wpbca.com/less/_plugin-selectize.less 404 (Not Found) _plugin-selectize.less:1
GET http://wpbca.com/less/_plugin-dropdownjs.less 404 (Not Found) _plugin-dropdownjs.less:1
GET http://wpbca.com/less/_welljumbo.less 404 (Not Found) _welljumbo.less:1
GET http://wpbca.com/less/_shadows.less 404 (Not Found) _shadows.less:1
GET http://wpbca.com/less/material.less 404 (Not Found) material.less:1
GET http://wpbca.com/less/_mixins.less 404 (Not Found)

**Comment by MarshallOfSound** [comment]
Sounds like you installed the non built version.  Make sure you get the files from the CDN sources or from the dist folder in master https://github.com/FezVrasta/bootstrap-material-design/tree/master/dist
