### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by roeku** [mdbootstrap/mdb-ui-kit#7]
I believe icon-material-gamepad and icon-material-games are the same icon and icon-material-games is double in the [demo.html](http://fezvrasta.github.io/bootstrap-material-design/).

Also icon-material-hangout2, icon-material-hangout don't seem to have a difference either.

**Comment by FezVrasta** [comment]
the gamepad and games are just two aliases for the same icon. the hangouts icons are actually the same , them are just extracted from the android source and I've not deleted any icon.
