### ISSUE TITLE
Add a way to prevent adding the ripple effect to elements we don't want to be "rippled"

### ISSUE THREAD

**Issue by pmarti** [mdbootstrap/mdb-ui-kit#70]
In some situations we might not want to have ripple added to an element, for now I've done this

https://gist.github.com/pmarti/4b693a0d40b0852e6353

Would you consider something like this?

**Comment by FezVrasta** [comment]
seems a good idea, feel free to send a PR

**Comment by Sofianio** [comment]
what about the other way around?
adding ripple effect to an element
