### ISSUE TITLE
How to start with Bootstrap Material Design

### ISSUE THREAD

**Issue by Zubrik** [mdbootstrap/mdb-ui-kit#701]
Hi,

I'm new to Bootstrap and I want to use it with Material Design. After reading through the REAMDE file, I'm not sure how to structure my files.

I've installed both bootstrap versions through bower:
- bower install bootstrap
- bower install bootstrap-material-design

Now, my main doubts are: where should I make my changes? How do I use the two bootstraps together? How should I structure my project? Which gruntfile should I use (the bootstrap one or bootstrap-material-design one)? How can I make changes to the less files?

Any indication about how to get started will be welcome.

Thanks!

**Comment by FezVrasta** [comment]
there's a dist/test.html to show you how
