### ISSUE TITLE
Do we have RTL support?

### ISSUE THREAD

**Issue by prashantidealittechno** [mdbootstrap/mdb-ui-kit#702]
This is very nice and healthy setup for bootstrap-material-design can you conform me that this theme have rtl support?

**Comment by FezVrasta** [comment]
I've never tried with RTL sorry :(

**Comment by prashantidealittechno** [comment]
OK no issue, can we paln for that?

**Comment by FezVrasta** [comment]
Actually, if Bootstrap supports it, then even my theme should. But I'm not 100% sure, first someone should test it.
