### ISSUE TITLE
compiler error in less 

### ISSUE THREAD

**Issue by MeLeGe** [mdbootstrap/mdb-ui-kit#705]
when i compile the material.less file with Simpless compiler its giver me error !!

**Comment by artem-vladimirov** [comment]
Confirm
ParseError: missing opening `{` in /bower_components/bootstrap-material-design/less/_mixins.less on line 146, column 1:
145 @all-variations: ~"-default, -primary, -info, -success, -warning, -danger";
146 {

**Comment by MeLeGe** [comment]
when i remove this line , its still give me same error !

**Comment by artem-vladimirov** [comment]
@MeLeGe try to download the previous version and compile from it (for me it's works) or just use compiled css files.

**Comment by FezVrasta** [comment]
you should use the stable version FYI

**Comment by jokimies** [comment]
Getting the same error, with     "bootstrap-material-design": "~0.3.0" and node-less lessc 1.4.2

**Comment by jokimies** [comment]
...and lessc 2.5.3 compiles just fine.

**Comment by FezVrasta** [comment]
Then you was using an old version

**Comment by rosskevin** [comment]
I've updated `grunt-contrib-less` recently to a newer version, and all is well.
