### ISSUE TITLE
I should install "bootstrap3" or  not?

### ISSUE THREAD

**Issue by thearabbit** [mdbootstrap/mdb-ui-kit#707]
I try to use this on `Meteor`.
Should I install `bootstrap 3` or not?

**Comment by micaelomota** [comment]
I want know too

**Comment by 92hackers** [comment]
This Bootstrap theme is an easy way to use the new Material Design guidelines by Google in your Bootstrap 3 based application. Just include the theme, after the Bootstrap CSS and include the JavaScript at the end of your document (just before the </body> tag), and everything will be converted to Material Design (Paper) style.

yes,  you  should install  bootstrap 3  firstly.

**Comment by thearabbit** [comment]
Thanks for your reply.

**Comment by micaelomota** [comment]
Thanks :D
