### ISSUE TITLE
btn-group-vertical and Floating Action Button and input in IE9

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#708]
Hi

I just started to investigating on your project and i must say I like it a lot. Good job.

But. From the firs time i looked an the examples i found some bugs:

1) btn-group-vertical 

on

http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html

when you click other button then first you can see that clicked button and all below it are moved slightly down.

2) Floating Action Button

on

http://fezvrasta.github.io/bootstrap-material-design/#floating-action-button

Mini versions have problems with icon position.

3)  Input in IE9

They loose all bottom border So they disappear totally and you don't know where to click to make them focused and start typing. But disabled dropdown, in other browsers then IE9, have that animation that suggest that you can type something in it.

I sow those errors in latest Google Chrome and latest Firefox, IE11 with simulation to display content in IE9.

**Comment by rosskevin** [comment]
Hello @pkgenerator, please try the latest version and see if you can reproduce you errors.  If so, please close this issue and file individual issues for each one of these items separately so we can track it.  If possible, please consider submitting a [CodePen test case](http://codepen.io/rosskevin/pen/VvRgrN) for each, it will be a great help.

**Comment by rosskevin** [comment]
> NOTE: In the interest of getting our issues list healthy, I am performing issue triage/cleanup and expiring dormant issues.  I have not necessarily reviewed this issue.
> 
> If you still have an issue, please reopen and submit a [CodePen](http://codepen.io/rosskevin/pen/VvRgrN) test case.  For more information, see the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).
