### ISSUE TITLE
Tabs not implemented

### ISSUE THREAD

**Issue by haffo** [mdbootstrap/mdb-ui-kit#710]
Any estimate about the tabs implementation ?
 It's been a while now.  Great resource BTW. 

Harold

**Comment by FezVrasta** [comment]
I think I'll wait for Bootstrap 4 to see how to proceed. Right now it's too late to work on BS3 and it's not quite the time to work on BS4. So just wait :)

I want to take a more minimal approach with the BS4 implementation.

**Comment by haffo** [comment]
OK.
Thanks

**Comment by nmocruz** [comment]
Bootstrap 4 is in a alpha, and with this speed the beta will take some time.
I think is to much time waiting for a so important control.
