### ISSUE TITLE
Inputs approach with placeholders using label

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#715]
Relates to #674

I'd like to suggest some changes in approach to inputs.  Currently, bootstrap recommends and many other plugins/tools/ecosystem generates code such as:

``` html
<div class="form-group">
    <label for="exampleInputEmail">Email address</label>
    <input class="form-control" id="exampleInputEmail" type="text"  autocomplete="off">
    <p class="help-block">This is a hint</p>
</div>
```

It seems that the `floating-label` sample is written such as 

``` html
<input type="text" class="form-control floating-label" placeholder="floating label">
```

This means that it is using a `placeholder` as a `label`, and these are actually two different things (definitely different markup).

I'd suggest the following for bs4 (and perhaps I can send a backwards compatible PR for some of this on 3):
1.  Use labels for floating-label functionality/content
2.  Use the javascript to allow user to set option `label: floating | default` which will alter the approach globally
3.  Use the given `<label>` instead of generating a `<div class=floating-label>`
4.  Allow a `label.not-floating` to designate a normal label if option `label: floating` is set.

In general, I'd like to see full support for the standard markup given that the ecosystem is generating code like this.  e.g. while `data-hint` might be convenient, it should generate a bs standard `help-block` instead of new markup proprietary to this project, that way the styles can be use universally for standard bs markup and the convenience markup.

Thoughts? Discussion?

**Comment by FezVrasta** [comment]
I agree with every single line you written.

**Comment by rosskevin** [comment]
Could I be so bold as to see if you would you be open to a coffeescript conversion? :)

**Comment by FezVrasta** [comment]
No way :)

Once BS4 will be released as stable I'll start a new version of this project with little or 0 JavaScript, and if I'll have to use some JS it will be probably ES6 compliant.

I don't see reasons to waste time converting stuff when in few weeks this version will be deprecated or quasi.

**Comment by rosskevin** [comment]
:+1:  I agree that the less script the better.  Though I do love me some coffee(script) if I need to write anything.

If I make bs3 changes to js/less for standard markup (not backwards compatible), are you interested in that as a PR?

**Comment by FezVrasta** [comment]
sure

**Comment by rosskevin** [comment]
@FezVrasta - Is floating label the standard?  And static labels the exception?

And, should static labels be the same size/color as floating labels with focus?

**Comment by FezVrasta** [comment]
Yes

**Comment by rosskevin** [comment]
So, do you mind if I take the approach of:
- floating labels mean zero markup (no `.floating-label`)
- static labels require `.not-floating` or `.static-label`

?

**Comment by FezVrasta** [comment]
Yes it seems good

**Comment by rosskevin** [comment]
I've submitted PR #725 which introduces bs3 standard markup while remaining backwards compatible, as well as it gets closer to the material spec.
