### ISSUE TITLE
list groups

### ISSUE THREAD

**Issue by xensor** [mdbootstrap/mdb-ui-kit#716]
could we make it where if we just use the standard list-group tags it shows the original list-groups as well. instead of unstyled.

**Comment by rosskevin** [comment]
I'm unclear about your question.  Please consider submitting a [CodePen test case](http://codepen.io/rosskevin/pen/VvRgrN) to demonstrate what you would like.

**Comment by rosskevin** [comment]
duplicate of #578 ?
