### ISSUE TITLE
Support select2 style?

### ISSUE THREAD

**Issue by thearabbit** [mdbootstrap/mdb-ui-kit#717]
Support select2 style?

**Comment by rosskevin** [comment]
[Selectize](https://github.com/FezVrasta/bootstrap-material-design#selectizejs) is supported.  Please read about it and see if it meets your needs.

**Comment by thearabbit** [comment]
Thanks, but I seem don't understand on doc

```
... Material Design for BS provides a full replacement of the plugin's CSS, so don't include it .....
```

So it mean that we don't include `CSS of Selectize` to use it.
Only add `JS file`

**Comment by chase439** [comment]
Selectize doesn't seem to be supported any longer?

https://github.com/FezVrasta/bootstrap-material-design/blob/master/scss/extensions/_selectize.scss
The README originally stated:

> Selectize.js
> Transform select and multi-select inputs into advanced text inputs. Material Design for BS provides a full replacement of the plugin's CSS, so don't include it.

**Comment by chase439** [comment]
FYI, for those looking I decided to use chosen-select js with css from https://github.com/haubek/bootstrap4c-chosen/blob/master/dist/css/component-chosen.css. I then modified it a bit, it works well with bootstrap-material-design
