### ISSUE TITLE
Replace JQuery with AngularJS

### ISSUE THREAD

**Issue by jamesbyrneiitd** [mdbootstrap/mdb-ui-kit#719]
Hi,

My project uses AngularJS and i'm wondering if bootstrap material design have a variant to work without JQuery and exclusively on AngularJS.

Do let me know or if there's anyone working on the same.

regards,

**Comment by chugunomi** [comment]
What the problem with official material https://material.angularjs.org/latest/ ?

**Comment by rosskevin** [comment]
BS3 requires jquery, therefore it is necessary that BMD is going to require jquery.

**Comment by tilwinjoy** [comment]
@jamesbyrneiitd here you go http://tilwinjoy.github.io/angular-bootstrap-material/
