### ISSUE TITLE
the css generated by the sass-files is not clean

### ISSUE THREAD

**Issue by wouterlemoine** [mdbootstrap/mdb-ui-kit#720]
Hello,

i was quickly checking this repo to see if i'ld like to use it on a project. But i noticed that the css-file is quite large. When i dig into this, i see for example in "material.css," at rule 913 that there are a lot of redundant css-selectors defined, caused by overusing the "&" in the sass-files. 
Just letting you know.

Kind regards. 
W.

**Comment by FezVrasta** [comment]
Yes both LESS and SASS generate bad CSS. I'm waiting for BS4 to start a lifting of this project.
