### ISSUE TITLE
Cards examples

### ISSUE THREAD

**Issue by Zhigalin** [mdbootstrap/mdb-ui-kit#721]
If you look to some Google products, you will find that cards are used like bootstrap modals pretty often.
It would be nice to have this option...

**Comment by rosskevin** [comment]
Such as https://github.com/FezVrasta/bootstrap-material-design#cards?

Perhaps we should provide a sample.

**Comment by Zhigalin** [comment]
Hi again!
1st: Yes https://github.com/FezVrasta/bootstrap-material-design#cards that ones. We should copy them to pages and provide an example.
2nd: There is still some work for cards, they should look like http://materializecss.com/cards.html or http://www.getmdl.io/components/index.html#cards-section 
3rd: [Wish] I think if they will be able to pop up like modals (like this https://vimeo.com/121454851 but without complicated animation) that would be very beautiful.

**Comment by FezVrasta** [comment]
@Zhigalin consider that this project's aim is about styling bootstrap as material design, not to provide the full set of features of material design.

**Comment by Zhigalin** [comment]
@FezVrasta You're telling "This shall not pass" or "We aren't going to do this right now because it isn't our primary target"?

**Comment by rosskevin** [comment]
I think he's saying bootstrap is our basis, and we want it to look like and embody the concepts of Material Design, but that does not mean it will be exactly one-for-one.  

You are welcome to do some work on this and submit a codepen or PR of something you would like included.  This is a community project so you should not expect that it will necessarily be done for you, everyone needs to chip in.

**Comment by LinX64** [comment]
I'm agree with `Zhigalin` about those Card examples.it makes the library better than before.we will appreciate your follow-up about that.@rosskevin

**Comment by rosskevin** [comment]
@TheGuyyii - I'm only working on `v4-dev` now and only spending maintenance time on the v3 compatible version.  On that note, BS v4 has a card implementation which is structured like a modal which should help a ton with our material implementation. I have already put a ton of work into much improved documentation/examples for v4, which includes by default the examples from bootstrap's documentation.

If you want to submit a v3 compatible example PR, I'm happy to include it!

**Comment by FezVrasta** [comment]
We are not going to improve the V3 documentation because we'll focus on V4 soon, feel free to send a PR to implement this tho.
