### ISSUE TITLE
LESS variables overiden weirdness

### ISSUE THREAD

**Issue by mackski** [mdbootstrap/mdb-ui-kit#722]
The final css generated after including the LESS files is wrong.
Specifically:
.btn-primary:not(.btn-link):not(.btn-flat) {
  background-color: #009688;
  color: #333333;
}

Where the compiled css supplied with the project has:
.btn-primary:not(.btn-link):not(.btn-flat) {
  background-color: #009688;
  color: rgba(255, 255, 255, 0.84);
}

**Comment by rosskevin** [comment]
Please upgrade to the latest 0.4.0.  

`_buttons.less` uses `color: @darkbg-text` which by default is `rgba(255, 255, 255, 0.84)`. Sources and compilation look to be correct.

Please reopen if you still have a problem and give further explanation so we can help.
