### ISSUE TITLE
Input autocomplete

### ISSUE THREAD

**Issue by arcangelsalazar** [mdbootstrap/mdb-ui-kit#726]
Is there any suggested way to make input text works with autocomplete?

**Comment by rosskevin** [comment]
Autocomplete appears to work in 0.4.0 (latest).  Can you describe what is not working for you?

**Comment by arcangelsalazar** [comment]
Sorry, I didn't know the datelist tag in HTML 5. Using it everything is working well.
But I suggest to add some autocomplete example in the demo page.

**Comment by nichovski** [comment]
@arcangelsalazar @rosskevin can you post html snippet with autocomplete input? Can't find an example how to implement it.

Thanks
