### ISSUE TITLE
v4 documentation and example site

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#728]
Given the addition of a bunch of examples, and the many more we need to add I've begun to prototype on a personal fork a documentation that parallels bootstrap's own.  It's based on Jekyll and has the added benefit of giving us all the samples that currently exist in bootstrap rendered with the BMD overlay.

Once I have something worth looking at, I'll post a link to get some feedback.
- [x] [review v4's documentation approach before going further](http://v4-alpha.getbootstrap.com/migration/#documentation)
- [x] bring in bootstrap documentation framework as a basis for new docs
- [x] normalize gruntfile with bs's gruntfile
- [x] convert doc.css to less and break it up for maintainability
- [x] normalize colors to a variable
- [x] strip unnecessary content, leaving bs examples as-is
- [x] add material specific examples
- [x] consider some js material defaults to get basic bs examples looking material
- [x] finish content for home
- [x] finish content for about
- [x] content for footer
- [x] parse version from package.json and use in site
- [x] parse version of bootstrap and use in dependencies
- [x] get urls out of _config.yml that are not dynamic based on the above

**Comment by FezVrasta** [comment]
Thanks for all the time you are spending on this project! I'm sorry I can't be useful but my free time is nearly zero... :(

**Comment by rosskevin** [comment]
I've spent the day working on the grunt build to generate docs, adopting the same approach as bootstrap.  While we'll be wanting to cut quite a bit of content, it's actually quite nice to see the default rendering of material over the bootstrap samples.  The home page doesn't work (errored resource caching?), but I think this is a starting point. I did virtually no work on styling.  I did break up their docs.css into less files for easier management, and based the coloring off of a single color (not sure which one to use).

The icons are placed dynamically as part of a grunt build process creating a list of icons by executing a regex on the icons less file, which is nice.

A lot more work to go, but it seems like a good foundation.

http://rosskevin.github.io/bootstrap-material-design/components/

**Comment by rosskevin** [comment]
Need to review v4's docs, they have had some upgrades, might be a better starting point.  http://v4-alpha.getbootstrap.com/migration/#documentation

**Comment by rosskevin** [comment]
A sample of v4 and rendering is published on my github repo (even though all the work is here in `v4-dev`).

http://rosskevin.github.io/bootstrap-material-design/getting-started/introduction/

Done:
- `Getting Started` and all related information has been updated written specific to MDB 
- `Migration` lists changes and rationale (all is up for debate based on peer review)
- Note that there is a `Material Design` section with specific examples.  
- `Bootstrap Reference Documentation` section is literally copied docs from bootstrap (with an inserted reference callout) that allows us to develop against their default examples. This has proven to be very helpful and is easy to keep up to date with automation via `grunt docs-copy-bootstrap-docs`.
- Customized jekyll plugin that provides some niceties for dependency/version management that automatically updates the docs
- Automated release process via grunt (with documentation) for both the `dist` and the publishing of `gh_pages`.  [Detailed in release process](http://rosskevin.github.io/bootstrap-material-design/getting-started/release-process/)
- [Full documentation on build tools and development setup](http://rosskevin.github.io/bootstrap-material-design/getting-started/build-tools/)

To be done:
- Homepage - it would be nice to customize this to showcase our material implementation
- Examples - this is still rooted in the hierarchy because I'm guessing we will add our own.  We could include theirs plus add our own, but I would want to make them markdown anyway (to get a basic header/footer layout for css/scripts).  Sort of in a wait and see.
- `Material Design` section of docs, this might be better named `Components`, but don't want to conflict/confuse with the reference bootstrap documentation.
- Color scheme for docs is just a guess

The fundamentals I need are mostly there for me with v4, so I'm going to start integrating in my application and see what else turns up.  

Updated/new implementations:
- switch (was toggle) - @FezVrasta's impl
- radio/radio-inline - refactored
- checkbox/checkbox-inline - not so much refactored, but updated for inlines
- ES6 everywhere with discrete components - easy to customize/update
- list-group - new impl
- See [Migration](http://rosskevin.github.io/bootstrap-material-design/migration/) for more notes

I'm going to close this issue out since I think the fundamentals are in place and we can build upon it.  Thoughts are welcome.
