### ISSUE TITLE
Add preset templates to imitate Material Design structues

### ISSUE THREAD

**Issue by nelsonomuto** [mdbootstrap/mdb-ui-kit#73]
Not sure if this exists or is just not documented. But it would be a great feature: http://www.google.com/design/spec/layout/structure.html#

**Comment by TransitoryBliss** [comment]
To clarify; you want the project to implement new bootstrap structures as defined by the google specification?

**Comment by FezVrasta** [comment]
this is the documentation of how you should structure your app... what should we do with it?

**Comment by nelsonomuto** [comment]
Sorry, I did not clarify this with a good enough description. What I am suggesting is creating components that mirror the layout/structure/core material design components. And this may already be implemented, just needs a bit documentation if not (it is not obvious on the demo page or readme).

**Comment by FezVrasta** [comment]
so we should write some preset templates with examples based on the structure specified in the doc?

**Comment by TransitoryBliss** [comment]
My five cents; it's currently out of scope. We have a lot of functionality to implement currently and FezVrasta (and me) want things to work great before marking this stable. Maybe when all components work accordingly we could take that on. / end five cents

**Comment by FezVrasta** [comment]
yes I agree with your idea, put it to ice till we'll reach the stable release

**Comment by TransitoryBliss** [comment]
@FezVrasta get on the chat if possible! :)

**Comment by nelsonomuto** [comment]
ok cool

**Comment by rosskevin** [comment]
#728 provides an examples section so we can have multiple without creating a maintenance headache.

**Comment by rosskevin** [comment]
I'm going to close this out as old, v4's new documentation will have a place for the community to contribute examples.
