### ISSUE TITLE
Change approach to full customization of bootstrap via variables

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#733]
Given the success of the work in progress of #727 basing the current duplicated variables on a bootstrap import, it seems clear that a viable `import` solution wherein we could customize the range of bootstrap variables to suit the material design spec is:
- viable
- will significantly reduce code
- will significantly ease maintainability
- will allow **full** customization to those using less/sass and `import` the bmd source.
- should have almost no impact on those using css

Changes to current users:
- `.css` only users will need to remove the `<link>` to bootstrap.css and only link to bmd
- less/sass users may need to change the order of their imports

Conclusion:
This seems like a clear win for maintainers and for users.

Must haves:
- [ ] less file/import structure should easily allow users to control their imports - e.g. see bootstrap-sass use variations (compass | sprockets | full bootstrap). This means they could possibly use a different version of bootstrap than the distribution referenced version.
- [ ] bmd variables should be aligned with standard bs variables where possible
- [ ] bs mixins should be used where possible

Questions/discussion items:
Reuse of mixins can be hairy between less/sass. @FezVrasta - since v4 is making the switch to sass, would you be opposed to me making the source switch fully to sass and removing less for milestone `0.5.0`?

**Comment by FezVrasta** [comment]
Will bs4 remote support for less completely?

Honestly till the base is bs3 I would like to keep less support

**Comment by rosskevin** [comment]
The primary author (mdo) uses scss everyday and while he [hopes for a less version, he doesn't have one for v4 and some say it will be difficult if the full features of sass are used](https://twitter.com/mdo/status/591377197715234816).

So officially, there is no less support in v4, but they are open to the community contributing a conversion.

This gets me to really the same issue.  I'm a sass user, v4 is sass, and moving this forward in a powerful way could be hindered by having to do conversions for differences in the two languages (and the two supported bs3 libraries). 

I've already had to copy one mixin, with my goal of _reducing_ code and _increasing_ browser compatibility by relying on bootstrap code/mixins, this may prove to be a make or break decision for me.

I will keep going with `less` until there is a breaking point, then revisit it.  If it is a breaking point for me, we can discuss a branch strategy.

**Comment by FezVrasta** [comment]
What do you mean with "browser support" when you talk about sass? The browser support should be guaranteed by autoprefixer

**Comment by rosskevin** [comment]
I mean with regards to using bootsrap's mixins, it isn't a sass/less thing, I don't see either of those having any affect on browser support.  

It's that we can reuse a lot of work that bootstrap itself does (i.e. mixins etc).  Reuse get's tricky when trying both sass and less, i.e. the `input-size` mixin - sass has an extra param that less doesn't have, so reuse either becomes a complicated conversion problem or we copy code...and I really want to reduce code instead.  Bootstrap has a huge community, and rock solid browser support.  I want to rely on it as much as possible to reduce work and to try and be as rock solid as we can.

**Comment by FezVrasta** [comment]
Okay

**Comment by rosskevin** [comment]
Lazy loading of variables could be something that makes things difficult:
http://lesscss.org/features/#variables-feature-lazy-loading

Sass has different treatment of variables and overrides with the potential of using `!default`, we'll see what happens when I dig in.

**Comment by FezVrasta** [comment]
I think I'm the only one who would prefer a postcss approach with maybe css modules... What a dream :(

**Comment by rosskevin** [comment]
Yes, variables is probably the breaking point...I'm trying to get some reuse now in the other issue (not full overrides, just reuse), and I can see that customizing bootstrap would be approached entirely differently in terms of variable definition override.  Less would define variables last, sass would define overrides before including bs variables...ouch.  I'll try to think about a modular way to make both happen.

**Comment by rosskevin** [comment]
@FezVrasta I'm considering removing material-fullpalette color variations for the 0.5.0 full customization version (but leaving `colors.less`) and providing instructions on how to customize color (with less variables).  This would get rid of a lot of issues with the size, but still leave full flexibility to compile your custom color, and to use the source/variables directly. 

This would remove color named styles, simplify the code, and give users a more expected 'default' bootstrap markup result  as the wouldn't have to do anything but set their variables because we have all the default colors set by our variables.

I think you were already thinking in this direction for v4, are you good with me making this change for 0.5.0?

**Comment by FezVrasta** [comment]
I was already planning to remove the color variations. I think we could stick with the classic "light" and "dark" versions provided by bootstrap.

If someone wants a different color, just let them change the variables or add custom css.

**Comment by rosskevin** [comment]
Lazy loading of variables in less is making less/sass cross compatibility impossible.  For example, to generically set `border-radius`, I should be able to set the variable `border-radius-base` then include bootstrap.  Unfortunately, in less, you must set this variable _after_ you import bootstrap, and in sass you need to do it _before_.  I have not decided when, but it seems that going to sass earlier than later is going to save me a lot of headaches, and given v4 is sass, I'm really starting to feel like I might be wasting time attempting to maintain both sass and less.

**Comment by rosskevin** [comment]
I'm closing this issue, the content is a bit out of date for the v4 release, this probably should have been in an earlier milestone.
