### ISSUE TITLE
example bootstrap-elements togglebutton sample positioned a bit too much to the right

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#737]
This could be a column or horizontal form issue.

**Comment by gpgekko** [comment]
100% a horizontal form issue, it adds a `text-align: right` that messes up the offsets.

**Comment by FezVrasta** [comment]
adding `text-align: left` to `.togglebutton label .toggle` fixes the problem

**Comment by rosskevin** [comment]
[Test case](http://codepen.io/rosskevin/pen/mVyGRo?editors=100)

**Comment by rosskevin** [comment]
Released in [0.5.4](https://github.com/FezVrasta/bootstrap-material-design/releases/tag/v0.5.4)
