### ISSUE TITLE
Switch RobodoDraft to Roboto web font

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#739]
Currently, the roboto.less produces css that fails the csslint.  After looking, it seems that we should remove responsibility from this project and switch to the web font with some updated documentation
- [x] remove roboto.less
- [x] update examples with `<link`
- [x] update documentation with information and recommendation
- [x] convert mdi to material-icons ligature reference

**Comment by ivantcholakov** [comment]
For faster page loading, the @font-face definition of 'Material-Design-Icons' could be placed within a separate CSS and then linked. This also would give the possibility of using Web Font Loader JavaScript (Edit: https://github.com/typekit/webfontloader) or another utility for loading fonts.

**Comment by rosskevin** [comment]
@ivantcholakov web font for icons will be done in #178

**Comment by ivantcholakov** [comment]
Oh, I see.
