### ISSUE TITLE
Use Grunt to run a connect server on a watch with live-reload for dev purposes

### ISSUE THREAD

**Issue by nelsonomuto** [mdbootstrap/mdb-ui-kit#74]

**Comment by TransitoryBliss** [comment]
Check out the SASS branch. This is present there. Except for the connect-server, I opted for using http-server as it is much more stable out of my own experience.

**Comment by nelsonomuto** [comment]
not sure what you mean by "more stable" can you clarify, grunt-contrib-connect is more or less the standard and as hooks that provide livereload out of the box. I looked in the feature/sass branch and did not see any http server task.
