### ISSUE TITLE
Remove fullpalette (keep colors.less and compilable variable substitution)

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#740]
relates to #733 
- [x] pull from codebase
- [x] update docs
- [x] remove superfluous variations (`-default | -info` etc that are not part of the default bs3 class structure)
- [x] break out radio color with variables

**Comment by rosskevin** [comment]
To be clear, access to full color variations is available, just set the color variables (choose one from `_colors.less`) and run `grunt dist`.

All color variations are still supported.

**Comment by AlexECP** [comment]
can you clarify further how to do this or provide an example?  I was using the full palette in the last version, and Im not clear how to get those colors working again in the new version.  What do you mean by set the color variables in that file?

**Comment by jensz12** [comment]
@rosskevin I would be lovely if you could clarify how to do that.

**Comment by rosskevin** [comment]
@AlexECP @jensz12 

I'm sorry, I see I left some TODOs in the readme.  I've update the docs with [color customization details.](https://github.com/FezVrasta/bootstrap-material-design#colors)  I tried these instructions locally without a problem.

**Comment by jensz12** [comment]
Thank you!

2015-12-02 16:42 GMT+01:00 Kevin Ross notifications@github.com:

> @AlexECP https://github.com/AlexECP @jensz12
> https://github.com/jensz12
> 
> I'm sorry, I see I left some TODOs in the readme. I've update the docs
> with color customization details.
> https://github.com/FezVrasta/bootstrap-material-design#colors I tried
> these instructions locally without a problem.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FezVrasta/bootstrap-material-design/issues/740#issuecomment-161338061
> .

## 

Med venlig hilsen:
_Jens Møller_
_jens@jensz12.com_ jens@jensz12.com
_+4520547827_
