### ISSUE TITLE
Ripple effect doesn't worked in Yii2

### ISSUE THREAD

**Issue by LinX64** [mdbootstrap/mdb-ui-kit#741]
refer to following link -> http://stackoverflow.com/questions/33652182/ripple-effect-does-not-work-after-using-material-design-for-bootstrap-in-yii2

**Comment by rosskevin** [comment]
Please see the [contributing guidelines](CONTRIBUTING.md).  If you have a bug, please submit it as a codepen reduced test case, otherwise personal support issues should remain on a site such as StackOverflow.
