### ISSUE TITLE
Missing material icon

### ISSUE THREAD

**Issue by bardtian** [mdbootstrap/mdb-ui-kit#742]
It seems there are some new material icons, for example "chat bubble outline" is not listed in Bootstrap material design.
https://www.google.com/design/icons/#ic_chat_bubble_outline

Any idea for the new icon use in Bootstrap material design?

**Comment by rosskevin** [comment]
@bardpresent we are switching to the [standard way of using md icons with the 0.5.0 release](https://github.com/FezVrasta/bootstrap-material-design/milestones/0.5.0).  You can try to do so now if you would like, though I'm unclear on what your results will be like:

http://google.github.io/material-design-icons/#icon-font-for-the-web

I'm hoping to have 0.5.0 out next week.

**Comment by FezVrasta** [comment]
@rosskevin will you just include the URL from Google Fonts for the icons?

I think it sucks (just a bit) because this will make the icons unavailable for websites without internet access.

I'd rather wait for Google to wake up and put their iconic font on bower...

**Comment by rosskevin** [comment]
You can also embed them, it's not too difficult to grab this and include it a project:
https://fonts.googleapis.com/icon?family=Material+Icons

For sites that are built that have restricted access, this should be a normal type of thing to need to bring in their version of the font.

On the flip side for the majority of cases, using the standard url **dramatically** increases the likelihood of being in browser cache thus speeding up initial hits.
