### ISSUE TITLE
v4 selection prototypes (radio, checkbox, switch)

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#743]
In the past months I've rewritten from scratch the Paper inputs (toggles, radios and checkboxes) to be easier to use and with much less markup needed.
# Radios:

http://codepen.io/FezVrasta/pen/XbQKez
# Checkboxes:

http://codepen.io/FezVrasta/pen/VLVqwb
# Toggles

http://codepen.io/FezVrasta/pen/yNRgrB

I've also created a pure SVG/SMIL loader, I'm not sure if it could be useful for this project:
http://codepen.io/FezVrasta/pen/oXrgdR

You may want to replace the old ones with these.

@rosskevin sorry for not being able to do it by myself... I've not enough time.

**Comment by rosskevin** [comment]
:+1: Your contribution is more than enough, thanks for submitting these as codepen samples.

**Comment by Zhigalin** [comment]
BUG!
Checkboxes in you pen is toggling only:
- if you click exactly top or left corner of the checkbox
- if you make click-click-click-click... very fast

Kubuntu 14.04, Firefox 42

**Comment by FezVrasta** [comment]
@Zhigalin they work as expected on Firefox 42 on El Capitan

**Comment by Zhigalin** [comment]
@FezVrasta I cannot add nothing, tried them again, but there is the same behaviour, my firefox is the last version from official ubuntu repos, no compiled/patched stuff or strange settings/addons...

**Comment by FezVrasta** [comment]
Does it happens only with checkboxes?

**Comment by Zhigalin** [comment]
Yes

**Comment by Zhigalin** [comment]
@FezVrasta Tried on the same system with Firefox Developer Edition, aurora branch, version 44.0a2 (2015-11-23)
Same behaviour here.
Update:
The checkbox is toggling (found making a BIG zoom)
- if you click exactly on the corner of the checkbox
- if you click exactly on the v sign(even if it is hidden)
- if you make click-click-click-click... very fast

**Comment by Zhigalin** [comment]
@FezVrasta Solved!
Checkbox was covered by svg, so just make sure is have a bigger z-index.
http://codepen.io/anon/pen/KdjgqG

P.S. I thing the ripple one was more beautiful...

**Comment by FezVrasta** [comment]
@Zhigalin the click should be triggered by clicking the label, and everything contained in it...

Probably on your system the SVG doesn't accept the click, so a better solution would be to set `pointer-events: none` to the svg element. Please try it and let me know if it works.

I liked the other as well but it had a much more complex markup/stylesheet and the material design specs says that on desktop the ripple effect should not be used on them.

**Comment by Zhigalin** [comment]
@FezVrasta You are right, without pointer events it also works.

**Comment by FezVrasta** [comment]
I've updated the prototype, now it should work even for you.

**Comment by rosskevin** [comment]
[Ripple on focus/pressed is something that is in the material design spec](https://www.google.com/design/spec/components/selection-controls.html#selection-controls-checkbox).

Is that easily added?

**Comment by FezVrasta** [comment]
I remember that MD says that the ripple effects should be applied only on touch screen devices... I don't remember where I have read it tho.

Ah, found:

> Use the outer radial reaction only on form factors that favor finger touch, where interaction may obstruct the element completely. For desktop usage with a mouse, you do not need this extra indication.

If we want to support ripple effect on mobile I think we should add it using the `ripples.js` script, in this way we can manage all the ripples from the same place.

**Comment by rosskevin** [comment]
Sounds good.  The other issue I see is that it is not rendering any text when I place it inside any of the labels.

**Comment by FezVrasta** [comment]
The elements I provided are thought to be used "as is", if you need a label you can easily add an extra one around the one used by the toggle element.

I've created them to be used on Ember/Angular/React (and so, this was the best way to make the components stand-alone and modular), not sure what is the best way in this case.

**Comment by Zhigalin** [comment]
@FezVrasta 

> MD says that the ripple effects should be applied only on touch screen devices... I don't remember where I have read it tho.

From material specs http://www.google.com/design/spec/components/selection-controls.html#selection-controls-switch:

> Use the outer radial reaction only on form factors that favor finger touch, where interaction may obstruct the element completely. For desktop usage with a mouse, you do not need this extra indication.

**Comment by rosskevin** [comment]
@FezVrasta can you make this checkbox svg respond relatively to the width and height of the svg?  i.e. I want the icon to be 20px, but the paths are drawn statically to an 18px bounding box.  I'd like this to be variable to suit form-control size variants as well.  I'm versed in svg enough to use it, just not author it.

[My current checkbox codepen](http://codepen.io/rosskevin/pen/MKKmVv?editors=110)

**Comment by rosskevin** [comment]
Perhaps we render the on the larger side,  say 30px and scale it with css?
