### ISSUE TITLE
"Select multiple" don't work with "size="15""? 

### ISSUE THREAD

**Issue by thearabbit** [mdbootstrap/mdb-ui-kit#748]
I use `select multiple`, but don't work with `size attribute`.

``` js
<select id="select222" multiple="" class="form-control" size="15">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
</select>
```

**Comment by rosskevin** [comment]
Please provide a codepen test case as requested in the contributing guidelines and describe your desired result.

**Comment by thearabbit** [comment]
It don't work with `size attribute`.
I try increase `size="20"`,  but it still show default of height.

**Comment by rosskevin** [comment]
Please respect the time of the other contributors.  Issues filed that do not meet [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#bug-reports) will be closed.
