### ISSUE TITLE
Need automated unit test build tasks for the js scripts and automated jshint task run

### ISSUE THREAD

**Issue by nelsonomuto** [mdbootstrap/mdb-ui-kit#75]

**Comment by TransitoryBliss** [comment]
This is being looked into - as well how we should structure future scripts. I believe @FezVrasta had some good ideas =)

**Comment by FezVrasta** [comment]
I've never written tests for front end scripts so any help is welcome. This weekend I'll write some test to check the integrity of the package.

**Comment by nelsonomuto** [comment]
I am going to submit a pull request with a fix for this in a few minutes.

**Comment by nelsonomuto** [comment]
it will include hooks for writing and running the unit tests as well as jshint. Just to clarify, it will not include unit tests for all scripts, just the hooks necessary to get unit testing as an automated part of the build. I will add unit tests slowly as I get familiar with the code.
