### ISSUE TITLE
Material Design Icons not rendering

### ISSUE THREAD

**Issue by suederade** [mdbootstrap/mdb-ui-kit#750]
I'm not sure if it is because I'm using wiredep to inject my script and link tags, but they don't seem to be rendering. Is there a specific file that handles this? I'd rather not go around this and actually install material-design-icons and have it twice.

**Comment by rosskevin** [comment]
With 0.5.0 (master) we switched to using the web-font for icons:
http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#icon

You must have the fonts linked in your layout:
https://github.com/FezVrasta/bootstrap-material-design#getting-started

As far as your question, it is unclear to me.  I think it would be best if you reviewed your generated html output and compare it to a the [codepen template](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#bug-reports)

If you still cannot get it to work, please submit a codepen so we can help further.

I'll double check it now to make sure codepen is working for icons.  

EDIT: it isn't, fixing that now.

**Comment by rosskevin** [comment]
Ok, sorry for the mixup, the [codepen template](http://codepen.io/rosskevin/pen/VvRgrN) is now working for icons, though it seems I have an icon bug to fix (roboto isn't showing)

**Comment by suederade** [comment]
So I use wiredep to inject all the necessary script and link tags as specified in the `bower.json`.

I noticed that and when I do something like `<i class="material-icons">chevron_right</i>`, when the page is rendered all I see is the text "chevron_right".

So is there a link tag that I'm missing to make this happen?

**Comment by rosskevin** [comment]
Please look at the information I have already provided:

> You must have the fonts linked in your layout:
> https://github.com/FezVrasta/bootstrap-material-design#getting-started

**Comment by suederade** [comment]
Ok, so you don't actually include material-design-icons in your source? Because I looked at the instructions for setting it up and it says I can install them through bower (which is how I install boostrap-material). I can either do that or use a link to Google Web Fonts. You don't necessarily specify whether or not you have it in your package.

**Comment by rosskevin** [comment]
> With 0.5.0 (master) we switched to using the web-font for icons

I'll make sure to remove those old docs now.

**Comment by ivantcholakov** [comment]
@stevenmwade What do you mean by "include in source"? If you mean that @font-face directives are to be inside the compiled CSS, that should not happen. A developer should have options available on how the fonts are going to be loaded, for improving performance. https://davidwalsh.name/font-loading

**Comment by rosskevin** [comment]
@ivantcholakov he's referring to the old method where we used to compile the font-face directives, that his since been removed so we can use the standard google fonts cdn (which should have better browser caching due to the more universal url)

**Comment by rosskevin** [comment]
docs updated

**Comment by suederade** [comment]
@rosskevin @ivantcholakov Yes, that, but also think directs you to Google's icon site which in the directions allows you to bower install the fonts as opposed to using their CDN. That seems to be how you had it before and I wasn't sure whether you actually took that out or not. Thanks for the update.
