### ISSUE TITLE
Btn raised on hover

### ISSUE THREAD

**Issue by suederade** [mdbootstrap/mdb-ui-kit#753]
I'm not sure if this is by design now, but `.btn` is raised on hover instead of flat like on the examples page.

**Comment by suederade** [comment]
I notice that `.btn-flat` corrects this.

**Comment by rosskevin** [comment]
`btn-flat` no longer exists in 0.5.*.  

[Examples show the default button is flat, and has a shadow on hover](http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#buttons).

See [`Flat and raised button states` in the Material Design specification](https://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons)

![image](https://cloud.githubusercontent.com/assets/136564/11544315/e009a4f4-9906-11e5-9277-bfe25294c194.png)

In the future, please indicate the version you are using and either link directly to the example or provide a codepen.  Please review our [contribution guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#bug-reports), it will help us help you.

**Comment by suederade** [comment]
I am using 0.4.1, the default for bower, since a couple weeks ago. I clearly missed the update to 0.5 in the last couple weeks. Apologies. Granted I've left the examples page open for the last few weeks as my reference and there is no version indicated. I didn't realize versions get updated that quick with y'all. 4.1-4.4 in two days and 4.4 to 5.0 three days later. Y'all move quick.
