### ISSUE TITLE
Relative path include of bootstrap LESS variables

### ISSUE THREAD

**Issue by guillaume-sainthillier** [mdbootstrap/mdb-ui-kit#756]
In the less/_import-bs-less.less file, the path to import Bootstrap could be : "../../bootstrap/less/variables.less" instead of "../bower_components/bootstrap/less/variables.less" ? 
This will prevent error compilation if the default bower path is not bower_components.

**Comment by rosskevin** [comment]
Those two paths are not equal so that would break compilation.  Give it a try and see for yourself.

**Comment by tylervick** [comment]
I'm also having an issue here. I have a project that uses a custom directory to store bower components.

Is there a workaround so that this package can import variables.less from a different location?

**Comment by rosskevin** [comment]
With less, I think you can actually import based on a variable.  In sass you cannot interpolate imports.  Sass is configured using a loadPath in the gruntfile, so perhaps:
a) try variable interpolation; or
b) look for an equivalent for load paths.

We'll gladly accept a PR!
