### ISSUE TITLE
Add the last documentation webpage

### ISSUE THREAD

**Issue by jonatanfm** [mdbootstrap/mdb-ui-kit#757]
For the users that downloaded the last repo code, now they can't add icons neither the material-colors page that was very usefull

**Comment by rosskevin** [comment]
Your comment or question is unclear, but I'll try to provide some useful information.

Color documentation is here: https://github.com/FezVrasta/bootstrap-material-design#colors

Icon details and reference to the full set of icons is here: https://github.com/FezVrasta/bootstrap-material-design#icons
