### ISSUE TITLE
Conflict with different validation plugin

### ISSUE THREAD

**Issue by oceanwap** [mdbootstrap/mdb-ui-kit#759]
I want ripple effect in my input fields but I am using different validation plugin which conflicts with has_error class.
How can I disable validation for input.

**Comment by rosskevin** [comment]
Have you set the [html5 `novalidate`](http://www.w3schools.com/tags/att_form_novalidate.asp)?  Does it still conflict after that?  Please reopen if this doesn't solve your issue.

**Comment by oceanwap** [comment]
Yes I have set novalidate.

**Comment by oceanwap** [comment]
If you read my comment properly you will know. formValidation.io which is an advance validation plugin, I am using in my app which is setting has_error class which then removed by "attachInputEventHandlers"
 bootstrap material design.
I am using backbone, requirejs.
I am using pattern attribute in my input but still it is being validated and has_error is being removed from div.form-group

**Comment by rosskevin** [comment]
Please edit this [codepen](http://codepen.io/rosskevin/pen/VvRgrN) and provide a minimal test case.  I'm familiar with formvalidation.io so it shouldn't take long for me to resolve.

**Comment by oceanwap** [comment]
formValidation(http://formValidation.io) is a premium plugin, not available on CDN so can't show but
I can show you that "checkValidity" method doesn't check for pattern attr in number input type. 
check http://codepen.io/anon/pen/QywKbj
I have set a pattern(for 10 digit number) for number input type(email validation is in-built in browser) and it doesn't turns red even if you type 20 digits. Which why "attachInputEventHandlers" removes "has_error" class.

**Comment by oceanwap** [comment]
@rosskevin 
I am just saying that there should be an option for whether I want to validate my form by material design's validation or custom/3rd party plugin.
If I set "input": false, it removes complete ui from input fields.

**Comment by rosskevin** [comment]
Got it, I switched to email because I know that is triggering validation.

http://codepen.io/rosskevin/pen/YwPpEW

I'll work on an option

**Comment by rosskevin** [comment]
This configuration will turn off validation `{validate: false}`: 
http://codepen.io/rosskevin/pen/YwPpEW

Available as bower 0.5.3

**Comment by oceanwap** [comment]
Thanks.

Roshan kumar
+91 9654923070
skype: oceanwap
