### ISSUE TITLE
How to disable effect ripple JS on right click

### ISSUE THREAD

**Issue by isogram** [mdbootstrap/mdb-ui-kit#76]
why Ripple JS change the color while right click? can I disable that feature? how?

**Comment by FezVrasta** [comment]
Will fix it soon

**Comment by FezVrasta** [comment]
fixed in the develop branch

**Comment by isogram** [comment]
have you try to click on the link with the ripple then you drag that link? the background color not go back to default background color :)

**Comment by FezVrasta** [comment]
I'm aware of that... it's not exactly one of the top problems to fix.. I'm not aware of lot of people that click and drag the buttons
