### ISSUE TITLE
Raised button variations in button groups are not colored correctly

### ISSUE THREAD

**Issue by gpgekko** [mdbootstrap/mdb-ui-kit#764]
In version 0.3.0 I could achieve quite good looking button groups with non-flat buttons, but the new ones won't play nice. This should either be documented or fixed.

**Comment by rosskevin** [comment]
http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#buttons

On the right there are examples of several raised buttons in groups.

I do not understand how "won't play nice" translates into your expectation and desired result.  

Please read: https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#bug-reports

**Comment by gpgekko** [comment]
Sorry, had to cut it short when filing these because of time pressure. The expectation is quite simple: I'm upgrading from the 0.3.0 and there I have coloured buttons in a group. In the new version, I can't find a way to have them be anything but a default flat gray button (this is actually the underlying issue, updating the title to reflect that - this title comes from the naive approach of giving the individual buttons a .btn-primary.btn-raised).

The basic use case here is a group of filter buttons at the top of a panel, which before had the same background colour but now stand out being gray.

For comparison:
New: http://codepen.io/anon/pen/LGErJp
Old: http://codepen.io/anon/pen/WrbyLy

**Comment by rosskevin** [comment]
Thanks @gpgekko - in the future, if you could cut out all the other css and markup it's easier to confirm then fix (and confirm the fix).

[0.3.0 button group raised coloring](http://codepen.io/rosskevin/pen/xZbJeL)
[Master button group raised coloring](http://codepen.io/rosskevin/pen/adzjgw)

So it's now clear that the color variations are not being rendered for the `btn-group-raised`, but `btn-group` with `btn.btn-raised` is working fine.

**Comment by rosskevin** [comment]
Released in [0.5.4](https://github.com/FezVrasta/bootstrap-material-design/releases/tag/v0.5.4)
