### ISSUE TITLE
Card image aspect ratio broken on Android WebView

### ISSUE THREAD

**Issue by dandv** [mdbootstrap/mdb-ui-kit#768]
I found that setting [`height: 100%`](https://github.com/FezVrasta/bootstrap-material-design/blob/master/less/_cards.less#L34) on card images has no effect in desktop Chrome 40+, but on Android 4.4 WebView, it distorts the aspect ratio of the image. My [sample Meteor hybrid app](https://github.com/dandv/instagram-clone) was affected by this.

**Comment by rosskevin** [comment]
Please reduce this to a minimal [codepen](http://codepen.io/rosskevin/pen/VvRgrN) test case [as requested in the contribution guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#bug-reports). I unfortunately don't have time to go through your code to try and replicate it.

**Comment by dandv** [comment]
I'll try to work on it. The change was [this](https://github.com/dandv/instagram-clone/commit/3090cfc7318ee425ad63f1f5ffc38ed49af3a985#diff-12cfe1b2a5a0447ef5de3f02a7829939R28).

**Comment by rosskevin** [comment]
We aren't working on or leaving open issues that do not have a test case.  If you submit one, please reopen this issue.  Thank you.
