### ISSUE TITLE
Meteor package update

### ISSUE THREAD

**Issue by 92hackers** [mdbootstrap/mdb-ui-kit#769]
I'am using this project in my meteor project,  and  i  found the version is still  0.3.0,  which is too old,
there is big difference between demo and  my  developed project.
maybe you have forgotten updating it or something others.
wish that, and i am willing to help  : ) !

**Comment by rosskevin** [comment]
Actually I am unfamiliar with meteor all together.  @FezVrasta is there something I need to do to make this available via meteor and npm?  I'm primarily just making sure good tags exist for bower and updating the release notes.

**Comment by 92hackers** [comment]
i have already make the meteor package, code from tag v0.4.5, if i should publish it to the atmospherejs.com ?

**Comment by FezVrasta** [comment]
I think there was a grunt task to update the atmospherejs package... I've not experience with it unfortunately.

**Comment by rosskevin** [comment]
@FezVrasta if you will add `rosskevin` to the atmospherejs and npmjs sites as a project admin, I'll try to push and see what happens.

**Comment by FezVrasta** [comment]
I lost the password of the account associated with the project :|

edit: actually I can login to my account but I can't find a way to add a collaborator...

**Comment by rosskevin** [comment]
It may give me a good message once it is publishable.  @92hackers I need you to try and fix the errors and submit a PR.  On master I have updated some of the files, but I'm lost otherwise and I admit I don't have a lot of motivation on this front.

If you can make `grunt meteor-test` work and submit that as a PR, I should be able to attempt to publish.

**Comment by 92hackers** [comment]
got it, i will do it as soon as possible

**Comment by 92hackers** [comment]
@rosskevin , can you explain me about meteor/test.js ?
code :  var plugins = ["affix", 'alert', "",,,,,,,,];
but ,  where do  you  include  those  plugins ?
and  why  test  those  plugins  ?

**Comment by rosskevin** [comment]
I have no idea why they were included,  but they are BS plugins,  so perhaps it was testing that or it was just copies and never fixed.  It doesn't seem like a good test of MDB.

**Comment by rosskevin** [comment]
@FezVrasta here is a note on adding contributors/publishing - it recommends creating an organization with people:
http://stackoverflow.com/a/29269583/2363935

I think we either need to get this updated or pull it, people are using a package that is out of date and it makes it look like the project is not working (which it may indeed not be for meteor users).

**Comment by FezVrasta** [comment]
I would drop it at all... If someone wants to maintain it, he will create a fork I guess.

**Comment by rosskevin** [comment]
I don't have access to drop it on atmosphere.  I would suggest you drop it (and I'll drop the related grunt code because it doesn't work).  If someone steps up and submits a PR, we can go from there.

**Comment by FezVrasta** [comment]
I wonder how should I be able to drop it from atmosphere... The account linked to it is `fezvrasta`, but I have the credentials to `fezvr4sta`... when I try to login to `fezvrasta` it says that such account has not a password set :/

@dandv setup it for me ages ago... If I remember correctly

**Comment by rosskevin** [comment]
If @dandv cannot help pull it, perhaps submit a support request?

**Comment by FezVrasta** [comment]
Let's wait a day to see if he can help us, if not, I'll then submit a ticket.

**Comment by tsega** [comment]
@FezVrasta I must say you have one of the most popular packages on Meteor some 7K+ downloads. I myself use if for almost all of my new projects but I didn't realize it was totally out of sync with the original. 

I want to help getting this up to date:

> I lost the password of the account associated with the project :|
> edit: actually I can login to my account but I can't find a way to add a collaborator...

Here is what you need to do, 
1. Go to meteor.com and sign in with your account, i.e `fezvrasta`. 
2. Then go to you profile settings to create an organization, https://www.meteor.com/account-settings/organizations ; this way you could add a trusted person like @rosskevin to your organization and he can follow with updating etc.

**Note:** @rosskevin would also need a meteor.com account.

I would also love to help with this!

**Comment by rosskevin** [comment]
I have a meteor account - it is rosskevin.

@tsega we would love to have your help.  What we need right now is a PR that makes the grunt meteor tasks work.  It doesn't appear that the `grunt meteor-test` has any bearing on this library, and may have been copied.

Permissions aside, I just need a PR from a meteor user that ensures I can call `grunt meteor` when I a have a new version to release.

**Comment by FezVrasta** [comment]
@tsega, sorry but I get this when I try to login to `fezvrasta`:

![image](https://cloud.githubusercontent.com/assets/5382443/12790445/94580758-caa2-11e5-8464-a14f74960528.png)

If I try to login with my real account `fezvr4sta`, I can login but I have no access to the repo settings.

**Comment by tsega** [comment]
OK it seems like the user `fezvrasta` is not a simple user but an organziation.

<img width="627" alt="screen shot 2016-02-03 at 8 21 24 pm" src="https://cloud.githubusercontent.com/assets/206924/12790537/c2b68c30-cab3-11e5-90b5-ec0bdc2eba17.png">

Your real user is `fezvr4sta`. Use that to login.

**Comment by FezVrasta** [comment]
Ah! yes!

I've added rosskevin to the collaborators

**Comment by tsega** [comment]
:+1:  @rosskevin I'll be working on that PR, but I must admin I haven't used grunt, gulp or bower. I'm a total Meteor fanboy :blush:

**Comment by FezVrasta** [comment]
I think we just need a task to pubblish the new builds on atmosphere...

**Comment by rosskevin** [comment]
The meteor task looks about right, but perhaps we need to just drop the meteor-test task (or make it useful)

**Comment by tsega** [comment]
@rosskevin according to the [README](https://github.com/tsega/bootstrap-material-design/tree/master/meteor) there is are only in-browser tests and here is what I get at the moment.

<img width="1390" alt="screen shot 2016-02-03 at 9 06 21 pm" src="https://cloud.githubusercontent.com/assets/206924/12792286/2803a070-cabc-11e5-8094-6492d62737fc.png">

and then

<img width="1390" alt="screen shot 2016-02-03 at 9 06 29 pm" src="https://cloud.githubusercontent.com/assets/206924/12792365/828e2bf0-cabc-11e5-9da6-cf77a5f5899b.png">

It looks like the main issue here is that jQuery `$` is not found. @dandv would be the perfect person to help with this but I try to see how I can fix it.

**Comment by tsega** [comment]
In an attempt to run the tests using the `grunt meteor-test` I get the following output:

<img width="470" alt="screen shot 2016-02-03 at 9 39 26 pm" src="https://cloud.githubusercontent.com/assets/206924/12792843/bc5437d8-cabe-11e5-88a4-eb726e769ad5.png">

From what I can understand the `dist` folder is not created so in order to do that I ran `grunt` simply and I get the following output

<img width="670" alt="screen shot 2016-02-03 at 9 39 09 pm" src="https://cloud.githubusercontent.com/assets/206924/12792880/e47baeb2-cabe-11e5-8bf8-d588cda0db27.png">

How do I generate the `dist` folder with all the files and folders?

**Comment by rosskevin** [comment]
The dist files are there and [checked in](https://github.com/FezVrasta/bootstrap-material-design/tree/master/dist), these may be old filenames that need to be updated.

**Comment by tsega** [comment]
That's so strange my copy doesn't have that folder, I have your latest commit as well. I'll try to clone again.

**Comment by rosskevin** [comment]
A clean could have run, i.e. if you ran `grunt`.  Just run `grunt dist`

**Comment by tsega** [comment]
Yes that's correct I did `grunt clean` earlier. So now I'm getting a very similar error to this one, https://travis-ci.org/FezVrasta/bootstrap-material-design/builds/89655229

**Comment by rosskevin** [comment]
Yes, these are the meteor tests, which appear to be bogus.

**Comment by tsega** [comment]
Could this be something related, https://github.com/themeteorchef/jquery-validation/issues/6

**Comment by rosskevin** [comment]
I have no idea.  I'm not sure if I made this clear before, but I think these tests should be **deleted** because they appear to have been copied from bootstrap.  

If you aren't going to make them relevant to MDB, just delete them is my thought.

**Comment by tsega** [comment]
Got the bugger! As I suspected it was a `jquery` issue. I had to add

``` javascript
$ =jQuery.noConflict();
```

At the top of the [meteor/test.js](https://github.com/FezVrasta/bootstrap-material-design/blob/master/meteor/test.js) file on the second line right under `user strict;`

<img width="586" alt="screen shot 2016-02-03 at 11 23 48 pm" src="https://cloud.githubusercontent.com/assets/206924/12795875/38db120a-cacd-11e5-9ca0-164c4caf34fc.png">

What's next?

**Comment by rosskevin** [comment]
Try `grunt meteor`.  If you make it up to a publishing error due to credentials, I think that's all you can do, you just need to submit your PR

**Comment by tsega** [comment]
As you expected, everything passed but I was unable to publish due to credentials. Here you go:
<img width="484" alt="screen shot 2016-02-03 at 11 30 03 pm" src="https://cloud.githubusercontent.com/assets/206924/12796118/499d2c94-cace-11e5-8cef-f859545b722e.png">

**Comment by tsega** [comment]
@rosskevin I've submitted my PR.

**Comment by rosskevin** [comment]
Published, thank you @tsega

**Comment by tsega** [comment]
Thank you @rosskevin for the quick publish! I'm the first one to download it :smile: Please let me know if you need my help with any of the remaining issues.

**Comment by rosskevin** [comment]
The only problem remaining is that there are 4 packages now, 3 of which are no longer relevant:
https://atmospherejs.com/fezvrasta

I cannot seem to delete these others.

**Comment by tsega** [comment]
Ah! That's the only thing I don't like about atmosphere, once published you can't remove a package. They say it has to do with [keeping backward compatibility](https://github.com/oortcloud/atmosphere/issues/53) or something. I'm afraid there is nothing we can do about that.

**Comment by dandv** [comment]
Hey guys. Looks like you've sorted out the permissions.

I haven't followed the latest developments, so I'm not sure why the -noglyph package is no longer relevant, but if you want to hide it, run

```
meteor admin set-unmigrated <package:name>
```

**Comment by rosskevin** [comment]
@dandv - unfortunately that appears to have failed as well:

``` bash
$ meteor admin set-unmigrated fezvrasta:bootstrap-material-design-fullpalette
done.                                         llpalette@0.3.0-dev as unsuccessfully migrated ...                                               
done.                                         llpalette@0.3.0 as unsuccessfully migrated ...                                               
$ meteor admin set-unmigrated fezvrasta:bootstrap-material-design-noglyph
done.                                         glyph@0.2.0 as unsuccessfully migrated ...                                               
done.                                         glyph@0.2.1 as unsuccessfully migrated ...                                               
done.                                         glyph@0.3.0-dev as unsuccessfully migrated ...                                               
done.                                         glyph@0.3.0 as unsuccessfully migrated ...                                               
$ meteor admin set-unmigrated fezvrasta:bootstrap-material-design-noicons
done.                                         icons@0.2.0 as unsuccessfully migrated ...                                               
done.                                         icons@0.2.1 as unsuccessfully migrated ...                                               
done.                                         icons@0.3.0-dev as unsuccessfully migrated ...                                               
done.                                         icons@0.3.0 as unsuccessfully migrated ...   
```

**Comment by tsega** [comment]
@rosskevin actually that has worked, if you look at your [teams profile on atmosphere](https://atmospherejs.com/fezvrasta) the only package now is `fezvrasta:bootstrap-material-design`. The message `as unsuccessfully migrated` is what it's supposed to say.

@dandv thanks for the command been looking for something like for a while now. I think it's not being shared with the masses for a reason, right?

**Comment by rosskevin** [comment]
:+1:

**Comment by tsega** [comment]
Sorry if it's wrong to ask this here but the [original problem that lead me here](https://github.com/FezVrasta/bootstrap-material-design/issues/424#issuecomment-179339774) is still bugging me.

On my Android device running 4.1.2, the checkboxes appear but neither the ripple effect or the actual check mark appear when checked. How can I get this to work? 

**Even more, check boxes that don't have labels cannot be selected.** I have the same issues on the iOS emulator but not the android one. Pretty strange, if you ask me!

![screenshot_2016-02-11-12-16-09](https://cloud.githubusercontent.com/assets/206924/12972926/28d6d37e-d0ba-11e5-9d83-d820e6833f4d.png)

**Comment by rosskevin** [comment]
@tsega please raise a different issue.  We cannot log each and every issue for a meteor issue here.

My initial advice is to log a new issue, and ask for advice.  You should know that you are likely to be the one that fixes it, but by logging a separate issue and asking, the community may be able to help you.

On a personal note from someone with deep experience in mobile, please first look at the mobile market share and make sure it is a must-have.  While it would be nice to fix this, the mobile market upgrades quickly.

**Comment by rosskevin** [comment]
Meteor guys - see #930, we have officially dropped support and need someone to step up and maintain a package.  We will be happy to link to you.
