### ISSUE TITLE
Radio button documentation mistake

### ISSUE THREAD

**Issue by gpgekko** [mdbootstrap/mdb-ui-kit#770]
First up, thanks for the swift resolution of the last couple of bugs, it's appreciated!

I was checking out the radio button documentation page (http://fezvrasta.github.io/bootstrap-material-design/#radio-button) and I noticed a mention of `.radio-success`, but it is visually the same as the `.radio-primary`. I'm not sure it's the documentation that is wrong or if it's a bug in the CSS though.

**Comment by rosskevin** [comment]
Those docs need to be removed. Since BS did not have the equivalent I pulled them and used a variable instead.
