### ISSUE TITLE
Inconsistent label highlighting on toggle type controls

### ISSUE THREAD

**Issue by gpgekko** [mdbootstrap/mdb-ui-kit#772]
I noticed the [checkbox](http://fezvrasta.github.io/bootstrap-material-design/#checkbox) colours the label on hover and [input / text boxes](http://fezvrasta.github.io/bootstrap-material-design/#input) colour their label on focus. [Radio](http://fezvrasta.github.io/bootstrap-material-design/#radio-button) and [toggle](http://fezvrasta.github.io/bootstrap-material-design/#toggle-button) buttons do not seem capable of this at all.

Is there a reason for the inconsistency? It seems a bit random to me.

**Comment by rosskevin** [comment]
Inner labels or outer `control-label` labels?  Remeber that a toggle type input can have two labels since they are grouped items. One for the group,  and one for the toggle type item.  In v4 the outer is primary colored on focus and the inner item label is darkened.

**Comment by rosskevin** [comment]
Note that `control-label` will get the `brand-primary`, whereas an inner `label` will darken on hover.  Added `is-focused` js to radio and toggle.

**Comment by rosskevin** [comment]
Also note how failure to demarcate with a `form-group` will cause inconsistent highlighting.  Omission of a form-group is there for convenience, but not recommended.  I'm doing some things to remedy this case in v4.
