### ISSUE TITLE
Alerts does not reappear after closed

### ISSUE THREAD

**Issue by nacholozano** [mdbootstrap/mdb-ui-kit#776]
This element does not reappear

<div class="alert alert-dismissible alert-danger">
</div>

Example: I use this in the login template to show if the password is incorrect 
I submit a incorrect password , the alert appear , I close the alert , I submit a incorrect password again and the alert does not appear 

I use it with angular

http://codepen.io/nacholozano/pen/bEdaOV

**Comment by rosskevin** [comment]
Hello @nacholozano,

It seems you need some personal support for use of angular with bootstrap.  This project does not add any functionality to alerts, only some visual changes.  Please ask your question on StackOverflow.
