### ISSUE TITLE
The label-floating input form is filling up something by browser

### ISSUE THREAD

**Issue by bardtian** [mdbootstrap/mdb-ui-kit#777]
The label-floating input form is filling up something by browser, and the default text is not floating.
Anyone know how to make the text floating when there is text filled by browser, so that it will not mix together after page loaded?

**Comment by FezVrasta** [comment]
There is a `:webkit-autofill` pseudo selector which could come in handy with this case... It's not implemented though.

There was a script to fix this problem time ago, I'm not sure if now it's gone.

May you provide a codepen to make the things easier?

**Comment by rosskevin** [comment]
We would like to help, but we really need a Codepen as there are too many variables to consider.  Please see [the contribution guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#using-the-issue-tracker) and submit a codepen.  Once submitted, please reopen the issue.

Thank you

**Comment by bardtian** [comment]
I tried, but I couldn't make it work in codepen, the :webkit-autofill is not working.
Here is a label-floating form sample.
http://codepen.io/bard/pen/QybepW

I guess .is-empty should not appear when autofill is working.

**Comment by sblackstone** [comment]
Also having this issue, here's a screenshot to help..

![example_materialize_issue](https://cloud.githubusercontent.com/assets/131382/13460720/9f178c8c-e04a-11e5-819e-9806d3d4f887.png)

The field is generated with this HTML:

```
<div class="form-group label-floating">
   <label class="control-label" for="admin_user_password">Password</label>
    <input autocomplete="off" class="form-control" type="password" name="admin_user[password]" id="admin_user_password">
</div>
```
