### ISSUE TITLE
floating label overlapping with text

### ISSUE THREAD

**Issue by pirat3k** [mdbootstrap/mdb-ui-kit#778]
I have used datetimepicker to pick a date. If the field is filled with this script, the floating label overlaps with the text in the field. But if I try to add 1 character the field, the floating label works fine.

**Comment by rosskevin** [comment]
We would like to help, but we really need a Codepen as there are too many variables to consider.  Please see [the contribution guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#using-the-issue-tracker) and submit a codepen.  Once submitted, please reopen the issue.

Thank you
