### ISSUE TITLE
Starter Template with sidebar

### ISSUE THREAD

**Issue by rijine** [mdbootstrap/mdb-ui-kit#779]

**Comment by rosskevin** [comment]
Please see [the contribution guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#using-the-issue-tracker) about filing issues.

**Comment by rijine** [comment]
@rosskevin please share me some starter template then...

**Comment by rosskevin** [comment]
Start with [bootstrap examples](http://getbootstrap.com/getting-started/#examples), then once you have the layout you would like, add in this project.  To add this project, see [getting started](https://github.com/FezVrasta/bootstrap-material-design#getting-started).

This project doesn't do layouts, we rely on bootstrap for all layout functionality.
