### ISSUE TITLE
Esc on label-placeholder causes is-empty marker to disappear as well as the label

### ISSUE THREAD

**Issue by lolobosse** [mdbootstrap/mdb-ui-kit#783]
Hi there,

Just want to be sure that the behaviour I'm seeing is the desired one because it seems pretty weird:

**Browser**: Chrome v47.0.2526.80

**Step to reproduce**:
- Create few inputs with `label` like this:

``` html
<div class="form-group label-placeholder is-empty">
  <label for="email" class="control-label" color="grey">Email</label>
  <input type="email" class="form-control" ng-model="controller.user.email" id="email" required>
  <span class="help-block">The email you type there will be your username</span>
</div>
<div class="form-group label-placeholder is-empty">
  <label for="passwd" class="control-label" color="grey">Passwort</label>
  <input type="password" class="form-control" ng-model="controller.user.password" equals={{controller.passwordRetype}} required id="passwd">
  <span class="help-block">Define a password, choose it as secure as possible</span>
</div>
<div class="form-group label-placeholder is-empty">
  <label for="passwdRepeat" class="control-label" color="grey">Passwort wiederholen</label>
  <input name="passwordRetype" type="password" ng-model="passwordRetype" equals={{controller.user.password}} class="form-control" required id="passwdRepeat">
  <span class="help-block">Retype your password to confirm it</span>
</div>
```
- It should look like something like this:
  ![image](https://cloud.githubusercontent.com/assets/5024077/11767982/f6e018b4-a1be-11e5-8110-bd66d32f17f4.png)
- Then, select a field (all is normal until there):
  ![image](https://cloud.githubusercontent.com/assets/5024077/11767989/194bb2d2-a1bf-11e5-8715-37f867a7b7cb.png)
- Then, type `Esc` to make the suggestion from Chrome disappear, and then your label (I mean the placeholder) doesn't appear anymore. 
  ![image](https://cloud.githubusercontent.com/assets/5024077/11767996/66ea5232-a1bf-11e5-9385-dca0ff0d27d2.png)

The last screen looks pretty bad, is that normal not to have the label anymore?

**Comment by rosskevin** [comment]
I'm not sure which version you are on but a form group should be adding enough margin bottom to include the help block.  Please try this using the codepen template requested in the contributing guidelines.

**Comment by lolobosse** [comment]
No that's not the problem, the div is not a problem at all. The problem is why are the label not there anymore, is that normal? :confused: :fearful:

**Comment by rosskevin** [comment]
I wouldn't think so, please submit a codepen so I can try it out.

**Comment by lolobosse** [comment]
Ok so I did a [CodePen](http://codepen.io/anon/pen/WrQMgO#0) and basically type `Esc` every time you're on a focused input to reproduce the "bug"

**Comment by rosskevin** [comment]
Thanks, in the future please use the codepen template requested in the docs as it references the `master` and is easier to prove it's not working, commit, then prove the fix.

This [codepen](http://codepen.io/rosskevin/pen/RrWJMw) is updated with the template and reproduces the bug.

This problem occurs because of a bug in the js determining emptiness.

**Comment by rosskevin** [comment]
All of these key codes exhibit the same incorrect behavior:

```
27  escape
13  enter
20 caps lock
16 shift
17 ctrl
```

**Comment by lolobosse** [comment]
Oh, ok, sorry, my report was not exhaustive, cool that you found that out! :smile:

**Comment by rosskevin** [comment]
Not a problem, almost done.

**Comment by rosskevin** [comment]
I suspect my latest commit resolves the issue, but it seems I'm still getting cached js for the sample.  I'll check on it in the morning to verify.
