### ISSUE TITLE
django "Try to dispatch to the right method"

### ISSUE THREAD

**Issue by Windsooon** [mdbootstrap/mdb-ui-kit#786]
![material-design-issue2](https://cloud.githubusercontent.com/assets/14333046/11863710/22834bfc-a4d1-11e5-8f14-47d29f65d6f4.png)

after submitted the form and click the back-botton,the page look like this
![material-design-issue](https://cloud.githubusercontent.com/assets/14333046/11863706/1765d97e-a4d1-11e5-9d21-5a03fc214065.png)

```
<div class="form-group label-floating is-empty">
    <label for="act_title" class="control-label">Act Title</label>
      {{ form.act_title }}
    <span class="help-block">Please enter a valid act title</span>
  </div>
  <div class="form-group label-floating is-empty">
    <label for="act_content" class="control-label">Act Content</label>
      {{ form.act_content }}
    <span class="help-block">Please enter a valid act content</span>
  </div>
```

**Comment by rosskevin** [comment]
Is there a javascript stack trace?  Are you using arrive.js?

**Comment by Windsooon** [comment]
![hey](https://cloud.githubusercontent.com/assets/14333046/11872510/941048d0-a510-11e5-8173-75b6548d193e.png)

I'm not sure, I used [cropit](https://github.com/scottcheng/cropit) here.

**Comment by rosskevin** [comment]
This [appears to be a django framework error](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=%22try%20to%20dispatch%20to%20the%20right%20method%22) and is unrelated to bootstrap-material-design.  Please ask your question on stackoverflow or seek help from the django community.
