### ISSUE TITLE
ripple affect not running web in firefox

### ISSUE THREAD

**Issue by jianqiao-ms** [mdbootstrap/mdb-ui-kit#787]
ripple affect not running web in firefox.Version 43.0.And my system is archlinux.Desktop environmen is plasma 5.5

**Comment by rosskevin** [comment]
I'm on firefox 34 on OSX and not having a problem with ripples on buttons:
http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html#buttons

I also tried on ubuntu desktop 15.04 with firefox 41 and 43, both of which worked.  

I cannot tell if you are using the examples or what version of bootstrap-material-design you are using.  Please see [the contribution guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#bug-reports) regarding submitting bugs.
