### ISSUE TITLE
Ripple does not function as expected after adding Animate.css

### ISSUE THREAD

**Issue by bkrajendra** [mdbootstrap/mdb-ui-kit#788]
Ripple effects does not respond to click as per directions after adding  Animate.css. Instead all ripple originates from center of element and  also it goes beyond boundary of element on page.
![2015-12-21](https://cloud.githubusercontent.com/assets/994083/11922899/a1f52d86-a7c1-11e5-87dd-db769d2ba7c5.png)

I'm Using latest code from dist folder.

**Comment by FezVrasta** [comment]
What's "animate.css"?

By the way, please, read the contributing guidelines and provide a codepen of the problem.

**Comment by rosskevin** [comment]
Please see https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#contributing-to-bootsrap-material-design
