### ISSUE TITLE
Navbar style on mobile like Materializecss

### ISSUE THREAD

**Issue by vinybnb** [mdbootstrap/mdb-ui-kit#789]
could we have navbar style on mobile like Materializecss? On mobile, when we toggle the menu icon, the navbar floats from left to right (much better than from top to bottom). Almost mobile apps have navbar style like this.

**Comment by rosskevin** [comment]
There are ways to do this with bootstrap, I suggest you search for those examples.  Jasny has some for example.  Otherwise that is not really in the current scope of this project.
