### ISSUE TITLE
Why can't I install bootstrap-material-design#0.3.1-dev?

### ISSUE THREAD

**Issue by tachang** [mdbootstrap/mdb-ui-kit#790]
This was the version in bower at one point.

**Comment by rosskevin** [comment]
Bower operates primarily off of git tags:
https://github.com/FezVrasta/bootstrap-material-design/tags

You were referencing a temporary development branch called `0.3.1-dev` which no longer exists.  I suggest you use the latest from bower which is `0.5.6`
