### ISSUE TITLE
navbar submenu not working

### ISSUE THREAD

**Issue by faxriddin** [mdbootstrap/mdb-ui-kit#791]
It is my code:
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        'css/site.css',
    ];
    public $js = [
        "js/plugins/formatter/jquery.formatter.min.js",
        "js/plugins/perfect-scrollbar/perfect-scrollbar.min.js"
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'romdim\bootstrap\material\BootMaterialCssAsset',
        'romdim\bootstrap\material\BootMaterialJsAsset'
    ];
}
///  

//in my layout 

NavBar::begin([
    'brandLabel' => Yii::t("frontend_layout_main", 'AppName'),
    'brandUrl' => Yii::$app->homeUrl,
    'brandOptions'=> [
        'data-toggle' => "tooltip",
        'data-placement' => "top",
        'title' => Yii::t("frontend_layout_main", "AppNameToolTip")
    ],
    'options' => [
        'class' => 'navbar-fixed-top',
    ],

]);

$menuItems = [];

if (!Yii::$app->user->isGuest) {

```
$menuItems[] = [
    'label' => Yii::$app->user->identity->username ,
    'visible'=>(Yii::$app->controller->module->id=="user"?false:true),
    'items'=>[
        ['label' => Yii::t("frontend_layout_main", 'Logout').'('. Yii::$app->user->identity->username . ')',
        'url' => ['/user/logout'],
        'linkOptions' => ['data-method' => 'post'],
        'visible'=>(Yii::$app->controller->module->id=="user"?false:true),]
    ]

];
```

}
echo NavX::widget([
    'options' => ['class' => 'navbar-nav'],

```
'items' =>[
    [
        'label' => Yii::t("frontend_layout_main", 'Select Company'),
        'url' => ['/company/select'],
        'visible' => (Yii::$app->controller->module->id=="user"?false:true)
    ],

    [
        'label' => Yii::t("frontend_layout_main", 'A data input unit'), 'url' => ['/company/view-input'],
        'visible' => (Yii::$app->controller->module->id=="user"?false:true),
        'options'=>'',
        'items'=>[

            [
                'label' => Yii::t("frontend_layout_main","Departments"),
                'url' => ['/department/index/'.Yii::$app->session->get('company_ID')],
                'visible' => (Yii::$app->controller->module->id=="user"?false:true),

                'items'=>[
                    [
                        'label' => Yii::t("frontend_layout_main","Departments"),
                        'url' => ['/department/index/'.Yii::$app->session->get('company_ID')],
                        'visible' => (Yii::$app->controller->module->id=="user"?false:true),
                    ],

                ]
            ],

        ]

    ],

    ['label' => 'Company',
        'visible' => (Yii::$app->controller->module->id=="user"&& Yii::$app->session->get('company_ID')!==null?false:true),
        'items'=>[
            [
                'label' => 'Company',
                'url' => ['/factoryep/company/view-input/'],
                'visible' => (Yii::$app->controller->module->id=="user"&& Yii::$app->session->get('company_ID')!==null?false:true)
            ],


        ]
    ],
],
```

]);

echo NavX::widget([
    'options' => ['class' => 'navbar-nav navbar-right'],
    'activateParents' => true,
    'encodeLabels' => false,
    'items' => $menuItems,
]);

NavBar::end();

Submenu not working, please help me!

**Comment by FezVrasta** [comment]
provide a codepen example with just the markup, we don't care about your backend logic

**Comment by faxriddin** [comment]
Excuse me!
