### ISSUE TITLE
Form fields are not filled correctly using chromeIPass

### ISSUE THREAD

**Issue by lehnen** [mdbootstrap/mdb-ui-kit#794]
Nice work.
Here is a little issue I found:
Credentials stored in KeyPass and filled in automatically using chromeIPass are optically filled, but submitted empty.

**Comment by rosskevin** [comment]
Thank you. 

First,  please see the contributing guidelines about submitting with a test case. 

Second,  we don't alter the actual text inputs for example,  so if there is a problem with an autofill component properly setting values,  I think it is unlikely (not impossible)  to be a css problem.
