### ISSUE TITLE
How to activate ripple effect on a custom class?

### ISSUE THREAD

**Issue by bardtian** [mdbootstrap/mdb-ui-kit#796]
I am building a site with a builder, and it's complicate to change the builder.
Currently giving .btn class name can active ripple effect on a button element. I Just wonder how to activate it by using a different class name?(also this may give possible for an old site that contains huge content)

**Comment by FezVrasta** [comment]
You can define any class to the .ripples function

It's `$.material.ripples('.class')`

**Comment by bardtian** [comment]
Thanks:)
