### ISSUE TITLE
Arrive.js `not a valid selector`

### ISSUE THREAD

**Issue by emdadgar2** [mdbootstrap/mdb-ui-kit#797]
Arrive.js support for new DOM object not working.
Witch version Arrive.js must use and how?

Got this error:

```
Uncaught SyntaxError: Failed to execute 'matches' on 'Element': '.btn:not(.btn-link),.card-image,.navbar a:not(.withoutripple),.dropdown-menu a,.nav-tabs a:not(.withoutripple),.withripple,.pagination li:not(.active, .disabled) a:not(.withoutripple)' is not a valid selector.
```

Thanks

**Comment by rosskevin** [comment]
Arrive.js appears to use `document.querySelectorAll`

I tested this in the console and got the same result:

```
document.querySelectorAll('.btn:not(.btn-link),.card-image,.navbar a:not(.withoutripple),.dropdown-menu a,.nav-tabs a:not(.withoutripple),.withripple,.pagination li:not(.active, .disabled) a:not(.withoutripple)')
```

I don't use arrive.js so it would be helpful if someone with jump in and figure this out.

**Comment by FezVrasta** [comment]
Looks like it doesn't like this part:

`.pagination li:not(.active, .disabled) a:not(.withoutripple)'` 

the comma separated classes in `not` are not allowed

It should be:

```
.pagination li:not(.active) a:not(.withoutripple),
.pagination li:not(.disabled) a:not(.withoutripple)
```

**Comment by rosskevin** [comment]
@emdadgar2 this does not appear in the latest version. Are you using 0.5.7 or a recent version?

**Comment by emdadgar2** [comment]
I use last version but doen't work

**Comment by rosskevin** [comment]
@emdadgar2, the latest version does not have this code.  Are you using the bower package or something else?  I mention this because the npm and meteor packages are far out of date...
