### ISSUE TITLE
CheckBoxes issue with Right to Left

### ISSUE THREAD

**Issue by LinX64** [mdbootstrap/mdb-ui-kit#798]
I was trying to add a right to left language like persian with following checkbox and here is my code:

`<div dir="auto" class="checkbox">
                    <label><input type="checkbox" value="">موافقم با شرایط استفاده از خدمات و حریم شخصی</label>
                </div>`

but after that, checkbox is working with an issue on showing the tick.here is the result:

http://i.imgur.com/GdelJFM.png

Currently, I'm using Yii2.

i will appreciate your suggestions and your recommendation.

**Comment by FezVrasta** [comment]
May you try to define the text direction of the checkbox to left to right?

**Comment by TheGuyyii** [comment]
hello, it's working with **left to right** but about that Right to Left no.and as you can see, i've set the `dir="auto"` to auto and of course with `dir="rtl"` it has the same result

**Comment by LinX64** [comment]
i just wanted to change the position of that checkbox to right and it has the above result.Btw, here is my try about that text:

`<div class="checkbox">
                    <label><input type="checkbox" dir="rtl" checked="checked" value=""> موافقم با شرایط استفاده از خدمات و حریم شخصی</label>
                </div>`

It shows perfectly, but what about that checkbox? how can change it from right to left without above issue?

thank you

**Comment by rosskevin** [comment]
@LinX64 I'm guessing that rtl support will require some significant changes.  I don't use any rtl languages, so without a potential committer stepping up to support all the rtl issues, I'm going to close this as won't fix, sorry.  If you are interested please let us know.

**Comment by KayvanMazaheri** [comment]
@LinX64

I had the same problem and I managed to fix it by adding this to my stylesheet: 

``` css
span.checkbox-material > span.check {
    padding-right: 10px;
}
```

This is the result :  
![checkbox-rtl](https://cloud.githubusercontent.com/assets/5472278/17394733/edcd6e40-5a3f-11e6-9b70-5561d4815319.png)
