### ISSUE TITLE
Increase specificity of all selectors

### ISSUE THREAD

**Issue by scinos** [mdbootstrap/mdb-ui-kit#799]
Use case:

Right now, rules that change the font in the page are encoded as a simple `body { font-family:...}` rule. This is the case for Bootstrap CSS as well. This means that if a developer wants to use Bootstrap + this theme, he/she have to rely on the order of the CSS stylesheets.

This is not always possible in all the frameworks. For example when using `jspm`, the order of the CSS stylesheets is not guaranteed, meaning that sometimes the fonts will not work. This also could affect other rules in this theme.

Proposed solution:

Add a class to the <body> (e.g. `<body class="material">`). This class will be used to increase the specificity of the rules in this theme, ensuring they will override the base rules in Bootstrap CSS.

**Comment by FezVrasta** [comment]
No way, if you use a tool that doesn't allow you to specify the order of the CASCADING style sheets then is the tool the problem.

**Comment by scinos** [comment]
Ok, I guess it is a matter of different points of view. Thanks for the reply anyway.

**Comment by FezVrasta** [comment]
No, is a matter of: you are using a shovel to row a boat.

Cascading means that the last one has the precedence, if you ignore this part, you are using just "Style Sheets", which is something nobody uses in the world.
