### ISSUE TITLE
looking for a better mixin for variations

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#8]
At the moment I use this mixin to generate every possible variation of a given element (buttons, wells, menus etc)

```
.variations(@extra, @property, @default) {
    // Bootstrap shades
    &@{extra}, &-default@{extra} {
        @{property}: @default;
    }
    &-primary@{extra} {
        @{property}: @primary;
    }
    &-success@{extra} {
        @{property}: @success;
    }
    &-info@{extra} {
        @{property}: @info;
    }
    &-warning@{extra} {
        @{property}: @warning;
    }
    &-danger@{extra} {
        @{property}: @danger;
    }
    // Material shades
    &-material-red@{extra} {
        @{property}: @red;
    }
    &-material-pink@{extra} {
        @{property}: @pink;
    }
    &-material-purple@{extra} {
        @{property}: @purple;
    }
    &-material-deeppurple@{extra} {
        @{property}: @deeppurple;
    }
    &-material-indigo@{extra} {
        @{property}: @indigo;
    }
    &-material-lightblue@{extra} {
        @{property}: @lightblue;
    }
    &-material-cyan@{extra} {
        @{property}: @cyan;
    }
    &-material-teal@{extra} {
        @{property}: @teal;
    }
    &-material-lightgreen@{extra} {
        @{property}: @lightgreen;
    }
    &-material-lime@{extra} {
        @{property}: @lime;
    }
    &-material-lightyellow@{extra} {
        @{property}: @lightyellow;
    }
    &-material-orange@{extra} {
        @{property}: @orange;
    }
    &-material-deeporange@{extra} {
        @{property}: @deeporange;
    }
    &-material-grey@{extra} {
        @{property}: @grey;
    }
    &-material-bluegrey@{extra} {
        @{property}: @bluegrey;
    }
    &-material-brown@{extra} {
        @{property}: @brown;
    }
    &-material-lightgrey@{extra} {
        @{property}: @lightgrey;
    }
}
```

The problem is that, using this code generates not-optimized CSS, I would like to find a better way (mixin?) to generate an unique, optimized, rule for every given element.

So, instead of have:

```
.checkbox-primary input[type=checkbox]:checked ~ .ripple {
  background-color: #4285f4;
}

.btn-primary {
  background-color: #4285f4;
}

.well-primary {
  background-color: #4285f4;
}

etc...
```

have:

```
.checkbox-primary input[type=checkbox]:checked ~ .ripple, .btn-primary, .well-primary {
  background-color: #4285f4;
}
```

This is just a reminder for me I think... but would be nice if someone could help me.

**Comment by zavoloklom** [comment]
I don't check, but maybe you can do this (if `@property` is used for color and background-color):
Less:

```
 .color(@default) {
     &-default {
        color: @default;
      }
      &-primary {
        color: @primary;
      }
      &-success {
        color: @success;
      }
     // etc
 }
```

And for background:

```
.background(@default) {
  ....
}
```

After that, you can create elements:

```
 .variations(@extra, @property) {
     &-default@{extra}  { &:extend(.@{property}-default); }
     &-primary@{extra}  { &:extend(.@{property}-primary); }
     // etc
 }
```

**Comment by FezVrasta** [comment]
Thank you! How should I use it? I've did this test:

```
.color(@default) {
    &-default {
        color: @default;
    }
    &-primary {
        color: blue;
    }
    &-success {
        color: red;
    }
}
.variations(@property) {
    &-default { &:extend(.@{property}-default); }
    &-primary { &:extend(.@{property}-primary); }
}

.foo {
  .color(black);
}

.bar {
  .variations(foo);
}
```

but it compiles into:

```
.foo-default {
  color: #000000;
}
.foo-primary {
  color: blue;
}
.foo-success {
  color: red;
}
```

**Comment by zavoloklom** [comment]
I see. An idea is to get from mixins code like this:

```
.color-default {
  color: #000000;
}
.color-primary {
  color: blue;
}
.color-success {
  color: red;
}
```

And then extend this classes by `&:extend` (docs: http://lesscss.org/features/#extend-feature).

```
// code1
.bar {
  .variations(color);
}
```

which is equal:

```
// code2
.bar-default { &:extend(.color-default); }
.bar-primary { &:extend(.color-primary); }
// etc
```

But, when i try it now - only `code2` works, not `code1`. 
So, sorry for that, I think it would work.

**Comment by nelsonomuto** [comment]
You can also think of this as part of build automation and use a tool which will parse the css and optimize it, run the code through this tool for example http://www.codebeautifier.com/ (based on http://csstidy.sourceforge.net/)to get a taste of what it does. (Basically it will concatenate those selectors that have the same style thereby solving our problem by performing selector and property merging). 

Incorporating a tool such as this in the build flow is ideal because your mixin does not need to be contorted into some weird unreadable code for optimization purposes. Here's a link to a tool currently maintained on npm for such purpose: https://www.npmjs.org/package/clean-css. I will try and add it to the build when I find time. This is the grunt plugin that supports that npm package: https://github.com/gruntjs/grunt-contrib-cssmin

**Comment by nelsonomuto** [comment]
Actually you are already using it and it is accurately performing the selector and property merging in the minified css output!!

**Comment by FezVrasta** [comment]
oh I didn't noticed it was merging properties...

**Comment by nelsonomuto** [comment]
Yeah, it does this already so we may better served leaving the less/sass as is because it is more readable in the current state. I would close this issue.
