### ISSUE TITLE
Compatibility with Summernote

### ISSUE THREAD

**Issue by rougin** [mdbootstrap/mdb-ui-kit#80]
It seems that [Summernote](https://github.com/HackerWins/summernote) is not compatible with this theme because it returns a NULL value on an element that is implemented with Summernote when sending the data through a POST method in PHP. To get that working, I need to disable either `material.js` or `ripples.js`.

**Comment by FezVrasta** [comment]
may you setup a demo to reproduce the problem? which one of the scripts cause the problem?

**Comment by rougin** [comment]
Unfortunately I can't view a live demo because of the server-side approach of this problem but I can give you a sample code on how I do this http://pastebin.com/4dMaHXXL

**Comment by FezVrasta** [comment]
I can't see how backend PHP can be broken by frontend JS... if you can report some error log I can see what it's happening.

**Comment by rougin** [comment]
I mean the value of the `.content` element (from the link provided) on client (JavaScript) are not being sent correctly as $_POST to server (PHP). Normally, If I write something to a `textarea` element with Summernote, it works perfectly as it should. But then when I tried to integrate it with your theme, now everytime I will send the value to the server, it remains empty. Sad to say I can't provide a sort of error log to prove it you :frowning:

**Comment by FezVrasta** [comment]
material.js and ripples.js do not change the behavior of the input fields, but material.js wraps the input in a div, it may break the script if it does not correctly select the input field.
