### ISSUE TITLE
ArriveJS doesn't seem to help applying the ripples to dynamically created elements

### ISSUE THREAD

**Issue by ccjmne** [mdbootstrap/mdb-ui-kit#806]
I've forked your starter CodePen and added AngularJS **and ArriveJS**, both **before Ripples and Material**.
My HTML contains a static button that dynamically creates other buttons when clicked, using some AngularJS directives.

Somehow **only the static one** has the expected ripple effect on click. What am I missing? :'(

Here's the [forked CodePen](http://codepen.io/anon/pen/OMmPBV) for illustration.

**Comment by ccjmne** [comment]
Just nevermind. Using:

``` javascript
$(document).ready(function() {
  $.material.init();
});
```

... instead of merely `$.material.init();` does wonders.

**Comment by ccjmne** [comment]
God dammit, actually it still isn't working as I expected. Any hint about what's wrong here?

**Comment by rosskevin** [comment]
I don't use Arrive.js, so any guidance from you would help me get it straight in this and in v4.  Thanks for the concise test case!

**Comment by FezVrasta** [comment]
```
Refused to execute script from 'https://raw.githubusercontent.com/uzairfarooq/arrive/master/minified/arrive.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

Looks like the URL is wrong.

You can't include raw.githubusercontent

use 

```
https://rawgit.com/uzairfarooq/arrive/master/minified/arrive.min.js
```

instead

**Comment by ccjmne** [comment]
... my bad. You're right, works perfectly. Thanks!
