### ISSUE TITLE
v4 checkbox and radios using material design icons

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#808]
See #743 for prototypes.

>  I want the icon to be 20px, but the paths are drawn statically to an 18px bounding box. I'd like this to be variable to suit form-control size variants as well. I'm versed in svg enough to use it, just not author it.

[My current checkbox codepen](http://codepen.io/rosskevin/pen/MKKmVv?editors=110)

Perhaps we render the on the larger side, say 30px and scale it with css?

**Comment by FezVrasta** [comment]
I'm not an SVG lizard... The original SVG was took from the icon set provided by Google.

I've tried to enlarge them by 2px but I can't get any good result.

Why 20px? Google uses 18 for all their icons.

**Comment by rosskevin** [comment]
When I reviewed several implementations, 20px yielded much better clarity, specifically for the radios.  Under 20px, the radios were pixelated, at 20, they were much better.

With that said, I wouldn't be happy with radios at 20 and checkboxes at 18.  

It should be noted that there are now published icons for both checkboxes and radios - search for `toggle` https://design.google.com/icons/

![material_icons_-_google_design](https://cloud.githubusercontent.com/assets/136564/12853015/6b1041de-cbf7-11e5-946a-5ac6d88107dd.png)

My thought was that perhaps both should be reworked to use the icons instead?  Thoughts?

**Comment by FezVrasta** [comment]
I've used exactly them, and if you read the specs they say that such icons are optimized for 18, 24, 36 and 48 dp (px in browser)

**Comment by rosskevin** [comment]
Your radio prototype didn't use them: http://codepen.io/FezVrasta/pen/XbQKez

**Comment by rosskevin** [comment]
But yes, I think I'd like to use them.  Wondering if we couldn't simply reference the ligatures instead of pulling in their svg source?

**Comment by FezVrasta** [comment]
I've tried to use just HTML and CSS where possible.

The checkboxes used the SVG because it would be a pain to create the entire checkbox in CSS... The old implementation was like that but wasn't so stable.

**Comment by FezVrasta** [comment]
I'm not sure if the ligatures could work, maybe.

**Comment by rosskevin** [comment]
What I'm saying is that the checkbox can stay at 18, and so can the radios, but we need a new prototype for radios with these icons.

**Comment by FezVrasta** [comment]
What's the problem of the current radio implementation? It's better if we can avoid to use SVG.

**Comment by rosskevin** [comment]
We have js involved here anyway (not much though), and I'm only thinking of swapping classes for the ligatures...I think it would be minimal js.  If you can try and render the svgs I can toy with the ligatures if I have time.  I'm not sure ligatures are worth it, just a thought that way we aren't copying any code, simply using it.

But I agree, moving to these in general is my preference.

**Comment by rosskevin** [comment]
Feel free to ping me on gitter

**Comment by rosskevin** [comment]
Current radio impl is pixelated at 18, but not at 20

**Comment by FezVrasta** [comment]
damn, stupid 5k screen... I see them crispy...

**Comment by rosskevin** [comment]
That's the svg impl advantage though, any screen they will be perfect

**Comment by rosskevin** [comment]
I would think that ligatures/font icons would be the most efficient _and_ best looking for this reason.

**Comment by FezVrasta** [comment]
SVG and HTML/CSS behave almost the same when you resize them.
Even SVG looks better on given resolutions (the ones optimized by the icon designer) and have weird artifacts on not supported resolutions.

That's why I don't think that use SVG/iconic fonts where not necessary is useless.

**Comment by rosskevin** [comment]
I'm not sure what you are saying, all I'm saying is that radios look bad at 18 and good at 20.  This seems to imply that the solution be either using the SVG or using the iconic font derived from SVG if we want to stay at 18 (which I have absolutely no objection to).  I simply don't want the radios to look terrible.
