### ISSUE TITLE
Where is fullpalette colors css?

### ISSUE THREAD

**Issue by LEXLEXLEXBATRAK** [mdbootstrap/mdb-ui-kit#809]
Where are material colors? Early there http://fezvrasta.github.io/bootstrap-material-design/#about was be a tab "material colors" or somithing like this.
Where is z-index and shadow classes for elements?
And etc.

Now it's and some other things doesn't work.

**Comment by rosskevin** [comment]
The fullpalette css was removed in lieu of compiled customization.  The variables are still available for use, see the readme https://github.com/FezVrasta/bootstrap-material-design#customization

If you can be more specific about z-index, I can help.  The shadows are mixins and are still present, albeit in a way that allows for sass conversion (so they have parenthesis).  See `_shadows.less` or the sass variant.  You may have used them like classes, but the source code uses them like mixins perhaps.

**Comment by skmexyz** [comment]
I can't seem to be able to use the `shadow-z-n` anymore. 
Imported it from [here](https://cdnjs.com/libraries/bootstrap-material-design)
