### ISSUE TITLE
Integrate with a continuous build server

### ISSUE THREAD

**Issue by nelsonomuto** [mdbootstrap/mdb-ui-kit#81]
Use Travis, it's free and will run your lint and unit tests to ensure everytime a developer checks in some code that it is not breaking anything.

**Comment by nelsonomuto** [comment]
I will look into this after you review my latest PR

**Comment by nelsonomuto** [comment]
have you heard of travis, https://travis-ci.org/

**Comment by TransitoryBliss** [comment]
Yes, I use it for my node_modules. Once unit tests is in place I will add it.

**Comment by FezVrasta** [comment]
please @shockwork may you test the dev branch and let me know if we can proceed with the merge on master?

**Comment by TransitoryBliss** [comment]
I'm on it! :)

**Comment by TransitoryBliss** [comment]
@FezVrasta I've finished the merging and testing. Had to update the jshint so it doesn't run on minified files. Want me to push it in?

**Comment by FezVrasta** [comment]
yea okay thanks :)

**Comment by nelsonomuto** [comment]
Guys we may have to re-open this, since the code-base is owned by @FezVrasta directly and not part of an organization, only he can set up a Travis CI repository build for it. I am limited to set one only on my fork(https://travis-ci.org/nelsonomuto/bootstrap-material-design), but we need one on the upstream (FezVrasta/bootstrap-material-design). 

Have you set up an org before @FezVrasta? This way anybody on the team can setup and modify the Travis CI build if needed. Otherwise you are the only one who can do this.

**Comment by FezVrasta** [comment]
I'll see what can I do tomorrow at office.

**Comment by FezVrasta** [comment]
Okay I think I've enabled it

**Comment by nelsonomuto** [comment]
Awesome, a nice finishing touch now would be to add the ci build emblem to the readme( the build status icon, https://travis-ci.org/FezVrasta/bootstrap-material-design.svg?branch=master), I will do this and issue a PR
