### ISSUE TITLE
well class not working

### ISSUE THREAD

**Issue by corientdev** [mdbootstrap/mdb-ui-kit#811]
I don't know why everything is working perfectly. only well class is not working

**Comment by rosskevin** [comment]
This is not a proper issue.  I don't know what "not working" means.  Please read and follow the contributing guidelines before reporting an issue.

**Comment by corientdev** [comment]
I meant well class is not working everything is loaded correctly and working correctly even ripple effect. only thing that doesn't work is "well" class. i guess it is not overriding the old well class of bootstrap

Can u please help?

**Comment by rosskevin** [comment]
I don't know what “doesn't work“ means.  Did you read the contributing guidelines? 

There is no such thing as a well in material design so you should avoid it.  It is also removed in bootstrap v4.

**Comment by corientdev** [comment]
And yes it was working properly before update using fullpallete.css

and see this is the well class i am talking about

![2016-01-08 18_42_38-bootstrap material](https://cloud.githubusercontent.com/assets/9655234/12198612/b9917632-b637-11e5-995c-f6e8c25e0fdc.png)

**Comment by corientdev** [comment]
I am sorry may be you are misunderstanding me. i am not saying there is a bug in a library. Only thing is i really want to achieve something which is there in library and demo also but i am not able to achieve it.

**Comment by rosskevin** [comment]
Try a card instead.  Cards are also in v4.

**Comment by corientdev** [comment]
Thanks!

Is there a way i can adjust two `Input` with `Input label styles` in same row?

**Comment by rosskevin** [comment]
No,  inputs are governed by a single form-group.  If you put two in the same foem group you will get bad focus behavior for example.

**Comment by corientdev** [comment]
any hacks for doing it?

**Comment by corientdev** [comment]
and there is too much space in between rows how can i decrease it?

**Comment by rosskevin** [comment]
Use CSS to reduce the form-group margin.
