### ISSUE TITLE
Ripple effect, strange behaviour

### ISSUE THREAD

**Issue by roccomuso** [mdbootstrap/mdb-ui-kit#812]
Hi guys, i'm having a weird behavior with the last ripple.min.css:

![Ripple effect](http://i.giphy.com/3o6UB4qggFcX0e6QYU.gif)

**Comment by rosskevin** [comment]
First,  is this reproducible with the codepen template referenced in the contributing guidelines?

**Comment by roccomuso** [comment]
Sure, this is the codepen: http://codepen.io/anon/pen/VeWZbo

I think it's related to my ripple.min.css and bootstrap-material-design.css combination.

**Comment by roccomuso** [comment]
I might have solved it. Updating to the last version all the JS files.
