### ISSUE TITLE
Unable to build with grunt, fails on compiling less

### ISSUE THREAD

**Issue by GeorgeL9** [mdbootstrap/mdb-ui-kit#813]
Fresh installation using bower, fails on compiling less.

Running "less:material" (less) task

> > FileError: '../bower_components/bootstrap/less/variables.less' wasn't found. Tried - bower_components/bootstrap/less/variables.less,bower_components/bootstrap/less/variables.less,../bower_components/bootstrap/less/variables.less in less/_import-bs-less.less on line 1, column 1:
> > 1 @import "../bower_components/bootstrap/less/variables.less";
> > 2 //@import "../bower_components/bootstrap/less/mixins.less";
> > Warning: Error compiling less/bootstrap-material-design.less Use --force to continue.

**Comment by alpacin0** [comment]
I'm experiencing the same issue, any ideas how to fix it? I have my bower_components folder inside the public folder of my laravel project (root_proyect/public/bower_components) is it the cause to the problem?

**Comment by rosskevin** [comment]
Yes, your bower components are in a different location, so you will need to adjust the include paths for less or sass depending on which you use.

**Comment by alpacin0** [comment]
Thanks kevin! I changed the paths in the "import-bs-less.less" file like:
`@import "/public/bower_components/bootstrap/less/variables.less";`
`//@import "/public/bower_components/bootstrap/less/mixins.less";`

And could run 'grunt less', and any command like a charm. Cheers bro.
