### ISSUE TITLE
Wrong path to bootstrap in file _import-bs-less.less when importing into another project

### ISSUE THREAD

**Issue by sclu1034** [mdbootstrap/mdb-ui-kit#814]
When installing both bootstrap and this design through bower, the path to bootstrap's variables file in `_import-bs-less.less` is incorrect.
So `../bower_components/bootstrap/less/variables.less` should be replaced with `../../bootstrap/less/variables.less`.

**Comment by rosskevin** [comment]
If we replaced as you request, it would fail to compile without another project.

I do think LESS allows variable interpolation in an import statement, perhaps you could look at defaulting the path to the current one, and substituting your own and see if that works.  If so, a PR would be helpful.

**Comment by sclu1034** [comment]
It does, but it uses the variable how its defined when the import happens. So defining the variable's default value within the theme would override the value the user defined.

``` LESS
// app.less
@bowerDir: "pathX"; // Will be overwritten, as last one wins
@import "/path/to/boostrap-material-design";
@bowerDir: "pathX"; // Too late, won't be used

// _import-bs-less.less
@bowerDir: "../bower_components"; // Default
@import "@{bowerDir}/boostrap/less/variables";
```

I think the best way to solve this would be to make the import optional and add a second, optional, import pointing to the path needed when installed through bower.
This should cover most use cases and even if it doesn't fit the user can just import bootstrap before importing the theme files himself.

If this solution is suitable in your eyes I'll create the PR.

**Comment by rosskevin** [comment]
In LESS, the **last** variable defined wins, so your source variable would win.  The only problem with this approach is that SASS is the exact opposite, but nonetheless, that's why we have the `_import-bs-less` vs. `_import-bs-sass` files.

**Comment by rosskevin** [comment]
I would call this var `mdb-bower-dir`

**Comment by rosskevin** [comment]
I was too quick to comment, I expect this to work:

The default var is defined in `_import-bs-less.less`

```
@mdb-bower-dir: "../bower_components";
@import "@{mdb-bower-dir}/bootstrap/less/variables.less";
```

```
// app.less
@import "../bower_components/bootstrap-material-design/less/core";
@mdb-bower-dir: "../..";
```

**Comment by rosskevin** [comment]
The other option would be the boolean variable as you suggested, which I also agree would work, perhaps it may be even simpler/more obvious.  In this case, I would default the source import to working, and change the grunt/build process to add the local ../../bower_components.

**Comment by rosskevin** [comment]
It's also possible the conditional/boolean approach would work with sass, though not sure.  

After some thought, **it definitely** seems like the conditional/boolean approach makes more sense.

So:
- default: app-ready source import using `../..`
- grunt: local build

`@mdb-local-build: false`?

**Comment by sclu1034** [comment]
Using a build tool might work.

As I said, changing the variable after the import statement has no effect (i tested this), so what you said earlier won't work.
But in LESS an import will wait for the variable to be defined if it is not yet, so you would use an undefined variable in the import statement and require to set it by build tools or when importing the design.
You could also use LESS import paths instead of setting the variable in your build tool.

**Comment by rosskevin** [comment]
Sass is currently setting a path in the gruntfile, while I don't like this, it works.  And v4 is sass, so it would be nice to solve this once and for all.

What I have decided is that moving forward (especially with v4), I want the typical application source import to _just work_, building from our own gruntfile allows us to do whatever we need to do to workaround the dual environments.

**Comment by sclu1034** [comment]
I've been trying to achieve the behaviour you mentioned, but using variables this always breaks down to the need of default values, which in this case is not possible as imports don't wait for lazy-load.
Using the two optional imports I mentioned earlier seems like the best solution to me now. It would cover both the local build without any changes to the gruntfile and the bower installed import and it would still allow users with an even different setup to import manually.

**Comment by rosskevin** [comment]
Set that up as a PR and I'll take a look.  We need a solution, and I'm convinced it may not be pretty.

**Comment by bhoomit** [comment]
Similar issue with sass I guess 

```
RROR in ./~/css-loader?sourceMap&-minimize&modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./~/sass-loader?sourceMap!./src/styles/core.scss
Module build failed: 
@import "bootstrap/variables";
^
      File to import not found or unreadable: bootstrap/variables
Parent style sheet: .../node_modules/bootstrap-material-design/sass/_import-bs-sass.scss
      in .../node_modules/bootstrap-material-design/sass/_import-bs-sass.scss (line 1, column 1)
 @ ./src/styles/core.scss 4:14-269 13:2-17:4 14:20-275

```
