### ISSUE TITLE
v4 Implement LMVTFY: Let Me Validate That For You

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#817]
https://github.com/cvrebert/lmvtfy

In filing an issue with bootstrap, this found a small error in my sample.  Pretty awesome.

**Comment by cvrebert** [comment]
Let me know if you run into any issues/questions when setting it up. :smile:

**Comment by rosskevin** [comment]
I've added bootlint directly to our Codepen templates, so that should cover this for the moment.
