### ISSUE TITLE
Adding a shadow to arbitrary elements?

### ISSUE THREAD

**Issue by andersodt** [mdbootstrap/mdb-ui-kit#819]
I am looking to add shadows to various elements at will (like the navbar) -- is there currently an easy way to do this?

**Comment by rosskevin** [comment]
Sure,  include the shadows.less or sass file and do something like `@include shadow-2dp()` sass or `.shadow-2dp()` less.

**Comment by andersodt** [comment]
Is there no way to do it without recompiling from the source?

**Comment by rosskevin** [comment]
The shadows are mixins,  so you would need the source.  You could copy them to your project and create them as classes if you would like.

**Comment by FezVrasta** [comment]
On less, mixins can be used as classes as well as far I know.

**Comment by Streemo** [comment]
What happened to 'shadow-z-1', etc.? This was a nice, simple method for including shadows -- why make it less simple?

**Comment by rosskevin** [comment]
@Streemo are you having a hard time finding the `shadow-z-1` mixin?
https://github.com/FezVrasta/bootstrap-material-design/blob/master/less/_shadows.less#L1

We support both less and sass so we use them as mixins, not classes.  Like @FezVrasta said, in less you could probably use them as a class.
