### ISSUE TITLE
Old Icon page

### ISSUE THREAD

**Issue by achuzan** [mdbootstrap/mdb-ui-kit#820]
Is there any way I can get a copy of the old icon page (with the mdi icons)? I don't have time to switch to the new icons. 
Thank you, 
    Brad

**Comment by rosskevin** [comment]
You can build from source and run `grunt serve` then navigate to either `index.html` or `bootstrap-elements.html`.

**Comment by achuzan** [comment]
that means nothing to me, but thank you, I will keep looking.

**Comment by rosskevin** [comment]
How about this, download the release source code for your release and try opening up the bootstrap-elements.html page in a browser?

https://github.com/FezVrasta/bootstrap-material-design/releases

**Comment by achuzan** [comment]
thank you
