### ISSUE TITLE
v4 drawer implementation

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#822]
## Initial implementation:
- [x] create a docs example drawer with no additional styling
- [x] initial layout with flex
- [x] allow marker class `mdb-drawer-open` to open the drawer i.e. for use with js
- [x] allow marker class `mdb-drawer-closed` to force closed the drawer i.e. for use with js (overrides responsive marker class)
## Style:
- [x] default pushes header and content
- [x] overlay overlays header and content
- [x] x overlay with a marker class (non-responsive)
- [x] y overlay with a marker class (non-responsive)
- [x] overlay should have a backdrop
## Responsive:
- [x] x/y - `open` responsive marker classes i.e. `mdb-drawer-open-md` to open the drawer at desired (and up) widths.
- [x] x/y - `overlay` responsive marker classes i.e. `mdb-drawer-overlay-md` to overlay the drawer at desired (and down) widths.
## Positioning:
- [x] x - left and right drawers
- [x] y - top and bottom drawers
## Component:

We may need a simple js component, or a way to toggle the `mdb-drawer-open`:
- [x] manual trigger to slide out
- [x] trigger to slide out on mobile should use a bg fade
- [x] integrate with navbar-toggler menu item to trigger it declaratively
## Nice to have

Not necessary but consider these during implementation:
- [x] drawer that works inside containers
- [x] two potential containers on the same layout i.e. left and footer?
- [x] different default drawer sizes (x width or y height) in an app
- [x] easy generation of custom drawer size classes

Left side is needed for #805 dashboard template.

**Comment by rosskevin** [comment]
Added some drawer demo icon buttons on the top right of the dashboard example
http://rosskevin.github.io/bootstrap-material-design/examples/dashboard/

**Comment by rosskevin** [comment]
Totally custom drawer size generated with:

```scss
// Example: creates a media responsive kitchen-sink-drawer that pairs with mdb-drawer-open-lg
@include mdb-drawer-x-closed(500px, ".kitchen-sink-drawer");

.kitchen-sink-drawer:not(.mdb-drawer-closed) {
  @include mdb-drawer-x-open-up(500px, lg);
}
```

Used with:

```html
<div class="mdb-layout-container mdb-drawer-fixed-left mdb-drawer-overlay-md mdb-drawer-open-lg kitchen-sink-drawer">
```

**Comment by rosskevin** [comment]
Drawer implementation completed.  I think it's pretty awesome and I've provided two good templates as demos in addition to the documentation.  

http://rosskevin.github.io/bootstrap-material-design/material-design/drawers/

Two things:
1.  I think that the drawer y mixins could be the basis for a bottom sheet
2.  I think we may want to transition the docs site to utilize a drawer for the side nav.

**Comment by dealproc** [comment]
So there is two different ways I can see folks using the drawer

as a navigation, always shown, not an overlay (probably the higher use case)

as a navigation for mobile, as in creating a main menu item.  in this use case, when i click on one of the entries of the menu, i'd like my drawer to disappear.  Any ideas/suggestions on how to accomplish this?  Whatever the solution is, support for Angular and/or knockout bindings would need to be respected.

**Comment by rosskevin** [comment]
For mobile,  clicking on the bg already makes the drawer close. 

If you aren't changing pages,  check the dashboard example,  the eye icon is hooked up to open/close the drawer,  you can adapt that how you would like.

**Comment by rosskevin** [comment]
I _may_ have hidden the extra demo icons on mobile.  Chexk them out on the desktop,  then peruse that code.

**Comment by dealproc** [comment]
yea, so you have 2 clicks to get rid of the drawer.  what i want to do is to click the icon/link/etc, and have it close as part of the navigation within my app.

**Comment by rosskevin** [comment]
Exactly,  that's why I pointed you to the example,  you need to write Javascript to listen for and do what you want.  The example has javascript that will take both actions. Did you also read the drawer docs?
