### ISSUE TITLE
v4 font root - should it be 16 or 14

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#824]
This is going to be painful, but as I've gone further, it seems we need to commit to a decision on font-root sizing.

BS4 switches to using `rem`s and the font-root is set to 16.  All MDB v4 work has been based on that.  For example, form padding and sizing is 16 based (the spec calls for the text that large) and it's one of the first things done so it made sense and was easy.

Now that I am getting into card spec with text etc, it seems I'm having to override down to 14sp, which is not really that big of a deal, but something to consider e.g. is a random `p` element going to behave as expected?

One question is how disorienting it might be to add bootstrap-material-design to an existing bs4 app, where if we change the root from 16 to 14, it will mess up everything else they have styled.

So, options:
1. Stick with font root at 16.  Add styles for `p, span, etc` to the spec which is likely 14sp.
2. Change font root to 14.  This will require:
   - a bunch of rework to the current styles
   - a side effect to those built on BS4 that adopt us later

After writing this up, I'm leaning towards option 1, leaving the font root at 16 and adding individual rules for standard text such as `p, span, etc`.

Thoughts?

/cc @FezVrasta

**Comment by FezVrasta** [comment]
angular-material has 16px as font root
material design lite has 13px
polymer has 14px

It seems a far west to me, so I'd stick with the default size used by Bootstrap.

**Comment by rosskevin** [comment]
Ok, I'm sticking with 16 as the root.
