### ISSUE TITLE
Bootstrap Material Design should not be intervening regarding validation.

### ISSUE THREAD

**Issue by ccjmne** [mdbootstrap/mdb-ui-kit#826]
Here's a [CodePen](http://codepen.io/anon/pen/ZQXXeB) using AngularJS to validate a user input, and Bootstrap Material Design for the styling.

I am dynamically updating the `class` of my `form-group` according to a simple rule: if the input string's length is **even**, the input is **valid**, otherwise, it's **invalid**.

As you can see, the input is either **accepted** (bright green) or **neutral** (the green using as the primary colour in BMD): when it should be **red**, the error-like status only ticks for an instant before being cleared.
Removing the JS dependency to [https://rawgit.com/FezVrasta/bootstrap-material-design/master/dist/js/material.js](https://rawgit.com/FezVrasta/bootstrap-material-design/master/dist/js/material.js) fixes the issue.

Something stuck me while having a quick glimpse at `material.js`'s source:

``` javascript
// Validation events do not bubble, so they must be attached directly to the input: http://jsfiddle.net/PEpRM/1/
//  Further, even the bind method is being caught, but since we are already calling #checkValidity here, just alter
//  the form-group on change.
//
// NOTE: I'm not sure we should be intervening regarding validation, this seems better as a README and snippet of code.
//        BUT, I've left it here for backwards compatibility.
if (validate) {
  if (isValid) {
    $formGroup.removeClass("has-error");
  }
  else {
    $formGroup.addClass("has-error");
  }
}
```

And indeed, getting rid of this piece of code solves my problem.
I don't actually see why we should keep this, and would suggest getting rid of it unless otherwise necessary.

**Comment by rosskevin** [comment]
You can initialize with validate: false. 

Please let me know if this doesn't solve your problem.

**Comment by ccjmne** [comment]
Problem fixed by initializing with `validate: false`... :+1: 

Thank you!

**Comment by morelazers** [comment]
I'm having the same issue, but I'm not using angular. How do I make sure that bmd isn't validating a field for me? I would only like to remove the validation from a single element if possible.
