### ISSUE TITLE
Selectize dropdown chevron does not render

### ISSUE THREAD

**Issue by mikevic** [mdbootstrap/mdb-ui-kit#827]
I'm using selectize with the bootstrap-material-design and it looks like the dropdown arrow does not render correctly.

![screen shot 2016-01-17 at 1 42 50 am](https://cloud.githubusercontent.com/assets/1719146/12374253/a5407c8e-bcbb-11e5-99f6-cfbf8f566542.png)

**Comment by rosskevin** [comment]
Please create the requested test case: https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md

**Comment by rosskevin** [comment]
This has not been converted to use the new material icon font.  I need someone that uses this plugin to  submit a PR.

**Comment by mikevic** [comment]
@rosskevin, I'm a bit new to this, but I'm definitely keen on fixing this issue!

So I'm guessing I need to change the font from 'Material-Design-Icons' to ''Roboto', 'Helvetica', 'Arial', sans-serif !default;' right?

However, when I do this -- the dropdown chevron disappears like so - 

![screen shot 2016-01-20 at 10 44 53 am](https://cloud.githubusercontent.com/assets/1719146/12440570/e98b7ef8-bf62-11e5-9ecf-4017187f04d9.png)

Please advice, thanks!

**Comment by rosskevin** [comment]
I just remembered I did this for the dropdown plugin.  

Check out this code, it should help: https://github.com/FezVrasta/bootstrap-material-design/blob/master/less/plugins/_plugin-dropdownjs.less#L7

Test it out and submit a PR and we'll get it merged.  Thank you
