### ISSUE TITLE
dropdown-menu divider not visible

### ISSUE THREAD

**Issue by roccomuso** [mdbootstrap/mdb-ui-kit#828]
I'm on Chrome latest version. I don't know if materials principle dictates an invisble dropdown-menu divider, but I'd darken it: changing color or increasing his alpha value.

![invisible divider](http://i.giphy.com/3oFyCWpGPDQa8HK0hy.gif)

**Comment by rosskevin** [comment]
in v4 cards we are using  `1px solid rgba(0, 0, 0, .12);` for the footer divider, it seems to work well on multi-color backgrounds.
