### ISSUE TITLE
Dropdown-menu clipped when inside card-content (-webkit-column)

### ISSUE THREAD

**Issue by roccomuso** [mdbootstrap/mdb-ui-kit#829]
As you can see, if you toggle the dropdown-menu, it's clipped.
http://codepen.io/anon/pen/NxwEEj

Not sure if this is related to the bootstrap-material itself or a CSS3 column bug not fixed yet:
https://code.google.com/p/chromium/issues/detail?id=84030

The <code>overflow: visible</code> assignement seems not to work.

**Comment by rosskevin** [comment]
Honestly I'm not sure, I just solved this issue in v4 and it was a problem with `overflow:hidden` though I don't see it in this example.  Given that cards are all new in BS4 and I'm focusing on that, I'll need someone to submit a PR for this one.

**Comment by roccomuso** [comment]
You solved it in v4 using -webkit-column?

**Comment by rosskevin** [comment]
No,  this issue presented the same way, and I removed overflow: hidden which allowed the dropdown to overlay another element.  It doesn't appear to apply here.
