### ISSUE TITLE
selectize wrap

### ISSUE THREAD

**Issue by cncolder** [mdbootstrap/mdb-ui-kit#83]
selectize style is fixed height and line-height.
if total width is large than container. first line should move up and invisible.

selected items more than one line. the first line invisible.

![2014-10-04 16 07 34](https://cloud.githubusercontent.com/assets/127009/4514974/fcd5a64e-4b9d-11e4-8cf7-dfdaec4828c3.png)

adjust height, in fact i have select many tags.

![2014-10-04 16 10 23](https://cloud.githubusercontent.com/assets/127009/4514975/fece8786-4b9d-11e4-93da-7d07cc4d236f.png)

**Comment by FezVrasta** [comment]
Not sure about how this element should behave in this situation... Will do some research.

**Comment by FezVrasta** [comment]
fix for this problem is welcome but it's not a priority, once I'll find some free time I'll write a replacement for selectize.js (it's really too heavy and not user friendly). I'll write the new one with this bug in mind.

**Comment by FezVrasta** [comment]
the replacemente is in place, it's [dropdown.js](https://github.com/fezvrasta/dropdown.js).

It has not all the features of Selectize.js but they will be added soon. This plugin is made to be **lightweight** and **customizable**.
