### ISSUE TITLE
JHipster validation compatibility

### ISSUE THREAD

**Issue by steviemo** [mdbootstrap/mdb-ui-kit#830]
Hi folks,
Using material design 0.5.7, bootstrap 3.3.6 with JHipster 2.26.2.

I'm getting a couple of errors especially around validation messages:

For example view registration form:
Enter invalid password - errors message overlays on top of the password strength indicator.
Enter invalid email such as 'test' - Multiple validation messages complaining about invalid email and invalid length overlay each other.

Any ideas if some tweaks should be made to any JHipster artefacts - I already had to tweak the navbar.html updating the dropdown menus to support material design.

**Comment by rosskevin** [comment]
Initialize with validate: false.

**Comment by eredwan** [comment]
@rosskevin Where do I initialize this?

I'm seeing line 58 in material.js. Doesn't seem to fix this problem that steviemo is talking about

**Comment by rosskevin** [comment]
`$.material.init({validate:  false})` turns off any validation performed by this project.  Beyond that,  any other problems with validation are not in the scope of this project.

**Comment by eredwan** [comment]
Ya... that's the same as changing line 58 in material.js to false.

**Comment by rosskevin** [comment]
If validation for this project is turned off, then it is not a problem with this project.  Correct?

If not, we need a test case as requested:
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#tldr-create-a-test-case-using-this-codepen-template-when-submitting-an-issue
