### ISSUE TITLE
Checkbox tabindex dosen't work

### ISSUE THREAD

**Issue by jumpitup82** [mdbootstrap/mdb-ui-kit#833]
I adjust bootstrap-materina in my project but checkbox tabindex does not work.
and I found event code to blur when checkbox has changed

[material.js 171~173]
.on("change", ".checkbox input[type=checkbox]", function () {
          $(this).blur();
        })

when I remove this event, tabindex works appropriately. I couldn't understand why this code block contain.

**Comment by rosskevin** [comment]
@fezvrasta can you comment on why this line exists?  I can't think of a reason.

**Comment by FezVrasta** [comment]
It was there to prevent the checkbox from staying highlighted after the click.

Recently on my private projects I've switched to ["What Input?"](https://github.com/ten1seven/what-input) to style correctly the input elements on focus. We may want to use the same plugin here?

**Comment by rosskevin** [comment]
@jumpitup82 please submit a test case.  

https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#tldr-create-a-test-case-using-this-codepen-template-when-submitting-an-issue

**Comment by rosskevin** [comment]
@jumpitup82 - we can't do everything for everyone - and need your help.  It's our policy to close issues without test cases that haven't affected others.  

If you submit a test case, we'll reopen it.
