### ISSUE TITLE
Help: How to do header waterfall

### ISSUE THREAD

**Issue by mmacedoeu** [mdbootstrap/mdb-ui-kit#835]
I'm looking into this waterfall mode:
https://elements.polymer-project.org/elements/paper-header-panel?view=demo:demo/index.html&active=paper-header-panel

Is it possible ? How ?

**Comment by rosskevin** [comment]
This question is probably best asked on StackOverflow.  Since bootstrap does all the layout, I would suggest asking "how to do a waterfall navbar with bootstrap".

Off the top, I would simply suggest multiple navbars, that may get you what you want.
