### ISSUE TITLE
Material-Colors

### ISSUE THREAD

**Issue by aul12** [mdbootstrap/mdb-ui-kit#836]
Is the option to choose a material color gone? It is still listed in the Readme but not on the website.
Is there a new way to style a navbar (currently i use navbar-material-blue)?

**Comment by aul12** [comment]
I don't know if they relate to each other but chromium shows an error: "/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details." on every page refresh.

**Comment by rosskevin** [comment]
What is listed in the readme that is not on the demo site?

I only see where it lists the color swatches and how to customize:
https://github.com/FezVrasta/bootstrap-material-design#colors

See #740
