### ISSUE TITLE
v4 Exception on hidden inputs

### ISSUE THREAD

**Issue by pinx** [mdbootstrap/mdb-ui-kit#838]
Phoenix/Elixir (and other frameworks) inject hidden inputs. I get this error:
Failed to instantiate component: $('input[type!='checkbox'][type!='radio'][type!='file']')[mdbText]([object Object]) Error: Text element: <input name="_method" type="hidden" value="delete"> requires class: form-control
Do we need a css class on hidden inputs? I'm not sure if that is easy to fix in Phoenix.

**Comment by rosskevin** [comment]
I would say it should omit hidden in that style/structure validation selector.

**Comment by rosskevin** [comment]
It actually should probably change the selector in the `bootstrapMaterialDesign.js` file, you can try altering the selector by passing in the altered selector, and let me know if it works.

**Comment by rosskevin** [comment]
I added it.

**Comment by pinx** [comment]
OK, great! thanks
