### ISSUE TITLE
why not add more entry to "main" in package.json

### ISSUE THREAD

**Issue by cgcgbcbc** [mdbootstrap/mdb-ui-kit#84]
According to [Getting Started](https://github.com/FezVrasta/bootstrap-material-design#getting-started), in fact we need `scripts/ripples.js`,`scripts/material.js`,`css-compiled/material.css`,`css-compiled/material-wfont.css`,`css-compiled/ripples` instead of simply `css-compiled/material.css` in bower.json.
 Adding them all to "main" will help those use [grunt-wiredep](https://github.com/stephenplusplus/grunt-wiredep)

**Comment by FezVrasta** [comment]
fixed with 47b9330b3005e5a389fc3325d42493a69d88a8fd

I've added just the two files really needed to make the theme work: material.js and material.css, the other files are optional.
