### ISSUE TITLE
v4 wrong documentation for NPM installation

### ISSUE THREAD

**Issue by gabrielenosso** [mdbootstrap/mdb-ui-kit#841]
At the page http://rosskevin.github.io/bootstrap-material-design/getting-started/download/ the NPM installation command is wrong.

It is now

```
npm install bootstrap@4.0.0-prealpha
```

Isn't it the bootstrap package?

Maybe it's just there cause there are no NPM packages for that?

**Comment by rosskevin** [comment]
We don't have a published npm package for v4 yet, I would point to `FezVrasta/bootstrap-material-design#v4-dev` for now.  But this is a bug that I will fix.
