### ISSUE TITLE
v4 new input underline decoration

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#842]
I've noticed that in the V4 version you are using the old method to add the underline decoration to the input elements.

I'm not sure if I had already applied the new method I've prepared on the v3, by the way here there's a codepen:

http://codepen.io/FezVrasta/pen/wBeQyr?editors=1100

The advantages are that you don't need any additional element or pseudo element to add the effect, it has a good cross browser compatibility also.

**Comment by rosskevin** [comment]
Yes, that would have been nice to have to try when I was integrating.  

With that said, I think this solution is incompatible with BS4 validation icons.  See [this example](http://rosskevin.github.io/bootstrap-material-design/components/forms/#validation)

```
.has-success .form-control-success {
    background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zd…43IDU4LjhMMjcwIDU5MGMtNy40IDEyLTIwLjIgMTkuNC0zNC4zIDIwaC0yeiIvPjwvc3ZnPg==);
}
```

While this isn't necessarily a _must have_ feature of BS4, I didn't want to omit it without reason.

I have spent a bunch of time getting the current solution to work given the change in the way BS4 does it's success/failure indicators in the background (which is different than BS3).  Our V3 background solution caused default BS4 to break.  I also examined several other implementations, and while we do add an element, the affect does appear to be compatible and widely used.

If you would like to put BS4 as a baseline stylesheet for this and redo the codepen, I would like to take another look at this. Please try one with the validation.

**Comment by FezVrasta** [comment]
I think it should be trivial to support the validation icons of BS4, you have just to append the background-image used by BS4 at the end of the `background-image:` list of bgs.
I already do something similar to add the dropdown arrow to the `select` elements styled with the codepen I've provided.

Does it make sense?

**Comment by rosskevin** [comment]
Ah, that's a trick I couldn't find (and I actually looked for it).  Must be bad googling on my part. 

I definitely agree this is a better solution. 

With that said I'd rather not have all the work shifted over to me to turn this prototype into a solution when the current solution works.  

If this was a codepen that used either MDB or BS4 as the basis (and preferably SCSS), then I wouldn't mind integrating the rest of the way

**Comment by FezVrasta** [comment]
I've added a demo to show the `select` support.

I could port it to SCSS and BS4 when I find some free time.

**Comment by FezVrasta** [comment]
@rosskevin may you point me to the BS4 source file where I can find the snippet you have shown me here? https://github.com/FezVrasta/bootstrap-material-design/issues/842#issuecomment-175062277

**Comment by rosskevin** [comment]
Great.  I haven't put together a new codepen, I'll put that on the list now that I'm committing the dist.  There's a new way to disable individual behaviors with js, so I'll try to get that together for you.

BS code is here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_forms.scss#L259

**Comment by FezVrasta** [comment]
Ah great, they already use a variable for the icon, so we can just prepend our "underline" variable before it and it's done

**Comment by rosskevin** [comment]
Sweet, I'll have a codepen for you in a moment #844

**Comment by rosskevin** [comment]
Here's the v4 template:
http://codepen.io/rosskevin/pen/eJMMVB

Here's one that disables the text and select js plugins:
http://codepen.io/anon/pen/qboYEy

Disabling them means you don't have to deal with the added underline decorator element, but not it disables floating labels etc, but those aren't necessary for your prototype.

**Comment by FezVrasta** [comment]
Here your prototype based on your codepen and written in SASS

http://codepen.io/FezVrasta/pen/BjrxJz?editors=1100

I'm sorry but I've not time to prepare a PR, I hope this is enough to get you started.

**Comment by rosskevin** [comment]
This is good.  I just altered dist into it's own branch and changed the codepen, so yours will stop working when the cache cycles.  This has update urls:

http://codepen.io/rosskevin/pen/zrWLMd?editors=1100

**Comment by rosskevin** [comment]
Integrated and deployed, here's the temp test page (these are examples elsewhere in the docs):
http://rosskevin.github.io/bootstrap-material-design/material-design/test/

The only thing I had to change was the `repeat-y`.  I see the note that it was bugged in safari, but it was even worse for size variations so I decided the best mitigation at this point is to let safari blink on animation out, it's a better tradeoff than random cutoff repeats.

**Comment by FezVrasta** [comment]
Seems like the inputs have a background color, they should just be transparent instead.

![image](https://cloud.githubusercontent.com/assets/5382443/12594522/d198a6b8-c476-11e5-9ac4-c8a17179da87.png)

**Comment by rosskevin** [comment]
Where did you get that snapshot? the bg color I have is transparent.

Oh, that's a documentation thing.  I'll override their styles.

**Comment by rosskevin** [comment]
published
