### ISSUE TITLE
Select styling

### ISSUE THREAD

**Issue by hecbuma** [mdbootstrap/mdb-ui-kit#848]
I need to know if I'm missing something with the select. Right now looks good BUT doesn't look like fully material design, the chevron is missing and some styling as well. 

Can you point me in the right direction?

<img width="592" alt="screen shot 2016-01-27 at 12 21 58 pm" src="https://cloud.githubusercontent.com/assets/363669/12623630/a94dc6c8-c4f0-11e5-9bdd-e42ccfb1d6ff.png">

**Comment by rosskevin** [comment]
I'm guessing you are looking for the dropdown plugin styling:

http://fezvrasta.github.io/bootstrap-material-design/#dropdown-menu

**Comment by hecbuma** [comment]
yes, I don't quite get how to make it work thought

**Comment by rosskevin** [comment]
For general development support, please use StackOverflow - a much bigger community that can help you.  You can point to the link above and ask for "how to" help there.  Thank you

https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md
