### ISSUE TITLE
V4: Checkboxes are not rounded

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#851]
![image](https://cloud.githubusercontent.com/assets/5382443/12674776/c424cdca-c685-11e5-8ef1-1566dfe17b7f.png)

Is it wanted? I remember Material Design specs says that Checkboxes should have rounded corners.

**Comment by rosskevin** [comment]
I haven't seen that,  can you point to the spec or guidelines for it? 

I don't think I have any personal preference, I would just follow spec.

**Comment by FezVrasta** [comment]
![image](https://cloud.githubusercontent.com/assets/5382443/12678198/e9a46052-c69d-11e5-8db8-229efe75942b.png)

from the guidelines

**Comment by rosskevin** [comment]
Bug in the scss.  Here's the spec pointer: http://www.google.com/design/spec/components/selection-controls.html#selection-controls-checkbox

**Comment by rosskevin** [comment]
published
http://rosskevin.github.io/bootstrap-material-design/components/forms/#checkboxes-and-radios
