### ISSUE TITLE
v3 Checkbox does not render in an ng-repeat loop with Angular JS

### ISSUE THREAD

**Issue by raz3r** [mdbootstrap/mdb-ui-kit#852]
Tested with Angular 1.4.9 and Bootstrap Material 0.5.7.

`<div ng-repeat="phone in currentUser.phones">`
`<div class="form-group" style="margin-top:0px;">`
`<div class="togglebutton">`
`<label>`
`<input ng-model="phone.secret" type="checkbox"> Secret Number`
`</label>`
`</div>`
`</div>`
`</div>`

Checkboxes inside ng-repeat are not rendered correctly as you can see [here](http://i.imgur.com/AnPKsHO.png).

**Comment by FezVrasta** [comment]
Please follow the [contributing guidelines](https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md).

Issues without a codepen demo get closed.
