### ISSUE TITLE
v4 file browser implementation

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#854]
It looks like the BS v4 implementation has settled in.  We need to re-enable our file component in `bootstrapMaterialDesign.js` and get our old implementation/functionality integrated.

**Comment by FezVrasta** [comment]
![image](https://cloud.githubusercontent.com/assets/5382443/17289821/b0d5cf34-57db-11e6-9b02-474fec217707.png)
![image](https://cloud.githubusercontent.com/assets/5382443/17289826/b4e7fe44-57db-11e6-93ea-f74bc1fb681e.png)
![image](https://cloud.githubusercontent.com/assets/5382443/17289849/c8261360-57db-11e6-8508-b6cc82b095c1.png)

Nothing special but at least it's styled. Feedbacks?
https://github.com/FezVrasta/bootstrap-material-design/commit/88d703e09dc56ab3d471612d6bd5cc69d601fbd2

Re-open it if there's something wrong please!
