### ISSUE TITLE
v4 enhance ripples.js to accomodate radio/checkbox

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#855]
Currently, radio ripple effect is off-centered.  
See http://rosskevin.github.io/bootstrap-material-design/components/forms/#checkboxes-and-radios

Perhaps the best path forward is to drop the custom one-off styling of ripples for radio/checkbox and get ripples.js to support them.

**Comment by FezVrasta** [comment]
Consider that the specs say that the ripple effect should be visible only on touch screen devices. I'm not sure it's worth spending time on it, I would drop it.

**Comment by rosskevin** [comment]
I'd like to make it optional either:
1. responsive; or 
2. variable enabled; or
3. variable enabled + responsive

My personal preference is 3, making it available on touch devices.

**Comment by FezVrasta** [comment]
I think the best way would be to extend ripples.js to support such elements.

In this way all the ripples would be managed the same way and you don't have to care about such problems.

**Comment by rosskevin** [comment]
Which `ripples.js` are you referring to? Ours or an external project?

**Comment by FezVrasta** [comment]
our

**Comment by rosskevin** [comment]
lol, now that you point it out I just realized that js component doesn't have anything to do with those selection components.

**Comment by FezVrasta** [comment]
@rosskevin  If you want to replace the radios and checkboxes components with the one I've provided [some week ago](https://github.com/FezVrasta/bootstrap-material-design/issues/743) I would be more than happy to work on ripple.js to allow it to cast ripples to all our components.

**Comment by rosskevin** [comment]
For the checkbox, I need a different svg: https://github.com/FezVrasta/bootstrap-material-design/issues/808

I believe I already integrated the radio (though I'm not sure why I didn't link a commit to it).  During that process I believe I reviewed a few other implementations as well.

**Comment by FezVrasta** [comment]
The radio seems the old one, in fact there's the ripple effect on click.

About the SVG, I've missed it. I'll fix it soon.

**Comment by rosskevin** [comment]
I recall with the radio that I reviewed it and other implementations. I didn't want to throw out the ripple, but you can easily do so by deleting the `&::after` and `@keyframes`.  Aside from the ripples, I don't see an advantage to your radio prototype over the current implementation.  If you let me know advantages I can look again.

**Comment by FezVrasta** [comment]
I'm working on it right now, this is allowing us to reduce the complexity of the ripples and make them configurable. :tada:
