### ISSUE TITLE
Sass compile error

### ISSUE THREAD

**Issue by appkr** [mdbootstrap/mdb-ui-kit#859]
During the gulp build, I encountered the following error message.

``` bash
Error in plugin 'sass'
Message:
    _assets/vendor/bootstrap-material-design/sass/_import-bs-sass.scss
Error: File to import not found or unreadable: bootstrap/variables
       Parent style sheet: /Users/***/workspace/blog/_assets/vendor/bootstrap-material-design/sass/_import-bs-sass.scss
        on line 1 of _assets/vendor/bootstrap-material-design/sass/_import-bs-sass.scss
>> @import "bootstrap/variables";
   ^
```

When I change the @import statement to the following it works fine.

``` css
// bootstrap-material-design/sass/_import-bs-sass.scss
@import "variables";
```

**Comment by appkr** [comment]
Sorry~ Still have error... I will re-post after studying more.

**Comment by rosskevin** [comment]
Add bower or node as you include path, check our gruntfile.

**Comment by loranger** [comment]
Can you please provide a example or give any clue ?

I tried to use the sass version with laravel elixir but always got this error message, even if I declare an includePath :

`gulpfile.js :`

``` javascript
elixir(function(mix) {
    mix.sass('app.scss', null, {includePaths: ['../../../node_modules/bootstrap-sass/assets/stylesheets/']});
});
```

`app.scss :`

``` sass
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";
@import "node_modules/bootstrap-material-design/sass/bootstrap-material-design.scss";

```

`output :`

```
Sass Compilation Failed: node_modules/bootstrap-material-design/sass/_import-bs-sass.scss
Error: File to import not found or unreadable: bootstrap/variables
       Parent style sheet: /Users/loranger/Developer/work/phoenixcorp/respawn/dactylifera/node_modules/bootstrap-material-design/sass/_import-bs-sass.scss
        on line 1 of node_modules/bootstrap-material-design/sass/_import-bs-sass.scss
>> @import "bootstrap/variables";
   ^
```

**Comment by rosskevin** [comment]
@loranger your includePaths should be base paths, not paths into a project.  i.e. path to `node_modules`

**Comment by rosskevin** [comment]
With that said, I'm working on an integration with v4 and having nested inclusion errors #874.  It may not be identical but seems related.

**Comment by w0ng** [comment]
To clarify @loranger's problem, the issue occurs when compiling sass when using [Laravel Elixir](https://laravel.com/docs/master/elixir) (a gulp wrapper). 

Laravel projects are structured:

```
.
├── gulpfile.js
├── node_modules
│   ├── bootstrap-material-design
│   │   ├── bower_components
│   │   │   ├── bootstrap
│   │   │   │   ├── assets
│   │   │   │   │   └── stylesheets
│   │   │   │   │       └── bootstrap
│   │   │   │   │           ├── _variables.scss
│   │   ├── sass
│   │   │   ├── _import-bs-sass.scss
│   │   │   ├── bootstrap-material-design.scss
├── resources
│   ├── assets
│   │   └── sass
│   │       └── app.scss
```

A [typical workflow](https://laravel-news.com/2015/10/setup-bootstrap-sass-with-laravel-elixir/) is to combine the npm packages with imports in app.scss before compiling with gulp.

An [alternative workflow](https://laravel-news.com/2014/10/setting-laravel-elixr-bootstrap/) is to do all the imports directly in the gulpfile.js, which works, but becomes a mess and a management pain when installing multiple packages.

Ideally I would like e83b411d75a8b0b8f0d6163d6a8f9781bd80db7b to be reverted, given there's only one external file being imported in sass, but I'm not smart enough to know whether the includepath in gulpfile should be kept, or whether this is a problem specific to Laravel + Elixir.

**Comment by appkr** [comment]
EDIT. I don't remember what I did to make it work, but it's working now.

Here is the master scss file.

``` css
// app.scss
// Not Laravel, but Jekyll project though~ for full code
// @see https://github.com/appkr/blog/blob/master/_assets/styles/main.scss
// @see https://github.com/appkr/blog/blob/master/gulpfile.babel.js

@charset "utf-8";

@import "../vendor/bootstrap-sass/assets/stylesheets/bootstrap";
@import "../vendor/bootstrap-material-design/sass/bootstrap-material-design";
@import "../vendor/bootstrap-material-design/sass/ripples";

// ...
```

**Comment by loranger** [comment]
So what I understand from @w0ng is bootstrap-material-design cannot be used anymore with laravel elixir. Ok I'll wait, then.
Thanks everyone

**Comment by rosskevin** [comment]
@loranger My previous guidance on the base path was wrong, I had v4 in mind.

It should work, just because you are using laravel or whatever, it appears to be ultimately using node-sass/libsass.

Be sure that you use a fully qualified pathname to the basepath, I used [`findup`](https://github.com/alienfast/gulp-pipeline/blob/master/src/sass.js#L33) to get this form me in an environment agnostic way.

Try this:

``` javascript
var findup = require('findup-sync')
elixir(function(mix) {
    mix.sass('app.scss', null, {includePaths: [findup('node_modules/bootstrap-sass/assets/stylesheets/')]});
});
```

**Comment by rosskevin** [comment]
BTW - we cannot reverse the commit because not everyone uses bower and the old code had a hard path.

**Comment by rosskevin** [comment]
ONE more thing, if you are using ruby-sass instead of libsass, you need to use:

`loadPath: "bower_components/bootstrap-sass/assets/stylesheets"` instead of `includePaths`

In v4, we use libsass exclusively (much faster)

**Comment by dikiaap** [comment]
some problem like you @appkr 

if I use less file, all is work fine.

**Comment by Poggen** [comment]
Exactly how did you get this working, @appkr? The style part of my gulpfile looks like this:

```
    .pipe(function() {
      return gulpif('*.scss', sass({
        outputStyle: 'nested', // libsass doesn't support expanded yet
        precision: 10,
        includePaths: [
          '.',
          '../../bower_components/bootstrap-sass/assets/stylesheets/'
        ],
        errLogToConsole: !enabled.failStyleTask
      }));
    })
```

I added another `includePaths` like suggested earlier in this thread.
My main.scss looks like this:

```
// Needs to be imported first
@import "common/variables";

// Automatically injected Bower dependencies via wiredep (never manually edit this block)
// bower:scss
@import "../../bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss";
@import "../../bower_components/bootstrap-material-design/sass/bootstrap-material-design.scss";
@import "../../bower_components/bootstrap-material-design/sass/ripples.scss";
// endbower

// My own styles start here
@import "common/global";
[...]
```

But it still fails when trying to import `bootstrap/variables` from `_import-bs-sass.scss`.

**Comment by appkr** [comment]
@Poggen God, I don't remember~ I think I made a correction on the original framework files. Not a good way though.. have you tried commenting out all declaration in `_import-bs-sass.scss`? Or comment out whichever makes the problem. Sorry, I was not much helpful~

**Comment by vedmant** [comment]
If you use Compass, add `additional_import_paths = "node_modules/bootstrap-sass/assets/stylesheets"` to config.rb file.

**Comment by FaheemAlam** [comment]
I am having the same issue. Does any one have a solution for this?

**Comment by NathanQ** [comment]
# 2 Fixes:

Hope this will help the next person.

## 1: Quick fix

1. In the file, `bootstrap-material-design/sass/_variables.scss`, delete the line `@import 'import-bs-sass';` because bootstrap imports it and importing it again seems duplicative.

## 2: Fix according to the error

1. Reread the error and think about what it says.
2. Open the `bootstrap-material-design/sass/_import-bs-sass.scss` and read the line that it contains. Oh! It doesn't point at where I have my bootstrap variables file! It needs to go two directories up to get out of the `bootstrap-material-design` directory then to the location of the bootstrap variables file.
3. Find the file it's trying to import in your project. Hint: Maybe your project isn't set up the same as everyone else.
4. Change the `bootstrap-material-design/sass/_import-bs-sass.scss` line `@import "bootstrap/variables";` to point to the bootstrap variables file.

**Comment by FezVrasta** [comment]
Or simpler, read the README and add the `loadPath` as described:
https://github.com/FezVrasta/bootstrap-material-design#bower

**Comment by NathanQ** [comment]
@FezVrasta good point. ;) But, but I didn't use bower... Love this project and thanks for putting it together.

**Comment by FezVrasta** [comment]
Feel free to send a PR to make it more clear.

**Comment by ferencbalogh** [comment]
My solution:

Install remove line
```
npm install --save gulp-remove-line
```

Add to gulpfile header

```
var require("gulp-remove-line");
```

Copy files to destination and remove line from _variables.scss

```
/* Bootstrap Material */
  gulp.src("vendor/bower/bootstrap-material-design/sass/**")
    .pipe( removeLine( { "_variables.scss": [42]} ) )
    .pipe(gulp.dest("resources/assets/sass/bootstrap-material-design/"));
```

Enjoy gulp working without problems.

**Comment by burakguneli** [comment]
unfortunately none of them worked for me but if you are still having this problem, you can try deleting node_modules and run `npm install` again. It worked for me
