### ISSUE TITLE
sass easy

### ISSUE THREAD

**Issue by demiantriebl** [mdbootstrap/mdb-ui-kit#861]
hi!, i try to install with bower but i have a problem, i can't initialize for two problems
1) docs are conflict for the header, i delete this
2) the jquery dependence don't function, i have this folder, and this packages, but the proyect can link that.

i only need the sass for personalization, any help?

**Comment by rosskevin** [comment]
I'm sorry, I do not understand what you are trying to communicate.  Others are successfully using it so I would suggest that there isn't a problem with this project, but a problem with your setup and help with such a thing is much better served by StackOverflow.

Here are the relevant docs:
- [Getting started](https://github.com/FezVrasta/bootstrap-material-design#getting-started)
- [Using bower](https://github.com/FezVrasta/bootstrap-material-design#bower)

Please try StackOverlow.
