### ISSUE TITLE
How to add background Icon to the inputs

### ISSUE THREAD

**Issue by rohitbind** [mdbootstrap/mdb-ui-kit#862]
How can I add a in the background of any input element. I think it dont allow you to do so.

**Comment by rosskevin** [comment]
Please ask general css development questions on stackoverflow.

**Comment by rohitbind** [comment]
Dear Kevin, I know how to do it. bootstrap-material-design is not allowing me to do the same in its input element. Can you open the issue again.

**Comment by rosskevin** [comment]
You have not followed the contributing guidelines and you are reminded to do so when submitting issues.  I will not leave open issues that fail to follow them.

**Comment by rohitbind** [comment]
Ok Kevin, Sorry for not following the guidelines. I will follow the guideline and post the issue again.
