### ISSUE TITLE
Background Icon or image is not working

### ISSUE THREAD

**Issue by rohitbind** [mdbootstrap/mdb-ui-kit#863]
I am not sure if it is an issue, but just now I found that FezVrasta/bootstrap-material-design dont accept background icons or images to its form input elements. I think its because of following code.

`.form-group .material:focus, .form-group-default .material:focus {
    background-image: linear-gradient(#48196D, #48196D), linear-gradient(#48196D, #48196D) !important;
}`

This is normal Bootstrap, Here its working
http://codepen.io/rohitbind/pen/gPdPBq

This is FezVrasta/bootstrap-material-design, Here its not working
http://codepen.io/rohitbind/pen/PZdZOx

**Comment by FezVrasta** [comment]
This is relevant:

https://github.com/FezVrasta/bootstrap-material-design/issues/842

**Comment by rosskevin** [comment]
@FezVrasta beat me to it.

@rohitbind - Federico in the linked issue shows how to use two bg images with an input.  Here is my commit:
https://github.com/FezVrasta/bootstrap-material-design/commit/86f2a21154859f50f78f98a266a93fcb1146b32e

Specifically:
https://github.com/FezVrasta/bootstrap-material-design/blob/v4-dev/scss/mixins/_forms.scss#L244

This shows:
1. underline bg image
2. validation icon bg image (to the right)

Here is the working example with two bg images:
http://rosskevin.github.io/bootstrap-material-design/components/forms/#validation

**Comment by rosskevin** [comment]
So @rohitbind - this looks like a customization of MDB for your purposes.  We've shown you how.  As an FYI - we chose the bg image method for underlining because it is the most compatible and has the least side effects.  While it makes doing what you want harder (but still possible), for most cases it is advantageous to have the bg image implementation for focus.

**Comment by rohitbind** [comment]
Thanks Kevin and Fernando

**Comment by FezVrasta** [comment]
Federico, lol

**Comment by rohitbind** [comment]
Federico sorry LOL
