### ISSUE TITLE
Checkbox does not render in an ng-repeat loop with Angular JS

### ISSUE THREAD

**Issue by raz3r** [mdbootstrap/mdb-ui-kit#867]
First of all, sorry because my last submit was closed due to a missing codepen example.

Take a look at this codepen:

http://codepen.io/anon/pen/EPdymr

Checkboxes are rendered correctly on page load. Later though the $scope.shareList array is populated with an HTTP request and that's when checkboxes are not rendered anymore. In the codepen example I simulated that with a timeout.

Notice that the issue occurs both with 0.5.7 and 0.3.0 version. If there's a way to fake a POST request on codepen

**Comment by FezVrasta** [comment]
You are not including [Arrive.js](https://github.com/uzairfarooq/arrive) which is the one that takes care to initialize dynamically added elements.

https://github.com/FezVrasta/bootstrap-material-design#arrivejs-support
