### ISSUE TITLE
When btn-group-vertical has only one button, doesn't style the same as a button group

### ISSUE THREAD

**Issue by jpafable** [mdbootstrap/mdb-ui-kit#873]
This sounds like a bit weird, but I'm using a dynamic button group.  In one of the cases, if there is only one button, it is formatted like the default icon

http://codepen.io/anon/pen/MKZgbY

**Comment by rosskevin** [comment]
1. Are you intending to use two round fab buttons in a group? 
2. Are you aware that except for dynamic pop up fab action sets,  you should only display one fab at a time?

**Comment by jpafable** [comment]
1. I am intending to use the current style applied for a "fab group" to minimize screen estate.  Instead of using the btn-raised attribute that would have more unneeded space around the icon.  So, I was expecting using the same grouping style for one button.
2. I was heavily relying on your work, and I have overlooked that.

**Comment by rosskevin** [comment]
> Only one floating action button is recommended per screen to increase its prominence. It should represent only the most common action.

https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button

You may be interested in something I implemented for V4 called the [`mdb-btn-icon`](http://rosskevin.github.io/bootstrap-material-design/material-design/buttons/#icon).  I think it is probably what you are looking for.  You can look at the implementation in the v4-dev branch.
