### ISSUE TITLE
Unnecessary top margin for input groups in inline forms

### ISSUE THREAD

**Issue by MJafarMashhadi** [mdbootstrap/mdb-ui-kit#875]
Input groups should not have top margin when used in an inline form. 
Check original [bootstrap](http://getbootstrap.com/css/#forms-inline) or simply remove bootstrap material design from [this codepen](http://codepen.io/anon/pen/obJQqJ)

**Comment by rosskevin** [comment]
Note that your sample wouldn't pass bootlint i.e. there is no such class as `from-control`

My codepen shows it with a floating label, we need this margin to accomodate both labels and help texts:
http://codepen.io/rosskevin/pen/gPZZbr

While some margin could be removed, that is easily overridden with your stylesheet and I don't think this warrants an adjustment.

**Comment by MJafarMashhadi** [comment]
`form-control` is used in bootstrap's [own example](http://getbootstrap.com/css/#forms-inline)
However, in "inline" form, having floating label on top of the input doesn't make sense. floating label makes the height too big and misses the main point of using an inline form.

**Comment by rosskevin** [comment]
1.  You either did not read or understand what I wrote.  You used `from-control` which is invalid.  The correct class is `form-control`.
2.  Floating labels are valid for inline forms, it is a matter of a design choice.
3.  Static labels are also valid for inline forms, and they render exactly like a focused floating label
4.  You can do **anything you want**, you can shrink the size by overriding the CSS, but this is not a bug.
