### ISSUE TITLE
Changing a readonly form input value using jQuery does not update the floating label attribute

### ISSUE THREAD

**Issue by jpafable** [mdbootstrap/mdb-ui-kit#876]
When I try to change a readonly textfield using jquery, the label for the textfield doesn't get updated.
http://codepen.io/anon/pen/xZMbRe

**Comment by rosskevin** [comment]
You must `trigger('change')` otherwise the field knows nothing about it.  These field operate on focus and blur.

http://codepen.io/rosskevin/pen/vLbKmv
