### ISSUE TITLE
Question: how much of the project does not use JS

### ISSUE THREAD

**Issue by simonh1000** [mdbootstrap/mdb-ui-kit#877]
I am looking for a material design library to use in an Elm project and therefore want to avoid using the JS libraries. I know I will lose a lot in the process, but I don't need every feature - mostly some form elements. What is possible?

**Comment by rosskevin** [comment]
Good luck!  While we try to minimize JS in every way we can, there are just some things that need it to be compatible with the wide array of devices.  You are free to try anything you would like.

V4 (v4-dev branch) has cleaner javascript implemented as ES2015 and better separation of concerns so you can clearly see every component it touches and how.  https://github.com/FezVrasta/bootstrap-material-design/tree/v4-dev/js/src

While of course you are free to try anything, without the js or equivalent implementation, plenty of things wont work.
