### ISSUE TITLE
How to add this package along with Webpack?

### ISSUE THREAD

**Issue by renelopez** [mdbootstrap/mdb-ui-kit#878]
Hi guys,
Im struggling in adding this package along with the bootstrap-sass-loader in order to load the styles and javascript using webpack but with no results.
Has anyone managed to integrate this library on webpack?

**Comment by rosskevin** [comment]
If you need personal support, please try StackOverflow.  If you have a bug, please report it here.

https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#using-the-issue-tracker
