### ISSUE TITLE
XML error in sitemap.xml

### ISSUE THREAD

**Issue by AIMMOTH** [mdbootstrap/mdb-ui-kit#879]
Why are there dashes in the beginning of sitemap.xml ?

https://github.com/FezVrasta/bootstrap-material-design/blob/master/docs/sitemap.xml#L2

**Comment by rosskevin** [comment]
This is a frontmatter/jekyll source file.  Jekyll docs were started on the master but never finished,  they are used only in v4. I should probably just remove them.

**Comment by rosskevin** [comment]
removed docs - https://github.com/FezVrasta/bootstrap-material-design/commit/2cab4a2979122c4c8b6ff5451f7ad3b2f1f55524
