### ISSUE TITLE
Hidden inputs should not be wrapped

### ISSUE THREAD

**Issue by curry684** [mdbootstrap/mdb-ui-kit#880]
At https://github.com/FezVrasta/bootstrap-material-design/blob/master/dist/js/material.js#L116 all input fields in a form are wrapped with `<div class="form-group">` if they haven't explicitly been.

However this also triggers for hidden inputs, specifically Symfony's CSRF protections, and as Material Design gives formgroups a 27px margin this means they actually take up space now.

**Comment by rosskevin** [comment]
Please submit PR.

**Comment by curry684** [comment]
Fix seems valid, apologies for not having time to pick it up myself sooner.
