### ISSUE TITLE
bootstrap multiselect checkbox not appear

### ISSUE THREAD

**Issue by sergio11** [mdbootstrap/mdb-ui-kit#884]
Hi,

Checkbox do not appear in the bootstrap multiselect.

Could you tell me I can do to fix it or  alternative library should I use?

thank you very much, Greetings.

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#why-was-my-issue-summarily-closed

**Comment by sergio11** [comment]
sorry I had not seen the rules.

I created a test case with the problem here http://codepen.io/Sergio11/pen/eJqpMa.

I wanted the result to be like this: http://codepen.io/Sergio11/pen/LGwpgZ (using bootwatch paper)

thank you very much, Greetings.

**Comment by rosskevin** [comment]
Thank you for the codepen.  I'm not familiar with the `multiselect` project, but we don't declare any support for it.  

Likely, it seems to generate checkboxes on the form.  You would need to either try and use arrive.js which may make it work, or do some custom coding to get our mdb checkbox rendering to work.  You can look through our javascript to see what we are doing with checkboxes.
