### ISSUE TITLE
v4 class and variable prefix renaming

### ISSUE THREAD

**Issue by rosskevin** [mdbootstrap/mdb-ui-kit#886]
Due to being enlightened of a recent project that is not _free as in beer_, we are going to change some of our v4 class and variable names to avoid a potential misunderstanding of the source.

New prefix will be `bmd-`

**Comment by ghost** [comment]
seems drawers were broken by this update 2bda49b00e23190ef368127b7d1d8f2763f5d801

**Comment by rosskevin** [comment]
@jlertleNike it would help if you would file separate issues when you encounter them, closed issues rely on me seeing an email notification.  Also, please me what "broken" means, and which example you are looking at, because it is actually working locally for me.
