### ISSUE TITLE
Required Fields spec compliance behavior

### ISSUE THREAD

**Issue by cesterline** [mdbootstrap/mdb-ui-kit#887]
Required Fields: when focus is lost and the conditions for a required field have not been met, 'has-error' state should persist as per GMD.

GMD Spec: https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields

**Comment by rosskevin** [comment]
1. Please provide a codepen https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#tldr-create-a-test-case-using-this-codepen-template-when-submitting-an-issue
2. Please be specific in what you want that is not working.  The video is _very_ helpful as a spec, but let's discuss/enumerate the gap to the spec.

**Comment by cesterline** [comment]
Codepen: http://codepen.io/cewinstherace/pen/jWgLLg (Bootstrap Material Input with class 'has-error')

1) When focus is applied, Bootstrap Material Design advocates changing helper text color from 'default' to 'alert' color.  

Note: GMD does not specify adjustments to helper text color in such a case.

2) When focus is lost and the conditions for a required field have not been met, Bootstrap Material Design persists the 'has-error' state (color value) yet the Input itself, as defined by a simple underline, reverts back to its default state.  

Note: GMD specifies maintaining the 'has-error' color values for both Input and Label until the conditions for 'required' are met.

**Comment by rosskevin** [comment]
Perhaps you may not see that I can still misinterpret what you want and what is spec.  I'll try to be specific so I have no room to misinterpret:
1) Helper text behavior is not out of written spec, but it is unchanged in the video. You want it to be unchanged regardless of error state, correct?
2) To be in-spec, the underline should remain colored in an error state.

**Comment by cesterline** [comment]
As per the video:
1) Helper text is unchanged regardless of state.
2) Underline should maintain color of state, in this case 'has-error', if user changes focus without first satisfying the required attribute.

**Comment by tilwinjoy** [comment]
@cesterline If you look at the [theme](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3SjZ2SkgwTERaVkU/components_textfields_single4.png) [demos](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3Y1doNDEyT1UzU28/components_textfields_single5.png) or the [password input section](https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0Bzhp5Z4wHba3ZHFxVFJqVy1FOEU/components_textfields_passwordinput.png) you can see that the text below inputs does change color, and the current implementation works accordingly.

Is _helper-text_ and _error message(s)_ different things? If so how do they co-exist? Does one override the other? I couldn't find such information in the documentation.

---

**Update:** Ok [I found it](https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors). It says:

> Show error text only after user interaction with a field. If the user inputs incorrect data, helper text may transform into error text.

So in our case, when there is an error consider helper text to be transformed to error message. (It was a friendly helper text until user ignored it, now it is a serious error message)  I'd say the color change is as per specification. 

I agree with the underline behavior.

**Comment by tilwinjoy** [comment]
I'd also like to mention that we should discuss whether the helper text should change it's behaviour once it becomes error message, i.e Unlike helper text it should not hide when the focus is lost.  
But if the underline indicates the fields having error it might be okay to hide the error message as well. I couldn't find anything that says error messages should stay in the spec, even though most of the images imply such behavior. So this is like a matter of choice? Or is there anything I missed in the spec?

**Comment by rosskevin** [comment]
My standard has been to follow the spec text.  If it isn't written but it's in the the demo video, I regard that as good as-is-written.

**Comment by tilwinjoy** [comment]
@rosskevin I believe you missed the update in my previous comment, the color change of helper text is clearly written in [spec](https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors). As you can see in this [image](https://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors) the helper text can transform into error message when there is an error.

By the way since there is a video demonstrating _"persistent helper text"_ I think it'll be useful to have CSS classes for:
-  Making the helper text (_and error message, when it becomes one_) stay regardless of the inputs focus state, something like `.helper-static` similar to `.label-static`
- Indicating that the helper text should not transform into error message (_by default it does at present_) something like `helper-persistent`

**Comment by rosskevin** [comment]
> By the way since there is a video demonstrating "persistent helper text" I think it'll be useful to have CSS classes

This is `.bmd-help` in v4.

**Comment by sivajisanapala** [comment]
Hi @cesterline ,
Did you overcome that issues( https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields ). Even i am struck with the same.
