### ISSUE TITLE
V4 Confusion with container

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#888]
Hello, thanks for all of the hard work with this one.

I am testing with **v4** bootstrap/material.

Here is the pen: http://codepen.io/anon/pen/dGxevz

I'm having some difficulty wrapping my head around an issue/feature regarding **.container** namely when my container is outside a canvas (e.g. with the sidebar) it defaults to standard bootstrap behaviour but once inside the canvas it is centered and the container loses it's width.

Regardless of whether this is an issue or default behaviour I have had a look over the styling and cannot find what is causing this effect.

Would somebody please mind pointing me in the right direction? I've used the 'quick start' template with the code from the 'fixed left' drawer example and have added two containers in as per the pen link.

**Comment by rosskevin** [comment]
!!!!!!!!!

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/v4-dev/CONTRIBUTING.md#tldr-create-a-test-case-using-this-codepen-template-when-submitting-an-issue

**Comment by ghost** [comment]
@rosskevin - I have added a pen. I think my issue is now compliant but if not please let me know.

**Comment by rosskevin** [comment]
It appears you have put a container inside a header which is flex based.

I have updated the codepen, specifically showing where content goes.  Does this help?

http://codepen.io/rosskevin/pen/OMKZOa

The template has `<!-- main content -->`, is that what you are wanting to use?

**Comment by ghost** [comment]
Yeah I literally just worked that out when you posted. I figured it was flex but see what's going on now thanks.
