### ISSUE TITLE
Grunt dist task failing

### ISSUE THREAD

**Issue by kkorada** [mdbootstrap/mdb-ui-kit#889]
Running "less:material" (less) task

> > NameError: variable @line-height-base is undefined in less_variables.less on
> >  line 75, column 37:
> > 74 //*\* Unit-less `line-height` for use in components like buttons.
> > 75 @mdb-input-line-height-base:        @line-height-base; //1.428571429; // 2
> > 0/14
> > 76 //*\* Computed "line-height" (`font-size` \* `line-height`) for use with `ma
> > rgin`, `padding`, etc.
> > Warning: Error compiling less/bootstrap-material-design.less Use --force to cont
> > inue.

Aborted due to warnings.

**Comment by sebastienguay** [comment]
and solving?

**Comment by kkorada** [comment]
yes it was working now.

**Comment by fizzl** [comment]
I'm having this same problem right now.

`grunt serve`

> > Running "less:material" (less) task
> > NameError: variable @line-height-base is undefined in less/_variables.less on line 75, column 37:
> > 74 //*\* Unit-less `line-height` for use in components like buttons.
> > 75 @mdb-input-line-height-base:        @line-height-base; //1.428571429; // 20/14
> > 76 //*\* Computed "line-height" (`font-size` \* `line-height`) for use with `margin`, `padding`, etc.

**Comment by fizzl** [comment]
`find|grep line-height-base`

Comes back empty. Where is this variable supposed to come from?

**Comment by SergeyKhval** [comment]
Bootstrap material design depends on original bootstrap framework. This variable comes from bootstrap's variables.less or _variables.scss file (depending on preprocessor being used)

**Comment by fizzl** [comment]
I tried checking out older versions to find a version to start a bisect from. I'm coming up with errors on all tags, so it's quite obviously a problem with my environment. 

I'll clean up and start over. Thanks for help.

I'll report back if I'll figure out what the problem was.

**Comment by kkorada** [comment]
try running npm install and bower install prior to grunt. so that required bower_components (bootstrap) are present.

**Comment by fizzl** [comment]
Problem solved:
1. I hadn't run `bower install`
2. I didn't have sass installed. `sudo gem install sass`

Thanks again for support!

**Comment by kkorada** [comment]
you dont need sass as you can do it with less task also. once you run bower install you will get bootstrap components in it then you can run grunt serve
