### ISSUE TITLE
Button Does not have Wave Effect

### ISSUE THREAD

**Issue by sanskritkm** [mdbootstrap/mdb-ui-kit#894]
Here what I include in my project for testing.

CSS:
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <link href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/bower_components/bootstrap-material-design/dist/css/bootstrap-material-design.css" rel="stylesheet" />
    <link href="~/bower_components/bootstrap-material-design/dist/css/ripples.css" rel="stylesheet" />`

Script:
`<script src="~/bower_components/jquery/dist/jquery.js"></script>
    <script src="~/bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/bower_components/bootstrap-material-design/dist/js/material.js"></script>
    <script src="~/bower_components/bootstrap-material-design/dist/js/ripples.js"></script>
`

My Button:
`<a href="#" class="btn btn-raised btn-danger">Click me</a>`

Result:
![capture](https://cloud.githubusercontent.com/assets/17005582/13346500/558e655e-dc99-11e5-9b7b-40d6fe4ad9fe.PNG)

Issued:
No Wave Effect while I click on button.

Or any problem within my code? Please kindly help.

**Comment by SergeyKhval** [comment]
You should initialize material.js and ripples.js by calling `$.material.init()`

**Comment by sanskritkm** [comment]
It's work now. Thanks. :+1:
