### ISSUE TITLE
btn-fab without ripple effect

### ISSUE THREAD

**Issue by JoernT** [mdbootstrap/mdb-ui-kit#895]
can't get this to work and also doesn't work on http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html for me (FF 44.0.2 and Chrome 48.0.2564.116 on OSX).

btn-fab shows lightgrey background on hover and does not react on clicks.

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#why-was-my-issue-summarily-closed
