### ISSUE TITLE
Sass causes a conflict. Boostrap dropdowns not working anymore.

### ISSUE THREAD

**Issue by arjanvaneersel** [mdbootstrap/mdb-ui-kit#897]
I have installed bootstrap-material-design via bower (in a yeoman environment, so with grunt). After the install grunt adds the following to my index.html page:

<script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>

<script src="bower_components/bootstrap-sass/assets/javascripts/bootstrap.js"></script>

<script src="bower_components/bootstrap-material-design/dist/js/material.js"></script>

<script src="bower_components/bootstrap-material-design/dist/js/ripples.js"></script>

This however seems to cause a conflict with bootstrap, because dropdown menus aren't working anymore. Only when I comment out the bootstrap.js of bootstrap-sass everything starts functioning again. 

I also tried to uninstall bootstrap or bootstrap-sass with bower, as I though that the latter is just bootstrap, but with sass. However trying to uninstall one or the other gives a warning that bootstrap-material-design requires both.

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#why-was-my-issue-summarily-closed

**Comment by arjanvaneersel** [comment]
If you look at your own codepen template then you'll see that only 1 bootstrap.js gets loaded, which is the one of bootstrap without sass. So OF COURSE everything works fine in your template...

If you will then look at your bower.json file then you'll see this:
"dependencies": {
    "jquery": "~2.1.1",
    "bootstrap": "~3.3.6",
    "bootstrap-sass": "~3.3.6"
  }

and that is exactly what causes this problem and what I described above. It seems that either bootstrap or bootstrap-sass has to be used, because both of them cause a problem.

**Comment by rosskevin** [comment]
The dual include is for dual compilation of less and sass

**Comment by Domynos** [comment]
@arjanvaneersel I have the exactly same problem. Did you resolve your issue ?
