### ISSUE TITLE
Severe performance hit when using 'Active' progress bars

### ISSUE THREAD

**Issue by Klakurka** [mdbootstrap/mdb-ui-kit#899]
Adding a single progress-bar with an 'active' class causes CPU usage to spike. Adding another active progress bar further amplifies the problem.

This is the case regardless of whether or not the 'progress-striped' class is applied.

**Comment by rosskevin** [comment]
These are bootstrap progress bars, you need to file an issue upstream with the twbs/bootstrap repository
