### ISSUE TITLE
Support file:/// loading in index.html

### ISSUE THREAD

**Issue by dandv** [mdbootstrap/mdb-ui-kit#90]
Currently, `index.html` in the root dir or in the `template` fails to load if opened in a browser as `file:///C:/.../bootstrap-material-design/index.html` because it depends on several stylesheets and scripts hosted online. The protocol for them is unspecified, which allows `http` vs `https` flexibility, but how about we hardcode the protocol as https? That way, https pages won't issue any warnings, and local development via `file:///` will work.

`material-wfont.css` also points to `//fonts.googleapis.com/`.

**Comment by FezVrasta** [comment]
@shockwork and @nelsonomuto what do you think?

**Comment by nelsonomuto** [comment]
I think development is best done on the http server. Especially now that a workflow with live reload and a watch has been implemented. The best way to resolve this is updating the README or WIKI with a developer section detailing the steps to run the grunt tasks for developers.

**Comment by TransitoryBliss** [comment]
We should not be using file:///... But as @nelsonomuto says, we should be more clear in the development section. Especially that work should be done on the develop branch :)
