### ISSUE TITLE
I can't use bootstrap-material-design with jquery 2.2.1

### ISSUE THREAD

**Issue by makroxyz** [mdbootstrap/mdb-ui-kit#900]
Hi, I'm using  bower-asset/jquery 2.2.1 in my project... I can't install latest stable (0.5.9) 'cos of this composer error. composer downloads only 0.1.5

bower-asset/bootstrap-material-design v0.5.9 requires bower-asset/jquery ~2.1.1 -> no matching package found.

**Comment by rosskevin** [comment]
I have no idea what _composer_ is, but I have updated the dependency and committed it, I'm guessing it will solve your problem now that jquery is up to date.

**Comment by makroxyz** [comment]
Thanks... but in order to work I had also to modify 
"bootstrap": ">=3.3.5",
"bootstrap-sass": ">=3.3.5"

**Comment by rosskevin** [comment]
Please feel free to submit a PR for what works.
