### ISSUE TITLE
Materical Icons behaving weird

### ISSUE THREAD

**Issue by Fubinator** [mdbootstrap/mdb-ui-kit#903]
Hey,
I don't really know if this is a bug or I am doing something wrong.

Material Icons with a space in between their names behave quite weird. The ones without a space are working correctly.

example: `<i class="material-icons">shopping basket</i> Marketplace` is doing a weird line break
or this: `<i class="material-icons">show chart</i> Statistics` is aligning the text right.

Here's a picture of it: http://imgur.com/t64iIK9

Maybe it's important to say that ripples and checkboxes aren't working for me as well. I double checked twice and I'm quite sure I referenced everything in the right way. 

What I use:
bootstrap 3.3.6
Latest bootstrap material
AngularJS (Maybe it's because of angular?)

Maybe you have any suggestions for this.

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#why-was-my-issue-summarily-closed

**Comment by FezVrasta** [comment]
you have to use `_`, not spaces
