### ISSUE TITLE
The function to apply only to specific elements does not work for (input, textarea, select) ... --- $.material.input() ---.

### ISSUE THREAD

**Issue by djmago** [mdbootstrap/mdb-ui-kit#904]
Hello, the function to apply only to specific elements does not work for (input, textarea, select) ... `$.material.input()`.

With the default function `$.material.init()` it works perfectly, but when trying to apply to specific elements does not work.

It stopped working since the previous version. In previous versions it worked perfectly but the latest versions no longer works.

**Comment by rosskevin** [comment]
Please submit a PR.  We don't guarantee those work in V3, but it's certainly nice to have.

**Comment by djmago** [comment]
- With the default function everything works perfectly:
  http://codepen.io/djmago/pen/dMMpMK

Example of failure:
- The bug is in the ((( forms ))) to apply only to specific elements:
  http://codepen.io/djmago/pen/pyyEXr

**Comment by rosskevin** [comment]
> Please submit a PR. We don't guarantee those work in V3, but it's certainly nice to have.
