### ISSUE TITLE
Automatically detect final markup inside togglebutton and not create the new span element

### ISSUE THREAD

**Issue by dragantl** [mdbootstrap/mdb-ui-kit#906]
I am using the toggle and want to manually create the `<span class="toggle">` element. The reason to do that is that I will add `data-icon="star"` to the element and update CSS to use attribute for `content: attr(data-icon)`. However, if I create it manually, I end up with two toggles. Can this check be made when instantiating a togglebutton?

**Comment by rosskevin** [comment]
Please submit a PR if you would like this functionality and I'm happy to review it.
