### ISSUE TITLE
checkbox not showing only the Label is showing because the <span/> is not appending after the label

### ISSUE THREAD

**Issue by khaled4vokalz** [mdbootstrap/mdb-ui-kit#907]
I am using the Bootstrap Material Design and it's awesome but when I tried to use the Material Checkbox it is not showing in my view.
the .checkbox > label > input[type=checkbox] from the Material.js is not getting applied which attaches a span tag on runtime. Don't know why. Tried a lot. Please help as I want to attach the material version of the checkbox.

I added the jquery.js,bootstrap.js, ripple.js, material.js in my view.

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#why-was-my-issue-summarily-closed

**Comment by khaled4vokalz** [comment]
@rosskevin can you please provide  me a CodePen demo of the checkbox... I can't get it working...

**Comment by rosskevin** [comment]
[checkbox codepen](http://codepen.io/rosskevin/pen/GZqZQZ?editors=1010)

It works fine, I used the code directly from the `input.html` sample.

**Comment by matiasarenhard** [comment]
$.material.init(); work for mee. thanks @rosskevin
