### ISSUE TITLE
Unable to Compile the source. Undefined variable errors.

### ISSUE THREAD

**Issue by whichrakesh** [mdbootstrap/mdb-ui-kit#908]
I want to change the primary color for my application for which I downloaded the source, changed the primary-brand-color in _variables.less and tried to compile it with grunt, but I am getting plenty of errors that many variables are undefined. I manually defined many variables, but I keep on getting more definition requirements. How to resolve this issues?

NameError: variable @screen-sm-min is undefined in /home/rakesh/bin/bootstrap-material-design-0.5.9/less/_inputs-size.less on line 194, column 22:
193   // labels on narrow viewports stack the same as a default form example.
194   @media (min-width: @screen-sm-min) {

**Comment by rosskevin** [comment]
Bower install and npm install first.  The build works otherwise Travis would indicate otherwise.  You can open the .travis.yml to learn how any project is built successfully
