### ISSUE TITLE
why the button does not fit in the column?

### ISSUE THREAD

**Issue by acopalipsis** [mdbootstrap/mdb-ui-kit#909]
why the button does not fit in the column?   [codepen](http://codepen.io/anon/pen/EKyKGJ?editors=1000)

**Comment by rosskevin** [comment]
Please start with our codepen template.

**Comment by rosskevin** [comment]
I've just had a chance to look at this on my desktop.  Please file issues as reduced test cases using our codepen template.  This means removing every extraneous css style that is not directly relevant to the test. e.g. your color elements appear to be absolute positioned, which is going to be quite misleading.

https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md

Further, your code would not pass bootlint (it is invalid bootstrap structure for rows/columns).  I'll see if I can incorporate bootlint into the template.

**Comment by rosskevin** [comment]
I've updated our codepen template with bootlint.  Given the number of errors in your markup and the strange positioning of elements in css, I'm going to close this. This issue tracker is for bugs/features, and I think you need some personal support which is best on StackOverflow.  I encourage you to use our codepen template and submit an issue to StackOverflow to help with your understanding.

**Comment by acopalipsis** [comment]
the colored blocks to render only the grid from bootstrap v3, which You took to be "something foreign". Will follow Your advice and go on SO, although I think I wouldn't get a response there, because with the standard styles in my "demo code" works perfectly.And I had already asked for a bit less popular than the resource SO and received no reply. And background the css is a grid from bs3, which I couldn't find it on cdn and had to insert it that way.

**Comment by rosskevin** [comment]
You can submit the codepen here, but as I said, it is an invalid bootstrap structure and one element rendering outside is a common symptom of that.

**Comment by acopalipsis** [comment]
it was quite desperate, so I don't answer. Made two examples - the first is with standard theme - http://codepen.io/anon/pen/BKLwmo . Help me to do the second as well as first - http://codepen.io/anon/pen/reMGpJ . I am learning to write only couple of hours a day, in the evening. The whole week I'm trying to understand what was going on but alone can not cope.

**Comment by rosskevin** [comment]
As I have said,  first start with our codepen template and add your html. 

https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#tldr-create-a-test-case-using-this-codepen-template-when-submitting-an-issue

**Comment by acopalipsis** [comment]
sorry I don't understand what You suggest me.I have something to do with Your template.But don't You come up with bs3 and You have to come up with templates.I can't help not community SO, don't komuniti of my segment.Everyone says that my code is valid and only You say no. I apologize for the timing, I thought You wrote the theme for bs3, but not a library with similar name who lives by his own rules.

**Comment by SergeyKhval** [comment]
@acopalipsis, have a look here:
[codepen](http://codepen.io/transGLUKator/pen/LNborB)

Your markup didn't comply with bootstrap conventions. You also need to include bootstrap.css for bootstrap-material-design to work.

**Comment by acopalipsis** [comment]
@SergeyKhval, I don't know what You wanted me to show the example, but this example is also not correct. Button sizes are not placed in the grid. 
![_001](https://cloud.githubusercontent.com/assets/9849922/13814712/6436db6e-eb98-11e5-8970-53cb4e28e059.png)
If You know how to do it right, You made me happy by showing an example.

**Comment by FezVrasta** [comment]
Out of my mind... How do you think such button should fit in the green column if its width is larger than the column?

**Comment by acopalipsis** [comment]
@FezVrasta , so I say that this theme is not for bs3, as it is not compatible with it. We could by default set the size of 3000px and say that it is all abnormal, and the button such as it must be.

**Comment by acopalipsis** [comment]
@FezVrasta the default button itself is scaled wrong, and mathematics is the problem of the library, not the standard grid. All the other themes don't have this problem, and You present this as an exception?

**Comment by rosskevin** [comment]
@acopalipsis, we are not getting through to you.  Now we have three people that have tried to help you, and you insist somehow that this project is wrong yet you have presented invalid bootstrap markup.  

You need to invest more time fundamentally understanding both CSS and bootstrap.  There are thousands of users of both this and bootstrap that do not have the problem you are presenting.  Layout is _completely_ done with bootstrap and not this library, and I am certain that it works.

Since this is not a problem of this library, nor even a problem for the upstream bootstrap, please take your issues to StackOverflow.
