### ISSUE TITLE
Dialog's target dialog div must be in 'top level'.

### ISSUE THREAD

**Issue by Hacksign** [mdbootstrap/mdb-ui-kit#911]
If I put the Dialog's target dialog div in a deeper level of Dom tree, then I couldn't close the dialog div after I active it.
Here is an example page:
http://www.hacksign.cn/t.php

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#why-was-my-issue-summarily-closed
