### ISSUE TITLE
btn-(variant) radio active color contrast

### ISSUE THREAD

**Issue by t123yh** [mdbootstrap/mdb-ui-kit#912]
This is what it looks like in original Bootstrap:
![origin](https://cloud.githubusercontent.com/assets/8972552/13750084/f76fe0fc-ea3e-11e5-9fa5-1bafe8285170.png)

And this is what it looks like in material design:
![md](https://cloud.githubusercontent.com/assets/8972552/13750085/f8678d02-ea3e-11e5-97fc-48926e0ff7fe.png)

This is my code on [CodePen](http://codepen.io/anon/pen/zqKQJj)

**Comment by rosskevin** [comment]
As far as I know,  the bootstrap radio toggle has no material design equivalent. Will you point to one on the material design spec?  

Also,  while the pics are helpful,  please remove the code and provide it in a codepen as requested in the contributing guidelines.

**Comment by t123yh** [comment]
I've already uploaded the code on CodePen. And also, I know there's no such equivalent, but can we just adjust the color to make it better?

**Comment by rosskevin** [comment]
First, you are using `btn-success` so I wouldn't vary the basis color, but I'm willing to accept a PR if you want to take a shot at making this look a bit better.  You just need to alter the less files (please avoid submitting `dist` or `sass` files, they'll be generated with the build).

So even though I'm happy to include a PR that looks a bit better, I'd just like to mention that it may be worth re-thinking your markup in the context of the entire [material design guidelines](https://www.google.com/design/spec/material-design/introduction.html)...not required...just a suggestion.

**Comment by rosskevin** [comment]
Closing this based on the inactivity in the PR
