### ISSUE TITLE
No fonts folder in dist

### ISSUE THREAD

**Issue by meril19181** [mdbootstrap/mdb-ui-kit#914]
Hi sorry I'm just a begginer, I'm trying out appery and they linked to your bootstrap-material-design repository. They were saying there that there should have been a font folder, may I know if this is just ok if it's not there?

**Comment by FezVrasta** [comment]
Probably they are referring to an old version of BMD. Now the fonts are loaded from google fonts.

**Comment by meril19181** [comment]
Alright, thank you so much! :+1:
