### ISSUE TITLE
Checkbox, toggle input, radio button and select are not properly displayed when using with meteor

### ISSUE THREAD

**Issue by rwaness** [mdbootstrap/mdb-ui-kit#916]
As you see on the screen shot below (a copy of your demo on my meteor project), severals elements are not properly displayed.
Checkbox styles are applied with javascript. Perhaps there is an issue between javascript and meteor ...

![capture](https://cloud.githubusercontent.com/assets/3472359/13811795/4f542cb4-eb4e-11e5-8dd8-1b41c191ca45.PNG)

Please help me :)

**Comment by rwaness** [comment]
PEBCAK
Problem Exists Between Chair And Keyboard !! sorry :/

**Comment by ftoresan** [comment]
I think I got the same bug as you :)
Everything is rendering fine, but the checkboxes and radiobuttons don't. What did you do to solve your problema?

**Update**
My problem was that the components were dynamically created, so I solved by adding to my project [arrive.js](https://github.com/uzairfarooq/arrive/):

```
meteor add modweb:arrive
```

**Comment by rwaness** [comment]
Functions
- $.material.init() - shortcut to run all the following commands:
- $.material.ripples() will apply ripples.js to the default elements.
- $.material.input() will enable the MD style to the text inputs, and
  other kind of inputs (number, email, file etc).
- $.material.checkbox(): will enable the MD style to the checkboxes
  (remember to follow the markup guidelines explained in the Inputs section
  https://github.com/FezVrasta/bootstrap-material-design#inputs.
- $.material.radio(): will enable the MD style to the checkboxes
  (remember to follow the markup guidelines explained in the Inputs section.

2016-03-19 13:01 GMT-04:00 Fabricio Toresan notifications@github.com:
