### ISSUE TITLE
V4 bower install and bower update fail

### ISSUE THREAD

**Issue by SergeyKhval** [mdbootstrap/mdb-ui-kit#922]
``` shell
bower bootstrap#v4-dev         ECMDERR Failed to execute "git ls-remote --tags --heads git@github.com:twbs/bootstrap.git", exit code of #128 Host key verification failed. fatal: Could not read from remote repository.  Please make sure you have the correct acces
s rights and the repository exists.

Additional error details:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

It is likely a problem with using `git` protocol instead of `https`
Changing dependency to `"bootstrap": "~4.0.0-alpha.2"` seems to solve the problem

**Comment by rosskevin** [comment]
Go ahead and submit a PR for the fix,  I'm using npm for dev so I haven't been checking bower and this branch isn't using travis yet.

**Comment by Giggiux** [comment]
`bower bootstrap#v4-dev                     ECMDERR Failed to execute "git ls-remote --tags --heads git@github.com:twbs/bootstrap.git", exit code of #128 Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

Additional error details:
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

It gives this error to me. Am I doing something wrong?
