### ISSUE TITLE
Unable to load css and js for ToggleButton

### ISSUE THREAD

**Issue by nehaverma8** [mdbootstrap/mdb-ui-kit#923]
I have include the material design .js and .css file in the dist folder. I loaded material design using 

  $["material"].init();

However, I cannot get my toggle button to work. The below code just displays a normal checkbox. How do I get togglebutton related js and css files to load?

```
<div class="row">
    <div class="col-xs-6 form-group pull-right">
        <div class="togglebutton">
            <label>On</label>
            <input type="checkbox">
        </div>
    </div>
```

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/README.md#getting-started

If you need more help than that,  please use stackoverflow for personal support.
