### ISSUE TITLE
How Bootstrap-Material-Design works with Angular2 ?

### ISSUE THREAD

**Issue by musmanpak** [mdbootstrap/mdb-ui-kit#925]
I am working on a website and I like the Bootstrap-Material-Design template for the front end. But I would like to use Angular2 with that, (Although I am still learning Angular2, and hence don't know exactly what I am asking, I hope you get the idea). I have the idea that when we use Angular2, we won't be adding Jquer files to the website (atleast that is what I have heard). I am not sure what it means exactly. Can you please explain how will this whole thing works out.

**Comment by jugglingcats** [comment]
Have not used bootstrap-material-design myself but in general just code your angular pages/templates using the correct CSS classes and it will work.

It appears that if you are using material.js for anything you need to include Arrive.js beforehand to make sure dynamic elements added to the DOM by angular are handled correctly by material.js.

HIH

**Comment by rosskevin** [comment]
As mentioned in the contribution guidelines,  for personal support,  please seek help on stackoverflow. This is for bugs/enhancements.
