### ISSUE TITLE
Floating labels are not working with meteor 1.3

### ISSUE THREAD

**Issue by Billybobbonnet** [mdbootstrap/mdb-ui-kit#929]
Hello,

I am giving a try to BMD with Meteor 1.3 and Blaze, using the package, and I can't get the floating labels to work. I tried to `$.material.init()` after importing the package at different steps of the DOM tree construction but I don't get any results (no error either).

As I understand it, as long as `$.material.init()` has been called before a template is rendered, arrive.js will activate the BMD features of the inputs, right?

Any idea of what I should do? Are there people experiencing the same issue?

**Comment by rosskevin** [comment]
Sorry, @see #930
