### ISSUE TITLE
Modal loads and disappears 

### ISSUE THREAD

**Issue by duncanhan** [mdbootstrap/mdb-ui-kit#93]
I have tried adding this template to an already existing project, when I launch a modal, it blinks and disappears.

**Comment by FezVrasta** [comment]
please provide more informations: browser, fiddle of the problem, error log etc. 
As you can see, in our demo the modals work

Thanks!

**Comment by duncanhan** [comment]
I have tried both in Chrome and Firefox, its only modals that are fired by button clicks that do not work.

**Comment by FezVrasta** [comment]
we need a fiddle to be sure the problem is the theme and not something in your project

**Comment by olmoser** [comment]
i had the exact same problem - once i removed the `bootstrap-saas` dependency the issue with the disappearing dialog was gone. hth.
