### ISSUE TITLE
cant install with bower

### ISSUE THREAD

**Issue by ghost** [mdbootstrap/mdb-ui-kit#932]
When installing with bower:
bower install bootstrap-material-design --save

I get an error : 
 ECMDERR Failed to execute "git ls-remote --tags --heads git@github.com:twbs/bootstrap.git", exit code of #128 Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

attached is the full output. 
[bower_MD_error.txt](https://github.com/FezVrasta/bootstrap-material-design/files/186648/bower_MD_error.txt)

This only happens with this repository.

Thank you

**Comment by rosskevin** [comment]
duplicate https://github.com/FezVrasta/bootstrap-material-design/issues/931#issuecomment-200429768

**Comment by rosskevin** [comment]
Please search before filing an issue: http://stackoverflow.com/a/12940681/2363935
