### ISSUE TITLE
has-*  status variants inconsistent with form size variants

### ISSUE THREAD

**Issue by jnosek** [mdbootstrap/mdb-ui-kit#935]
control-label elements in form-group-lg and form-group-sm layouts do not have the proper text color applied for has-success, has-error, has-warning, and has-info status classes.

The following codepen example shows the proper working text color styling for the default form-group, and the non-working styles for form-group-lg and form-group-sm.
http://codepen.io/jnosek/pen/GZmGNO

Tested in Google Chrome

**Comment by rosskevin** [comment]
Looks fine to me.  What do you mean by "proper text color"?

**Comment by rosskevin** [comment]
Ah,  size variants!

**Comment by jnosek** [comment]
I have a pull request incoming with my fix
