### ISSUE TITLE
Ripples color

### ISSUE THREAD

**Issue by FezVrasta** [mdbootstrap/mdb-ui-kit#94]
We should make the ripple of the same color of the text of the target. (I think it is the method used by polymer)

**Comment by TransitoryBliss** [comment]
:+1 I can fix this tonight.

**Comment by FezVrasta** [comment]
thanks!

**Comment by TransitoryBliss** [comment]
sooo many projects at work current; hard to get time.. I'm currently fixing this one!

**Comment by TransitoryBliss** [comment]
@FezVrasta I kept the alpha at 0.05 - but not sure if that's high enough. Maybe we should raise it to 0.08 or something?

**Comment by FezVrasta** [comment]
@shockwork have we did some regression? Watching the diff I see lot of rows deleted. What's happened?

**Comment by TransitoryBliss** [comment]
Look at the Demo, it's in
