### ISSUE TITLE
Impossible to run Grunt

### ISSUE THREAD

**Issue by sylvainar** [mdbootstrap/mdb-ui-kit#947]
Hey guys !

First, thanks for your work, this framework is truly awesome ! However, I'm experiencing troubles. I'd like to modify the primary color, so I've followed instructions in the readme.md. But I can't run Grunt, seems like their is a missing file.

Here's the log (clean:dist and htmllint:all run correctly) : 
`Running "bootlint:files" (bootlint) task

> > index.html:92:15 E047 `.btn` should only be used on `<a>`, `<button>`, `<input>`, or `<label>` elements.
> > bootstrap-elements.html:1818:11 E046 `.modal` elements must have a `tabindex` attribute.

2 lint error(s) found across 2 file(s).

For details, look up the lint problem IDs in the Bootlint wiki: https://github.com/twbs/bootlint/wiki

Running "less:material" (less) task

> > NameError: variable @line-height-base is undefined in less/_variables.less on line 75, column 37:
> > 74 //*\* Unit-less `line-height` for use in components like buttons.
> > 75 @mdb-input-line-height-base:        @line-height-base; //1.428571429; // 20/14
> > 76 //*\* Computed "line-height" (`font-size` \* `line-height`) for use with `margin`, `padding`, etc.
> > Warning: Error compiling less/bootstrap-material-design.less Use --force to continue.

Aborted due to warnings.
`

Thanks !

**Comment by rosskevin** [comment]
npm install && bower install first.  You are missing the bootstrap dependency
