### ISSUE TITLE
Manually toggling dropdown no longer works

### ISSUE THREAD

**Issue by lordplagus02** [mdbootstrap/mdb-ui-kit#953]
According to the bootstrap docs, I was able to use `.dropdown('toggle')` to manually open a dropdown, now after a recent update to material bootstrap I get this error in the console:

> Uncaught Error: Method toggle does not exists on jQuery.dropdown

**Comment by rosskevin** [comment]
Wrong repo,  that is an upstream bootstrap method,  not one from this project.
