### ISSUE TITLE
Not able to change primary color of theme

### ISSUE THREAD

**Issue by MRDcoder** [mdbootstrap/mdb-ui-kit#956]
I tried to change primary color of this theme. I followed this http://spapas.github.io/2014/12/16/change-bootstrap-material-primary-color/. But i faced below attached issue while generating css:

```
D:\Mudassar\MyCAPS\website\bootstrap-material-design-0.5.9>lessc custom.less  >
material-custom.css
NameError: variable @line-height-base is undefined in D:\Mudassar\MyCAPS\website
\bootstrap-material-design-0.5.9\less\_variables.less on line 75, column 37:
74 //** Unit-less `line-height` for use in components like buttons.
75 @mdb-input-line-height-base:        @line-height-base; //1.428571429; // 20/1
4
76 //** Computed "line-height" (`font-size` * `line-height`) for use with `margi
n`, `padding`, etc.
```

Can you please help me to do the same or provide link of updated full palette css?

P.S : Please find content of my custom.less below:
@import "less/bootstrap-material-design.less";

@primary: @indigo;

**Comment by rosskevin** [comment]
You should try following our readme instead of an article feom 2014
