### ISSUE TITLE
V4: Cannot compile with ruby SASS

### ISSUE THREAD

**Issue by JP-Ellis** [mdbootstrap/mdb-ui-kit#957]
Currently, the SCSS files seem to be incompatible with SASS due to the presence of `&` at the base level of mixins:

``` text
$ sass --version
Sass 3.4.22 (Selective Steve)
$ sass -I ./bower_components scss/bootstrap-material-design.scss
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
        on line 106 of scss/mixins/_forms.scss, in `bmd-form-color'
        from line 80 of scss/_forms.scss
        from line 13 of scss/_core.scss
        from line 3 of scss/bootstrap-material-design.scss
  Use --trace for backtrace.
```

**Comment by FezVrasta** [comment]
@JP-Ellis I'm not a SASS expert and I can't find a solution to this problem.

I found the `@at-root` selector but it doesn't seem to work.

The problem is this part of mixin:

``` sass
@mixin bmd-form-color($label-color, $label-color-focus, $border-color) {

  [...]

  .is-focused, // may or may not be a form-group or bmd-form-group
  &.is-focused {

  [...]
}
```

As you see we want to add a `&.is-focused` selector to the selector which calls the mixin, but I don't know how to make it work with the `sass` ruby command.

**Comment by blanco217** [comment]
@JP-Ellis I noticed you have a commit dealing with this issue did that work for you?

**Comment by JP-Ellis** [comment]
I've been busy with other things lately and haven't dealt with SASS in a while.  I originally saw this issue and made a pull request (#949) to try and address this issue, but it was not merged as discussed in the pull request.  I closed the pull request in favour of this issue to get a better fix.

The pull request did work for me in my use cases though, and you can see a very similar patch was used in [this other commit](https://github.com/memikequinn/bootstrap-material-design/commit/46366033fcc20849e6fa0712b0ef14890c8f8573).

**Comment by JamesVanWaza** [comment]
@JP-Ellis @blanco217 @FezVrasta were you able to find the solution because, I am still getting the error below. 

My `Sass Version:` **3.4.23**
`Grunt`: **1.0.1**

**Comment by FezVrasta** [comment]
Nope, I still don't know how to fix this problem. But I remember it doesn't compile only with a specific version of Sass, I don't remember which one tho 😥

PRs are welcome.

**Comment by JP-Ellis** [comment]
@jgacuca567 A nice fix?  No, I was not able to find one.  A temporary fix to get things compiling can be found from my pull request (#949), but the problem with that pull request is that it can cause issues if used incorrectly.

**Comment by JamesVanWaza** [comment]
@JP-Ellis any updates yet on whether the issue was resolved, still getting the error even after updating to `4.0.0-beta.3`

**Comment by FezVrasta** [comment]
Nope, sorry.

By the way ruby-sass is going to be deprecated within an year so you should switch away from it anyway

**Comment by JamesVanWaza** [comment]
@FezVrasta how do I work around the issue?, so that `grunt` can run

**Comment by FezVrasta** [comment]
I don't know, just use libsass instead of ruby-sass

This should work:
https://github.com/sindresorhus/grunt-sass

**Comment by JamesVanWaza** [comment]
@FezVrasta it works, do you think we should make a page on what to do when getting common errors?

**Comment by FezVrasta** [comment]
If the idea is to drop support for ruby-sass, I think it's okay to add a note in the README of the project.

Do you want to send a PR?

**Comment by JamesVanWaza** [comment]
I will try and create a PR and send for you to review.

**Comment by FezVrasta** [comment]
Closing, I dropped support for ruby-sass once for all.

https://fezvrasta.github.io/bootstrap-material-design/docs/4.0/getting-started/build-tools/#sass
