### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'matches' on 'Element': 'input[type!='hidden'][type!='checkbox'][type!='radio'][type!='file'][type!='button'][type!='submit'][type!='reset']' is not a valid selector.

### ISSUE THREAD

**Issue by youngyou** [mdbootstrap/mdb-ui-kit#958]
The default component configuration may not work. the "!=" selector just works in jquery, but not purejs. And the `arrivejs` use the `HTMLElement.prototype.matches`. It will not work.

**Comment by rosskevin** [comment]
Test cases are required.

https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#why-was-my-issue-summarily-closed

**Comment by youngyou** [comment]
The test case is here, http://codepen.io/youngyou/pen/eZGQjN
And this is my fix: http://codepen.io/youngyou/pen/wGrQpE

**Comment by rosskevin** [comment]
Bootstrap requires jquery and so does this project.  We are open to reviewing a PR on this but it is not a bug.

**Comment by youngyou** [comment]
But arrivejs uses `HTMLElement.prototype.matches`, which is not query.
And I'm sorry that in the test case I use a wrong js file, I have fixed it just now. You may check it again.

**Comment by rosskevin** [comment]
Got it, thank you.  Since the PR is open I'll just leave this closed and we can resolve it there.
