### ISSUE TITLE
v4.0.1 Material elements and ajax content 

### ISSUE THREAD

**Issue by preetamslot** [mdbootstrap/mdb-ui-kit#959]
I have content that gets visible trough .load() jQuery. Now the loaded content / components does not interact with the bootstrap material design javascript. Is there a way to init .bootstrapMaterialDesign() on loaded content / components? Thanks

**Comment by SergeyKhval** [comment]
Try to include [arrive.js](https://github.com/uzairfarooq/arrive)

**Comment by noushad-pp** [comment]
add `$.material.init();` load() call
