### ISSUE TITLE
Arrive.js vs JQuery.on 

### ISSUE THREAD

**Issue by artemijan** [mdbootstrap/mdb-ui-kit#960]
Why are you using Arrive.js to bind ripples on dynamically created DOM elements?
Would it be better with this solution? 

``` js
//this event will be triggered even for dynamically created elements
$(document.body).on("click", ".ripple", function(){
    var el =$(this);
    if(!el.data('ripple_initialized')){
        //init element here before ripple if needed
    }    
    el.ripple(); //do ripple
});
```

**Comment by FezVrasta** [comment]
It was used because we needed to initialize even other kind of elements which don't rely on events.

I hope it answers your question.

**Comment by artemijan** [comment]
i'm just asking because i used your library instead of "angular-material" in my angular application. And the power of angular is "dynamic content" and i'm just worrying about performance. But anyway i got your point and thank you for quick reply

**Comment by FezVrasta** [comment]
If you are using Angular or any other JS framework you should completely forget about the javascript included in this theme and write your own components including the HTML that would be added by our javascript plugin.
