### ISSUE TITLE
difficulty adding pure javascript 

### ISSUE THREAD

**Issue by laterdude** [mdbootstrap/mdb-ui-kit#964]
I doubt this is truly an issue with your guys' wrapping of bootstrap 4 (which is incredible by the way) but I'm having difficulty manipulating elements with native javascript or accessing element properties through javascript the way I'm able to do with plain bootstrap v4. 

As a quick example, say I added this bit of html to your material dashboard demo:

underneath the main tag with a class of 'bmd-layout-content', insert a div with a class of 'hero container-fluid'  in order to insert a background image for a jumbotron-esque banner and have it fade on scroll

with this styling class of hero added to the example.css file:

```
.hero {
    height: 16em;
    width: 100%;
    position: fixed;
    top: 4em;
    background: url("images/basin.jpg") center center no-repeat;
    background-size: cover;
  }
```

and then added this javascript to the example.js file, which otherwise I'm able to do with plain bootstrap v4:

```
var hero = document.getElementsByClassName("hero");
var latestKnownScrollY = 0,
  ticking = false;
function onScroll() {
  latestKnownScrollY = window.scrollY;
  requestTick();
}
function requestTick() {
  if(!ticking) {
    requestAnimationFrame(scrollToFade);
  }
  ticking = true;
}
function scrollToFade() {
  ticking = false;
  var currentScrollY = latestKnownScrollY;
  var startPoint = hero.offsetHeight;
  var alpha = hero.style.opacity;
  hero.style.opacity = 1 - ((currentScrollY + 150) / window.innerHeight);
  console.log(alpha);
 }
window.addEventListener('scroll', onScroll, false);
```

Anyway, if you wouldn't mind taking a look I'd be really grateful. I'd like to be able to use other libraries like velocity.js as well in lieu of jquery because they seem to be a little smoother but I can't seem to get them to work alongside your guys' implementation of bootstrap. Your default styling classes are awesome, I simply can't figure out what I'm missing that prevents me from using pure js code alongside the jquery code in the example.js file that I've been toying with in your demo dashboard. I even tried removing all the jquery in the example.js file dealing with the drawer, but to no avail. 
Take care

**Comment by rosskevin** [comment]
Please submit a test case as requested in the [v4-dev contributing doc](https://github.com/FezVrasta/bootstrap-material-design/blob/v4-dev/CONTRIBUTING.md) if you wish for us to look at it.

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/v4-dev/CONTRIBUTING.md#why-was-my-issue-summarily-closed
