### ISSUE TITLE
V4: Cannot compile using webpack

### ISSUE THREAD

**Issue by thangchung** [mdbootstrap/mdb-ui-kit#965]
Hi all,

I am using webpack for compiling the bootstrap-material-design@v4.0.1, but I always got an exception like `File to import not found or unreadable: bootstrap/scss/_variables`, I wonder why in https://github.com/FezVrasta/bootstrap-material-design/blob/v4.0.1/scss/_variables.scss at line 38 referenced to `bootstrap\scss\variables` node module, but in https://github.com/twbs/bootstrap/tree/v4-dev/scss doesn't' have any folder with named variables there. Is it a bug?

**Comment by rosskevin** [comment]
Our code compiles so it is not a bug.  You are using a different tool and not setting up the library include paths based on the message. In our build setup,  that file is in node_modules.

**Comment by thangchung** [comment]
ahh okay. Got up, sorry for this. I have seen in your gulp file, actually your build at node_modules.

**Comment by jflayhart** [comment]
@thangchung, what is it you did to fix this? I am having same errors. Confused at what my include paths should look like for just one plugin. What does your set up look like that gets this material theme working?
