### ISSUE TITLE
bower install bootstrap-material-design --save returns permission denied

### ISSUE THREAD

**Issue by johhansantana** [mdbootstrap/mdb-ui-kit#968]
I get the following message when trying to `bower install bootstrap-material-design --save`

`Permission denied (publickey). fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists`

![screenshot from 2016-04-06 11 57 52](https://cloud.githubusercontent.com/assets/9933887/14323494/cf603b86-fbee-11e5-9fe6-586dc0df95c2.png)

**Comment by FezVrasta** [comment]
Your errors seems related to some config problem on your machine (and is giving error on `bootstrap#v4-dev`, not on this project)

**Comment by rosskevin** [comment]
Please search first, not only google, but our issue list.  #931
