### ISSUE TITLE
bower installs v4.0.1 by default but should install 0.5.*

### ISSUE THREAD

**Issue by atfornes** [mdbootstrap/mdb-ui-kit#969]
`bower install bootstrap-material-design` installs the bootstrap 4.0.1 version of bootstrap-material-design and not the Bootstrap 3 compatible version. Furthermore, the instructions at [README.md](https://github.com/FezVrasta/bootstrap-material-design/blob/master/README.md) file do not work for that version: `bootstrap-material-design/dist/css` directory does not exist.

I had to force `0.5.x` version at `bower.json`  to make it work.

**Comment by rosskevin** [comment]
Thank you,  I deleted the tags,  those were from test builds.  This should resolve as soon as bower refreshes.
