### ISSUE TITLE
Bower.json missing ripples.js

### ISSUE THREAD

**Issue by phil-hudson** [mdbootstrap/mdb-ui-kit#97]
The bower file is missing Ripple.js in the include.

Could this please be included? (I left a comment where it needs to go).

Cheers,
Phil

**Comment by FezVrasta** [comment]
It is not included because it's optional, it's not needed to make the theme work. Not sure if this is the right way to go...

**Comment by phil-hudson** [comment]
Within the theme I've found that without it, checkboxes do not render correctly - I also think the ripples really make the theme feel complete?

**Comment by FezVrasta** [comment]
Checkboxes do not depend from ripples.js, I know it looks better with ripples.js but the theme works perfectly without it..

**Comment by phil-hudson** [comment]
I'm experiencing that the checkboxes dont display without ripples.js?

**Comment by FezVrasta** [comment]
Weird... Will double check them tomorrow morning.

**Comment by phil-hudson** [comment]
Thanks mate!

**Comment by FezVrasta** [comment]
just checked, checkboxes work great without ripples.js

**Comment by phil-hudson** [comment]
Are you running it with Bower?

**Comment by FezVrasta** [comment]
What do you mean with "running with bower"? I'm using the live preview server of Brackets

**Comment by phil-hudson** [comment]
Sorry that was unclear... I'm using Bower with Grunt. So I'm just trying to identify where the issue is, I was trying to understand how you were testing

Thanks

**Comment by FezVrasta** [comment]
try with:

```
git clone https://github.com/FezVrasta/bootstrap-material-design.git
cd bootstrap-material-design
grunt serve
```

**Comment by FezVrasta** [comment]
I've added ripples.js to the bower file, fixed in the latest develop branch

**Comment by phil-hudson** [comment]
thanks!
