### ISSUE TITLE
v4 input-group implementation

### ISSUE THREAD

**Issue by DzmitryShylovich** [mdbootstrap/mdb-ui-kit#971]
I'm trying to use [input group](http://v4-alpha.getbootstrap.com/components/input-group/#content) with bmd v4 but it looks really awful http://codepen.io/honey_badger/pen/oxEoyX

Are there any plans to implement proper styling for input groups?

**Comment by rosskevin** [comment]
It looks like the latest BS code has changed something, I don't remember them looking like this upon initial implementation though I could have missed them. 
- BMD4 - http://rosskevin.github.io/bootstrap-material-design/components/input-group#content
- BS4- http://v4-alpha.getbootstrap.com/components/input-group/#content

Yes, we will make these look good, but on our timeline (which is essentially when I run into them in our app).  A PR is welcome, just let me know if you are going to work on it.

**Comment by DzmitryShylovich** [comment]
Thx for your response.

>  A PR is welcome, just let me know if you are going to work on it.

No, I'm pretty bad at css :pensive:

**Comment by rosskevin** [comment]
`v4-dev` has the fix, I'll probably publish sometime today with fixes.
