### ISSUE TITLE
V4: grunt not compiling code

### ISSUE THREAD

**Issue by imadulhaque** [mdbootstrap/mdb-ui-kit#972]
Hi,
I downloaded latest code and tried grunt serve but code doesn't compile css file. This is the error I get:

Running "less:material" (less) task

> > NameError: variable @line-height-base is undefined in less_variables.less on line 75, column 37:
> > 74 //*\* Unit-less `line-height` for use in components like buttons.
> > 75 @mdb-input-line-height-base:        @line-height-base; //1.428571429; // 20/14
> > 76 //*\* Computed "line-height" (`font-size` \* `line-height`) for use with `margin`, `padding`, etc.
> > Warning: Error compiling less/bootstrap-material-design.less Used --force, continuing.
> > Any ideas what should be the correct fix for this?

Thanks,
Imad.

**Comment by rosskevin** [comment]
It seems pretty clear that you didn't checkout the `v4-dev` branch, because it has neither `grunt` nor `less`.

Here are building instructions:
http://rosskevin.github.io/bootstrap-material-design/getting-started/building/
