### ISSUE TITLE
v3: Increase font-weight of alerts

### ISSUE THREAD

**Issue by simonsmiley** [mdbootstrap/mdb-ui-kit#973]
Alerts are almost not readable in v3. I'm not sure how it looks in v4

**Comment by rosskevin** [comment]
Please submit the requested codepen test case form our template and we can review.

**Comment by simonsmiley** [comment]
Sure. Here is a link http://codepen.io/anon/pen/QNQXXr

**Comment by rosskevin** [comment]
I agree, @FezVrasta you think bumping to 400 is good?

**Comment by FezVrasta** [comment]
I can easily read it.. By the way if you think is better 400, for me is okay.

**Comment by rosskevin** [comment]
@simonsmiley I'm going to leave this as-is, I checked a couple of devices and asked a few people and the majority prefer the current weight.  Luckily, this isn't a big deal for you to customize.  Thanks for submitting the test case with us.
