### ISSUE TITLE
v4 form-inline button vertical alignment

### ISSUE THREAD

**Issue by simonsmiley** [mdbootstrap/mdb-ui-kit#974]
In http://rosskevin.github.io/bootstrap-material-design/material-design/forms/#visible-labels
the button is not aligned properly. It should be wrapped in a `<div class="form-group">`

**Comment by rosskevin** [comment]
The _workaround_ right now would be to wrap it in the `form-group`, which would provide the top margin (only used here to provide room for floating labels).  It should not _require_ a `form-group` to look good.

The right solution should probably be to align this off the bottom when inside `form-inline`, but I'm open to ideas.

**Comment by rosskevin** [comment]
I didn't see a better way, not an easy one....so I added the surrounding group.
