### ISSUE TITLE
Input floating label not floating on login form auto completion

### ISSUE THREAD

**Issue by om-yo** [mdbootstrap/mdb-ui-kit#976]
Hello i have a  login form. The password label not floating when the browser using password manager auto completion. Here's the preview. Thanks, i really love this project! :smile: 
![untitled](https://cloud.githubusercontent.com/assets/11387168/14581644/229d108c-041c-11e6-923b-aaeae81e90a9.png)

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#tldr-create-a-test-case-using-this-codepen-template-when-submitting-an-issue

**Comment by rosskevin** [comment]
Also,  which browser and which login manager?

**Comment by FezVrasta** [comment]
Seems like the default chrome keychain

**Comment by FezVrasta** [comment]
There are several solutions 
http://stackoverflow.com/questions/11708092/detecting-browser-autofill

I wonder why mine is not working here

**Comment by om-yo** [comment]
Yeah that's right from Chrome Browser

**Comment by YamiOdymel** [comment]
Try to disabled the auto-fill function by adding this attribute to the password input:

`autocomplete="new-password"`

**Comment by cannobbio** [comment]
Until there's an actual "fix" I'm doing this in my login forms:

JS:

``` javascript
// Browser password autofill floating label fix
$(window).load(function() {
  setTimeout(function(){
    var $pwdInput = $('input[type="password"]:-webkit-autofill');
    $pwdInput.closest('.form-group').removeClass('is-empty');
  }, 500);
});
```

This is just a half a sec timeout that removes the .is-empty class after the page has loaded.

CSS:

``` javascript
input[type="password"]:-webkit-autofill {
  position: relative;
}
```

This hides the label behind the "yellow" input until it animates.

**Comment by FreekingDean** [comment]
Is there a reason this is closed? I am having the same issue, would like to know if this is my own implementation issues or if it is an issue in bootstrap-material-design

**Comment by om-yo** [comment]
no its not ur implementation issues, this bootstrap-material-design issue

On Thu, Jul 14, 2016 at 7:35 AM, Dean Galvin notifications@github.com
wrote:

> Is there a reason this is closed? I am having the same issue, would like
> to know if this is my own implementation issues or if it is an issue in
> bootstrap-material-design
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/FezVrasta/bootstrap-material-design/issues/976#issuecomment-232525813,
> or mute the thread
> https://github.com/notifications/unsubscribe/AK3BIMy-xM6cFzBLKhDlxypycpCbX-Omks5qVYRrgaJpZM4II7-b
> .

## 

Regards,
Yohanda
Software Engineer

Wisma 77
Jln. S. Parman Kav. 77
Jakarta Barat 11410
HP        \* : *+6285719363149
Email     : yohanda@tokopedia.com andri.dwi@tokopedia.com
Website : www.tokopedia.com

**Comment by ShankzPatil** [comment]
working... is parent div "md-input-container"

```
$(document).ready(function () {
 setTimeout(function () {
var $pwdInput = $('input[type="password"]:-webkit-autofill');
$pwdInput.closest("md-input-container").addClass('md-input-has-value');
}, 500);
});
```

**Comment by pmayur25** [comment]
I used Material design Bootstrap (MDB)
below code is working for me

$(document).ready(function () {
setTimeout(function () {
var $Input = $('input:-webkit-autofill');
$Input.next("label").addClass('active');
}, 200);
});
