### ISSUE TITLE
Navbar is not working properly

### ISSUE THREAD

**Issue by ashishrevar** [mdbootstrap/mdb-ui-kit#977]
In my head section, I've added this way. I am not getting even a single Navbar.

```
<head>
    <title>Materialize Demo</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/bootstrap-material-design.css">
    <link rel="stylesheet" href="css/bootstrap-material-design.css.map">
    <link rel="stylesheet" href="css/ripples.css">
    <link rel="stylesheet" href="css/ripples.css.map">
![Uploading Material.png…]()

    <script src="js/material.js"></script>
    <script src="js/material.min.js.map"></script>
    <script src="js/ripples.js"></script>
    <script src="js/ripples.min.js.map"></script>
</head>
```

Please refer link for screenshot.
[Image](http://i63.tinypic.com/15ojw4i.png)

**Comment by rosskevin** [comment]
Next time please submit a codepen with our template or this will be closed. 

https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#tldr-create-a-test-case-using-this-codepen-template-when-submitting-an-issue

You didn't include the bootstrap css or js.
