### ISSUE TITLE
full icon support for sass

### ISSUE THREAD

**Issue by bcm** [mdbootstrap/mdb-ui-kit#98]
is there a plan for supporting the full icon support in the sass source? if not then I might be able to find some time to make it happen.

**Comment by FezVrasta** [comment]
the "less" for the icons is just a .css with the extension changed, everyone can do the same thing for sass I guess. @shockwork is the maintainer of the SASS version but everyone is welcome to send a PR

**Comment by TransitoryBliss** [comment]
@bcm feel free to submit a Pull Request. I've got a big push coming up but feel free to!

**Comment by bcm** [comment]
> the "less" for the icons is just a .css with the extension changed, everyone can do the same thing for sass I guess.

that's exactly what I did to get things working locally. I will submit a pull request soon. thanks!

**Comment by FezVrasta** [comment]
@showckwork are you still on this project or may I consider removing the sass support due to lack of support?

**Comment by TransitoryBliss** [comment]
@FezVrasta I'm back! I've been extremely busy with renovation and stuff.... I will look into this asap!

**Comment by TransitoryBliss** [comment]
@bcm Did you get this working? Else I will do it myself

**Comment by bcm** [comment]
I wound up not using the theme for my project, but it was as simple as copying the less file.

**Comment by FezVrasta** [comment]
I've just included this file to the material.scss, I've really 0 experience with SASS so I don't know if I did it correctly. @shockwork and @bcm may you check 43a9f4f4b4bb1ef4b51c091de152e1f0e092b9ad?
