### ISSUE TITLE
form validation

### ISSUE THREAD

**Issue by salvadoresc** [mdbootstrap/mdb-ui-kit#981]
i using your library with angularjs and i made  this input:

`<input name="mailb" id="mailb" class="form-control floating-label" type="email" placeholder="Correo electrónico" ng-model="mailb">`

and i try to validate this way:

<h1>correo b es valido: {{casob.mailb.$valid}}</h1>

the message starts true and never change, but if i remove the class attribute, it works fine but obviously it loss all the looks and the effects, what should I do?

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#why-was-my-issue-summarily-closed
