### ISSUE TITLE
lines under the form input is not working

### ISSUE THREAD

**Issue by ravipatel181229** [mdbootstrap/mdb-ui-kit#985]
Lines animation in textbox and other form inputs is not working in firefox.

![image](https://cloud.githubusercontent.com/assets/18737882/14915746/d9dad142-0e32-11e6-8d98-0a082e50c2ae.png)

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#tldr-create-a-test-case-using-this-codepen-template-when-submitting-an-issue

**Comment by ravipatel181229** [comment]
not needed. coz its view problem and its browser specific css problem..
