### ISSUE TITLE
windows7 safari browser elements are not displaying correctly

### ISSUE THREAD

**Issue by apusaha727** [mdbootstrap/mdb-ui-kit#992]
Hi there,

There is display issue in windows 7 Safari browser.

"Windows7 safari browser elements are not displaying correctly"

Please check this issue.

Best Regards,
Apu Saha

**Comment by rosskevin** [comment]
https://github.com/FezVrasta/bootstrap-material-design/blob/master/CONTRIBUTING.md#why-was-my-issue-summarily-closed
