### ISSUE TITLE
v4.0.1 preview not available via Bower

### ISSUE THREAD

**Issue by nwalters512** [mdbootstrap/mdb-ui-kit#993]
I'm following the instructions [her](http://rosskevin.github.io/bootstrap-material-design/getting-started/download/#bower) to try and get up and running with v4 using Bower. However, when I run `bower install bootstrap-material-design#v4.0.1`, I get an error that says

```
No tag found that was able to satisfy v4.0.1
```

Was this version unpublished? I know v4 isn't official yet, but the `v4.0.1` preview is [still available on `npm`](https://www.npmjs.com/package/bootstrap-material-design). I'd just really like to be able to use it with Bower.

**Comment by rosskevin** [comment]
On that very same page, in bold lettering with a red callout, it says:

> Heads up! Use the repository branch!
> With the pace of current changes, any published package would be out of date almost every day.
> 
> For the current time, please use the v4-dev branch for all package managers including bower and npm by pointing to FezVrasta/bootstrap-material-design#v4-dev.

The npm package publish was a mistake during testing of the publish process.  Soon enough we will start publishing something, but we would like for BS4 to be out of alpha at least.

**Comment by nwalters512** [comment]
That's embarrassing on my behalf. Thanks for pointing that out.

**Comment by rosskevin** [comment]
I'll check with npmjs and see if we can't get that pulled so it is more obvious.  I pulled the github tag so bower refreshed and removed it.

**Comment by stealthybox** [comment]
Should we open another issue for the npm module?

Telling users to point to an actively changing dev branch isn't a solution to the problem of existing dependencies that were created while the package was published.

v4.0.1 was out there, and then the tag was yanked improperly.

**Comment by rosskevin** [comment]
4.0.1 was out accidently there and "yanked properly" if there is such a thing, and no, you should not create an issue for npm.  If we aren't comfortable releasing for bower, why would we be for npm?

We are creating builds off the Bootstrap master, so no, we are not at a place to produce a release.  If you are not comfortable directly using branches, then the v4 is **not for you**.  It should be viewed as _unstable_, even though it's been stable so far.  There are zero guarantees.
