### ISSUE TITLE
[Question] Use some kind of spinner.

### ISSUE THREAD

**Issue by nhomar** [mdbootstrap/mdb-ui-kit#994]
Hello.

This is more a question than an issue:

I need an spinner like this one: http://codepen.io/mrrocks/pen/EiplA I found pure examples outside, but it has been a little difficult implement directly using sort kind of helper.

Do you have an idea what should be the steps to do that with this incredible tool?

I need some direction to achieve something like:

```
<i class="material-icon" data="icon-spin">spinner</i>
```

If you give me some guidance where I should look I can make a proper PR.

Fontawesome has one option but I want use a proper material implementation.

Thanks in advance.

**Comment by nhomar** [comment]
ping

**Comment by FezVrasta** [comment]
What is the problem with the example you have provided?

**Comment by nhomar** [comment]
Hello.

Thanks for ask.

In fontawesome we have an special class called spin:

``` html
<i icon="fa fa-spinner spin"></i>
```

And the icon simply started to spin properly.

I want to do the same with the material-icons on this project to have a proper **spinner icon** but I do not knwo how to achieve that (that's when my questions comes up).

For example I want to declare an icon like:

```
<i class="material-icon" data="icon-spin">spinner</i>
```

And it behave like this [snnipet](http://codepen.io/mrrocks/pen/EiplA).

I tried to use this example into the bootstrap-material usage and it did not work I supose the manage of the <svg> is not properly done (but I am supposing) that why I want rceate some kind of helper on this lib to offer the spin "alá" fontawesome out of the box iwth a proper PR obviously.

And I need help you can enlight me, how should I do that conceptually (you can list for me some steps) and I can do the job or you can tell me "we have it ... and it is ``__here___`"

Do I explain myself better?

Sorry for my bad english BTW.

**Comment by rosskevin** [comment]
If you would like to submit a PR, we would accept it, otherwise we aren't adding scope for v3.
