### ISSUE TITLE
gulp build fails on line 40 of bower_components/bootstrap-material-design/scss/_variables.scss

### ISSUE THREAD

**Issue by lkhedlund** [mdbootstrap/mdb-ui-kit#995]
#### Shell Output

``` shell
[14:46:24] Starting 'styles'...
bower_components\bootstrap-material-design\scss\_variables.scss
Error: File to import not found or unreadable: bootstrap/scss/variables
        on line 40 of bower_components/bootstrap-material-design/scss/_variables.scss
>> @import "bootstrap/scss/variables"; // from bootstrap node_module
   ^
```
#### Summary
1. Ran `bower install FezVrasta/bootstrap-material-design#
   v4-dev --save` 
2. The install succeeds and the bower.json file is updated properly. 
3. gulpfile fails to compile and throws the above error.

Here is a link to the gulpfile: https://gist.github.com/lkhedlund/0d4aec1cd92006d402ab53eeb89712d2
#### Additional Information

We're using [Wordpress Sage](https://roots.io/sage/) and the build is failing on a clean install.

**Comment by rosskevin** [comment]
Some info for building our project: http://rosskevin.github.io/bootstrap-material-design/getting-started/building/

You are responsible for setting up your own tools for your project, this isn't a bug.

You will need to add the include/import paths depending on your toolchain.  We use gulp-pipeline which does it automatically from node_modules.  

As a note, you can also checkout `.travis.yml` to see how a project builds from scratch.  Our build is succeeding our travis would let us know.

**Comment by lkhedlund** [comment]
Thanks @rosskevin. I'll let Sage know about the problem on their end, since it's part of their standard package right now and will likely cause problems for multiple users.
