### ISSUE TITLE
No docs for opening and closing modals in angular.

### ISSUE THREAD

**Issue by djoks** [mdbootstrap/mdb-ui-kit#999]
I can't seem to find any docs on how to use a modal dailog, be it alert or confirm or custom modal.

**Comment by FezVrasta** [comment]
Follow the Bootstrap doc

**Comment by tilwinjoy** [comment]
@djoks  Check [angular bootstrap documentation](https://angular-ui.github.io/bootstrap/)  for docs to use [model](https://angular-ui.github.io/bootstrap/#/modal) and other bootstrap components with angular. Here's a [demo](http://tilwinjoy.github.io/angular-bootstrap-material/#/modal) using it with bootstrap modal design.
